### ISSUE TITLE
WPK remote upgrade failing

### ISSUE THREAD

**Issue by LucioDonda** [wazuh/wazuh#24926] opened 2024-07-24 21:14 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-alpha3 | Wazuh wpk upgrade | Agent | Packages | Several |

After Testing Release 4.9.0 - Alpha 3 - WPK upgrade tests [#24876](https://github.com/wazuh/wazuh/issues/24876)
We found that the upgrade script didn't finish till the timeout is reached.

* Some cases seems like the aget-upgrade script doesn't get the ack (or any response) from the agent. But the process in the destination was performed correctly.
* Happening with both success or failed wpk's.
* There where seen some cases where after the force failed scenario didn't leave the directries as it should. In this cases, as the previous test checked, the agent's directory should only be changed by the tar received for the upgrade process.
* It's happening in macos, linux and windows.

Additional information
* For wpk creation we built [Linux](https://github.com/wazuh/wazuh-agent-packages/actions/workflows/packages-build-linux-agent-amd.yml), [WIndows](https://github.com/wazuh/wazuh-agent-packages/actions/workflows/packages-build-windows-agent.yml) and [macos](https://github.com/wazuh/wazuh-agent-packages/actions/workflows/packages-build-macos-agent.yml) agents here.
and used the s3 name for [wpk's](https://github.com/wazuh/wazuh-agent-packages/actions/workflows/packages-build-wpk.yml) 
* Assets used: 
  - [Linux deb](https://s3.us-west-1.amazonaws.com/packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/wazuh-agent_4.9.0-0_amd64_82fc581.deb.wpk) 
  - [Linux rpm](https://s3.us-west-1.amazonaws.com/packages-dev.internal.wazuh.com/development/wazuh/4.x/main/packages/wazuh-agent_4.9.0-0_x86_64_82fc581.rpm.wpk) 

Example of the error:

```shell
[root@ip-172-31-41-149 ec2-user]# time /var/ossec/bin/agent_upgrade -a 002  -F -f /home/ec2-user/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk 
Upgrading...
Failed upgrades:
	Agent 002 status: Timeout reached while waiting for the response from the agent, check the result manually on the agent for more information

real	15m6.907s
user	0m3.589s
sys	0m0.554s

``` 

upgrade.log  with both cases in the same log:

```shell
vagrant@macos-13 Downloads % cat upgrade.log 
2024/07/24 13:10:13 - Upgrade started.
2024/07/24 13:10:13 - Checking execution path.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2024/07/24 13:10:33 - Installation result = 0
2024/07/24 13:10:33 - Checking for Wazuh Agent control script.
2024/07/24 13:10:33 - Checking if Wazuh Agent is running.
2024/07/24 13:10:33 - Wazuh Agent is already running.
2024/07/24 13:10:34 - Waiting connection... Remaining attempts: 30.
2024/07/24 13:10:35 - Status = connected. 
2024/07/24 13:10:35 - Upgrade failed...
2024/07/24 13:40:02 - Upgrade started.
2024/07/24 13:40:02 - Checking execution path.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2024/07/24 13:40:20 - Installation result = 0
2024/07/24 13:40:20 - Checking for Wazuh Agent control script.
2024/07/24 13:40:20 - Checking if Wazuh Agent is running.
2024/07/24 13:40:20 - Wazuh Agent is already running.
2024/07/24 13:40:21 - Waiting connection... Remaining attempts: 30.
2024/07/24 13:40:22 - Status = connected. 
2024/07/24 13:40:23 - Connected to manager.
2024/07/24 13:40:23 - Upgrade finished successfully.

```

**Comment by vikman90** [comment] 2024-07-25 10:22
@cborla according to the _upgrade.log_ file, the installation times are 22 seconds and 21 seconds, respectively. Which stage is taking ~15 minutes?

Please confirm that you're adding this setting to your manager's _ossec.conf_:
```xml
<agent-ugrade>
  <chunk_size>32078</chunk_size>
</agent_upgrade>
```

If this is not the case, we will need to trace back the changes, and locate the cause of this problem:

- https://github.com/wazuh/wazuh/issues/21152

**Comment by TomasTurina** [comment] 2024-07-25 15:06
@cborla @LucioDonda This is expected behavior, since after the development of #21152 the way Wazuh behaves after a failed upgrade changed. The rollback mechanism has been removed as you can see in this PR #23188. Keep this in mind for future WPK testing. Closing as not planned.

**Comment by LucioDonda** [comment] 2024-07-25 16:37
This issue should be reopened only for the centos8 case.
OS:

```shell
[root@vm-centos8 vagrant]# cat /etc/*release
CentOS Linux release 8.3.2011
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
CentOS Linux release 8.3.2011
CentOS Linux release 8.3.2011
``` 

[wpk used](https://packages-dev.wazuh.com/pre-release/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk)

From agent 4.9.0 .

More info [here](https://github.com/wazuh/wazuh/issues/24876#issuecomment-2245582012).

**Comment by LucioDonda** [comment] 2024-07-25 16:37
This issue should be reopened only for the centos8 case.
OS:

```shell
[root@vm-centos8 vagrant]# cat /etc/*release
CentOS Linux release 8.3.2011
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
CentOS Linux release 8.3.2011
CentOS Linux release 8.3.2011
``` 

[wpk used](https://packages-dev.wazuh.com/pre-release/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk)

From agent 4.9.0 .

More info [here](https://github.com/wazuh/wazuh/issues/24876#issuecomment-2245582012).

**Closed** 2024-07-30 20:43 UTC
Labels: type/bug, module/upgrade/wpk, module/agent, module/upgrade, level/task
