### ISSUE TITLE
Handle Leak in FIM in Realtime Mode on Windows

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#26741] opened 2024-11-06 12:14 UTC
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.7.3 | FIM | Agent| Windows |

## Description

A handle leak has been identified in the File Integrity Monitoring (FIM) module on Windows when configuring individual files instead of directories, using `realtime` mode. In this scenario, the process opens a high number of redundant handles for a limited set of files, leading to excessive handle consumption while the process's private memory remains low. This issue could impact system-level memory and performance due to the high handle count.

## Steps to Reproduce

1. **Set up FIM configuration**:
   - Configure FIM to monitor individual files, rather than directories, in the `<directories>` block.
   - Use `realtime` mode for this configuration.
   - Add a significant number of individual files to the FIM configuration (e.g., hundreds or thousands).
2. **Run the agent**:
   - Start the Wazuh agent with the configured FIM settings.
   - Allow the agent to run for a few scans.
3. **Observe handle count**:
   - Using a tool like `handle.exe` from Sysinternals, inspect the number of open handles associated with the `wazuh-agent.exe` process.

### Sample configuration

<details><summary>ossec.conf</summary>

```xml
<ossec_config>
  <syscheck>
    <disabled>no</disabled>
    <frequency>1</frequency>

    <directories realtime="yes">C:\autoexec.bat</directories>
    <directories realtime="yes">C:\boot.ini</directories>
    <directories realtime="yes">C:\config.sys</directories>
    <directories realtime="yes">C:\Windows\system.ini</directories>
    <directories realtime="yes">C:\Windows\win.ini</directories>
    <directories realtime="yes">C:\Windows\regedit.exe</directories>
    <directories realtime="yes">C:\Windows\System32\userinit.exe</directories>
    <directories realtime="yes">C:\Windows\explorer.exe</directories>

    <windows_audit_interval>60</windows_audit_interval>
    <process_priority>10</process_priority>
    <max_eps>50</max_eps>

    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>
</ossec_config>
```

</details>

#### Helper

This Powershell tool will help you to generate a large configuration according to your current directory:

```PowerShell
Get-ChildItem -Path . -File -Recurse | ForEach-Object { "<directories realtime=`"yes`">{0}</directories>" -f $_.FullName }
```

## Expected Behavior

FIM should not create redundant handles for monitored files. Ideally, configuring individual files in real-time mode should not lead to excessive handle usage and should maintain an efficient memory footprint.

In fact, FIM should ignore individual file monitoring, at less in real-time mode.

**Comment by jotacarma90** [comment] 2024-11-14 17:16
# Analysis

## Handleleak explanation
The code where FIM creates the handles for realtime monitoring is this:
https://github.com/wazuh/wazuh/blob/509f7b154638a9eb57b86214aca1773c53de33ff/src/syscheckd/src/run_realtime.c#L674-L697

For each path configured with realtime, we will open a handle and then in line 691, realtime_win32read, we will try to use the subscription function `ReadDirectoryChangesW`, this is the function that prevents us from configuring files directly.
In the case that the path is a file, at that point we will find the error and the mdebug1 `“(6323): Unable to set 'ReadDirectoryChangesW' for directory”`. The problem is that, although we are releasing the reserved structure, we are not closing the handle, which causes the handleleak.

To solve it, we have analyzed the following options:
- During the process of reading the configuration, prevent the user to set in the tag directories, a file with the realtime mode. Either by warning or by modifying the configuration. It would be necessary to control situations of configuration changes, for example when whodata cannot start, and passes all its configuration to realtime. Solution a bit convoluted. Not recommended.
- In the same line where we detect the error, we can verify that indeed the path is not a directory. At that moment we can give a warning to the user, and modify the configuration mode of that path from realtime to schedule. We have concluded that this is the easiest option to implement and should result in the fewest errors in the code.
- Trying to make the files work for realtime mode. This is a very inefficient option. We have considered, for example, trying to monitor the whole directory containing the configured file (and at this point trying to filter the information only for that specific file). But several problems may arise, for example the path '`C:\testfile`', which would leave the whole disk C monitored. Not recommended.


# Conclusion
We have added a CloseHandler that avoids the handleleak, also we have added a warning that warns the user and after that we change the mode of that path, from realtime to schedule. With this logs and warnings:

Configuring:

Logs:
```
2024/11/14 09:15:13 wazuh-agent[6132] run_realtime.c:693 at realtime_adddir(): DEBUG: (6323): Unable to set 'ReadDirectoryChangesW' for directory: 'c:\test\new text document.txt'. Error(87): 'The parameter is incorrect.'
2024/11/14 09:15:13 wazuh-agent[6132] run_realtime.c:698 at realtime_adddir(): WARNING: (6957): Realtime mode only supports directories, not files. Switching to scheduled mode. File: 'c:\test\new text document.txt'
```

**Closed** 2024-11-18 15:47 UTC
Labels: type/bug, module/fim, module/fim/realtime, level/task
