### ISSUE TITLE
Regex "\<" not working properly in the web XML editor

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#13632] opened 2022-05-30 20:51 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.6 | Ruleset | Manager | OVA | Centos7 |

Hi,

Creating a custom decoder from the web interface, I noticed that the XML editor doesn't recognize `\<` inside a regex as an escaped character, and takes it as the beginning of a new XML element. This shows an error on the left side:
![image](https://user-images.githubusercontent.com/42900763/171057737-150d7117-fba4-4015-bf17-765cfc71efee.png)
![image](https://user-images.githubusercontent.com/42900763/171057744-623832fa-6554-4745-9c76-fb7daea57df8.png)

And also prevents the user from saving the changes:
![image](https://user-images.githubusercontent.com/42900763/171057747-cabefb7b-1e0a-4d37-b602-0f261d226daa.png)

If those same changes are performed from the terminal, no error is shown and the manager works properly.

The `<` character should be escaped as `\<` according to this [documentation](url):
![image](https://user-images.githubusercontent.com/42900763/171057762-645e7f50-a08a-4242-a8b0-e5ed84224070.png)

There are also default decoders that include that expression (for example `sonicwall` in `0295-sonicwall_decoders.xml`) and if there are inspected from the web interface, shows the error too:
![image](https://user-images.githubusercontent.com/42900763/171057925-8e2289d5-21be-4fe2-93d5-7a1584eb7f58.png)

I've tested in v4.3.1 and the issue is still there.

Best regards,

Nicolás Guevara.

**Comment by mcarmona99** [comment] 2022-05-31 06:38
Hi @Tostti,

This is an already known bug discovered in Wazuh 4.1.0 and reported in https://github.com/wazuh/wazuh-kibana-app/issues/3504. Use that issue to track the development of the solution to the problem.

Right now, and until the issue is solved, you cannot add the `\<` character to a rule or decoder via the Wazuh UI or API. The only way to do it, as you said, is editing the rules or decoders file from the terminal.

I am closing this issue as it is a duplicate of https://github.com/wazuh/wazuh-kibana-app/issues/3504. 

Sorry for the inconvenience caused and thanks for contributing to the Wazuh community.

**Closed by mcarmona99** 2022-05-31 06:38 UTC
Labels: community
