### ISSUE TITLE
Investigate possible condition error in test_parser of the AWS integration tests

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh#19730] opened 2023-10-18 21:20 UTC
| Affected integration |
|---|
| AWS|

## Description

During the test of [Release 4.7.0 - Alpha 1 - External Integration Modules](https://github.com/wazuh/wazuh/issues/19698)  specifically the AWS module, it was found that the test integration failed due to a TimeoutError when performing the `test_parser` tests.

```
>                   raise TimeoutError(error_message)
E                   TimeoutError: The AWS module did not show the expected message about invalid value
================================================== short test summary info ==================================================
FAILED test_parser.py::test_invalid_values_in_bucket[parser_invalid_name_in_bucket] - TimeoutError: The AWS module did not...
========================================= 1 failed, 25 passed in 244.35s (0:04:04) ==========================================
```

But after debugging it was found that it only fails when the entire test module is executed. If the test causing the timeout is executed alone the fail passes without errors.

```
root@vagrant:/wazuh-qa/tests/integration/test_aws# pytest --disable-warnings -k test_invalid_values_in_bucket test_parser.py
============================================================ test session starts ============================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /wazuh-qa/tests/integration, configfile: pytest.ini
plugins: metadata-3.0.0, testinfra-5.0.0, html-3.1.1
collected 26 items / 19 deselected / 7 selected

test_parser.py .......                                                                                                                [100%]

================================================ 7 passed, 19 deselected in 84.23s (0:01:24) ================================================
```

This issue tends to investigate a possible condition error on the configuration of the module that makes the entire module to fail when performing the test `test_invalid_values_in_bucket`. 

## Tasks
- [x] Test in a manager.
- [x] Test in an agent.
- [x] Unit tests without failures. Updated if there are any relevant changes.
- [x] Integration tests without failures. Updated if there are any relevant changes.
- [x] Update the documentation if necessary.
- [x] Add entry to the changelog if necessary.

**Comment by javiersanchz** [comment] 2023-11-21 16:32
## UPDATE 

- Due to ongoing work to refactor AWS integration tests at https://github.com/wazuh/wazuh/issues/19052, it has been decided to block this issue.

- Once the refactoring is finished, any related issues will be addressed

**Comment by javiersanchz** [comment] 2024-03-15 14:42
## Update

- The test execution was checked to verify the described issue, which has been resolved as all tests pass successfully.
- Branch `4.8.2` was used for its release.
- Its execution was tested both from a manager and from an agent.

## Test 

### Manager

<details>
<summary>Wazuh Info</summary>

```console
root@vagrant:~# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.2"
WAZUH_REVISION="40820"
WAZUH_TYPE="server"
```

</details>

<details>
<summary>Test</summary>

```console
root@vagrant:~/wazuh-qa/tests/integration/test_aws# python3 -m pytest --disable-warnings -k test_invalid_values_in_bucket test_parser.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /root/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.1.1, html-3.1.1
collected 26 items / 19 deselected / 7 selected                                                                                                                                                            

test_parser.py .......                                                                                                                                                                               [100%]

=============================================================================== 7 passed, 19 deselected in 75.82s (0:01:15) ================================================================================
```

```console
root@vagrant:~/wazuh-qa/tests/integration/test_aws# python3 -m pytest --disable-warnings test_parser.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /root/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.1.1, html-3.1.1
collected 26 items                                                                                                                                                                                         

test_parser.py ..........................                                                                                                                                                            [100%]

====================================================================================== 26 passed in 229.89s (0:03:49) =====================================================================================
```
</details>

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### Agent

<details>
<summary>Wazuh Info</summary>

```console
root@vagrant:~# /var/ossec/bin/wazuh-control info
WAZUH_VERSION="v4.8.2"
WAZUH_REVISION="40820"
WAZUH_TYPE="agent"
```

</details>

<details>
<summary>Test</summary>

```console
root@vagrant:~/wazuh-qa/tests/integration/test_aws# python3 -m pytest --disable-warnings -k test_invalid_values_in_bucket test_parser.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /root/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.1.1, html-3.1.1
collected 26 items / 19 deselected / 7 selected                                                                                                                                                            

test_parser.py .......                                                                                                                                                                               [100%]

=============================================================================== 7 passed, 19 deselected in 75.82s (0:01:15) ================================================================================
```

```console
root@vagrant:~/wazuh-qa/tests/integration/test_aws# python3 -m pytest --disable-warnings test_parser.py
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.4.0
rootdir: /root/wazuh-qa/tests/integration, configfile: pytest.ini
plugins: testinfra-5.0.0, metadata-3.1.1, html-3.1.1
collected 26 items                                                                                                                                                                                         

test_parser.py ..........................                                                                                                                                                            [100%]

====================================================================================== 26 passed in 229.89s (0:03:49) =====================================================================================
```
</details>

**Comment by GGP1** [comment] 2024-03-21 12:27
## Review

The error couldn't be reproduced after the module refactor and it's likely that it has been resolved with those changes. I think we should keep an eye on these tests to make sure that they pass in the future. The conclusion looks good to me.

**Comment by Selutario** [comment] 2024-03-22 10:12
According to the issue description, the error was happening only when all tests were run:

> But after debugging it was found that it only fails when the entire test module is executed. If the test causing the timeout is executed alone the fail passes without errors.

@javiersanchz, please try running all tests instead of only `test_parser.py`. In any case, if it still fails, we should probably block this issue again until finishing the refactor and migration:
- https://github.com/wazuh/wazuh/issues/17788

**Comment by javiersanchz** [comment] 2024-03-26 13:38
## Update 

- The `test_aws` set was attempted to verify the error case mentioned in the issue.
- Most tests result in Error or Failure, so this issue will be marked as blocked until the AWS refactoring and migration are completed, as mentioned [here](https://github.com/wazuh/wazuh/issues/19730#issuecomment-2014764383).

- https://github.com/wazuh/wazuh/issues/17788

**Comment by Selutario** [comment] 2024-05-28 16:56
This is no longer happening in the results seen in https://github.com/wazuh/wazuh/issues/17788:
- https://github.com/wazuh/wazuh/actions/runs/9269028458/job/25498966467

**Closed by Selutario** 2024-05-28 16:56 UTC
Labels: type/test, module/cloud monitoring, level/task, qa_known
