### ISSUE TITLE
Wazuh-db showing agent-groups information after deleting all agents and groups

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15965] opened 2023-01-18 12:47 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.4.0-beta1 | Wazuh-db | Manager | - | Centos7 |

## Description

A problem has been found during the workload testing of 4.4-beta1 (https://github.com/wazuh/wazuh/issues/15938#issuecomment-1385106895). 

In an environment like this:
- 26 managers (25 workers, 1 master)
- 50k agents.
- Agents connecting only to workers.

There is a cluster task for synchronizing agent-groups. In certain situations, the master has to send the complete `agent-groups` information to the workers. As we can see here, it takes 26 chunks (~65KB each):
```
2023/01/16 13:49:13 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] Starting.
2023/01/16 13:49:16 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] 26/26 chunks updated in wazuh-db in 3.032s.
2023/01/16 13:49:16 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] Finished in 3.050s. Updated 26 chunks.
```

However, after deleting all groups and agents via API at 13:54:01:
```
2023/01/16 13:54:01 INFO: wazuh 172.31.62.248 "DELETE /groups" with parameters {"groups_list": "all"} and body {} done in 3.239s: 200
2023/01/16 13:54:11 ERROR: Timeout executing API request
2023/01/16 13:54:11 INFO: wazuh 172.31.62.248 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.047s: 500
```

Logs showing that the worker has received 26 chunks of agent-group information from the master can still be found:
```
2023/01/16 14:05:15 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] Starting.
2023/01/16 14:05:16 DEBUG: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] 26/26 chunks updated in wazuh-db in 1.895s.
2023/01/16 14:05:16 INFO: [Worker CLUSTER-Workload_benchmarks_metrics_B235_manager_3] [Agent-groups recv full] Finished in 1.913s. Updated 26 chunks. 
```

That means that the master's db could still contain information for groups and agents that no longer exist. 

---- 
Full logs: [artifacts.zip](https://github.com/wazuh/wazuh/files/10432608/artifacts.zip)

**Comment by Nicogp** [comment] 2023-01-25 02:01
I was able to reproduce the error by removing all agents
```
2023/01/24 03:37:58 DEBUG: [Worker worker-node] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7e55ad0a0a69840cf710c1531edf9064f06b60ed | Master checksum: f55fa2110b1d35816c673a889d996d3f40573529.
2023/01/24 03:37:58 INFO: [Worker worker-node] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2023/01/24 03:37:58 INFO: [Worker worker-node] [Agent-groups recv] Finished in 0.007s. Updated 1 chunks.
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'new_str''
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'str_upd''
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'syn_g_m_w_c''
2023/01/24 03:37:59 INFO: [Worker worker-node] [Agent-groups recv full] Starting.
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Agent-groups recv full] 6/6 chunks updated in wazuh-db in 0.223s.
2023/01/24 03:37:59 INFO: [Worker worker-node] [Agent-groups recv full] Finished in 0.228s. Updated 6 chunks.
```
Environment:

- 1 master
- 1 worker
- 2 groups are created
- 50k agents are registered and the two groups are assigned to all agents

The key to reproduce it is, after deleting groups and agents immediately restart the master, this is seen in the API log:
```
2023/01/16 13:54:11 INFO: wazuh 172.31.62.248 "DELETE /agents" with parameters {"agents_list": "all", "status": "all", "older_than": "0s"} and body {} done in 10.047s: 500
2023/01/16 13:54:21 INFO: wazuh 172.31.62.248 "DELETE /security/users" with parameters {"user_ids": "all"} and body {} done in 9.700s: 200
2023/01/16 13:54:21 INFO: wazuh 172.31.62.248 "DELETE /security/roles" with parameters {"role_ids": "all"} and body {} done in 0.607s: 200
2023/01/16 13:54:22 INFO: wazuh 172.31.62.248 "DELETE /security/policies" with parameters {"policy_ids": "all"} and body {} done in 0.581s: 200
2023/01/16 13:54:22 INFO: wazuh 172.31.62.248 "DELETE /security/rules" with parameters {"rule_ids": "all"} and body {} done in 0.190s: 200
2023/01/16 13:54:22 INFO: wazuh 172.31.62.248 "PUT /manager/restart" with parameters {} and body {} done in 0.101s: 200
```
Restarting the master immediately after executing the removal of the agents does not allow time for the run_writer() thread to update the client.

```
root@nico-VirtualBox:/home/nico/scripts# cat /var/ossec/etc/client.keys | grep any | wc -l
10111

....
15049 new_agent_15049 any 3012cc25ca8743681c167e1896e40bfcf45217e88785e01e180741183b94ede3
10104 new_agent_10104 any c25fc72c3b5bc3a5e567510877f74876e528d7d7f97cf49f8a54cbcff9429f32
14557 new_agent_14557 any 8d73e1afcf48d950a97ca81896b8b95e825c8dbd63d7e422e9559506463334ae
40461 new_agent_40461 any c2941e70bf96c93d8b2eef28ea912eacc353d3b0fbb2225b08184a994966ea2f
13055 new_agent_13055 any ca291ea76b882734e90cc48b69f8cbaedf355e8d2e0113d9da3c64c3dcb20976
15400 new_agent_15400 any 2dd4a1cbfd86f284f37d7332142025f1e6cfb5d2b7f5f274489d7df4e3f689b7
10109 new_agent_10109 any 72f53aca346f6b1316116c4edc5081716980bdbc8998d885ec991b70a8014fb6
20859 new_agent_20859 any ae51c2f39c57106510335fd3df3932fcabed901151a04800e7e03336a93fcd13
30303 new_agent_30303 any c4e3d40828df0b8cd1928de77dde1c56374f025c00e1a4d43967ded46eadb880
....
```

After this the worker keeps synchronizing, in this case 6 chunks:
```
2023/01/24 03:37:58 DEBUG: [Worker worker-node] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 7e55ad0a0a69840cf710c1531edf9064f06b60ed | Master checksum: f55fa2110b1d35816c673a889d996d3f40573529.
2023/01/24 03:37:58 INFO: [Worker worker-node] [Agent-groups recv] Sent request to obtain all agent-groups information from the master node.
2023/01/24 03:37:58 INFO: [Worker worker-node] [Agent-groups recv] Finished in 0.007s. Updated 1 chunks.
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'new_str''
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'str_upd''
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Main] Command received: 'b'syn_g_m_w_c''
2023/01/24 03:37:59 INFO: [Worker worker-node] [Agent-groups recv full] Starting.
2023/01/24 03:37:59 DEBUG: [Worker worker-node] [Agent-groups recv full] 6/6 chunks updated in wazuh-db in 0.223s.
2023/01/24 03:37:59 INFO: [Worker worker-node] [Agent-groups recv full] Finished in 0.228s. Updated 6 chunks.
```

**Comment by Nicogp** [comment] 2023-01-25 17:12
## Update
After running the script created by @Selutario to get the `groups-hash` and calculate the `groups-hash`, we notice that the master node misreports the `groups-hash`:

Master:
```
root@nico-VirtualBox:/home/nico/scripts# python3 calculate-hash.py 
Global groups hash: 22eba041e0079bc12372b3c03c6065703e76099d
root@nico-VirtualBox:/home/nico/scripts# python3 send_msg.py 'global sync-agent-groups-get {"condition": "sync_status", "set_synced": false, "get_global_hash": true}'
['ok', '[{"data":[],"hash":"04de140919ef71f100255bab5b324c791c38b359"}]']
```

Worker:
```
root@worker:/home/vagrant# python3 calculate-hash.py
Global groups hash: 22eba041e0079bc12372b3c03c6065703e76099d
root@worker:/home/vagrant# python3 send-msg.py 'global sync-agent-groups-get {"condition": "sync_statu
s", "set_synced": false, "get_global_hash": true}'
['ok', '[{"data":[],"hash":"22eba041e0079bc12372b3c03c6065703e76099d"}]']
```

cluster.log(Worker)
`2023/01/25 16:56:58 DEBUG: [Worker worker-node] [Agent-groups recv] The master's checksum and the worker's checksum are different. Local checksum: 22eba041e0079bc12372b3c03c6065703e76099d | Master checksum: 04de140919ef71f100255bab5b324c791c38b359.`

Possibly the error is due to the fact that the `master `did not update the cached "group hash" correctly and is returning an old value, because if at this point I restart the `master `again, the master reports the correct value and the synchronization is normalized.

**Comment by TomasTurina** [comment] 2023-02-01 20:19
Investigation already completed.

Related issue: https://github.com/wazuh/wazuh/issues/16074

**Closed by TomasTurina** 2023-02-01 20:19 UTC
Labels: type/bug, module/db, team/core
