### ISSUE TITLE
 Implement the new management of agent groups

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#25122] opened 2024-08-09 12:30 UTC
|Objective|
|---|
| #22677 |

# Description

The issue intends to make the necessary changes to the mechanisms used to manage the agent groups. Currently, the framework makes a series of operations with `wazuh-db` to create, modify and delete the group information related to the agents. In 5.0, this behavior will be modified in favor of the persistence of such information in the Wazuh Indexer.

# Requirements
## Functional requirements

- The Server Management API must support the basic agent group operations: create, read, and delete groups.
- The Server Management API must support complex multiple indexes queries related to group assignment since the agent group information will be stored in these. The assignment of an agent to a group should be reflected in every related index.
-  The Server Management API must communicate with the Indexer to exchange the agent group information.
- Analyze and adapt the RBAC filters and mechanisms applied until now along with queries to `wazuh-db` to check the allowed actions over agents must be analyzed in depth, i.e., the `expose_resources` decorator found in `wazuh.rbac.decorators`.

## Non-functional requirements

- The performance of the Server Management API should not be affected due to the implemented queries. In case it happens, it should not be affected severely, therefore the response times should be measured.

## Implementation restrictions

- The indexer client developed in https://github.com/wazuh/wazuh/issues/24615 must be used for API-Indexer communication.  
- The framework code sections related to `wazuh-db` and the agent group management must be removed/modified to implement the necessary logic for this communication.

# Plan

- [x] Review the current Server Management API endpoints related to agent group management. 
- [x] Implement the necessary changes to support the basic agent group operations, agent group assignment, and agent group information exchange with the Indexer managed as commands along its Command Manager.
- [x] Verify that a group can be created, modified, and deleted using the Server Management API.
- [x] Verify that an agent:
    - Can be assigned and removed from a group by checking the corresponding indices.
    - Can be registered with a group assigned to it.

**Comment by GGP1** [comment] 2024-08-29 17:30
## Update

I've reviewed the endpoints related to the agents groups management.

### Endpoints that access groups files

| Endpoint | Method | Description | Status | Reason |
| --- | --- | --- | --- | --- |
| `/agents/{agent_id}/group` | **DELETE** | Remove agent from groups | ✏️ | Changes in the groups files |
| `/agents/{agent_id}/group/is_sync` | **GET** | Get configuration sync status | ❌ | Deprecated in 4.8.0 |
| `/agents/{agent_id}/group/{group_id}` | **DELETE** | Remove agent from group | ❌ | Use `/agents/group` |
| `/agents/{agent_id}/group/{group_id}` | **PUT** | Assign agent to group | ❌ | Use `/agents/group` |
| `/agents/group` | **DELETE** | Remove agents from group | ✏️ | Changes in the groups files |
| `/agents/group` | **PUT** | Assign agents to group | ✏️ | Changes in the groups files |
| `/agents/group/{group_id}/restart` | **PUT** | Restart agents in group | ✏️ | AR replaced with a command |
| `/groups` | **DELETE** | Delete groups | ✔️ |
| `/groups` | **GET** | Get groups | ✏️ | Changes in the groups files |
| `/groups` | **POST** | Create a new group | ✏️ | Changes in the groups files |
| `/groups/{group_id}/agents` | **GET** | Get agents in a group | ✏️ | Changes in the groups files |
| `/groups/{group_id}/configuration` | **GET** | Get group configuration | ✏️ | Changes in the groups files |
| `/groups/{group_id}/configuration` | **PUT** | Update group configuration | ✏️ | Changes in the groups files |
| `/groups/{group_id}/files` | **GET** | Get groups files | ❌ | There will be no group files |
| `/groups/{group_id}/files/{file_name}` | **GET** | Get a group file | ❌ | There will be no group files |

#### Legend

|Symbol|Meaning|
|:-:|--|
| ✔️ | Keep |
| ❌ | Remove |
| ✏️ | Needs modifications |

> [!Note]
> "Changes in the groups files" refers to the modifications/removal of the `agent.conf`, `ar.conf` and `merged.mg` files.

### Endpoints that access agents groups relationships

Every endpoint that accesses agents groups information from wazuh-db should be updated to obtain it from the indexer.

### Cluster threads

The cluster thread `Local agent-groups` in the master node which periodically asks information about the agent groups should also be updated to get this information from the indexer.

### Server binaries

The binary `agent_groups` will be removed.

**Comment by GGP1** [comment] 2024-08-30 14:22
## Update

In the last update, I mentioned that many endpoints will require changes because of modifications to the groups files, so I'm listing all the files used in the current version and their future status.

### Groups shared files

| Type | Status | Reason |
| --- | --- | --- |
| ar.conf | ❌ | Active response module removed |
| CIS benchmarks | ❌ | CIS-CAT module removed |
| Rootkit | ❌ | Rootcheck module removed |
| merged.mg | ❔ | Will it be used to share multiple files in one payload? |
| agent.conf | ✔️ |   |
| Custom files | ❔ | Will they be a thing? |

**Comment by GGP1** [comment] 2024-09-02 18:56
## Update

I continued with the development of the tasks mentioned above, particularly, I worked on:

- Modifications to read YAML files instead of XML
- I updated the endpoints and files tables based on what we discussed in Slack
- Removed the `/agents/group/{group_id}/restart` endpoint
- Removed the `/groups/{group_id}/files` endpoint
- Removed the `/groups/{group_id}/files/{filename}` endpoint
- Updated unit tests from functions that were modified to replace `wazuh-db` with the indexer

**Comment by GGP1** [comment] 2024-09-03 18:27
## Update

I've been working on several changes:

- Changed the way groups are created
- Refactored group files structure
- Changed the way group configuration files are updated

All that's left is to build the queries to update the groups in the `agents` index and tests all endpoints together.

**Comment by GGP1** [comment] 2024-09-04 17:25
## Update

I've been building the queries to get agents from a group, delete agents from a group, delete groups and add agents to a group.

<details><summary>Environment</summary>

```
0191bcd6-d5d9-7c4f-9808-553a9a2f5316 -> default,group1,group2

0191bcd6-d5d9-7688-8e4e-a51caa5847a8 -> default,group2,group5

0191bcd6-d5d9-7d5f-8724-849499e4cacf -> group3,test 
```

</details>

<details><summary>Create agents</summary>

```console
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_create/0191bcd6-d5d9-7c4f-9808-553a9a2f5316 -d '{"name": "test1", "groups": "default,group1,group2"}'
{"_index":"agents","_id":"0191bcd6-d5d9-7c4f-9808-553a9a2f5316","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":0,"_primary_term":1}
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_create/0191bcd6-d5d9-7688-8e4e-a51caa5847a8 -d '{"name": "test1", "groups": "default,group2,group5"}'
{"_index":"agents","_id":"0191bcd6-d5d9-7688-8e4e-a51caa5847a8","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":1,"_primary_term":1}
root@curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_create/0191bcd6-d5d9-7d5f-8724-849499e4cacf -d '{"name": "test1", "groups": "group3,test"}'
{"_index":"agents","_id":"0191bcd6-d5d9-7d5f-8724-849499e4cacf","_version":1,"result":"created","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":2,"_primary_term":1}
```

</details>

<details><summary>Get agents in group</summary>

Query: `{"query": {"term": {"groups": {"value": "<group_name>"}}}}`

```console
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_search -d '{"query": {"term": {"groups": {"value": "
group2"}}}}'
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":0.4471386,"hits":[{"_index":"agents","_id":"0191bcd6-d5d9-7c4f-9808-553a9a2f5316","_score":0.4471386,"_source":{"name": "test1", "groups": "default,group1,group2"}},{"_index":"agents","_id":"0191bcd6-d5d9-7688-8e4e-a51caa5847a8","_score":0.4471386,"_source":{"name": "test1", "groups": "default,group2,group5"}}]}}
```

</details>

<details><summary>Assign agents to group</summary>

Query: `{"query": {"ids": {"values": [<agent_ids>]}}, "script" : {"source": "ctx._source.groups += \",\"+params.group", "params": {"group": "new_group_name"}}}`

```console
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_update_by_query -d '
{
  "query": {
    "ids": {
      "values": ["0191bcd6-d5d9-7688-8e4e-a51caa5847a8"]
    }
  },
  "script" : {
    "source": "ctx._source.groups += \",\"+params.group",
    "lang": "painless",
    "params": {
      "group": "new_group"
    }
  }
}'
{"took":57,"timed_out":false,"total":2,"updated":2,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":1"}
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_search -d '{"query": {"ids": {"values": ["0191bcd6-d5d9-7688-8e4e-a51caa5847a8"]}}}'
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"agents","_id":"0191bcd6-d5d9-7688-8e4e-a51caa5847a8","_score":1.0,"_source":{"name":"test1","groups":"default,group2,group5,new_group"}}]}}
```

</details>

<details><summary>Remove agents from group</summary>

Query: `ctx._source.groups = ctx._source.groups.replace(","+<group_name>, "").replace(<group_name>, "")`

```console
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_update_by_query -d '
{
  "query": {
    "ids": {
      "values": ["0191bcd6-d5d9-7688-8e4e-a51caa5847a8"]
    }
  },
  "script" : {
    "source": "ctx._source.groups = ctx._source.groups.replace(\",\"+params.group, \"\").replace(params.group, \"\")",
    "lang": "painless",
    "params": {
      "group": "new_group"
    }
  }
}'
{"took":7,"timed_out":false,"total":1,"updated":1,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
root@wazuh-root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_search -d '{"query": {"ids": {"values": ["0191bcd6-d5d9-7688-8e4e-a51caa5847a8"]}}}'
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":1,"relation":"eq"},"max_score":1.0,"hits":[{"_index":"agents","_id":"0191bcd6-d5d9-7688-8e4e-a51caa5847a8","_score":1.0,"_source":{"name":"test1","groups":"default,group2,group5"}}]}}
```

</details>

<details><summary>Delete group</summary>

Query: `ctx._source.groups = ctx._source.groups.replace(","+<group_name>, "").replace(<group_name>, "")`

```console
root@wazuh-master:/# curl -X POST -H "Content-Type: application/json" -ku admin:SecretPassword1% http://wazuh-indexer:9200/agents/_update_by_query -d '
{
  "query": {
    "term": {
      "groups": "group2"
    }
  },
  "script" : {
    "source": "ctx._source.groups = ctx._source.groups.replace(","+params.group, "").replace(params.group, "")",
    "lang": "painless",
    "params": {
      "group": "group2"
    }
  }
}'
{"took":7,"timed_out":false,"total":2,"updated":2,"deleted":0,"batches":1,"version_conflicts":0,"noops":0,"retries":{"bulk":0,"search":0},"throttled_millis":0,"requests_per_second":-1.0,"throttled_until_millis":0,"failures":[]}
{"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":2,"relation":"eq"},"max_score":0.4471386,"hits":[{"_index":"agents","_id":"0191bcd6-d5d9-7c4f-9808-553a9a2f5316","_score":0.4471386,"_source":{"name": "test1", "groups": "default,group1"}},{"_index":"agents","_id":"0191bcd6-d5d9-7688-8e4e-a51caa5847a8","_score":0.4471386,"_source":{"name": "test1", "groups": "default,group5"}}]}}
```

</details>

**Comment by GGP1** [comment] 2024-09-05 17:50
## Update

Continued the development and tests of the different endpoints. I updated the PR's description with the tests completed so far.

**Comment by GGP1** [comment] 2024-09-06 18:28
## Update

Finished implementing all the cases required, made some corrections to the endpoints logic, tested that everything is working as intended and updated affected unit tests.

**Comment by GGP1** [comment] 2024-09-12 17:49
## Update

Applied suggested changes.

**Closed** 2024-09-13 18:32 UTC
Labels: type/enhancement, level/task, phase/mvp
