### ISSUE TITLE
Ability to ingest vpc flow logs from 1 centralized s3 bucket containing logs from numerous AWS accounts.

### ISSUE THREAD

**Issue by ericbrumfield** [wazuh/wazuh#11727] opened 2022-01-04 13:27 UTC
Hello, following up here to report an issue/feature request from slack conversation I had with @okynos:  https://wazuh.slack.com/archives/C0A933R8E/p1640960773010100.

I have a client that wishes to ingest vpc flow logs from about 15 different AWS accounts and does not want to do the setup where Wazuh cross account role assumes into each AWS account and pulls logs from s3 buckets that reside inside each individual AWS account.  What they want is to have all these AWS accounts send their vpc flow logs to a centralized s3 bucket that sits in 1 of the 15 accounts called the "logging" account that Wazuh is running in and have Wazuh ingest them all from there.

In doing this centralized setup what I've discovered is that even adding permissions for ec2:DescribeFlowLogs, Wazuh will only successfully ingest vpc flow logs for the 1 account that it is running in, and does not process the rest of the account files in that centralized s3 bucket.  I kind of suspect it's in how the python is written for vpc flow log ingestions from s3, that it is geared more for the cross account role assuming setup and how it makes that DescribeFlowLogs api call.  The way it acts is that it never picks up new vpc flow logs under the other account id prefixes in the s3 bucket from what I've seen in the wazuh-modulesd debug logging I watched.  I can send this log privately upon request, but don't want to share out the account ids in it.  

I'm able to successfully ingest vpc flow logs from all the AWS accounts, but only when I configure Wazuh to cross account assume a role into each individual AWS account and have it read from an s3 bucket holding logs in each AWS account.  Instead of 15 s3 buckets, 1 in each account, the client only wants 1 s3 bucket holding the logs from all 15 accounts and this doesn't seem to work.

The setup should be able to be reproduced using 2 AWS accounts, run Wazuh in 1 of them and have an s3 bucket sitting in that same account, we'll call this the "logging" account.  Configure vpc flow logs from all accounts to be written to the s3 bucket in the "logging" account, and configure Wazuh to ingest vpc flow logs from that bucket.  The result should be that Wazuh only ingests files from the "logging" account id that it runs in and does not process the logs from the other account.  For the account(s) that it doesn't process the wazuh-modulesd debug logs will just show No logs to process for '<flow-log-id>' flow log id in bucket: <account_id>/<region>

Please let me know if there's anything I can do to help further.

**Comment by ericbrumfield** [comment] 2022-01-07 18:40
I'm also seeing problems with another AWS service ingestion attempting to ingest them from S3 in a centralized manner like I originally was doing with vpc flow logs.  It seems that cloudtrail only ingests for the "logging" account as well like the vpc flow logs did from centralized s3.

Interestingly, we are also ingesting from KMS, balancers (alb, clb, nlb), guard duty and aws config from central s3 buckets in this logging account as well, and I'm able to find the other account ids via wazuh > modules > Amazon AWS > events in the UI.  Out of these services, only the aws guard duty account ids actually show up on the wazuh > modules > Amazon AWS > dashboard area.  This UI parts are probably another issue all together I'd assume.  I can open another issue related to that if you all would like.

The work-around I've put in place for our client so far is to aggregate vpc flow logs => cloudwatch in member accoutns and then have subscription-filters + kinesis send these to the central "logging" account, where they are ingested via lambda and aggregated into another cloudwatch log group in the central logging account.  Wazuh successfully ingests from that central/aggregated cloudwatch log group in the logging account going that route for all the accounts after adding a customer decoder and rule.  

I suspect that I'll have to come up with something similar for ingesting the cloudtrail logs from all the member accounts.

**Comment by davidjiglesias** [comment] 2022-01-10 09:37
Duplicate of #10846. This development will be treated in that issue.

**Closed by davidjiglesias** 2022-01-10 09:37 UTC
Labels: framework
