### ISSUE TITLE
Fix failed integration tests in 4.9.0

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh#22714] opened 2024-04-02 16:44 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | ITs | Manager/Agent | Packages/Sources | Linux/Windows |

## Description

In the execution of the integration tests that are already migrated in this repository, we have found that there are several failed checks that need to be fixed.
These checks can be found in the following PR:
- https://github.com/wazuh/wazuh/pull/22705

The reason for this should be determined, and the necessary changes implemented so that the ITs are fixed.

## Failed ITs

We found two cases:

### [Integration tests for Wazuh_db](https://github.com/wazuh/wazuh/actions/runs/8521467723/job/23339668685?pr=22705)
```
FAILED test_wazuh_db/test_databases/test_agent_database_version.py::test_agent_database_version
FAILED test_wazuh_db/test_databases/test_wazuh_db.py::test_wazuh_db_messages_agent[Agent messages - Agents' Packages/Hotfixes tables: sys_programs and sys_hotfixes]
```

- Reason for failure: https://github.com/wazuh/wazuh/pull/22569

### [Integration tests for enrollment on Windows](https://github.com/wazuh/wazuh/actions/runs/8521467721/job/23339813304?pr=22705)
```
>               assert socket_monitor.matches == 2
E               assert 1 == 2
E                +  where 1 = <wazuh_testing.tools.monitors.queue_monitor.QueueMonitor object at 0x0000027A8D1E00A0>.matches
---------
2024/04/02 10:51:15 agent-auth: ERROR: SSL read (unable to receive message)
2024/04/02 10:51:15 agent-auth: ERROR: If Agent verification is enabled, agent key and certificates may be incorrect!
---------
FAILED test_enrollment/test_agent/test_agent_auth_enrollment.py::test_agent_auth_enrollment[Multi Groups]
```

- Reason for failure: Unknown

**Comment by TomasTurina** [comment] 2024-04-15 20:40
Wazuh DB tests already fixed in https://github.com/wazuh/wazuh/pull/22865.

**Comment by TomasTurina** [comment] 2024-04-16 15:02
Could not reproduce the problem with the enrollment tests: https://github.com/wazuh/wazuh/actions/runs/8695871965

**Closed** 2024-04-16 15:03 UTC
Labels: type/test, level/task
