### ISSUE TITLE
Errors reading Logcollector stress test logs.

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#19258] opened 2023-09-26 18:36 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3-rc1 | wazuh-agent | Windows | Packages | Windows |

## Description

During testing for release 4.5.3 RC1 - https://github.com/wazuh/wazuh/issues/19207, a non-descriptive error was found on the Windows agent's ossec.log.

```
2023/09/22 23:38:10 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
2023/09/22 23:38:10 wazuh-agent: ERROR: Ftell function failed due to [(9)-(Bad file descriptor)]
2023/09/22 23:38:10 wazuh-agent: ERROR: (1115): Could not read from file 'C:\tmp\logcollector_test\flood-8-10.log' due to [(9)-(Bad file descriptor)].
```

We need to investigate if the `Ftell function failed due to the [(9)-(Bad file descriptor)]` message is related to the `flood-8-10.log` file or not

**Comment by vikman90** [comment] 2023-09-27 06:09
This is a duplicate of https://github.com/wazuh/wazuh/issues/18689, also reported in 4.5.2.

**Closed by vikman90** 2023-09-27 06:09 UTC
Labels: type/bug, module/logcollector, level/task
