### ISSUE TITLE
Manager not updating cis benchmark results

### ISSUE THREAD

**Issue by abdulelah-dev** [wazuh/wazuh#10292] opened 2021-09-26 09:07 UTC
I have an issue with wazuh manager not updating cis benchmark results

I have an ubuntu agent connected to the manager, while trying to cover most of the cis benchmark issues, some of them do update actually, but some won't for some reason, I ran `./wazuh-modulesd -dd -f` and followed the ID and as per my understanding of the logs, the regex are passing successfully but for some reason they're not updated in the manager

an example:

- [wazuh-modulesd -dd -f] log
```
2021/09/26 08:32:38 sca[48238] wm_sca.c:983 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 2536 'Ensure core dumps are restricted'
2021/09/26 08:32:38 sca[48238] wm_sca.c:984 at wm_sca_do_scan(): DEBUG: Rule aggregation strategy for this check is 'all'
2021/09/26 08:32:38 sca[48238] wm_sca.c:985 at wm_sca_do_scan(): DEBUG: Initial rule-aggregator value por this type of rule is '1'
2021/09/26 08:32:38 sca[48238] wm_sca.c:986 at wm_sca_do_scan(): DEBUG: Beginning rules evaluation.
2021/09/26 08:32:38 sca[48238] wm_sca.c:1011 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:sysctl fs.suid_dumpable -> r:=\s*\t*0$'
2021/09/26 08:32:38 sca[48238] wm_sca.c:1092 at wm_sca_do_scan(): DEBUG: Running command: 'sysctl fs.suid_dumpable'
2021/09/26 08:32:38 sca[48238] wm_sca.c:1568 at wm_sca_read_command(): DEBUG: Executing command 'sysctl fs.suid_dumpable', and testing output with pattern 'r:=\s*\t*0$'
2021/09/26 08:32:38 sca[48238] wm_sca.c:1574 at wm_sca_read_command(): DEBUG: Command 'sysctl fs.suid_dumpable' returned code 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:=\s*\t*0$)(fs.suid_dumpable = 2) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:=\s*\t*0$)(fs.suid_dumpable = 2) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:=\s*\t*0$)(EMPTY_LINE) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:=\s*\t*0$)(EMPTY_LINE) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1630 at wm_sca_read_command(): DEBUG: Result for (r:=\s*\t*0$)(sysctl fs.suid_dumpable) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1164 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sysctl fs.suid_dumpable -> r:=\s*\t*0$': 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1171 at wm_sca_do_scan(): DEBUG: Breaking from rule aggregator 'all' with found = 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1187 at wm_sca_do_scan(): DEBUG: Result for check id: 2536 'Ensure core dumps are restricted' -> 0
```

- [sysctl fs.suid_dumpable] out put
`fs.suid_dumpable = 0`

- result in the manager
<img width="2479" alt="Screen Shot 1443-02-19 at 12 07 04 PM" src="https://user-images.githubusercontent.com/91411065/134801261-f6961203-dfc9-4abd-9c79-bcbac0bb1c6e.png">

any help is appreciated.

**Comment by chemamartinez** [comment] 2021-09-28 08:54
Hi @abdulelah-dev,

Thank you for the detailed explanation and the debug logs. They are very useful to find out the problem here.

The check that is being evaluated in your example looks like this:
```yml
  - id: 2536
    title: "Ensure core dumps are restricted"
    description: "A core dump is the memory of an executable program. It is generally used to determine why a program aborted. It can also be used to glean confidential information from a core file. The system provides the ability to set a soft limit for core dumps, but this can be overridden by the user."
    rationale: "Setting a hard limit on core dumps prevents users from overriding the soft variable. If core dumps are required, consider setting limits for user groups (see limits.conf(5) ). In addition, setting the fs.suid_dumpable variable to 0 will prevent setuid programs from dumping core."
    remediation: "Add the following line to /etc/security/limits.conf or a /etc/security/limits.d/* file: * hard core 0 Set the following parameter in /etc/sysctl.conf or a /etc/sysctl.d/* file: fs.suid_dumpable = 0 Run the following command to set the active kernel parameter: # sysctl -w fs.suid_dumpable=0"
    compliance:
      - cis: ["1.6.4"]
      - cis_csc: ["13"]
      - pci_dss: ["2.2.4"]
      - nist_800_53: ["CM.1"]
      - tsc: ["CC5.2"]
    condition: all
    rules:
      - 'c:sysctl fs.suid_dumpable -> r:=\s*\t*0$'
      - 'c:grep -Rh fs\.suid_dumpable /etc/sysctl.conf /etc/sysctl.d -> !r:^# && r:=\s*\t*0$'
      - 'c:grep -Rh ^*[[:space:]]*hard[[:space:]][[:space:]]*core[[:space:]][[:space:]]* /etc/security/limits.conf /etc/security/limits.d -> r:\s*\t*0$'
```

When this check is evaluated, SCA starts by the first rule, in this case it runs `sysctl fs.suid_dumpable` and checks the output of the command. It should match `= 0` to pass the check. However, regarding the debug output you shared, it seems the real output in your host is `fs.suid_dumpable = 2` as we can see in these logs:
```
2021/09/26 08:32:38 sca[48238] wm_sca.c:1574 at wm_sca_read_command(): DEBUG: Command 'sysctl fs.suid_dumpable' returned code 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:=\s*\t*0$)(fs.suid_dumpable = 2) -> 0
2021/09/26 08:32:38 sca[48238] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:=\s*\t*0$)(fs.suid_dumpable = 2) -> 0
```

Once the result for the first rule is `failed`, the whole check is marked as failed because the condition field is set to `all` which means all the rules of the check must pass to validate the check.

Could you please run the command `sysctl fs.suid_dumpable` in your Ubuntu agent to ensure the value is set to 2? In that case, you would have to switch it to 0 in order to get the check pass.

Best regards,
Chema.

**Comment by 72nomada** [comment] 2022-06-13 08:47
I am closing as resolved. Ping here to open if the issue is still in place.

**Closed by 72nomada** 2022-06-13 08:47 UTC
Labels: community, sca
