### ISSUE TITLE
Azure Log Analytics Integration not generating alerts

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh#18963] opened 2023-09-11 17:31 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.6.0-alpha1	|Server|Amazon Machine Images (AMI)|Amazon Machine Images (AMI)|-Amazon Machine Images (AMI)|

### Description

During E2E testing on #18841, integration with Microsoft Log Analytics integration following the [documentation](https://documentation-dev.wazuh.com/v4.6.0-alpha1/cloud-security/azure/activity-services/services/log-analytics.html) failed to generate alerts either in alerts.logs, archives.log or on the Wazuh dashboard

Checking Ossec.log shows that the collection of the logs has been finished without any errors. 

```
[wazuh-user@wazuh-server ~]$ sudo cat /var/ossec/logs/ossec.log | grep "azure"
2023/09/11 16:23:57 wazuh-modulesd:azure-logs: INFO: Module started.
2023/09/11 16:23:57 wazuh-modulesd:azure-logs: INFO: Starting fetching of logs.
2023/09/11 16:23:57 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/09/11 16:24:00 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for request 'request_2077410536'.
2023/09/11 16:24:00 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/09/11 16:24:00 wazuh-modulesd:azure-logs: INFO: Starting Storage log collection for 'azure-activity'.
2023/09/11 16:24:01 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for container 'insights-logs-auditlogs'.
2023/09/11 16:24:01 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for 'azure-activity'.
2023/09/11 16:29:57 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2023/09/11 16:30:01 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2023/09/11 16:30:03 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2023/09/11 16:30:03 wazuh-modulesd:azure-logs: INFO: Module finished.
2023/09/11 16:30:12 wazuh-modulesd: INFO: At module 'azure-logs': No request tag defined. Setting it randomly...
2023/09/11 16:30:12 wazuh-modulesd:azure-logs: INFO: Module started.
2023/09/11 16:30:12 wazuh-modulesd:azure-logs: INFO: Starting fetching of logs.
2023/09/11 16:30:12 wazuh-modulesd:azure-logs: INFO: Starting Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/09/11 16:30:13 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for request 'request_1929103629'.
2023/09/11 16:30:13 wazuh-modulesd:azure-logs: INFO: Finished Log Analytics collection for the domain 'wazuh.onmicrosoft.com'.
2023/09/11 16:30:13 wazuh-modulesd:azure-logs: INFO: Starting Storage log collection for 'azure-activity'.
2023/09/11 16:30:15 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for container 'insights-logs-auditlogs'.
2023/09/11 16:30:15 wazuh-modulesd:azure-logs: INFO: Finished Storage log collection for 'azure-activity'.
```

**Comment by vikman90** [comment] 2023-09-12 06:04
@thony4uu the owners of this integration are @wazuh/framework.

**Comment by Selutario** [comment] 2023-09-12 07:30
This seems to be already reported here:
- https://github.com/wazuh/wazuh/issues/18936

If this is not the same error, let me know in order to reopen the issue.

**Comment by thony4uu** [comment] 2023-09-12 08:10
Hello @Selutario, please note that there are different issues entirely, although it's the same behavior. The issue you are referring to has to do with Azure Storage integration, while this has to do with Log Analytics integration.

**Comment by Selutario** [comment] 2023-09-12 08:16
You are absolutely right, I'm reopening it :+1:

**Comment by fdalmaup** [comment] 2023-09-14 19:21
# Issue Update

## Module operation

- The module was set up with the same parameters used in the test but a different workspace and application.
```xml
<wodle name="azure-logs">
    <disabled>no</disabled>
    <run_on_start>yes</run_on_start>
    <log_analytics>
      <auth_path>/var/ossec/loganalytics_auth.txt</auth_path>
      <tenantdomain>wazuh.onmicrosoft.com</tenantdomain>
      <request>
          <query>AzureActivity</query>
          <workspace>FrameworkTest-WORKSPACE-ID</workspace>
          <time_offset>1d</time_offset>
      </request>
    </log_analytics>
</wodle>
``` 
- The options `logall` and `wazuh_modules.debug=2` were set to get more information about the module's execution. 

No issues were found and events were written in `archives` and sent to Analysisd. One of these was tested using `wazuh-logtest` to verify that an alert is triggered:
```
**Phase 3: Completed filtering (rules).
	id: '87811'
	level: '3'
	description: 'Azure: Log analytics: List Storage Account Keys'
	groups: '['azure']'
	firedtimes: '1'
	mail: 'False'
```

This means that the lack of logs in the dashboard does not come from the module in charge of fetching the records but might come from the Azure configuration. 

## Test using the same Azure resources

The `4.6.0-Alpha-1-LogAnalytics` application is still in the `App registrations` section on Azure. An `Application key` for the app was generated in order to test the module with the `LogAnalyticsWorkspace` workspace. The manual execution of the module has the following output:
```bash
/var/ossec/wodles/azure/azure-logs --log_analytics --la_auth_path /var/ossec/loganalytics_auth.txt --la_tenant_domain wazuh.onmicrosoft.com --la_query "AzureActivity" --workspace LogAnalyticsWorkspace-WORKSPACE-ID --la_time_offset 1d -d2
2023/09/14 03:41:49 azure: INFO: Checking database integrity
2023/09/14 03:41:49 azure: INFO: Database integrity check finished
2023/09/14 03:41:49 azure: INFO: Azure Log Analytics starting.
2023/09/14 03:41:49 azure: INFO: Log Analytics: Getting authentication token.
2023/09/14 03:41:50 azure: INFO: Log Analytics: The search starts for query: 'AzureActivity | order by TimeGenerated asc | where TimeGenerated >= datetime(2023-09-13T18:41:50.425849Z) '
2023/09/14 03:41:50 azure: INFO: Log Analytics: Sending a request to the Log Analytics API.
2023/09/14 03:41:52 azure: INFO: Log Analytics: There are no new results
2023/09/14 03:41:52 azure: INFO: Azure Log Analytics ending.
``` 
The results show that no log was fetched from the Log Analytics API.
It is important to notice that when checking the `Role assignments` in the ` Access control (IAM)` section of the workspace, the `4.6.0-Alpha-1-LogAnalytics` app was not present. This change could have been performed after closing the E2E test issue.

As a final check, a manual query to get `AzureActivity` was executed in the two workspaces used to test the module's operation. No results were found for the `LogAnalyticsWorkspace` workspace:
![image](https://github.com/wazuh/wazuh/assets/26691145/66e34f25-eb5f-446a-9182-34f175d7a946)

On the other hand, the results for the `FrameworkTest` workspace were:
![image](https://github.com/wazuh/wazuh/assets/26691145/afc46392-ca36-460d-9e55-da4fce2f904e)
The logs found match with the ones obtained in the first section of this update.

## Conclusion

The module does not contain any bug that affects it to obtain the Azure Log Analytics logs.

**Comment by EduLeon12** [comment] 2023-09-18 10:56
## 🟢  Issue Review

After looking at and reviewing the steps made to recreate the bug with the logs, I also conclude that there are no bugs during the retrieval of Azure Log Analytics Logs. Therefore, the Issue is approved, and LGTM!

**Closed** 2023-09-19 11:23 UTC
Labels: type/bug, level/task
