### ISSUE TITLE
Error in Wazuh Docker startup

### ISSUE THREAD

**Issue by vcerenu** [wazuh/wazuh#18966] opened 2023-09-11 19:49 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | wazuhdb | Manager | Packages | ubuntu 20.04 Docker image |

At the start of the Docker image created with the .deb package for version 4.6.0-1, the following error is encountered:

```
wazuh.manager_1    | Traceback (most recent call last):
wazuh.manager_1    |   File "/var/ossec/framework/scripts/create_user.py", line 16, in <module>
wazuh.manager_1    |     from wazuh.rbac.orm import create_rbac_db
wazuh.manager_1    | ImportError: cannot import name 'create_rbac_db' from 'wazuh.rbac.orm' (/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.6.0-py3.9.egg/wazuh/rbac/orm.py)
wazuh.manager_1    | There was an error configuring the API user
wazuh.manager_1    | [cont-init.d] 2-manager: exited 0.
```

This error in the image entrypoint, which tries to launch the Wazuh manager services, causes the image to restart

**Comment by vcerenu** [comment] 2023-09-11 20:04
To run a test it is necessary to create the Wazuh Docker images, which can be generated with the [18966-error-wazuhdb](https://github.com/wazuh/wazuh-docker/tree/18966-error-wazuhdb) branch

Once located in the downloaded repository, they must execute the following command:

```
build-docker-images/build-images.sh
```

When the images are ready, execute the following commands:

```
cd single-node
docker-compose -f generate-indexer-certs.yml run --rm generator
docker-compose up
```

The execution of the stack is carried out in foregound, so that the container messages appear on the screen, there the error will appear at the start of the Wazuh manager container

**Comment by vikman90** [comment] 2023-09-12 06:07
This seems to be related to the API @wazuh/framework.

**Comment by nico-stefani** [comment] 2023-09-14 19:44
# Issue Update

The problem is caused because the function `create_rbac_db` was replaced by the `DatabaseManager` class in #13109.
So, the script `create_user.py` must be modified to use this new class to interact with the DB.

**Comment by nico-stefani** [comment] 2023-09-15 20:23
# Issue Update

I was working on the solution, now the manager container starts without problems.

```
Attaching to single-node_wazuh.manager_1
wazuh.manager_1    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
wazuh.manager_1    | [s6-init] ensuring user provided files have correct perms...exited 0.
wazuh.manager_1    | [fix-attrs.d] applying ownership & permissions fixes...
wazuh.manager_1    | [fix-attrs.d] done.
wazuh.manager_1    | [cont-init.d] executing container initialization scripts...
wazuh.manager_1    | [cont-init.d] 0-wazuh-init: executing... 
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/api/configuration/
wazuh.manager_1    | The path /var/ossec/api/configuration is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/etc/
wazuh.manager_1    | The path /var/ossec/etc is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/logs/
wazuh.manager_1    | The path /var/ossec/logs is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/queue/
wazuh.manager_1    | The path /var/ossec/queue is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/agentless/
wazuh.manager_1    | The path /var/ossec/agentless is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/var/multigroups/
wazuh.manager_1    | The path /var/ossec/var/multigroups is empty, skiped
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/integrations/
wazuh.manager_1    | The path /var/ossec/integrations is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/active-response/bin/
wazuh.manager_1    | The path /var/ossec/active-response/bin is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/var/ossec/wodles/
wazuh.manager_1    | The path /var/ossec/wodles is already mounted
wazuh.manager_1    | /var/ossec/data_tmp/permanent/etc/filebeat/
wazuh.manager_1    | The path /etc/filebeat is already mounted
wazuh.manager_1    | Updating /var/ossec/etc/internal_options.conf
wazuh.manager_1    | Updating /var/ossec/integrations/pagerduty
wazuh.manager_1    | Updating /var/ossec/integrations/slack
wazuh.manager_1    | Updating /var/ossec/integrations/slack.py
wazuh.manager_1    | Updating /var/ossec/integrations/virustotal
wazuh.manager_1    | Updating /var/ossec/integrations/virustotal.py
wazuh.manager_1    | Updating /var/ossec/active-response/bin/default-firewall-drop
wazuh.manager_1    | Updating /var/ossec/active-response/bin/disable-account
wazuh.manager_1    | Updating /var/ossec/active-response/bin/firewalld-drop
wazuh.manager_1    | Updating /var/ossec/active-response/bin/firewall-drop
wazuh.manager_1    | Updating /var/ossec/active-response/bin/host-deny
wazuh.manager_1    | Updating /var/ossec/active-response/bin/ip-customblock
wazuh.manager_1    | Updating /var/ossec/active-response/bin/ipfw
wazuh.manager_1    | Updating /var/ossec/active-response/bin/kaspersky.py
wazuh.manager_1    | Updating /var/ossec/active-response/bin/kaspersky
wazuh.manager_1    | Updating /var/ossec/active-response/bin/npf
wazuh.manager_1    | Updating /var/ossec/active-response/bin/wazuh-slack
wazuh.manager_1    | Updating /var/ossec/active-response/bin/pf
wazuh.manager_1    | Updating /var/ossec/active-response/bin/restart-wazuh
wazuh.manager_1    | Updating /var/ossec/active-response/bin/restart.sh
wazuh.manager_1    | Updating /var/ossec/active-response/bin/route-null
wazuh.manager_1    | Updating /var/ossec/agentless/sshlogin.exp
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_pixconfig_diff
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_asa-fwsmconfig_diff
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_integrity_check_bsd
wazuh.manager_1    | Updating /var/ossec/agentless/main.exp
wazuh.manager_1    | Updating /var/ossec/agentless/su.exp
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_integrity_check_linux
wazuh.manager_1    | Updating /var/ossec/agentless/register_host.sh
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_generic_diff
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_foundry_diff
wazuh.manager_1    | Updating /var/ossec/agentless/ssh_nopass.exp
wazuh.manager_1    | Updating /var/ossec/agentless/ssh.exp
wazuh.manager_1    | Updating /var/ossec/wodles/utils.py
wazuh.manager_1    | Updating /var/ossec/wodles/aws/aws-s3
wazuh.manager_1    | Updating /var/ossec/wodles/aws/aws-s3.py
wazuh.manager_1    | Updating /var/ossec/wodles/azure/azure-logs
wazuh.manager_1    | Updating /var/ossec/wodles/azure/azure-logs.py
wazuh.manager_1    | Updating /var/ossec/wodles/docker/DockerListener
wazuh.manager_1    | Updating /var/ossec/wodles/docker/DockerListener.py
wazuh.manager_1    | Updating /var/ossec/wodles/gcloud/gcloud
wazuh.manager_1    | Updating /var/ossec/wodles/gcloud/gcloud.py
wazuh.manager_1    | Updating /var/ossec/wodles/gcloud/integration.py
wazuh.manager_1    | Updating /var/ossec/wodles/gcloud/tools.py
wazuh.manager_1    | find: '/proc/312/task/312/fd/6': No such file or directory
wazuh.manager_1    | find: '/proc/312/task/312/fdinfo/6': No such file or directory
wazuh.manager_1    | find: '/proc/312/fd/5': No such file or directory
wazuh.manager_1    | find: '/proc/312/fdinfo/5': No such file or directory
wazuh.manager_1    | find: '/proc/313/task/313/fd/6': No such file or directory
wazuh.manager_1    | find: '/proc/313/task/313/fdinfo/6': No such file or directory
wazuh.manager_1    | find: '/proc/313/fd/5': No such file or directory
wazuh.manager_1    | find: '/proc/313/fdinfo/5': No such file or directory
wazuh.manager_1    | Identified Wazuh configuration files to mount...
wazuh.manager_1    | '/wazuh-config-mount/etc/ossec.conf' -> '/var/ossec/etc/ossec.conf'
wazuh.manager_1    | [cont-init.d] 0-wazuh-init: exited 0.
wazuh.manager_1    | [cont-init.d] 1-config-filebeat: executing... 
wazuh.manager_1    | Customize Elasticsearch ouput IP
wazuh.manager_1    | Configuring username.
wazuh.manager_1    | Configuring password.
wazuh.manager_1    | Configuring SSL verification mode.
wazuh.manager_1    | Configuring Certificate Authorities.
wazuh.manager_1    | Configuring SSL Certificate.
wazuh.manager_1    | Configuring SSL Key.
wazuh.manager_1    | [cont-init.d] 1-config-filebeat: exited 0.
wazuh.manager_1    | [cont-init.d] 2-manager: executing... 
wazuh.manager_1    | Starting Wazuh v4.6.0...
wazuh.manager_1    | Started wazuh-apid...
wazuh.manager_1    | Started wazuh-csyslogd...
wazuh.manager_1    | Started wazuh-dbd...
wazuh.manager_1    | 2023/09/15 19:31:12 wazuh-integratord: INFO: Remote integrations not configured. Clean exit.
wazuh.manager_1    | Started wazuh-integratord...
wazuh.manager_1    | Started wazuh-agentlessd...
wazuh.manager_1    | Started wazuh-authd...
wazuh.manager_1    | Started wazuh-db...
wazuh.manager_1    | Started wazuh-execd...
wazuh.manager_1    | Started wazuh-analysisd...
wazuh.manager_1    | Started wazuh-syscheckd...
wazuh.manager_1    | Started wazuh-remoted...
wazuh.manager_1    | Started wazuh-logcollector...
wazuh.manager_1    | Started wazuh-monitord...
wazuh.manager_1    | Started wazuh-modulesd...
wazuh.manager_1    | Completed.
```

Trying to push the change I realize that don't have permission to push to `wazuh-docker` repo, so I need to fix this before opening the PR.

**Comment by vcerenu** [comment] 2023-09-18 15:39
Applied the changes in the branch https://github.com/wazuh/wazuh-docker/tree/18966-error-in-wazuh-docker-startup and created the PR https://github.com/wazuh/wazuh-docker/pull/1000 to merge to branch https://github.com/wazuh/wazuh-docker/tree/4.6.0

Deployment tests were carried out and completed successfully

![image](https://github.com/wazuh/wazuh/assets/56500015/46e463d3-edfe-4380-8a31-53d301500a3f)

**Comment by teddytpc1** [comment] 2023-09-18 17:39
PR was merged.

**Closed by teddytpc1** 2023-09-18 17:39 UTC
Labels: type/bug, level/task
