### ISSUE TITLE
Memory increase on rootcheck isolated case.

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#4894] opened 2020-04-13 16:07 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.2-31207 | Rootcheck | Agent | Packages | Windows Server 2016 |

Hello team,

We have detected a small memory increase on Rootcheck daemon that causes memory raise by ~1.5MB each hour, we will attach all clues that we have:
[ossec.conf.txt](https://github.com/wazuh/wazuh/files/4470307/ossec.conf.txt)
[ossec.log.txt](https://github.com/wazuh/wazuh/files/4470308/ossec.log.txt)

As you can see on the logs there is only Rootcheck enabled and we haven't any special configuration on it.

We obtain the following memory chart (after 2 hours of testing):
![image](https://user-images.githubusercontent.com/10661307/79135845-45fac580-7db0-11ea-975e-10518bff5a06.png)

Regards.

**Comment by antoniomanuelfr** [comment] 2020-04-23 10:42
Hi team. 
The memory leak was caused by the function: https://github.com/wazuh/wazuh/blob/833e6e92577266281ff5ec19a0aa7f6fa2091488/src/rootcheck/win-common.c#L26-L109
The function wasn't calling the BackupRead function with the correct parameters in order to free the memory allocated previously by this function.
This behavior has been observed only in Windows Server 2016.
The memory increase was very slow, and all the test has been done using a debug branch, ignoring the frequency and removing all the sleep in order to make rootcheck work
at maximum.

After calling the function with the correct parameters the memory leak was fixed in Windows Server 2016 and in other versions of windows server, the memory remains normal.
More info of the BackupRead function can be found here:
https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-backupread

**Closed** 2020-04-24 18:03 UTC
Labels: bug, cicd, core/rootcheck, platform/windows
