### ISSUE TITLE
Error executing internal command. Exit code: 1

### ISSUE THREAD

**Issue by l4yn3** [wazuh/wazuh#1115] opened 2018-08-17 04:08 UTC
## Description
Hi guys, I have continuely get errors, anyone have an idea on it?

When I use wazuh-api, I got this error every time.
`{
error: 1,
message: "Error executing internal command. Exit code: 1"
}`

I got api.log:

> # tail api.log
WazuhAPI 2018-08-17 11:51:22 : Listening on: http://0.0.0.0:55000
WazuhAPI 2018-08-17 11:51:25 foo: [10.20.38.211] GET /version - 200 - error: '0'.
WazuhAPI 2018-08-17 11:51:35 foo: Internal Error: uncaughtException
WazuhAPI 2018-08-17 11:51:35 foo: Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)
WazuhAPI 2018-08-17 11:51:35 foo: Exiting...
WazuhAPI 2018-08-17 11:51:35 foo: [10.20.38.211] GET /agents/ - 500 - error: '1'.
WazuhAPI 2018-08-17 12:04:52 : Listening on: http://0.0.0.0:55000
WazuhAPI 2018-08-17 12:04:54 foo: [10.20.38.211] GET /version - 200 - error: '0'.

Then wazuh-api would be exit.

My development envvironment: 

1. Centos 6.1
2. Node Js:v8.11.4
3. Wazuh-api:v3.5.0

Any one can help me?Thanks!

**Comment by l4yn3** [comment] 2018-08-17 04:09
My wazuh version is 3.x.

**Comment by mgmacias95** [comment] 2018-08-17 04:26
Hello @l4yn3 ,

In order to reproduce your issue, I need to know which python version are you using. I think it may be related to the python version because of the following:
* ` WazuhAPI 2018-08-17 11:51:25 foo: [10.20.38.211] GET /version - 200 - error: '0'.` => This API call is correctly executed and it doesn't use python.
* `WazuhAPI 2018-08-17 11:51:35 foo: [10.20.38.211] GET /agents/ - 500 - error: '1'.` => This API call fails and it does use python.

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 04:29
Hi, @mgmacias95 , 
My Python version is 2.7.7.

**Comment by l4yn3** [comment] 2018-08-17 04:32
I didn't modify config.js .
config.js:

> config.python = [
    // Default installation
    {
        bin: "python",
        lib: ""
    },
    // Python 3
    {
        bin: "python3",
        lib: ""
    },
    // Package 'python27' for CentOS 6
    {
        bin: "/opt/rh/python27/root/usr/bin/python",
        lib: "/opt/rh/python27/root/usr/lib64"
    }
];

**Comment by l4yn3** [comment] 2018-08-17 04:36
Hello, @mgmacias95 
I consider it's related to python version too.
But I don't know How could I debug that.

**Comment by mgmacias95** [comment] 2018-08-17 04:37
Hello @l4yn3,

Is your python2.7.7 installed on this path: `/opt/rh/python27/root/usr/bin/python`? 
The default python version in Centos 6 is python2.6, so if you execute `$ python`  it should run python2.6. Have you modified your system to run python2.7 instead of python2.6?

I'll tell you the debug commands after you answer those questions 😄 .

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 04:45
@mgmacias95 , 
My python path isn't /opt/rh/python27/root/usr/bin/python.
I have changed config.js like this:

> config.python = [
    // Default installation
    {
        bin: "python",
        lib: ""
    },
    // Python 3
    {
        bin: "python3",
        lib: ""
    },
    // Package 'python27' for CentOS 6
    {
        bin: "python",
        lib: ""
    }
];
Bug it doesn't work as well.

And did you mean the json string under ‘// Package 'python27' for CentOS 6’ is for Centos OS?

**Comment by l4yn3** [comment] 2018-08-17 04:46
And my Python version is /usr/bin/python2.7.

**Comment by l4yn3** [comment] 2018-08-17 04:50
I have modified `$python` to python 2.7.

**Comment by mgmacias95** [comment] 2018-08-17 04:56
Hello @l4yn3,

This part of the configuration `// Package 'python27' for CentOS 6` is for the special case of having python installed on the path I told you above.

Does the error appear after changing python to 2.7? 

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 05:01
I change config.js like this:

> config.python = [
    // Default installation
    {
        bin: "python",
        lib: ""
    },
    // Python 3
    {
        bin: "python3",
        lib: ""
    },
    // Package 'python27' for CentOS 6
    {
        bin: "python",
        lib: ""
    }
];

Then I can visit `/version`, It's return 200.
But I cann't visit '/agetns' or other router.It's return 500 and exit wazuh-api automaticly.

**Comment by l4yn3** [comment] 2018-08-17 05:03
And `lib:""` is OK?

**Comment by mgmacias95** [comment] 2018-08-17 05:12
Hello @l4yn3 ,

`lib: ""` is OK when the bin is `python`.

Let's debug to see what's happening.

1. Stop API.
1. Enable debug in your API configuration (`config.logs = "debug";`)
1. Run the API in foreground:
    ```shelsession
    # node /var/ossec/api/app.js -f
    ```
1. Execute the `/agents` API call.

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 05:30
Hi, @mgmacias95  
The result is:

> # node /var/ossec/api/app.js -f
WazuhAPI 2018-08-17 13:29:40 : Listening on: http://0.0.0.0:55000
WazuhAPI 2018-08-17 13:30:04 foo: [10.20.38.211] GET /version - 200 - error: '0'.
WazuhAPI 2018-08-17 13:30:09 foo: Internal Error: uncaughtException
WazuhAPI 2018-08-17 13:30:09 foo: Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)
WazuhAPI 2018-08-17 13:30:09 foo: Exiting...
WazuhAPI 2018-08-17 13:30:09 foo: [10.20.38.211] GET /agents/ - 500 - error: '1'.

**Comment by l4yn3** [comment] 2018-08-17 05:32
@mgmacias95 
Sorry, the result is:

> # node /var/ossec/api/app.js -f
WazuhAPI 2018-08-17 13:31:27 : Selected Python binary at 'python'.
WazuhAPI 2018-08-17 13:31:27 : Listening on: http://0.0.0.0:55000
WazuhAPI 2018-08-17 13:31:45 foo: 10.20.38.211 GET /version
WazuhAPI 2018-08-17 13:31:45 foo: [10.20.38.211] GET /version - 200 - error: '0'.
WazuhAPI 2018-08-17 13:31:48 foo: 10.20.38.211 GET /agents
WazuhAPI 2018-08-17 13:31:48 foo: CMD - Command: python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}
WazuhAPI 2018-08-17 13:31:48 foo: Internal Error: uncaughtException
WazuhAPI 2018-08-17 13:31:48 foo: Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at Pipe.onread (net.js:618:25)
WazuhAPI 2018-08-17 13:31:48 foo: Exiting...
WazuhAPI 2018-08-17 13:31:48 foo: CMD - Exit code: 1
WazuhAPI 2018-08-17 13:31:48 foo: [10.20.38.211] GET /agents/ - 500 - error: '1'.
WazuhAPI 2018-08-17 13:31:48 foo: Response: {"error":1,"message":"Error executing internal command. Exit code: 1"} HTTP Status: 500

**Comment by l4yn3** [comment] 2018-08-17 05:33
> # python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}
python: can't open file 'args:/var/ossec/api/models/wazuh-api.py': [Errno 2] No such file or directory

**Comment by l4yn3** [comment] 2018-08-17 05:34
>  python args:/var/ossec/api/models/wazuh-api.py stdin:{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}
python: can't open file 'args:/var/ossec/api/models/wazuh-api.py': [Errno 2] No such file or directory

**Comment by mgmacias95** [comment] 2018-08-17 05:36
Hello @l4yn3,

Can you check if the file `/var/ossec/api/models/wazuh-api.py` exists?

Best regards,
Marta

**Comment by mgmacias95** [comment] 2018-08-17 05:38
BTW, the correct command is:

```
echo '{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
```

**Comment by l4yn3** [comment] 2018-08-17 05:45
@mgmacias95 ,yes, `/var/ossec/api/models/wazuh-api.py` is exists.
I run the command
`echo '{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
`


The result is:
>
>Traceback (most recent call last):
> File "/var/ossec/api/models/wazuh-api.py", line 39, in <module>
>    except WazuhException as e:
>NameError: name 'WazuhException' is not defined

**Comment by mgmacias95** [comment] 2018-08-17 05:56
Hello @l4yn3,

That error is an import error of the Wazuh package.

Can you please change lines 39 to 49 (https://github.com/wazuh/wazuh-api/blob/master/models/wazuh-api.py#L39-L49) with the following?
```python
except Exception as e:
     raise e
```


And run the script again.

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 06:13
@mgmacias95 ,
It does work.
Thank you so much.
Is it a bug?
But I ran that in my other Centos 7 machine very well.

**Comment by l4yn3** [comment] 2018-08-17 06:26
I just change

 ```
except WazuhException as e:
    error_wazuh_package = -3
    error = e.message
    error_code = e.code
```

to

```
except Exception as e:
    error_wazuh_package = -3
    error = e.message
    error_code = e.code
```

It didn't work in your computer?

**Comment by mgmacias95** [comment] 2018-08-17 06:29
Hello @l4yn3,

That change is wrong, what I wanted was:

```python
except WazuhException as e:
    error_wazuh_package = -3
    error = e.message
    error_code = e.code
except Exception as e:
    error = str(e)
    if str(e).startswith("Error 4000"):
        error_wazuh_package=-1
    else:
        error_wazuh_package = -2
        exception_error = e
```

to

```python
except Exception as e:
    raise e
```

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-17 06:41
@mgmacias95 
```
except WazuhException as e:
    error_wazuh_package = -3
    error = e.message
    error_code = e.code
except Exception as e:
    error = str(e)
    if str(e).startswith("Error 4000"):
        error_wazuh_package=-1
    else:
        error_wazuh_package = -2
        exception_error = e
```
The code works.
But the code

```
except Exception as e:
    raise e
```

doesn't work in my env.

**Comment by l4yn3** [comment] 2018-08-17 06:44
@mgmacias95  
I got another error:
`
{
error: 2001,
message: "Incompatible version of SQLite: 3.6.20 Try to export the internal SQLite library: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/lib"
}
`

Is it the error trace you mean?

**Comment by l4yn3** [comment] 2018-08-21 01:51
Hi,@mgmacias95 
Thank you for your help, -_-.

**Comment by mgmacias95** [comment] 2018-08-21 03:02
Hi @l4yn3,

Was it helpful? 😄 

Best regards,
Marta

**Comment by l4yn3** [comment] 2018-08-22 07:00
Hi,@mgmacias95 
Yes, It's helpful for me. My Wazuh service has worked.
Thank you for your help.

**Comment by mgmacias95** [comment] 2018-08-22 07:03
Hello @l4yn3,

I'm glad your problem was solved! I'm closing this issue but don't hesitate to open a new one if you have another question or problem.

Best regards,
Marta

**Comment by Nocturneat50Hz** [comment] 2018-09-02 00:29
Hello @mgmacias95, 

i am having the same issue now once @l4yn3 had (uncaughtException - ECONNRESET).
the response i received for 
echo '{"function":"/agents","arguments":{"filters":{}},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
is a bit different:
{"message": "Wazuh-Python Internal Error: invalid syntax (utils.py, line 381)", "error": 1000}
i compared the lines in my installation's utils.py with the one one this github page and they look similar in fact. So i think i need another tweak for this issue.

Thanks,
Erman

PS: i'm sorry that i am new to github so my post may not look shiny

**Comment by mgmacias95** [comment] 2018-09-03 06:28
Hello @Nocturneat50Hz,

Your error seems to be related with an incompatible Python version. Are you using Python 2.6? Which OS are you using?

Best regards,
Marta

**Comment by Nocturneat50Hz** [comment] 2018-09-03 06:43
Hello @mgmacias95 

Python27 and Centos 6.10

In fact I prepared a new deployment over the old one because of an emergent demand, and did not face the same situation again.

Sorry to take your time,

Thanks,
Erman

**Comment by mgmacias95** [comment] 2018-09-03 06:44
Hello @Nocturneat50Hz,

I'm glad your issue was solved. I think the error was caused because the API wasn't using Python 2.7. I'm closing this issue but you can open a new one if you have any other problem.

Best regards,
Marta

**Comment by crakerkai** [comment] 2019-01-24 03:48
Hello @mgmacias95,

I am having the same issue as Nocturneat50Hz, My issues like that:
wazuh.exception.WazuhException: Error 2001 - Incompatible version of SQLite: 3.6.20
Try to export the internal SQLite library:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/framework/lib

When I try to fix following your instruction, I still met this issue, By the way, I still using Python27 and Centos 6.10, Would you help me to fix it?

Thanks,

**Comment by mgmacias95** [comment] 2019-01-24 08:50
Hello @crakerkai,

Sure! Which wazuh version are you using? Also, is the API using Python 2.7? You can check that running the following commands:
```shellsession
# sed -i "s:config.logs = \"info\":config.logs = \"debug\":g" /var/ossec/api/configuration/config.js
# service wazuh-api restart
WAZUH-API stopped.
WAZUH-API started.
# tail /var/ossec/logs/api.log
WazuhAPI 2019-01-24 08:45:11 : Listening on: http://:::55000
WazuhAPI 2019-01-24 08:47:39 : Exiting... (SIGTERM)
WazuhAPI 2019-01-24 08:47:40 : Selected Python binary at '/opt/rh/python27/root/usr/bin/python'.
WazuhAPI 2019-01-24 08:47:40 : Listening on: http://:::55000
```
For example, my API is using `/opt/rh/python27/root/usr/bin/python`.

Don't forget to turn off debug logs once you have checked the python interpreter:
```shellsession
# sed -i "s:config.logs = \"debug\":config.logs = \"info\":g" /var/ossec/api/configuration/config.js
# service wazuh-api restart
WAZUH-API stopped.
WAZUH-API started.
```

Best regards,
Marta

**Comment by crakerkai** [comment] 2019-01-24 09:14
Hello @mgmacias95 ,

FYI,
[root@WAZUH bin]# tail /var/ossec/logs/api.log
WazuhAPI 2019-01-24 14:28:42 wazuh-admin: [::ffff:192.168.28.24] GET /syscheck/001/last_scan? - 200 - error: '0'.
WazuhAPI 2019-01-24 15:00:01 wazuh-admin: [::ffff:192.168.28.24] GET /agents/?offset=0&limit=1 - 200 - error: '0'.
WazuhAPI 2019-01-24 15:00:01 wazuh-admin: [::ffff:192.168.28.24] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-01-24 15:00:02 wazuh-admin: [::ffff:192.168.28.24] GET /agents/?offset=0&limit=500 - 200 - error: '0'.
WazuhAPI 2019-01-24 16:00:01 wazuh-admin: [::ffff:192.168.28.24] GET /agents/?offset=0&limit=1 - 200 - error: '0'.
WazuhAPI 2019-01-24 16:00:01 wazuh-admin: [::ffff:192.168.28.24] GET /cluster/status? - 200 - error: '0'.
WazuhAPI 2019-01-24 16:00:02 wazuh-admin: [::ffff:192.168.28.24] GET /agents/?offset=0&limit=500 - 200 - error: '0'.
WazuhAPI 2019-01-24 16:08:52 wazuh-admin: Exiting... (SIGTERM)
WazuhAPI 2019-01-24 16:08:53 : Selected Python binary at '/opt/rh/python27/root/usr/bin/python'.
WazuhAPI 2019-01-24 16:08:53 : Listening on: http://:::55000
[root@WAZUH bin]# cat /var/ossec/etc/
af_wazuh.conf                internal_options.conf        localtime                    ossec-init.conf              shared/
client.keys                  lists/                       ossec.conf                   rootcheck/                   sslmanager.cert
decoders/                    local_internal_options.conf  ossec.conf.bk                rules/                       sslmanager.key
[root@WAZUH bin]# cat /var/ossec/etc/ossec-init.conf
DIRECTORY="/var/ossec"
NAME="Wazuh"
VERSION="v3.7.2"
REVISION="3727"
DATE="Thu Dec 13 20:20:11 UTC 2018"
TYPE="server"
[root@WAZUH bin]#

I hope some information can help your investiagation.

Thanks,

**Comment by mgmacias95** [comment] 2019-01-24 13:32
Hello @crakerkai,

Can you provide more details about the error? I see in the log you've posted some API calls that make database queries. For example:
```
WazuhAPI 2019-01-24 15:00:01 wazuh-admin: [::ffff:192.168.28.24] GET /agents/?offset=0&limit=1 - 200 - error: '0'.
```
This log line shows the API call `/agents` which makes queries against `/var/ossec/var/db/global.db` database and it returns error `0`. It should have returned error `2001` if it had the issue you commented.

Best regards,
Marta

**Comment by crakerkai** [comment] 2019-01-28 03:50
Hi @mgmacias95,

Thanks for your clarification. The problem here due to installing python27 on centos 6 incorrectly after some of my tests. It will be better to install the following:
`# sudo yum update.`
`# sudo yum install centos-release-scl`
`# sudo yum install python27`
`# scl enable python27 bash`
`# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/var/ossec/framework/lib`
`# pip install cryptography`
After fix the error python, I had met the other error:
`[root@WAZUH bin]# ./update_ruleset`
`### Wazuh ruleset ###`
`ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v3.7.x. Found version v3.8.1`
Could you give me some advice on this case?

Sorry for wasting your time

Best regards,
Pm

**Comment by mgmacias95** [comment] 2019-01-28 08:17
Hello @crakerkai,

I'm happy to know your issue was fixed. The new problem you're having is not related to the previous one so I need to ask you to open a new issue to talk about it. Since your previous problem is now fixed, I'm closing this issue.

Thank you so much and sorry for the inconvenience.

Best regards,
Marta

**Closed by mgmacias95** 2019-01-28 08:17 UTC
Labels: API
