### ISSUE TITLE
False positive on "Trojaned version of file detected."

### ISSUE THREAD

**Issue by ricokritzer** [wazuh/wazuh#13278] opened 2022-04-30 18:23 UTC
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2 | Rule: 510 | False-Positive |

## Description
Wazuh rule 510 detects the /bin/diff of Ubuntu 22.04 as trojaned version.

### Service/Product/Module
Rule 510

### Current results
`Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).`

### Expected results
No detection at all.

### Log source / integration
`Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).`

### Log reference
_none_

### Log examples
`Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).`

### Threats and compliance
_none_

**Comment by NHAS** [comment] 2022-07-12 02:09
Hi there, I am also being hit with this quirk. 

```
Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh' (Generic).
```
The system this is run on is Ubuntu 21.10, with wazuh-agent 4.3.5. 

From running `strings` over `/usr/bin/diff` I see the following:

```
username@computer:~$ strings /usr/bin/diff | grep '/dev'
/dev/full
/dev/null
```

It appears the match just needs to be updated to `/dev/[^nf]`

**Comment by mthbrown** [comment] 2022-08-26 01:53
I ran into this as well on `4.3.6` on Ubuntu 22.04

**Comment by mvagit** [comment] 2022-10-30 19:57
Same issue Ubuntu 20.04 LTS 
wazuh-agent/stable,now 4.3.9-1 amd64
sha1sum /bin/diff : e36327a2da31d8a11378ed3d0dc1f02bd54d33ec

**Comment by gnordli** [comment] 2023-01-24 23:12
Same issue, Wazuh 4.3.10 on Ubuntu 22.04.

**Comment by andonovski** [comment] 2023-05-13 09:24
Same issue on Wazuh 4.4.1, agent Ubuntu 22.04

**Comment by grepcatman** [comment] 2023-06-05 16:51
still happening on Ubuntu 22.04.2 LTS, Wazuh 4.4.3: 
sha1sum /bin/diff e36327a2da31d8a11378ed3d0dc1f02bd54d33ec  /bin/diff

**Comment by djosip** [comment] 2023-08-28 09:49
The same problem on Debian 12.1 with diffutils 3.8-4 and wazuh-agent 4.5.1-1.
This could be solved in the file _/var/ossec/etc/shared/rootkit_trojans.txt_ by replacing the line:
`diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh!`
with the line:
`diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]ull|^/bin/.*sh!`
That would ignore only `/dev/null` and `/dev/full` strings.

I have found old reports such as this one, in both, OSSEC and WAZUH projects.
False positives shouldn't be left unsolved for years as they encourage people to ignore the rule completely or even worse, to stop taking the alerts seriously.

**Comment by iasdeoupxe** [comment] 2024-02-07 17:16
Looks like there are multiple issues about the same / similar message open:
- #19000
- #19346
- #11808

Could be possible that all have the same origin and some could be closed as duplicates.

**Comment by nwhistler** [comment] 2024-09-04 16:44
Still getting this issue on agent v4.8.2 on Ubuntu 22.04.4 LTS

**Comment by JanKraljic** [comment] 2024-09-06 08:57
Have same problem on latest Debian 12

Do I see correctly that in ossec should the problem be fixed: https://github.com/ossec/ossec-hids/issues/2020

**Comment by djosip** [comment] 2024-09-06 09:56
Yes, they replaced the line:
`diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^n]|^/bin/.*sh!`

with the line:
`diff        !bash|^/bin/sh|file\.h|proc\.h|^/bin/.*sh!`

However, better solution would be:
`diff        !bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]ull|^/bin/.*sh!`

The line above would ignore strings /dev/null and /dev/full while still
triggering alert in case of any other file in /dev directory which is IMHO,
better solution.

The root of the problem is that newer diff binaries contain not just
/dev/null string but also /dev/full string.
It can be checked using the command:
`strings /usr/bin/diff | grep /dev/`

**Comment by iasdeoupxe** [comment] 2024-09-06 09:59
> Do I see correctly that in ossec should the problem be fixed: [ossec/ossec-hids#2020](https://github.com/ossec/ossec-hids/issues/2020)

Yes, has been already mentioned in https://github.com/wazuh/wazuh/issues/19346#issuecomment-1845319726

The discussion around this probably should be concentrated in a single issue (there are multiple open about the same issue) as it will get more difficult to follow if info is spread across multiple open issues:
- #19000
- #19346
- #11808
- This one here (#13278)

**Comment by iasdeoupxe** [comment] 2024-09-06 10:03
> However, better solution would be: `diff !bash|^/bin/sh|file\.h|proc\.h|/dev/[^nf]ull|^/bin/.*sh!`

Nice, have you considered to create a pull request? Probably needs a community contribution to get this issue (open since 2+ years) moved forward.

**Comment by djosip** [comment] 2024-09-06 11:03
I didn't.
I will try to do it later, today.

**Comment by djosip** [comment] 2024-09-07 14:50
I have created a pool request that, if accepted, should resolve the issue:
#25634

**Comment by vikman90** [comment] 2024-10-04 10:50
Hi all,

This issue has been fixed by @djosip:
- https://github.com/wazuh/wazuh/pull/25634

**Closed by vikman90** 2024-10-04 10:50 UTC
Labels: type/bug, reporter/community, team/threatintel, level/task
