### ISSUE TITLE
High Disk_Read increase of wazuh-monitord in Manager from Footprint test

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh#26219] opened 2024-10-08 09:57 UTC
| Version | Revision | Production/Development | Component | Install type | 
|:--:|:--:|:--:|:--:|:--:|
|  4.9.1  |  RC 3  |    |  Manager  | Download/Repository/Sources/Assistant |  

## Description

During the tests performed at https://github.com/wazuh/wazuh/issues/26183, in Active response test has been found a different behavior in the plots from Disk_Read, specifically a high increase in  `wazuh-monitord` component. It is necessary to study this behavior and find if it is expected or not.

### Current result

The plots from 4.9.1-rc3 are:
![image](https://github.com/user-attachments/assets/3e1579eb-4f44-4236-9dde-fcffc2f2616e)

### Expected result

It is expected to have a similar behavior like in 4.9.0-rc2
![image](https://github.com/user-attachments/assets/daee8ccf-12e7-4433-825f-33b8066159b8)

### Attachments

- Build link: https://ci.wazuh.info/job/Test_stress/5636/

- Build parameters: https://ci.wazuh.info/job/Test_stress_tier/188/parameters/

- Artifacts and logs: 
[B5636_manager_centos.zip](https://github.com/user-attachments/files/17291496/B5636_manager_centos.zip)

**Comment by juliancnn** [comment] 2024-10-08 16:49
Hi @joaquinsgi,

Could you tell us about the graph, I am interested in knowing in which unit the Y-axis is and if it is cumulative, instantaneous or cumulative by intervals.

**Comment by juliancnn** [comment] 2024-10-08 20:18
## Update

- Wazuh-monitord is responsible for log rotation. The sizes of ossec.logs are slightly over 17Kb, as opposed to 16KB in 4.9.0, which does not explain the increase in read operations.
- Firewall and archive logs are empty in both versions.
- The number of alerts is 4% higher in version 4.9 compared to 4.8.
- The module has been virtually unchanged for almost 3 years, indicating that the version is not the issue.
- This increase in read operations was not observed in 4.9.0-RC 1: [https://github.com/wazuh/wazuh/issues/25389](https://github.com/wazuh/wazuh/issues/25389)
- It was first noticed in 4.9.0-RC2, where it doubled and was marked as green: [https://github.com/wazuh/wazuh/issues/26026#issuecomment-2383313308](https://github.com/wazuh/wazuh/issues/26026#issuecomment-2383313308)
- The metric involved is a cumulative metric in bytes:
    ```
    read_bytes: the number of bytes read (cumulative). Always -1 on BSD.
    ```
    - ref psutils: https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters
    - test ref:  [here](https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L558C1-L559C1)

- The timing of the spike coincides with the date change when logs rotate:

|Timestamp|	Daemon|	CPU(%)|	RSS(KB)|	VMS(KB)|	FD	|Read_Ops|	Write_Ops	|Disk_Read(B)|
|---|---|---|---|---|---|---|---|---|
|---|---|---|---|---|---|---|---|---|
|2024-10-05 00:00:04|	wazuh-monitord	|0|	3912	|54448	|9|	13|	2|	0|
|2024-10-05 00:00:09|	wazuh-monitord	|0|	3912	|54448	|9|	13|	2|	0|
|2024-10-05 00:00:15|	wazuh-monitord	|0|	7452	|54448	|9|	636|	33|	1703936|
|2024-10-05 00:00:20|	wazuh-monitord	|0|	7452	|54448	|9|	636|	33|	1703936|
|2024-10-05 00:00:26|	wazuh-monitord	|0|	7452	|54448	|9|	636|	33|	1703936|
|2024-10-05 00:00:31|	wazuh-monitord	|0|	7452	|54448	|9|	636|	33|	1703936|
|---|---|---|---|---|---|---|---|---|
|2024-10-06 00:00:00|	wazuh-monitord	|0	|7452	|54448|	9	|636	  |33	|1703936|
|2024-10-06 00:00:06|	wazuh-monitord	|0	|7452	|54448|	9	|636	  |33	|1703936|
|2024-10-06 00:00:11|	wazuh-monitord	|100.3	|7452|	54640	|11	  |20817	|378	|4726784|
|2024-10-06 00:00:17|	wazuh-monitord	|53.9	|7452|	54448	|9	  |65583	|1495	|11227136|
|2024-10-06 00:00:22|	wazuh-monitord	|0	|7452	|54448|	9	|65583	    |1495	|11227136|
|2024-10-06 00:00:28|	wazuh-monitord	|0	|7452	|54448|	9	|65583	    |1495	|11227136|
|2024-10-06 00:00:33|	wazuh-monitord	|0	|7452	|54448|	9	|65583	    |1495	|11227136|
|2024-10-06 00:00:39|	wazuh-monitord	|0	|7452	|54448|	9	|65583	    |1495	|11227136|


This is expected as not only does it rename the file, but it also reads it to compress it:
[https://github.com/wazuh/wazuh/blob/8e0e581a1925a90472fd6a7bdbc358947f809e3f/src/monitord/compress_log.c#L38-L50](https://github.com/wazuh/wazuh/blob/8e0e581a1925a90472fd6a7bdbc358947f809e3f/src/monitord/compress_log.c#L38-L50)

An analysis of the alerts written by wazuh-analysisd could provide further insights:

- v4.9.0:
  - Start time: 2024-08-31 01:58:11
  - First rotation: 2024-09-01 00:00:00 - alerts.json should have 299396 alerts total.
  - Second rotation: 2024-09-02 00:00:01 - alerts.json should have 673463 alerts total.

- v4.9.1-rc3:
  - Start time: 2024-10-04 18:33:17
  - First rotation: 2024-10-05 00:00:03 - 1 alert
  - Second rotation: 2024-10-06 00:00:00 - 413778 alerts total.
  - Third rotation: 2024-10-07 00:00:00 - 726203 alerts total.

We don't have enough information to correct whether these readings are expected or not, although there is nothing to indicate changes. It would be desirable to have access to the VM to review the alert logs.

**Comment by juliancnn** [comment] 2024-10-09 13:38
## Update

I have analyzed the manager, and there seems to be a problem with the test.


According to the test, analyzing the python code [here](https://github.com/wazuh/wazuh-jenkins/blob/89dc64cddaa6054293161839442443df4ce63314/quality/python-packages/jenkins_utils/jenkins_utils/monitor.py#L558C1-L559C1), the disk read is done using the `io_counter()` functionality of the psutils library. The [documentation](https://psutil.readthedocs.io/en/latest/#psutil.Process.io_counters) clarifies:
```
read_bytes: the number of bytes read (cumulative).
```
That is, we would expect according to the graph that in the log rotation, wazuh-monitord would read approximately 11MB of files, but in reality we know that this is not the case.
Wazuh-monitord reads at that peak, at least 239MB, as it has rotated alerts. We know this because by reviewing the manger and analyzing the alerts, we can see the size of that day:

![image](https://github.com/user-attachments/assets/262cab90-9222-40ec-905a-494dc1486db8)

On the other hand, wazuh-monitord reads the whole file, to compress it, in that code section:

https://github.com/wazuh/wazuh/blob/8e0e581a1925a90472fd6a7bdbc358947f809e3f/src/monitord/compress_log.c#L38-L60

Finally, it does not seem to be a scaling problem, since the previous day it must have read at least 2.3MB, i.e. one tenth, but the reading jump is not 10 times smaller.

### Conclusions
Considering that the module has not been modified for more than 3 years, and that the **test is not trustworthy**, and that this does not seem to be a major problem, I think we should move on from this issue and review these tests.

**Comment by Dwordcito** [comment] 2024-10-09 15:39
LGTM, invalid results(unit of measurement) and, this is an expected behavior at 00:00 (when the log rotation occurs)

**Closed by Dwordcito** 2024-10-09 15:39 UTC
Labels: type/bug, level/task
