### ISSUE TITLE
Add the possibility to define the session duration when assuming roles on AWS-S3 wodle

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh#9086] opened 2021-06-22 17:35 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Any | AWS-S3 Wodle | Manager/Agent | Packages/Sources | - |

Hello team,

This issue aims to add the possibility to define the session duration when assuming a role on the AWS-S3 wodle.

As stated in [boto3 documentation - sts.client.assume_role](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sts.html#STS.Client.assume_role):

> **DurationSeconds (integer) --**
> 
> The duration, in seconds, of the role session. The value specified can can range from 900 seconds (15 minutes) up to the maximum session duration that is set for the role. The maximum session duration setting can have a value from 1 hour to 12 hours. If you specify a value higher than this setting or the administrator setting (whichever is lower), the operation fails. For example, if you specify a session duration of 12 hours, but your administrator set the maximum session duration to 6 hours, your operation fails. To learn how to view the maximum value for your role, see View the Maximum Session Duration Setting for a Role in the IAM User Guide .

### Modifications

**Current implementation:**
```python
sts_role_assumption = sts_client.assume_role(RoleArn=iam_role_arn,
                                             RoleSessionName='WazuhLogParsing'
                                             )
```

**Possible iteration:**
```python
sts_role_assumption = sts_client.assume_role(RoleArn=iam_role_arn,
                                             RoleSessionName='WazuhLogParsing',
                                             DurationSeconds=iam_role_duration
                                             )
```

Regards,
Franco Hielpos

**Comment by noise-kngdm** [comment] 2021-09-15 09:55
## Issue update
The development of the new feature has been finished, both the changes in the AWS module and the addition of the new parameter to the `ossec.conf` file. The changes have been committed to [this branch](https://github.com/wazuh/wazuh/tree/feature/9086-add-iam-role-session-duration).
Apart from the changes made to add the new parameter when invoking the script, the call to `assume_role` has been reworked to admit the `role_session_duration` parameter if set.
https://github.com/wazuh/wazuh/blob/c38afff1b3730ef5c19ef64ea741b2bdd2b55e36/wodles/aws/aws_s3.py#L249-L260

I am currently performing some manual tests in order to check if the new additions to the code work properly.

**Comment by noise-kngdm** [comment] 2021-09-16 18:26
## Issue update
Because of a delay caused by the lack of a proper role that I could switch to while testing the new additions, and problems with my development environment; I have only been able to test that the changes made to the C code that reads the configuration are working fine.
I have tested that the new parameter works fine in the configuration of both a service and a bucket by adding the following configuration items (one at a time) to the `ossec.conf` file and modifying the python program to write the value of the `role_session_variable`, if specified, to a temporary file. Then I made sure that the written value was the expected. 
### Bucket testing configuration
```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>10m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="cloudtrail">
     <name>wazuh-test-bucket</name>
     <access_key>XXXXXX</access_key>
     <secret_key>XXXXXX</secret_key>
     <iam_role_arn>arn:aws:iam::XXXXX:role/test_role</iam_role_arn>
     <role_session_duration>1300</role_session_duration>
  </bucket>  
</wodle>
```
### Service testing configuration
```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>1m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <service type="cloudwatchlogs">
     <access_key>XXXXXX</access_key>
     <secret_key>XXXXXX</secret_key>
     <iam_role_arn>arn:aws:iam::XXXXX:role/test_role</iam_role_arn>
     <role_session_duration>1300</role_session_duration>
     <aws_log_groups>framework-test-apache</aws_log_groups>
  </service>  
</wodle>
```

I have finally been provided with the role I needed to test the new parameter. I will soon write an update with the results of the testing.

**Comment by noise-kngdm** [comment] 2021-09-17 10:54
## Issue update
To test the changes I temporary added the following code to the module after the `assume_role` call to test if the module would return a timeout when trying to use a session after it has expired.
```python3
sleeping_time = role_session_duration + 10
import datetime
print(f'Time now: {datetime.datetime.now().strftime("%H:%M:%S")}')
print(f'Role assumed. role_session_duration variable is set to {role_session_duration}. Sleeping for {sleeping_time} seconds.')
import time
time.sleep(sleeping_time)
print(f'Time after sleep: {datetime.datetime.now().strftime("%H:%M:%S")}')

```
The execution would return an error, as expected.
### Testing a bucket
```
root@ff5389d2ebf2:/var/ossec/wodles/aws# /var/ossec/framework/python/bin/python3 ./aws-s3.py -b cloudtrail-bucket -t cloudtrail -ds 900 -i arn:aws:iam::xxxxxxx:role/test_role
Time now: 09:03:43
Role assumed. role_session_duration variable is set to 900. Sleeping for 910 seconds.
Time after sleep: 09:18:53
ERROR: Invalid credentials to access S3 Bucket
```
### Testing a service
```
root@ff5389d2ebf2:/var/ossec/wodles/aws# py ./aws-s3.py -sr inspector -ds 900 -i arn:aws:iam::xxxxxxx:role/test_role
Time now: 10:37:26
Role assumed. role_session_duration variable is set to 900. Sleeping for 910 seconds.
Time after sleep: 10:52:36
ERROR: An error occurred (ExpiredTokenException) when calling the ListFindings operation: The security token included in the request is expired
```

**Closed** 2021-09-23 14:29 UTC
Labels: enhancement, operations, aws_integration
