### ISSUE TITLE
Inconsistent behavior in group's agents endpoint

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#18331] opened 2023-08-10 14:12 UTC
|Wazuh version|Component|
|---|---|
| 4.6.0 | API |

## Description
We found an inconsistent behavior using `q` parameters in `groups/<group_name>/agents`

- Request 1:
```
GET /groups/default/agents
```
Returns the agents for the group `default` except for the agent `000`
![image](https://github.com/wazuh/wazuh/assets/42900763/0da8931b-cc42-4527-8208-458b54d287bd)
![image](https://github.com/wazuh/wazuh/assets/42900763/0c611be7-25ab-42f2-9ab2-7a5c2776899a)

- Request 2:
```
GET /groups/default/agents?q=(name~wazuh,status~active)
```
Returns the agents for the group `default`, which name contains `wazuh` and the status is `active` except for the agent `000`
![image](https://github.com/wazuh/wazuh/assets/42900763/ac288fe1-907a-4328-8e25-03de4cf5b78e)
![image](https://github.com/wazuh/wazuh/assets/42900763/c0befd26-ab1d-4a67-b899-854877964e92)

- Request 3:
```
GET /groups/default/agents?q=name~wazuh,status~active
```
Same as request 2 but without parentheses, returns the agents for the group `default`, which name contains `wazuh` and the status is `active` **including**  the agent `000`
![image](https://github.com/wazuh/wazuh/assets/42900763/605bde49-7501-43bb-b416-ba890faf67b3)
![image](https://github.com/wazuh/wazuh/assets/42900763/9ab53a72-2b22-4d4a-a596-7c707bbbcd52)

We cannot explicitly query the agent `000` running, for example, `GET /groups/default/agents?q=id=000`. The only case when we see it is running a query with several terms and no parentheses

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by RamosFe** [comment] 2023-08-16 21:13
## Update

Replicated the cases. I continue debugging what is causing this behavior.

**Comment by RamosFe** [comment] 2023-08-17 20:45
## Update

The inconsistent behavior is caused by this line:
https://github.com/wazuh/wazuh/blob/a272f03d698ad355fcdcb7ad5f7a37a693da54bb/framework/wazuh/agent.py#L399

If there is no parenthesis in the `q` param the `group=groudId` statement modifies the conditions of the query:
```
name ~ wazuh OR status ~ active
# AND has more precedence than OR, changing the original condition
group = groupId AND name ~ wazuh OR status ~ active 
```

Added an if condition for adding the corresponding parenthesis in case the `q` query doesn't have it:
https://github.com/wazuh/wazuh/blob/174d26195fdaa6197ed0e3994536698a37b6b771/framework/wazuh/agent.py#L399-L400

Going back to the previous example:

```
name ~ wazuh OR status ~ active
# With the new logic
group = groupId AND (name ~ wazuh OR status ~ active) 
```

### Replicating the examples
```
# Request
{{baseUrl}}/agents

# Response
{
    "data": {
        "affected_items": [
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |wazuh-master |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "127.0.0.1",
                "name": "wazuh-master",
                "version": "Wazuh v4.8.0",
                "lastKeepAlive": "9999-12-31T23:59:59+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:14:02+00:00",
                "ip": "127.0.0.1",
                "manager": "wazuh-master",
                "id": "000",
                "node_name": "master-node",
                "status": "active"
            },
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |74e0845bc09c |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "74e0845bc09c",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:16:07+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:14:14+00:00",
                "ip": "172.18.0.7",
                "manager": "wazuh-worker1",
                "id": "001",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "worker",
                "status": "active"
            },
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |db0fc1c883ab |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "db0fc1c883ab",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:16:12+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:15:06+00:00",
                "ip": "172.18.0.6",
                "manager": "wazuh-master",
                "id": "002",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "master-node",
                "status": "active"
            }
        ],
        "total_affected_items": 3,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```
```
# Request
{{baseUrl}}/groups/:group_id/agents?q=(name~wazuh,status~active)

# Response
{
    "data": {
        "affected_items": [
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |74e0845bc09c |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "74e0845bc09c",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:17:17+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:14:14+00:00",
                "ip": "172.18.0.7",
                "manager": "wazuh-worker1",
                "id": "001",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "worker",
                "status": "active"
            },
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |db0fc1c883ab |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "db0fc1c883ab",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:17:22+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:15:06+00:00",
                "ip": "172.18.0.6",
                "manager": "wazuh-master",
                "id": "002",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "master-node",
                "status": "active"
            }
        ],
        "total_affected_items": 2,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```
```
# Request
{{baseUrl}}/groups/:group_id/agents?q=name~wazuh,status~active

# Response
{
    "data": {
        "affected_items": [
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |74e0845bc09c |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "74e0845bc09c",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:17:47+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:14:14+00:00",
                "ip": "172.18.0.7",
                "manager": "wazuh-worker1",
                "id": "001",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "worker",
                "status": "active"
            },
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |db0fc1c883ab |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "registerIP": "any",
                "name": "db0fc1c883ab",
                "version": "Wazuh v4.8.0",
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "group": [
                    "default"
                ],
                "lastKeepAlive": "2023-08-17T20:17:52+00:00",
                "group_config_status": "synced",
                "dateAdd": "2023-08-17T20:15:06+00:00",
                "ip": "172.18.0.6",
                "manager": "wazuh-master",
                "id": "002",
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "node_name": "master-node",
                "status": "active"
            }
        ],
        "total_affected_items": 2,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents information was returned",
    "error": 0
}
```

### Tests

Added new test for checking these edge cases:
https://github.com/wazuh/wazuh/blob/174d26195fdaa6197ed0e3994536698a37b6b771/framework/wazuh/tests/test_agent.py#L343-L369

*Results*:

```
(venv) federamos@pop-os:~/Documents/Wazuh/Repositories/wazuh/framework/wazuh/tests$ PYTHONPATH=/home/federamos/Documents/Wazuh/Repositories/wazuh/framework/:/home/federamos/Documents/Wazuh/Repositories/wazuh/api python3 -m pytest test_agent.py --disable-warnings
================================================================================= test session starts =================================================================================
platform linux -- Python 3.9.16, pytest-7.4.0, pluggy-0.13.1
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/framework
plugins: metadata-2.0.4, html-2.1.1, tavern-1.23.5
collected 122 items                                                                                                                                                                   

test_agent.py ..........................................................................................................................                                        [100%]

========================================================================== 122 passed, 11 warnings in 3.66s ===========================================================================
```

**Comment by RamosFe** [comment] 2023-08-31 14:03
## Update

When testing the new functionality, the Integration Test with the `q` value `id<5;id!=2;manager~waz;(os.major>14,os.major<20)` fails due to the following error:

```
{
  "title": "Bad Request",
  "detail": "Error in wazuhdb request: Cannot execute Global database query; incomplete input",
  "remediation": "Make sure the request is correct",
  "dapi_errors": {
    "node01": {
      "error": "Error in wazuhdb request: Cannot execute Global database query; incomplete input"
    }
  },
  "error": 2003
}
```

This problem is related to the Issue https://github.com/wazuh/wazuh/issues/16909. This Issue moves to `blocked` until the fix is merged.

**Comment by RamosFe** [comment] 2023-09-18 19:23
## Update
Integration tests results after rebase to `4.5.3`
```
pytest -vv test_agent_GET_endpoints.tavern.yaml
================================================================================= test session starts =================================================================================
platform linux -- Python 3.9.16, pytest-5.0.0, py-1.10.0, pluggy-0.13.1 -- /home/federamos/Documents/Wazuh/Repositories/wazuh/venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.6-76060206-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '5.0.0', 'pluggy': '0.13.1'}, 'Plugins': {'metadata': '2.0.4', 'html': '2.1.1', 'cov': '4.1.0', 'tavern': '1.2.2'}}
rootdir: /home/federamos/Documents/Wazuh/Repositories/wazuh/api/test/integration, inifile: pytest.ini
plugins: metadata-2.0.4, html-2.1.1, cov-4.1.0, tavern-1.2.2
collected 93 items                                                                                                                                                                    

test_agent_GET_endpoints.tavern.yaml::GET /agents PASSED                                                                                                                        [  1%]
test_agent_GET_endpoints.tavern.yaml::GET /agents with single agent id PASSED                                                                                                   [  2%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} PASSED                                                                          [  3%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/config/{component}/{configuration} (only cluster configuration) PASSED                                             [  4%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/group/is_sync PASSED                                                                                               [  5%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/key PASSED                                                                                                         [  6%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/daemons/stats PASSED                                                                                               [  7%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/{agent_id}/stats/{component} PASSED                                                                                           [  8%]
test_agent_GET_endpoints.tavern.yaml::GET /groups PASSED                                                                                                                        [  9%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[md5] PASSED                                                                                                       [ 10%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha1] PASSED                                                                                                      [ 11%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha224] PASSED                                                                                                    [ 12%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha256] PASSED                                                                                                    [ 13%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha384] PASSED                                                                                                    [ 15%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha512] PASSED                                                                                                    [ 16%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2b] PASSED                                                                                                   [ 17%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[blake2s] PASSED                                                                                                   [ 18%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_224] PASSED                                                                                                  [ 19%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_256] PASSED                                                                                                  [ 20%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_384] PASSED                                                                                                  [ 21%]
test_agent_GET_endpoints.tavern.yaml::GET /groups filter hash[sha3_512] PASSED                                                                                                  [ 22%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents PASSED                                                                                                      [ 23%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[configSum] PASSED                                                                             [ 24%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[dateAdd] PASSED                                                                               [ 25%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[group] PASSED                                                                                 [ 26%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[id] PASSED                                                                                    [ 27%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[ip] PASSED                                                                                    [ 29%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[lastKeepAlive] PASSED                                                                         [ 30%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[manager] PASSED                                                                               [ 31%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[mergedSum] PASSED                                                                             [ 32%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[name] PASSED                                                                                  [ 33%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[node_name] PASSED                                                                             [ 34%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.arch] PASSED                                                                               [ 35%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.build] PASSED                                                                              [ 36%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.codename] PASSED                                                                           [ 37%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.major] PASSED                                                                              [ 38%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.minor] PASSED                                                                              [ 39%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.name] PASSED                                                                               [ 40%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.platform] PASSED                                                                           [ 41%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.uname] PASSED                                                                              [ 43%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[os.version] PASSED                                                                            [ 44%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[registerIP] PASSED                                                                            [ 45%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[status] PASSED                                                                                [ 46%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/agents {sort,select}[version] PASSED                                                                               [ 47%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/configuration PASSED                                                                                               [ 48%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files PASSED                                                                                                       [ 49%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[md5] PASSED                                                                                      [ 50%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha1] PASSED                                                                                     [ 51%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha224] PASSED                                                                                   [ 52%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha256] PASSED                                                                                   [ 53%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha384] PASSED                                                                                   [ 54%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha512] PASSED                                                                                   [ 55%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[blake2b] PASSED                                                                                  [ 56%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[blake2s] PASSED                                                                                  [ 58%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_224] PASSED                                                                                 [ 59%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_256] PASSED                                                                                 [ 60%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_384] PASSED                                                                                 [ 61%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files filter hash[sha3_512] PASSED                                                                                 [ 62%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files/{filename}/json PASSED                                                                                       [ 63%]
test_agent_GET_endpoints.tavern.yaml::GET /groups/{group_id}/files/{filename}/xml PASSED                                                                                        [ 64%]
test_agent_GET_endpoints.tavern.yaml::GET /agents?name=agent_name PASSED                                                                                                        [ 65%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group PASSED                                                                                                               [ 66%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[dateAdd] PASSED                                                                                        [ 67%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[id] PASSED                                                                                             [ 68%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[ip] PASSED                                                                                             [ 69%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[name] PASSED                                                                                           [ 70%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[node_name] PASSED                                                                                      [ 72%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[registerIP] PASSED                                                                                     [ 73%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/no_group {sort,select}[status] PASSED                                                                                         [ 74%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/outdated PASSED                                                                                                               [ 75%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct PASSED                                                                                                         [ 76%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[dateAdd] PASSED                                                                                       [ 77%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[id] PASSED                                                                                            [ 78%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[ip] PASSED                                                                                            [ 79%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[lastKeepAlive] PASSED                                                                                 [ 80%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[manager] PASSED                                                                                       [ 81%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[name] PASSED                                                                                          [ 82%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[node_name] PASSED                                                                                     [ 83%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.arch] PASSED                                                                                       [ 84%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.build] PASSED                                                                                      [ 86%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.codename] PASSED                                                                                   [ 87%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.major] PASSED                                                                                      [ 88%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.minor] PASSED                                                                                      [ 89%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.name] PASSED                                                                                       [ 90%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.platform] PASSED                                                                                   [ 91%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.uname] PASSED                                                                                      [ 92%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[os.version] PASSED                                                                                    [ 93%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[registerIP] PASSED                                                                                    [ 94%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[status] PASSED                                                                                        [ 95%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/stats/distinct {fields}[version] PASSED                                                                                       [ 96%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/summary/status PASSED                                                                                                         [ 97%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/summary/os PASSED                                                                                                             [ 98%]
test_agent_GET_endpoints.tavern.yaml::GET /agents/upgrade_result PASSED                                                                                                         [100%]

============================================================================= 93 passed in 393.69 seconds =============================================================================
```

**Closed** 2023-10-25 08:26 UTC
Labels: type/bug, level/task
