### ISSUE TITLE
Upgrade from 3.0.0 on Ubuntu 17.04 show error in logs

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2075] opened 2018-12-11 16:21 UTC
## Bug report

**OS**
_Ubuntu Zesty_

**Wazuh version**
_3.0.0 to 3.7.1_

**Install type**
_Manager_

**Install method**
_packages_

**Log sample**

```
2018/12/11 10:39:23 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
2018/12/11 10:39:23 ossec-execd: INFO: Started (pid: 8133).
2018/12/11 10:39:23 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
2018/12/11 10:39:23 ossec-agentd: INFO: Version detected -> Linux |7f2668830513 |4.4.0-1072-aws |#82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 |x86_64 [Ubuntu|ubuntu: 17.04 (Zesty Zapus)] - Wazuh v3.7.1
2018/12/11 10:39:23 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/12/11 10:39:23 ossec-agentd: INFO: Using AES as encryption method.
2018/12/11 10:39:23 ossec-agentd: INFO: Started (pid: 8138).
2018/12/11 10:39:23 ossec-agentd: INFO: Server IP Address: 172.100.204.212
2018/12/11 10:39:23 ossec-agentd: INFO: Trying to connect to server (172.100.204.212:1514/udp).
2018/12/11 10:39:23 ossec-agentd: INFO: (4102): Connected to the server (172.100.204.212:1514/udp).
2018/12/11 10:39:23 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2018/12/11 10:39:23 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\\([[:alnum:]]\\+\\)\\ \\+[[:digit:]]\\+\\ \\+[[:digit:]]\\+\\ \\+\\(.*\\):\\([[:digit:]]*\\)\\ \\+\\([0-9\\.\\:\\*]\\+\\).\\+\\ \\([[:digit:]]*\\/[[:alnum:]\\-]*\\).*/\\1 \\2 == \\3 == \\4 \\5/' | sort -k 4 -g | sed 's/ == \\(.*\\) ==/:\\1/' | sed 1,2d
2018/12/11 10:39:23 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2018/12/11 10:39:23 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/12/11 10:39:23 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2018/12/11 10:39:23 ossec-logcollector: INFO: Started (pid: 8151).
2018/12/11 10:39:23 wazuh-modulesd: INFO: Process started.
2018/12/11 10:39:23 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/12/11 10:39:26 ossec-syscheckd: INFO: Started (pid: 8146).
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Monitoring directory: '/boot', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/12/11 10:39:26 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/12/11 10:39:26 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/12/11 10:39:26 rootcheck: INFO: Started (pid: 8146).
2018/12/11 10:39:41 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/12/11 10:39:41 ossec-syscheckd: INFO: Starting syscheck scan.
2018/12/11 10:39:41 rootcheck: INFO: Starting rootcheck scan.
2018/12/11 10:39:46 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/12/11 10:39:53 rootcheck: INFO: Ending rootcheck scan.
2018/12/11 10:39:56 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2018/12/11 10:39:57 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
2018/12/11 10:39:57 ossec-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/11 10:39:57 ossec-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/11 10:39:57 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/11 10:39:57 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2018/12/11 10:39:57 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/11 10:39:57 ossec-execd: ERROR: (1129): Could not unlink file '/var/ossec/var/run/ossec-execd-8133.pid' due to [(2)-(No such file or directory)].
2018/12/11 10:39:58 ossec-execd: INFO: Started (pid: 8507).
2018/12/11 10:39:58 ossec-agentd: INFO: Using notify time: 60 and max time to reconnect: 300
2018/12/11 10:39:58 ossec-agentd: INFO: Version detected -> Linux |7f2668830513 |4.4.0-1072-aws |#82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 |x86_64 [Ubuntu|ubuntu: 17.04 (Zesty Zapus)] - Wazuh v3.7.1
2018/12/11 10:39:58 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/12/11 10:39:58 ossec-agentd: INFO: Using AES as encryption method.
2018/12/11 10:39:58 ossec-agentd: INFO: Started (pid: 8512).
2018/12/11 10:39:58 ossec-agentd: INFO: Server IP Address: 172.100.204.212
2018/12/11 10:39:58 ossec-agentd: INFO: Trying to connect to server (172.100.204.212:1514/udp).
2018/12/11 10:39:58 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2018/12/11 10:39:58 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\\([[:alnum:]]\\+\\)\\ \\+[[:digit:]]\\+\\ \\+[[:digit:]]\\+\\ \\+\\(.*\\):\\([[:digit:]]*\\)\\ \\+\\([0-9\\.\\:\\*]\\+\\).\\+\\ \\([[:digit:]]*\\/[[:alnum:]\\-]*\\).*/\\1 \\2 == \\3 == \\4 \\5/' | sort -k 4 -g | sed 's/ == \\(.*\\) ==/:\\1/' | sed 1,2d
2018/12/11 10:39:58 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2018/12/11 10:39:58 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/12/11 10:39:58 ossec-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2018/12/11 10:39:58 ossec-logcollector: INFO: Started (pid: 8523).
2018/12/11 10:39:58 wazuh-modulesd: INFO: Process started.
2018/12/11 10:39:58 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/12/11 10:39:59 ossec-agentd: INFO: (4102): Connected to the server (172.100.204.212:1514/udp).
2018/12/11 10:40:01 ossec-syscheckd: INFO: Started (pid: 8517).
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Monitoring directory: '/boot', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/12/11 10:40:01 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/12/11 10:40:01 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/12/11 10:40:01 rootcheck: INFO: Started (pid: 8517).
2018/12/11 10:40:03 ossec-logcollector: INFO: Agent is now online. Process unlocked, continuing...
2018/12/11 10:40:16 rootcheck: INFO: Starting rootcheck scan.
2018/12/11 10:40:16 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/12/11 10:40:16 ossec-syscheckd: INFO: Starting syscheck scan.
2018/12/11 10:40:21 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/12/11 10:40:26 rootcheck: INFO: Ending rootcheck scan.
2018/12/11 10:40:42 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2018/12/11 10:40:47 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
```

Bug description
----------------
This error appears on upgrade process to 3.7.1 from 3.0.0, the error seems to appear when daemons are stopped.

**Comment by vikman90** [comment] 2018-12-17 09:54
This issue is duplicate of #2071.

**Comment by JuantAldea** [comment] 2019-04-17 09:23
Closing as duplicate. 
Related issues: https://github.com/wazuh/wazuh/issues/2071, https://github.com/wazuh/wazuh/issues/2072, https://github.com/wazuh/wazuh/issues/2074, https://github.com/wazuh/wazuh/issues/2075, https://github.com/wazuh/wazuh/issues/2095

Please reopen if the error manifest again.

**Closed by JuantAldea** 2019-04-17 09:23 UTC
Labels: bug, core/fim, duplicate
