### ISSUE TITLE
Increase of RSS/FSS/USS in the manager

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#21517] opened 2024-01-18 10:33 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Rootcheck | Manager | Packages | CentOS |

## Description

During the analysis performed in the rootcheck stress test, in https://github.com/wazuh/wazuh/issues/21491, it could be seen, compared with the same test in 4.7.2 RC 2, in https://github.com/wazuh/wazuh/issues/21269, that the RSS/FSS/USS usage has increased in the manager:

- **4.8.0-alpha2**:
  
  ![image](https://github.com/wazuh/wazuh/assets/80041853/151f1841-a72b-4811-80ab-68485865e05b)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/7268c390-43f4-4ab1-b4ba-a6db1c5f9a69)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/f56ad197-1068-48d5-af97-93e49437b97c)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/2f4858c5-5f23-4e7e-a728-fb20abd56678)

- **4.7.2-rc2**:
  
  ![image](https://github.com/wazuh/wazuh/assets/80041853/44f1dac8-27d2-4031-a0b6-38b26f5af4d0)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/e19e8598-5e87-4f77-a327-e61ba2ad6746)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/d14b9ce5-c96e-4527-90c7-13870461c2fe)
  ![image](https://github.com/wazuh/wazuh/assets/80041853/48280310-d163-4dc0-9efc-38dfd0a7e498)

**Comment by jnasselle** [comment] 2024-01-18 12:51
## Update
This also happens in [Release 4.8.0 - Alpha 2 - Footprint Metrics - LOGCOLLECTOR (2.5d)](https://github.com/wazuh/wazuh/issues/21497#top)
#21497

Seems to be an increase for logcollector, analysisd and modules

- 4.8.0-alpha2
![image](https://github.com/wazuh/wazuh/assets/1791430/1e5760a5-4318-443e-8a91-57fd4e419dd3)

- 4.7.2-rc2 (https://github.com/wazuh/wazuh/issues/21276)

![image](https://github.com/wazuh/wazuh/assets/1791430/3d765d94-b871-44e8-a07b-3d46f7b35dae)

**Comment by Rebits** [comment] 2024-01-18 12:56
This also happen in https://github.com/wazuh/wazuh/issues/21503

**Comment by nbertoldo** [comment] 2024-01-30 21:10
The test reports have been analysed and it can be seen that the modules with significant variations in memory usage are `wazuh-db` (decrease), `modulesd` and `remoted` (increase).

![image](https://github.com/wazuh/wazuh/assets/117279646/324089c3-d64b-4950-b3cb-aff23f49a7b0)

**Comment by nbertoldo** [comment] 2024-01-31 20:39
Continuing with the analysis, the results of `4.8.0-alpha1` have been compared with `4.7.2-RC2`. 

![image](https://github.com/wazuh/wazuh/assets/117279646/9d23b995-474e-4c2b-90b7-de36ff177b42)

Considering also the [previous analysis](https://github.com/wazuh/wazuh/issues/21517#issuecomment-1917900395), the following can be seen:
- wazuh-db: there is a significant decrease from `4.8.0-alpha1`. Probably due to improvements made in [#16058](https://github.com/wazuh/wazuh/pull/16058) or [#18476](https://github.com/wazuh/wazuh/pull/18476)
- modulesd and remoted: there is a significant increase from `4.8.0-alpha2`. Probably due to changes introduced in [#21201](https://github.com/wazuh/wazuh/pull/21201).

@Dwordcito @TomasTurina please could you confirm if these could be the causes?

**Comment by cborla** [comment] 2024-02-01 12:11
This case is related to https://github.com/wazuh/wazuh/issues/21545

**Comment by TomasTurina** [comment] 2024-02-01 18:17
About `wazuh-db` analysis, I agree with that.

**Comment by Dwordcito** [comment] 2024-02-02 02:00
closed as duplicated of https://github.com/wazuh/wazuh/issues/21545

**Closed by Dwordcito** 2024-02-02 02:00 UTC
Labels: type/bug, level/task, qa_known
