### ISSUE TITLE
nodes not connecting all of a sudden

### ISSUE THREAD

**Issue by evilpete** [wazuh/wazuh#809] opened 2018-06-18 17:44 UTC
I am suddenly getting a error with cluster nodes not connecting with the master,  do you have any suggestions on where to look ( library compatibility error ?) 

I am running  wazuh-api / wazuh-manager  version     3.2.4 on Ubuntu 16.04.4 servers

cluster.log:

```
2018-06-18 17:19:57,509 INFO    : [Client] PID: 2736
2018-06-18 17:19:57,569 INFO    : [Client] Connecting to 10.255.255.20:1516.
2018-06-18 17:19:57,569 INFO    : [Client] Disconnected.
2018-06-18 17:19:57,569 ERROR   : [Transport-Handler] Error: 'from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object'.
```

Relevant ossec.conf sections :   

```
  <remote>
    <connection>secure</connection>
    <port>1514</port>
    <!-- ipv6>::/0</ipv6 -->
    <protocol>tcp</protocol>
    <queue_size>16384</queue_size>
  </remote>
. . . 
  <cluster>
    <name>wazuh</name>
    <node_name>wazuh-use1-076</node_name>
    <node_type>client</node_type>
    <key>ABCDEFGHIJKNOTMYKEY</key>
    <port>1516</port>
    <bind_addr>0.0.0.0</bind_addr>
    <nodes>
         <node>10.255.255.20</node>
    </nodes>
    <hidden>no</hidden>
    <disabled>no</disabled>
  </cluster>
```

Hete is a trace:

```
root@wazuh-use1-076:/var/ossec/logs# /var/ossec/bin/cluster_control -d -l
DEBUG: [Transport-InternalSocketSend] Starting: /var/ossec///queue/cluster/c-internal.sock.
DEBUG: [Transport-InternalSocketSend] Sending request: 'get_nodes {}'.
DEBUG: [Transport-InternalSocketSend] Request sent.
DEBUG: [Transport-InternalSocketSend] Answer received: 'err'.
DEBUG: [Transport-InternalSocketSend] Closing socket.
DEBUG: [Transport-InternalSocketSend] Socket closed.
ERROR: string indices must be integers
Traceback (most recent call last):
  File "/var/ossec/bin/cluster_control", line 360, in <module>
    print_nodes_status(args.filter_node)
  File "/var/ossec/bin/cluster_control", line 231, in print_nodes_status
    data = [[nodes[node_name]['name'], nodes[node_name]['ip'], nodes[node_name]['type'], nodes[node_name]['version']] for node_name in sorted(nodes.keys())]
TypeError: string indices must be integers
```

I added a pprint(nodes) to like 230 and saw this:
`{u'err': u'Trying to send and there is no connection with the server'}`

**Comment by evilpete** [comment] 2018-06-18 17:48
looking closer I see  one of the node servers came up with version 3.3.0,  could this have sent data tha cause problems with other  the 3.2.4  node server via a 3.2.4 Master?

 I will  run a full upgrade and report back

**Comment by jesuslinares** [comment] 2018-06-18 17:52
Hi @evilpete,

The nodes must be in the same _major.minor_ version. We recommend using at least the v3.2.3 version since we added several bug fixes.

The last issue with cluster control is fixed in 3.3: https://github.com/wazuh/wazuh/pull/762.

Regards,
Jesus Linares.

**Comment by evilpete** [comment] 2018-06-18 18:03
was running  3.2.4  on 6 node server in 5 regions with a 3.2.4 Master,  then one  of the Node accidentally upgraded to 3.3 and things went bad across the cluster.

I am pushing 3.3 across the board now and will restart

**Comment by evilpete** [comment] 2018-06-18 18:12
Ok this is odd:

I am running 3.3.0 on masters and servers :


**wazuh00%**  `dpkg -l | grep wazuh`
```
ii  wazuh-api                        3.3.0-1                        
ii  wazuh-manager                    3.3.0-1
```

and on the Nodes : 

**wazuh00%**  ` ssh 10.255.252.5  dpkg -l | grep wazuh`

```
ii  wazuh-api                        3.3.0-1                        
ii  wazuh-manager                    3.3.0-1
```

yet 

**wazuh00%**  `/var/ossec/bin/cluster_control -l`
```
-----------------------------------------------
Name            Address         Type    Version
-----------------------------------------------
wazuh-usw1-005  10.255.252.5    client  3.2.4
wazuh-usw1-070  10.255.252.70   client  3.2.4
wazuh-usw2-116  10.255.254.116  client  3.2.4
wazuh-usw2-172  10.255.254.172  client  3.2.4
wazuh00         10.255.255.20   master  3.2.4
-----------------------------------------------
```

and I  have restarted  and rebooted , yet I am getting client  3.2.4 as the reported version ???

**Comment by jesuslinares** [comment] 2018-06-18 18:16
Please, stop Wazuh and check that all daemons are stopped (ps aux | grep ossec). It is really weird.

**Comment by evilpete** [comment] 2018-06-18 18:23
just rebooted everything, will report back after lunch .

**Comment by evilpete** [comment] 2018-06-18 22:17
I see newer update  release just  3.3.1,  the Master now self identified as  3.3.1 but non (upgraded) node servers can connect, no error message.

**#**  `/var/ossec/bin/wazuh-clusterd  -V`

`Wazuh 3.3.1 - Wazuh Inc`

**#** `/var/ossec/bin/wazuh-clusterd  -f -d`

```
2018-06-18 22:12:43,504 DEBUG   : [Cluster] Removing '/var/ossec//queue/cluster/'.
2018-06-18 22:12:43,504 DEBUG   : [Cluster] Removed '/var/ossec//queue/cluster/'.
2018-06-18 22:12:43,504 INFO    : [Master] PID: 24577
2018-06-18 22:12:43,505 INFO    : [Master] Listening '0.0.0.0:1516'.
2018-06-18 22:12:43,505 DEBUG   : [Master] Creating threads.
2018-06-18 22:12:43,505 DEBUG   : [Master] [IntegrityControl] Calculating.
2018-06-18 22:12:43,505 DEBUG   : [Master] Threads created.
2018-06-18 22:12:43,508 DEBUG   : [Master] [IntegrityControl] Calculated.
2018-06-18 22:12:45,508 INFO    : [Master] [Internal-COM ]: Ready.
2018-06-18 22:12:49,249 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:49,416 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:49,416 INFO    : [Master] Connection with 10.254.252.6 closed.
2018-06-18 22:12:49,416 INFO    : [Master] Connection with 10.254.252.74 closed.
2018-06-18 22:12:50,082 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:50,083 INFO    : [Master] Connection with 10.254.253.101 closed.
2018-06-18 22:12:50,108 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:50,108 INFO    : [Master] Connection with 10.254.253.77 closed.
2018-06-18 22:12:50,374 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:50,375 INFO    : [Master] Connection with 10.254.255.152 closed.
2018-06-18 22:12:50,930 DEBUG   : [Transport-Server] Incoming connection.
2018-06-18 22:12:50,931 INFO    : [Master] Connection with 10.254.255.186 closed.
```

**Comment by evilpete** [comment] 2018-06-18 22:31
The Error is on the server Nodes : 

r**oot@wazuh-use2-152:/var/ossec/logs#** `/var/ossec/bin/wazuh-clusterd -f -d`
```
2018-06-18 22:29:07,765 DEBUG   : [Cluster] Removing '/var/ossec//queue/cluster/'.
2018-06-18 22:29:07,766 DEBUG   : [Cluster] Removed '/var/ossec//queue/cluster/'.
2018-06-18 22:29:07,766 INFO    : [Client] PID: 11112
2018-06-18 22:29:07,807 DEBUG   : [Master] Creating threads.
2018-06-18 22:29:07,810 INFO    : [Client] Connecting to 10.254.255.170:1516.
2018-06-18 22:29:07,810 INFO    : [Client] Disconnected.
2018-06-18 22:29:07,810 ERROR   : [Transport-Handler] Error: 'from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object'.
2018-06-18 22:29:07,811 DEBUG   : [Transport-Handler] Error: '<type 'exceptions.TypeError'>' - '[/usr/lib/python2.7/asyncore.py|write|91] [/usr/lib/python2.7/asyncore.py|handle_write_event|467] [/usr/lib/python2.7/asyncore.py|handle_connect_event|455] [/var/ossec/bin/../framework/wazuh/cluster/client.py|handle_connect|39] [/var/ossec/bin/../framework/wazuh/cluster/communication.py|handle_connect|644] [/var/ossec/bin/../framework/wazuh/cluster/communication.py|msgbuild|74] [/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py|encrypt|51] [/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py|_encrypt_from_parts|62] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py|update|149] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py|update|120] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py|update_into|131]'.
2018-06-18 22:29:07,811 ERROR   : [Client] Disconnected. Trying to connect again in 10s.
2018-06-18 22:29:07,811 DEBUG   : [Client] Cleaning threads. Start.
2018-06-18 22:29:07,811 DEBUG   : [Client] Cleaning main threads
2018-06-18 22:29:08,828 DEBUG   : [Client] Cleaning handler threads.
2018-06-18 22:29:08,828 DEBUG   : [Transport-Handler] Cleaning handler threads. Start.
2018-06-18 22:29:08,828 DEBUG   : [Transport-Handler] Cleaning handler threads. End.
2018-06-18 22:29:08,828 DEBUG   : [Client] Cleaning threads. End.
2018-06-18 22:29:09,771 INFO    : [Client] [Internal-COM ]: Ready.
2018-06-18 22:29:18,836 DEBUG   : [Master] Creating threads.
2018-06-18 22:29:18,838 INFO    : [Client] Connecting to 10.254.255.170:1516.
2018-06-18 22:29:18,838 INFO    : [Client] Disconnected.
2018-06-18 22:29:18,838 ERROR   : [Transport-Handler] Error: 'from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object'.
2018-06-18 22:29:18,839 DEBUG   : [Transport-Handler] Error: '<type 'exceptions.TypeError'>' - '[/usr/lib/python2.7/asyncore.py|write|91] [/usr/lib/python2.7/asyncore.py|handle_write_event|467] [/usr/lib/python2.7/asyncore.py|handle_connect_event|455] [/var/ossec/bin/../framework/wazuh/cluster/client.py|handle_connect|39] [/var/ossec/bin/../framework/wazuh/cluster/communication.py|handle_connect|644] [/var/ossec/bin/../framework/wazuh/cluster/communication.py|msgbuild|74] [/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py|encrypt|51] [/usr/local/lib/python2.7/dist-packages/cryptography/fernet.py|_encrypt_from_parts|62] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/primitives/ciphers/base.py|update|149] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py|update|120] [/usr/local/lib/python2.7/dist-packages/cryptography/hazmat/backends/openssl/ciphers.py|update_into|131]'.
2018-06-18 22:29:18,839 ERROR   : [Client] Disconnected. Trying to connect again in 10s.
```

**Comment by mgmacias95** [comment] 2018-06-18 22:59
Hello @evilpete,

I've been doing a little research about that problem. I found out (https://github.com/pyca/cryptography/commit/0517d1ae49061f486e2e4d279d70b6b61361de2f#commitcomment-28344071) that the issue is caused because an old version of `cffi` is installed. Did you installed it using `apt`? If so, try the following:

```shellsession
# apt-get purge --auto-remove python-cffi
# pip install --upgrade cffi
```

Best regards,
Marta

**Comment by evilpete** [comment] 2018-06-18 23:52
@mgmacias95  cffi is installed and up to date:


`Requirement already up-to-date: cffi in /usr/local/lib/python2.7/dist-packages (1.11.5)`

So I did a forced reinstall `pip install --force-reinstall  cffi`
and eventually :  
 **%** `pip install --force-reinstall  cffi cryptography six pyOpenSSL ipaddress   enum34`
. . . 
`Successfully installed asn1crypto-0.24.0 cffi-1.11.5 cryptography-2.2.2 enum34-1.1.6 idna-2.7 ipaddress-1.0.22 pyOpenSSL-18.0.0 pycparser-2.18 six-1.11.0`

**Comment by mgmacias95** [comment] 2018-06-18 23:54
Hello @evilpete,

Did that work for you? 

Best regards,
Marta

**Comment by evilpete** [comment] 2018-06-18 23:58
Sorry, Nope...


I am running
16.04.4 LTS (Xenial Xerus) on aws from the AMI :  
`ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20180509`
( if you want to be exact )

**Comment by mgmacias95** [comment] 2018-06-19 00:09
Hello @evilpete,

Does the same error happen using Python 3? Ubuntu 16 has python 3 installed by default. If you want Python3 to be the default python interpreter for wazuh, you have to change the following in both `/bin/wazuh-clusterd` and `/bin/cluster_control` to `#!/usr/bin/python3`:

https://github.com/wazuh/wazuh/blob/55ba4d755a124d09557b77f8c41eae870a3e365d/framework/scripts/wazuh-clusterd.py#L1

Best regards,
Marta

**Comment by evilpete** [comment] 2018-06-19 00:31
yes it seems to work with python 3 and python3

here are the package IDs:

ii  python3-cryptography             1.2.3-1ubuntu0.1                           amd64        Python library exposing cryptographic recipes and primitives (Python 3)
ii  python3-minimal                  3.5.1-3                                    amd64        minimal subset of the Python language (default python3 version)

I am attaching the output of `pip3 list` and `pip2 list` if they can be any help
(the py2 I assume is wacked by now due the multiple forced  install / removes of packages with both pip and apt-get ) 

[py3pkgs.txt](https://github.com/wazuh/wazuh/files/2113390/py3pkgs.txt)
[py2pkgs.txt](https://github.com/wazuh/wazuh/files/2113391/py2pkgs.txt)

**Comment by mgmacias95** [comment] 2018-06-19 00:34
Hello @evilpete,

Thank you so much for doing the Python 3 test. I recommend you to keep using python 3. We'll do some more research on the Python 2 issue using the information that you've posted (thank you for that too!). If your problem is solved, I'll close the issue 😄 .

Best regards,
Marta

**Closed by mgmacias95** 2018-06-19 00:34 UTC

**Comment by evilpete** [comment] 2018-06-19 00:36
If you need any help in narrowing down a functional package combinations   just send me a direct IM

**Comment by evilpete** [comment] 2018-06-19 01:00
BTW:  you may want to add some extra error checking around  "/var/ossec/bin/cluster_control", line 231 .  ( see the posted I the first message )

**Comment by mgmacias95** [comment] 2018-06-19 01:07
Hello @evilpete,

We worked on that in https://github.com/wazuh/wazuh/pull/762. That code was released in Wazuh v3.3.1 (today). I'll review the bug that you've reported to see if it's still failing in the new version.

Thanks,
Marta

**Comment by evilpete** [comment] 2018-07-13 21:19
@mgmacias95 :

I recently started getting the following errors:
is this related to the previous SSLlib python bug ?

client:cluster.log:

```
2018-07-13 20:58:49,429 INFO    : [Client] [Integrity-S  ]: Start.
2018-07-13 20:58:49,429 INFO    : [Client] [Integrity-S  ]: Asking permission to sync.
2018-07-13 20:58:49,480 INFO    : [Client] [Integrity-S  ]: Permission granted.
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Reason: 'Interval'
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Master found: 10.254.255.170.
2018-07-13 20:58:54,484 INFO    : [Client] [Integrity-S  ]: Gathering files.
2018-07-13 20:58:54,486 INFO    : [Client] [Integrity-S  ]: Gathered files: 10.
2018-07-13 20:58:54,487 INFO    : [Client] [Integrity-S  ]: Sending files to master.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Sync accepted by the master.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Result: Successfully.
2018-07-13 20:58:54,795 INFO    : [Client] [Integrity-S  ]: Locking: Waiting for receiving Master response and process the integrity if necessary.
2018-07-13 20:58:54,895 INFO    : [Client] [Integrity    ]: The master was not able to verify the integrity.
2018-07-13 20:58:54,896 INFO    : [Client] [Integrity-S  ]: Unlocking: Master sent the response and the integrity was processed if necessary.
2018-07-13 20:58:54,896 INFO    : [Client] [Integrity-S  ]: End. Sleeping: 19s.
```


Master:cluster.log:
```
2018-07-13 20:56:45,163 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Reception completed: Time: 0.24s.
2018-07-13 20:56:45,163 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Analyzing client integrity: Start.
2018-07-13 20:56:45,163 ERROR   : [Master] [wazuh-usw2-041] [Integrity-R  ]: Error decompressing data: the JSON object must be str, not 'bytes'
2018-07-13 20:56:45,163 ERROR   : [Master] [wazuh-usw2-041] [Integrity-R  ]: Result: Unknown error: the JSON object must be str, not 'bytes'.
2018-07-13 20:56:45,164 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Sending Sync-Error to client.
2018-07-13 20:56:45,234 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Sync accepted by the client.
2018-07-13 20:56:45,234 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: Unlocking 'sync_integrity_free' due to error.
2018-07-13 20:56:45,334 INFO    : [Master] [wazuh-usw2-041] [Integrity-R  ]: End.
```

**Comment by evilpete** [comment] 2018-07-14 01:15
Yup it was.. python crypto bug

**Comment by evilpete** [comment] 2018-07-14 17:08
can you send me a direct email, I should be able to clone the hosts and
give you direct access
