### ISSUE TITLE
Nasty Bug in Windows Agent v3.8.2 EventChannel Query Filter Processing.

### ISSUE THREAD

**Issue by gjahchan** [wazuh/wazuh#2731] opened 2019-03-03 11:38 UTC
More than two XPATH filter expressions pointing to the same file extension in a File ObjectName cause the agent to refuse to start.

In the attached sanitized rule snippet, If I uncomment the third rule the agent will refuse to start.

Similar behavior is exhibited regardless of the extension, so long as it is the same in more than two rules. Two rules work, at the count of three the agent service fails.

The order of the rules does not matter, and they could be scattered in the Query section among other file extensions, _it makes no difference_. As soon as a third rule with the same ObjectName extension as two existing ones is activated, the agent goes boom.

It took me a very long time to zero in on the conditions that are causing the agent to refuse to start, it should however be trivial to reproduce in the lab.

[XPATH Query Filter Bug.txt](https://github.com/wazuh/wazuh/files/2923049/XPATH.Query.Filter.Bug.txt)

**Comment by cristgl** [comment] 2019-03-15 10:21
Hello @gjahchan,

I have been trying to reproduce the issue you are experiencing. Can you try this block from below?

```
  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>
      \<QueryList>
        \<Query Id="0" Path="Security">
          \<Select Path="Security">*[System[band(Keywords,9007199254740992) and (EventID=4656 or EventID=4663)]]\</Select>
          \<Suppress Path="Security">(*[EventData[Data[@Name="ObjectName"]="C:\\Users\\&lt;sanitized&gt;\\&lt;sanitized&gt;\\filename1.zip"]])\</Suppress>
          \<Suppress Path="Security">(*[EventData[Data[@Name="ObjectName"]="C:\\Users\\&lt;sanitized&gt;\\&lt;sanitized&gt;\\&lt;sanitized&gt;\\Filename2.zip"]])\</Suppress>
          \<Suppress Path="Security">(*[EventData[Data[@Name="ObjectName"]="C:\\Users\\&lt;sanitized&gt;\\&lt;sanitized&gt;\\&lt;sanitized&gt;\\Filename3.zip"]])\</Suppress>
        \</Query>
      \</QueryList>
    </query>
  </localfile>
```

I don't really know what do you mean with '<sanitized>' but we cannot write the characters '<' and '>' inside an XML query. I hope this can help, could you verify that this works for you please?

Best regards,
Cristina

**Comment by gjahchan** [comment] 2019-03-15 20:36
To test, replace '\<sanitized\>' with 'sanitized'.

**Comment by Zenidd** [comment] 2019-06-19 09:13
Hello @gjahchan,

Are you still experiencing this issue ? You can read the @cristgl answer on our mail list https://groups.google.com/forum/#!topic/wazuh/i5N2-oU9viw


<br></br>
Greetings,

Juan Pablo Sáez

**Comment by cristgl** [comment] 2019-08-26 09:23
Hi @gjahchan,

I am closing this issue as there are no new replies since March. If you have any doubts or you are experiencing new bugs, you can reopen this issue or a new one and we will be glad to help you.

Kind regards,
Cristina

**Closed by cristgl** 2019-08-26 09:23 UTC
Labels: community, status/awaiting reply
