### ISSUE TITLE
Critical error while installing Wazuh Agent in Windows Server 2022

### ISSUE THREAD

**Issue by hossam1522** [wazuh/wazuh#26067] opened 2024-09-30 15:21 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh Agent | Agent | Packages | OS version |

While doing the upgrade test in https://github.com/wazuh/wazuh/issues/26002#issuecomment-2383483688, it has been detected the following error while installing Wazuh Agent 4.9.0:

```
PS C:\Users\vagrant\Downloads> .\wazuh-agent-4.9.0-1.msi /q WAZUH_MANAGER="x.x.x.x"
PS C:\Users\vagrant\Downloads> NET START Wazuh
The Wazuh service is starting.
The Wazuh service could not be started.

The service did not report an error.

More help is available by typing NET HELPMSG 3534.

PS C:\Users\vagrant\Downloads> NET START Wazuh

The Wazuh service was started successfully.
```

It is worth mentioning that the manager is an Ubuntu 24 ARM.

When analyzing the logs, the following information is obtained:

```
PS C:\Program Files (x86)\ossec-agent> Get-Content ossec.log | findstr ERROR
2024/09/30 14:54:29 wazuh-agent: ERROR: CryptAcquireContext Flag: NewKeySet (1): (8009000f)

PS C:\Program Files (x86)\ossec-agent> Get-Content ossec.log | findstr WARNING

PS C:\Program Files (x86)\ossec-agent> Get-Content ossec.log | findstr CRITICAL
2024/09/30 14:54:29 wazuh-agent: CRITICAL: randombytes failed for all possible methods for accessing random data
```

- ossec.log:  [ossec.log](https://github.com/user-attachments/files/17192261/ossec.log)

- ossec.conf: [ossec.txt](https://github.com/user-attachments/files/17192319/ossec.txt)

- Manager ossec.log: [ossec-manager.log](https://github.com/user-attachments/files/17192484/ossec-manager.log)

I also consider it important to mention that, despite the error, the upgrade to 4.9.1-RC 2 was successful and everything seems to be working perfectly. More research is required.

**Comment by vikman90** [comment] 2024-10-01 10:17
This issue is a duplicate of:
- #22630

According to the code and the explanation by @pereyra-m, it appears that the Wazuh Agent encountered a problem accessing its cryptographic container. The error codes suggest that the key container either could not be accessed due to permission issues or a new container could not be created because one already exists but access was denied.

We recommend using **Process Monitor** to track the key container used by the Wazuh Agent. You can apply the following filters:

- Process name contains "Wazuh"
- Path contains `S-1-5-18`

Be sure to **disable registry activity tracking** for clearer results. Once the specific key container is identified, stopping the agent and deleting this key should allow the agent to recreate it upon restarting.

Could you please confirm if this issue is reproducible? If so, please provide additional details and logs. If the issue was resolved in a subsequent attempt, we can proceed with closing the issue.

Best regards,

**Comment by hossam1522** [comment] 2024-10-01 13:58
Hello @vikman90, there is no useful information provided by Process Monitor using those filters.

![image](https://github.com/user-attachments/assets/2a3a5c93-1342-4339-898c-1df33ccf7bb7)

Also, I have not been able to replicate the error, plus the manager has been running without major problem.

Is there anything else I can try or provide?

**Comment by vikman90** [comment] 2024-10-01 14:54
@hossam1522 Thank you for the update.

To clarify, this issue is specific to the agent and is not related to the manager. The error occurs when the agent initializes the **random number generator**. It attempts to use an existing cryptographic container, and if it cannot, it tries to create a new one. In your case, **the agent failed to both access an existing container and create a new one**.

@pereyra-m’s suggestion in the related issue was to use Process Monitor to analyze what happens at the moment the error occurs, which requires the problem to be reproduced first.

This issue has only been reported a few times in the last six years, so while there is definitely a problem, it is quite elusive:

- https://github.com/wazuh/wazuh/issues/22630
- https://github.com/wazuh/wazuh/issues/1825
   - https://github.com/wazuh/wazuh/pull/1898 (fixed in v3.7.1)

It’s possible that there was a previous agent on the same host, or that the UI and service were started at the same time. Alternatively, the update may have cleaned up the installation, or two programs could have been attempting to create the cryptographic container simultaneously.

Since the issue is no longer reproducible and the agent is now functioning properly, we will go ahead and close the issue. If you encounter the problem again, please feel free to reopen this issue or #22630 and notify us so we can investigate while the error is still present.

Thank you for your help!

Best regards,

**Closed by vikman90** 2024-10-01 14:54 UTC
Labels: type/bug, level/task
