### ISSUE TITLE
oscap Ubuntu 20.04

### ISSUE THREAD

**Issue by kovaga** [wazuh/wazuh#5395] opened 2020-07-03 13:05 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |
 3.13.01 | OSCAP  | Agent| Packages | Ubuntu 20.04

The module OSCAP does not run and logs the following error.
"wazuh-modulesd:oscap: ERROR: Internal error. Exiting..."

the problem can be resolved by changing python to python2 in the 

/var/ossec/wodles/oscap/oscap.py

So it reads
#!/usr/bin/env python2

p.s. The current version of the libopenscap8 that is supplied in ubuntu 20.04 is suffering from a bug itself and is unable to evaluate existing ubuntu oval file. Thus needs to be recompiled with the minor patch as per this post.

https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1688223.html

**Comment by vikman90** [comment] 2020-07-06 07:47
Hi @kovaga,

This issue is a duplicate of #4879. We must decide whether to go to Python 3 or require Python 2, and test that all supported platforms work with `python2`.

In the meantime, I commented a workaround for Ubuntu 20.04 and CentOS 8: https://github.com/wazuh/wazuh/issues/4879#issuecomment-635949993

Hope that helps.
Let me close this issue. Please comment on #4879 anything you need regarding this matter.

Best regards.

**Closed by vikman90** 2020-07-06 07:47 UTC
Labels: community, duplicate
