### ISSUE TITLE
Cluster synchronization stores old information

### ISSUE THREAD

**Issue by sdvendramini** [wazuh/wazuh#24401] opened 2024-07-03 11:04 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh-cluster | Manager | Packages/Sources | Linux |

## Description

During the tests performed on this [issue](https://github.com/wazuh/wazuh/issues/24106) by the @wazuh/devel-pyserver team, a problem was encountered when synchronizing the cluster. 

During the tests there are agents connected to a cluster with 3 nodes. When an agent connected to a worker node restarts and connects to the manager node we see that the information in its database is wrong. Since it is updated with old data sent by the cluster. 

Once the agent is restarted and jumps to the manager we see that the first query is `update-keepalive` that passes the agent to `pending`, this is because a `HC_STARTUP` message has been received in the master node. At this point the `status_code` and `disconnection_time` are set to 0:

`2024/07/02 14:54:16 wazuh-db[169] wdb_parser.c:859 at wdb_parse(): DEBUG: Global query: update-keepalive {"id":1,"connection_status":"pending","sync_status":"synced"}`

Then the `keep_alive` messages start arriving, changing the status to active, and executing the `update-agent-data` query, without setting `status_code` and `disconnection_time`, since these values are supposed to have been set to 0 with the `HC_STARTUP` message:

`2024/07/02 14:54:16 wazuh-db[169] wdb_parser.c:859 at wdb_parse(): DEBUG: Global query: update-agent-data {"id":1,"version":"Wazuh v4.9.0","config_sum":"29e0926e5a77442212e824868a2a61df","merged_sum":"b4ef190a63d49289df870a85be158ff5","manager_host":"wazuh-master","node_name":"master-node","agent_ip":"172.19.0.7","labels":"#\"_manager_hostname\":wazuh-master\n#\"_agent_ip\":172.19.0.7\n#\"_node_name\":master-node\n#\"_wazuh_version\":Wazuh v4.9.0","connection_status":"active","sync_status":"synced","group_config_status":"synced","os_name":"Ubuntu","os_version":"20.04.1 LTS","os_major":"20","os_minor":"04","os_codename":"Focal Fossa","os_platform":"ubuntu","os_uname":"Linux |wazuh-agent1 |5.15.0-112-generic |#122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 |x86_64","os_arch":"x86_64"}
`

Finally, after a few seconds the cluster synchronization information arrives, which is already old:

`
2024/07/02 14:54:22 wazuh-db[169] wdb_parser.c:859 at wdb_parse(): DEBUG: Global query: sync-agent-info-set [{"id":1,"name":"wazuh-agent1","ip":"172.19.0.7","os_name":"Ubuntu","os_version":"20.04.1 LTS","os_major":"20","os_minor":"04","os_codename":"Focal Fossa","os_platform":"ubuntu","os_uname":"Linux |wazuh-agent1 |5.15.0-112-generic |#122-Ubuntu SMP Thu May 23 07:48:21 UTC 2024 |x86_64","os_arch":"x86_64","version":"Wazuh v4.9.0","config_sum":"ab73af41699f13fdd81903b5f23d8d00","merged_sum":"4a8724b20dee0124ff9656783c490c4e","manager_host":"wazuh-worker1","node_name":"worker1","last_keepalive":1719932054,"connection_status":"disconnected","disconnection_time":1719932055,"group_config_status":"not synced","status_code":3,"labels":[{"id":1,"key":"#\"_agent_ip\"","value":"172.19.0.7"},{"id":1,"key":"#\"_manager_hostname\"","value":"wazuh-worker1"},{"id":1,"key":"#\"_node_name\"","value":"worker1"},{"id":1,"key":"#\"_wazuh_version\"","value":"Wazuh v4.9.0"}]},...]
`

The agent's database ends with this information:

```
date &&  echo "global sql select * from agent where id = 1;" | /var/ossec/framework/python/bin/python3 wdb-query.py
Tue Jul  2 15:45:45 UTC 2024
[
    {
        "id": 1,
        "name": "wazuh-agent1",
         ...
        "manager_host": "wazuh-master",
        "node_name": "master-node",
        "date_add": 0,
        "last_keepalive": 1719935136, # (15:45:36)
        "group": "default,group1",
        "group_hash": "e48046b2",
        "group_sync_status": "synced",
        "sync_status": "synced",
        "connection_status": "active",
        "disconnection_time": 1719932055, # (14:54:15)
        "group_config_status": "synced",
        "status_code": 3
    }
]
```

We see that the agent remains with an `active` status with a recent `keep-alive` but a `status_code` and `disconnection_time` different from 0.

## NOTE: 

We believe that this issue may be related to other previous cluster synronization problems. On of them analyzed in this [issue](https://github.com/wazuh/wazuh/issues/23349#issuecomment-2103684785) and the other one is the problem of pendings agents in large environments.

The flow could be as follows:

- Agent restarts connected to worker1
- Agent connects to worker2, sends startup but fails to send keepalive and restarts -> remains in pengind status.
- Agent connects to worker3
- Master receives sync from worker2 with pending status, and remains so until it receives sync from worker3.

This problem was seen a lot in the city of LA client.

**Comment by Selutario** [comment] 2024-07-04 16:07
In my opinion (and taking performance into account), there is no way to solve this problem from the cluster side. The `Agent-info sync` task, which is responsible for synchronizing agent information from workers to the master, does the following:
- Each worker executes the task with a frequency of 10 seconds.
- The worker's clustered process requests the local `wazuh-db` for information about agents that have suffered any modifications since the previous query.
- `wazuh-db` returns a list of 65KB chunks. Each chunk has information from as many agents as can fit.
- The worker sends the list of chunks to the master.
- The master sends the chunks, one by one (unparsed and unmodified) to its local wazuh-db.

Since each chunk contains information from many agents and the master does not analyze the information, it cannot do anything to solve this problem. The fix must therefore be on the `wazuh-db` or `remoted` side. For example, updating the disconnection_time and status_code fields at every `update-agent-data` and not just during `HC_STARTUP`.

I'm assigning the issue to the cppserver team.

**Comment by Dwordcito** [comment] 2024-07-05 12:30
RCA - Time box to 10/07

**Comment by juliancnn** [comment] 2024-07-05 16:36
Hi @Selutario and @sdvendramini,


## Root Cause Analysis (RCA)
To summarize the scenario outlined by @sdvendramini:

1. An agent connected to a worker node restarts and connects to the Master node.
2. Upon connection, the Master receives a `HC_STARTUP`:
   - The agent's status updates to `pending`.
   - The `status_code` and `disconnection_time` are set to 0 for this agent.
3. The agent sends a `keep-alive` and its status on the manager updates to `active`.
4. The manager then receives outdated synchronization information from the cluster, which incorrectly updates the `status_code` and `disconnection_time` (Among other), and changes the `connection_status` to `disconnected`.
5. The agent sends another `keep-alive` and updates its status to `active` on the manager.
6. The manager retains the incorrect `status_code` and `disconnection_time`.

## Conclusion and Proposal
It seems that the responsibility to update `status_code` and `disconnection_time` with every `update-agent-data` shouldn't fall solely on `wazuh-db`, as it does not fully address the synchronization issues. Cluster management should determine when to replace agent data, potentially by checking the timestamp of the last update to decide whether to refresh an agent's information.

Given that this issue is not critical and considering the upcoming new agent-manager connection implementation in version 5.0, this issue will not persist. Therefore, I propose we close this issue as **not planned** for further action in the current version.

**Comment by Dwordcito** [comment] 2024-07-11 03:36
LGTM

**Closed by Dwordcito** 2024-07-11 03:36 UTC
Labels: type/bug, level/task
