### ISSUE TITLE
Syscheck continues to run despite being disabled in the configuration

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18185] opened 2023-08-01 09:02 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2 | Syscheck | Manager and Agent | Packages | centOS 7 |

### Description

Despite disabling this module in the manager configuration, it appears that syscheck is still running and consuming host resources.

This issue becomes evident in all the footprint tests specifically designed for the rootcheck module, as documented [here](https://github.com/wazuh/wazuh/issues/9462). Despite not enabling the syscheck module, it is apparent that it consumes nearly 100% of the CPU resources during these tests

### How to replicate
- Disable syscheck module in the manager or agent configuration

<details>

<summary> ossec.conf </summary>

```
  <syscheck>
    <disabled>yes</disabled>
    <frequency>2</frequency>
    <scan_on_start>yes</scan_on_start>
    <directories check_all="yes">/etc,/usr/bin,/usr/sbin</directories>
    <directories check_all="yes">/bin,/sbin,/boot</directories>
    <directories check_all="yes" realtime="yes">/tmp/syscheck_test/files</directories>
    <ignore>/etc/mtab</ignore>
    <ignore>/etc/hosts.deny</ignore>
    <ignore>/etc/mail/statistics</ignore>
    <ignore>/etc/random-seed</ignore>
    <ignore>/etc/random.seed</ignore>
    <ignore>/etc/adjtime</ignore>
    <ignore>/etc/httpd/logs</ignore>
    <ignore>/etc/utmpx</ignore>
    <ignore>/etc/wtmpx</ignore>
    <ignore>/etc/cups/certs</ignore>
    <ignore>/etc/dumpdates</ignore>
    <ignore>/etc/svc/volatile</ignore>
    <ignore type="sregex">.swp$</ignore>
    <ignore type="sregex">^/proc</ignore>
    <ignore type="sregex">.log$|.swp$</ignore>
    <nodiff>/etc/ssl/private.key</nodiff>
    <skip_nfs>yes</skip_nfs>
    <skip_dev>yes</skip_dev>
    <skip_proc>yes</skip_proc>
    <skip_sys>yes</skip_sys>
    <process_priority>10</process_priority>
    <max_eps>100</max_eps>
    <synchronization>
      <enabled>yes</enabled>
      <interval>5m</interval>
      <max_interval>10m</max_interval>
      <max_eps>10</max_eps>
    </synchronization>
  </syscheck>

```

</details>

- Confirm syscheck is disabled in manager/agent logs
```
...
2023/08/01 08:52:11 wazuh-syscheckd: INFO: (6001): File integrity monitoring disabled.
...
```
- Check that wazuh-syscheck process is still running
```
root@all-in-one-ubuntu2:/home/vagrant# ps -fax | grep wazuh-syscheck
 405256 pts/0    S+     0:00  |                       \_ grep --color=auto wazuh-syscheck
 347522 ?        SNl    0:10 /var/ossec/bin/wazuh-syscheckd
```

- Check that wazuh-syscheck is running using wazuh-control
```
root@all-in-one-ubuntu2:/home/vagrant# /var/ossec/bin/wazuh-control status
...
wazuh-syscheckd is running...
...
```
- Check that wazuh-syscheck is consuming resources
```
root@all-in-one-ubuntu2:/home/vagrant# ps -p 347522 -o %cpu,%mem,cmd
%CPU %MEM CMD
 8.4  0.1 /var/ossec/bin/wazuh-syscheckd
```

**Comment by vikman90** [comment] 2023-08-01 14:38
@Rebits It's not a bug, it's a feature!

_wazuh-syscheckd_ runs both Syscheck (FIM) and Rootcheck, but they are different components. If _wazuh-syscheckd_ stops because FIM is disabled:

- Rootcheck could not run.
- The API could not query configuration.

For instance, _wazuh-logcollector_ runs even when no `<localfile>` stanzas are declared, and _wazuh-execd_ runs although Active Response is disabled.

On the other hand, those daemons which go down when their features are disabled produced a wrong exit code in `wazuh-control status`.

This is not a bug, let me close this issue.

**Closed by vikman90** 2023-08-01 14:38 UTC
Labels: type/bug, level/task
