### ISSUE TITLE
Include os information in every alert

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh#633] opened 2018-05-16 17:16 UTC
Hi all,

we are facing an issue where we want to use logstash to catalogue alerts in different elasticsearch indices regarding some criteria, one of them being the operating system.

This would be easily achieved if we have access to os information on every alert, with the counterpart of adding size to it.

What do you think about this?

Regards.

**Comment by jesuslinares** [comment] 2018-05-21 13:06
+1

It could be a setting in the `<global>` section.

**Comment by evilpete** [comment] 2018-05-21 15:14
an't this be mostly accomplished with agent labels?

https://documentation.wazuh.com/3.x/user-manual/capabilities/labels.html

Or am I misunderstanding the question.

**Comment by jesusgn90** [comment] 2018-07-16 15:55
Some news about this issue? I'm very interested about this feature. As @havidarou said, this information would be very valuated when searching in Elasticsearch. We can groups alerts by OS to generate a useful information for the user...

Thanks in advance,
Jesús

**Comment by jesuslinares** [comment] 2018-07-16 16:18
@evilpete, yes, it is accomplished with the labels but you have to do it manually. We are looking for an automatic way to send the OS of every agent in the alert.

We could re-use the labels but they would be populated automatically:
`<labels type="os"/>`
instead of
`<label key="os">Windows</label>`

It will work with more "pre-defined labels" like IP, MAC, etc.

**Comment by evilpete** [comment] 2018-07-16 17:59
I am familiar with labels, A useful feature would be a hook for a script that can be called at startup.

For example A script that outputs XML label data that become as part of the config,  This will allow for more homogenous agent.conf.

Right now in aws I have a Python script that generates the following that I append  on to the ossec.conf

```
<ossec_config>
  <labels>
    <label key="aws.instance-id">i-06da6666660fee586</label>
    <label key="aws.accountId">123456437575</label>
    <label key="aws.privateIp">10.255.255.20</label>
    <label key="aws.launchTime">2018-07-13T07:58:24Z</label>
    <label key="aws.availabilityZone">us-east-2a</label>
    <label key="aws.imageId" hidden="yes">ami-4f80b52a</label>
  </labels>
</ossec_config>
```

The problem is when someone copies a config file from one host to another.  Having a hook that retrieves and inserts this information at start up resolve this problem and others.

https://github.com/wazuh/wazuh/issues/684 relates to this topic

**Comment by evilpete** [comment] 2019-02-03 11:18
I took a look at #1004, but   IP addr / hostname are not sufficient unique identifiers in a cloud environment, to identify a host instance from a distributed cloud architecture spanning  multiple regions you would need the instance ID  from the system metadata (the Account # will help also)
( queryable  from any host at  from a locally routed URL http://169.254.169.254/latest/meta-data/  )

The environment that I run as two separate Wazuh clusters, (one prod and one dev/QA) each spanning 6 regions with monitoring agents currently running in 12 separate AWS accounts (when fully Deployed this number can approach 60 accounts)

**Comment by vikman90** [comment] 2019-02-21 03:08
@havidarou @evilpete Issue #1004 is related to this one. We will continue this discussion there.

Let me close this issue.
Best regards.

**Closed by vikman90** 2019-02-21 03:08 UTC
Labels: enhancement, question
