### ISSUE TITLE
Whodata not working in OpenSUSE  Leap-15.6

### ISSUE THREAD

**Issue by ed108206** [wazuh/wazuh#20243] opened 2023-11-14 20:47 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0 | FIM | Agent | Any | openSUSE Leap 15.6 |

This issue is a direct result of the tests performed in [this issue](https://github.com/wazuh/wazuh/issues/19823). FIM whodata tests are failing, and as a workaround, a realtime is used instead. It is important to highlight that this particular malfunction has been previously observed in a related [issue](https://github.com/wazuh/wazuh/issues/19399) concerning openSUSE-Leap 15.5.

**Comment by jotacarma90** [comment] 2023-12-11 16:05
This issue is directly related to the problem detailed here:
https://github.com/wazuh/wazuh/issues/19399

It is due to an error caused by the default rule in these systems. We will work on a fix to remove the rule when starting Wazuh.
![image](https://github.com/wazuh/wazuh/assets/60003131/163d0b73-c6fc-4288-9526-755e71928b26)

Closing issue due to duplicated.

**Closed** 2023-12-14 15:32 UTC
Labels: type/bug, level/task
