### ISSUE TITLE
[Syscollector][OpenSuse] Failed to open database '/var/lib/rpm/Packages': No such file or directory

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#4776] opened 2020-03-24 12:01 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0-31204 | Syscollector | Manager and Agent | Packages | OpenSuse Tumbleweed 20200322 |

Hello team,

We have detected undesired error message inside the modulesd logs while we are working with Wazuh on OpenSuse Tumbleweed, we think it could be reproduced on OpenSuse 15 and OpenSuse 42.

Below we attach our `ossec.log` (Agent side):
```
2020/03/24 09:22:08 ossec-execd: INFO: Started (pid: 2587).
2020/03/24 09:22:08 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2020/03/24 09:22:08 ossec-agentd: INFO: Version detected -> Linux |be21cf1046b1 |4.15.0-91-generic |#92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 |x86_64 [openSUSE Tumbleweed|opensuse-tumbleweed: 0.0] - Wazuh v3.12.0
2020/03/24 09:22:08 ossec-agentd: INFO: (1410): Reading authentication keys file.
2020/03/24 09:22:08 ossec-agentd: INFO: Using AES as encryption method.
2020/03/24 09:22:08 ossec-agentd: INFO: Started (pid: 2596).
2020/03/24 09:22:08 ossec-agentd: INFO: Server IP Address: 172.17.0.3
2020/03/24 09:22:08 ossec-agentd: INFO: Trying to connect to server (172.17.0.3:1514/udp).
2020/03/24 09:22:09 ossec-syscheckd: INFO: Started (pid: 2610).
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/etc', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/usr/bin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/usr/sbin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/bin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/sbin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/boot', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6003): Monitoring directory/file: '/test', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | realtime'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/mtab'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/hosts.deny'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/mail/statistics'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/random-seed'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/random.seed'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/adjtime'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/httpd/logs'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/utmpx'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/wtmpx'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/cups/certs'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/dumpdates'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/svc/volatile'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/sys/kernel/security'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/sys/kernel/debug'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6206): Ignore 'file' entry '/dev/core'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6207): Ignore 'file' sregex '^/proc'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6207): Ignore 'file' sregex '.log$|.swp$'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6004): No diff for file: '/etc/ssl/private.key'
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6016): Directory set for real time monitoring: '/test'.
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6000): Starting daemon...
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2020/03/24 09:22:09 ossec-syscheckd: INFO: (6008): File integrity monitoring scan started.
2020/03/24 09:22:09 ossec-agentd: INFO: (4102): Connected to the server (172.17.0.3:1514/udp).
2020/03/24 09:22:09 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2020/03/24 09:22:09 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
2020/03/24 09:22:09 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2020/03/24 09:22:09 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2020/03/24 09:22:09 ossec-logcollector: INFO: Started (pid: 2624).
2020/03/24 09:22:09 wazuh-modulesd: INFO: Process started.
2020/03/24 09:22:09 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2020/03/24 09:22:09 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2020/03/24 09:22:09 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2020/03/24 09:22:09 sca: INFO: Module started.
2020/03/24 09:22:09 wazuh-modulesd:syscollector: INFO: Module started.
2020/03/24 09:22:09 wazuh-modulesd:control: INFO: Starting control thread.
2020/03/24 09:22:09 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/sca_unix_audit.yml'
2020/03/24 09:22:09 sca: INFO: Starting Security Configuration Assessment scan.
2020/03/24 09:22:09 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/sca_unix_audit.yml'
2020/03/24 09:22:10 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2020/03/24 09:22:10 wazuh-modulesd:syscollector: ERROR: Failed to open database '/var/lib/rpm/Packages': No such file or directory
2020/03/24 09:22:10 wazuh-modulesd:syscollector: ERROR: Unable to get rpm packages due to: No such file or directory
2020/03/24 09:22:10 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2020/03/24 09:22:12 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/sca_unix_audit.yml'
2020/03/24 09:22:13 sca: INFO: Security Configuration Assessment scan finished. Duration: 4 seconds.
2020/03/24 09:22:14 rootcheck: INFO: Starting rootcheck scan.
2020/03/24 09:22:14 ossec-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
2020/03/24 09:22:14 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2020/03/24 09:22:14 ossec-syscheckd: INFO: (6012): Real-time file integrity monitoring started.
2020/03/24 09:22:24 rootcheck: INFO: Ending rootcheck scan.
2020/03/24 10:22:11 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2020/03/24 10:22:11 wazuh-modulesd:syscollector: ERROR: Failed to open database '/var/lib/rpm/Packages': No such file or directory
2020/03/24 10:22:11 wazuh-modulesd:syscollector: ERROR: Unable to get rpm packages due to: No such file or directory
2020/03/24 10:22:11 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2020/03/24 11:22:11 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2020/03/24 11:22:11 wazuh-modulesd:syscollector: ERROR: Failed to open database '/var/lib/rpm/Packages': No such file or directory
2020/03/24 11:22:11 wazuh-modulesd:syscollector: ERROR: Unable to get rpm packages due to: No such file or directory
2020/03/24 11:22:11 wazuh-modulesd:syscollector: INFO: Evaluation finished.
```

Probably such error produces that Syscollector can't update its database.
Where error is produced -> https://github.com/wazuh/wazuh/blob/v3.12.0/src/wazuh_modules/syscollector/syscollector_linux.c#L408
Where the path is defined -> https://github.com/wazuh/wazuh/blob/v3.12.0/src/wazuh_modules/syscollector/syscollector.h#L80

Regards.

**Comment by alberpilot** [comment] 2020-03-24 14:30
Hello team

  We noticed that this occurs in the Docker OpenSUSE official image: `opensuse/tumbleweed`. We saw that there is no `/var/lib/rpm/Packages` but `/var/lib/rpm/Packages.db`, which it could be the root cause. 

Best regards, 
Alberto R

**Comment by pereyra-m** [comment] 2021-01-19 15:39
Hi team.

These error messages can be found in another OS and situations. 
It's due to the logic in **syscollector**.

The `sys_packages_linux()` method checks two different folders:

- If _"/var/lib/dpkg/"_, exists, it calls `sys_deb_packages()`
- If _"/var/lib/rpm/"_ exists, it call `sys_rpm_packages()`

But it always checks both, regardless the previous result.
So, for example, an user in Ubuntu that has created the _"/var/lib/rpm/"_ folder for any reason, would receive an error message even when it's empty.

Regards.

**Comment by Dwordcito** [comment] 2021-11-02 20:10
This issue will be fixed in:

https://github.com/wazuh/wazuh/issues/10324

**Closed by Dwordcito** 2021-11-02 20:10 UTC
Labels: bug, core/syscollector, cicd
