### ISSUE TITLE
Wazuh rule handler bug

### ISSUE THREAD

**Issue by o-tsyhanov** [wazuh/wazuh#25664] opened 2024-09-10 10:27 UTC
| Wazuh version: 4.8.1–4.9.0 | wazuh-ruleset, wazuh-manager, wazuh-analysisd | 

Dear support,

We faced with the problem when wazuh api stoppes responding and wazuh dashboards can't connect to it (screenshots will be attached as a proof).

![image](https://github.com/user-attachments/assets/3d0522c4-3c70-42f1-a6e2-c1d848a0f188)

A Wazuh manager service restart could help restore it. Logs examples which I could see in the manager's /var/ossec/etc/osses.comf:
```
Sep 4, 2024 @ 13:31:00.000 wazuh-modulesd ERROR  At wm_sendmsg(): Unable to send message to queue: (Bad file descriptor)
Sep 4, 2024 @ 13:31:00.000 wazuh-modulesd:office365 ERROR  (1210): Queue 'queue/sockets/queue' not accessible: 'Bad file descriptor'
Sep 4, 2024 @ 13:31:00.000 wazuh-modulesd ERROR  socketerr (not available).
```
During that case, all ports that wazuh manager is using are in a listening state (I didn't check them for availability so can't add any context). 

I tried to research that and discovered that some users faced with the same:
  1. https://github.com/wazuh/wazuh/issues/20659
  2. https://groups.google.com/g/wazuh/c/Crz9hJSsRWU

The google groups thread (2nd link) helped me to receive the issue. Victor M Fernandez-Castro recommended to review the rules and I found the one which was added before the problem started. The rule code (agent and client names were anonimized):
```
<rule id="200719" level="5">
  <if_sid>60204</if_sid>
  <hostname>^wazuh_agent_name$</hostname>
  <field name="win.eventdata.workstationName">^client_hostsnames_regex*</field>
  <description>Multiple Windows logon failures.</description>
</rule>
```
The strangest thing is that we have a lot of similar rules and they don't cause any issues. 

Hope this issue can help to resolve some issues and to reproduce the bug. It also would be great if you help us to avoid such issues in the future. 

Thanks

**Comment by JavierBejMen** [comment] 2024-10-09 12:35
Hi, I cannot reproduce the error, I was unable to generate events to trigger the parent rule 60204.

- In order to continue I will need an example XML windows event that triggered this error.
- Also could you check in the manager if there was a segfault?
```
cat /var/log/messages | grep segfault
```
- If there was I would appreciate if you configure the core dumps in the manager so if it happens again I can check it, you can follow the [documentation](https://documentation.wazuh.com/current/development/coredump.html)

**Comment by o-tsyhanov** [comment] 2024-10-10 08:17
Segfault isn't caused by matching the rule. It happens after the nightly ossec.logs rotation maybe I skipped that, sorry if it is. 
Of course after the rule was disabled there was no crashed and seagfaults in the logs. 
If you will still need the XML for the rule I was disabled or core dumps let me know.

**Comment by JavierBejMen** [comment] 2024-10-10 10:11
Yes, if the crash occurs at rotation we can try to reproduce it with the XML. And the core dump would be much appreciated.

**Comment by o-tsyhanov** [comment] 2024-10-10 10:14
Ok, I will return that rule, configure core dump and write back there.

**Comment by o-tsyhanov** [comment] 2024-10-10 10:19
It will be on this weekend aprox.

**Comment by o-tsyhanov** [comment] 2024-10-15 08:56
It looks strange. I configured coredumps (hoping all is correct) and preconfigured Wazuh manager restart a few hours after the probable time to crash (to avoid the system outage). 

I checked mentioned directory of coredumps but it is empty. I disabled the manager restart to validate that the problem is gone. 

There were also no events that must match the mentioned rule. 

XML for the rule which we created for:

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event"> 
- <System> 
<Provider Name="Microsoft-Windows-Perflib" Guid="{13B197BD-7CEE-4B4E-8DD0-59314CE374CE}" EventSourceName="Perflib" /> 
<EventID Qualifiers="49152">1023</EventID> 
<Version>0</Version> 
<Level>2</Level> 
<Task>0</Task> 
<Opcode>0</Opcode> 
<Keywords>0x80000000000000</Keywords> 
<TimeCreated SystemTime="2024-10-10T10:45:17.193279800Z" /> 
<EventRecordID>418311</EventRecordID> 
<Correlation /> 
<Execution ProcessID="0" ThreadID="0" /> 
<Channel>Application</Channel> 
<Computer>hostname.domain</Computer> 
<Security /> 
</System> 
- <UserData> 
- <EventXML xmlns="Perflib"> 
<param1>MSSQL$PROGET</param1> 
<binaryDataSize>8</binaryDataSize> 
<binaryData>7E00000000000000</binaryData> 
</EventXML> 
</UserData> 
</Event>
```

So I can propose waiting for the next occurrence of the event with enabled core dumps and disabled wazuh-manager auto restart at night.

**Comment by JcabreraC** [comment] 2024-10-16 15:46
Hello @o-tsyhanov ,

I'm closing this issue as we wasn't able to reproduce it, and it seems that the problem is no longer occurring on your environment.

If the issue reappears, please feel free to reopen it and provide any additional details that might help us investigate further.

**Closed by JcabreraC** 2024-10-16 15:46 UTC
Labels: type/bug, level/task

**Comment by o-tsyhanov** [comment] 2024-12-02 09:11
Hello,

I am here now with the same problem. 

We have created a few new rules and some time later faced with the same issue. 
I did some troubleshooting and discovered that the root of the problem was the same rule. 
I think systemd-coredump was configured correctly, but the destination folder is empty, so there were no records. I also tried
```
coredumpctl list
```
from sudo and received:
```
No coredumps found.
```
```
systemctl status systemd-coredump*
```
returns
```
● systemd-coredump.socket - Process Core Dump Socket
     Loaded: loaded (/lib/systemd/system/systemd-coredump.socket; static; vendor preset: enabled)
     Active: active (listening) since Mon 2024-11-25 12:37:49 EET; 6 days ago
       Docs: man:systemd-coredump(8)
     Listen: /run/systemd/coredump (SequentialPacket)
   Accepted: 0; Connected: 0;
      Tasks: 0 (limit: 14248)
     Memory: 0B
     CGroup: /system.slice/systemd-coredump.socket

Nov 25 12:37:49 wazuh.siem systemd[1]: Listening on Process Core Dump Socket.
```
The only mentions about segfault I discovered was the record in Syslog:
```
/var/log/syslog.1:Dec  1 00:00:55 wazuh kernel: [4329906.478621] wazuh-analysisd[1323221]: segfault at 7fe8a8a32000 ip 00007fe8ebd99963 sp 00007fe8afff6d38 error 6 in libc-2.31.so[7fe8ebc31000+178000]
```
Also wazuh manager version is 4.9.2.
