### ISSUE TITLE
Active response not functioning on Windows 2016 Datacentre

### ISSUE THREAD

**Issue by CrazyLlama** [wazuh/wazuh#166] opened 2017-08-10 13:56 UTC
Hi guys,

I'm testing active response on windows 2016 Datacentre and cannot for the life of me figure out what is wrong. I've gone through the following steps:

* Testing the active response script itself works
* Looking through the source code to see if there is any indication of errors or logging of errors, I find I'm not familiar enough to find much in the way of this beyond it indicating that they will be stored in ossec.log and not active-responses.log
* Packet traces on both the manager and agent to ensure they are being sent 
* Activated debugging and found the following:

`2017/08/10 14:54:00 ossec-logcollector: WARN: Could not convert SID to string which returned (87)`
`2017/08/10 14:54:00 ossec-logcollector: DEBUG: Performing a LookupAccountSid() on (unknown)`

However this may be for a separate issue I've yet to look into.

* Switching types of logging and ports to test network issues, found no problems with packet tracers here as well

It appears that I have an issue on the agent side however I'm not really familiar enough with the code nor debugs right now to find the issue so any help is highly appreciated!

**Comment by CrazyLlama** [comment] 2017-09-28 13:46
This is still an issue for me, #165 didn't fix this issue. I will test again on a fresh install to see if there has been any changes that have fixed this and report back.

**Comment by vikman90** [comment] 2017-09-28 16:34
Hi @CrazyLlama 

thanks for reporting. We have also noticed the error 87 on Windows, we are investigating it.

Please keep us updated.

Thanks again!
Best regards.

**Comment by mskotarczak** [comment] 2018-02-09 12:42
@vikman90 is there any update with error 87 on Windows ? 
i'v got problem with sending event 4663 form every windows that i have 

_ossec-logcollector:_ WARN: Could not convert SID to string which returned (87)
ossec-logcollector: DEBUG: Performing a LookupAccountSid() on (unknown)_

**Comment by vnil1994** [comment] 2019-03-19 12:26
Did anyone here ever find out the cause of this issue? We are experienceing it now as well, but then using syscheck with whodata on System32.

**Comment by vikman90** [comment] 2019-05-27 13:44
Hi all,

The error reported by @mskotarczak should no longer appear in the log because that operation is not used anymore from v3.8.0.

Apologies for not notifying you previously.
Could you confirm that you're seeing that error in Wazuh Agent after v3.8.0?

Thank you.
Best regards.

**Comment by vikman90** [comment] 2019-06-03 13:18
Hi,

Let me close this issue as this log error should no longer appear. Feel free to reopen it if you see that error or encounter any other problem.

Best regards.

**Closed by vikman90** 2019-06-03 13:18 UTC
Labels: bug, community, core/logcollector, platform/windows, status/awaiting reply
