### ISSUE TITLE
File Integrity (Syscheck) false positive 

### ISSUE THREAD

**Issue by ajohnson8503** [wazuh/wazuh#589] opened 2018-05-05 18:17 UTC
After configuring FIM on Windows server and enabling alerting for level 7 and above. Now alerts are coming in all day with hash value changes on static files which have not changed in hash calue.

**Comment by vikman90** [comment] 2018-05-05 18:59
Hi @ajohnson8503,

We have already been reported about this issue but it seems hard to reproduce. We are trying to figure out why this is happening and think that the agent is not able to read completely some files because they are locked by another application.

Could you tell us which version of Windows you are using and some examples of the false positives? Did you enable any feature like IIS or Active Directory?

Thank you for reporting.
Best regards.

**Comment by ajohnson8503** [comment] 2018-05-05 19:31
Right now we are testing on a mix of 2008R2 2012R2 servers. Some are
running IIS, Domain Controllers and a basic Windows server. From what I
have noticed it seems that they read the file once as the old hash value is
the current one when I check them.

Where is started to notice this issue was on a 2008R2 IIS server when
scanning the web directory.

**Comment by ajohnson8503** [comment] 2018-05-05 19:32
One thing I also did to test was install the Elastic auditbeat which seems
to be able to scan the files fine and report the same hash value.

**Comment by ajohnson8503** [comment] 2018-05-08 19:03
I did some testing and I think you are correct that the agent is not able to real the files that are in use which is causing the false hash. On a side note dose Wazuh support SHA256 or is it just SHA1 and MD5 hashing?

**Comment by bah07** [comment] 2018-05-09 09:11
Hi @ajohnson8503, 

In this PR you can check the development of the SHA256 support for wazuh, [#410](https://github.com/wazuh/wazuh/pull/410)
We have planned its release for the version 3.3, but we don't have a date yet, so we will work to add this feature as soon as possible.

Best regards.

**Comment by doubledeee** [comment] 2018-05-25 00:35
I am having the same issue as @ajohnson8503 and have been working with some developers at Wazuh to figure out the issue.

**Comment by ajohnson8503** [comment] 2018-05-30 13:55
So it looks like some of the issue that I am seeing is not with the agent being able to read the files but more with reading/storing the data in the queue diff folder.

**Comment by bah07** [comment] 2018-06-04 08:14
Hi @ajohnson8503 

We have checked that what you are saying is a different error, I have generated an issue [708](https://github.com/wazuh/wazuh/issues/708), where you can check its status.

Thank you so much for the report.
Regards.

**Comment by bah07** [comment] 2018-10-29 11:06
Due to the changes made in FIM from version 3.3 to 3.7 and in order to keep an updated list of issues that currently occur in the new version we proceed to close this thread.
In case you find this problem again in updated releases, please do not hesitate to reopen it.

Regards.

**Closed by bah07** 2018-10-29 11:06 UTC
Labels: bug, fim

**Comment by ajohnson8503** [comment] 2018-10-29 12:38
Is that fixed or is it just closed because you wanted to close it?

**Comment by bah07** [comment] 2018-10-29 15:04
Of course not, maybe I haven't explained myself correctly.
In release 3.4 FIM changed radically, among the numerous changes, we fixed the way in which the agent avoids sending events to the manager if there has not been a real change in the file. Because no user has reported a similar problem since version 3.4 we have decided to take the issue for fixed. 

But as I said in my previous comment, in case the error persists in updated versions and tells us how to reproduce it do not hesitate to open it again.

Regards.
