### ISSUE TITLE
Wazuh with a load balancer

### ISSUE THREAD

**Issue by noahaas** [wazuh/wazuh#4662] opened 2020-02-26 07:15 UTC
I have a network that has: 
Wazuh manager 
Wazuh cluster
Wazuh agent
Load balancer

(My environment works on port 443)

When I try to connect my wazuh agent to the load balancer it won’t connect.
The logs show:
Ossec-agentd: WARNING: (4101): waiting for server reply (not started). Tried: ‘-load balancer ip-’. 
Ossec-agentd: INFO: trying to connect to server (-load balancer ip-:443/tcp). 
Ossec-agentd: INFO: trying to connect to server (-load balancer ip-:443/tcp). 

If I connect my agent straight to my manager it works. 

My question is, why won’t it works? 
Does the agent needs to receive a certain data from the manager and that’s why it won’t connect to my load balancer?

**Comment by crd1985** [comment] 2020-02-27 09:05
Hi @noahaas ,

These resources may help you:
- https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/
- https://documentation.wazuh.com/3.11/user-manual/configuring-cluster/advanced-settings.html#pointing-agents-to-the-cluster-with-a-load-balancer

I am closing this issue because it is not a bug report nor feature request. If you need further support you can post a new thread in our community slack channel or mailing list (https://wazuh.com/community/).

I hope you understand.
Regards.

**Closed by crd1985** 2020-02-27 09:05 UTC
