### ISSUE TITLE
Test: API

### ISSUE THREAD

**Issue by albertomn86** [wazuh/wazuh#1948] opened 2018-11-23 17:46 UTC
| Version | Revision | Branch |
| --- | --- | --- |
| 3.7.1 | 3722 | v3.7.1 |

## Installation

- [x] Install API in a cluster of two nodes. One of the nodes must be a custom directory install. All agents must report to the worker node.
- [x] Check API status is running in both nodes.

## Configuration

- [x] Custom user, password and https working.

### Certificates and HTTPS

- [x] Install certificates.
- [x] Run query using HTTPS.

### Test mocha

Required tests:

- Agents.
- Decoders.
- Manager.
- Rootcheck.
- Rules.
- Syscheck.
- Syscollector.

Checks:

- [x] Master node:
    - [x] Ubuntu 18 / Python 2.
    - [x] Ubuntu 18 / Python 3.
    - [x] CentOS 7 / Python 2.
    - [ ] CentOS 7 / Python 3.
    - [ ] CentOS 6 / Python27.

**Comment by manuasir** [comment] 2018-11-29 10:10
`1. Install API in a cluster of two nodes. One of the nodes must be a custom directory install. All agents must report to the worker node.`

In the worker node, the manager was compiled and installed in the custom directory `/etc/wazuh`. Agents were configured to reporting to the worker. Everything was fine during the process.

`2.  Check API status is running in both nodes.`

![](https://i.imgur.com/nPLz0sU.png)

OK

`3. Custom user, password and https working.`

The `configure_api.sh` script was launched and every parameter was modified in order to test them. Everything was correct.

**Comment by manuasir** [comment] 2018-11-29 16:01
I'm adding here the mocha `failed` tests for Centos 7 - Python 2
[Mochawesome Report.pdf](https://github.com/wazuh/wazuh/files/2629868/Mochawesome.Report.pdf)

**Comment by adri9valle** [comment] 2018-11-30 12:50
Added the mocha test fails for Ubuntu 18 - Python 2 / Python 3
[report-ubuntu18-python2.pdf](https://github.com/wazuh/wazuh/files/2633240/report-ubuntu18-python2.pdf)
[report-ubuntu18-python3.pdf](https://github.com/wazuh/wazuh/files/2633241/report-ubuntu18-python3.pdf)

**Comment by mgmacias95** [comment] 2018-11-30 23:59
Hello @adri9valle and @manuasir,

Thank you so much for those detailed reports. I have been looking into the reported errors and I'd like to explain them one by one.

# Ubuntu 18
## Python 2
### GET/agents/:agent/conﬁg/:component/:conﬁguration - Request-Mail-Global
#### Reported error
```
AssertionError: expected Object { error: 1013, message: 'Unable to connect with socket: The component might be disabled' } to have property data
```
#### What happened
Maild wasn't enabled, so Wazuh wasn't able to retrieve its configuration. When it's enabled, the API call works properly:
```javascript
# curl -u foo:bar "localhost:55000/agents/000/config/mail/global?pretty"
{
   "error": 0,
   "data": {
      "global": {
         "email_maxperhour": 12,
         "email_to": [
            "recipient@example.wazuh.com",
            "hello@wazuh.com"
         ],
         "email_from": "wazuh@test.com",
         "smtp_server": "127.0.0.1"
      }
   }
}
```

### GET/agents/:agent/conﬁg/:component/:conﬁguration - Request-Mail-Internal
#### Reported error
```
AssertionError: expected Object { error: 1013, message: 'Unable to connect with socket: The component might be disabled' } to have property data
```
#### What happened
Maild wasn't enabled, so Wazuh wasn't able to retrieve its configuration. When it's enabled, the API call works properly:
```javascript
# curl -u foo:bar "localhost:55000/agents/000/config/mail/internal?pretty"
{
   "error": 0,
   "data": {
      "internal": {
         "mail": {
            "strict_checking": 1,
            "grouping": 1
         }
      }
   }
}
```
### GET/cluster/:node_id/stats - Cluster stats
#### Reported error
```
Error: expected 200 "OK", got 404 "Not Found"
```
#### What happened
As it can be seen in the report, the API call that is being tested is `GET/cluster/stats` instead of `GET/cluster/:node_id/stats`:
```javascript
request(common.url)
     .get("/cluster/stats")
     [...]
```

That API call doesn't exists, the good one works properly:
```javascript
# curl -u foo:bar "localhost:55000/cluster/worker-1/stats?pretty"
{
   "error": 1308,
   "message": "Stats file has not been created yet: /var/ossec/stats/totals/2018/Nov/ossec-totals-30.log"
}
```

### GET/manager/stats
#### Reported error
```
AssertionError: expected Object {   error: 1308,   message: 'Stats file has not been created yet: /var/ossec/stats/totals/2018/Nov/ossec-totals} to have property data
```
#### What happened
The stats files are created daily, if the manager is a new installation it will not have that stats file created yet.

### GET/rootcheck/:agent_id/cis
#### Reported error
```
AssertionError: expected 0 to be above 0
```
#### What happened
The manager where the tests were run, doesn't have any CIS alert. That's why the API call returns nothing:
```javascript
# curl -u foo:bar "localhost:55000/rootcheck/000/cis?pretty"
{
   "error": 0,
   "data": {
      "totalItems": 0,
      "items": []
   }
}
```
### GET/syscollector/:agent_id/packages - Filter: vendor
#### Reported error
```
Error: expected 200 "OK", got 400 "Bad Request"
```
#### What happened
The test has two stages:
1. First of all, it makes a normal request like the following one:
    ```javascript
    # curl -u foo:bar "localhost:55000/syscollector/000/packages?limit=1&pretty"
    {
       "error": 0,
       "data": {
          "totalItems": 515,
          "items": [
             {
                "description": "Python interface to libapt-pkg (locales)",
                "vendor": "Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>",
                "name": "python-apt-common",
                "format": "deb",
                "section": "python",
                "scan": {
                   "id": 1104939757,
                   "time": "2018/11/30 17:05:07"
                },
                "priority": "optional",
                "source": "python-apt",
                "version": "1.6.3",
                "architecture": "all",
                "size": 244
             }
          ]
       }
    }
    ```
2. Then, it filters field by field using the field filters. The problem is that field `vendor` contains non URL such as `<`, `>` and `@`. That makes the test to fail in Ubuntu systems.

### GET/experimental/syscollector/processes
#### Reported error
```
AssertionError: expected Object { tty: 0, rgroup: 'root', sgroup: 'root', scan: Object { id: 234072111, time: '2018/11/30 12:19:19' }, resident: 0, pid: '4', session: 0, size: 0, egroup: 'root', tgid: 4, priority: 0, fgroup: 'root', state: 'I', nlwp: 1, euser: 'root', share: 0, start_time: 0, stime: 0, vm_size: 0, utime: 0, ppid: 2, name: 'kworker/0:0H', pgrp: 0, ruser: 'root', suser: 'root', processor: 0, agent_id: '000' } to have property nice
```
#### What happened
It seems some entries in database doesn't contain field `nice`:
```python
# python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from wazuh import wdb
>>> mywdb = wdb.WazuhDBConnection()
>>> a = mywdb.execute("agent 000 sql select * from sys_processes")
>>> map(lambda x: 'nice' in x, a)
[True, True, False, False, True, True, True, True, True, True, True, True, True, True, False, True, False, True, True, True, True, False, True, True, False, False, False, False, False, False, False, False, True, True, False, False, True, False, True, False, False, False, False, False, False, True, False, False, False, False, True, False, False, False, False, False, False, False, True, True, False, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
>>>
```
## Python 3
### PUT/agents/:agent_id/group/:group_id
#### Reported error
```
AssertionError: expected Object { error: 1005, message: 'Error reading ﬁle: Unicode-objects must be encoded before hashing' } to have property data
```
#### What happened
This is a real bug, its trace is the following:
```python
Traceback (most recent call last):
  File "/var/ossec/framework/wazuh/agent.py", line 1551, in create_multi_group
    folder = hashlib.sha256(group_id).hexdigest()[:8]
TypeError: Unicode-objects must be encoded before hashing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 171, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 55, in distribute_function
    return execute_local_request(input_json, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 104, in execute_local_request
    data = rq.functions[input_json['function']]['function'](**input_json['arguments'])
  File "/var/ossec/framework/wazuh/agent.py", line 1680, in set_group
    return Agent.add_group_to_agent(agent_id=agent_id, group_id=group_id, force=force)
  File "/var/ossec/framework/wazuh/agent.py", line 1188, in add_group_to_agent
    Agent.create_multi_group(agent_group)
  File "/var/ossec/framework/wazuh/agent.py", line 1558, in create_multi_group
    raise WazuhException(1005, str(e))
wazuh.exception.WazuhException: Error 1005 - Error reading file: Unicode-objects must be encoded before hashing
```

### DELETE/agents/:agent_id/group/:group_id
#### Reported error
```
message: 'Error unsetting agent group: Agent 001 doesn\'t belong to group dmz'
```
#### What happened
The agent wasn't previously assigned to that group, but the API call works ok:
```javascript
# curl -u foo:bar "localhost:55000/agents/002/group/mygroup?pretty" -XDELETE
{
   "error": 0,
   "data": "Group 'mygroup' unset for agent '002'."
}
```
### GET/syscheck/:agent_id
#### Reported Error
```
AssertionError: expected 0 to be above 0
```
#### What happened
The previous API test (the one using Python 2) removed the syscheck database.
```javascript
# curl -u foo:bar "localhost:55000/syscheck/000?pretty&limit=1"
{
   "error": 0,
   "data": {
      "totalItems": 2814,
      "items": [
         {
            "sha1": "d023522bfb0296c5cc0536a355fbda9411ea8977",
            "gid": "0",
            "date": "2018-11-30 22:56:25",
            "uname": "root",
            "size": 662,
            "file": "/etc/dbus-1/system.d/com.ubuntu.SoftwareProperties.conf",
            "mtime": "2018-05-02 13:58:01",
            "gname": "root",
            "sha256": "816f024681c03b3b1116096991a6750babdb845f912e6f3fb46ce2e2a41a8733",
            "uid": "0",
            "type": "file",
            "perm": "100644",
            "inode": 1169,
            "md5": "cc3c01a5b5e8e05d40c9c075f44c43ea"
         }
      ]
   }
}
```

# CentOS 7
### GET/agents/no_group
#### Reported error
```
AssertionError: expected 0 to be above 0
```
#### What happened
There weren't any agents without a group. I need more information about the environment to be sure, but this should have not happened, since [the test adds an agent without group before executing the test](https://github.com/wazuh/wazuh-api/blob/b4fd87d85cc3e2fcca1fa91ba5ac892969c6f00e/test/test_agents.js#L965):
```javascript
# curl -u foo:bar "localhost:55000/agents/no_group?pretty"
{
   "error": 0,
   "data": {
      "totalItems": 1,
      "items": [
         {
            "status": "Never connected",
            "dateAdd": "2018-11-30 23:14:29",
            "name": "NC-Agent",
            "ip": "any",
            "id": "002",
            "node_name": "unknown"
         }
      ]
   }
}
```
### GET/experimental/syscollector/hardware
#### Reported error
```
AssertionError: expected 0 to be above 0
```
#### What happened
[This test filters using `search=Intel`](https://github.com/wazuh/wazuh-api/blob/b4fd87d85cc3e2fcca1fa91ba5ac892969c6f00e/test/test_syscollector.js#L1218). May the processor of the computer used to do it be AMD?
```javascript
# curl -u foo:bar "localhost:55000/experimental/syscollector/hardware?pretty&search=Intel"
{
   "error": 0,
   "data": {
      "totalItems": 2,
      "items": [
         {
            "cpu": {
               "cores": 2,
               "mhz": 1992.001,
               "name": "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz"
            },
            "ram": {
               "usage": 94,
               "total": 499256,
               "free": 33528
            },
            "scan": {
               "id": 323445514,
               "time": "2018/11/30 23:14:29"
            },
            "agent_id": "000",
            "board_serial": "0"
         }
      ]
   }
}
```

While working on this last bug I found a new one: a race condition in the distributed API:
```python
# echo '{"function":"/experimental/syscollector/hardware","arguments":{"filters":{},"wait_for_complete":false},"ossec_path":"/var/ossec"}' | /var/ossec/api/models/wazuh-api.py --debug
DEBUG:wazuh.cluster.dapi.dapi:[Cluster] [D API        ] Distributed API is enabled.
DEBUG:wazuh.cluster.dapi.dapi:{u'function': u'/experimental/syscollector/hardware', u'ossec_path': u'/var/ossec', 'from_cluster': False, u'arguments': {u'wait_for_complete': False, u'filters': {}}}
DEBUG:wazuh.cluster.dapi.dapi:Sending to unknown
DEBUG:wazuh.cluster.dapi.dapi:Sending to master
DEBUG:wazuh.cluster.dapi.dapi:[Cluster] [D API        ] Distributed API is enabled.
DEBUG:wazuh.cluster.dapi.dapi:{u'function': u'/experimental/syscollector/hardware', u'ossec_path': u'/var/ossec', 'from_cluster': True, u'arguments': {u'wait_for_complete': False, u'filters': {}}}
DEBUG:wazuh.cluster.dapi.dapi:[Cluster] [D API        ] Distributed API is enabled.
{"message": "Wazuh-Python Internal Error: 'wait_for_complete'", "error": 1000}
Traceback (most recent call last):
  File "/var/ossec/api/models/wazuh-api.py", line 171, in <module>
    data = dapi.distribute_function(request, pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 60, in distribute_function
    return forward_request(input_json, node_info['node'], pretty, debug)
  File "/var/ossec/framework/wazuh/cluster/dapi/dapi.py", line 206, in forward_request
    responses = list(filter(lambda x: x is not None, pool.map(forward_list, node_name.items())))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
KeyError: 'wait_for_complete'
```
When distributing API calls, a ThreadPool is created to forward the request to all nodes where there are nodes reporting. Never connected agents report to a node called `unknown` and that request is made locally to the master since there is no node to forward it to. Since there was another request being forwarded to the master at the same time, they were both sharing the `input_json` defining the API call parameters, including `wait_for_complete`.

The `wait_for_complete` parameter is removed right before calling the local function, since functions doesn't know about that parameter. It was being removed in one thread, but since the `input_json` variable was shared by both, a `KeyError` was raised when attempting to remove it in the other thread too.

I'm creating separated issues for the bugs found here.

Best regards,
Marta

**Closed** 2018-12-06 20:00 UTC
Labels: API, qa
