### ISSUE TITLE
Syslog json format

### ISSUE THREAD

**Issue by Lefnui** [wazuh/wazuh#107] opened 2017-04-26 14:22 UTC
Hi,

I was trying to integrate Wazuh in our current ELK Workflow, where all machines write to a central syslog server which sends the logs to logstash.

I configured Ossec to use the syslog output with json format 
`  <syslog_output>
    <server>X.X.X.X</server>
    <format>json</format>
  </syslog_output>
`

When I compare the syslog output to alerts.json, it seems that only the rule part of the alert is sent:
syslog json:

> {"crit":3,"id":5502,"component":"(agent) X.X.X.X->/var/log/auth.log","classification":"pam,syslog,pci_dss_10.2.5,","description":"PAM: Login session closed.","message":"Apr 26 16:20:53 agent su[26831]: pam_unix(su:session): session closed for user nobody","acct":"nobody"}

alerts.json:
>{"timestamp":"2017-04-26T16:21:26+0200","rule":{"level":3,"description":"PAM: Login session closed.","id":"5502","firedtimes":8,"groups":["pam","syslog"],"pci_dss":["10.2.5"]},"agent":{"id":"001","name":"agent","ip":"X.X.X.X"},"manager":{"name":"manager"},"dstuser":"nobody","full_log":"Apr 26 16:20:53 agent su[26831]: pam_unix(su:session): session closed for user nobody","program_name":"su","decoder":{"parent":"pam","name":"pam"},"location":"/var/log/auth.log"}

Is it expected behavior? Is there a way to get the same output?

**Comment by snaow** [comment] 2017-04-27 15:31
Hi @Lefnui,

Thanks for using Wazuh.
It is the expected behavior.
Syslog JSON output is outdated and does not have all the fields we have been including on standard JSON output (alerts.json).

The work-around you could use is set up a local syslog server reading from alerts.json file and sending everything to your Logstash instance.

I think you have a valid point for using Syslog output with enriched JSON format from Wazuh, we will study your case.
Let me keep open this issue so we can this in mind on the future.

Best regards,
Pedro.

**Comment by Lefnui** [comment] 2017-04-27 15:41
Hi,

Thanks for your reply, I set up a syslog to forward alerts.json, it works perfectly ;)

Indeed it could be nice to have it natively in Wazuh with the Syslog JSON !

**Comment by snaow** [comment] 2017-04-27 15:49
I am glad the work around do the trick for you.

Agree with the native Syslog JSON, thanks for the feedback and ideas.

**Comment by irctrakz** [comment] 2017-05-05 20:23
+1 for the full JSON output over syslog. Also the ability to remove syslog headers so syslog message is entirely JSON.

**Comment by vikman90** [comment] 2017-05-06 09:41
Hi,

@irctrakz we have adde this issue to our roadmap. We should read from file `alerts.json` instead of `alerts.log`, filter it and send the same JSON object to the Syslog server.

Thank you for you feedback!
Kind regards.

**Comment by ageis** [comment] 2017-08-19 12:22
+2

**Comment by vikman90** [comment] 2017-08-19 13:23
Hi @ageis and @irctrakz,

this feature is already available in new version 2.1 that we have just released! Please take a look to our documentation: [Release notes](https://documentation.wazuh.com/current/release-notes/release_2_1_0.html#new-features-for-internal-logs).

Let me close this issue. Thank you for your feedback!

**Closed by vikman90** 2017-08-19 13:23 UTC
Labels: enhancement

**Comment by ageis** [comment] 2017-08-19 20:33
@vikman90 Now that this ticket is cleared up, can I add a general question to it, and ask you about how often you pull in code from OSSEC upstream for the manager and agent and rules components? (I realize many are now switching to you guys now) but for instance, 2.9.2 just came out with a bunch of new rules..) For some reason I thought Wazuh had forked at version 2.8.3? That must be wrong of me, you have an entirely different versioning scheme of course.

The JSON output filter was out in 2.90 since February. When I last looked your site said there was only syslog alert output. Maybe I was looking at the 2.0 notes! Sorry about that. But anyway, I'm interested in switching; your documentation and the Kibana app is great, everything seems up to date, plus I can try out in Docker or VBox first...

Are other stakeholders like AtomCorp and AlienVault and Sucuri moving towards Wazuh too?

**Comment by vikman90** [comment] 2017-08-21 22:39
Hi @ageis,

thank you for your comment, I appreciate it so much. Let me answer your questions:

Wazuh had forked at OSSEC version 2.9 beta. Since then, we have been bringing the new code from OSSEC to the Wazuh project once for each Wazuh release at less. In fact we are working in importing the new rules to our [ruleset project](https://github.com/wazuh/wazuh-ruleset) and the functional code to this  repository.

Regarding to the JSON output, both OSSEC and Wazuh produce alerts in JSON format, and are able to output them via Syslog. The Syslog client (`ossec-csyslogd`) read the plain-text alerts and transformed them into JSON objects in order to send them:

> Log analysis engine (`analysisd`) → _alerts.json_
> Log analysis engine (`analysisd`) → _alerts.log_ → Syslog client (`csyslogd`)

We have introduced some improvements in the alerts, like full agent information (agent ID, name and IP) or dynamic fields. The thing is that the Syslog clients always reads the plain-text alerts no matter if the JSON alert output is enabled, and the Syslog client's plain-text alert parser was outdated.

This enhancement makes the Syslog client read the JSON alert output from the analysis engine and send the data directly to the Syslog server, bringing the new alert capabilities and improving the performance (since there is no alert re-parsing).

Answering your last question, we are talking to the OSSEC guys about moving to Wazuh and we hope so, but it does not depend on us.

Again, thank you for your comment.

Kind regards,
Victor.

**Comment by Lefnui** [comment] 2017-09-08 08:40
Hi,

Thanks for the update!
Just tested it and it seems that by specifying <format>json</format>, it no longer sends the syslog header, which is quite useful if you want to filter on these fields (PROGRAM for example).

I found a ugly workaround by filtering on the IP sending the logs. Would it be possible to add the syslog headers for the json format?

**Comment by vikman90** [comment] 2017-09-08 11:26
Hi @Lefnui,

you are right, there was no "ossec" program: 

```
Sep  8 12:04:28 localhost {"timestamp": "2017-09-08T12:01:06+0200","rule":{"level":3,"description":"System Audit event.","id":"516","firedtimes":17,"mail":false,"groups":["ossec","rootcheck"],"cis":["6.2.9 RHEL7"],"pci_dss":["4.1"]},"agent":{"id":"001","name":"centos"},"manager":{"name":"vmubuntu"},"id":"1504864866.69282","full_log":"System Audit: CIS - RHEL7 - 6.2.9 - SSH Configuration - Empty passwords permitted {CIS: 6.2.9 RHEL7} {PCI_DSS: 4.1}. File: /etc/ssh/sshd_config. Reference: https://benchmarks.cisecurity.org/tools2/linux/CIS_Red_Hat_Enterprise_Linux_7_Benchmark_v1.1.0.pdf .","decoder":{"name":"rootcheck"},"data":{"title":"CIS - RHEL7 - 6.2.9 - SSH Configuration - Empty passwords permitted","file":"/etc/ssh/sshd_config"},"location":"rootcheck"}
```

I've just fixed it: https://github.com/wazuh/wazuh/commit/08c9351117039300a2805e9283086b4aa5dcb92b

The header is now similar to the old one:

```
Sep  8 13:18:12 myhost ossec: {"timestamp":"2017-09-08T13:18:12+0200","rule":{"level":3,"description":"System Audit event.","id":"516","firedtimes":12,"mail":false,"groups":["ossec","rootcheck"],"cis":["2.3 Debian Linux"],"pci_dss":["4.1"]},"agent":{"id":"000","name":"vmubuntu"},"manager":{"name":"vmubuntu"},"full_log":"System Audit: CIS - Debian Linux - 2.3 - SSH Configuration - Root login allowed {CIS: 2.3 Debian Linux} {PCI_DSS: 4.1}. File: /etc/ssh/sshd_config. Reference: https://benchmarks.cisecurity.org/tools2/linux/CIS_Debian_Benchmark_v1.0.pdf .","title":"CIS - Debian Linux - 2.3 - SSH Configuration - Root login allowed","file":"/etc/ssh/sshd_config","decoder":{"name":"rootcheck"},"hostname":"vmubuntu","location":"rootcheck"}
```

I hope you find it useful.
Thank all of you for feedback!

**Comment by ddpbsd** [comment] 2017-09-08 11:32
@vikman90 Who in the OSSEC project are you talking to about switching? Has there been interest?

**Comment by Lefnui** [comment] 2017-09-08 11:39
Wow! Thanks for the reactivity !
