### ISSUE TITLE
Load balancer cannot redirect agents after overflow of the file system on the worker in the cluster

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#10195] opened 2021-09-18 23:36 UTC
|Wazuh version|Component|Os system|
|---|---|
| 4.2.0 | Wazuh cluster| Red Hat 7.9 (Maipo)|

## Problem

Hello Wazuh team,

I am currently struggling with a rather strange bug in the operation of Wazuh. I have a cluster of three workers and one manager. Agents communicate with the cluster through the load balancer (nginx).

The problem is that when the filesystem to which Worker Wazuha dumps logs becomes full, the following things happen:
- Agents who are connected to the worker in this situation (which has just overfilled the filesystem) go into the "disconnected" state, and the loadbalancer is unable to switch them to other workers, because the system on which the worker is running still has ports 1514/1515 open which indicates that not all processes are shutting down. 
[possible solution]The agent must be able to receive a message from the worker that his filesystem is full and he should know to use another available worker in the cluster.
- After increasing the required space, the Worker is not able to resume his work by himself without restarting the worker

**Comment by orsifacundo** [comment] 2021-10-16 00:56
Hello @mradaszewski92,

As the issue is related to this other one https://github.com/wazuh/wazuh/issues/10504, I'm going to proceed and close this.

Regards.

**Closed** 2021-10-16 01:00 UTC
