### ISSUE TITLE
ossec-monitord expects configuration in /etc/ossec.conf instead of /var/ossec/etc/ossec.conf by default on debian 9

### ISSUE THREAD

**Issue by BurningNetel** [wazuh/wazuh#339] opened 2018-01-04 11:18 UTC
A clean install of Wazuh 3.1 from packages on Debian 9 reveals an issue with monitord.
When starting Wazuh via systemd or ossec-control, the monitord-daemon tries to read configuration from /etc/ossec.conf.

ossec.log tells me:
`2018/01/04 11:48:19 ossec-monitord: CRITICAL: (1226): Error reading XML file '/etc/ossec.conf':  (line 0).`

The ossec.conf configuration is valid according to multiple daemons when running them with the '-t' flag. I have changed only a few settings in ossec.conf that should not impact the way monitord reads its configuration or where the basepath of ossec itself is.
When starting monitord manualy with the flags '-f' and '-ddd' it runs without any issues, as it reads the configuration from the correct path.
Note that I have not added any agents other than the agent that runs by default on the master.
Other daemons run as expected.

I have not found a configuration option or read in the documentation that this is default behavior of monitord, hence I made it an issue.

**Comment by vikman90** [comment] 2018-01-09 10:39
Hi @BurningNetel,

I couldn't reproduce your issue. Don't worry about the path `/etc/ossec.conf`: that's because `ossec-monitord` and some other components perform _chroot_ for security purposes, so `/` is actually `/var/ossec`.

Normally an error at line 0 means one of these problems:
1. The file at `/var/ossec/etc/ossec.conf` does not exist.
2. The file does not have the proper permissions.
3. There is a syntax error in the file.

These are the permissions for the `ossec.conf`:
```
root@:/var/ossec/etc# ls -l ossec.conf
-rw-r----- 1 root ossec 7187 Jan  9 10:27 ossec.conf
```

For the third case, `xmllint` (from package `libxml2-utils`) may help you to detect syntax problems:
```
root@:/var/ossec/etc# xmllint ossec.conf
ossec.conf:242: parser error : Extra content at the end of the document
<ossec_config>
^
```

This problem does not affect Wazuh because it does accept multiple root tags. Please make these checks and write back to us if you find any problem.

Hope it help.
Best regards.

**Comment by vikman90** [comment] 2018-03-05 23:59
Hi @BurningNetel,

did you have time to take a look at this issue? As I told you we have not been able to reproduce this problem.

Please let us know if your issue is solved so we will close this issue.

Thanks.

**Closed** 2018-03-07 04:42 UTC

**Comment by CODE-REaD** [comment] 2020-06-08 18:14
### Environment: CentOS 7, Wazuh agent 3.12.0
In my case, there were multiple errors in my `ossec.conf` file, but neither my Wazuh startup command nor `/var/ossec/bin/ossec-syscheckd` were telling me where they were.

Wazuh simply said
> CRITICAL: (1226): Error reading XML file '/var/ossec/etc/ossec.conf':  (line 0).

but the errors were elsewhere in my file.

Thankfully, xmllint **did** locate the particular errors (_Opening and ending tag mismatch_)

Once my `ossec.conf` file tested clear with xmllint, I found that Wazuh's startup scripts began producing more accurate error messages about `ossec.conf`, this time the result of options I had specified incorrectly:
>ossec-syscheckd: ERROR: (1230): Invalid element in the configuration: 'skip_dev'.

Once I eliminated these errors as well, my Wazuh startup succeeded.

**Comment by vikman90** [comment] 2020-06-10 08:41
@CODE-REaD I'm glad you finally managed to solve this issue.

Indeed, the XML parser fails on "line 0" when there is a syntax error. Hopefully, we'll improve the configuration parser in further versions.

Best regards.
