### ISSUE TITLE
issue when taking build to run the project

### ISSUE THREAD

**Issue by sundarrdeveloper** [wazuh/wazuh#22397] opened 2024-03-07 06:41 UTC
Step 1; I have clone the project (https://github.com/wazuh/wazuh.git)  
Step 2:  based on the file install i'm trying to run the project that time these errors are occuring. 

Errors : 
make[4]: Entering directory '/root/wazhu/wazuh/src/data_provider/build'

[  5%] Building CXX object /root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/src/HTTPRequest.cpp.o

In file included from /root/wazhu/wazuh/src/shared_modules/http-request/src/urlRequest.hpp:18:0,

                 from /root/wazhu/wazuh/src/shared_modules/http-request/src/HTTPRequest.cpp:15:

/root/wazhu/wazuh/src/shared_modules/http-request/shared/fsWrapper.hpp: In static member function ‘static bool FsWrapper::exists(const string&)’:

/root/wazhu/wazuh/src/shared_modules/http-request/shared/fsWrapper.hpp:33:21: error: ‘std::filesystem’ has not been declared

         return std::filesystem::exists(name);

                     ^~~~~~~~~~

In file included from /root/wazhu/wazuh/src/shared_modules/http-request/src/factoryRequestImplemetator.hpp:15:0,

                 from /root/wazhu/wazuh/src/shared_modules/http-request/src/HTTPRequest.cpp:13:

/root/wazhu/wazuh/src/shared_modules/http-request/src/IRequestImplementator.hpp: At global scope:

/root/wazhu/wazuh/src/shared_modules/http-request/src/IRequestImplementator.hpp:76:38: warning: inline function ‘virtual const string IRequestImplementator::response()’ used but never defined

     virtual inline const std::string response() = 0;

                                      ^~~~~~~~

/root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/build.make:62: recipe for target '/root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/src/HTTPRequest.cpp.o' failed

make[4]: *** [/root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/src/HTTPRequest.cpp.o] Error 1

make[4]: Leaving directory '/root/wazhu/wazuh/src/data_provider/build'

CMakeFiles/Makefile2:127: recipe for target '/root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/all' failed

make[3]: *** [/root/wazhu/wazuh/src/shared_modules/http-request/build/CMakeFiles/urlrequest.dir/all] Error 2

make[3]: Leaving directory '/root/wazhu/wazuh/src/data_provider/build'

Makefile:94: recipe for target 'all' failed

make[2]: *** [all] Error 2

make[2]: Leaving directory '/root/wazhu/wazuh/src/data_provider/build'

Makefile:1745: recipe for target 'build_sysinfo' failed

make[1]: *** [build_sysinfo] Error 2

make[1]: *** Waiting for unfinished jobs....

[ 40%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_dbengine.cpp.o

[ 50%] Building CXX object CMakeFiles/dbsync.dir/src/sqlite/sqlite_wrapper.cpp.o

[ 60%] Linking CXX shared library lib/libdbsync.so

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

[ 60%] Built target dbsync

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

Scanning dependencies of target dbsync_example

Scanning dependencies of target dbsync_test_tool

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

[ 70%] Building CXX object example/CMakeFiles/dbsync_example.dir/main.cpp.o

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

[ 80%] Building CXX object testtool/CMakeFiles/dbsync_test_tool.dir/main.cpp.o

[ 90%] Linking CXX executable ../bin/dbsync_example

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

[ 90%] Built target dbsync_example

[100%] Linking CXX executable ../bin/dbsync_test_tool

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

[100%] Built target dbsync_test_tool

make[3]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

make[2]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/dbsync/build'

cd shared_modules/rsync/ && mkdir -p build && cd build && cmake     .. && make

-- The C compiler identification is GNU 7.5.0

-- The CXX compiler identification is GNU 7.5.0

-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Configuring done

-- Generating done

-- Build files have been written to: /root/wazhu/wazuh/src/shared_modules/rsync/build

make[2]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[3]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

Scanning dependencies of target rsync

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

[ 12%] Building CXX object CMakeFiles/rsync.dir/src/rsync.cpp.o

[ 25%] Building CXX object CMakeFiles/rsync.dir/src/rsyncImplementation.cpp.o

[ 37%] Linking CXX shared library lib/librsync.so

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

[ 37%] Built target rsync

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

Scanning dependencies of target rsync_test_tool

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[4]: Entering directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

[ 50%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/agentEmulator.cpp.o

[ 62%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/main.cpp.o

[ 75%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/oneTimeSync.cpp.o

[ 87%] Building CXX object testtool/CMakeFiles/rsync_test_tool.dir/managerEmulator.cpp.o

[100%] Linking CXX executable ../bin/rsync_test_tool

make[4]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

[100%] Built target rsync_test_tool

make[3]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[2]: Leaving directory '/root/wazhu/wazuh/src/shared_modules/rsync/build'

make[1]: Leaving directory '/root/wazhu/wazuh/src'

Makefile:812: recipe for target 'server' failed

make: *** [server] Error 2

 

Error 0x5.

Building error. Unable to finish the installation.

**Comment by jnasselle** [comment] 2024-03-11 12:10
Hi @sundarrdeveloper ,

At first sight, I noticed that you do not meet GCC/C++ minimum version (9.4) needed to compile Wazuh and you are using the master branch and it could be unstable.

My recommendations:
- Follow https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html
- Use a stable branch (usually tagged, could be released, or RC)

From my side:
- Open an issue to add a external dependencies minimal version on installation from the sources guide

Regards,
Nico

**Comment by sundarrdeveloper** [comment] 2024-03-13 11:34
based on the documentation i have tried the steps to run the project. after that if i run my ip address in the browser url it is showing site can't be reached,  can you help me to run the project and see the output in browser.

**Comment by jnasselle** [comment] 2024-03-13 11:58
Hi @sundarrdeveloper ,

Wazuh Server (the source code you are trying to compile) is the core part of Wazuh product but does not contain GUI OOTB. Please take a look at [Central Components](https://github.com/wazuh/wazuh-jenkins/issues/6212) and [Architecture](https://documentation.wazuh.com/current/getting-started/architecture.html) documentation.

I suggest you follow the next guide to install Wazuh Central Components in an easy way:
- [Virtual Machine](https://documentation.wazuh.com/current/deployment-options/virtual-machine/virtual-machine.html)
- [Quickstart](https://documentation.wazuh.com/current/quickstart.html#installing-wazuh)

Hope this helps!
Nico

**Comment by sundarrdeveloper** [comment] 2024-03-14 11:40
Hi, 

Only using github  source code I need to run the project  any other option available or help me to find the stable branch and commands to  complete.

**Comment by jnasselle** [comment] 2024-03-14 12:31
Hi @sundarrdeveloper ,

The compilation and installation from sources of the whole project are not documented to be executed as an OOTB tutorial.

As I mentioned previously, Wazuh's Central Components are made up of more than one package: Wazuh Server, Wazuh Indexer, and Wazuh Dashboard. Please take a look at https://github.com/wazuh/wazuh-jenkins/issues/6212 and [Architecture](https://documentation.wazuh.com/current/getting-started/architecture.html) documentation.

[Installation from sources documentation](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html) aims only at the Wazuh Server, but also you could generate an RPM/DEB using the [next guide](https://documentation.wazuh.com/current/development/packaging/index.html). Wazuh Indexer and Wazuh Dashboard can also be created from sources but you should follow the next URL https://github.com/wazuh/wazuh-packages/tree/v4.7.3/stack

On the other side, the last stable branch is the tag v4.7.3.

Hope this helps

**Comment by jnasselle** [comment] 2024-03-20 20:03
@sundarrdeveloper ,

Did you mean https://github.com/wazuh/wazuh-packages/tree/v4.7.3/debs right?

About your error, you are right, the example is outdated because we no longer release wazuh-api as a separate package, and currently is part of wazuh-manager.

In case you are looking only a compilation from sources for wazuh-manager, you just need to execute

```
./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3  -t manager -a amd64
```

Regards,
Nico

**Comment by sundarrdeveloper** [comment] 2024-03-21 07:17
Hi Nico, 

After running  this command :  ./generate_debian_package.sh -b v4.7.3 --packages-branch v4.7.3  -t manager -a amd64  i have got this information.

W: wazuh-manager: executable-not-elf-or-script var/ossec/framework/python/lib/python3.9/ensurepip/_bundled/pip-23.3.2-py3-none-any.whl
W: wazuh-manager: executable-not-elf-or-script var/ossec/framework/python/lib/python3.9/test/test_socket.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/ar-definitions.template
W: wazuh-manager: executable-not-elf-or-script var/ossec/wodles/azure/orm.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/integrations/virustotal.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/integrations/slack.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/integrations/maltiverse.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/framework/python/lib/python3.9/socket.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/localfile-logs/snort-logs.template
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/localfile-logs/audit-logs.template
W: wazuh-manager: executable-not-elf-or-script var/ossec/wodles/utils.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/integrations/shuffle.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/framework/python/lib/python3.9/ensurepip/_bundled/setuptools-65.5.1-py3-none-any.whl
W: wazuh-manager: executable-not-elf-or-script var/ossec/integrations/pagerduty.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/localfile-logs/ossec-logs.template
W: wazuh-manager: executable-not-elf-or-script var/ossec/framework/python/lib/python3.9/test/test_array.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/wodles/gcloud/exceptions.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/wodles/__init__.py
W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/etc/templates/config/generic/localfile-logs/apache-logs.template
N: 19467 tags overridden (10 errors, 19457 warnings)
Finished running lintian.

WARNING generated by debuild:
Making debian/rules executable!

+ deb_file=wazuh-manager_4.7.3-1
+ [[ amd64 == \p\p\c\6\4\l\e ]]
+ deb_file=wazuh-manager_4.7.3-1_amd64.deb
+ pkg_path=/build_wazuh/manager
+ [[ no == \y\e\s ]]
+ mv /build_wazuh/manager/wazuh-manager_4.7.3-1_amd64.deb /var/local/wazuh
Package wazuh-manager_4.7.3-1_amd64.deb added to /var/www/html/wazuh-packages/debs/output/.

**Comment by jnasselle** [comment] 2024-03-22 11:23
@sundarrdeveloper 

Those messages are just warnings and do not affect the package generation, but we've just create an issue to solve them https://github.com/wazuh/wazuh-packages/issues/2887

**Comment by sundarrdeveloper** [comment] 2024-04-01 04:30
Okay, thanks for updating.

**Comment by jnasselle** [comment] 2024-04-03 11:47
Closing this issue since it's not a bug on this repo, but a documentation one.

**Closed by jnasselle** 2024-04-03 11:47 UTC
Labels: reporter/community
