### ISSUE TITLE
How I can check "win_malware_rcl.txt" ?

### ISSUE THREAD

**Issue by santi10** [wazuh/wazuh#187] opened 2017-09-06 16:13 UTC
Hi,

I'm trying do a test for validate the "win_malware_rcl.txt". This file has a line like: "f:%WINDIR%\System32\nonzipsr.noz;" so I think that If I create this file into "C:\windows\system32\nonzipsr.noz", do I see a new alert??????

My wazuh server has this line into agent.conf, such as:

`
  <rootcheck>
    <disabled>no</disabled>
    <windows_audit>./shared/win_audit_rcl.txt</windows_audit>
    <windows_apps>./shared/win_applications_rcl.txt</windows_apps>
    <windows_malware>./shared/win_malware_rcl.txt</windows_malware>
  </rootcheck>`

So, What can I do for check that, please???

**Comment by vikman90** [comment] 2017-09-12 10:01
Hi @santi10,

sorry for late response, we are working on this issue.

The cause of this problem is that the Wazuh agent for Windows is a 32-bit application and it's running (surely) on a 64-bit Windows system.

Windows redirects the `C:\Windows\System32` path to `C:\Windows\SysWOW64` for 32-bit applications. In summary:

```
32-bit application   | Actual folder
---------------------+--------------------
C:\Windows\System32  | C:\Windows\SysWOW64
C:\Windows\SysNative | C:\Windows\System32
```

In other words, if we want to access the actual `System32` folder we should go to `C:\Windows\SysNative`. This has been already fixed for directories monitored by Syscheck: https://github.com/wazuh/wazuh/blob/master/src/win32/ossec.conf#L63

We are working on making the Rootcheck's controls available for 64-bit systems.

We'll keep you informed.
Thanks for you feedback.

**Comment by DaveVG1** [comment] 2019-04-17 14:06
Hi again @santi10 

First of all, sorry for the late response. This issue was fixed in https://github.com/wazuh/wazuh-ruleset-dev/pull/21

As @vikman90 said, `Sysnative ` folder has been included to be checked in `win_malware_rcl.txt` among others. This should fix your problem.

I'm closing this issue. Please feel free to re-open it if you have any further troubles regarding this issue.

Kind regards.

**Closed by DaveVG1** 2019-04-17 14:06 UTC
Labels: bug
