### ISSUE TITLE
Add s390x architecture to RPM build, or possibility to build direct without Internet access

### ISSUE THREAD

**Issue by Joeri-MS** [wazuh/wazuh#6728] opened 2020-11-25 09:59 UTC
We start using RedHat 8.3 on our s390x Mainframe systems.
So I build an RPM, wich seems to work fine.

Wazuh agent_control. Agent information:
   Agent ID:   28377
   Agent Name: guest0013
   IP address: xxx.xxx.xxx.xxx
   Status:     Active

   Operating system:    Linux |guest0013 |4.18.0-240.el8.s390x |#1 SMP Wed Sep 23 05:12:04 EDT 2020 |s390x [Red Hat Enterprise Linux|rhel: 8.3 (Ootpa)]
   Client version:      Wazuh v4.0.2 / 9cbb0003b45ad879966093bc9bbc21b7
   Shared file hash:    f3bb7d88bfe31b396f541c0bdd21bb6d
   Last keep alive:     Wed Nov 25 10:45:39 2020

   Syscheck last started at:  Wed Nov 25 10:35:30 2020
   Syscheck last ended at:    Wed Nov 25 10:35:33 2020

   Rootcheck last started at: Wed Nov 25 10:35:32 2020

The Inventory Tab dont konw the CPU:
Cores: 4
Memory: 3,720.74 MB
Arch: s390x
OS: Red Hat Enterprise Linux 8.3 (Ootpa)
CPU: unknown

The cpuinfo show the following:

vendor_id       : IBM/S390
# processors    : 4
bogomips per cpu: 21881.00
max thread id   : 0
features        : esan3 zarch stfle msa ldisp eimm dfp edat etf3eh highgprs te vx vxd vxe gs
facilities      : 0 1 2 3 4 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 30 31 32 33 34 35 36 37 38 40 41 42 43 44 45 47 48 49 50 51 52 53 54 57 58 59 60 64 65 69 71 73 74 75 76 77 78 80 81 82 129 130 131 133 134 135 138 139 146 147
cache0          : level=1 type=Data scope=Private size=128K line_size=256 associativity=8
cache1          : level=1 type=Instruction scope=Private size=128K line_size=256 associativity=8
cache2          : level=2 type=Data scope=Private size=4096K line_size=256 associativity=8
cache3          : level=2 type=Instruction scope=Private size=2048K line_size=256 associativity=8
cache4          : level=3 type=Unified scope=Shared size=131072K line_size=256 associativity=32
cache5          : level=4 type=Unified scope=Shared size=688128K line_size=256 associativity=42
processor 0: version = FF,  identification = 1E41E8,  machine = 3906
processor 1: version = FF,  identification = 1E41E8,  machine = 3906
processor 2: version = FF,  identification = 1E41E8,  machine = 3906
processor 3: version = FF,  identification = 1E41E8,  machine = 3906

cpu number      : 0
cpu MHz dynamic : 5208
cpu MHz static  : 5208

cpu number      : 1
cpu MHz dynamic : 5208
cpu MHz static  : 5208

cpu number      : 2
cpu MHz dynamic : 5208
cpu MHz static  : 5208

cpu number      : 3
cpu MHz dynamic : 5208
cpu MHz static  : 5208

To build i have todo the following:
1. Create an normal RPM on  an x86_64 system, grep the source RPM ans extract the Spec-file.
2. Build the Agent frome source on x86_64 to download the extra sources (openssl....), bevause my s390x system has no internet access
3. Change the spec file to remove/replace some Variables (%{_localstatedir}, %{_debugenabled}, %{_sysconfdir}, %{_initrddir} these where empty.....)
4. Change the Makefile to ignore the downloads from the internet, because the sources are allready there
5. rpmbuild ..... done

My Question is: Is it possible to create an specfile and source tar-ball on an system with internet access for building on an other system?

**Comment by vikman90** [comment] 2020-11-25 11:51
Hi @Joeri-MS,

We usually use the script `generate_rpm_package.sh` (https://github.com/wazuh/wazuh-packages/tree/master/rpms) to build RPMs. If I understood correctly, the problem is that `rpmbuild` is downloading the external dependencies even having them already.

In that case, I think these steps should help you out:

1. Download the external dependencies manually where you have access to the Internet:
```sh
src$ make deps
```

2. Remove such line from the SPEC file ([wazuh-agent-4.1.0.spec:45](https://github.com/wazuh/wazuh-packages/blob/master/rpms/SPECS/4.1.0/wazuh-agent-4.1.0.spec#L45)):
```
    make deps
```

3. Now you can run `rpmbuild` on a host without connection to the Internet.

Let me know if that helps you or you need further assistance.

Best regards.

**Comment by Joeri-MS** [comment] 2020-11-25 17:26
Thanks, that helps.
I made an extra tar.gz wich i included as source1....

**Comment by Joeri-MS** [comment] 2020-11-26 08:35
It works.
Here my workflow:

Disable debug:
echo '%debug_package %{nil}' > /etc/rpm/macros

Create wazu-4.0.2-external.tar.gz ( Content: wazuh-4.0.2/src/external/cJSON/...... )

[wazuh-agentspec.zip](https://github.com/wazuh/wazuh/files/5601420/wazuh-agentspec.zip)

Patch the spec-file to include the second source

Build the RPM
rpmbuild --define "_sysconfdir /etc" --define "_threads 2" --define "_release 1" --define "_localstatedir /var/ossec" --define "_debugenabled no" -ba wazuh-agent-4.0.2.spec

I also fix the CPU-Name problem with the s390x architecture.

[s390x-syscolector.zip](https://github.com/wazuh/wazuh/files/5601464/s390x-syscolector.zip)

(My problem is that i dont have full internet access from work.... so i cant make an git pull/push from here)

**Comment by vikman90** [comment] 2020-12-02 11:43
Hi @Joeri-MS. I'm glad that worked for you. Let me close this issue. Should you have further questions, please reopen it.

Best regards.

**Closed by vikman90** 2020-12-02 11:43 UTC
Labels: community, packages
