### ISSUE TITLE
Cluster - issues during testing

### ISSUE THREAD

**Issue by VAdamec** [wazuh/wazuh#391] opened 2018-02-14 08:07 UTC
Hi,
 documentation about cluster is quite short, not cover all topics, So there are some thoughts/questions/bugs which I found during testing:
1. Cluster clients itselves are not checked by OSSEC (only master), how this can be fixed ? It was installed as a standard Wazuh manager, just configuration in ossec.conf has different role
2. Kibana Wazuh module, I need to add all cluster members in API config to see correct state of nodes, is this correct behaviour or API should be also clustered ?
3. Cluster upgrade - test update from 3.1 to 3.2, cluster clients need to be removed and add again (some cluster DB issue ?) Also as cluster processes freezed and need to be killed manually, wazuh-manager.service restart doesn't stop them
4. Balancing, I use consul DNS and service registration, so I'm getting all active cluster members IP, it seems to work, but it's ok ? As a simple service check I use this (run locally on all cluster members):

```
/var/ossec/bin/cluster_control -n | grep connected | grep `hostname -s`
```

## Issue after 3.1 to 3.2 update - wazuh-clusterd processes still running after RPM update
```
$ /var/ossec/bin/cluster_control -p
ERROR: Error 3009 - Error connecting to cluster database: [Errno 111] Connection refused

$  ps -ef | grep clust
ossec    19404     1  0 22:00 ?        00:00:02 python /var/ossec/bin/wazuh-clusterd
ossec    19415 19404  0 22:00 ?        00:00:00 python /var/ossec/bin/wazuh-clusterd
root     25466     1  0 23:18 ?        00:00:00 /var/ossec/bin/wazuh-clusterd-internal -tmaster

$ tail -f /var/ossec/logs/cluster.log
2018-02-13 23:18:50,961 ERROR: Can't bind socket: [Errno 98] Address already in use
```

Right now running latest RPM of Wazuh 3 (3.2.0-1) and latest supported Kibana and Wazuh plugin.

**Comment by mgmacias95** [comment] 2018-02-14 12:13
Hello @VAdamec,

1. Each node in the cluster has its own Wazuh installation. The cluster purpose is to distribute load among multiple Wazuh managers, so each node is itself checked.

2. We're working to distribute our API so in the future all API information could be retrieved from the master node. If you use the API in the client nodes, **never register an agent in a client node**. Use it only to retrieve information about a client's status.

3. The database schema has changed from 3.1 to 3.2. The database should be removed in the upgrading process. Also, all processes should have been stopped in the upgrading process. We're looking into these issues to find out what could be wrong.  I'll keep you updated if we find the reason for these errors.

4. I understood you use several nodes IPs in the agents' configuration, right? The agents should be registered in the master node but a load balancer should be used to deliver the agent-reporting load among all nodes. Using several IPs on the agents' configuration won't deliver the load among all nodes. Also, to check connected nodes you can run the `cluster_control -n` command in the master node and it will tell you which nodes are active.

Best regards,
Marta

**Comment by branchnetconsulting** [comment] 2018-02-14 21:41
Hi Marta,

A question about your #4 item above.  If you use several manager IPs in the agent configuration, will the agent randomly pick from the list to determine which manager to contact, or does it attempt to connect to managers in the order listed, only moving down the list if a manager higher in the list could not be contacted?  If the agents respect the order of listed mangers, then at least a basic kind of load balancing could be achieved by putting the same list in a different order for different agents.  For example with manager A and manager B, if half of the agents were pointed at A,B and the other half were pointed at B,A, then I'd expect that half of the agents would prefer manager A and half would prefer manager B, while all of them would fail over to the surviving manager if their preferred manager went down.

Thanks in advance for clarifying this,
Kevin

**Comment by VAdamec** [comment] 2018-02-15 06:33
Hi @mgmacias95 
 1. Managers in client mode are not visible in Kibana
 but ```/var/ossec/bin/agent_control -lc``` clients are listed.

 2. It means that when master is down than Kibana will not work. So right now there is no way to do auto fallback ? So only manually change role and restart any other cluster client in master mode. What happens with cluster DB when old master will come up ?

 3. Make sense, it's a new feature I don't expect that it will run without any problems

 4. Consul DNS do roundrobin, so client will pickup randomly one IP  **BUT** on agent startup. Than it will be bound to resolved IP until restart.  Means that this type of load balancing cannot be used (if given cluster member is down you have to restart agent to activate connection). So for me only way right now is to add HAproxy to Consul service which will also contain all active cluster members (still issue when whole server is down, but this can be solved only by keepalived or some IP migration technique).

It will be helpful if client do DNS resolving at least during retry/server connection issue or support some master-master voting. Implementation of RAFT protocol ? ;-)

**Comment by mgmacias95** [comment] 2018-02-15 22:35
Hello @branchnetconsulting and @VAdamec,

Replying to @branchnetconsulting's question, that approach would work initially but I think it's not true load balancing.

You are choosing "manually" via sorting the IP's where the agents need to report to, at the moment they restart/start, but you can't anticipate what could happen if the nodes fail. 
Imagine the following scenario:

* agent A reporting to node 1
* agent B reporting to node 2

If node 2 is stopped, then agent B would start reporting to node 1, if node 2 recovers, the agent will still report to node 2.

That thing at scale, means, you can end up with all the agents reporting to the same node.

Something to take in consideration as well as how you can add/remove new nodes to the LB, in your case, you need to manually edit ossec.conf file in each node every time you want to add a new node, and that means you need to reboot your entire deployment every time you want to scale.

In summary, the idea could do the trick and simulate some LB but let's say it is not the ideal solution.

Replying to @VAdamec's questions:

1. The Kibana app should be configured with the master's API. Currently, only the master node has all the information about the cluster and its agents. Client nodes will only have partial information.

2. We're working on a high availability approach to elect a new master when the elected one is down. It will be available soon.

3. Can you give us more information about your environment in order to reproduce your error? Cluster options in your `ossec.conf`, any error or strange behaviour, an error/warning log line, etc? I think the cluster process blocked and the only option to kill it was using the `-SIGKILL` but I need to know why. Also, you said that agents needed to be registered again, weren't they reporting to the cluster?

4. Yes, a better approach would be registering all cluster nodes IPs in your load balancer and make a round robin each time an agent reports to a manager. On the other hand, an agent can have multiple IPs configured on its `ossec.conf` file, so you can configure your load balancer to pick _n_ random IPs instead of one.

Best regards,
Marta

**Comment by VAdamec** [comment] 2018-02-28 13:58
Used cfg is like example in documentation, node_type master/agent. Btw update to 3.2.0-2 (RPM) was without any problem.

```
<cluster>
  <name>lab-cluster</name>
  <node_name>wazuh-manager-lab001</node_name>
  <node_type>client</node_type>
  <key>xxxxxxxx</key>
  <interval>2m</interval>
  <port>1516</port>
  <bind_addr>0.0.0.0</bind_addr>
  <nodes>
    <node>xxx.xxx.xxx.001</node>
    <node>xxx.xxx.xxx.002</node>
  </nodes>
  <hidden>no</hidden>
  <disabled>no</disabled>
</cluster>
```

**Comment by VAdamec** [comment] 2018-02-28 14:01
Ad 4. multiple IPs in cfg is not good solution, adding/removing server will be massive change on all agents + restart (yes, can be handled by config management but still unnecessary). Support for service discovery will be best. Also support for some fallback IP/DNS name.

**Comment by mgmacias95** [comment] 2018-02-28 15:32
Hello @VAdamec ,

We are aware of this problem in our current configuration. We're working to remove client IPs from cluster configuration, making it easier to add and remove client nodes from the cluster.

Best regards,
Marta

**Comment by mgmacias95** [comment] 2018-05-29 08:16
Hello @VAdamec ,

We have officially release Wazuh v3.2.3 which solves many of the problems you had during your testing. Check our docs to update: https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html#upgrading-from-older-versions

Best regards,
Marta

**Comment by mgmacias95** [comment] 2018-05-30 16:36
Hello @VAdamec,

It's been more than a month since the last response (excluding mine) to this issue, so I'll proceed to close it.

Don't hesitate to open a new one if you still have questions or problems.

Thanks,
Marta

**Closed by mgmacias95** 2018-05-30 16:36 UTC

**Comment by vochanhdai-016** [comment] 2018-10-11 10:45
> Hello @branchnetconsulting and @VAdamec,
> 
> Replying to @branchnetconsulting's question, that approach would work initially but I think it's not true load balancing.
> 
> You are choosing "manually" via sorting the IP's where the agents need to report to, at the moment they restart/start, but you can't anticipate what could happen if the nodes fail.
> Imagine the following scenario:
> 
> * agent A reporting to node 1
> * agent B reporting to node 2
> 
> If node 2 is stopped, then agent B would start reporting to node 1, if node 2 recovers, the agent will still report to node 2.
> 
> That thing at scale, means, you can end up with all the agents reporting to the same node.
> 
> Something to take in consideration as well as how you can add/remove new nodes to the LB, in your case, you need to manually edit ossec.conf file in each node every time you want to add a new node, and that means you need to reboot your entire deployment every time you want to scale.
> 
> In summary, the idea could do the trick and simulate some LB but let's say it is not the ideal solution.
> 
> Replying to @VAdamec's questions:
> 
> 1. The Kibana app should make of use the master's API. Currently, only the master node has all the information about the cluster and its agents. Client nodes will only have partial information.
> 2. We're working on a high availability approach to elect a new master when the elected one is down. It will be available soon.
> 3. Can you give us more information about your environment in order to reproduce your error? Cluster options in your `ossec.conf`, any error or strange behaviour, an error/warning log line, etc? I think the cluster process blocked and the only option to kill it was using the `-SIGKILL` but I need to know why. Also, you said that agents needed to be registered again, weren't they reporting to the cluster?
> 4. Yes, a better approach would be registering all cluster nodes IPs in your load balancer and make a round robin each time an agent reports to a manager. On the other hand, an agent can have multiple IPs configured on its `ossec.conf` file, so you can configure your load balancer to pick _n_ random IPs instead of one.
> 
> Best regards,
> Marta

In the example "...If node 2 is stopped, then agent B would start reporting to node 1, if node 2 recovers, the agent will still report to node 2...". Can you detail the way that Wazuh cluster work to do that?
