### ISSUE TITLE
3.7.0 installation on Centos 7 show error in logs

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#2095] opened 2018-12-13 11:39 UTC
## Bug report

**OS**
_Centos 7_

**Wazuh version**
_3.7.0_

**Install type**
_Agent_

**Install method**
_packages_

**Log sample**

```
2018/12/13 10:42:32 agent-auth: INFO: Started (pid: 1413).
2018/12/13 10:42:34 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/12/13 10:42:34 ossec-execd: INFO: Started (pid: 1495).
2018/12/13 10:42:34 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/12/13 10:42:34 ossec-agentd: INFO: Version detected -> Linux |87fd6aae6d2f |4.4.0-1072-aws |#82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 |x86_64 [CentOS Linux|centos: 7 (Core)] - Wazuh v3.7.0
2018/12/13 10:42:34 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/12/13 10:42:34 ossec-agentd: INFO: Using AES as encryption method.
2018/12/13 10:42:34 ossec-agentd: INFO: Started (pid: 1500).
2018/12/13 10:42:34 ossec-agentd: INFO: Server IP Address: 172.100.211.189
2018/12/13 10:42:34 ossec-agentd: INFO: Trying to connect to server (172.100.211.189:1514/udp).
2018/12/13 10:42:34 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2018/12/13 10:42:34 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\\([[:alnum:]]\\+\\)\\ \\+[[:digit:]]\\+\\ \\+[[:digit:]]\\+\\ \\+\\(.*\\):\\([[:digit:]]*\\)\\ \\+\\([0-9\\.\\:\\*]\\+\\).\\+\\ \\([[:digit:]]*\\/[[:alnum:]\\-]*\\).*/\\1 \\2 == \\3 == \\4 \\5/' | sort -k 4 -g | sed 's/ == \\(.*\\) ==/:\\1/' | sed 1,2d
2018/12/13 10:42:34 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2018/12/13 10:42:34 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/12/13 10:42:34 ossec-logcollector: INFO: Started (pid: 1512).
2018/12/13 10:42:34 wazuh-modulesd: INFO: Process started.
2018/12/13 10:42:34 wazuh-modulesd:syscollector: INFO: Module started.
2018/12/13 10:42:34 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2018/12/13 10:42:34 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2018/12/13 10:42:34 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/12/13 10:42:35 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Started (pid: 1507).
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Monitoring directory: '/boot', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/sys/kernel/security'
2018/12/13 10:42:37 ossec-syscheckd: INFO: Ignoring: '/sys/kernel/debug'
2018/12/13 10:42:37 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/12/13 10:42:37 rootcheck: INFO: Started (pid: 1507).
2018/12/13 10:42:44 ossec-agentd: INFO: (4102): Connected to the server (172.100.211.189:1514/udp).
2018/12/13 10:42:46 ossec-logcollector: INFO: Agent is now online. Process unlocked, continuing...
2018/12/13 10:42:48 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/12/13 10:42:52 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/12/13 10:42:52 ossec-syscheckd: INFO: Starting syscheck scan.
2018/12/13 10:42:52 rootcheck: INFO: Starting rootcheck scan.
2018/12/13 10:42:57 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/12/13 10:43:05 rootcheck: INFO: Ending rootcheck scan.
2018/12/13 10:43:17 ossec-agentd: INFO: Agent is restarting due to shared configuration changes.
2018/12/13 10:43:18 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/12/13 10:43:18 wazuh-modulesd:syscollector: INFO: Module finished.
2018/12/13 10:43:18 ossec-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/13 10:43:18 ossec-logcollector: ERROR: (1129): Could not unlink file '/var/ossec/var/run/ossec-logcollector-1512.pid' due to [(2)-(No such file or directory)].
2018/12/13 10:43:18 ossec-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/13 10:43:18 ossec-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/13 10:43:18 ossec-execd: INFO: (1314): Shutdown received. Deleting responses.
2018/12/13 10:43:18 ossec-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2018/12/13 10:43:19 ossec-execd: INFO: Started (pid: 1752).
2018/12/13 10:43:19 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2018/12/13 10:43:19 ossec-agentd: INFO: Version detected -> Linux |87fd6aae6d2f |4.4.0-1072-aws |#82-Ubuntu SMP Fri Nov 2 15:00:21 UTC 2018 |x86_64 [CentOS Linux|centos: 7 (Core)] - Wazuh v3.7.0
2018/12/13 10:43:19 ossec-agentd: INFO: (1410): Reading authentication keys file.
2018/12/13 10:43:19 ossec-agentd: INFO: Using AES as encryption method.
2018/12/13 10:43:19 ossec-agentd: INFO: Started (pid: 1757).
2018/12/13 10:43:19 ossec-agentd: INFO: Server IP Address: 172.100.211.189
2018/12/13 10:43:19 ossec-agentd: INFO: Trying to connect to server (172.100.211.189:1514/udp).
2018/12/13 10:43:19 ossec-logcollector: INFO: Monitoring output of command(360): df -P
2018/12/13 10:43:19 ossec-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\\([[:alnum:]]\\+\\)\\ \\+[[:digit:]]\\+\\ \\+[[:digit:]]\\+\\ \\+\\(.*\\):\\([[:digit:]]*\\)\\ \\+\\([0-9\\.\\:\\*]\\+\\).\\+\\ \\([[:digit:]]*\\/[[:alnum:]\\-]*\\).*/\\1 \\2 == \\3 == \\4 \\5/' | sort -k 4 -g | sed 's/ == \\(.*\\) ==/:\\1/' | sed 1,2d
2018/12/13 10:43:19 ossec-logcollector: INFO: Monitoring full output of command(360): last -n 20
2018/12/13 10:43:19 ossec-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2018/12/13 10:43:19 ossec-logcollector: INFO: Started (pid: 1769).
2018/12/13 10:43:19 wazuh-modulesd: INFO: Process started.
2018/12/13 10:43:19 wazuh-modulesd:syscollector: INFO: Module started.
2018/12/13 10:43:19 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2018/12/13 10:43:19 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2018/12/13 10:43:19 wazuh-modulesd:oscap: INFO: Module disabled. Exiting...
2018/12/13 10:43:20 ossec-agentd: INFO: (4102): Connected to the server (172.100.211.189:1514/udp).
2018/12/13 10:43:20 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Started (pid: 1760).
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/etc', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/usr/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/usr/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/bin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/sbin', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Monitoring directory: '/boot', with options perm | size | owner | group | md5sum | sha1sum | sha256sum | mtime | inode.
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/mtab'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/hosts.deny'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/mail/statistics'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/random-seed'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/random.seed'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/adjtime'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/httpd/logs'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/utmpx'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/wtmpx'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/cups/certs'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/dumpdates'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/etc/svc/volatile'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/sys/kernel/security'
2018/12/13 10:43:22 ossec-syscheckd: INFO: Ignoring: '/sys/kernel/debug'
2018/12/13 10:43:22 ossec-syscheckd: INFO: No diff for file: '/etc/ssl/private.key'
2018/12/13 10:43:22 rootcheck: INFO: Started (pid: 1760).
2018/12/13 10:43:23 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2018/12/13 10:43:24 ossec-logcollector: INFO: Agent is now online. Process unlocked, continuing...
2018/12/13 10:43:37 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2018/12/13 10:43:37 ossec-syscheckd: INFO: Starting syscheck scan.
2018/12/13 10:43:37 rootcheck: INFO: Starting rootcheck scan.
2018/12/13 10:43:42 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2018/12/13 10:43:47 rootcheck: INFO: Ending rootcheck scan.
2018/12/13 10:44:05 ossec-syscheckd: WARNING: Cannot open '/boot': No such file or directory 
2018/12/13 10:44:05 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2018/12/13 10:44:10 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
```

Bug description
----------------
This error appears on installation process of 3.7.0, the error seems to appear when daemons are stopped with sigterm after received remote configuration of manager, Inspecting this file https://github.com/wazuh/wazuh/blob/3.7/src/init/ossec-client.sh#L199 , it seems to be this part of code:

```
rm -f ${DIR}/var/run/${i}*.pid
```

Regards.

**Comment by BraulioV** [comment] 2018-12-13 11:44
Hi,

in addition to this, the stop function of `ossec-client.sh` and `ossec-server.sh` are different:
https://github.com/wazuh/wazuh/blob/a94c82108f053f96c6d56a0274ad3a3ae5cb666e/src/init/ossec-server.sh#L422-L474
https://github.com/wazuh/wazuh/blob/a94c82108f053f96c6d56a0274ad3a3ae5cb666e/src/init/ossec-client.sh#L186-L203
The `stop` function in the ossec-client.sh deletes the pid file without waiting for the process to erase it.

Regards.

**Comment by vikman90** [comment] 2018-12-17 09:54
This issue is duplicate of #2071.

**Comment by JuantAldea** [comment] 2019-04-17 09:27
Closing as duplicate. 
Related issues: https://github.com/wazuh/wazuh/issues/2071, https://github.com/wazuh/wazuh/issues/2072, https://github.com/wazuh/wazuh/issues/2074, https://github.com/wazuh/wazuh/issues/2075, https://github.com/wazuh/wazuh/issues/2095

Please reopen if the error manifests again.

**Closed by JuantAldea** 2019-04-17 09:27 UTC
Labels: bug, core/logcollector, duplicate
