### ISSUE TITLE
Active Response Alerts

### ISSUE THREAD

**Issue by CBillinsRMG** [wazuh/wazuh#4754] opened 2020-03-19 10:15 UTC
Hi,

I'm having trouble with alerting when an IP has been blocked using the default active response scripts. When active response blocks the IP the log is ingested to Kibana but not as an alert.

I do have one manager that works but for the other the only difference I can see in the log entry is that the one that isn't working has GMT in the time/date.

Example entry that isn't working

Thu 19 Mar 05:27:22 GMT 2020 /var/ossec/active-response/bin/host-deny.sh delete - xxx.xxx.xxx.xxx 1584595041.586533952 31510

Any ideas? Would the GMT part be causing the issue?

Thanks,
Craig

**Comment by CBillinsRMG** [comment] 2020-03-19 10:18
I posted a delete event but this occurs when it is an add.

**Comment by Zenidd** [comment] 2020-03-19 15:23
Hello @CBillinsRMG 


> I do have one manager that works but for the other the only difference I can see in the log entry is that the one that isn't working has GMT in the time/date.

> Any ideas? Would the GMT part be causing the issue?

Not exactly, but the part causing the issue is close to the 'GMT' field. Let me paste here some AR sample logs along with the decoder that identifies them as AR events:

 - #### The following sample logs have the patterns that the default AR decoder further down is able to detect:

```
UNIX
Fri Dec  6 21:14:55 CET 2019 /var/ossec/active-response/bin/firewall-drop.sh delete - 1.84.172.7 1575634494.72911778 3396
WIN-A
Wed 12/07/2016 16:48:15.37 "active-response/bin/route-null.cmd" delete "-" "192.168.2.66" "1481129296.262924 100001 /home/test.txt (null)"
WIN-B
08/28/2018  09:25 "active-response/bin/netsh.cmd" delete "-" "1.2.3.4" "1535465731.23945822 18258 (some-hostname) any->WinEvtLog (null)"
```
```XML
<!-- /var/ossec/ruleset/decoders/0010-active-response_decoders.xml -->
<decoder name="ar_log">
  <prematch>^\w\w\w \w+\s+\d+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/|^\w\w\w \d\d/\d\d/\d\d\d\d \.+"active-response/bin/|^\d\d/\d\d/\d\d\d\d \.+"active-response/bin/</prematch>
</decoder>
```

 -  #### Seems like your server is UNIX kind (it is triggering an `sh` script) so lets compare your log with the UNIX pattern:

```XML
^\w\w\w \w+\s+\d+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/

Thu 19 Mar 05:27:22 GMT 2020 /var/ossec/active-response/bin/host-deny.sh delete - xxx.xxx.xxx.xxx 1584595041.586533952 31510
```
The `\w+\s+\d+` regex isn't satisfied by `19 Mar` and checking the UNIX pattern, the day is expected to come after the month, not before. So here is why the AR decoder isn't triggering.


- #### Let's modify the vanilla decoder to fit this:

As the day comes first, we should just swap the `\w+\s+\d+` sequence: `^\w\w\w \d+\s+\w+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/`, and add this pattern to the original decoder on `/var/ossec/ruleset/decoders/0010-active-response_decoders.xml ` :

```XML
<!-- /var/ossec/ruleset/decoders/0010-active-response_decoders.xml -->
<decoder name="ar_log">
  <prematch>^\w\w\w \d+\s+\w+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/|^\w\w\w \w+\s+\d+ \d\d:\d\d:\d\d \p*\w+ \d+ /\S+/active-response/bin/|^\w\w\w \d\d/\d\d/\d\d\d\d \.+"active-response/bin/|^\d\d/\d\d/\d\d\d\d \.+"active-response/bin/</prematch>
</decoder>
```

You can check if the log is correctly decoded on the `/var/ossec/bin/ossec-logtest` tool:
```
**Phase 2: Completed decoding.
       decoder: 'ar_log'
       script: 'host-deny.sh'
       type: 'delete'
       srcip: 'xxx.xxx.xxx.xxx'
       id: '1584595041.586533952'
       extra_data: '31510'

**Phase 3: Completed filtering (rules).
       Rule id: '604'
       Level: '3'
       Description: 'Host Unblocked by host-deny.sh Active Response'
**Alert to be generated.
```

I also recommend checking our '[changing an existing decoder](https://documentation.wazuh.com/3.11/user-manual/ruleset/custom.html#changing-an-existing-decoder)' documentation section where you can read about good practices when vanilla decoders are modified.

Let me know how it goes !
Greetings, 
JPablo

**Comment by CBillinsRMG** [comment] 2020-03-19 16:35
@Zenidd Thanks that worked! I have also followed the documentation you posted for persistence when updated

**Comment by Zenidd** [comment] 2020-03-23 08:49
Hey @CBillinsRMG,

I'm glad it worked out! I'm closing the issue, tet us know if you need further guidance. 

Greetings, JP Sáez

**Closed by Zenidd** 2020-03-23 08:49 UTC
Labels: community, question, ruleset, status/awaiting reply
