### ISSUE TITLE
Firewall logging does not seem to work (empty firewall.log and nothing in archives.log/json)

### ISSUE THREAD

**Issue by MagnusMWW** [wazuh/wazuh#4628] opened 2020-02-20 10:06 UTC
Hello!
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|3.11.3-1|analysisd|Manager|RPM from repo|Centos 7|

I have an interesting issue where I want to collect logs from pf running on openbsd. I've set up loggning via syslog and configured wazuh to accept remote syslog-connections and verified that it works (system logs from the openbsd-syslogd arrives fine and are alterted on and/or stored in the archive.log/json-files). However, this is not the case with the firewall-logs from pf. They have the following format:

```
Feb 20 10:53:06 retsuko pf: Feb 20 10:53:06.704647 rule 0/(match) block in on tun0: 192.168.100.239.47639 > 85.24.248.50.443: . ack 1 win 256 <nop,nop,timestamp 1000733620 196378231> (DF)
Feb 20 10:53:10 retsuko pf: Feb 20 10:53:10.625278 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]
Feb 20 10:53:40 retsuko pf: Feb 20 10:53:40.625559 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]
```

When doing a test with one of these lines in ossec-logtest, I get the following:
```
2020/02/20 10:56:50 ossec-testrule: INFO: Started (pid: 2091).
ossec-testrule: Type one log per line.

Feb 20 10:53:40 retsuko pf: Feb 20 10:53:40.625559 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]


**Phase 1: Completed pre-decoding.
       full event: 'Feb 20 10:53:40 retsuko pf: Feb 20 10:53:40.625559 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]'
       timestamp: 'Feb 20 10:53:40'
       hostname: 'retsuko'
       program_name: 'pf'
       log: 'Feb 20 10:53:40.625559 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]'

**Phase 2: Completed decoding.
       decoder: 'pf'

**Phase 3: Completed filtering (rules).
       Rule id: '4100'
       Level: '0'
       Description: 'Firewall rules grouped.'
```
And when checking rule 4100 we can see that the reasoning behind dropping firewall-logs is:
```
<group name="firewall,">
  <rule id="4100" level="0">
    <category>firewall</category>
    <description>Firewall rules grouped.</description>
  </rule>

  <!-- We don't log firewall events, because they go
    -  to their own log file.
    -->
```
The problem is that this statement does not seem to be true, since that log file is still empty. When checking the internal_options.conf it seems that firewall loging should be enabled though:
```
# Analysisd Enable the firewall log (at logs/firewall/firewall.log)
# 1 to enable, 0 to disable.
analysisd.log_fw=1
# Maximum number of fields in a decoder (order tag)
```
So my question is how to deal with this situation? It's tempting to overwrite rule 4100 in local_rules.xml to have a level of 1 or something. I guess this would result in them being logged in archives.log/json at least, which is kinda what I want. But I'm also curious how other people are handling firewall logs in their setups.

**Comment by vikman90** [comment] 2020-02-20 12:19
Hi @MagnusMWW,

The firewall logs are a legacy method to route logs to another file (firewall.log). The analysis engine prints there logs that the decoder marked as firewall type (`<type>firewall</type>`), and extracted the following fields:

- `action`
- `srcip`
- `srcport`
- `dstip`
- `dstport`
- `protocol`

Just as you wrote in your comment, firewall logs are routed to _firewall.log_, but they are only printed if all the fields above were extracted.

Hope it helps.

Best regards.

**Comment by MagnusMWW** [comment] 2020-02-20 15:12
Hello @vikman90 ! Thank you for answering.

That certainly explains things. So the issue is likely that the way I'm sending pf-logs via syslog makes them unrecognizable by the decoder, however, they seem to hit the grouping rule to identify them as firewall-logs which causes this behavior. Looking through the relevant section in the file 0180-openbsd_decoders.xml reveals the following:
```
<!-- OpenBSD pf decoder (as a plugin - compiled).
  - Will extract the action,srcip,dstip,protocol,srcport,dstport
  - Examples:
  - Mar 30 15:33:26 enigma pf: Mar 30 15:32:33.483712 rule 2/(match) pass in on xl0: 140.211.166.3.6667 > 192.168.2.10.16290: P 7408:7677(269) ack 1773 win 2520 <nop,nop,timestamp 3960674784 2860123562> (DF)
  - Mar 30 15:47:05.522341 rule 4/(match) block in on lo0: 127.0.0.1.48784 > 127.0.0.1.23: S 1381529123:1381529123(0) win 16384 <mss 33184,nop,nop,sackOK,nop,wscale 0,[|tcp]> (DF) [tos 0x10]
  - Mar 30 15:54:22.171929 rule 3/(match) pass out on xl0: 192.168.2.10.1514 > 192.168.2.190.1030:  udp 73
  - Mar 30 15:54:22.174412 rule 3/(match) pass out on xl0: 192.168.2.10.1514 > 192.168.2.190.1030:  udp 89

  -->
<decoder name="pf">
   <type>firewall</type>
   <program_name>^pf$</program_name>
   <plugin_decoder>PF_Decoder</plugin_decoder>
</decoder>
```
The examples in the comments differ from mine as you can see. However, if I try to run one of the example-lines through ossec-logtest, it doesn't work either (i.e no fields are extracted), so perhaps there is a problem with the plugin-decoder somehow?

Anyway, I've worked around the issue by excluding the file 0180-openbsd_decoders.xml in ossec.conf, and instead included my own local version with the following changes:
```
<decoder name="pf">
   <program_name>^pf$</program_name>
   <regex>rule\s\d+/\(\w+\)\s+(\w+)\s+(\w+)\son\s(\w+):\s</regex>
   <order>action,direction,interface</order>
</decoder>

<decoder name="pf-detail-icmp">
  <parent>pf</parent>
  <prematch>icmp</prematch>
  <regex>rule\s(\d+)/\(\w+\)\s+(\w+)\s+(\w+)\son\s(\w+):\s(\S+)\s\.\s(\S+):\s</regex>
  <order>ruleid,action,direction,interface,srcip,dstip</order>
</decoder>

<decoder name="pf-detail">
  <parent>pf</parent>
  <regex>rule\s(\d+)/\(\w+\)\s+(\w+)\s+(\w+)\son\s(\w+):\s(\S+).(\d+)\s\.\s(\S+).(\d+):</regex>
  <order>ruleid,action,direction,interface,srcip,srcport,dstip,dstport</order>
</decoder>
```
This results in the logs being picked up in archive.log/json, and also populates some fields with data from the events as a bonus. This works for my use-case.
```
2020/02/20 16:06:03 ossec-testrule: INFO: Started (pid: 10160).
ossec-testrule: Type one log per line.

Feb 20 16:03:23 retsuko pf: Feb 20 16:03:23.071365 rule 0/(match) block in on tun0: 192.168.100.239.22000 > 77.72.169.212.3478: udp 32


**Phase 1: Completed pre-decoding.
       full event: 'Feb 20 16:03:23 retsuko pf: Feb 20 16:03:23.071365 rule 0/(match) block in on tun0: 192.168.100.239.22000 > 77.72.169.212.3478: udp 32'
       timestamp: 'Feb 20 16:03:23'
       hostname: 'retsuko'
       program_name: 'pf'
       log: 'Feb 20 16:03:23.071365 rule 0/(match) block in on tun0: 192.168.100.239.22000 > 77.72.169.212.3478: udp 32'

**Phase 2: Completed decoding.
       decoder: 'pf'
       ruleid: '0'
       action: 'block'
       direction: 'in'
       interface: 'tun0'
       srcip: '192.168.100.239'
       srcport: '22000'
       dstip: '77.72.169.212'
       dstport: '3478'
Feb 20 16:03:09 retsuko pf: Feb 20 16:03:09.121841 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]


**Phase 1: Completed pre-decoding.
       full event: 'Feb 20 16:03:09 retsuko pf: Feb 20 16:03:09.121841 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]'
       timestamp: 'Feb 20 16:03:09'
       hostname: 'retsuko'
       program_name: 'pf'
       log: 'Feb 20 16:03:09.121841 rule 0/(match) block in on tun0: fe80::3e97:eff:fead:f8d5.43851 > ff12::8384.21027: udp 297 [hlim 1]'

**Phase 2: Completed decoding.
       decoder: 'pf'
       ruleid: '0'
       action: 'block'
       direction: 'in'
       interface: 'tun0'
       srcip: 'fe80::3e97:eff:fead:f8d5'
       srcport: '43851'
       dstip: 'ff12::8384'
       dstport: '21027'
```
From this I could start adding rules if I wanted, or I'll just keep them searchable like this in archives.log/json.

**Comment by FernandoCP** [comment] 2020-02-27 12:45
Hello! @MagnusMWW 

The problem is that decoder doesn't extract fields if it has child. This happens because, after having assigned a plugin decoder, the child's information is used and that information doesn't have a plugin decoder. If didn't have a child this wouldn't happen, because it use the current information.

For example, the JSON decoder (in 0006-json_decoders.xml) hasn't children and runs the plugin decoder. 

```xml
<decoder name="json">
  <prematch>^{\s*"</prematch>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
</decoder>
```
However the pf decoder has the following child in /0455-pfsense_decoders.xml

```xml
<decoder name="pf-fields">
  <parent>pf</parent>
  <regex>^\S*,\S*,\S*,(\S*),\S*,\S*,(\S*),\S*,\S*,\S*,\S*,\S*,\S*,\S*,\S*,\S*,(\S*),\S*,(\S*),(\S*),(\S*),(\S*),\S*</regex>
  <order>id,action,protocol,srcip,dstip,srcport,dstport</order>
</decoder>
```
And this is why doesn't run its plugin decoder. It might work to remove ```<plugin_decoder>``` from pf decoder, and make a child decoder just below, that does have the plugin. Something like this:

```xml
<decoder name="pf">
   <type>firewall</type>
   <program_name>^pf$</program_name>
</decoder>

<decoder name="pf-child">
   <parent>pf</parent>
   <plugin_decoder>PF_Decoder</plugin_decoder>
</decoder>
```


Best regards,
Fernando

**Comment by MagnusMWW** [comment] 2020-03-02 13:15
Hello @FernandoCP !

Thank you for the clarification! I will look into this and see if it works in a test environment. If that is the case, then perhaps that is the route that I will take instead. I'll get back here later today with results.

**Closed** 2020-05-18 06:35 UTC
Labels: bug, community, ruleset

**Comment by FernandoCP** [comment] 2020-05-18 07:11
I'm closing this issue for inactivity, feel free to reopen it if you have any further questions.

Best regards, 
Fernando.
