### ISSUE TITLE
Wazuh App fails to list rules when a variable is used to define the rule level

### ISSUE THREAD

**Issue by ArielIvanOjeda** [wazuh/wazuh#16032] opened 2022-05-24 16:04 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.1-rev 40311| Server | Manager | Packages | Any |

Hello Team,

There seems to be an issue when using a variable for the rule level. The rules work fine, but when trying to list the rules from the Kibana interface, by going to Wazuh-Management-Rules, the interface clocks and displays an error. This does not happen when Listing files, only when listing rules after the file for the rules that use the variable for the rule level, is uploaded to the Manager. There is no error when saving the file from the Kibana interface and no error when restarting the Manager. This was tested in 4.2.4 too and the same happens.

## Steps to reproduce

- Add the rule to the Wazuh Manager.
Example:

```
<var name="LEVEL">0</var>
<rule id="100101" level="$LEVEL">
```

- Go to Wazuh->Management->Rules.

## Expected results

The Wazuh Kibana interface should list the complete ruleset.

## Current results

The interface fails to display the rules list and clocks until an error is displayed.
"Error when getting the items of rules"

![Error in 4 3 1](https://user-images.githubusercontent.com/97059668/170502509-a71f1b74-c26a-44ab-9c28-edf8281dc65a.jpg)

**Comment by mateojames** [comment] 2023-02-03 11:31
### UPDATE
I have been able to reproduce the behavior of the issue using the following configuration:
```
<group name="local,syslog,sshd,">

  <!--
  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2
  -->
  <var name="LEVEL">0</var>
  <rule id="100001" level="$LEVEL">
    <if_sid>5716</if_sid>
    <srcip>1.1.1.1</srcip>
    <description>sshd: authentication failed from IP 1.1.1.1.</description>
    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
  </rule>
</group>
```
By replicating the same configuration as described and using the `GET /rules` request, an error is thrown by the Wazuh API as expected:
<img width="1095" alt="image (1)" src="https://user-images.githubusercontent.com/64434083/216591863-de5d97c8-2709-40f7-815f-f0cbecb7c4bd.png">

**Comment by mateojames** [comment] 2023-02-10 18:58
### UPDATE


Inside the function `load_rules_from_file()` , the XML containing the rules is decoded with the function `load_wazuh_xml()`. 

<img width="969" alt="image" src="https://user-images.githubusercontent.com/64434083/218170172-8959501c-83b0-48d1-90c6-3f2ac4b533cc.png">

Once the data is retrieved, we can see the variable $LEVEL is not being replaced by its value defined in `<var name="LEVEL">0</var>`

![image](https://user-images.githubusercontent.com/64434083/218171412-1c55922d-ce40-4098-a363-eb4dd9186639.png)


This is the reason why we get the error `ValueError: invalid literal for int() with base 10: '$LEVEL'`. The program is trying to cast the attribute level of value "$LEVEL" to an int ( `xml_rule.attrib['level']` ), but as the attribute is a string, the error raises.

------------------------------------------------

The question now is, the original issue says "The rules work fine, but when trying to list the rules from the Kibana interface, by going to Wazuh-Management-Rules, the interface clocks and displays an error".

If the rules work fine, this means at some point, this XML is actually being parsed in a correct manner, with the value $LEVEL being replaced successfully. I will try to find at what point this happens, and what is the difference with this process of parsing the information.

I also don't know exactly where this variable replacement is taking place. I have found that the function `load_wazuh_xml()` cleans the data, to finally pass it to the function `fromstring()` from **defusedxml**.ElementTree.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/64434083/218173199-17e43ec9-05f6-4712-bd2c-d213f18263de.png">

My guess is the process takes place in this last function. But that doesn't explain why it would work someplace else and not here. I have further investigation to regarding when this variable replacement process happens, and why it is not working.

**Comment by mateojames** [comment] 2023-02-17 19:58
### UPDATE

El reemplazo de variables ocurre en la función `load_rules_from_py()` del archivo **rules.py**. 
Hoy en dia, tras encontrar un tag <rule>, primero se predefine un diccionario rule que ya contiene varios campos (inluido level), y luego partir de ahi según que se vaya encontrando dentro de la rule se lo modifica.

El reemplazo de variable ocurre en este proceso "secundario". Por ejemplo en el caso de `level`, enseguida se encontró el tag de rule, en el diccionario creado se le asigna el valor `'level': int (xml_rule.attrib ['level'])`. Pero si luego se encuentra un tag dentro de rule, que se encuentre dentro del set definido de DYNAMIC_FIELDS, se realiza el reemplazo del valor en el diccionario en caso de tratarse de una variable.

El error es que ya en esta primera definición del diccionario, se esta intentando castear a entero este nombre de variable, ya que todavía no ocurrió el reemplazo.

Por lo hablado, parece que se planea deprecar esta manera de parsear las reglas, pero de cualquier manera debe existir parcialmente una solución. La solución propuesta es de principio crear un diccionario que contenga las variables de forma `{nombre_variable: valor}`, no incluir ningún campo que se encuentre en DYNAMIC_FIELDS predefinido en el diccionario de principio, e ir agregándolos a medida que aparezcan. Si un tag que encontramos dentro de rule pertenece a DYNAMIC_FIELDS y su valor comienza con $, nos fijamos si existe este valor en nuestro diccionario de variables. Si es asi, realizamos el reemplazo, sino mantiene su valor.

**Comment by mateojames** [comment] 2023-02-23 19:38
Parcialmente se esta testando la implementación de los campos `id` y `name` que son los campos que sufren un casteo de tipo de dato previo a los reemplazo de variable, que es la causa principal del error. De cualquier manera en paralelo se esta testando una solución mas genérica, sin llegar al limite de hacer un refactor total ya que estando en el scope de deprecarse no lo amerita. La causa del error ya es clara, en los próximos días se terminaría el teste de la reimplementación.

**Comment by mateojames** [comment] 2023-02-27 13:14
UPDATE

A fix has been found, but an issue rises. The variables in this issue were defined inside the group tag. This doesn't work, as they are not found as variables if not defined outside this scope. I believe this issue must be addressed in the documentation, as it may lead to confusion, clarifying that variable definition must occur at base level. Other than that, there is no specification on limitations of the variable scope other than "variable that may be used in any place of the same file"

**Comment by davidjiglesias** [comment] 2023-03-15 11:22
We are missing the documentation PR with the changes

**Comment by mateojames** [comment] 2023-03-16 13:23
### A documentation PR has been made --> [#5972](https://github.com/wazuh/wazuh-documentation/pull/5972)

**Closed** 2023-04-24 11:10 UTC
Labels: type/bug, module/framework, module/api, reporter/operations, feed/rules, level/task
