### ISSUE TITLE
Improve the Syscollector module to allow a manual scan execution

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh#9223] opened 2021-07-06 22:30 UTC
# Description

Currently, the Syscollector module works only by a time interval, and it is not possible to perform any type of scan request to this module.
The aim of this issue is to define a set of actions for this component that could be executed on demand.

The analysis of this issue began in #9219.

# Requirements

This new feature requires:

- The Agentd module should be capable to parse and handle the commands coming from the Manager.
- The Syscollector module needs a queue capable of receiving these commands. The queue would be the existent one that is owned by Wazuh modules.
- The scan should be parametrized by the following options: 
  - Specific agents
  - All agents 
  - All agents that belong to a certain node
  - All agents that belong to a certain group
- The user should be able to launch the scan through the UI using a button that will be performing a query to an endpoint from the API. The UI will receive immediately a response that the scan started (or not) and a brief description of the process in JSON format.
- The normal flow of Syscollector has to keep working, but the module will only be able to run one scan at a time. A synchronization mechanism should be implemented to avoid the scan on demand interfere with a possible running scan triggered by time interval. The components to be scanned are defined by the ossec configuration file.

**Comment by DProvinciani** [comment] 2022-03-22 01:26
Closing the issue as this is a duplicate of https://github.com/wazuh/wazuh/issues/12552.

**Closed by DProvinciani** 2022-03-22 01:26 UTC
Labels: enhancement, core/syscollector
