### ISSUE TITLE
Solaris always downloads dependencies sources  due to "test -e" command incompatibility

### ISSUE THREAD

**Issue by jr0me** [wazuh/wazuh#21571] opened 2024-01-22 17:33 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 |  | Manager,Agent | Sources | All |

While working on generating the precompiled binaries for our external dependencies we found that Solaris installs always re-compiled them from sources instead of downloading the precompiled versions.

This seems to be related to how the `Makefile` checks if files are available or not, as `test -e` is not supported on all shells. See [Oracle Solaris 11.3 Reference Manuals: test](https://docs.oracle.com/cd/E86824_01/html/E54763/test-1.html)

**Comment by jnasselle** [comment] 2024-02-01 11:46
Hi @jr0me ,

This is a duplicate of https://github.com/wazuh/wazuh/issues/13400

Regards,
Nico

**Closed** 2024-05-08 14:52 UTC
Labels: type/bug, module/building, level/task
