### ISSUE TITLE
[Development] wazuh-modulesd: ERROR: Child process not found

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#6231] opened 2020-10-07 14:01 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.0-40001 | wazuh-modulesd | Agent | Packages | Debian and Ubuntu |

Hello team,

Performing some installation tests for `4.0.0`, I found the following errors in agent `ossec.log`:

**ARM Debian stretch agent**

```
wazuh-modulesd: ERROR: Child process 2146 not found
wazuh-modulesd: ERROR: Child process 2146 not found.
```

**AMD64 Ubuntu Xenial**

```
wazuh-modulesd: ERROR: Child process 2013 not found.
wazuh-modulesd: ERROR: Child process 2013 not found
```

The `ossec.log` files for both cases are attached below:

- **ARM Debian stretch agent**: [ossec.log](https://github.com/wazuh/wazuh/files/5341141/debian_arm_ossec_log.txt)
- **AMD64 Ubuntu Xenial**: [ossec.log](https://github.com/wazuh/wazuh/files/5341143/ubuntu_xenial_ossec_log.txt)

It is requested to investigate this problem and to solve it.

Best regards.

**Comment by vikman90** [comment] 2020-10-07 14:35
I think this is a duplicate of #6011.

**Closed** 2020-10-09 18:19 UTC
Labels: bug, cicd, core/modulesd, duplicate
