### ISSUE TITLE
local depends make ./configure.  

### ISSUE THREAD

**Issue by necrose99** [wazuh/wazuh#5143] opened 2020-05-31 17:17 UTC
cython , etc already installed ./configure make ? what happened. > ?
to a dynamic config. 

dynamic or static build ? my case im on gentoo so all the -dev crap gets shiped on emerge foo. 
no need for foo and foo-dev add on ... all in that.

but can i specify nope... rpi4 yeah static might be the way to go ... but on local no.

**Comment by pereyra-m** [comment] 2020-06-02 11:53
Hi!

I am not sure to understand the problem you are having. 
Could you please upload a capture of the situation, the information in the logs or the commands you are using? 

I'll be able to reproduce it if you share more details.
Regards!

**Comment by necrose99** [comment] 2020-06-02 12:56
./sh

Used to generate

./configure,  make
‐--------
Now it wants static binaries i assume


Make depends tries to download  everything...
This bit new..

Gentoo  is a meta distribution..

Emerge openssl typically has the most recent...
Headers are included installed with binaries.
Only gets x if it needs refactoring and sources cache was purged.

Expected was if build fails gripes about missing depends,  or just to
build.
Else emerge foo bar .. make again..


Make depends  --local

Test if system has all req items to just build might be a plus.

**Comment by pereyra-m** [comment] 2020-06-03 11:11
Hi, thank you for your answer.

The Wazuh installer sets the dependencies to a specific versions and downloads them when building `libwazuhext.so`.
This is done with `make deps` in the makefile. 

We can assure it will always work in this way.
The local versions are not used because of previous errors encountered compiling for different operative systems.

You may modify the `makefile` if you need to avoid downloading.

Regards!

**Comment by pereyra-m** [comment] 2020-06-12 12:17
Hi.

Let me post another option.
You may download the external dependencies with `make deps` and compile them only one time.
Then, you have to compress them and this file can be used if you have to install the manager again:

```
make deps
make TARGET=server external
tar -zcf ~/external.tar.gz external
```

I'm closing this issue but you don't hesitate in asking again if you need.

Have a nice day!
Regards.

**Closed by pereyra-m** 2020-06-12 12:17 UTC
Labels: community

**Comment by necrose99** [comment] 2020-06-12 19:00
No im using gentoo,  
Hybrid agent or local agent .  Server ..
 ossec gentoo ebuild i can hopefully modify to automatically build , 
USE="SEEVER" AGANT HYBRID,  
Other use flags , USe=""... emerge Wazuh
The python package however (rules) far simpler to do so... 

libwazuhext is separate,  id just build repo on it. 
Ie /wazuh/libwazu...git , 

However thanks for clarifying..
As typically gentoo has newerish tools akin to debian testing esp if on ~amd64 or ~arm64..

**Comment by necrose99** [comment] 2020-07-10 00:13
@pereyra-m newer package 
curl will not fetch your external deps.

cant get packages dirs  ie rpm or deb , paths , else I could Wrap ebuilds to rpm2tgz etc.  
nor is the debs/rpms on a release page , 
looks like its a full bleeping docker to just build X

normally https://github.com/wazuh/wazuh-ruleset  , setup.py or (even easier)   

dodir ebuild wrpaaper command  > /var/ossec/rules for ebuild , 

however ... 

https://gitweb.gentoo.org/repo/gentoo.git/tree/net-analyzer/ossec-hids/ossec-hids-3.6.0.ebuild 

with some fiddeling was trying to addapt osssec to do wazuh agents and the like, 

however scripts no loger drop a ./configure

**Comment by pereyra-m** [comment] 2020-07-16 01:14
Hello @necrose99 !

I'm sorry to hear you are having trouble, but I need you to share the commands you are using, or even the project if it's possible, in order to reproduce and fix the error.

**make deps** should always download all the packages needed , and **make external** compiles all the external libraries.
Is this issue related to [#1078](https://github.com/wazuh/wazuh/issues/1078) ?
In [this](https://github.com/wazuh/wazuh/issues/1078#issuecomment-657426487) comment there are instructions to trace the cause of the **deps** target failure. 
Were you able to test them? What was the output?

Regards.
