### ISSUE TITLE
Integrating the vpcflow logs wazuh

### ISSUE THREAD

**Issue by anjanaradhakrishnan** [wazuh/wazuh#22648] opened 2024-03-25 06:51 UTC
I have created a flowlogs with the destination type as s3 and vpc flow logs are getting stored in the s3 bucket.
- Integrated the s3 bucket with wazuh. We are using AWSgovcloud, so the region code is us-gov-west-1. This is the integration added in the ossec.conf

```
<wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>1m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <bucket type="vpcflow">
      <name>vpcflowlogs</name>
      <aws_profile>default</aws_profile>
      <regions>us-gov-west-1</regions>
  </bucket>
</wodle>
```

- To debug i have enabled the  ``` wazuh_modules.debug=2 ``` . This is the ossec.log i'm getting.  It's showing invalid region
```
2024/03/21 13:13:21 wazuh-modulesd:aws-s3[274022] wm_aws.c:136 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: new-vpcflow-log, Type: vpcflow, Profile: default)
2024/03/21 13:13:21 wazuh-modulesd:aws-s3[274022] wm_aws.c:379 at wm_aws_run_s3(): DEBUG: Create argument list
2024/03/21 13:13:21 wazuh-modulesd:aws-s3[274022] wm_aws.c:494 at wm_aws_run_s3(): DEBUG: Launching S3 Command: wodles/aws/aws-s3 --bucket new-vpcflow-log --aws_profile default --regions us-gov-west-1 --type vpcflow --debug 2
2024/03/21 13:13:22 wazuh-modulesd:aws-s3[274022] wm_aws.c:534 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
DEBUG: No retries configuration found in profile config. Generating default configuration for retries: mode: standard - max_attempts: 10
DEBUG: Created Config object using profile: 'default' configuration
DEBUG: +++ Working on xxx - us-gov-west-1
DEBUG: +++ No logs to process in bucket: x/uxxs-gov-west-1
DEBUG: +++ WARNING: Check the provided region: 'us-gov-west-1'. It's an invalid one.
```

Tried integrating the same with commercial account with region code as `us-east-1` and is fetching the logs.

**Comment by shivaniclops** [comment] 2024-03-26 09:27
Same issue I'm also facing. Do we have any solution for gov cloud?

**Comment by Selutario** [comment] 2024-03-27 15:49
Hello! Thanks for the report. We will be reviewing this as soon as possible.

**Comment by fdalmaup** [comment] 2024-04-17 16:03
# Issue Update

The problem is due to the AWS GovCloud (US) regions not being part of the `ALL_REGIONS` constant used to verify that the input region is a valid one:
https://github.com/wazuh/wazuh/blob/c6412e52263bdce7b8be0e4625466b63b43aa65e/wodles/aws/aws_s3.py#L108-L113

This is verified in the methods of the `AWSVPCFlowBucket` in charge of fetching the logs from the S3 bucket:

https://github.com/wazuh/wazuh/blob/c6412e52263bdce7b8be0e4625466b63b43aa65e/wodles/aws/aws_s3.py#L1756-L1791

**Comment by Selutario** [comment] 2024-05-23 08:55
I'm closing this for now because we haven't gotten any updates. Please, reopen if you can attach results of the modifications proposed by @fdalmaup [here](https://github.com/wazuh/wazuh/issues/22648#issuecomment-2061653089).

**Closed by Selutario** 2024-05-23 08:55 UTC
Labels: type/bug, level/task
