### ISSUE TITLE
AWS CloudWatch events are analyzed more than once

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#15610] opened 2022-12-05 16:35 UTC
|Wazuh version|Component|
|---|---|
| 4.4.0-1 | AWS CloudWatch Integration |

### Description
AWS Cloudwatch integration events are analyzed more than one time. 
In the case of restarting the manager, the already analyzed events are sent to analysis again. This produce the same event that triggers multiple alerts, flooding the manager.

### Steps to reproduce
- Set  modulesd debug to 2 (`/var/ossec/etc/local_internal_options.conf`):
```
wazuh_modules.debug=2
```
- Configure a cloud watch integration (using two log groups):
```
 <wodle name="aws-s3">
  <disabled>no</disabled>
  <interval>30m</interval>
  <run_on_start>yes</run_on_start>
  <skip_on_error>yes</skip_on_error>
  <service type="cloudwatchlogs">
    <aws_profile>prod</aws_profile>
    <aws_log_groups>log_group1,log_group2</aws_log_groups>
    <regions>us-east-1</regions>
  </service>
 </wodle>
```

- Generate a log in a log stream of the log group.
- Restart the manager
- Check that the event has been pulled
- Wait for a few minutes
- Restart the manager
- Check that the same event has been pulled again, triggering the same alert if proceed.

### Video

[testing.webm](https://user-images.githubusercontent.com/11089305/205691066-362282a2-41a7-4959-be79-49645014f821.webm)

## Evidences
- [ossec.log](https://github.com/wazuh/wazuh/files/10176651/ossec.log)
- [archives.log](https://github.com/wazuh/wazuh/files/10176653/archives.log)

<hr>

After a meeting with @CarlosRS9, we have launched the command manually, getting a database lock error 
```
DEBUG: +++ Error: database is locked
Unknown error: database is locked
Traceback (most recent call last):
  File "/var/ossec/wodles/aws/aws-s3.py", line 3716, in <module>
    main(sys.argv[1:])
  File "/var/ossec/wodles/aws/aws-s3.py", line 3702, in main
    service.get_alerts()
  File "/var/ossec/wodles/aws/aws-s3.py", line 3163, in get_alerts
    self.save_data_db(log_group=log_group, log_stream=log_stream, values=db_values)
  File "/var/ossec/wodles/aws/aws-s3.py", line 3366, in save_data_db
    self.db_cursor.execute(self.sql_cloudwatch_insert.format(table_name=self.db_table_name,
sqlite3.OperationalError: database is locked
```

**Comment by CarlosRS9** [comment] 2022-12-13 15:41
After reviewing the error at the time, we were able to conclude that the reason why the duplicates were being processed was due to the combination of the use of `<skip_on_error>yes</skip_on_error>` and the error present when attempting to update the database. Since the execution continued because of the `skip_on_error` option, the execution finished without updating the database, which means that in subsequent executions the exact same events would be processed again since they are marked as processed in the database.

Regarding the `sqlite3.OperationalError: database is locked` error that prevented us from updating the database during this test, **we have not been able to replicate it manually yet**, neither in a local docker environment nor using an EC2 instance in our Amazon Wazuh-dev environment.

The `database is locked` error could theoretically correspond to one of the possible causes:

1. An attempt is made to execute a query on the database that is already being used by another query.
2. A query takes too long to finish its execution, generating a timeout that would trigger the error message.

Every step in our module is always executed sequentially, so it would not be possible to try to perform a query on the database without first having finished the previous one, so the first cause would not be possible, unless there is something wrong in the way we are closing the connection, which does not seem to be the case.

We have performed numerous manual tests trying to replicate the error without success. The following are some of the tests performed and the environment used.

### Details of the tests

To determine if the error could be influenced by the volume of log streams available in CloudWatch Logs the following log groups were used for testing in the Wazuh-dev environment:

- A log group (`/aws/lambda/stacks-autodeletion-dev-StackDeletion-1C39U4MYP099A`) which in turn contains 25411 log streams containing 8 log events each.
- A log group (`fluent-bit-cloudwatch`) with a single logstream but containing hundreds of log events.
- Two empty log groups (`framework-test` and `4_4_test`) which had a single log stream created and a single log event inserted into them during the test.
- A log group (`/aws/ecr/image-scan-findings/framework-test-ecr-repository`) which in turn contains 26 log streams containing 8 log events each.


The tests were performed both by invoking the script manually and by using the ossec.conf. Different combinations were also used, i.e. it was tested to run with a single log group and with different combinations of the previously indicated log groups.

Regarding the database, the tests were carried out by previously deleting the DB and also by using an existing database with little data (from a previous execution) and another one with 50,000 rows inserted manually. In neither case did this make a difference in causing the error.

These tests were performed in a Docker environment with 4.4 installed from source and on an EC2 instance (t2.medium) installing via quickstart using the same command as indicated in the E2E testing issue.

During all the tests performed only once the error message `sqlite3.OperationalError: database is locked` appeared while running the module using the EC2 instance. However, when trying to replicate the error by following exactly the same steps it was not possible to force the error to appear again. A possible explanation for this could be that the error was caused by a performance issue with the EC2 instance that caused the INSERT query to take longer than supported.

### Conclusions

It has not yet been possible to replicate the error, so we cannot 100% confirm the root cause. On the other hand, although reviewing all the changes introduced for the AWS module it does not seem that this error is unique to `4.4`, but could also occur in `4.3`, we cannot confirm this just yet as it has not been possible to replicate it.

**Comment by CarlosRS9** [comment] 2022-12-14 16:25
We were able to perform a some additional tests after having direct access to the original host on which this error was detected. Here are the details and the results:

First of all, the details about the host in the Wazuh-QA environment are as follows:


```
EC2 instance: m5.large (2CPU/8GB)

OS
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.6"
```

After accessing the host, we tried to run the module manually to see if the error was still present. The execution ended with the expected `database locked` error.

Then we checked the database file. Here are the contents of the AWS folder:
```
# ll /var/ossec/wodles/aws/
total 4380
-rwxr-x---. 1 root wazuh 1045 nov 29 20:54   aws-s3
-rwxr-x---. 1 root wazuh 175900 Dec 14 10:11 aws-s3.py
-rw-r--r--. 1 root root 3055616 Dec 14 08:37 aws_services.db
-rw-r--r--. 1 root root 817208 Dec 14 11:00  aws_services.db-journal
```

As we can see there is a database with an approximate size of 3.1 MB and a `journal` file. The database did not contain any unusual or invalid rows.

After deleting the `journal` file we tried to manually run the module again but the result was the same error.

We decided to create a backup file of the `aws_services.db` file, keeping the permissions and ownership. Then we deleted the original database file to force a clean run. This time no errors were present and the module ran correctly for about 2 hours.

After that, we deleted the new database file and restored the backup, keeping permissions and ownership. After the restoration process, we ran the module again expecting the same error. However, this time the module worked correctly, despite using the same potentially problematic database file.


Finally, we proceeded to create another EC2 instance but using the Wazuh-dev environment and once configured in the same way we copied the database backup file and repeated the tests. The module did not fail this time either.



## Conclusions

We don't know why the `journal` file was present, but everything points to it being due to a manual execution that was cancelled inappropriately. On the other hand, it seemed that the module's issue could be the size of the database file, but this has also been proved wrong since after creating a copy of it, the module has been able to work using that backup without any issues.

Therefore, we cannot confirm the root cause of this error and we have no way to replicate it again, because despite using the database backup file, the module has not failed again.

Finally, none of the changes introduced in `4.4` would be related to this behaviour, so in case there is a problem with the database management, it would be inherited from `4.3`.

**Comment by davidjiglesias** [comment] 2023-01-10 10:05
We were not able to reproduce

**Closed by davidjiglesias** 2023-01-10 10:05 UTC
Labels: type/bug, module/aws, reporter/qa, module/cloud monitoring, team/framework
