### ISSUE TITLE
Release 4.7.2 - RC 1 - E2E UX tests - GCP integration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#21049] opened 2023-12-22 16:13 UTC
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.7.2-rc1/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the CICD team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the CICD team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing/publication` objective and `Very high` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Dec 27, 2023 and notify the @wazuh/framework team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/framework team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Dec 28, 2023 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Dec 29, 2023.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Debian 12 x86_64 |
| Server | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Debian 12 x86_64 |
| Dashboard | [Quickstart](https://documentation-dev.wazuh.com/v4.7.2-rc1/quickstart.html) | - | Debian 12 x86_64 |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.7.2-rc1/installation-guide/wazuh-agent/index.html) | - | Debian 12 x86_64 |

## Test description

Configure the GCP integration in a Wazuh Manager and a Wazuh Agent.
Try both Pub/Sub and Storage integrations.
Test some use cases and ensure the alerts are correctly displayed on the GCP dashboard.

Documentation: https://documentation-dev.wazuh.com/v4.7.2-rc1/gcp/index.html

## Known issues

- https://github.com/wazuh/wazuh-documentation/issues/4996 
- https://github.com/wazuh/wazuh-documentation/issues/5699 
- https://github.com/wazuh/wazuh-documentation/issues/5505 
- https://github.com/wazuh/wazuh/issues/15615 

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below. **REMOVE CURRENT EXAMPLES**:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟡   | Deploy indexer, manager and dashboard in debian 12| The installation assistant does not support debian 12 | Everything installed and worked using the -i flag. |
| 🟡  | Agent installation | initial configuration failed to set the server IP declared in WAZUH_MANAGER variable | This happened becasue I didn't purge the previous agent installation, and apt thought it was not a new install. |
| 🔴 | Buckets integration | Unable to check buckets due to GCP problem | The enrollment for a trial account failed several times with no error |
| 🟡 | GCP pre-requisites installation | Some packages failed to install using pip due to unsupported paclage version (PyYAML 5.4.1) and insuficient resources (grpcio) | We continued the test using system packages with no errors | 
| 🟢  | GCP configuration | GCP documentation about how to configure the integration worked as stated | |
| 🟡 | GCP dashboard | We could not test all dashboards | | 

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?

- Debian 12 is unsupported by the installation assistant. I needed to ask if I was expected to use the ignore option.
- The Quickstart documentation applies to all-in-one deployments, but the issues seem to instruct using a distributed deployment.

- Did you face any challenges not covered by the guideline?

  - There is not enough context to test all the use cases supported by dashboard, there is no documentation as to how to generate the required events to make everythoing work.

- Suggestions for improvement:
  - Define the tests beyond selecting the deployment options and the basic documentation. The uses cases we're testing must be clearly defined so we can test them consistently.

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @davidjiglesias
- [x] @wazuh/framework

**Comment by gdiazlo** [comment] 2023-12-27 09:44
### Environment deployment

#### Cloud VMs

- https://github.com/wazuh/internal-devel-requests/issues/622

#### Indexer

<details>
<summary> 🟡 Indexer installed successfully with the -i option </summary>

- Download assistant and config.yml
- Edited config.yml

```
$ cat config.yml
nodes:
  # Wazuh indexer nodes
  indexer:
    - name: indexer
      ip: "172.31.45.57"
    #- name: node-2
    #  ip: "<indexer-node-ip>"
    #- name: node-3
    #  ip: "<indexer-node-ip>"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: server
      ip: "172.31.32.216"
    #  node_type: master
    #- name: wazuh-2
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker
    #- name: wazuh-3
    #  ip: "<wazuh-manager-ip>"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "172.31.39.11"
      
```


- Start installation ignoring the fact that this is debian 12, which is unsupported by the assistant

```
sudo bash wazuh-install.sh -i --wazuh-indexer indexer
26/12/2023 13:00:26 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.2
26/12/2023 13:00:26 INFO: Verbose logging redirected to /var/log/wazuh-install.log
26/12/2023 13:00:33 INFO: --- Dependencies ----
26/12/2023 13:00:33 INFO: Installing gawk.
26/12/2023 13:00:34 INFO: Installing lsof.
26/12/2023 13:00:36 WARNING: Hardware and system checks ignored.
26/12/2023 13:00:40 INFO: --- Dependencies ----
26/12/2023 13:00:40 INFO: Installing apt-transport-https.
26/12/2023 13:00:42 INFO: Installing software-properties-common.
26/12/2023 13:00:54 INFO: Installing gnupg.
26/12/2023 13:01:00 INFO: Wazuh development repository added.
26/12/2023 13:01:00 INFO: --- Wazuh indexer ---
26/12/2023 13:01:00 INFO: Starting Wazuh indexer installation.
26/12/2023 13:02:18 INFO: Wazuh indexer installation finished.
26/12/2023 13:02:18 INFO: Wazuh indexer post-install configuration finished.
26/12/2023 13:02:18 INFO: Starting service wazuh-indexer.
26/12/2023 13:02:40 INFO: wazuh-indexer service started.
26/12/2023 13:02:40 INFO: Initializing Wazuh indexer cluster security settings.
26/12/2023 13:02:42 INFO: Wazuh indexer cluster initialized.
26/12/2023 13:02:42 INFO: --- Dependencies ----
26/12/2023 13:02:42 INFO: Removing gawk.
26/12/2023 13:02:44 INFO: Removing lsof.
26/12/2023 13:02:46 INFO: Installation finished.
```

```
sudo bash wazuh-install.sh -i --start-cluster
26/12/2023 13:04:15 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.2
26/12/2023 13:04:15 INFO: Verbose logging redirected to /var/log/wazuh-install.log
26/12/2023 13:04:22 INFO: --- Dependencies ----
26/12/2023 13:04:22 INFO: Installing gawk.
26/12/2023 13:04:24 INFO: Installing lsof.
26/12/2023 13:04:26 WARNING: Hardware and system checks ignored.
26/12/2023 13:04:35 INFO: Wazuh indexer cluster security configuration initialized.
26/12/2023 13:05:40 INFO: --- Dependencies ----
26/12/2023 13:05:40 INFO: Removing gawk.
26/12/2023 13:05:42 INFO: Removing lsof.
26/12/2023 13:05:43 INFO: Wazuh indexer cluster started.
```


```
tar -axf wazuh-install-files.tar wazuh-install-files/wazuh-passwords.txt -O | grep -P "\'admin\'" -A 1
  indexer_username: 'admin'
  indexer_password: 'wjRt7XXXXXXXXXXXXXXu+pr+yE'
```


```
curl -k -u "admin:wjRtXXXXXXXXXXXXXX+yE" https://172.31.45.57:9200
{
  "name" : "indexer",
  "cluster_name" : "wazuh-indexer-cluster",
  "cluster_uuid" : "nuM5wFBeT7WZP55tcZqDEQ",
  "version" : {
    "number" : "7.10.2",
    "build_type" : "rpm",
    "build_hash" : "db90a415ff2fd428b4f7b3f800a51dc229287cb4",
    "build_date" : "2023-06-03T06:24:25.112415503Z",
    "build_snapshot" : false,
    "lucene_version" : "9.6.0",
    "minimum_wire_compatibility_version" : "7.10.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "The OpenSearch Project: https://opensearch.org/"
}
```


```

curl -k -u "admin:wjRt7IXXXXXXXXXXXr+yE" https://172.31.45.57:9200/_cat/nodes?v
ip           heap.percent ram.percent cpu load_1m load_5m load_15m node.role node.roles                               cluster_manager name
172.31.45.57            7          94  11    0.09    0.31     0.19 dimr      data,ingest,master,remote_cluster_client *               indexer
```
</details>

**Comment by gdiazlo** [comment] 2023-12-27 10:27
### GCP configuration

#### pre-requisites

<details>
<summary> 🟡 Unable to install some dependencies following the documentation</summary>

Installing the requires python packages in debian 12, in a VM with 2 GB of RAM there were multiple problems:

- I needed to install `libffi-dev` package
- I could not build `PyYAML` version 5.4.1, the systems come with `PyYAML` 6.0.1 and I ended up using this
- I could not build grpcio, probably due to lack of resources (tried with 2 and 4 GB of RAM the linker failed to build the library), I used the system package `python3-grpcio` version 1.51.1-3+b1 
After installing

```
pip3 install --break-system-packages cachetools==4.1.0 certifi==2022.12.07 cffi==1.14.4 chardet==3.0.4 charset-normalizer==2.0.4 google-api-core==1.30.0 google-auth==1.28.0 google-cloud-core==1.7.1 google-cloud-pubsub==2.7.1 google-cloud-storage==1.39.0 google-crc32c==1.1.2 google-resumable-media==1.3.1 googleapis-common-protos==1.51.0 grpc-google-iam-v1==0.12.3  idna==2.9 libcst==0.3.20 mypy-extensions==0.4.3 packaging==20.9 proto-plus==1.19.0 protobuf==3.19.6 pyasn1-modules==0.2.8 pyasn1==0.4.8 pycparser==2.20 pyparsing==2.4.7 pytz==2020.1  requests==2.25.1 rsa==4.7.2 setuptools==59.6.0 six==1.14.0 typing-extensions==3.10.0.2 typing-inspect==0.7.1 urllib3==1.26.5
```

</details>

**Comment by EduLeon12** [comment] 2023-12-28 17:22
## Review Update

After analyzing the steps shown in the issue update and seeing the tests have passed and the fails have been reported or justified it can be concluded that the issue is approved.

LGTM !!

**Comment by Rebits** [comment] 2023-12-29 14:53
> Some packages failed to install using pip due to unsupported paclage version (PyYAML 5.4.1) and insuficient resources (grpcio)

If this situation applies, it would be advisable to open an issue addressing the consideration of upgrading PyYAML to higher version, or alternatively, evaluating the possibility of replacing the current version with `PyYAML>=5.4.1`.

**Action required (@gdiazlo)**: Create a documentation issue to track this situation

***

 > I could not create buckets due to an error in the GCP enrollment process for a trial.

A significant portion of the testing was not possible to follow up, and it is essential to acknowledge this aspect for future stages. However, it's important to note that the :red_circle: indicator is typically reserved for identifying new errors in the product, and this situation doesn't seem to align with that criterion.

**Action required** (@damarisg): Approve that this testing stage will not be carried on for this stage due to difficulties during the buckets creation

***


> Did you face any challenges not covered by the guideline?
> 
>     There is not enough context to test all the use cases supported by dashboard, there is no documentation as to how to generate the required events to make everything work.
> 
> Suggestions for improvement:
> 
>     Define the tests beyond selecting the deployment options and the basic documentation. The uses cases we're testing must be clearly defined so we can test them consistently.

***

I completely agree with your observation on this matter. The testing instructions currently lack clear indications regarding the testing environment and the specific tests to be performed. It is imperative to enhance and refine this testing template to provide more comprehensive guidance for effective testing.

In addition the template documentation page is outdated. https://documentation-dev.wazuh.com/v4.7.2-rc1/gcp/index.html should be replace with https://documentation-dev.wazuh.com/v4.7.2-rc1/cloud-security/gcp/index.html

**Comment by EduLeon12** [comment] 2023-12-29 15:18
Hi Team,

Regarding the action proposed:

> If this situation applies, it would be advisable to open an issue addressing the consideration of upgrading PyYAML to higher version, or alternatively, evaluating the possibility of replacing the current version with PyYAML>=5.4.1.
> 
> Action required (@gdiazlo): Create a documentation issue to track this situation



I want to clarify that this is a known issue and is already fixed and merged in this [PR](https://github.com/wazuh/wazuh-documentation/pull/6847) for Wazuh version 4.8.0.

**Comment by Rebits** [comment] 2023-12-29 15:21
LGTM

**Closed by Rebits** 2023-12-29 15:21 UTC
Labels: type/test, level/subtask
