### ISSUE TITLE
ossec-remoted dies randomly after a couple of minutes

### ISSUE THREAD

**Issue by galzetta** [wazuh/wazuh#3355] opened 2019-05-20 13:48 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.9.0 | ossec-remoted | Manager | RPM packages | CentOS 7 |

I recently noticed that ossec-remoted sometimes fails (a.k.a. the process dies) randomly. I enabled debugging and in the logs I see:

```
2019/05/20 15:13:54 ossec-remoted[16468] manager.c:537 at c_files(): DEBUG: Updating shared files sums.
2019/05/20 15:13:54 ossec-remoted[16468] manager.c:771 at c_files(): DEBUG: End updating shared files sums.
2019/05/20 15:13:54 ossec-analysisd[16459] state.c:100 at w_analysisd_write_state(): DEBUG: Updating state file.
2019/05/20 15:13:55 ossec-remoted[16468] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-remoted[16468] secure.c:408 at HandleSecureMessage(): ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/05/20 15:13:55 ossec-remoted[16468] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-remoted[16468] secure.c:408 at HandleSecureMessage(): ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/05/20 15:13:55 ossec-remoted[16468] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-remoted[16468] secure.c:408 at HandleSecureMessage(): ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/05/20 15:13:55 ossec-remoted[16468] mq_op.c:91 at SendMSG(): ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-remoted[16468] secure.c:408 at HandleSecureMessage(): ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Bad file descriptor'.
2019/05/20 15:13:55 ossec-remoted[16468] secure.c:246 at rem_keyupdate_main(): DEBUG: Checking for keys file changes.
2019/05/20 15:13:55 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:55 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:56 ossec-syscheckd: ERROR: socketerr (not available).
2019/05/20 15:13:56 ossec-syscheckd: ERROR: (1224): Error sending message to queue.
2019/05/20 15:13:56 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:57 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:58 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:13:59 ossec-remoted[16468] state.c:59 at rem_write_state(): DEBUG: Updating state file.
2019/05/20 15:13:59 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:00 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:01 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:02 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:03 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:04 ossec-remoted[16468] state.c:59 at rem_write_state(): DEBUG: Updating state file.
2019/05/20 15:14:04 ossec-remoted[16468] manager.c:537 at c_files(): DEBUG: Updating shared files sums.
2019/05/20 15:14:04 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:04 ossec-remoted[16468] manager.c:771 at c_files(): DEBUG: End updating shared files sums.
2019/05/20 15:14:05 ossec-remoted[16468] secure.c:246 at rem_keyupdate_main(): DEBUG: Checking for keys file changes.
2019/05/20 15:14:05 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:06 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:07 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:08 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:09 ossec-remoted[16468] state.c:59 at rem_write_state(): DEBUG: Updating state file.
2019/05/20 15:14:09 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:10 ossec-remoted[16468] mq_op.c:43 at StartMQ(): ERROR: (1210): Queue '/queue/ossec/queue' not accessible: 'Connection refused'.
2019/05/20 15:14:10 ossec-remoted[16468] secure.c:411 at HandleSecureMessage(): CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/05/20 15:14:10 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:11 ossec-syscheckd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2019/05/20 15:14:11 ossec-syscheckd: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
2019/05/20 15:14:11 ossec-logcollector: ERROR: socketerr (not available).
```

After this ossec-remoted and analysisd processes die. 

The queues exist and seem to have the correct permissions:

```
[root@localhost ~]# ls -l /var/ossec/queue/ossec/
total 0
srw-rw----. 1 ossec  ossec 0 20 mag 15.12 analysis
srw-rw----. 1 root   ossec 0 20 mag 15.12 auth
srw-rw----. 1 root   ossec 0 20 mag 15.12 com
srw-rw----. 1 root   ossec 0 20 mag 15.12 download
srw-rw----. 1 root   ossec 0 20 mag 15.12 logcollector
srw-rw----. 1 ossec  ossec 0 20 mag 15.13 monitor
srw-rw----. 1 ossec  ossec 0 20 mag 15.12 queue
srw-rw----. 1 ossecr ossec 0 20 mag 15.12 request
srw-rw----. 1 root   ossec 0 20 mag 15.12 syscheck
srw-rw----. 1 root   ossec 0 20 mag 15.12 wmodules
```

When I restart the manager ossec-remoted works and is able to connect the agents and sync the configuration files. After 1-5 minutes the above mentioned errors occurs and it dies.

Is there any other information I could provide you to help me fix this issue?

**Comment by vikman90** [comment] 2019-05-20 15:07
Hi @galzetta,

First of all, thank you for reporting this bug. Per your logs, Remoted, Logcollector and Syscheck are reporting that they cannot connect to the Analysisd queue (_queue/ossec/queue_):

```
2019/05/20 15:14:10 ossec-remoted[16468] secure.c:411 at HandleSecureMessage(): CRITICAL: (1211): Unable to access queue: '/queue/ossec/queue'. Giving up..
2019/05/20 15:14:10 ossec-logcollector: ERROR: socketerr (not available).
2019/05/20 15:14:11 ossec-syscheckd: CRITICAL: (1211): Unable to access queue: '/var/ossec/queue/ossec/queue'. Giving up..
```

So, Syscheck and Remoted are exiting in a controlled manner. On the other hand, Analysisd is crasing, it is not printing any log.

The first question to address this issue is to find out why it's crasing. It may be due to a logical programming error or a system resource limitation.

Could you find some of these lines in the system log, please?
```sh
$ egrep "\(ossec-analysisd|ossec-analysisd\[" /var/log/messages

May 20 07:28:50 centos kernel: ossec-analysisd[2952]: segfault at 0 ip 0000000000423140 sp 00007ffc3a7d2150 error 6 in ossec-analysisd[400000+154000]
May 20 07:32:36 centos kernel: Out of memory: Kill process 6299 (ossec-analysisd) score 920 or sacrifice child
May 20 07:32:36 centos kernel: Killed process 6299 (ossec-analysisd) total-vm:2479836kB, anon-rss:408020kB, file-rss:0kB, shmem-rss:0kB
```

If the process crash is due to a segmentation fault, we may need some debugging information. I think it will be easy to gather it because you are able to reproduce the problem. Would you be able to compile a manager from sources and run it with GDB?

I wonder if there may be a bug in the regex engine. Are you using any special kind of decoder in your system?

Thank you again for your collaboration.
Best regards.

**Comment by galzetta** [comment] 2019-05-20 15:28
Here are the logs for analysisd that I obtain grepping with the command you provided. At a first glance I don't see any strange log line that would indicate an error.

[analysisd_log_messages.log](https://github.com/wazuh/wazuh/files/3198604/analysisd_log_messages.log)

I'm currently already compiling the manager on my own and building the rpm using wazuh-packages, so I guess I could add debugging flags, rebuild the manager and try to debug analysisd. However I have very little experience in using GDB so if you could provide any directions on how to proceed with that part I'd be glad to help you.

**Comment by vikman90** [comment] 2019-05-20 16:50
Hi. Thank you for your logs.

This is the log that reports the issue.
```
May 20 14:47:15 localhost kernel: traps: ossec-analysisd[6951] general protection ip:425a3e sp:7fb8bf7fddc0 error:0 in ossec-analysisd[400000+d5000]
May 20 14:57:29 localhost kernel: traps: ossec-analysisd[11480] general protection ip:425a3e sp:7fa634ff8dc0 error:0 in ossec-analysisd[400000+d5000]
May 20 15:06:54 localhost kernel: traps: ossec-analysisd[12171] general protection ip:425a3e sp:7f4e227fbdc0 error:0 in ossec-analysisd[400000+d5000]
May 20 15:13:55 localhost kernel: traps: ossec-analysisd[16542] general protection ip:425a3e sp:7f092cff8dc0 error:0 in ossec-analysisd[400000+d5000]
May 20 16:54:58 localhost kernel: traps: ossec-analysisd[28745] general protection ip:425a3e sp:7f7ceeffcdc0 error:0 in ossec-analysisd[400000+d5000]
May 20 17:13:18 localhost kernel: traps: ossec-analysisd[31703] general protection ip:425a3e sp:7f21a87f7dc0 error:0 in ossec-analysisd[400000+d5000]
```

There are many causes that may produce a general protection fault: an illegal instruction, permission issue, a segmentation violation or even a hardware failure.

If you have a chance to run GDB, this is a little guide:

1. Start the mananger normally:
```sh
service wazuh-manager restart
```
2. Launch GDB and attach the debugging session to the Analysisd process running:
```sh
gdb /var/ossec/bin/ossec-analysisd $(pidof ossec-analysisd)
```
3. Let the process continue its execution:
```
continue
```
4. When the process crashes, you should see a message like:
```
Program received signal SIGSEGV, Segmentation fault.
```
Then, save a core dump, for instance, into _/tmp/analysisd.core_
```
generate-core-file /tmp/analysisd.core
```
5. Quit from GDB:
```
quit
```
6. Compress the core dump file:
```sh
gzip /tmp/analysisd.core
```

That file would be very helpful for us to find the line of code where the program crashed, and the memory context.

Analysisd does not send the shared configuration files. Remoted is the one that does it. But when the agents get their configuration updated, they restart and send a complete scan for most features (FIM, SCA, etc.). A large amount of data would increase the chance to crash.

Thank you again for your help.
Best regards.

**Comment by galzetta** [comment] 2019-05-21 08:17
Here is the core file generated as you described. I did get a segfault:

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f931ffff700 (LWP 7264)]
0x0000000000425a3e in DecodeConfigurationAssessment ()
```

By the way, the client is a windows agent installed on a Windows 10 VM.

[analysisd.core.gz](https://github.com/wazuh/wazuh/files/3201430/analysisd.core.gz)

**Comment by TJOSERAFAEL** [comment] 2019-05-21 08:56
Hi @galzetta ,

thank you for reporting your segfault trace, I noticed that the function ``DecodeConfigurationAssessment`` doesn't exists anymore in our source code.

By looking at this line:

https://github.com/wazuh/wazuh/commit/f0f1dbf60a278ffeba8ca2ef7f3acc68acac7449#diff-f0af52d1202c75b688e08d58c711b7ddL2030

The function name was changed to ``DecodeSCA`` on February 22. 

Do you have the Wazuh 3.9 manager compiled from sources before this change? 
If so could you please install the 3.9 from packages or from the tag `v3.9.0`.

Thank you for the feedback that you are giving to us!
Regards.

**Comment by galzetta** [comment] 2019-05-21 13:16
Apparently I was using an outdated version of `wazuh-packages` to build the manager's RPM. Using the latest version of `wazuh-packages` I cannot reproduce the issue anymore. I will try a couple of things in the next days to see if I'm able to trigger again this behaviour, but it might have simply been an issue with my build chain. Thanks a lot of the readiness in your response.

**Comment by vikman90** [comment] 2019-05-24 06:21
Hi @galzetta,

Thank you for your feedback and your help with this issue. Since you cannot reproduce this problem, let me close this issue. Please don't hesitate to reopen it if you run into any trouble again

Best regards.

**Closed by vikman90** 2019-05-24 06:21 UTC
Labels: bug, core/analysisd, operations, status/awaiting reply
