### ISSUE TITLE
Unexpected  'Agent Key Already in Use' Warning Arises During Windows Agent Restart via API

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#18533] opened 2023-08-22 12:47 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.5 | Remoted/API | Manager | Packages | Windows Server 2022

### Description

It has been detected an unexpected `Agent key already in use:` is created when a Widnows Wazuh agent is restarted using the API:
```
2023/08/22 11:06:18 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:06:50 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:06:55 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:07:00 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:07:16 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:07:21 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
2023/08/22 11:07:26 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
```

The warning appears to bear no implications within the environment. Moreover, it exclusively surfaces for Windows agents

### Steps to reproduce

- Deploy an environment with a manager and a Windows Agent
```
root@ip-172-31-7-85:/home/qa# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-7-85 (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: EC2AMAZ-N9OLJ1L, IP: any, Active

List of agentless devices:

root@ip-172-31-7-85:/home/qa# /var/ossec/bin/agent_control -i 002

Wazuh agent_control. Agent information:
   Agent ID:   002
   Agent Name: EC2AMAZ-N9OLJ1L
   IP address: any
   Status:     Active

   Operating system:    Microsoft Windows Server 2022 Datacenter
   Client version:      Wazuh v4.4.5
   Configuration hash:  ab73af41699f13fdd81903b5f23d8d00
   Shared file hash:    4a8724b20dee0124ff9656783c490c4e
   Last keep alive:     1692708237

   Syscheck last started at:  Tue Aug 22 11:07:31 2023
   Syscheck last ended at:    Tue Aug 22 11:07:53 2023
```

- Get an API token: `TOKEN=$(curl -u wazuhwazuh -k -X GET "https//localhost55000/security/user/authenticate?raw=true")`
- Restart the Windows agent using the API
```
root@ip-172-31-7-85:/home/qa# curl -k -X PUT "https://localhost:55000/agents/002/restart" -H "Authorization: Bearer $TOKEN"
{"data": {"affected_items": ["002"], "total_affected_items": 1, "total_failed_items": 0, "failed_items": []}, "message": "Restart command was sent to all agents", "error": 0}root@ip-172-31-7-85:/home/qa# 
```
- Check `ossec.log` for the warning:
```
2023/08/22 12:44:47 wazuh-remoted: WARNING: Agent key already in use: agent ID '002'
```

**Comment by vikman90** [comment] 2023-08-22 13:18
@Rebits this issue is a duplicate of https://github.com/wazuh/wazuh/issues/17706 (fixed in 4.5.2).

Best!

**Closed by vikman90** 2023-08-22 13:18 UTC
Labels: type/bug, level/task
