### ISSUE TITLE
Wazuh 4.7.1 Linux and macOS agent not honouring wildcards for log names.

### ISSUE THREAD

**Issue by JBsGitHubAccount** [wazuh/wazuh#21237] opened 2024-01-06 06:45 UTC
It seems in 4.7.1 Linux and macOS log collector fail when a wildcard is in the agent.conf file.

Both server and agent are running 4.7.1 on Rocky Linux 9

Unless I specify complete log file name in my agent.conf the path is ignored.

Sample use of wildcard Ossec.log output
2024/01/06 17:33:13 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/01/06 17:33:13 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2024/01/06 17:33:13 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/secure'.
2024/01/06 17:33:13 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/maillog'.
2024/01/06 17:33:13 wazuh-logcollector: INFO: Started (pid: 106852).

Sample of when a log file name is directly added to the agent.conf
2024/01/06 17:38:21 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/01/06 17:38:21 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/messages'.
2024/01/06 17:38:21 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/secure'.
2024/01/06 17:38:21 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/maillog'.
2024/01/06 17:38:21 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/remote-logs/2024/0106dhcpserver'.
2024/01/06 17:38:21 wazuh-logcollector: INFO: Started (pid: 107749).

Wildcard agent.conf sample
```
<agent_config>
<localfile>
<log_format>syslog</log_format>
<location>/var/log/remote-logs/2024/*</location>
</localfile>
</agent_config>
```

Named log file agent.conf sample
```
<agent_config>
<localfile>
<log_format>syslog</log_format>
<location>/var/log/remote-logs/2024/0106dhcpserver</location>
</localfile>
</agent_config>

```
Any help would be appreciated.

Additions, this is the output from a Windows 10 client running 4.7.1 using the wildcard statement.

```
2024/01/08 20:29:41 sca: INFO: Starting Security Configuration Assessment scan.
2024/01/08 20:29:41 wazuh-modulesd:syscollector: INFO: Module started.
2024/01/08 20:29:41 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/01/08 20:29:41 wazuh-agent: INFO: (1951): Analyzing event log: 'Application'.
2024/01/08 20:29:42 wazuh-agent: INFO: (1951): Analyzing event log: 'Security'.
2024/01/08 20:29:42 sca: INFO: Starting evaluation of policy: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win10_enterprise.yml'
2024/01/08 20:29:42 wazuh-agent: INFO: (1951): Analyzing event log: 'System'.
2024/01/08 20:29:42 wazuh-agent: INFO: (1950): Analyzing file: 'active-response\active-responses.log'.
2024/01/08 20:29:42 wazuh-agent: INFO: (1950): Analyzing file: 'c:\logs\2024\lonelog.log'.
```

Windows 10 agent.conf

```
<!-- Source file: default/agent.conf -->
<agent_config>

  <!-- Shared agent configuration here -->

</agent_config>
<!-- Source file: Windows-Desktop-Wildcard/agent.conf -->
<agent_config>
        <localfile>
                <log_format>syslog</log_format>
                <location>c:\logs\2024\*</location>
        </localfile>
</agent_config>
```

macOS Sonoma 4.7.1 Client without wildcard.

```
2024/01/08 20:53:47 wazuh-logcollector: INFO: (1604): Monitoring macOS logs with: /usr/bin/log stream --style syslog --type activity --type log --type trace --level info --predicate (process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd").
2024/01/08 20:53:47 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/logs/temp/macostest.log'.
```

macOS Sonoma 4.7.1 with wildcard. **(Log file not found)**

`2024/01/08 20:58:52 wazuh-logcollector: INFO: (1604): Monitoring macOS logs with: /usr/bin/log stream --style syslog --type activity --type log --type trace --level info --predicate (process == "sudo") or (process == "sessionlogoutd" and message contains "logout is complete.") or (process == "sshd") or (process == "tccd" and message contains "Update Access Record") or (message contains "SessionAgentNotificationCenter") or (process == "screensharingd" and message contains "Authentication") or (process == "securityd" and eventMessage contains "Session" and subsystem == "com.apple.securityd").
`

**Comment by jnasselle** [comment] 2024-01-10 14:06
Hi @JBsGitHubAccount ,

Although the wazuh-logcollector daemon does not show `Analyzing file`, your files that match the patterns are still being collected. 
The reasons for my answer:
- Discovery log message is in debug level `2024/01/10 13:52:37 wazuh-logcollector[22374] logcollector.c:1385 at check_pattern_expand(): DEBUG: (1957): New file that matches the '/tmp/test/*.log' pattern: '/tmp/test/test3.log'.
`
-  `Analyzing file '-like messages are only for statically defined logs.

On the other hand, I'm going to open an issue about `New file that matches` because it is not consistent on every OS, specifically, Windows Agent shows it at the info level.

Regards,
Nico

**Comment by jnasselle** [comment] 2024-02-15 17:13
Closing this issue because is a duplicate of https://github.com/wazuh/wazuh/issues/7245

**Closed by jnasselle** 2024-02-15 17:13 UTC
Labels: module/logcollector, reporter/community, type/troubleshooting
