### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by ruzzetto** [wazuh/wazuh#553] opened 2018-04-19 12:31 UTC
Hi,
apologize again, probably it's my fault. Wazuh is installed on ELK stack and is running fine. Already registered 2 agent (1 win and 1 centos) and they appear in wazuh app. My question: by default data are sent to wazuh manager? If yes, why kibana won't show me?

Thanks,
Fabio

**Comment by JuanjiJG** [comment] 2018-04-19 12:39
Hello @ruzzetto,

I'm not totally sure what you mean. The problem is that you're not seeing alerts on the Wazuh app? (for example, on the Overview or Discover tabs)

If that's the case, please paste here the output of this command:
```bash
lsof /var/ossec/logs/alerts/alerts.json
```

Also, make sure to **select a proper time range** on the upper right corner of the app on the Overview or Discover tabs (for example, `Last 24 hours`).

Another question: Are you seeing alerts on the Kibana Discover tab? (located on the left sidebar, right below the Kibana logo)

Thanks and regards,
Juanjo

**Comment by ruzzetto** [comment] 2018-04-19 13:00
Hey Juanjo probably my question is made due to my inexperience with ELK in general :)
Anyway, I meant basically about stream of events, no focus on alerts. Just searching incoming events firstly.
That's the output:
```
COMMAND    PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
ossec-ana 1391 ossec   10w   REG  253,3  1918475 50332923 /var/ossec/logs/alerts/alerts.json
```

On kibana discover tab I only see two indexes: wazuh-alerts-3-x.* and wazuh-monitoring-3.x.*

Thanks a lot
Fabio

**Comment by JuanjiJG** [comment] 2018-04-19 13:44
Hello again @ruzzetto,

`wazuh-alerts-3.x-*` and `wazuh-monitoring-3.x-*` are index patterns. They are used to collect a bunch of indexes who follows the same name structure (all the indices starting with `wazuh-alerts-3.x-...`).

On the Discover tab, you can choose between different index patterns, and see the content of the indices on the central section. In the case of Wazuh, you'll see the content of the `alerts.json` file when you choose the `wazuh-alerts` index pattern.

You can see this screenshot for more info:
![discover](https://user-images.githubusercontent.com/10928321/38994412-9be28088-43e6-11e8-95c6-1cb1e53c2f56.png)

According to your output, Logstash is not reading the `alerts.json` file. This is the case you're not seeing alerts on Kibana. If Logstash is not capable of reading the `alerts.json` file, it won't be able to send the content to Elasticsearch, so there won't be indices with the read data.

You can follow the steps from [our documentation](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html) to add Logstash to the OSSEC group.

```
systemctl stop logstash
curl -so /etc/logstash/conf.d/01-wazuh.conf https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/logstash/01-wazuh-local.conf
usermod -a -G ossec logstash
systemctl start logstash
```

Now you should be able to see alerts on the Wazuh app.

If you have more questions, don't hesitate to post a new comment.

Regards,
Juanjo

**Comment by ruzzetto** [comment] 2018-04-19 14:57
ok, apologize but my ELK knowledge is not so good :) I'm going to have a deep learning. Anyway I created a new index under discover as wazuz-monitoring-DATE and i see a lot of events from machines where the agent is installed. But I cannot see events under wazuh app 
thanks

**Comment by JuanjiJG** [comment] 2018-04-22 12:02
Hello again @ruzzetto,

The Wazuh app uses the `wazuh-alerts-3.x-*` index pattern to show data on the visualizations. The `wazuh-monitoring-3.x-*` index pattern is only used for just one visualization (located on the *Overview -> General* tab).

You need indices with the `wazuh-alerts-3.x-*` format to see alerts on the app.

I hope this information helps you clarify your doubts. In any case, don't hesitate to post a new comment if you still have questions.

Thanks and regards,
Juanjo

**Comment by ruzzetto** [comment] 2018-04-23 07:26
@JuanjiJG thanks, I understood the basic ELK functioning. I removed that indexes and created again with the same name, and events appeared. Now I'm waiting for new wazuh app compatible with ELK 6.2.4.

Thanks guys! I really appreciated and appreciate your kindly way to help who (like me) is an ELK newbie.

Fabio

**Comment by JuanjiJG** [comment] 2018-04-23 07:37
We're always glad to help @ruzzetto!

Any time you have a question about Wazuh, you can create a new issue and we'll try to help you as much as we can.

Since you have solved the main doubt about this issue, I'll proceed to close it. 

Thanks and regards,
Juanjo

**Closed by JuanjiJG** 2018-04-23 07:37 UTC
Labels: bug, wazuh app
