### ISSUE TITLE
Fix random failures in ciscat api integration tests.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#6868] opened 2020-12-11 09:38 UTC
|Wazuh version|Component|
|---|---|
| master | API tavern tests |

## Description
Hi team!

Currently, ciscat related tests (`test_ciscat_endpoints.tavern.yaml`, `test_rbac_black_ciscat_endpoints.tavern.yaml`, `test_rbac_white_ciscat_endpoints.tavern.yaml`) fail randomly due to multiple factors. Some of them are the following:
- Sometimes some agents never show a log that the ciscat scan has completed. The master doesn't go `healthy` until all agents have finished it.
- Although the information of agents 9 and 10 is inserted so that they look like `disconnected`, sometimes that information is not applied or is overwritten. It only happens in tests related to ciscat.

It is necessary to investigate the reasons and solutions, and determine if everything fails in the framework or there are also problems in the core.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards!
Selu

**Comment by mcarmona99** [comment] 2020-12-23 10:23
Experimental related tests (`test_experimental_endpoints.tavern.yaml`, `test_rbac_black_experimental_endpoints.tavern.yaml`, and `test_rbac_white_experimental_endpoints.tavern.yaml`) fail randomly due to things similar to  the ones listed in this issue.

In this PR https://github.com/wazuh/wazuh/pull/6936 I have fixed a race condition that made the ciscat tests fail sometimes. 

Another problems is that sometimes, some agents never go healthy and the healthcheck gives a timeout, making the whole test give an error. This is caused by the following:

While the tests are running, these kind of logs appear in `ossec.log`:

```
2020/12/22 16:37:09 wazuh-modulesd:ciscat: INFO: Module started.
2020/12/22 16:37:09 wazuh-modulesd:ciscat: INFO: Starting evaluation.
```

The healthcheck will return healthy when this evaluation (and the syscollector evaluation) has finished. As I said before, some agents never go healthy. These agents never go healthy because the ciscat evaluation never finishes.

I have seen that when you restart the agent while runnning the test, the wazuh-modulesd daemon is also restarted. When restarting the daemon, the ciscat evaluation starts again and finishes.

The provisional solution has been killing the wazuh-modulesd proccess and starting it again after x seconds without a message with the end of the evaluation.

```
2020/12/22 16:39:39 wazuh-modulesd:ciscat: INFO: Module started.
2020/12/22 16:39:39 wazuh-modulesd:ciscat: INFO: Starting evaluation.
2020/12/22 16:42:02 wazuh-modulesd:ciscat: INFO: Scan finished successfully. File: /var/ossec/wodles/ciscat/benchmarks/CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0-xccdf.xml
2020/12/22 16:42:05 wazuh-modulesd:ciscat: INFO: Evaluation finished.
```


This is also happenning in the ciscat related tests but with less frequency, due to the fact that the experimental tests are also testing syscollector and the wazuh-modulesd charge is higher. (In ciscat related tests, every agent is healthy after 6 minutes, whereas in experimental, they are healthy after 7-8 minutes.) 

Regards,
Manuel.

**Comment by mcarmona99** [comment] 2020-12-23 12:26
## Issue Status

I have been investigating the ciscat and experimental API integration tests and both return errors sometimes. These errors happens because some agents don't go healthy because the ciscat scans never finish. 

In these logs (from an unsuccessful test) we can see that the `wazuh-modulesd` starts the ciscat evaluation and after some time the evaluation finishes (log per agent):

[ossec1.log](https://github.com/wazuh/wazuh/files/5735093/ossec1.log)
[ossec2.log](https://github.com/wazuh/wazuh/files/5735095/ossec2.log)
[ossec3.log](https://github.com/wazuh/wazuh/files/5735096/ossec3.log)
[ossec4.log](https://github.com/wazuh/wazuh/files/5735097/ossec4.log)
[ossec5.log](https://github.com/wazuh/wazuh/files/5735098/ossec5.log)
[ossec6.log](https://github.com/wazuh/wazuh/files/5735099/ossec6.log)
[ossec7.log](https://github.com/wazuh/wazuh/files/5735100/ossec7.log)
[ossec8.log](https://github.com/wazuh/wazuh/files/5735101/ossec8.log)


In the logs we can see the ciscat scan has started and after a lot of time the ciscat scan finishes. This is unexpected because the ciscat scan isn't supposed to spend that time. Sometimes that time is higher than the `healthcheck` `timeout` and as I said before, the test fails. In this test, the agent 5 didn't finish the ciscat scan on time and there was an error because of the healthcheck timeout. In some cases the scan never finishes (even if we don't take into account the timeout). All these things may be internal `ciscat` or `wazuh-modulesd` errors, so use this issue to investigate them.

Here we can see an example. The ciscat scan took almost 5 minutes:

```
2020/12/23 12:12:29 wazuh-modulesd:ciscat: INFO: Module started.
2020/12/23 12:12:29 wazuh-modulesd:ciscat: INFO: Starting evaluation.

...

2020/12/23 12:17:06 wazuh-modulesd:ciscat: INFO: Scan finished successfully. File: /var/ossec/wodles/ciscat/benchmarks/CIS_Ubuntu_Linux_16.04_LTS_Benchmark_v1.0.0-xccdf.xml
2020/12/23 12:17:08 wazuh-modulesd:ciscat: INFO: Evaluation finished.
```



  
In the PR https://github.com/wazuh/wazuh/pull/6936 I made the investigation and I proposed provisional changes that are not going to be merged to our code (detailed in the last comment). 

I also proposed a solution for the race condition the ciscat test has (sometimes, the scan for the 8 agents is not done on time) but the real solution is changing the healthcheck as it is not correct. 

That PR will change the healthcheck for ciscat and experimental tests and will add a `wait_for_complete` for a syscollector test inside `test_experimental` that was missing.

Regards,
Manuel.

**Comment by davidjiglesias** [comment] 2021-01-26 09:50
Fixed in https://github.com/wazuh/wazuh/issues/7142

**Closed by davidjiglesias** 2021-01-26 09:50 UTC
Labels: bug, framework, qa
