### ISSUE TITLE
Make syscheck_control/syscheck_update signal to analysisd to reload databases when cleared/changed.

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#815] opened 2018-06-19 21:39 UTC
**Problem**

- When using `syscheck_control` or `syscheck_update` on the manager to clear/modify one or more syscheck databases in `/var/ossec/queue/syscheck/`, ossec-analysisd on the manager does not notice the change (reload the database/databases) until wazuh-manager is restarted.  

- This means when you clear the syscheck database of an agent just before running system updates on that computer to avoid lots of FIM noise about a planned update, that on that agent's next FIM scan you will still get a boatload of "file added" events clouding your radar if you have <alert_new_files> enabled on the manager.

**Workaround**

- Remember to restart the wazuh-manager service any time you use `syscheck_control` with options -u, -z, or -d,  or `syscheck_update` with options -a or -u.  I do not think it is widely understood that this is needed, nor do I find any documentation explaining this fact.

**Solution**

- Make syscheck_control/syscheck_update cause analysisd to reload the flat-file FIM databases any time they are cleared or changed by those tools.  If `ossec-makelists` can cause analysisd to reload CDBs, then surely `syscheck_control` and `syscheck_update` could make analysisd reload syscheck database files.  

- If for some reason this cannot or should not be done, at least make these commands inform the user that their changes will not take affect until the wazuh-manager service is restarted.

Thanks for your consideration :)
Kevin Branch

**Comment by bah07** [comment] 2019-01-08 14:49
Hi, Kevin

Sorry for the late response. From 3.7 version the `syscheck_control` and `syscheck_update` scripts became obsolete, however, this functionality is still present through API calls, so what you say still makes sense.

We will study a solution like the one you propose from the API. We will keep you informed.

Thank you very much, regards.

**Comment by branchnetconsulting** [comment] 2019-01-08 15:32
Hi Borja,

I thought I understood from a recent chat with Victor that the API calls to
update syscheck databases do not need to be followed by a manager restart
to notice the update, because everything is in database files instead of
flat files.  Please do confirm that.

Kevin

**Comment by bah07** [comment] 2019-01-08 16:48
Hi Kevin,

Is correct, the problem is that when the API modifies the database, for example by cleaning the files that are stored, Analysisd will not notice and in the next scan will appear to ADD alerts of all monitored files. 

Regards.

**Comment by branchnetconsulting** [comment] 2019-01-08 18:08
If that is the case, then we really need to get the Wazuh API service to
signal to analysisd somehow telling it to reload the relevant syscheck db
into memory when a syscheck update action is performed.
If ossec-makelists is able to make analysisd reload a CDB list then surely
somehow the API can make analysisd reload a syscheck db.

Kevin

**Comment by bah07** [comment] 2020-04-03 07:51
Hi @branchnetconsulting 

In version 3.12 how FIM generates and maintains its data has been changed.

- When starting the agent it performs a first scan, where it generates its database. The agent can be configured with the option `<database>` to create it in disk or memory. From now, the changes produced while the agent is off will not be reported.
- Once the scan is finished, the agent can start to report alerts in who-data or real-time mode.
- Besides, the synchronization process starts. This process keeping the states of the monitored files in the agent updated in the manager database. You can consult a list of the inventory of the monitored files from the Kibana app.
- It is not necessary to delete the agent DB since it is not persistent, it is deleted after restarting the agent.
- The manager will update the content of the agent databases in the next synchronization attempt.

I proceed to close the issue since the synchronization method implemented in this release solves the problem.

Thank you very much, Kevin, for reporting.
Regards.

**Closed by bah07** 2020-04-03 07:51 UTC
Labels: core/fim
