### ISSUE TITLE
Bug with log forward to SIEM(QRadar)

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#3421] opened 2019-05-29 15:11 UTC
Wazuh version 3.9.0 on CentOS 7.6

Hi,
I have a issue, in ossec.conf à put <syslog_output> for forward logs to SIEM. It's work but the logs take around 1 hour to be display into QRadar and it is so long. Why ? Where I can solve that please

**Comment by Lopuiz** [comment] 2019-06-04 12:14
Hi @John33000, 

Wazuh shouldn't have this behavior. Alerts are sent instantly.
Could you check that it is not a QRadar problem by configuring Rsyslog server.
Also, Could you give us your Wazuh and QRadar settings to replicate your case?

Regards, Eva

**Comment by John33000** [comment] 2019-06-04 15:38
Hello Eva,
I resolve the issue,
But I have a other problem.
I update wazuh and I lost plugin Wazuh in web interface so I do this :

/usr/share/kibana/bin/kibana-plugin remove wazuh
rm -rf /usr/share/kibana/optimize/bundles
chown -R kibana:kibana /usr/share/kibana/optimize
chown -R kibana:kibana /usr/share/kibana/plugins
then :  /usr/share/kibana/bin/kibana-plugin install
https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_6.8.0.zip
The installation was successful
And service kibana restart

I doing this manipulation with service kibana started

But nothing in web interface no "wazuh"

Can you help me please

Best regards


Le mar. 4 juin 2019 à 14:14, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by Lopuiz** [comment] 2019-06-05 07:12
Hello @John33000, 

You may not have the right version of Kibana for Wazuh App.
You can follow this [link](https://github.com/wazuh/wazuh-kibana-app#older-packages) to more information about versions.
If the problem is not resolved lets us know.

Regards, Eva

**Comment by John33000** [comment] 2019-06-05 07:30
Hi Eva
At the beginning  I install this version :  /usr/share/kibana/bin/kibana-plugin
install https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.0.zip
But at the end of installation I had a error who say : You plugin is not
compatible with version Kibana 6.8.0 plugin not installed. So I install
this plugin :  /usr/share/kibana/bin/kibana-plugin install
https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_6.8.0.zip

Who is compatible with Kibana 6.8.0 the installation was success but in web
interface they are not Wazuh plugin, how I can verify the version of Kibana
and the Wazuh ?

Le mer. 5 juin 2019 à 09:12, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by John33000** [comment] 2019-06-05 08:11
I found, sorry, I have Wazuh version : 3.9.1 and Kibana version : 6.8.0
it's good no ?

**Comment by Lopuiz** [comment] 2019-06-05 10:07
Hi @John33000, 

yes, it must works

Regards, Eva

**Comment by John33000** [comment] 2019-06-05 12:25
Yes it's good thanks, I reinstall the plugin .

It's possible to generate report PDF automatically evey week or month for
Wazuh=>Security Event and send this report by mail ? I saw the report PDF
and he's good but I don't found the option for send it by mail every week.

Le mer. 5 juin 2019 à 12:07, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by Lopuiz** [comment] 2019-06-06 06:39
Hello @John33000, 

At the moment isn't possible to do this.
This functionality has already been requested by other users, we will try to implement it in the next releases.

The issue [Automatic reports in the UI](https://github.com/wazuh/wazuh-kibana-app/issues/1492) describes the enhancement.

Regards, Eva

**Comment by John33000** [comment] 2019-06-06 07:25
Hi Eva,
No problem thank you, I update Logstash, Kibana and Elasticsearch to
version 7.1.1 but now.. In Kibana interface they are not any log in
Security Event.. I check elasticsearch.yml, Kibana.yml and startup.options
of Logstash and nothing has changed. The collect of logs works but we see
nothing in Kibana after update.

Best Regards

Le jeu. 6 juin 2019 à 08:40, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by Lopuiz** [comment] 2019-06-06 09:55
Hello @John33000,

I think your Wazuh App version is 3.9.1_6.8.0.
If you update Kibana to 7.1.1 you should install Wazuh App https://packages.wazuh.com/wazuhapp/wazuhapp-3.9.1_7.1.1.zip
Do you have the version 3.9.1_7.1.1 installed?

Regards

**Comment by Lopuiz** [comment] 2019-06-06 10:02
@John33000
 
Reading your second [issue](https://github.com/wazuh/wazuh/issues/3476) I understand that you already have Wazuh App 3.9.1_7.1.1 installed. And you view the Wazuh plugin.
The manager works because you get the alerts in IBM QRadar.
I'm right?

**Comment by John33000** [comment] 2019-06-06 10:03
Yes,
 cat /usr/share/kibana/plugins/wazuh/package.json | grep version
  "version": "3.9.1",
    "version": "7.1.1"

Le jeu. 6 juin 2019 à 11:55, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by Lopuiz** [comment] 2019-06-06 10:22
Hi @John33000, 

My workmate will help you with your doubts about Kibana. Here's the [issue](https://github.com/wazuh/wazuh-kibana-app/issues/1514).
He knows more about Kibana than I do.
I hope I can help you on another occasion.

Kind regards, Eva

**Comment by John33000** [comment] 2019-06-06 10:24
Okey, thank you .

Best regards


Le jeu. 6 juin 2019 à 12:22, Eva López Ruiz <notifications@github.com> a
écrit :

**Comment by Lopuiz** [comment] 2019-06-07 08:53
Hello @John33000,

I hope your queries about QRadar have already been answered.
I will close this issue
If you have further questions, you can reopen this issue or open a new one.

Kind regards, Eva

**Closed by Lopuiz** 2019-06-07 08:53 UTC
Labels: question
