### ISSUE TITLE
No log files being monitored in macOS agents by default

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#15579] opened 2022-12-02 16:37 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.4-Alpha1 | Agent | Packages/Sources | macO |

## Description

If we compare the files/logs being monitored by default in the `ossec.conf` of different OS agents, there is a big difference between macOS and the rest. For example, while in CentOS agents all of this is included by default:
```XML
  ...
  <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>
</ossec_config>

<ossec_config>
  <localfile>
    <log_format>audit</log_format>
    <location>/var/log/audit/audit.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/ossec/logs/active-responses.log</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/messages</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/secure</location>
  </localfile>
  <localfile>
    <log_format>syslog</log_format>
    <location>/var/log/maillog</location>
  </localfile>
</ossec_config>
```

These are the files monitored by default in macOS (none):
```XML
  ...
  <!-- Choose between "plain", "json", or "plain,json" for the format of internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>

</ossec_config>
```

Although macOS agents can be extremely noisy due to their logging system (ULS), it can be confusing that certain basic actions such as erroneous login attempts are alerted by default in some agents and not in others. Would it make sense to include monitoring of certain basic logs (PAM, SSH, etc) in macOS agents by default? Or maybe include a note in the documentation for macOS agents' installation?

Related to this issue:
- https://github.com/wazuh/wazuh-documentation/issues/5795

**Comment by davidjiglesias** [comment] 2022-12-12 12:14
Duplicate of https://github.com/wazuh/wazuh/issues/13064

**Closed by davidjiglesias** 2022-12-12 12:14 UTC
Labels: type/enhancement/feature, team/core
