### ISSUE TITLE
`like as` operator doesn't work with the `id` field in `GET /agents` as expected

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#16905] opened 2023-04-28 09:49 UTC
|Wazuh version|Component|
|---|---|
|4.5 | Wazuh component |

## Description

Using the `like as` operator of the `q` query parameter in the `GET /agents` endpoint with a substring as value, doesn't retrieve the expected results.

Example:

```
GET /agents
```

```json
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "x86_64",
          "codename": "Bionic Beaver",
          "major": "18",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |ubuntu18 |4.15.0-209-generic |#220-Ubuntu SMP Tue Mar 21 17:52:18 UTC 2023 |x86_64",
          "version": "18.04.6 LTS"
        },
        "group_config_status": "synced",
        "name": "ubuntu18",
        "status": "active",
        "ip": "127.0.0.1",
        "id": "000",
        "dateAdd": "2023-04-25T10:46:01+00:00",
        "version": "Wazuh v4.5.0",
        "registerIP": "127.0.0.1",
        "manager": "ubuntu18",
        "node_name": "node01",
        "lastKeepAlive": "9999-12-31T23:59:59+00:00"
      },
      {
        "group_config_status": "not synced",
        "name": "NewAgent",
        "status": "never_connected",
        "ip": "any",
        "id": "001",
        "dateAdd": "2023-04-25T10:52:49+00:00",
        "registerIP": "any",
        "node_name": "unknown"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "Focal Fossa",
          "major": "20",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |7d0d827cd0f4 |5.15.94-1-MANJARO |#1 SMP PREEMPT Tue Feb 14 19:45:58 UTC 2023 |x86_64",
          "version": "20.04.5 LTS"
        },
        "group_config_status": "synced",
        "name": "7d0d827cd0f4",
        "status": "disconnected",
        "ip": "172.17.0.2",
        "disconnection_time": "2023-04-28T05:48:58+00:00",
        "id": "002",
        "dateAdd": "2023-04-27T11:05:57+00:00",
        "version": "Wazuh v4.4.1",
        "registerIP": "any",
        "manager": "ubuntu18",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
        "node_name": "node01",
        "lastKeepAlive": "2023-04-27T15:38:29+00:00",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "group": [
          "default"
        ]
      }
    ],
    "total_affected_items": 3,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

If I try to use the `like as` operator of `q` query parameter for the `id` field and `00` value, I would expect to get the agents whose `id` includes the `00` value, but I get no agents instead.

```
GET /agents?q=id~00
```

Response:
```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No agent information was returned",
  "error": 0
}
```

Using a exact ID, such as `002`, it doesn't return the expected results:

```
GET /agents?q=id~001
```

```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No agent information was returned",
  "error": 0
}
```

I don't know if this behavior could be happening with other fields or endpoints. Maybe you could be interested to extend the research of this case.

This was detected in the development of the new search bar: https://github.com/wazuh/wazuh-kibana-app/issues/4312. This causes the WQL search mode of the search bar doesn't get the expected results when the input is `00` and the user expects at least the agents whose ID contains that string to be returned.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [ ] Tests (unit tests, API integration tests).
- [ ] Changelog.
- [ ] Documentation.
- [ ] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by Selutario** [comment] 2023-08-08 11:51
Closing the issue since this is a duplicate of:
- https://github.com/wazuh/wazuh/issues/18204

IDs are stored as integers in the database (`1`, `2`, `3`, etc), not as strings (`001`, `002`...), so searching for `00` will have no results. We should switch to integers and change everything (documentation, RBAC, API responses, CLIs, client.keys, etc) to fix this consistently, but is a quite big and breaking change. In any case, this would be carried out in #18204

**Closed by Selutario** 2023-08-08 11:51 UTC
Labels: type/bug, level/task, team/framework
