### ISSUE TITLE
Error in Wazuh-analysisd: 'Operation not permitted'

### ISSUE THREAD

**Issue by Gertjuh** [wazuh/wazuh#21818] opened 2024-02-08 07:06 UTC
When I check the status of the Wazuh Manager is see this error with Wazuh-analysisd. Can't find a solution.
I installed Wazuh (App version: 4.7.2 App revision: 02) in a Proxmox container on Ubuntu 22.04.

-------------------------------------------------------------------------------------------------------
feb 08 07:52:03 Wazuh env[11587]: Started wazuh-maild...
feb 08 07:52:03 Wazuh env[11753]: 2024/02/08 07:52:03 wazuh-analysisd: ERROR: Could not set resource limit for file descriptors to 458752: Operation not permitted (1)
feb 08 07:52:04 Wazuh env[11587]: Started wazuh-analysisd...

**Comment by rauldpm** [comment] 2024-02-08 14:34
Hi, @Gertjuh I am going to check your issue, let me investigate it and do some tests, in the meantime, this issue is a duplicate of this one right? https://github.com/wazuh/wazuh-documentation/issues/7014

In general, this problem is usually related to a permission issue in Proxmox, as Wazuh is unable to increase the resource limit, but I am going to check it again anyway, you can check this issue and its comments: https://github.com/wazuh/wazuh-documentation/issues/6282, or this one that mentions Proxmox with the same error: https://github.com/wazuh/wazuh/issues/11377

**Comment by rauldpm** [comment] 2024-02-22 20:56
Closed due to inactivity

**Closed by rauldpm** 2024-02-22 20:56 UTC
Labels: reporter/community

**Comment by hmoreau** [comment] 2024-09-25 20:15
See solution here : https://github.com/wazuh/wazuh/issues/11377
