### ISSUE TITLE
Windows agent crashes when FIM scans folder with a big ammount of files and sub-folders. 

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#10692] opened 2021-10-29 16:00 UTC
|Wazuh version|Component|Install type|Platform|
|---|---|---|---|
| 4.2.32 | FIM | Agent | Windows |

From the analysis of the problem reported on this community [thread ](https://groups.google.com/g/wazuh/c/dsMoeB3Dstw), it was identified that Windows Wazuh Agent crashes when FIM scans folders with a big amount of files and sub-folders.
During the scan (without recursion limit) of a folder with 128.502 sub-folders and 928.558 files, the agent crashed without an error log output.
![image](https://user-images.githubusercontent.com/11434230/139466735-d8b5e759-c797-41fb-9ff5-4c6b387b9f67.png)

The analysis of event_viewer reflect that the agent has crashed at the moment of the FIM scan:

```
Nombre de registro:Application
Origen:        Windows Error Reporting
Fecha:         21/10/2021 17:22:51
Id. del evento:1001
Categoría de la tarea:Ninguno
Nivel:         Información
Palabras clave:Clásico
Usuario:       No disponible
Equipo:        SERVERDADES.intranet.DOMAIN.com
Descripción:
Depósito con errores , tipo 0
Nombre de evento: APPCRASH
Respuesta: No disponible
Identificador de archivo CAB: 0

Firma del problema:
P1: wazuh-agent.exe
P2: 0.0.0.0
P3: 615c2757
P4: msvcrt.dll
P5: 7.0.14393.2457
P6: 5b7e2dd0
P7: c0000005
P8: 00089619
P9: 
P10: 

Archivos adjuntos:

Es posible que estos archivos estén disponibles aquí:
C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_wazuh-agent.exe_298eaaf7c8aa5c9c641b1a589aa7e00405b5ad8_31add48b_38a45243

Símbolo de análisis: 
Nueva búsqueda de una solución: 0
Identificador de informe: d82c8baf-2942-4fed-ac07-6d94b49afa95
Estado del informe: 4
Depósito con algoritmo hash: 
XML de evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-10-21T15:22:51.671369600Z" />
    <EventRecordID>490769</EventRecordID>
    <Channel>Application</Channel>
    <Computer>SERVERDADES.intranet.DOMAIN.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>APPCRASH</Data>
    <Data>No disponible</Data>
    <Data>0</Data>
    <Data>wazuh-agent.exe</Data>
    <Data>0.0.0.0</Data>
    <Data>615c2757</Data>
    <Data>msvcrt.dll</Data>
    <Data>7.0.14393.2457</Data>
    <Data>5b7e2dd0</Data>
    <Data>c0000005</Data>
    <Data>00089619</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportQueue\AppCrash_wazuh-agent.exe_298eaaf7c8aa5c9c641b1a589aa7e00405b5ad8_31add48b_38a45243</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>d82c8baf-2942-4fed-ac07-6d94b49afa95</Data>
    <Data>4</Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

[FIM_crash.zip](https://github.com/wazuh/wazuh/files/7443296/FIM_crash.zip)

**Comment by jotacarma90** [comment] 2022-05-04 15:34
## Research
Hi team, I have been working on trying to reproduce this issue. I have not been able to get to the mentioned crash.
My tests have been on a **Windows 7** machine. With the **same configuration** as reported by the user.
The FIM scan **finished correctly** after having created a million files.

I also tried to modify all the files and I was also testing on a machine without enough disk space, in case it could be related to lack of resources (in the user's screenshot the monitored disk occupies almost 400 GB).
The user had commented that the error occurred in all 3 FIM modes. 

Without knowing more details of the environment it is difficult to conclude the reasons for the error. We are waiting for further information on the subject.

New message in the thread:
https://groups.google.com/g/wazuh/c/dsMoeB3Dstw/m/HOW5Q4DDAQAJ

**Comment by vikman90** [comment] 2022-08-10 09:47
Closing this issue as we could not manage to reproduce it.

**Closed by vikman90** 2022-08-10 09:47 UTC
Labels: type/bug, module/fim, platform/windows, reporter/community, type/bug/crash
