### ISSUE TITLE
Ruleset update tool does not work in Ubuntu 18.04

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#579] opened 2018-04-30 05:40 UTC
If we run the ruleset update tool (based on Python 2) on Ubuntu 18.04 this error appears:
```sh
# /var/ossec/bin/update_ruleset
### Wazuh ruleset ###
ERROR: 	URL Error - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726): https://github.com/wazuh/wazuh-ruleset/archive/stable.zip
```

However if we force to use Python 3, this issue appears instead:
```sh
# python3 /var/ossec/bin/update_ruleset
### Wazuh ruleset ###
ERROR: Unknown: name 'HTTPError' is not defined.
Exiting.
```

**Comment by mgmacias95** [comment] 2018-05-07 06:50
Hello @vikman90,

The first error is an OpenSSL error, caused by #583. The second one has been fixed in https://github.com/wazuh/wazuh/commit/5f002a4d5e5b908df2d8ae0f67ead140f15ad43c. Thank you so much for reporting.

Best regards,
Marta

**Closed by mgmacias95** 2018-05-07 06:50 UTC
Labels: bug
