### ISSUE TITLE
The email_alerts configuration causes the ossec-maild process to exit abnormally

### ISSUE THREAD

**Issue by justinoy** [wazuh/wazuh#5758] opened 2020-08-18 11:18 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|3.13.0,3.13.1|wazuh-manager|yum|yum|Amazon Linux 2|

ossec.conf email-alert 
---
```
  <email_alerts>
    <email_to>example@exampleabc.com</email_to>
    <rule_id>52502,10498</rule_id>
  </email_alerts>

<global>
  <email_maxperhour>1000000</email_maxperhour>
</global>
```

error message:
Aug 18 11:05:36 ip-192-168-1-250 kernel: ossec-maild[15470]: segfault at 18 ip 0000000000409079 sp 00007fff5f8110a0 error 4 in ossec-maild[400000+e3000]

This problem no longer occurs after I commented out the configuration of email_alerts

**Comment by Molter73** [comment] 2020-08-18 12:09
Hi @justinoy,

I'm looking into this issue but I am having some trouble attempting to reproduce it. Could you share with us the full contents of your manager's configuration file? Feel free to modify/censor any sensitive data such as URLs and public IPs.

It would also be very useful if you could run `maild` in debug mode, so we can have a better understanding of what is going on. In order to do this, you would have to kill the process (not necessary if it has just segfaulted) and then run it with `-fdd` cli options, it would look something like this:

```
root@server:/var/ossec# pkill ossec-maild
root@server:/var/ossec# cd /var/ossec/bin
root@server:/var/ossec/bin# ./ossec-maild -fdd
2020/08/18 12:04:41 ossec-maild[5841] debug_op.c:69 at _log(): DEBUG: Logging module auto-initialized
2020/08/18 12:04:41 ossec-maild[5841] maild.c:113 at main(): DEBUG: Starting ...
...
```

These last commands assume that you have your manager installed under `/var/ossec`. Again, if sensitive information is output to the console, feel free to modify/censor it.

**Comment by justinoy** [comment] 2020-08-19 04:16
FYI

[ossec.txt](https://github.com/wazuh/wazuh/files/5093964/ossec.txt)

**Comment by justinoy** [comment] 2020-08-19 08:23
./ossec-maild -fdd
`
2020/08/19 08:22:21 ossec-maild[14109] debug_op.c:69 at _log(): DEBUG: Logging module auto-initialized
2020/08/19 08:22:21 ossec-maild[14109] maild.c:113 at main(): DEBUG: Starting ...
2020/08/19 08:22:21 ossec-maild[14109] email-alerts-config.c:125 at Read_EmailAlerts(): DEBUG: Adding '52502' to granular e-mail
2020/08/19 08:22:21 ossec-maild[14109] email-alerts-config.c:125 at Read_EmailAlerts(): DEBUG: Adding '10498' to granular e-mail
2020/08/19 08:22:21 ossec-maild[14109] maild.c:190 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: ossecm
2020/08/19 08:22:21 ossec-maild[14109] maild.c:198 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: ossecm
2020/08/19 08:22:21 ossec-maild[14109] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2020/08/19 08:22:21 ossec-maild[14109] mailcom.c:106 at mailcom_main(): DEBUG: Local requests thread ready
2020/08/19 08:22:21 ossec-maild[14109] maild.c:212 at main(): INFO: Started (pid: 14109).
2020/08/19 08:22:21 ossec-maild[14109] maild.c:254 at OS_Run(): INFO: Getting alerts in JSON format.
`
There seems to be no problem running this alone.

**Comment by justinoy** [comment] 2020-08-24 10:37
@Molter73  Any update?

**Comment by Molter73** [comment] 2020-08-25 07:14
Hi @justinoy 

I have not been able to reproduce this behaviour. Are you using different users when restarting with systemctl and running the process in debug? It could be possible that maild is attempting an operation which is not permitted with the user that runs systemctl but is allowed when running the daemon directly (I'm guessing you used a root user for this last one). Have you by any chance modified access or ownership of any files inside your installation? Here are the permissions and ownership of the file I consider relevant in my server:

```
[root@amazon vagrant]# ls -la /var/ossec/bin/ossec-maild
-rwxr-x---  1 root root  1052123 Jul 13 18:42 ossec-maild
```

```
[root@amazon vagrant]# ls -la /etc/init.d/wazuh-manager
-rwxr-xr-x 1 root ossec 1242 Jul 13 18:43 /etc/init.d/wazuh-manager
```

```
[root@amazon vagrant]# ls -la /var/ossec/etc/
total 48
drwxrwx---  7 ossec ossec   265 Aug 25 07:02 .
drwxr-x--- 18 root  ossec   231 Aug 19 12:07 ..
-rw-r-----  1 root  ossec     0 Aug 25 07:02 client.keys
drwxrwx---  2 root  ossec    31 Aug 19 12:06 decoders
-rw-r-----  1 root  ossec 13535 Jul 13 18:42 internal_options.conf
drwxrwx---  3 root  ossec   122 Aug 19 12:06 lists
-rw-r-----  1 root  ossec   320 Jul 13 18:42 local_internal_options.conf
-rw-r-----  1 root  ossec   127 Aug 29  2019 localtime
-rw-rw----  1 root  ossec 10206 Aug 19 13:40 ossec.conf
lrwxrwxrwx  1 root  ossec    20 Aug 19 12:06 ossec-init.conf -> /etc/ossec-init.conf
drwxrwx---  2 root  ossec  4096 Aug 19 12:06 rootcheck
drwxrwx---  2 root  ossec    29 Aug 19 12:06 rules
drwxrwx---  3 root  ossec    63 Aug 19 12:07 shared
-rw-r-----  1 root  root   1176 Aug 19 12:07 sslmanager.cert
-rw-r-----  1 root  root   1704 Aug 19 12:07 sslmanager.key
```

Could you check they are the same in your server?

**Comment by justinoy** [comment] 2020-08-26 07:37
Hi @Molter73 , All files owner and permission are the same.

I have tried to use ./ossec-maild -fdd run again.  I got this ->
`
[root@ip-1xx bin]# ./ossec-maild -fdd
2020/08/26 07:25:44 ossec-maild[28620] debug_op.c:69 at _log(): DEBUG: Logging module auto-initialized
2020/08/26 07:25:44 ossec-maild[28620] maild.c:113 at main(): DEBUG: Starting ...
2020/08/26 07:25:44 ossec-maild[28620] email-alerts-config.c:125 at Read_EmailAlerts(): DEBUG: Adding '52502' to granular e-mail
2020/08/26 07:25:44 ossec-maild[28620] email-alerts-config.c:125 at Read_EmailAlerts(): DEBUG: Adding '10498' to granular e-mail
2020/08/26 07:25:44 ossec-maild[28620] maild.c:190 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: ossecm
2020/08/26 07:25:44 ossec-maild[28620] maild.c:198 at main(): DEBUG: Chrooted to directory: /var/ossec, using user: ossecm
2020/08/26 07:25:44 ossec-maild[28620] pthreads_op.c:45 at CreateThreadJoinable(): DEBUG: Thread stack size set to: 8192 KiB
2020/08/26 07:25:44 ossec-maild[28620] mailcom.c:106 at mailcom_main(): DEBUG: Local requests thread ready
2020/08/26 07:25:44 ossec-maild[28620] maild.c:212 at main(): INFO: Started (pid: 28620).
2020/08/26 07:25:44 ossec-maild[28620] maild.c:254 at OS_Run(): INFO: Getting alerts in JSON format.
2020/08/26 07:26:34 ossec-maild[28620] os_maild_client.c:575 at OS_RecvMailQ_JSON(): DEBUG: OS_RecvMailQ: mail->body[
Wazuh Notification.
2020-08-26T07:26:33.909+0000

Received From: (ip-1xx) xx->ossec-agent
Rule: 202 fired (level 7) -> "Agent event queue is 90% full."
Portion of the log(s):

wazuh: Agent buffer: '90%'.


 --END OF NOTIFICATION


]
Segmentation fault
`

"Segmentation fault" , It's look like "ossec-maild" process attempts to access memory it has either not been assigned by the operating system, or is otherwise not allowed to access (https://stackoverflow.com/questions/3200526/what-is-a-segmentation-fault-on-linux)

**Comment by justinoy** [comment] 2020-08-28 06:12
Finally, when i removed email_alert_level from <alerts>. “ossec-maild” works normal again.

**Comment by Molter73** [comment] 2020-08-28 11:21
I've managed to reproduce the error but haven't been able to pin-point the cause just yet.

Seems like a race condition is causing the buffer read from `alerts.json` to be wrong but still "good enough" for cJSON to parse it, unfortunately some fields get their type changed and cause a segfault when we attempt to access the wrong cJSON object's field.

I will continue posting updates as I get closer to narrowing the problem.

**Comment by mjcr99** [comment] 2023-02-16 17:14
Hi team,

I have been reviewing this issue and I have not been able to reproduce it, I do not know if it may have been fixed at some moment since I have been trying to reproduce the reported behavior using Wazuh 4.3.10, in Amazon Linux 2 and using the suggested config which is causing this problem as it is reported by the user, but I have not got success reproducing it.

I have been having a look at the rules that trigger the mail sent, and I have found that the 10498 one is not in the default ruleset. So it may be, by any chance, related to this problem, but still, further investigation is needed.

**Comment by chemamartinez** [comment] 2023-03-23 10:07
Hi @justinoy,

Unfortunately, we were not able to replicate this issue. Since we are talking about a considerably old version (3.13) we are closing this issue. I suggest you upgrade your manager to the latest Wazuh version, currently 4.3.10, and re-open this issue if this crash appears again.

We are sorry for the inconvenience, and thank you for your feedback!

**Closed by chemamartinez** 2023-03-23 10:07 UTC
Labels: type/bug, module/mail, reporter/community, type/bug/crash, level/task
