### ISSUE TITLE
sts_endpoint option not working with cloudwatchlogs

### ISSUE THREAD

**Issue by inai-shreyas** [wazuh/wazuh#14206] opened 2022-07-11 13:31 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.3.5 | Wodle | Manager| Packages/Sources | OS version |

Hi I'm using the aws-s3 wodle to fetch logs from cloudwatch logs. We have to disabled internet access to the wazuh instance and so decided to use vpc endpoint feature. The instance needs to fetch logs from another account, it is done by assuming the role in the other account. We have used the following configuration, but it always tries to contact the global endpoint instead of the endpoint that we configured. am I doing something wrong here?
```
<service type="cloudwatchlogs">
      <sts_endpoint>https://sts.us-east-2.amazonaws.com</sts_endpoint>
      <service_endpoint>https://logs.us-east-2.amazonaws.com</service_endpoint>
      <aws_log_groups>LOG GROUP</aws_log_groups>
      <iam_role_arn>arn:aws:iam::_<account_id>_:role/_<role_arn>_</iam_role_arn>
      <regions>us-east-2</regions>
```

**Comment by FrancoRivero** [comment] 2022-07-12 14:59
Hi @inai-shreyas, I don't know what you mean, I can share you the [AWS FIPS documentation](https://documentation.wazuh.com/current/amazon/services/prerequisites/considerations.html?highlight=fips#fips-endpoints).
Regarding the error in the module, can you share the logs with me? If you can share me, I would need the logs in `debug=2`. 
To set modulesd to `debug=2`, you must change `internal_options.conf` in the `modulesd.debug` line from 0 to 2.
Regards

**Comment by inai-shreyas** [comment] 2022-07-21 09:06
@davidjiglesias @Selutario would you be able to help here?

we are stuck with this.

**Comment by CarlosRS9** [comment] 2022-07-21 10:05
Hi @inai-shreyas

Sorry for the delay. Let me try to help you with this issue.

If first place, yes, you were right. You don't need to specifically use FIPS endpoints for this. VPC Endpoints are the way to go in this case.

To be able to help you I need to know more about your AWS environment. Please confirm me if what you have configured corresponds to the steps I am about to describe or if you have done something different:

1. You created a private subnet in your VPC for a given region.
2. You deployed an EC2 instance in that private subnet and installed Wazuh on it.


In addition to that, please make sure and confirm us you meet the following prerequisites:
 
1. It seems you are using private DNS for these endpoints. If that's the case you must enable DNS hostnames and DNS resolution for your VPC. Check [this link](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating) to learn more about this topic.

2. The security group for the interface endpoint must allow communication between the endpoint network interface and the resources in your VPC that must communicate with the service.

3. If your resources are in a subnet with a network ACL, verify that the network ACL allows traffic between the endpoint network interfaces and the resources in the VPC.

4. AWS STS is activated for the AWS Region. Follow [this link](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-activate-deactivate) to learn more about this topic.


Assuming those are the steps you followed and the prerequisites are met, let's continue.

It seems the issue is with the STS endpoint. It looks like the calls are being redirected to the global STS endpoint instead of your regional one.

 
I suggest you use the AWS CLI to confirm if everything it's ok on the AWS side to see if this is an AWS or Wazuh configuration issue. Check [this link](https://docs.aws.amazon.com/vpc/latest/privatelink/create-interface-endpoint.html#test-interface-endpoint-aws) to learn about how to test the VPC endpoints using the AWS CLI.

**Comment by inai-shreyas** [comment] 2022-07-21 10:30
@carlocas Yes, everything is configured correctly. I'm able to run the following command and get the response correctly.

```
aws sts assume-role --role-arn arn:aws:iam::<account_id>:role/<role_name> --role-session-name test --region=us-east-2
```
I've even set `AWS_STS_REGIONAL_ENDPOINTS` env to `regional` at system level.

**Comment by inai-shreyas** [comment] 2022-07-21 10:33
I've also tried creating a default profile with `sts_regional_endpoints=regional` for both wazuh and wazuh-indexer users. 
under
`/var/ossec` and `/usr/share/wazuh-indexer`

**Comment by CarlosRS9** [comment] 2022-07-21 12:03
I'm trying to replicate this issue but it is working in my environment just fine. It is using the regional STS endpoint without issues.

Could you please try to run the module manually and share with us the output replacing any sensitive information? Try using the following command, adding the corresponding value for your iam role:

```
/var/ossec/wodles/aws/aws-s3 -sr cloudwatchlogs -r us-east-2 -g /aws/rds/instance/inai-prod-1/audit -st https://sts.us-east-2.amazonaws.com -se https://logs.us-east-2.amazonaws.com -i YOUR IAM ROLE -d 3

```

With this information I may be able to help you further.

**Comment by inai-shreyas** [comment] 2022-07-21 12:33
@CarlosRS9 I set debug level to 2, but just hangs no output, added a log after creating the client. I can see that endpoint_url was configured but, I don't see the following logs:
```
Getting data from DB for log stream
```
https://github.com/wazuh/wazuh/blob/2b63741c449ff0f397eafa607df4ceedb48a8e66/wodles/aws/aws_s3.py#L2928
which should be executed.

**Comment by inai-shreyas** [comment] 2022-07-21 12:35
Actually, it timedout again. IDK why

**Comment by inai-shreyas** [comment] 2022-07-21 12:49
I've set the AWS_DEFAULT_REGION env to work around this for now as I didn't know which user this runs as. Even though it has solved my problem, I believe this should be fixed.

**Comment by FrancoRivero** [comment] 2022-07-28 13:14
Hi @inai-shreyas,
With the changes proposed by @CarlosRS9, were you able to solve the problem?
Can I close this issue?

**Comment by FrancoRivero** [comment] 2022-08-08 12:36
Hi @inai-shreyas,
I will close the issue, if you find any other problems with this issue we will look at it again.
Regards

**Closed by FrancoRivero** 2022-08-08 12:36 UTC
Labels: module/aws, reporter/community, module/cloud monitoring
