### ISSUE TITLE
Wazuh Manager: ERROR: Error 3021 - Timeout executing API request

### ISSUE THREAD

**Issue by skhanum** [wazuh/wazuh#14682] opened 2022-08-18 11:33 UTC
Hello Team,

I am constantly seeing the ERROR: Error 3021 - Timeout executing API request when executing "./cluster_control -a" 

root@wazhuManager:/var/ossec/bin# ./cluster_control -a
ERROR: Error 3021 - Timeout executing API request

I am not finding any documentation for this. 

Please help and advise

**Comment by skhanum** [comment] 2022-08-18 11:33
Wazuh Manager version : 4.2.6

**Comment by FrancoRivero** [comment] 2022-08-18 17:08
Hi @skhanum,
Thank you for using Wazuh!
You can follow the next [guide](https://documentation.wazuh.com/4.2/user-manual/configuring-cluster/index.html#configuring-cluster) to deploy a cluster, however, I need more information about the issue to give you an answer to this question.
Can you share me your configuration, logs and other relevant information to reproduce this error.
I can see in the code the problem is when you can request information about the cluster. The problem is in this code block:
```python
def run_local(f, f_kwargs, logger, rbac_permissions, broadcasting, nodes, current_user):
        """Run framework SDK function locally in another process."""

        def debug_log(logger, message):
            if logger.name == 'wazuh-api':
                logger.debug2(message)
            else:
                logger.debug(message)

        debug_log(logger, "Starting to execute request locally")
        common.rbac.set(rbac_permissions)
        common.broadcast.set(broadcasting)
        common.cluster_nodes.set(nodes)
        common.current_user.set(current_user)
        data = f(**f_kwargs)
        common.reset_context_cache()
        debug_log(logger, "Finished executing request locally")
        return data

    async def execute_local_request(self) -> str:
        """Execute an API request locally.

        Returns
        -------
        str
            JSON response.
        """
        try:
            if self.f_kwargs.get('agent_list') == '*':
                del self.f_kwargs['agent_list']

            before = time.time()
            self.check_wazuh_status()

            timeout = self.api_request_timeout if not self.wait_for_complete else None

            # LocalClient only for control functions
            if self.local_client_arg is not None:
                lc = local_client.LocalClient()
                self.f_kwargs[self.local_client_arg] = lc
            try:
                if self.is_async:
                    task = self.run_local(self.f, self.f_kwargs, self.logger, self.rbac_permissions, self.broadcasting,
                                          self.nodes, self.current_user)

                else:
                    loop = asyncio.get_event_loop()
                    if 'thread_pool' in pools:
                        pool = pools.get('thread_pool')
                    elif self.f.__name__ in authentication_funcs:
                        pool = pools.get('authentication_pool')
                    else:
                        pool = pools.get('process_pool')

                    task = loop.run_in_executor(pool, partial(self.run_local, self.f, self.f_kwargs,
                                                              self.logger, self.rbac_permissions,
                                                              self.broadcasting, self.nodes,
                                                              self.current_user))
                try:
                    data = await asyncio.wait_for(task, timeout=timeout)
                except asyncio.TimeoutError:
                    raise exception.WazuhInternalError(3021) # <--- here is where this error is shown
                except OperationalError:
                    raise exception.WazuhInternalError(2008)
                except process.BrokenProcessPool:
                    raise exception.WazuhInternalError(901)
            except json.decoder.JSONDecodeError:
                raise exception.WazuhInternalError(3036)
            except process.BrokenProcessPool:
                raise exception.WazuhInternalError(900)

            self.debug_log(f"Time calculating request result: {time.time() - before:.3f}s")
            return data
        except (exception.WazuhError, exception.WazuhResourceNotFound) as e:
            e.dapi_errors = self.get_error_info(e)
            if self.debug:
                raise
            return json.dumps(e, cls=c_common.WazuhJSONEncoder)
        except exception.WazuhInternalError as e:
            e.dapi_errors = self.get_error_info(e)
            # Avoid exception info if it is an asyncio timeout error, JSONDecodeError or /proc availability error
            self.logger.error(f"{e.message}", exc_info=e.code not in {3021, 3036, 1913})
            if self.debug:
                raise
            return json.dumps(e, cls=c_common.WazuhJSONEncoder)
        except Exception as e:
            self.logger.error(f'Error executing API request locally: {str(e)}', exc_info=True)
            if self.debug:
                raise
            return json.dumps(exception.WazuhInternalError(1000,
                                                           dapi_errors=self.get_error_info(e)),
                              cls=c_common.WazuhJSONEncoder)
```
Regards

**Comment by skhanum** [comment] 2022-08-22 08:20
Hello @FrancoRivero 

Thanks for checking this for me

we have deployed a cluster of 3 Managers
Recently, I have been seeing seeing "Error 3021 - Timeout executing API request" whenever I happened to execute cluster control command

We have enrolled over 100 agents and this issue has recently occurred. For example, out of 5 tries, 4 tries give me this timeout error and 1 try might show up the agent status along with Wazuh Managers info

We have developed a custom dashboard to check the status of the agents that uses cluster control command, but due to this issue, we are unable to see real time data about the agent status.

**Comment by skhanum** [comment] 2022-08-24 04:44
root@wazhuManager0:~# service wazuh-manager status
● wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2022-08-08 16:59:40 UTC; 2 weeks 1 days ago
    Tasks: 97 (limit: 4069)
   CGroup: /system.slice/wazuh-manager.service
           ├─7862 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
           ├─7902 /var/ossec/bin/wazuh-authd
           ├─7920 /var/ossec/bin/wazuh-db
           ├─7943 /var/ossec/bin/wazuh-execd
           ├─7961 /var/ossec/bin/wazuh-analysisd
           ├─7974 /var/ossec/bin/wazuh-syscheckd
           ├─8011 /var/ossec/bin/wazuh-remoted
           ├─8044 /var/ossec/bin/wazuh-logcollector
           ├─8063 /var/ossec/bin/wazuh-monitord
           ├─8086 /var/ossec/bin/wazuh-modulesd
           └─8129 /var/ossec/framework/python/bin/python3 /var/ossec/framework/scripts/wazuh-clusterd.py

Aug 08 16:59:32 wazhuManager0 env[7787]: Started wazuh-analysisd...
Aug 08 16:59:32 wazhuManager0 env[7787]: 2022/08/08 16:59:32 wazuh-syscheckd: WARNING: The check_unixaudit option is deprecated in favor of the SCA module.
Aug 08 16:59:33 wazhuManager0 env[7787]: Started wazuh-syscheckd...
Aug 08 16:59:34 wazhuManager0 env[7787]: Started wazuh-remoted...
Aug 08 16:59:35 wazhuManager0 env[7787]: Started wazuh-logcollector...
Aug 08 16:59:36 wazhuManager0 env[7787]: Started wazuh-monitord...
Aug 08 16:59:38 wazhuManager0 env[7787]: Started wazuh-modulesd...
Aug 08 16:59:38 wazhuManager0 env[7787]: Started wazuh-clusterd...
Aug 08 16:59:40 wazhuManager0 env[7787]: Completed.
Aug 08 16:59:40 wazhuManager0 systemd[1]: Started Wazuh manager.



root@wazhuManager0:~# grep -E "WARN|ERR" /var/ossec/logs/ossec.log
grep: /var/ossec/logs/ossec.log: No such file or directory
root@wazhuManager0:~# cd /var/ossec/logs/
root@wazhuManager0:/var/ossec/logs#
root@wazhuManager0:/var/ossec/logs# grep -E "WARN|ERR" /var/ossec/logs/ossec.log
grep: /var/ossec/logs/ossec.log: No such file or directory
root@wazhuManager0:/var/ossec/logs# grep -E "WARN|ERR"  ossec.json
ossec.json    ossec.json-1
root@wazhuManager0:/var/ossec/logs# grep -E "WARN|ERR"  ossec.json
ossec.json    ossec.json-1
root@wazhuManager0:/var/ossec/logs# grep -E "WARN|ERR"  ossec.json
root@wazhuManager0:/var/ossec/logs#



root@wazhuManager0:/var/ossec/logs# grep -iE "error|exception|caused|daemon" /var/ossec/logs/api.log
root@wazhuManager0:/var/ossec/logs#

**Comment by FrancoRivero** [comment] 2022-08-24 13:44
Hi @skhanum,
how are you?
Unfortunately the information aren't enough to define the problem in your cluster. So could you share more information?
I'd need the logs, `ossec.log`, `api.log`, `cluster.log` after executes `cluster_control -a`.
From this information we should have a better idea of what the problem might be.

Regards

**Comment by skhanum** [comment] 2022-08-24 13:59
Hello Franco,

Sure, let me try to repro the issue and share all the relevant logs that were requested.

I will send the logs and all the required information soon.

Thanks,

Please excuse typo's

Saniya Khanum
________________________________

**Comment by FrancoRivero** [comment] 2022-08-24 16:54
Thank you @skhanum,
I will be waiting for your message with this information. 
Regards

**Comment by skhanum** [comment] 2022-08-25 06:52
Hi @FrancoRivero 

I replicated the issue and kept the requested logs

I did not see any new logs generated for api.log

root@wazhuManager0:/var/ossec/logs# tail -f api.log
2022/08/08 16:59:37 INFO: Listening on 0.0.0.0:55000..

In cluster.log file, I could see the error. But not much details are provided. Do we have a debug logging available? If yes, will it require a service restart?

2022/08/25 06:18:50 INFO: [Master] [Local integrity] Starting.
2022/08/25 06:18:50 INFO: [Master] [Local integrity] Finished in 0.006s. Calculated metadata of 177 files.
2022/08/25 06:18:50 INFO: [Worker hcs-wazuh-manager-wazhumanager2] [Agent-info sync] Finished in 12.379s (1 chunks updated).
2022/08/25 06:18:50 ERROR: [Local Server] [D API] Timeout executing API request
2022/08/25 06:18:50 INFO: [Worker hcs-wazuh-manager-wazhumanager1] [Agent-info sync] Starting
2022/08/25 06:19:03 INFO: [Master] [Local integrity] Starting.
2022/08/25 06:19:03 INFO: [Master] [Local integrity] Finished in 0.006s. Calculated metadata of 177 files.

I did not find ossec.log file under /var/ossec/logs, do we have different path for this log file?

root@wazhuManager0:/var/ossec/logs# ls
active-responses.log  api      archives  cluster.log    cluster.log.2022-08-05  firewall          ossec.json    wazuh
alerts                api.log  cluster   cluster.log-1  cluster.log.2022-08-17  integrations.log  ossec.json-1
root@wazhuManager0:/var/ossec/logs#

**Comment by FrancoRivero** [comment] 2022-08-25 15:11
Hi @skhanum,
I am reviewing the information you share with me, I see that you have something wrong with your installation because it is abnormal not to have the ossec.log in the standard installation.
Can you tell me about your custom installation?
I think your problem is a network problem because it is not normal that a synchronization of the agent information takes 12 seconds, normally it should take about 100 microseconds.
We will need more information to be able to debug the problem so if you can help me with that I need to know some information about the network, could you execute those commands:

1. Make a ping from manager to some worker
2. iperf -c <master_host> from a worker
3. iperf -s

Sorry for not being of more help
Regards

**Comment by skhanum** [comment] 2022-08-26 08:11
Hello @FrancoRivero 

I really appreciate your help to identify the issue. 

Here is the requested information

1. Make a ping from manager to some worker

root@wazhuManager0:/var/ossec/bin# ping 10.0.2.5
PING 10.0.2.5 (10.0.2.5) 56(84) bytes of data.
64 bytes from 10.0.2.5: icmp_seq=1 ttl=64 time=0.820 ms
64 bytes from 10.0.2.5: icmp_seq=2 ttl=64 time=1.59 ms
64 bytes from 10.0.2.5: icmp_seq=3 ttl=64 time=0.665 ms
64 bytes from 10.0.2.5: icmp_seq=4 ttl=64 time=1.00 ms
64 bytes from 10.0.2.5: icmp_seq=5 ttl=64 time=0.859 ms
64 bytes from 10.0.2.5: icmp_seq=6 ttl=64 time=0.975 ms
64 bytes from 10.0.2.5: icmp_seq=7 ttl=64 time=0.955 ms
^C
--- 10.0.2.5 ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6045ms
rtt min/avg/max/mdev = 0.665/0.981/1.590/0.273 ms

2. iperf -c <master_host> from a worker

root@wazhuManager2:~# iperf -c 10.0.2.4
connect failed: Connection refused
root@wazhuManager2:~#

3. iperf -s  ( From Master node)

root@wazhuManager0:/var/ossec/bin# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------

iperf -s  (From Worker Node)

root@wazhuManager2:~# iperf -s
------------------------------------------------------------
Server listening on TCP port 5001
TCP window size:  128 KByte (default)
------------------------------------------------------------

There were not much of custom installation that I am aware of. This was working as expected before but started to timeout as and when we started enrolling agents. Currently, there are close 100 agents which is quite a less number as per my understanding

Please let me know if we need any other information and I will be happy to share and update

**Comment by FrancoRivero** [comment] 2022-08-26 15:46
Hi @skhanum,
thanks for your help in debugging this issue.
Apparently this error is not generated by a network problem, so we should continue debugging it.
Can you run a top command in your manager and some worker?
We should find some processes that are using a lot of resources (memory, disk, cpu, etc).
Sorry for the inconvenience and thank you for your help !
Regards

**Comment by skhanum** [comment] 2022-08-29 12:17
Hi @FrancoRivero 

Below is the requested output, the resources seems to be under control

In Master

`root@wazhuManager0:~# ps -eo cmd,%mem,%cpu --sort=-%mem | head
CMD                         %MEM %CPU
/var/ossec/framework/python 32.0  0.1
/var/ossec/bin/wazuh-analys  7.8  0.5
/var/ossec/bin/wazuh-db      6.5  1.2
/var/ossec/bin/wazuh-remote  3.7  0.8
/var/ossec/framework/python  2.5  0.0


root@wazhuManager0:~# ps -eo cmd,%mem,%cpu --sort=-%cpu | head
CMD                         %MEM %CPU
/var/ossec/bin/wazuh-db      6.5  1.2
/var/ossec/bin/wazuh-remote  3.7  0.8
/var/ossec/bin/wazuh-sysche  0.4  0.6
/var/ossec/bin/wazuh-analys  7.8  0.5
/var/ossec/bin/wazuh-authd   0.0  0.2
/var/ossec/bin/wazuh-monito  0.0  0.2
`

In Worker

`root@wazhuManager1:~# ps -eo cmd,%mem,%cpu --sort=-%cpu | head
CMD                         %MEM %CPU
/var/ossec/bin/wazuh-remote  4.1  1.2
/var/ossec/bin/wazuh-db      5.2  0.8
/var/ossec/bin/wazuh-sysche  0.3  0.7
/var/ossec/bin/wazuh-analys  7.7  0.6

root@wazhuManager1:~# ps -eo cmd,%mem,%cpu --sort=-%mem | head
CMD                         %MEM %CPU
/var/ossec/bin/wazuh-analys  7.7  0.6
/var/ossec/bin/wazuh-db      5.2  0.8
/var/ossec/bin/wazuh-remote  4.1  1.2
/var/ossec/framework/python  2.5  0.0
/var/ossec/framework/python  1.5  0.1
`

Please let me know if we need any other details and I will be happy to share

**Comment by FrancoRivero** [comment] 2022-08-30 13:55
Hi @skhanum,
how are you?
Thank you for your help !
We have an [issue](https://github.com/wazuh/wazuh/issues/14765) in Wazuh DB which are affecting some cluster, we are working in order to fix this bug. You could follow the development in this [issue](https://github.com/wazuh/wazuh/issues/14765) if you want to follow it.
So if by any chance the problem you have is different I would need you to keep your cluster in debug mode for a while and if you see a different problem than the one you named share with us the cluster.log file.
To configure your cluster in debug mode, you should modify `/var/ossec/etc/local_internal_options.conf` adding `wazuh_clusterd.debug=1` and after that restart your cluster.
Regards

**Comment by skhanum** [comment] 2022-08-30 14:36
Hi Franco,

Thanks a lot for your help.
I will have a quick check on the issue link shared

I will also share the debug logs as requested after replicating the issue and would keep the logging for 15 to 30 mins as this would generate debug logs and share it as well

Please excuse typo's

Saniya Khanum
________________________________

**Comment by skhanum** [comment] 2022-08-31 09:03
Hi @FrancoRivero 

Thanks for sharing the [issue](https://github.com/wazuh/wazuh/issues/14765) details. This does look similar with the one I am facing.
Will this be addressed in the later release?

I also did enable debug logging for cluster.log and tried reproducing the issue few times but I did not face the issue today to my surprise.

I will keep trying to repro and will share the requested debug logs as soon as I encounter the issue today.

Will keep you posted

**Comment by FrancoRivero** [comment] 2022-08-31 12:48
Hi @skhanum, 
I think this issue should be fixed in the next release, I will close this issue, however if you need to open it again let me know!
Thank you again for your help and if your problem is different than the mentioned issue let me know ! 
Regards

**Closed** 2022-09-05 11:37 UTC
Labels: module/framework, reporter/community
