### ISSUE TITLE
SCA policies not present in Sonoma Arm

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21837] opened 2024-02-08 17:03 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta1 | SCA| Agent | Packages | Sonoma ARM |

## Description

During testing for https://github.com/wazuh/wazuh/issues/21766, it was detected that on Sonoma ARM 14.2.1 endpoints, no SCA policies are copied and SCA is not executed.

```
cat /Library/Ossec/logs/ossec.log | grep sca
2024/02/08 15:04:28 sca: INFO: No policies defined. Exiting.

# ls /Library/Ossec/ruleset/sca/ -la
ls: -la: No such file or directory
/Library/Ossec/ruleset/sca/:
```

- More research required

**Comment by vikman90** [comment] 2024-02-09 12:30
@gdiazlo and I have found out that the this problem is caused at source installation: File `cis_apple_macOS_14.0.yml` cannot be found`.

This bug is caused by:
- https://github.com/wazuh/wazuh/issues/21440

The fix may be applied on [sca.files](https://github.com/wazuh/wazuh/blob/4.8.0/etc/templates/config/darwin/23/sca.files),

Transferring this issue to @wazuh/threat-intel.

**Comment by ooniagbi** [comment] 2024-02-09 13:58
https://github.com/wazuh/wazuh/pull/21848 to fix this.

**Comment by ooniagbi** [comment] 2024-02-09 14:00
https://github.com/wazuh/wazuh/pull/21848 reviewed and merged!

**Closed** 2024-02-09 14:01 UTC
Labels: type/bug, level/task
