### ISSUE TITLE
Don't allow to set same command sections in the configuration

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh#963] opened 2018-07-17 15:33 UTC
No error is shown when it is set two same `<command>` tags for active-response in the configuration file. For example:

```
<command>
    <name>disable-account</name>
    <executable>disable-account.sh</executable>
    <expect>user</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>

  <command>
    <name>disable-account</name>
    <executable>disable-account.sh</executable>
    <expect>user</expect>
    <timeout_allowed>yes</timeout_allowed>
  </command>
```

However, only the first one works so it should not be allowed to set two commands with the same name or at least it should trigger a warning message.

**Comment by vikman90** [comment] 2018-08-22 13:35
This issue is a duplicate of https://github.com/wazuh/wazuh/issues/1057
Fixed in https://github.com/wazuh/wazuh/pull/1128

**Closed by vikman90** 2018-08-22 13:35 UTC
Labels: bug, duplicate
