### ISSUE TITLE
log rotation issues

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh#2290] opened 2019-01-09 14:26 UTC
wazuh-manager 3.7.1

```xml
<ossec_config>
  <global>
    <jsonout_output>no</jsonout_output>
    <alerts_log>no</alerts_log>
    <logall>no</logall>
    <logall_json>yes</logall_json>
    <max_output_size>1M</max_output_size>
  </global>
....
```
# max_output_size option

It doesn't seem to be documented, but `max_output_size` does not actually result the log file being rotated once its over the specified size. This is the behaviour I expected, and is common in other applications. Instead, the log file is rotated every 600s as specified by `Config.min_rotate_interval`. That results logs like these:
```
-rw-r-----. 1 ossec ossec 1.6M Jan  8 14:01 ossec-archive-08-001.json
-rw-r-----. 1 ossec ossec  42K Jan  8 14:11 ossec-archive-08-002.json
-rw-r-----. 1 ossec ossec  34K Jan  8 14:21 ossec-archive-08-003.json
-rw-r-----. 1 ossec ossec  42K Jan  8 14:31 ossec-archive-08-004.json
-rw-r-----. 1 ossec ossec 2.8M Jan  8 14:41 ossec-archive-08-005.json
-rw-r-----. 1 ossec ossec 1.1M Jan  8 14:51 ossec-archive-08-006.json
-rw-r-----. 1 ossec ossec 1.7M Jan  8 15:01 ossec-archive-08-007.json
-rw-r-----. 1 ossec ossec 1.1M Jan  8 15:11 ossec-archive-08-008.json
-rw-r-----. 2 ossec ossec 2.1M Jan  8 15:21 ossec-archive-08-009.json
```

# log rotation when older files are deleted

Now suppose that I have cron job that delete files, and I have:

```
-rw-r-----. 1 ossec ossec 1.1M Jan  8 15:31 ossec-archive-08-008.json
-rw-r-----. 2 ossec ossec 2.1M Jan  8 15:31 ossec-archive-08-009.json
```
After I restart `wazuh-manage`, or the log rotates, I get:

```
-rw-r-----. 2 ossec ossec  16K Jan  8 15:34 ossec-archive-08-001.json
-rw-r-----. 1 ossec ossec 1.1M Jan  8 15:31 ossec-archive-08-008.json
-rw-r-----. 1 ossec ossec 2.1M Jan  8 15:34 ossec-archive-08-009.json
```

Rotation code:

https://github.com/wazuh/wazuh/blob/01b9b0a3c8b803868cc3e9cfe2f0772d9932417d/src/analysisd/alerts/getloglocation.c#L131-L135

# limiting the number of log files for archive and alert logs

This is a feature request. In the case where logs are shipped out with logstash/filebeat, there is no point keeping the logs. A cron job can certainly be used here, but it would be nice to have an option in wazuh itself. For example, have up to 10 files, where each can be a maximum of 1 GB. That way an administrator can control the storage usage

**Comment by vikman90** [comment] 2019-01-09 15:43
Hi @rossengeorgiev,

We have not been able to reproduce this issue. We have decreased `analysisd.min_rotate_interval` to 10 seconds and the file is not rotated until 1 MiB with your configuration.

Just as you said, the expected configuration for file size limit is that the manager shall check the every output file size each `analysisd.min_rotate_interval` seconds (in your case, 10 minutes). All these files that exceed the size limit will be rotated.

Could you send us a configuration report using the API?

### Local configuration

```json
# curl -u foo:bar -k http://127.0.0.1:55000/agents/000/config/analysis/global?pretty
{
   "error": 0,
   "data": {
      "global": {
         "email_notification": "yes",
         "max_output_size": 1048576,
         "alerts_log": "no",
         "zeromq_output": "no",
         "host_information": 8,
         "jsonout_output": "no",
         "rootkit_detection": 8,
         "integrity_checking": 8,
         "memory_size": 8192,
         "logall": "no",
         "prelude_output": "no",
         "stats": 4,
         "rotate_interval": 0,
         "logall_json": "yes"
      }
   }
}
```

### Internal configuration

```json
# curl -u foo:bar -k http://127.0.0.1:55000/agents/000/config/analysis/internal?pretty
{
   "error": 0,
   "data": {
      "internal": {
         "analysisd": {
            "label_cache_maxage": 1,
            "stats_percent_diff": 150,
            "show_hidden_labels": 0,
            "decoder_order_size": 256,
            "min_rotate_interval": 10,
            "stats_mindiff": 1250,
            "log_fw": 1,
            "rlimit_nofile": 65536,
            "fts_list_size": 32,
            "debug": 0,
            "fts_min_size_for_str": 14,
            "default_timeframe": 360,
            "stats_maxdiff": 999000
         }
      }
   }
}
```

Regarding your request to limit the number of rotations, let me label this issue as `enhancement` to implement it. We have some things to discuss. For instance, if what should the manager do if it exceeds the number of rotations?

1. Stop rotating.
2. Delete older files.

There is an issue related to your third answer: #87. Please confirm us that you are using the `ossec-puppet` module.

Thanks for reporting this issue.
Best regards.

**Comment by rossengeorgiev** [comment] 2019-01-09 16:44
I see, the default is set to 600.

```
# cat /var/ossec/etc/internal_options.conf | grep min_rotate
analysisd.min_rotate_interval=600
```
I can just change this value to something lower and achieve what I need, thanks!

In regards to the rotation, I would expect to be able to set a max number of files. For example, 10, then as result only have the latest 10 log files for each type. Say we keep all other settings as default, then I would end up with log files for the last 10 days, since they only get rotated daily.

I would also suggest a change to the filename. Instead of appending a number, use a timestamp at time of rotation. For example, `ossec-archive-09-163201.json`. File was rotated at 16:32:01.

**Comment by rhysxevans** [comment] 2019-02-06 13:47
Hi

Do you have an ETA for this feature ?

Just need to know something like the next 3, 6 or 12 months 

Thanks

**Comment by rossengeorgiev** [comment] 2019-04-02 12:07
Any progress on this?

Something I have missed to mention is that rotated files are not compressed immediately. Someone else has already pointed that out in https://github.com/wazuh/wazuh/issues/2919

**Comment by Cerv1** [comment] 2019-04-03 14:50
Hi @rhysxevans and @rossengeorgiev!

I hope you are all doing well. We're currently working on this new features in [this branch](https://github.com/wazuh/wazuh/tree/fix-log-compression). 

We're developing the following features:
* Compressing alerts logs when `rotate_inverval` is defined (https://github.com/wazuh/wazuh/commit/17778ec7066cc9f1cccb28e3a15b4a866535f1ee)
* Delete old logs.

 Any suggestion is welcome, I'll keep you updated!

Best regards,
Cerv1.

**Comment by rhysxevans** [comment] 2019-04-04 21:44
Hi

Thanks, just for clarification, at present. If I set the following to values 

```
  <global>
    <rotate_interval>1h</rotate_interval>
    <max_output_size>2G</max_output_size>
  </global>
```

The following will be the expected behaviour

The files (alerts and archive) will be checked every hour, to see if they are over 2G, if they are they will be rotated out  

Is that correct ?

I am having issues with filebeat, when the files are getting large (I think this is around 10G). Filebeat doesn't seem to be able to process the log, in the event Filebeat is restarted (service, or failure).

Thanks

**Comment by Cerv1** [comment] 2019-04-05 15:09
Hi @rhysxevans,

As @rossengeorgiev said, the option `max_output_size` it's not working as expected. 

We've been able to reproduce this issue and we've fixed in [this commit](https://github.com/wazuh/wazuh/commit/3f6b1795941aa88241cfb98e78147763a3d8c42f). Right now, logs will rotate after `rotate_interval`, in your case, after **1h** if they're not empty.

Regarding the problem with *Filebeat*, I'll need more information about it. Does the process die? Or does it get blocked?

Best regards,
Cerv1.

**Comment by rhysxevans** [comment] 2019-04-07 11:07
Hi

Thanks, regarding filebeat, it doesn't stop it just doesn't process the
logs in a sustainable timeframe (IE I let it run for 90 mins, and nothing
comes through to the elasticsearch cluster, I haven't let it run for longer
than this).

Note this only occurs when the logs are large (Tens of GB) and filebeat is
restarted (be that due to server failure, or process restart), keeping the
logs to a manageable size  (at most a few GB's) seems to do the trick for me

Thanks

**Comment by rossengeorgiev** [comment] 2019-04-07 14:56
@rhysxevans sounds like a problem with your configuration or lack of connectivity. Look at the logs to find out while. FIlebeat has no problem with 90GB file.

**Comment by vikman90** [comment] 2024-04-10 16:21
Closing this issue as it will be superseded by version 5.0.

**Closed as not planned by vikman90** 2024-04-10 16:21 UTC
Labels: type/bug, type/enhancement
