### ISSUE TITLE
Installation Errors

### ISSUE THREAD

**Issue by LeroyJ0nes** [wazuh/wazuh#13231] opened 2022-04-25 15:31 UTC
System:
┌──(r**t💀kali)-[~]
└─# hostnamectl
 Static hostname: kali
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: No
         Boot ID: No
  Virtualization: vmware
Operating System: Kali GNU/Linux Rolling
          Kernel: Linux 5.10.0-kali9-amd64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware Virtual Platform

Hello team, i'm having multiple issues during the installation of the latest version of Wazuh server from the documentation provided here:
https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html

I'm getting some messages regarding deprecated GPG keys, some repositories not found, and invalid signatures.

Can you point me in the right direction ?

┌──(r**t💀kali)-[~]
└─# apt-get update                       
Get:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease [2,147 B]
Hit:2 https://packages.wazuh.com/4.x/apt stable InRelease                                                                                                            
Hit:3 http://packages.microsoft.com/repos/code stable InRelease                                                                                                      
Hit:4 https://repo.nordvpn.com//deb/nordvpn/debian stable InRelease                                                                                 
Err:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease                                                               
  The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
Hit:5 https://download.sublimetext.com apt/stable/ InRelease                                            
Hit:6 https://mirror.karneval.cz/pub/linux/kali kali-rolling InRelease
Ign:7 https://updates.atomicorp.com/channels/atomic/kali kali InRelease
Err:8 https://updates.atomicorp.com/channels/atomic/kali kali Release
  404  Not Found [IP: 51.161.13.101 443]
Reading package lists... Done
W: https://ossec.wazuh.com/repos/apt/debian/dists/wheezy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://ossec.wazuh.com/repos/apt/debian wheezy InRelease: The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
E: The repository 'https://ossec.wazuh.com/repos/apt/debian wheezy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://packages.wazuh.com/4.x/apt/dists/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Contents-deb (main/Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Contents-deb (main/Contents-all) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: https://download.sublimetext.com/apt/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://updates.atomicorp.com/channels/atomic/kali kali Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Contents-deb (main/Contents-amd64) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
W: Target Contents-deb (main/Contents-all) is configured multiple times in /etc/apt/sources.list.d/wazuh.list:1 and /etc/apt/sources.list.d/wazuh.list:2
                                                                                                                                                                      
┌──(r**t💀kali)-[~]
└─# curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | apt-key add -                                                                                                                        100 ⨯
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
OK

**Comment by rauldpm** [comment] 2022-04-25 16:23
Hello @LeroyJ0nes, I am preparing an answer to your questions and doing some checks, I'll be back shortly

**Comment by rauldpm** [comment] 2022-04-25 16:47
Hello @LeroyJ0nes 

Regarding `apt-key` command, it is true that it is being deprecated but that does not disable its function, what is obtained is a warning and the command should work

Can you run: `apt-key list` command and check that you see the following in the list?

```
/etc/apt/trusted.gpg
--------------------
pub   rsa4096 2016-08-01 [SC] [expires: 2027-05-15]
      0DCF CA55 47B1 9D2A 6099  5060 96B3 EE5F 2911 1145
uid           [ unknown] Wazuh.com (Wazuh Signing Key) <support@wazuh.com>
sub   rsa4096 2016-08-01 [E] [expires: 2027-05-15]
```

Regarding the `ossec.wazuh.com` repository, it is quite old and is no longer used for any installation, in fact, in our documentation it is indicated to use the `packages.wazuh.com` repository from version 2.1 to the current one

- https://documentation.wazuh.com/2.1/getting-started/
- https://documentation.wazuh.com/current/getting-started/

I see many warnings referring to duplicate entries in `/etc/apt/sources.list.d/wazuh.list`, could you show its content? In principle, you should have a line like the following referring to our current production repository:

```
# cat /etc/apt/sources.list.d/wazuh.list                              
deb https://packages.wazuh.com/4.x/apt/ stable main
```

Regarding the `atomicorp` not found repository, it is an external repository to wazuh, and it is also based on ossec, maybe you can get more information in its forum https://support.atomicorp.com/hc/en-us

Regards, Raúl.

**Comment by LeroyJ0nes** [comment] 2022-04-25 18:23
Hi, thank you for your thorough reply. In the meantime i tried to remove everything i could related to wazu/ossec in order to do a brand new install again, thinking i must i done something wrong the first time.

So, i haven't dont the new install yet, but i tried to deleted/removed/purged a lot of material.

Here is the current data so far:

┌──(r**t💀kali)-[~]
└─# apt-get update                           
Hit:1 http://packages.microsoft.com/repos/code stable InRelease
Get:2 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease [2,147 B]                                                                                             
Hit:3 https://repo.nordvpn.com//deb/nordvpn/debian stable InRelease                                                                                        
Err:2 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease                                                               
  The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
Get:4 https://kali.download/kali kali-rolling InRelease [30.6 kB]                                                                                          
Hit:5 https://download.sublimetext.com apt/stable/ InRelease                                                 
Get:6 https://kali.download/kali kali-rolling/main Sources [14.5 MB]
Ign:7 https://updates.atomicorp.com/channels/atomic/kali kali InRelease
Err:8 https://updates.atomicorp.com/channels/atomic/kali kali Release
  404  Not Found [IP: 51.79.80.20 443]
Get:9 https://kali.download/kali kali-rolling/non-free Sources [128 kB]
Get:10 https://kali.download/kali kali-rolling/main amd64 Packages [18.2 MB]
Get:11 https://kali.download/kali kali-rolling/main amd64 Contents (deb) [41.3 MB]
Get:12 https://kali.download/kali kali-rolling/non-free amd64 Packages [213 kB]
Get:13 https://kali.download/kali kali-rolling/non-free amd64 Contents (deb) [1,004 kB]
Reading package lists... Done                                                                                                                                         
W: https://ossec.wazuh.com/repos/apt/debian/dists/wheezy/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
W: GPG error: https://ossec.wazuh.com/repos/apt/debian wheezy InRelease: The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
E: The repository 'https://ossec.wazuh.com/repos/apt/debian wheezy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://download.sublimetext.com/apt/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.
E: The repository 'https://updates.atomicorp.com/channels/atomic/kali kali Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
                                                                                                                                                                       
┌──(r**t💀kali)-[~]
└─# cat /etc/apt/sources.list.d/wazuh.list                                                                                                                       100 ⨯
cat: /etc/apt/sources.list.d/wazuh.list: No such file or directory

**Comment by LeroyJ0nes** [comment] 2022-04-25 18:27
there used to be 2 keys related to wazuh and ossec that i removed from here:

┌──(r**t💀kali)-[~]
└─# apt-key list                                                                                                                                                   1 ⨯
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
/etc/apt/trusted.gpg
--------------------

there are other keys down below but not related, they have to do with gpgsecurity@microsoft and ftpmaster@debian

**Comment by rauldpm** [comment] 2022-04-25 21:54
Hello @LeroyJ0nes 

I have managed to reproduce your error messages with the following commands:

```
- wget -qO - https://ossec.wazuh.com/repos/apt/conf/ossec-key.gpg.key | sudo apt-key add -
- echo -e "deb https://ossec.wazuh.com/repos/apt/debian wheezy main" >> /etc/apt/sources.list.d/ossec.list
```

When executing an `apt-get upgrade`, I get the following output:

```
# apt-get update                                                                          
Get:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease [2,147 B]
Err:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease 
  The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
Hit:2 http://kali.download/kali kali-rolling InRelease
Reading package lists... Done
W: GPG error: https://ossec.wazuh.com/repos/apt/debian wheezy InRelease: The following signatures were invalid: 9FE55537D1713CA519DFB85114B9C8DB9A1B1C65
E: The repository 'https://ossec.wazuh.com/repos/apt/debian wheezy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

In the path `/etc/apt/sources.list.d`, you should have a file called `ossec.list`, is this correct? If it exists, remove it

Also, under the `apt-key list` command output, you should see a reference to santiago.bassett@gmail.com, there is the key added for our old repository, if you see it, delete it too (see that the gpg signature is the same as yours)

```
/etc/apt/trusted.gpg
--------------------
pub   rsa2048 2013-12-01 [SC]
      9FE5 5537 D171 3CA5 19DF  B851 14B9 C8DB 9A1B 1C65
uid           [ unknown] Santiago Bassett <santiago.bassett@gmail.com>
sub   rsa2048 2013-12-01 [E]
```

Regards, Raúl.

**Comment by LeroyJ0nes** [comment] 2022-04-27 12:44
Hi, thank you.

I removed the key related to santiago.bassett@gmail.com

/etc/apt/sources.list.d had a line with atomicorp, i removed it


Now the info looks like this:

┌──(r**t💀kali)-[~]
└─# apt-get update && apt-get full-upgrade -y
Get:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease [2,147 B]
Hit:2 http://packages.microsoft.com/repos/code stable InRelease                                                                                                                  
Hit:3 https://repo.nordvpn.com//deb/nordvpn/debian stable InRelease                                                                                 
Err:1 https://ossec.wazuh.com/repos/apt/debian wheezy InRelease                                                               
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 14B9C8DB9A1B1C65
Hit:4 https://download.sublimetext.com apt/stable/ InRelease                                            
Hit:5 https://mirrors.dotsrc.org/kali kali-rolling InRelease          
Reading package lists... Done
W: GPG error: https://ossec.wazuh.com/repos/apt/debian wheezy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 14B9C8DB9A1B1C65
E: The repository 'https://ossec.wazuh.com/repos/apt/debian wheezy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: https://download.sublimetext.com/apt/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

**Comment by LeroyJ0nes** [comment] 2022-04-28 12:59
Oh sorry, i meant that i first tried to install Ossec a couple of weeks ago, and i believe it is related to Atomicorp
https://atomicorp.com/atomic-enterprise-ossec/

So when i ran your command and so lines with atomicorp on it i removed them, since i trying to clean my set up and ultimately do a new wazuh install.

Nothing comes up when i run your command:
┌──(r**t💀kali)-[~]
└─# grep -R "ossec" /etc/apt/sources.list.d
                                                                                                                                                                                                                     
┌──(r**t💀kali)-[~]
└─#

**Comment by rauldpm** [comment] 2022-04-28 20:51
Hello @LeroyJ0nes , well it's weird, the only way I've had to reproduce your case is keeping the .list file with the repository `https://ossec.wazuh.com/repos/apt/debian wheezy InRelease` in a file in the path `/etc/apt/sources.list.d/`, and if there isn't a file in that directory that has a reference to ossec.wazuh.com, the apt-get update command shouldn't show anything abbout ossec.wazuh.com, however, this shouldn't cause a problem with the  installation of our current product following the guide you shared at the beginning.

Can you run this command in case you have a reference to our old and deprecated repository in another file in the parent folder that also references official system repositories?

```
grep -R "ossec" /etc/apt/
```

Also, regarding Articorp, keep in mind that they are based on original Ossec, not Wazuh, so our reference to Ossec is not the same as Articorp and shouldn't affect this.

**Comment by LeroyJ0nes** [comment] 2022-04-29 14:34
Helle, here is the result:
┌──(r**t💀kali)-[~]
└─# grep -R "ossec" /etc/apt/              
/etc/apt/sources.list:deb https://ossec.wazuh.com/repos/apt/debian wheezy main

**Comment by rauldpm** [comment] 2022-04-29 18:55
Hello @LeroyJ0nes, please remove from the `/etc/apt/sources.list` file the `deb https://ossec.wazuh.com/repos/apt/debian wheezy main` line, then do an `apt-get update`, do you still see the error?

**Comment by LeroyJ0nes** [comment] 2022-04-30 04:08
Hi, i removed the line, and updated, no more errors showing:

┌──(r**t💀kali)-[~]
└─# cat /etc/apt/sources.list
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb https://http.kali.org/kali kali-rolling main contrib non-free

# Additional line for source packages
deb-src https://http.kali.org/kali kali-rolling main contrib non-free
                                                                                                                                                                                                                     
┌──(r**t💀kali)-[~]
└─# apt-get update                           
Get:1 http://packages.microsoft.com/repos/code stable InRelease [10.4 kB]
Hit:2 https://repo.nordvpn.com//deb/nordvpn/debian stable InRelease                                                                                          
Get:3 http://packages.microsoft.com/repos/code stable/main amd64 Packages [81.5 kB]                                           
Get:4 http://packages.microsoft.com/repos/code stable/main arm64 Packages [82.4 kB]                                                                  
Get:5 http://packages.microsoft.com/repos/code stable/main armhf Packages [82.3 kB]                                           
Hit:6 https://download.sublimetext.com apt/stable/ InRelease                                         
Get:7 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling InRelease [30.6 kB]
Get:8 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/non-free Sources [129 kB]
Get:9 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/main Sources [14.6 MB]
Get:10 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/contrib Sources [72.5 kB]
Get:11 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/main amd64 Packages [18.2 MB]
Get:12 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/main amd64 Contents (deb) [41.9 MB]
Get:13 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/contrib amd64 Packages [116 kB]
Get:14 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/contrib amd64 Contents (deb) [157 kB]
Get:15 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/non-free amd64 Packages [214 kB]
Get:16 https://ftp.acc.umu.se/mirror/kali.org/kali kali-rolling/non-free amd64 Contents (deb) [1,005 kB]
Fetched 76.7 MB in 8s (9,164 kB/s)                                                                                                                                                                                  
Reading package lists... Done
W: https://download.sublimetext.com/apt/stable/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

Thank you!

So based on my version of Kali Linux, in order to apt install Wazuh, Elasticsearch, Filebeaet and Kibana, the link and procedure is still this one ?
https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all-in-one.html

 Static hostname: kali
       Icon name: computer-vm
         Chassis: vm 🖴
      Machine ID: No
         Boot ID: No
  Virtualization: vmware
Operating System: Kali GNU/Linux Rolling
          Kernel: Linux 5.10.0-kali9-amd64
    Architecture: x86-64
 Hardware Vendor: VMware, Inc.
  Hardware Model: VMware Virtual Platform

**Comment by rauldpm** [comment] 2022-05-03 15:40
Hello @LeroyJ0nes 

I'm glad you were able to fix it, regarding Kali, it's a Debian based distribution, so in principle it should be possible to use it on this system, although please note that this system is not marked as one of the supported systems https://documentation.wazuh.com/current/installation-guide/requirements.html

Anyway, I have done the installation of that guide and I have achieved a functional deployment, keep in mind that for this type of deployment, it is recommended to have at least 4GB of RAM for proper operation.

If you have any problem with the installation please tell me.

Regards, Raúl.

**Comment by rauldpm** [comment] 2022-05-10 17:28
Hello @LeroyJ0nes 

I close this issue due to inactivity, if you consider it appropriate, do not hesitate to reopen this issue.

Regards, Raúl.

**Closed by rauldpm** 2022-05-10 17:28 UTC
Labels: community
