### ISSUE TITLE
API PUT /{rootcheck,syscheck} runs one of them, not both

### ISSUE THREAD

**Issue by singuliere** [wazuh/wazuh#2236] opened 2019-01-08 16:45 UTC
## Bug report

**OS**
_Debian GNU/Linux Stretch._

**Wazuh version**
_3.7.2-1_

**Wazuh API version**
_3.7.2_

**Install type**
_manager and agent_

**Install method**
_packages_

**Log sample**

`/var/ossec/logs/ossec.log` on the wazuh-agent
```
2019/01/08 16:18:35 rootcheck: INFO: Started (pid: 29423).
2019/01/08 16:18:37 wazuh-modulesd: INFO: Agent is now online. Process unlocked, continuing...
2019/01/08 16:18:37 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2019/01/08 16:18:50 ossec-syscheckd: INFO: Syscheck scan frequency: 43200 seconds
2019/01/08 16:18:50 ossec-syscheckd: INFO: Starting syscheck scan.
2019/01/08 16:18:50 rootcheck: INFO: Starting rootcheck scan.
2019/01/08 16:18:55 ossec-syscheckd: INFO: Starting syscheck database (pre-scan).
2019/01/08 16:19:07 rootcheck: INFO: Ending rootcheck scan.
2019/01/08 16:19:20 ossec-syscheckd: INFO: Finished creating syscheck database (pre-scan completed).
2019/01/08 16:19:25 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
2019/01/08 16:19:41 rootcheck: INFO: Starting rootcheck scan.
2019/01/08 16:19:59 rootcheck: INFO: Ending rootcheck scan.
2019/01/08 16:21:40 ossec-syscheckd: INFO: Starting syscheck scan.
2019/01/08 16:22:16 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
2019/01/08 16:22:46 rootcheck: INFO: Starting rootcheck scan.
2019/01/08 16:23:04 rootcheck: INFO: Ending rootcheck scan.
2019/01/08 16:29:08 rootcheck: INFO: Starting rootcheck scan.
2019/01/08 16:29:25 rootcheck: INFO: Ending rootcheck scan.
2019/01/08 16:32:29 ossec-syscheckd: INFO: Starting syscheck scan.
2019/01/08 16:33:06 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
2019/01/08 16:33:36 ossec-syscheckd: INFO: Starting syscheck scan.
2019/01/08 16:34:13 ossec-syscheckd: INFO: Ending syscheck scan. Database completed.
```

`/var/ossec/logs/api.log` on the wazuh-manager

```
WazuhAPI 2019-01-08 16:17:03 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:34 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:34 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:36 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:38 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:42 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:18:51 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:07 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:12 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:39 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:39 frob: [::ffff:86.247.128.19] GET /syscheck/001?file=/etc/fuse.conf - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:40 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:41 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:42 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:44 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:49 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:19:57 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:20:13 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:20:43 frob: [::ffff:127.0.0.1] GET /rootcheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:20:46 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:39 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:39 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:40 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:42 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:45 frob: [::ffff:127.0.0.1] GET /rootcheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:47 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:49 frob: [::ffff:127.0.0.1] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:21:55 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:12 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:44 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:44 frob: [::ffff:86.247.128.19] GET /syscheck/001?file=/etc/fuse.conf - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:45 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:46 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:47 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:49 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:22:54 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:23:02 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:23:18 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:23:51 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:24:55 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:27:03 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:07 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:07 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:08 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:10 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:15 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:23 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:29:39 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:30:21 frob: [::ffff:127.0.0.1] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:30:32 frob: [::ffff:127.0.0.1] GET /rootcheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:29 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:29 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:30 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:33 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:37 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:46 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:32:48 frob: [::ffff:127.0.0.1] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:02 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:34 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:34 frob: [::ffff:86.247.128.19] GET /syscheck/001?file=/etc/fuse.conf - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:36 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:36 frob: [::ffff:86.247.128.19] PUT /syscheck/001 - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:37 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:39 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:44 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:33:52 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:34:08 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:34:40 frob: [::ffff:86.247.128.19] GET /syscheck/001/last_scan - 200 - error: '0'.
WazuhAPI 2019-01-08 16:34:41 frob: [::ffff:86.247.128.19] GET /syscheck/001?file=/etc/fuse.conf - 200 - error: '0'.
```

Bug description
----------------

When sending **PUT /{rootcheck,syscheck}** the designated agent runs either rootcheck or syscheck but not both. Sometimes **PUT /syscheck** triggers a run of rootcheck and sometimes it triggers a run of syscheck.

**Comment by Zenidd** [comment] 2019-05-21 11:54
Hi @singuliere,

Syscheck and rootcheck are implemented in the same daemon so it's not possible to restart one of them separately. In the next version of Wazuh, v3.10, they may be separated into two different modules so that they can be started, stopped and restarted separately.

In your case, if needed, we recommend you reset the two by using `PUT /syscheck` 

<br></br>
Best regards,

Juan Pablo Sáez

**Comment by singuliere** [comment] 2019-05-21 12:05
@Zenidd I think there is a misunderstanding about the bug described here.

> In your case, if needed, we recommend you reset the two by using **PUT /syscheck**

This does not work. If you do that it will sometime report to only trigger the run of rootcheck. I suggest you try that and see for yourself that the logs reports running either **rootcheck** or **syscheck** when receiving **PUT /syscheck**.

I think the logs and the example above describe the problem accurately but please let me know if something is ambiguous.

**Comment by Zenidd** [comment] 2019-05-22 10:37
Hi again @singuliere,

we're sorry for the misunderstanding, As you well indicated, there is a problem on how the restart of `syscheck` and `rootcheck` is performed.

Let's trace what happens with this two API calls:
<br></br>
1. This is the correspondence between API calls and functions:

https://github.com/wazuh/wazuh/blob/6f4b54891e83f088b8e9af73586c89b0f1908382/framework/wazuh/cluster/dapi/requests_list.py#L303-L306

https://github.com/wazuh/wazuh/blob/6f4b54891e83f088b8e9af73586c89b0f1908382/framework/wazuh/cluster/dapi/requests_list.py#L343-L345
<br></br>
2. The function `run` is the same for Rootcheck and Syscheck:

https://github.com/wazuh/wazuh/blob/93f2febb9c0d5d7a682d355ad1a2420c731670e0/framework/wazuh/syscheck.py#L16-L55
<br></br>
3. After seeing the function call `oq.send_msg_to_agent(OssecQueue.HC_SK_RESTART, agent_id)`, we keep tracing the flow of the API call by following  `HC_SK_RESTART`. Here is where the call to resetter function of `syscheck` and `rootcheck` is performed.

https://github.com/wazuh/wazuh/blob/4f95081c711dfdc1ddda3735b93e0b869af0ace1/src/client-agent/receiver.c#L135-L139

<br></br>
4.The function sets Syscheck and Rootcheck to be restarted. The problem begins here, as you can see there is only one file descriptor that they both share.
https://github.com/wazuh/wazuh/blob/b07c3d36b59a68b4e775c82777b696dd3e1d2ed2/src/shared/agent_op.c#L39-L53


<br></br>
5. Each second Syscheck and Rootcheck check if they need to restart:
https://github.com/wazuh/wazuh/blob/4887fb875c8b988fc62c97d48bcdce9839feefb4/src/rootcheck/run_rk_check.c#L303-L317

https://github.com/wazuh/wazuh/blob/6243d1d3483b74f943d1ac894579805dc853fc18/src/syscheckd/run_check.c#L210-L216

<br></br>
6. The unexpected behaviour occurs inside the function that checks the need of restarting them. When the restarting request is set by the function `os_set_restart_syscheck()`, one of the two, rootcheck or syscheck will execute first `os_check_restart_syscheck()` and own the file descriptor, so the one who performs the call later will see no need of restart.
https://github.com/wazuh/wazuh/blob/b07c3d36b59a68b4e775c82777b696dd3e1d2ed2/src/shared/agent_op.c#L14-L34

### One possible approach to the solution

 - Creating two separate file descriptors to avoid this race condition.
<br></br>

We will work on this issue as soon as possible. Thank you for your quick response and for detailing the issue, you have been really helpful.

<br></br>
Best regards,

Juan Pablo Sáez

**Comment by singuliere** [comment] 2019-05-22 17:36
Wow! This truly is a wonderful diagnostic of the problem. Kudos :-)

**Comment by FernandoCP** [comment] 2020-03-12 09:04
I will close this issue because I have been testing this problem in the current development and it already works as it should.

**Closed by FernandoCP** 2020-03-12 09:05 UTC
Labels: bug, community, core/fim, core/rootcheck
