### ISSUE TITLE
Release 4.8.1 - RC 2 - E2E UX tests - Azure integration

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#24459] opened 2024-07-08 07:55 UTC
## End-to-End (E2E) Testing Guideline

- **Documentation:** Always consult the development documentation for the current stage tag at [this link](https://documentation-dev.wazuh.com/v4.8.1-rc2/index.html). Be careful because some of the description steps might refer to a current version in production, always navigate using the current development documention for the stage under test. Also, visit the following [pre-release package guide](https://docs.google.com/document/d/1fW8koy8P8OMvcxzIOXWGDw9qmKlju-XuRHD-Bdv3uP4/edit) to understand how to modify certain links and urls for the correct testing of the development packages.
- **Test Requirements:** Ensure your test comprehensively includes a full stack and agent/s deployment as per the Deployment requirements, detailing the machine OS, installed version, and revision.
- **Deployment Options:** While deployments can be local (using VMs, Vagrant, etc) or on the aws-dev account, opt for local deployments when feasible. For AWS access, coordinate with the DevOps team through [this link](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **External Accounts:** If tests require third-party accounts (e.g., GitHub, Azure, AWS, GCP), request the necessary access through the DevOps team [here](https://github.com/wazuh/internal-devel-requests/issues/new?assignees=&labels=level%2Ftask%2C+request%2Foperational%2C+type%2Fchange&projects=&template=operational--request.md&title=%3CTitle%3E).
- **Alerts:** Every test should generate a minimum of one end-to-end alert, from the agent to the dashboard, irrespective of test type.
- **Multi-node Testing:** For multi-node wazuh-manager tests, ensure agents are connected to both workers and the master node.
- **Package Verification:** Use the pre-release package that matches the current TAG you're testing. Confirm its version and revision.
- **Filebeat Errors:** If you encounter errors with Filebeat during testing, refer to [this Slack discussion](https://wazuh-team.slack.com/archives/C03BDG0K6JC/p1672168163537809) for insights and resolutions.
- **Known Issues:** Familiarize yourself with previously reported issues in the Known Issues section. This helps in identifying already recognized errors during testing.
- **Reporting New Issues:** Any new errors discovered during testing that aren't listed under Known Issues should be reported. Assign the issue to the corresponding team (QA if unsure), add the `Release testing` objective and `Urgent` priority. Communicate these to the team and QA via the c-release Slack channel.
- **Test Conduct:** It's imperative to be thorough in your testing, offering enough detail for reviewers. Incomplete tests might necessitate a redo.
- **Documentation Feedback:** Encountering documentation gaps, unclear guidelines, or anything that disrupts the testing or UX? Open an issue, especially if it's not listed under Known Issues. Please answer the feedback section, this is a mandatory step.
- **Format:** If this is your first time doing this, refer to the format (but not necessarily the content, as it may vary) of previous E2E tests, here you have an example https://github.com/wazuh/wazuh/issues/13994.
- **Status and completion:** Change the issue status within your team project accordingly. Once you finish testing and write the conclusions, move it to Pending review and notify the @wazuh/devel-devops team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ). Beware that the reviewers might request additional information or task repetitions.
- **For reviewers:** Please move the issue to Pending final review and notify via Slack using the same thread if everything is ok, otherwise, perform an issue update with the requested changes and move it to On hold, increase the review_cycles in the  team project by one and notify the issue assignee via Slack using the same thread.

For the conclusions and the issue testing and updates, use the following legend:

**Status legend**
- 🟢 All checks passed
- 🟡 Found a known issue
- 🔴 Found a new error

## Issue delivery and completion
- **Initial delivery:** The issue's assignee must complete the testing and deliver the results by Jul 09, 2024 and notify the @wazuh/devel-pyserver team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ)
- **Review:** The @wazuh/devel-pyserver team will assign a reviewer and add it to the `review_assignee` field in the  project. The reviewer must then review the test steps and results. Ensure that all iteration cycles are completed by Jul 10, 2024 date (issue must be in `Pending final review` status) and notify the QA team via Slack using the [c-release channel](https://wazuh-team.slack.com/archives/C02A737S5MJ).
- **Auditor:** The QA team must audit, validate the results, and close the issue by Jul 10, 2024.

## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Step by step](https://documentation-dev.wazuh.com/v4.8.1-rc2/installation-guide/wazuh-indexer/step-by-step.html) | Single node | Alma Linux 8 x86_64 |
| Server | [Step by step](https://documentation-dev.wazuh.com/v4.8.1-rc2/installation-guide/wazuh-server/step-by-step.html) | Multi node | Alma Linux 8 x86_64 |
| Dashboard | [Step by step](https://documentation-dev.wazuh.com/v4.8.1-rc2/installation-guide/wazuh-dashboard/step-by-step.html) | - | Alma Linux 8 x86_64 |
| Agent | [Wazuh WUI one-liner deploy using IP](https://documentation-dev.wazuh.com/v4.8.1-rc2/_images/deploy-new-agent-from-ui1.png) | - | Alma Linux 8 x86_64 |

## Test description

Configure the Azure integration in a Wazuh Manager and a Wazuh Agent. 
Try the Graph, Log Analytics, and Storage integrations.
Ensure the events are correctly displayed on the dashboard.
Documentation: https://documentation-dev.wazuh.com/v4.8.1-rc2/cloud-security/azure/index.html

## Known issues

- https://github.com/wazuh/wazuh-documentation/issues/5803
- https://github.com/wazuh/wazuh-documentation/issues/6494
- https://github.com/wazuh/wazuh-documentation/issues/6563
- https://github.com/wazuh/wazuh/issues/19282
- https://github.com/wazuh/wazuh-documentation/issues/6559

## Conclusions

Summarize the errors detected (Known Issues included). Illustrate using the table below, removing current examples:

| **Status**     | **Test**    | **Failure type**    | **Notes**      |
|----------------|-------------|---------------------|----------------|
| 🟢 | Deployment | NA | NA |
| 🟢 | Azure Integration for Log Analytics, Graphs and Storage on Wazuh Server  | NA | NA |
| 🔴 | Azure Integration for Log Analytics, Graphs and Storage on Wazuh agent  | Error `1` | Similar credentials and configuration used successfully on the Wazuh server integration were used on the Wazuh agent but it did not work. Reported the error on issue[#24545](https://github.com/wazuh/wazuh/issues/24545) |

## Feedback

We value your feedback. Please provide insights on your testing experience.

- Was the testing guideline clear? Were there any ambiguities?
- Did you face any challenges not covered by the guideline?
- Suggestions for improvement:

## Reviewers validation

The criteria for completing this task is based on the validation of the conclusions and the test results by all reviewers.

All the checkboxes below must be marked in order to close this issue.
- [ ] @juliamagan
- [x] @wazuh/devel-pyserver

**Comment by SamsonIdowu** [comment] 2024-07-08 21:44
### OS version and IP check:
**Wazuh dashboard:**
```
[root@wazuh-dashboard ~]# ip a && cat /etc/os-release
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:25:b7:f8 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 192.168.186.40/24 brd 192.168.186.255 scope global noprefixroute ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe25:b7f8/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:cd:a0:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
[root@wazuh-dashboard ~]#
```
**Wazuh server 1:**
```
[root@wazuh-server-1 ~]# ip a && cat /etc/os-release
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:cc:b7:ad brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 192.168.186.41/24 brd 192.168.186.255 scope global noprefixroute ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fecc:b7ad/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:cd:a0:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
[root@wazuh-server-1 ~]#
```

**Wazuh server 2:**
```
[root@wazuh-server-2 ~]# ip a && cat /etc/os-release
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:7e:3e:25 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 192.168.186.42/24 brd 192.168.186.255 scope global noprefixroute ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe7e:3e25/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:cd:a0:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
[root@wazuh-server-2 ~]#
```

**Wazuh indexer:**
```
[root@wazuh-indexer ~]# ip a && cat /etc/os-release
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens160: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:0c:29:61:06:f9 brd ff:ff:ff:ff:ff:ff
    altname enp3s0
    inet 192.168.186.43/24 brd 192.168.186.255 scope global noprefixroute ens160
       valid_lft forever preferred_lft forever
    inet6 fe80::20c:29ff:fe61:6f9/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:cd:a0:44 brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
NAME="AlmaLinux"
VERSION="8.10 (Cerulean Leopard)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.10 (Cerulean Leopard)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
SUPPORT_END=2029-06-01
[root@wazuh-indexer ~]#
```

**Wazuh agent:**
```

```

**Comment by GGP1** [comment] 2024-07-10 15:04
## Review

The test was marked as failed but there is not enough information to determine if the errors encountered were caused by a misconfiguration or an issue with the integration.

It's also worth mentioning that the last E2E from the 4.8.0 version was [successful](https://github.com/wazuh/wazuh/issues/21770) and there hasn't been any changes to the integration since then ([4.8.0-4.8.1-rc2 comparison](https://github.com/wazuh/wazuh/compare/v4.8.0...v4.8.1-rc2)).

Please document the Azure portal application setup and Microsoft Entra ID user creation step by step (remember obfuscating any sensitive information like credentials, workspaces, etc).

If you encounter any errors during the second iteration, please provide as much information about them as possible and open an issue with the details found.

> As a side note, I would also suggest wrapping the terminal outputs with 3 tilde characters ``` above and below instead of `<pre>` so it's easier to read.

**Comment by GGP1** [comment] 2024-07-11 18:04
## Review

The deployment and wazuh server tests look good to me. On the other hand, the agent dependency installation logs indicate that the package installed was `4.9.0-1` instead of `4.8.0-1`.

![agent_version](https://github.com/wazuh/wazuh/assets/51374959/13d6df47-635c-4956-bab5-e75c429bf52a)

> In one of the logs after, the `systemctl status wazuh-agent` shows `Starting Wazuh v4.8.1...`, but I think this was from the first iteration.

Could you repeat the agent tests with the package for this release candidate? This may be what is causing the error code 1.

**Comment by SamsonIdowu** [comment] 2024-07-12 12:37
> ## Review
> The deployment and wazuh server tests look good to me. On the other hand, the agent dependency installation logs indicate that the package installed was `4.9.0-1` instead of `4.8.1-1`.
> 
> ![agent_version](https://private-user-images.githubusercontent.com/51374959/347933913-13d6df47-635c-4956-bab5-e75c429bf52a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzkyNzYsIm5iZiI6MTcyMDc3ODk3NiwicGF0aCI6Ii81MTM3NDk1OS8zNDc5MzM5MTMtMTNkNmRmNDctNjM1Yy00OTU2LWJhYjUtZTc1YzQyOWJmNTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDEwMDkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZmQxNDA0ZTRjZjg2Yzc0N2ZmZmRkNTIwMzczNTk1ZWQwNDY2YjE5M2Y3ZTRlMmUxYzc2NDU1M2Y0YTU2NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IvcihVGdhd-bLdL8JkYmRuMJrOpdUJFI-tnfvbiw1jk)
> 
> > In one of the logs after, the `systemctl status wazuh-agent` shows `Starting Wazuh v4.8.1...`, but I think this was from the first iteration.
> 
> Could you repeat the agent tests with the package for this release candidate? This may be what is causing the error code 1.

I repeated the test using the release candidate. This time I made sure the agent package was not upgraded. However, the error code 1 still persists.

<img width="942" alt="image" src="https://github.com/user-attachments/assets/edb8352e-d34d-472c-ac54-5b0db88fc5bb">

**Comment by Rebits** [comment] 2024-07-12 15:33
The workspace has been leaked in the comments. I see this is not the first time it's happened in these issues; we need to be more careful about this.

I have obfuscated the sensitive information myself.

Other than that, LGTM.

**Closed by Rebits** 2024-07-12 15:33 UTC
Labels: type/test, level/subtask
