### ISSUE TITLE
Decoder dovecot didnt catch srcip

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh#1121] opened 2018-08-18 09:48 UTC
This is my Dovecot log from syslog looks like

`Aug 14 15:57:57 debian dovecot: imap-login: Aborted login (no auth attempts in 2 secs): user=<>, rip=someoneip, lip=myippublic, session=<2zBnkWBzwwBHBp6m>`

In my wazuh alerts, it's produce like this.
```
{
  "_index": "wazuh-alerts-3.x-2018.08.14",
  "_type": "wazuh",
  "_id": "X5RzN2UBFpFPX4oPPnnk",
  "_version": 1,
  "_score": null,
  "_source": {
    "full_log": "Aug 14 15:57:57 debian dovecot: imap-login: Aborted login (no auth attempts in 2 secs): user=<>, rip=someoneip, lip=myippublic, session=<2zBnkWBzwwBHBp6m>",
    "decoder": {
      "parent": "dovecot",
      "name": "dovecot"
    },
    "path": "/var/ossec/logs/alerts/alerts.json",
    "rule": {
      "pci_dss": [
        "10.2.4",
        "10.2.5"
      ],
      "id": "9707",
      "mail": false,
      "level": 5,
      "description": "Dovecot Aborted Login.",
      "groups": [
        "dovecot",
        "invalid_login",
        "gpg13_7.1"
      ],
      "firedtimes": 1
    },
    "manager": {
      "name": "debian"
    },
    "location": "/var/log/syslog",
    "host": "debian",
    "@timestamp": "2018-08-14T08:00:23.000Z",
    "id": "1534233623.512675",
    "agent": {
      "name": "Debian004",
      "ip": "192.168.56.204",
      "id": "004"
    },
    "predecoder": {
      "program_name": "dovecot",
      "timestamp": "Aug 14 15:57:57",
      "hostname": "debian"
    }
  },
  "fields": {
    "@timestamp": [
      "2018-08-14T08:00:23.000Z"
    ]
  },
  "highlight": {
    "rule.id": [
      "@kibana-highlighted-field@9707@/kibana-highlighted-field@"
    ],
    "agent.id": [
      "@kibana-highlighted-field@004@/kibana-highlighted-field@"
    ],
    "manager.name": [
      "@kibana-highlighted-field@debian@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1534233623000
  ]
}
```

But icouldnt see any srcip nor my public ip....

In syslog version, myippublic and someone ip appear, but in alerts it didint....
IS there anything wrong with my decoder ?

**Comment by gagantous** [comment] 2018-08-19 03:53
I have did some dig up about this and checked dovecot decoder, nad it's like syntax below for aborted login log line 

```
<decoder name="dovecot-aborted">
  <parent>dovecot</parent>
  <prematch offset="after_parent">^\w\w\w\w-login: Aborted login</prematch>
  <regex offset="after_prematch">: user=\p(\S+)\p, method=\S+, rip=(\S+), lip=(\S+), (\S*)$</regex>
  <order>user, srcip, dstip, protocol</order>
</decoder>

```

at regex offset section, we could see that the dovecot log should be contain `method=` while in my log file, it didnt exist.

`Aug 14 15:57:57 debian dovecot: imap-login: Aborted login (no auth attempts in 2 secs): user=<>, rip=someoneip, lip=myippublic, session=<2zBnkWBzwwBHBp6m>`

I have delete that `method=` but it still didnt catch and ip...

```
2018/08/19 11:51:52 ossec-testrule: INFO: Started (pid: 23106).
ossec-testrule: Type one log per line.

Aug 19 10:00:41 debian dovecot: pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=114.125.207.69, lip=182.23.83.29, session=<i2PyKMBzbAByfc9F>


**Phase 1: Completed pre-decoding.
       full event: 'Aug 19 10:00:41 debian dovecot: pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=114.125.207.69, lip=myip, session=<i2PyKMBzbAByfc9F>'
       timestamp: 'Aug 19 10:00:41'
       hostname: 'debian'
       program_name: 'dovecot'
       log: 'pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=114.125.207.69, lip=myip, session=<i2PyKMBzbAByfc9F>'

**Phase 2: Completed decoding.
       decoder: 'dovecot'

**Phase 3: Completed filtering (rules).
       Rule id: '9707'
       Level: '5'
       Description: 'Dovecot Aborted Login.'
**Alert to be generated.
```

**Comment by gagantous** [comment] 2018-08-19 04:29
I finally i made it. I changed my decoder to be like this

```
<decoder name="dovecot-aborted">
  <parent>dovecot</parent>
  <prematch offset="after_parent">^\w\w\w\w-login: Aborted login</prematch>
  <regex offset="after_prematch">user=(\S+), rip=(\S+), lip=(\S+),</regex>
  <order>user, srcip, dstip</order>
</decoder>
```

decoded it using ossec-logtest:

```
ossec-testrule: Type one log per line.

Aug 19 10:00:41 debian dovecot: pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=114.125.207.69, lip=182.23.83.29, session=<i2PyKMBzbAByfc9F>


**Phase 1: Completed pre-decoding.
       full event: 'Aug 19 10:00:41 debian dovecot: pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=114.125.207.69, lip=182.23.83.29, session=<i2PyKMBzbAByfc9F>'
       timestamp: 'Aug 19 10:00:41'
       hostname: 'debian'
       program_name: 'dovecot'
       log: 'pop3-login: Aborted login (no auth attempts in 1 secs): user=<>, rip=someoneip, lip=myippublic, session=<i2PyKMBzbAByfc9F>'

**Phase 2: Completed decoding.
       decoder: 'dovecot'
       dstuser: '<>'
       srcip: 'someoneip'
       dstip: 'myippublic'

**Phase 3: Completed filtering (rules).
       Rule id: '9707'
       Level: '5'
       Description: 'Dovecot Aborted Login.'
**Alert to be generated.

```

**Comment by vikman90** [comment] 2018-08-20 11:01
Hi @gagantous,

The problem is that those logs have an optional parameter: `protocol`. So the decoder expected that parameter and failed because it was not present.

I've fixed it in https://github.com/wazuh/wazuh-ruleset/pull/171. We will release it in the next version.

Thank you for reporting this bug!
Best regards.

**Comment by gagantous** [comment] 2018-08-20 11:36
Hi @vikman90 
Awesome! Thanks for the hard work

**Comment by vikman90** [comment] 2018-08-20 15:48
Hi,

I have also found a bug in the algorithm that set the `after_regex` offset. It makes the parameter `protocol` get an invalid value.

It has also been fixed. These are the results:

- _imap-login: Aborted login (auth failed, 2 attempts in 18 secs): user=<test>, method=PLAIN, rip=109.201.200.201, lip=67.205.141.203, session=<i8uMIAZEDrdtycjJ>_

> decoder: 'dovecot'
> dstuser: 'test'
> srcip: '109.201.200.201'
> dstip: '67.205.141.203'
> session: 'i8uMIAZEDrdtycjJ'

- _Dec 19 17:20:08 ny dovecot: imap-login: Aborted login (auth failed, 2 attempts in 18 secs): user=<test>, method=PLAIN, rip=109.201.200.201, lip=67.205.141.203, session=<i8uMIAZEDrdtycjJ>, secured_

> decoder: 'dovecot'
> dstuser: 'test'
> srcip: '109.201.200.201'
> dstip: '67.205.141.203'
> session: 'i8uMIAZEDrdtycjJ'
> protocol: 'secured'

- _Dec 19 17:20:08 ny dovecot: imap-login: Aborted login (auth failed, 2 attempts in 18 secs): user=<test>, method=PLAIN, rip=109.201.200.201, lip=67.205.141.203, secured_

> decoder: 'dovecot'
> dstuser: 'test'
> srcip: '109.201.200.201'
> dstip: '67.205.141.203'
> protocol: 'secured'

- _Dec 19 17:20:08 ny dovecot: imap-login: Aborted login (auth failed, 2 attempts in 18 secs): user=<test>, method=PLAIN, rip=109.201.200.201, lip=67.205.141.203_

> decoder: 'dovecot'
> dstuser: 'test'
> srcip: '109.201.200.201'
> dstip: '67.205.141.203'

Best regards.

**Comment by vikman90** [comment] 2018-08-22 09:04
Hi @gagantous,

This issue has been fixed. Let me close it.

Thank you again.
Best regards.

**Closed by vikman90** 2018-08-22 09:04 UTC
Labels: bug, needs ruleset
