### ISSUE TITLE
When audit rules are locked, log (once) all rules which fail insertion

### ISSUE THREAD

**Issue by kpinc** [wazuh/wazuh#6392] opened 2020-10-22 19:02 UTC
|3.13.2|syscheck|?|?|Ubuntu 18.4.5|

Enhancement request.

We are using wazuh-agent 3.13.1-1, on Ubuntu 18 using the cloud Wazuh service.

The DSS PCI rules suggest locking the auditd rules with "-e 2".  But
if you do this then the FIM monitor cannot write auditd rules to audit
files.

It would be nice for Wazuh to log (once) all the rules that fail
insertion when the rules are locked with -e 2.  That way, the user
knows what rules Wazuh wants.  If the user updates the config so that
the automatically inserted rules change then the new rules should be
logged (once).

This should also be done for the health check rule.

**Comment by jesusjimsa** [comment] 2020-10-23 07:22
I'm closing this issue as it is a duplicate of #6393.

**Closed by jesusjimsa** 2020-10-23 07:23 UTC
Labels: community, core/fim, core/fim/whodata, duplicate, platform/unix
