### ISSUE TITLE
Investigate JSONDecodeError when forwarding request to a node

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#10360] opened 2021-09-30 14:29 UTC
|Wazuh version|Component|
|---|---|
| 4.3.0 | Distributed API |

As it was detailed in the issue https://github.com/wazuh/wazuh/issues/10212, there is a possible `JSONDecodeError` when try to load the result of sending a `dapi_fwd` command as JSON.

In the issue #10212, we included the possibility to handle this error once it appears. 
In this issue, we should investigate the origin of that `Exception` and try to include a fix for it.

The logs we can see in the api.log when this Exception is raised are the followings (without handling the JSONDecodeError):

```
2021/09/20 11:12:06 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2021/09/20 11:12:06 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2021/09/20 11:12:06 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2021/09/20 11:12:13 INFO: Listening on 0.0.0.0:55000..
2021/09/20 11:18:18 INFO: Listening on 0.0.0.0:55000..
2021/09/20 11:35:36 INFO: wazuh 172.31.32.158 "GET /security/user/authenticate" with parameters {} and body {} done in 0.546s: 200
2021/09/20 11:36:10 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 157, in distribute_function
    response = await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 514, in forward_request
    response = await asyncio.shield(asyncio.gather(*[forward(node) for node in cleaned_valid_nodes]))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.3.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 423, in forward
    result = json.loads(await client.execute(b'dapi_fwd',
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021/09/20 11:36:10 INFO: wazuh 172.31.32.158 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 999999} done in 34.930s: 500
```

This happens in the `forward` function of the `forward_request` Distributed API class method:

https://github.com/wazuh/wazuh/blob/18b698f7f7600568e48e5bcc1ff9738d2392c63a/framework/wazuh/core/cluster/dapi/dapi.py#L385-L449

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by yanazaeva** [comment] 2021-11-22 09:02
## Issue update

The error mentioned above appears whenever the input value in the `json.loads` method is empty or using an incorrect format:
- Wrong format:
```
>>> json.loads('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>>> json.loads('a')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
- Correct format:
```
>>> json.loads('""')
''
>>> json.loads('"a"')
'a'
```

If we follow the trace of this error, we can see that it is produced in the `forward` function, which is nested in the `forward_request` method, that belongs to the `DistributedAPI` class. We can see that in the `json.loads` method we are calling the method `client.execute`, which belongs to the `LocalClient` class. In this method, we call the `send_api_request` method in order to return a `result` value. If we go to this latest method, we can see the output value in this method is returned by the `protocol` attribute, which also calls an attribute called `response`. The former attribute belongs to the LocalClientHandler class, meanwhile, the latter is initialized as `b''`, which could be causing the error seen above. If we check the error once again, we can see that almost 35 seconds have passed since the request, so this is probably due to a timeout happening in these lines: 
https://github.com/wazuh/wazuh/blob/e9ceabeb4f3d1c29b0e94a8fb8f487bf1a3647bb/framework/wazuh/core/cluster/local_client.py#L182-L188

**Comment by yanazaeva** [comment] 2022-03-15 13:40
## Issue update

This issue was finally replicated by modifying the [`execute`](https://github.com/wazuh/wazuh/blob/ac19a04670f1f8c36c58b8871baaa352e71f5556/framework/wazuh/core/cluster/local_client.py#L194) method present in [LocalClient](https://github.com/wazuh/wazuh/blob/master/framework/wazuh/core/cluster/local_client.py) class: 
```PYTHON3
        await self.start()
        result = await self.send_api_request(command, data, wait_for_complete)
        sleep(30) # From time
        self.transport.close()
        await self.protocol.on_con_lost
        return result
````

If we restart the cluster after this change and run the following queries: 
```
TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")
curl -k -X PUT "https://localhost:55000/security/config" -H "Authorization: Bearer $TOKEN" -d '{"auth_token_exp_timeout":99999}' -H "Content-Type: application/json"
```
We should be able to see the Exception mentioned above:
```
2022/03/15 09:19:55 INFO: Listening on 0.0.0.0:55000..
2022/03/15 09:20:11 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.339s: 200
2022/03/15 09:22:14 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 159, in distribute_function
    response = await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 548, in forward_request
    response = await asyncio.shield(asyncio.gather(*[forward(node) for node in cleaned_valid_nodes]))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 457, in forward
    result = json.loads(await client.execute(b'dapi_fwd',
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/03/15 09:22:14 INFO: wazuh 127.0.0.1 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 99999} done in 120.810s: 500
```

This error can be seen only after the simultaneous restart of all of the managers. If we execute the queries mentioned above a second time without restarting, the request is properly handled: 
- Executing the request a second time:
```
2022/03/15 12:32:11 INFO: Listening on 0.0.0.0:55000..
2022/03/15 12:32:23 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.351s: 200
2022/03/15 12:34:26 ERROR: Unhandled exception: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 159, in distribute_function
    response = await self.forward_request()
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 548, in forward_request
    response = await asyncio.shield(asyncio.gather(*[forward(node) for node in cleaned_valid_nodes]))
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.4.0-py3.9.egg/wazuh/core/cluster/dapi/dapi.py", line 457, in forward
    result = json.loads(await client.execute(b'dapi_fwd',
  File "/var/ossec/framework/python/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2022/03/15 12:34:26 INFO: wazuh 127.0.0.1 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 99999} done in 120.772s: 500
2022/03/15 12:35:03 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.293s: 200
2022/03/15 12:37:05 INFO: wazuh 127.0.0.1 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 99999} done in 120.361s: 200
```
- Restarting the workers first and then the manager:
```
2022/03/15 12:38:30 INFO: Listening on 0.0.0.0:55000..
2022/03/15 12:38:37 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {"raw": "true"} and body {} done in 0.354s: 200
2022/03/15 12:38:39 WARNING: 1: {"items": [{"name": "wd-ar_manager_1", "type": "master", "version": "4.4.0", "ip": "wd-ar_manager_1"}, {"name": "e960f8d2d55a", "type": "worker", "version": "4.4.0", "ip": "172.19.0.3"}], "totalItems": 2}
2022/03/15 12:39:09 WARNING: 2: {"items": [{"name": "wd-ar_manager_1", "type": "master", "version": "4.4.0", "ip": "wd-ar_manager_1"}, {"name": "e960f8d2d55a", "type": "worker", "version": "4.4.0", "ip": "172.19.0.3"}], "totalItems": 2}
2022/03/15 12:39:09 WARNING: 1: {"items": [{"name": "wd-ar_manager_1", "type": "master", "version": "4.4.0", "ip": "wd-ar_manager_1"}, {"name": "e960f8d2d55a", "type": "worker", "version": "4.4.0", "ip": "172.19.0.3"}], "totalItems": 2}
2022/03/15 12:39:39 WARNING: 2: {"items": [{"name": "wd-ar_manager_1", "type": "master", "version": "4.4.0", "ip": "wd-ar_manager_1"}, {"name": "e960f8d2d55a", "type": "worker", "version": "4.4.0", "ip": "172.19.0.3"}], "totalItems": 2}
2022/03/15 12:39:40 WARNING: 1: {"__wazuh_result__": {"__class__": "WazuhResult", "__object__": {"str_priority": null, "result": {"result": "True"}}}}
2022/03/15 12:40:10 WARNING: 2: {"__wazuh_result__": {"__class__": "WazuhResult", "__object__": {"str_priority": null, "result": {"result": "True"}}}}
2022/03/15 12:40:10 INFO: wazuh 127.0.0.1 "PUT /security/config" with parameters {} and body {"auth_token_exp_timeout": 99999} done in 90.746s: 200
```

This error is triggered due to a timeout produced here: 
https://github.com/wazuh/wazuh/blob/76ddc1341326e9e8cd06d8579f52380ee0903bd5/framework/wazuh/core/cluster/common.py#L475-L477

When this timeout takes place, this method returns an `Error sending request: timeout expired`. This message is returned to the [`send_api_request`](https://github.com/wazuh/wazuh/blob/ac19a04670f1f8c36c58b8871baaa352e71f5556/framework/wazuh/core/cluster/local_client.py#L157) method, and goes into the following condition: https://github.com/wazuh/wazuh/blob/ac19a04670f1f8c36c58b8871baaa352e71f5556/framework/wazuh/core/cluster/local_client.py#L177-L192
returning directly the message shown above. This is received by the `execute` method mentioned before and forwarded back again to the `forward` function: https://github.com/wazuh/wazuh/blob/76ddc1341326e9e8cd06d8579f52380ee0903bd5/framework/wazuh/core/cluster/dapi/dapi.py#L457-L463

Once here, a WazuhResult dictionary is expected, but instead `json.loads` tries to parse the error string mentioned above, thus failing and raising the JSONDecodeError.

Currently, this exception is handled as a `JSONDecodeError`, but it seems that the best way would be to handle this as a TimeoutError instead, and do it before the `JSONDecodeError` is produced:
https://github.com/wazuh/wazuh/blob/ac19a04670f1f8c36c58b8871baaa352e71f5556/framework/wazuh/core/cluster/dapi/dapi.py#L175-L181

**Comment by davidjiglesias** [comment] 2022-07-06 08:19
Better exception handling included in https://github.com/wazuh/wazuh/issues/10212, if it happens again, we would have a better chance to reproduce it. We have not been able to reproduce it as it is, closing this.

**Closed by davidjiglesias** 2022-07-06 08:19 UTC
Labels: type/bug, module/cluster, module/api

**Comment by FoxDcx** [comment] 2025-08-04 08:35
@davidjiglesias I've been facing the same error recently.
For me it came from the fact that when I changed application' secrets (I used password auto generated by a vault manager) and they includes some special characters.
Causing the JSONdecodeError to be raised.

`'/wazuh-config-mount/etc/authd.pass' -> '/var/ossec/etc/authd.pass'
sed: -e expression #1, char 71: unterminated s' command [cont-init.d] 0-wazuh-init: exited 0. [cont-init.d] 1-config-filebeat: executing...  Customize Elasticsearch output IP Configuring username. sed: -e expression #1, char 38: unterminated s' command
[cont-init.d] 1-config-filebeat: exited 1.
[cont-init.d] 2-manager: executing... 
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/create_user.py", line 69, in < module >
    username, password = read_user_file()
  File "/var/ossec/framework/scripts/create_user.py", line 31, in read_user_file
    data = json.load(user_file)
  File "/var/ossec/framework/python/lib/python3.10/json/init.py", line 293, in load
    return loads(fp.read(),
  File "/var/ossec/framework/python/lib/python3.10/json/init.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/var/ossec/framework/python/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/ossec/framework/python/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 2 column 25 (char 26)`
