### ISSUE TITLE
wazuh-logtest does not report missing list

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh#14205] opened 2022-07-11 12:02 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.5-40317 | wazuh-logtest | Manager | Packages | any |

If a rule references a list which does not exist or is not adequately configured on the manager's `ossec.conf` the API's `PUT /logtest` endpoint correctly warns about this but the `/var/ossec/bin/wazuh-logtest` does not.

That is, for example, if one adds the following rule:
```
  <rule id="100014" level="3">
    <list field="srcip">etc/lists/non-existing-list</list>
    <description>Rule with a list that does not exist (testing)</description>
  </rule>
```
and forgets to create or configure the list, then the API call:
```
PUT /logtest
{
  "log_format": "syslog",
  "location": "logtest",
  "event": "test"
}
```
Correctly results in:
```
{
  "error": 0,
  "data": {
    "messages": [
      "WARNING: (7616): List 'etc/lists/non-existing-list' could not be loaded. Rule '100014' will be ignored.",
      "INFO: (7202): Session initialized with token '48879b1c'"
    ],
    "token": "48879b1c",
    "output": {
      "timestamp": "2022-07-11T11:58:01.038000Z",
      "agent": {
        "id": "000",
        "name": "wazuh43"
      },
      "manager": {
        "name": "wazuh43"
      },
      "id": "1657540681.31950",
      "full_log": "test",
      "decoder": {},
      "location": "logtest"
    },
    "alert": false,
    "codemsg": 1
  }
}
```
where `wazuh-logtest` results in:
```
/var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.3.5
Type one log per line

test

**Phase 1: Completed pre-decoding.
	full event: 'test'

**Phase 2: Completed decoding.
	No decoder matched.
```

It is expected that `wazuh-logtest` should provide the same verbosity as the API so its users may correctly assess the functionality of their current configuration. 

The verbosity modifier (`-v`) does not provide further insight.

**Comment by vikman90** [comment] 2022-08-25 10:33
@jctello I think this is a duplicate of #10785, fixed in 4.4.0.

## Test

```shell
service wazuh-manager start
cp local_rules.xml /var/ossec/etc/rules
echo "test" | wazuh-logtest
```

### Result in 4.3.7

```
Starting wazuh-logtest v4.3.7
Type one log per line


**Phase 1: Completed pre-decoding.
        full event: 'test'

**Phase 2: Completed decoding.
        No decoder matched.
```

### Result in 4.4.0 (development)

```
Starting wazuh-logtest v4.4.0
Type one log per line


** Wazuh-Logtest: WARNING: (7616): List 'etc/lists/non-existing-list' could not be loaded. Rule '100014' will be ignored.

**Phase 1: Completed pre-decoding.
        full event: 'test'

**Phase 2: Completed decoding.
        No decoder matched.
```

Let me close this issue.
Best.

**Closed by vikman90** 2022-08-25 10:33 UTC
Labels: reporter/operations, module/analysis/logtest
