### ISSUE TITLE
4.3.5 Windows agent crashes with msvcrt error

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh#14353] opened 2022-07-19 11:28 UTC
|Wazuh version|Component|
|---|---|
| 4.3.5 | Windows agent (2019) |

## Crash log
```python
Faulting application name: wazuh-agent.exe, version: 0.0.0.0, time stamp: 0x62b4c20d
Faulting module name: msvcrt.dll, version: 7.0.17763.475, time stamp: 0xba51b082
Exception code: 0xc0000005
Fault offset: 0x0008ac4c
Faulting process id: 0x12ac
Faulting application start time: 0x01d89acd38747ac0
Faulting application path: C:\Program Files (x86)\ossec-agent\wazuh-agent.exe
Faulting module path: C:\Windows\System32\msvcrt.dll
Report Id: eba7e6eb-fd85-4f02-ba12-cd127db54c40
Faulting package full name: 
Faulting package-relative application ID: 
```

## Context
* Windows 2019 (current rev) running Oracle database (with its dependency fun likely being the cause here)
* Crash occurred roughly 18h after agent deployment - deployed as 4.3.5 (no upgrades)
* Deployment is effected via the MSI using a batch file in Group Policy

## Proposed solution vector
* Offsec folks have dealt with this mess by including an object file in payload compilation which statically links the required msvcrt functions into the PE/DLL' built. https://github.com/neosmart/msvcrt.lib and similar.

**Comment by jotacarma90** [comment] 2022-07-19 14:21
Hello @sempervictus 
To start debugging the problem it would be very helpful to have the agent's configuration and log files (ossec.log from agent). It can be the first step to reproduce it, knowing the module that is giving problems, and finding the reason.
You can get the configuration through the API:

- Get the authentication token: `TOKEN=$(curl -u <user>:<password> -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")`
- Request the configuration to the API: `curl -u '<user>:<password>' -k -X GET 'https://localhost:55000/agents/<agent_id>/config/syscheck/syscheck' -H "Authorization: Bearer $TOKEN"`

Thanks and best regards!

**Comment by Dwordcito** [comment] 2022-07-20 00:43
The segfault is occurring in a call to strlen, unfortunately, the information on the issue is insufficient,

I would like to know if you could reproduce this error again, to indicate how you can send us enough information to reconstruct the backtrace and see the tree of calls to identify which part of the code causes the error.

https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps
wazuh-agent.exe is the application name.

------------------

![image](https://user-images.githubusercontent.com/14300208/179871102-f7662df6-d899-487e-9b79-f05456b802c6.png)


```
Microsoft (R) Windows Debugger Version 10.0.22621.1 X86
Copyright (c) Microsoft Corporation. All rights reserved.
 
 
Loading Dump File [C:\Users\vagrant\Downloads\depends22_x86\msvcrt.dll]
Symbol search path is: srv*
Executable search path is: 
ModLoad: 10100000 101c0000   C:\Users\vagrant\Downloads\depends22_x86\msvcrt.dll
eax=00000000 ebx=00000000 ecx=00000000 edx=00000000 esi=00000000 edi=00000000
eip=10136c80 esp=00000000 ebp=00000000 iopl=0         nv up di pl nz na po nc
cs=0000  ss=0000  ds=0000  es=0000  fs=0000  gs=0000             efl=00000000
msvcrt!_CRTDLL_INIT:
10136c80 8bff            mov     edi,edi
0:000> lm
start    end        module name
10100000 101c0000   msvcrt     (pdb symbols)          C:\Program Files (x86)\Windows Kits\10\Debuggers\x86\sym\msvcrt.pdb\63C33283589EF68854C9D8A0657AE3A71\msvcrt.pdb
0:000> ln 10100000+8ac4c
Browse module
Set bu breakpoint
 
(1018ac40)   msvcrt!strlen+0xc   |  (1018acd0)   msvcrt!strncat
```

**Comment by sempervictus** [comment] 2022-07-20 02:01
This is on a production system running Oracle's DB - the mere mention of debuggers in a 50 meter radius of the thing might produce a plague of lawyers and other amphibians not seen since the time of Moses... :wink: 

Unfortunately i do not have the ability to collect on that specific host, but we do have sysmon running there so if you have any way to leverage that for relevant collection, i'm all ears (they can't really complain about a Microsoft component running on the system).

**Comment by sempervictus** [comment] 2022-07-20 02:37
Inventory shows that the stack on-host deployed a slew of these runtimes:
![image](https://user-images.githubusercontent.com/1331084/179884038-abd25410-7262-4911-b4b9-8ac03e48a810.png)

**Comment by vikman90** [comment] 2022-07-20 10:14
Wondering if this issue might be related to #10692.

**Comment by jotacarma90** [comment] 2022-07-20 12:38
Analyzing the data we only know that there has been a bug in the msvcrt library, although it is a bug that occurs in the Wazuh agent most likely.
Since it is a bug unknown to us so far, to narrow it down we would be greatly helped by any data from the environment that helps us to identify it, or find a reliable way to reproduce it. For now, the info that would help us the most is:

- `ossec.log` file of the agent in the timeframe of the crash.
- `ossec.conf` file of the agent to know which modules are enabled and thus be able to rule out causes.

**If these documents contain sensitive information**, we ask you to hide it or send us the data privately.
If this is not possible, you could try to narrow down the problem by analyzing which Wazuh module is causing it. For example, disabling one module at a time until the crash disappears.

Regarding the issue mentioned https://github.com/wazuh/wazuh/issues/10692, there is some possibility that it is related, so to rule it out, you could take a look at it and compare the environments, the most relevant was a very large amount of monitored files. Any clues could be helpful.

On the other hand, in 4.4.0 we are going to incorporate more mechanisms so that when a crash happens in the agent it indicates us with more precision the cause (https://github.com/wazuh/wazuh/issues/9913). So this kind of situations will be more easily solvable.

Thank you!

**Comment by jotacarma90** [comment] 2022-08-03 07:24
hi @sempervictus,

Are you still having this issue? We’d really appreciate it if you could help us to find and fix this problem. Any clues would be appreciated.

Thanks!

**Comment by sempervictus** [comment] 2022-08-03 15:58
Its intermittent, has happened 2 more times in the last week, and with so many MSVC installations on the system, it is not surprising. I cannot run debuggers on the system or do anything to it really without violating the environment's Oracle license agreement - i asked, was denied by system owner, there's nothing more i can do with this specific host's situation other than run an agent upgrade by push or GPO.

I created an issue outlining how you guys can avoid this _class_ of concern moving forward: #14467 
The fact that Windows will load the _first_ viable DLL it finds to match your `loadLibrary()` call makes it nearly impossible for you to prevent having something in your PID's memory space which _could_ have different code than what you linked against at build-time but presenting the same symbols. Outside of strict static builds carrying all of your own code, you end up running someone else's code, and there's just too much variance on-target to be **sure** which ABI of that code you are calling at runtime.
If you don't want to go the static route, you can implement your own library loader, but thats the sort of thing my kind do and could well flag you on EDR for memory manipulation techniques.

**Comment by vikman90** [comment] 2024-04-30 09:45
We will proceed to close this issue as we were unable to pinpoint the root cause of the problem, and it has not been reported again in versions after 4.3.5 (currently at 4.7.4).

Furthermore, we anticipate having a more robust bug tracking tool with #9913.

Thank you.

**Closed by vikman90** 2024-04-30 09:45 UTC
Labels: type/bug, platform/windows, type/bug/crash, level/task
