### ISSUE TITLE
Double syscheck alert with arch="both" field

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh#4262] opened 2019-11-20 15:51 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 10.0.2 | syscheck | winAgent | Packages/Sources | OS version |

Double alert in syscheck when using the `arch="both"` field when monitoring windows registries. 

## Example

`ossec.conf`
```
<!-- Frequency that syscheck is executed default every 12 hours -->
    <frequency>10</frequency>
    . . . 
    <!-- Windows registry entries to monitor. -->
    <windows_registry arch="both">HKEY_LOCAL_MACHINE\HARDWARE</windows_registry>
```

Using the above configuration, each time a registry is created, modified, or deleted, the syscheck alert appears twice, for 32 and 64 bits.

`output`
```
** Alert 1574257273.782584: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Nov 20 14:41:13 (vm-win7) 10.0.0.7->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '[x32] HKEY_LOCAL_MACHINE\Hardware\jk' added
Mode: scheduled
Event time: 11/20/19 14:41:13
Attributes:
 - Date: Wed Nov 20 14:41:12 2019
 - SHA256: a74a0576f1adea197821596a20514f86e89a84f2388b41c15abf9b948638c635
** Alert 1574257273.783058: - ossec,syscheck,pci_dss_11.5,gpg13_4.11,gdpr_II_5.1.f,hipaa_164.312.c.1,hipaa_164.312.c.2,nist_800_53_SI.7,
2019 Nov 20 14:41:13 (vm-win7) 10.0.0.7->syscheck
Rule: 554 (level 5) -> 'File added to the system.'
File '[x64] HKEY_LOCAL_MACHINE\Hardware\jk' added
Mode: scheduled
Event time: 11/20/19 14:41:13
Attributes:
 - Date: Wed Nov 20 14:41:12 2019
 - SHA256: a74a0576f1adea197821596a20514f86e89a84f2388b41c15abf9b948638c635
```

This should not happen unless it is a registry of the following:  https://docs.microsoft.com/es-es/windows/win32/winprog64/shared-registry-keys

In the previous case, register X has been monitored, and it is not in the table, so this double alert should not be generated.

**Comment by vikman90** [comment] 2020-01-08 09:40
Hi @JcabreraC,

We should count this list of redirected keys and make this classification automatically by the agent:
https://docs.microsoft.com/en-us/windows/win32/winprog64/shared-registry-keys

This could let us deprecate option `<arch>`.

Cheers!

**Comment by antoniomanuelfr** [comment] 2020-07-22 11:21
Hi team.
After making a deep research about the behavior of syscheck on the Windows registries, we decided to close this issue.
The problem was caused because of the type of registries that are on Windows:
- Shared registries: These registries are shared for both architectures (32-bits and 64-bits).
- Redirected registries: The registry of 32-bit is isolated from the registry of 64-bit and Windows makes the conversion (transparently to the application) to the right physical registry.
This means that the only way to detect if a registry is redirected or shared is hardcoding all the registries that are in the list that was mentioned in the previous comment. The problem is that this behavior changes between Windows versions, architectures and in some cases, a redirected registry can be shared if a value inside the registry is an empty string.
Hardcoding all the cases is not a proper solution from this problem. 

The solution is to select properly the registries are monitored using the option arch=both.
For example, if we want to monitor a redirected key like  ` HKEY_LOCAL_MACHINE\SOFTWARE\Classes\DirectShow`, the option arch=both is required. Like this, the 32-bit and 64-bit alerts will be generated.
If we want to monitor a shared registry like HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\COM3, and we specify the arch=both option, it will generate 2 alerts, one for the 64-bit registry and other for the 32-bit registry but this alert will have the same SHA1. If we want to avoid that syscheck generate two alerts for this registry, the option arch must be omitted or be set to either 32-bit or 64-bit.

Kind regards.

**Closed by antoniomanuelfr** 2020-07-22 11:21 UTC
Labels: core/fim, enhancement, platform/windows
