### ISSUE TITLE
wazuh-authd gives `SSL Error (0)` on Footprint tests 

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh#18973] opened 2023-09-12 08:56 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-alpha1 | wazuh-authd | Manager | Packages | CentOS |

On the footprint tests for `4.6.0-alpha1` a new error has appeared in the logs from the `wazuh-authd`. 

The error:
```
wazuh-authd ERROR: SSL Error (0)
```

Full logs and configurations from the manager:
https://ci.wazuh.com/data/Test_stress/pre-release/4.6.0/B4310-3600m/B4310_agent_centos/logs/ossec_Test_stress_B4310_centos_2023-09-10.zip

**Comment by vikman90** [comment] 2023-09-12 09:01
This issue is a duplicate of https://github.com/wazuh/wazuh/issues/15021, related to https://github.com/wazuh/wazuh/issues/13936. We decided not to implement them.

**Comment by vikman90** [comment] 2023-09-13 15:14
Removing from 4.6.0 as it's not a stopper because the bug was caused many versions ago.
Setting the objective to _low impact bugs_.

**Comment by TomasTurina** [comment] 2024-04-16 19:48
The modules involved will be refactored, so this issue will not be addressed.

**Closed by TomasTurina** 2024-04-16 19:48 UTC
Labels: type/bug, level/task
