### ISSUE TITLE
Agent's upgrade via WPK rollback sometimes fails 

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#11257] opened 2021-12-08 21:07 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0 | WPK Agent Upgrade | Agent | WPK | Windows Server 2016 |

On a Wazuh agent version 4.3.0, when forcing an `Agent's upgrade via WPK rollback`, from time to time, the file restoring process fails. The backup files get lost and the `ossec.conf` file is then misconfigured, so the agent is not able to connect to the manager. It is important to notice that the rollback was tested several times and it did not always fail.

It was possible to test that this only happens when previously upgrading from a former Wazuh version, such as 4.2.5 or 4.0.4, to 4.3.0 through WPK and then forcing the rollback. The error does not occur when manually upgrading an agent to 4.3.0 vía `msi`.

The previously described error happened when using the following VM configuration:

```ruby
Vagrant.configure("2") do |config|
  
  config.vm.box = "jacqinthebox/windowsserver2016"
  config.vm.hostname = "200-131-ws16-agent"
  config.vm.box_version = "1.4"
  config.vm.define "200-131-ws16-agent"
  
  config.vm.network "private_network", name: "vboxnet1", ip: "192.168.200.131"
 
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "4096"
     vb.name = "200-131-ws16-agent"
     vb.cpus = 6
     vb.customize ["modifyvm", :id, "--vram", "256"]
  end

end
```

This same VM was tested in different computers with different results, so it may be tricky to reproduce. This behavior was seen on an Intel machine, but could not be reproduced on an AMD one.

To force the rollback it is necessary to modify the `do_upgrade.ps1`. To do so, on [**this line**](https://github.com/wazuh/wazuh/blob/d1a05b607f260d168d38088b13c1c703fa787908/src/win32/do_upgrade.ps1#L274), the `status` variable should be set to `$null`.

Best Regards,

Koremblum Mariano

**Comment by alromeros** [comment] 2021-12-24 14:23
**#11257 upgrade:**

Hi team,

After performing intensive testing, we can confirm the presence of the bug described in this issue. However, the cause of the bug itself is still unknown.

We've gathered relevant information through the following testing:

## Steps to replicate the bug

1. Install an agent with a version previous to v4.3 in the affected Windows machine. We've tested both v4.2.5 and v4.2.0

2. Connect the agent to a Wazuh manager.

3. Apply an upgrade via **WPK** to v4.3.

4. Prepare the upgrade that'll force the rollback. To do it,  we've used a custom WPK with the `status` variable modified as `$null` in `do_upgrade`, as mentioned in the description.

5. Perform the upgrade to force the rollback until the bug is replicated.

6. When the bug is replicated, the manager should freeze, as it cannot connect with the agent since the agent's configuration has not been restored correctly.

## Machine-related testing

After trying to replicate the bug in different Windows OS, we have only managed to replicate it in a custom **Windows Server 2016** virtual machine with the same specs as the one described in this issue.

The list of virtual machines where it has been tested is:

- [x] **Windows Server 2012**.
- [x] **Windows Server 2016 (other than custom VM)**.
- [x] **Windows Server 2019**.
- [x] **Windows 10**.
- [x] **Windows 11**.

## Log analysis

For log analysis, we have compared different logs after successfully replicating the bug and after an expected rollback to v4.3.

- [x] **upgrade.log:**

`upgrade.log` output is successful in both cases, and it always looks as follows:

```
2021/12/23 16:25:01 wazuh-agent: INFO: Found (WazuhSvc) service is not running.
2021/12/23 16:25:01 wazuh-agent: INFO: Successfully removed (WazuhSvc) from the service database.
2021/12/23 16:25:01 wazuh-agent: INFO: Successfully added to the service database.
2021/12/23 16:25:01 wazuh-agent: ERROR: (4112): Invalid server address found: '0.0.0.0'
2021/12/23 16:25:01 wazuh-agent: CRITICAL: (1215): No client configured. Exiting.
2021/12/23 16:25:01 wazuh-agent: INFO: Received exit signal. Starting exit process.
2021/12/23 16:25:01 wazuh-agent: INFO: Set pending exit signal.
2021/12/23 16:25:01 wazuh-agent: INFO: Exit completed successfully.
```

- [x] **ossec.log:**

The agent's `ossec.log` file remains empty when the bug is replicated, while the manager's one provides a successful output. 

However, the manager's one lacks the next log message:

>wazuh-modulesd:agent-upgrade[366346] wm_agent_upgrade_commands.c:187 at wm_agent_upgrade_process_agent_result_command(): INFO: (8164): Received upgrade notification from agent '14'. Error code: '2', message: 'Upgrade failed'

Other than that, the logs seem to be successful in both cases.

- [x] **installer.log:**

 This log's output is also successful in cases with and without the bug. 

- [x] **uninstall.log** custom log:

We've also used a modified `.msi` package that outputs a new log with information about the uninstalling process. However, this process has been apparently successful in both cases.

## Code analysis

We have also reviewed the logic of both the scripts and source code related to the upgrade process, focusing especially on the changes introduced in v4.3.

- [x] **do_upgrade.ps1:**

Since the bug seems to be related to the process of restoring the files during the upgrade process, we consider this script to be the most suspicious one. However, we haven't been able to find anything wrong with it.

- [x] **agent_upgrade** module: 

The`agent_upgrade` module remains largely unchanged from previous versions. This, together with the fact that its workflow seems to be properly working, makes us discard it as the cause of the problem.

- [x] **InstallerScripts.vbs** and **RemoveAllScripts.vbs**:

These scripts involve suspicious file management, but we've not been able to see anything dangerous on them.

## Conclusions

After carefully reviewing the bug's behavior, we suspect that it may be caused during the `do_upgrade` process, mainly after restoring the files saved in the `/backup` folder. 

We suspect that, after the upgrade attempt crashes, the configuration files (`ossec.conf`, `internal_options.conf` and `local_internal_options.conf`) are restored by default, without obtaining the previous configuration and therefore, with an invalid manager IP (`0.0.0.0`) so that it is not possible to connect with it and finish the update process by **WPK**.

We'll keep updating this issue whenever we find something relevant about the bug.
Best regards.

**Comment by vikman90** [comment] 2022-01-11 11:46
Wondering if this issue may be related to #11566 and #11442, fixed for the upcoming RC3.

**Comment by alromeros** [comment] 2022-01-12 13:51
**#11257 update:**

Hi team,

We've also been able to replicate the bug after testing with custom **WPK**s including the fixes merged in https://github.com/wazuh/wazuh/pull/11736, meaning that https://github.com/wazuh/wazuh/issues/11566 and https://github.com/wazuh/wazuh/issues/11442 may not be completely related to this issue.

That said, the bug seems to be replicated much less frequently than with the previous, unfixed **WPK**s: The error has been only replicated twice after following the replication steps more than 30 times, while the unfixed **WPK**s usually took around 5 times between each replication.

We will update the issue as soon as we find any relevant information.
Best regards.

**Comment by alromeros** [comment] 2022-01-25 12:28
**#11257 update:**

Hi team,

Again, after performing intensive testing, we've not been able to find the cause of this bug yet.

That said, we've come to reach several conclusions:

- We confirm that the factors that contribute to the appearance of this bug are extremely specific: The bug has only been replicated with the exact same machine and steps described in the issue. Every other test has been unsuccessful.
- Since the fixes described by @Vikman90 in his previous message were introduced, the replicability of the bug has decreased considerably: After a whole day of testing, we've not been able to replicate the error again once. That said, the bug stills appear every once in a while with the previous **WPK**.
- The consequences of the bug are still somewhat negligible, especially considering the very specific conditions needed for it to occur.

As always, we'll keep updating this issue whenever we find something relevant about the bug.
Best regards.

**Closed** 2022-01-26 10:32 UTC
Labels: bug, packages/wpk, upgrade, platform/windows, status/stopped investigating
