### ISSUE TITLE
Rootcheck database inconsistencies

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#23477] opened 2024-05-16 19:07 UTC
## Description

During the investigation in https://github.com/wazuh/wazuh/issues/23389, we found that in 4.9.0 our test cases are failing sporadically because the agents' rootcheck databases are empty even though their logs indicate that the scans have finished.

I tried sleeping for two minutes before starting the test to see if it was a race condition but the database remained empty after multiple scans. In some other executions, even without a sleep, the database did contain the scan results.

> Our agent healtcheck waits 30 seconds after the shared configuration is modified to consider it healthy. So before 4.9.0 the results were stored within this time frame.

We haven't noticed this behavior in previous versions, so we should investigate if there is any issue while populating the database or with the scan itself not finding results.

Logs: [rootcheck_logs.zip](https://github.com/wazuh/wazuh/files/15339796/rootcheck_logs.zip)

**Comment by vikman90** [comment] 2024-05-17 10:00
@GGP1 I've checked that all agents have logs like:

> 2024/05/16 18:21:57 rootcheck: INFO: Starting rootcheck scan.
> 2024/05/16 18:22:05 rootcheck: INFO: Ending rootcheck scan.

On the other hand, I see the tables populated.

## Manual check

### Agent 000

```shell
echo 'agent 000 sql select * from pm_event' | ~/wdb-query.py
```

<details><summary>Output</summary>

```json
[
    {
        "id": 1,
        "date_first": 1715937625,
        "date_last": 1715937625,
        "log": "Starting rootcheck scan."
    },
    {
        "id": 2,
        "date_first": 1715937626,
        "date_last": 1715937626,
        "log": "Trojaned version of file '/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\\.h|proc\\.h|/dev/[^n]|^/bin/.*sh' (Generic)."
    },
    {
        "id": 3,
        "date_first": 1715937626,
        "date_last": 1715937626,
        "log": "Trojaned version of file '/usr/bin/diff' detected. Signature used: 'bash|^/bin/sh|file\\.h|proc\\.h|/dev/[^n]|^/bin/.*sh' (Generic)."
    },
    {
        "id": 4,
        "date_first": 1715937661,
        "date_last": 1715937661,
        "log": "Ending rootcheck scan."
    }
]
```

</details>

### Agent 002

On the other hand, there are agents that just have the "Starting/Ending rootcheck scan.", like this one.

```shell
echo 'agent 000 sql select * from pm_event' | ~/wdb-query.py
```

<details><summary>Output</summary>

```json
[
    {
        "id": 1,
        "date_first": 1715938455,
        "date_last": 1715938461,
        "log": "Starting rootcheck scan."
    },
    {
        "id": 2,
        "date_first": 1715938469,
        "date_last": 1715938469,
        "log": "Ending rootcheck scan."
    }
]
```

</details>

```shell
wazuh-api -XGET https://localhost:55000/rootcheck/002
```

<details><summary>Output</summary>

```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No rootcheck information was returned",
  "error": 0
}
```

</details>

However, the API still reports the last scan data:

```shell
wazuh-api -XGET https://localhost:55000/rootcheck/002/last_scan
```

<details><summary>Output</summary>

```json
{
  "data": {
    "affected_items": [
      {
        "start": "2024-05-17T09:34:21Z",
        "end": "2024-05-17T09:34:29Z"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Last rootcheck scan of the agent was returned",
  "error": 0
}
```

</details>

## Test implementation

If I'm correct, the Rootcheck integration test is accessing _/var/ossec/queue/db/*.db_ manually: [test_rootcheck.py](https://github.com/wazuh/wazuh-qa/blob/d6616bff7329b99a9b896af9dd7eb63cb6ad97c3/tests/integration/test_rootcheck/test_rootcheck.py#L130-L137)

This may provide wrong results or even corrupt the databases. 

## Conclusion

This might be caused by:
- A race condition: querying the database before the scan has ended.
- A database is not committed.
- A really empty database.

I rule out load-related event dropping, as I've seen no logs about full buffer. However, I'm a bit confused as the test is accessing `X.db` but we can see JSON results from the API in your report.

### Next steps

Please avoid accessing database files manually. We need a fix in the test. Until then, we should disregard this test.

- https://github.com/wazuh/wazuh-qa/issues/5398

### Workaround

Wait 1:30 minutes (30 second margin + 60 seconds for _commit time_).

**Comment by GGP1** [comment] 2024-05-17 14:57
@vikman90 

The tests were this behavior was observed are the [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) where we open a direct connection to the database ([ref](https://github.com/wazuh/wazuh/blob/9709e57d92d611612c3f7eb178caf8638d73bf2e/framework/wazuh/core/rootcheck.py#L12)).

I tried the workaround you suggested by adding 90 seconds to the agents' healtcheck [script](https://github.com/wazuh/wazuh/blob/9709e57d92d611612c3f7eb178caf8638d73bf2e/api/test/integration/env/tools/healthcheck_utils.py#L62) but the tests continue failing sporadically.

Logs: [logs.zip](https://github.com/wazuh/wazuh/files/15351579/logs.zip)

**Comment by GGP1** [comment] 2024-05-17 14:59
@vikman90 

The tests were this behavior was observed are the [API integration tests](https://github.com/wazuh/wazuh/tree/master/api/test/integration) where we open a direct connection to the database ([ref](https://github.com/wazuh/wazuh/blob/9709e57d92d611612c3f7eb178caf8638d73bf2e/framework/wazuh/core/rootcheck.py#L12)).

I tried the workaround you suggested by adding 90 seconds to the agents' healtcheck [script](https://github.com/wazuh/wazuh/blob/9709e57d92d611612c3f7eb178caf8638d73bf2e/api/test/integration/env/tools/healthcheck_utils.py#L62) but the tests continue failing sporadically.

Logs: [logs.zip](https://github.com/wazuh/wazuh/files/15351579/logs.zip)

**Comment by vikman90** [comment] 2024-05-20 08:25
@GGP1 gotcha, sorry for the mistake. At first glance, it may seem that the scan data is missing from the database since the /rootcheck test fails but /rootcheck/last_scan works. However, after analyzing this case with Selu, we found that the expected values for the latter case are:

```yaml
end: !anything
start: !anystring
```

This would validate a case where the Rootcheck scan has not finished:

```json
{
  "data": {
    "affected_items": [
      {
        "start": "2024-05-20T08:01:06Z",
        "end": null
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "Last rootcheck scan of the agent was returned",
  "error": 0
}
```

## Conclusion
I believe it is very likely that the test failed simply because the scan has not finished.

## Suggestions
1. Test `/rootcheck/last_scan` before `/rootcheck` (determine if the scan has finished).
2. Rename the previous case to "**scan started**".
3. Add a "**scan finished**" case with `end: !anystring`.

That will help determine whether the scan data is missing from the DB or the scan did not finish.

## Next steps
I have agreed with @Selutario to close this issue and leave it to your team to apply the suggested changes above.

Best!

**Closed by vikman90** 2024-05-20 08:25 UTC
Labels: type/bug, level/task
