### ISSUE TITLE
Wazuh windows agent errors

### ISSUE THREAD

**Issue by soulmaster43** [wazuh/wazuh#4658] opened 2020-02-25 10:13 UTC
Hello,

As part of our planned Wazuh deployment, I've been installing the Wazuh windows agent in server in order to monitor the forwarded events channel. (Microsoft Windows Server 2016 Standard [Ver: 10.0.14393] - Wazuh v3.11.3 )
For the purposes of this test I ran a query for only one provider yet I would like to mention that the results are repeatable with or without the query.

```
  <localfile>
    <location>ForwardedEvents</location>
    <log_format>eventchannel</log_format>
    <query>
     \<QueryList>
       \<Query Id="0" Path="ForwardedEvents">
         \<Select Path="ForwardedEvents">*[System[Provider[@Name='Microsoft-Windows-Security-Auditing']]]\</Select>
       \</Query>
     \</QueryList>
    </query>
  </localfile>
```

The problem noticed was that events are being dropped and upon analyzing the ossec.log agent file I noticed these errors:

```
2020/02/25 10:06:30 ossec-agent[5176] read_win_event_channel.c:190 at get_message(): ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2020/02/25 10:06:30 ossec-agent[5176] read_win_event_channel.c:468 at send_channel_event(): ERROR: Could not get message for (disabled)

2020/02/25 10:06:02 ossec-agent[5176] read_win_event_channel.c:190 at get_message(): ERROR: Could not EvtFormatMessage() with flags (1) which returned (15029)
2020/02/25 10:06:02 ossec-agent[5176] read_win_event_channel.c:468 at send_channel_event(): ERROR: Could not get message for (10.151.15.255)

2020/02/24 12:03:41 ossec-agent[6804] read_win_event_channel.c:165 at get_message(): ERROR: Could not EvtFormatMessage() to determine buffer size with flags (1) which returned (15027)
2020/02/24 12:03:41 ossec-agent[6804] read_win_event_channel.c:474 at send_channel_event(): ERROR: Could not get message for (ForwardedEvents), provider (Microsoft-Windows-Security-Auditing)

2020/02/25 10:09:56 ossec-agent[5176] read_win_event_channel.c:165 at get_message(): ERROR: Could not EvtFormatMessage() to determine buffer size with flags (1) which returned (15027)
2020/02/25 10:09:56 ossec-agent[5176] read_win_event_channel.c:468 at send_channel_event(): ERROR: Could not get message for (disabled)
```

After a bit of googling I was able to identify the errors but not fix them:

**ERROR_EVT_MESSAGE_NOT_FOUND**
_15027 (0x3AB3)
the message resource is present but the message is not found in the string/message table._

**ERROR_EVT_UNRESOLVED_VALUE_INSERT**
_15029 (0x3AB5)
The substitution string for insert index (%1) could not be found._

For error 15029 the message arrives and is processed by the manager. The same cannot be said for events with error 15027.

I stumbled upon similar issues whe trying to troubleshoot yet none have detailed a fix or workaround for this issue. (https://github.com/wazuh/wazuh/issues/3114, https://github.com/wazuh/wazuh/issues/905)

Please assist.

**Comment by soulmaster43** [comment] 2020-02-28 09:57
An additional error has been noticed in the agent logs:

> 2020/02/28 10:48:57 ossec-agent[14492] read_win_event_channel.c:147 at get_message(): DEBUG: Could not EvtOpenPublisherMetadata() with flags (1) which returned (2): The system cannot find the file specified. 
> 2020/02/28 10:48:57 ossec-agent[14492] read_win_event_channel.c:474 at send_channel_event(): ERROR: Could not get message for (ForwardedEvents), provider (MSExchange ADAccess)

**Comment by Dwordcito** [comment] 2020-04-16 20:42
Hi, I can't reproduce this problem in Windows 10, I will try it in 2k16.

**Could you tell me if the error is in 100% of the situations in which an incorrect password is entered, for example?**

error 15029, is more oriented to failures in the provider and not in the subscriber (for this case Wazuh), since it deals with the impossibility of replacing a prototype in a string format tag.

As for error 15027, this is the typical problem when the event provider sent an incomplete message.
This error is discarded even in the examples and Microsoft codes:

https://docs.microsoft.com/en-us/windows/win32/wes/formatting-event-messages

https://github.com/microsoft/windows-container-tools/blob/9853a33609ac63ea87cfa8b30cbfbad5b4305f3f/LogMonitor/src/LogMonitor/EventMonitor.cpp#L488

Although this eventuality can happen, it should not be a blocking condition for not sending it.

the message must be empty, but the header information must be sent to the manager, something that happens in the Wazuh code.

**Comment by Dwordcito** [comment] 2020-04-17 06:46
I also could not reproduce it with Windows 2k16.

Could you upload a screenshot of the custom view "ForwardEvents" on both tabs?
I'm surprised you use the name of the custom view as the path.

Your configuration
```
<localfile>
    <location>ForwardedEvents</location>
    <log_format>eventchannel</log_format>
    <query>
     \<QueryList>
       \<Query Id="0" Path="ForwardedEvents">
         \<Select Path="ForwardedEvents">*[System[Provider[@Name='Microsoft-Windows-Security-Auditing']]]\</Select>
       \</Query>
     \</QueryList>
    </query>
  </localfile>
```

my configuration that works.

  ```
<localfile>
    <location>ForwardedEvents</location>
    <log_format>eventchannel</log_format>
    <query>
     \<QueryList>
       \<Query Id="0" Path="Security">
         \<Select Path="Security">*[System[Provider[@Name='Microsoft-Windows-Security-Auditing']]]\</Select>
       \</Query>
     \</QueryList>
    </query>
  </localfile>
```

**Comment by soulmaster43** [comment] 2020-04-17 07:47
Hi Dwordcito,

From my observations, I cannot say that this error happens 100% of the times and it is also not isolated to the Microsoft-Windows-Security-Auditing.
It just happened that in the example logs this provider was mentioned.
Perhaps not relevant to our discussion but issues such as this one have been noticed with other logging solutions (NXLog) in which the message is incompletely parsed.

At this moment in time, I am trying to switch the Windows Event Forwarders to "Rendered Text" as I suspect this may improve the event quality to our Windows Event Collector and cause fewer (or perhaps no) errors.

Screenshots you requested:

![1](https://user-images.githubusercontent.com/19363009/79544986-2dc8c600-8090-11ea-8633-1820e4f2409b.PNG)
![2](https://user-images.githubusercontent.com/19363009/79544990-2f928980-8090-11ea-83fa-107d093ae747.PNG)
![3](https://user-images.githubusercontent.com/19363009/79544995-315c4d00-8090-11ea-883a-306414d4235d.PNG)
![4](https://user-images.githubusercontent.com/19363009/79545000-33261080-8090-11ea-8efd-9ad12968e18d.PNG)

Nonetheless, I will also try the configuration you suggested and update you.

Thank you for your support.

**Comment by Dwordcito** [comment] 2020-05-21 15:20
Hi @soulmaster43 , could you improve the new configuration that I proposed?

related to the inconveniences you had, are you still experiencing any?

if there was improvement, could you close the issue?

Thank you very much, I am for what you need!

**Comment by soulmaster43** [comment] 2020-05-22 13:07
Hi Dwordcito,

Apologies for the late reply.
I tried the configuration you proposed but unfortunately that did not solve the issue.
I ended up using NXLog CE to extract the windows logs from the Windows Event Collector (Forwarded Events) and made several customizations to the wazuh deployment in order for the software to be able to ingest and alert based on the NXLog JSON output.

In other words, I think you can close the issue now.

Thank you very much for your support.

**Comment by Dwordcito** [comment] 2020-05-23 20:09
Thanks for your response, any concerns we are at your disposal.

**Closed** 2020-05-23 20:08 UTC
Labels: community, platform/windows
