### ISSUE TITLE
Unable to connect to socket `queue/db/wdb` error in Wazuh manager upgrade test

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#24327] opened 2024-06-26 14:10 UTC
# Description

An error related to wazuh-authd has been found in the Wazuh manager upgrade test from 4.8.0 to v4.9.0-alpha1 stating that it has not been possible to connect to the database in RedHat 8

```
16:37:32  2024/06/25 14:34:26 wazuh-db: INFO: Graceful process shutdown.
16:37:32  2024/06/25 14:34:26 wazuh-authd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
16:37:32  2024/06/25 14:34:27 wazuh-authd: INFO: Exiting...
16:37:32  2024/06/25 14:35:03 wazuh-dbd: INFO: Database not configured. Clean exit.
16:37:32  2024/06/25 14:35:03 wazuh-authd: INFO: Started (pid: 3090).
16:37:32  2024/06/25 14:35:03 wazuh-authd: INFO: Accepting connections on port 1515. No password required.
16:37:32  2024/06/25 14:35:03 wazuh-authd: INFO: Setting network timeout to 1.000000 sec.
16:37:32  2024/06/25 14:35:05 wazuh-db: INFO: Started (pid: 3107).
16:37:32  2024/06/25 14:35:05 wazuh-authd: INFO: New connection from 172.31.27.126
16:37:32  2024/06/25 14:35:05 wazuh-authd: INFO: Received request for a new agent (ip-172-31-27-126.ec2.internal) from: 172.31.27.126
16:37:32  2024/06/25 14:35:08 wazuh-authd: INFO: Cannot find 'queue/db/wdb'. Waiting 3 seconds to reconnect.
16:37:32  2024/06/25 14:35:11 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'.
16:37:32  2024/06/25 14:35:11 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'.
16:37:32  2024/06/25 14:35:11 wazuh-authd: ERROR: Unable to connect to socket 'queue/db/wdb'
16:37:32  2024/06/25 14:35:11 wazuh-authd: ERROR: Error querying Wazuh DB to get the agent's 1 information.
16:37:32  2024/06/25 14:35:11 wazuh-authd: WARNING: Duplicate name 'ip-172-31-27-126.ec2.internal', rejecting enrollment. Failed to get agent-info for agent '001'
```

## Related

- https://github.com/wazuh/wazuh/issues/24258#issuecomment-2191720357
- https://ci.wazuh.info/job/Test_upgrade/135360/

**Comment by sebasfalcone** [comment] 2024-06-27 12:19
## Issue blocked
With the available information, it's not possible to determine the root cause of the problem

@rauldpm we need access to the environment in which the error appears, the logs in debug will be greatly appreciated

**Comment by rauldpm** [comment] 2024-07-01 08:04
The environment is an upgrade test, using this Docker image:

https://github.com/wazuh/wazuh-jenkins/blob/v4.9.0-alpha1/dockers/service/targeted/RedHat/8/Dockerfile

The 4.9.0 package is installed using the Ansible playbook

https://github.com/wazuh/wazuh-jenkins/blob/v4.9.0-alpha1/ansible-roles/install_wazuh_repo/tasks/install_wazuh_repo.yaml

The upgrade tasks are done using this Ansible playbook

https://github.com/wazuh/wazuh-jenkins/blob/v4.9.0-alpha1/quality/tests/generic/03-upgrade/linux/test/conf/test-manager/tasks/configure_test.yaml

I have not been able to reproduce the error using the upgrade test pipeline in debug mode, looking at the community, there are some reports about this error, this is the first time that this error has appeared in our testing

Can you explain this error or what may be causing it? What can cause a connection error to the DB socket? I found that a community user found this error and we applied a fix, related to https://github.com/wazuh/wazuh/issues/12320#issuecomment-1043021722 - https://github.com/wazuh/wazuh/pull/10849 

Can this error be related to the WARNING message about the rejected enrollment?

> Duplicate name 'ip-172-31-27-126.ec2.internal', rejecting enrollment. Failed to get agent-info for agent '001'

**Comment by sebasfalcone** [comment] 2024-07-02 12:49
## Feedback
This error appears when the wazuh-db hasn't started yet and we attempt to connect to it

From what I am seeing in the logs, the issue is due to a race condition:
1. Wazuh-db stops: `16:37:32  2024/06/25 14:34:26 wazuh-db: INFO: Graceful process shutdown.`
2. Authd stops: `16:37:32  2024/06/25 14:34:27 wazuh-authd: INFO: Exiting...`
3. Authd starts: `16:37:32  2024/06/25 14:35:03 wazuh-authd: INFO: Started (pid: 3090).`
4. Wazuh-db starts: `16:37:32  2024/06/25 14:35:05 wazuh-db: INFO: Started (pid: 3107).`

Authd requests information to the wazuh-db but it isn't operational yet, so it fails to connect to the socket. The problem will be solved once wazuh-db fully starts

## Closure
I will close this issue as it has not been reproduced and has really low prevalence in the community

Re open the issue if we find this again

**Closed by sebasfalcone** 2024-07-02 12:49 UTC
Labels: type/bug, level/task
