### ISSUE TITLE
Problem RAM with Wazuh Cluster

### ISSUE THREAD

**Issue by John33000** [wazuh/wazuh#4908] opened 2020-04-15 08:38 UTC
Hi,

I use Wazuh 3.10, elasticsearch 7.4 , Kibana 7.3.2 and filebeat 7.4.

I have 2 Wazuh Manager. Server01 is the Master and Server02 is Worker. I made a clone of Server01 for made Server02. But Server01 has 8Go RAM and Server02 has 10Go RAM. 
But I have a problem. The ossec process in Server01 use 5% of RAM but in Server02 38%.  And the python script : wazuh-clusted.py use 36.6% of RAM in Server02 but 5% in Server01. Can you tell me why the Worker use more ressource ?

Best Regards

**Comment by John33000** [comment] 2020-04-21 07:05
Hi, this night the swap was used at 99%. What is the problem please ? 

Best regards

**Comment by 0xN3utr0n** [comment] 2020-04-22 09:32
Hi @John33000 ,
That looks totally as a memory leak; since 3.10 a few of them have been found and fixed, so I highly recommend you to upgrade both servers to the latest version (3.12.2 right now).

You can follow this steps if you wish to do so: https://documentation.wazuh.com/3.12/upgrade-guide/upgrading/latest_wazuh3_minor.html

Kind regards,
Fernando G.

**Comment by Selutario** [comment] 2020-04-22 10:17
Hello @John33000,

As my teammate pointed out, the problem is related to two memory leaks in the cluster that were discovered a few months ago.

The most important was due to the storage of all sent requests as you can see below. The problem was corrected in release 3.11.2.
https://github.com/wazuh/wazuh/blob/5a6f81a0c7629ca8a8ae3e780fe1a69bf506b694/framework/wazuh/cluster/common.py#L256-L258
You can find more detailed information on both the problem and the solution here [#4444](https://github.com/wazuh/wazuh/issues/4444).

Regarding the second leak, it was less relevant but could cause problems too. The problem was due to the continuous creation of loggers and filter objects. If you want to go deeper, the corresponding issue is #4463. 

Both leaks are fixed in newer versions (along with other major improvements like a refactor in Syscheck that greatly improves File Integrity Monitoring), so our recommendation is to upgrade your current version of Wazuh.

For any questions, do not hesitate to ask.

Kind regards,
Selu.

**Comment by 0xN3utr0n** [comment] 2020-04-27 08:03
@John33000 ,due to inactivity I'm going to close this issue. However, feel free to open it if you have any other related question.

**Closed by 0xN3utr0n** 2020-04-27 08:03 UTC
Labels: community
