### ISSUE TITLE
Bug in agent redirection during load balancer operation and when worker's space is running out

### ISSUE THREAD

**Issue by mradaszewski92** [wazuh/wazuh#10504] opened 2021-10-14 08:03 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.1| Cluster | Worker | Packages | Red Hat Enterpirsie Linux 7 |

Hello Team, 

I have 4 cluster nodes plus one manager. I use NGINX to balance the traffic, but I do not understand why all agents are redirected to only one node in the cluster, it would not be a problem if it were not for the fact that it overloads the node (to which traffic from agents is redirected), while all the rest node'ow sits and gets bored. This leads to a situation where the disk space runs out quickly, and when the disk space runs out, the load balancer cannot switch traffic to other nodes in the cluster. Does Wazuh have a tool to balance the number of agents along the cluster?

**Comment by mradaszewski92** [comment] 2021-10-16 12:47
Hello @orsifacundo 

I resolve problem with NGINX using least_conn parametr for niginx.conf. If I can suggest, please add some information to your course from this link: https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/. I believe that in larger environments (above 5,000 agents) it is extremely important that traffic is distributed equally to all nodes in the cluster. This will make it much easier to maintain the environment for the Wazuh application.

Q:What kind of method you are using? Do you have a proxy for outbound connections of the agents?
A: **I did everything according to this course: https://wazuh.com/blog/nginx-load-balancer-in-a-wazuh-cluster/**
Q:What kind of architecture you have for your Manager/Agents communication? 
A: **The manager, nodes and agents operate on the x86_64 architecture, under the Red Hat 7 system. Communication takes place via TCP.**

**Comment by orsifacundo** [comment] 2021-10-20 00:41
Hi @mradaszewski92,

Thank you for your suggestions. I was going to advise to change exactly that parameter on the NGINX config. Based on the tests that I performed (given the problem that you reported) an issue was opened in order to modify our documentation. You can check it here: https://github.com/wazuh/wazuh-documentation/issues/4465. Feel free to add more information.

Regards.

**Comment by orsifacundo** [comment] 2021-11-03 18:39
This has been reported here: https://github.com/wazuh/wazuh/issues/9043 and the issue is already marked as enhancement. I'll proceed and close this issue.

**Closed by orsifacundo** 2021-11-03 18:39 UTC
Labels: enhancement
