### ISSUE TITLE
Footprint - Docker-listener finished unexpectedly found in logs

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25059] opened 2024-08-05 13:18 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0-beta1 | Wazuh component | Agent | Packages/Sources | Ubuntu |

The following log was found in [Footprint Metrics - ALL-EXCEPT-SYSCOLLECTOR](https://github.com/wazuh/wazuh/issues/25028) 

```
2024/08/02 20:37:45 wazuh-modulesd:docker-listener WARNING: Docker-listener finished unexpectedly (code 0). Retrying to run in next scheduled time...
2024/08/02 20:37:45 wazuh-modulesd:docker-listener WARNING: Interval overtaken.
```

An unexpectedly failed module should not return code 0

The only previous record of this log is at https://github.com/wazuh/wazuh/issues/19499 where its appearance was expected.

Further research should be done

**Comment by fdalmaup** [comment] 2024-08-06 09:59
Docker-listener configuration used in the `ossec.conf` file:
```xml
  <wodle name="docker-listener">
    <disabled>no</disabled>
    <attempts>200</attempts>
    <run_on_start>yes</run_on_start>
    <interval>1s</interval>
  </wodle>
```

The mentioned messages are inside the attached file:
- [ubuntu-agent-test-stress-2024-08-05.zip](https://github.com/user-attachments/files/16508616/ubuntu-agent-test-stress-2024-08-05.zip)

**Comment by GGP1** [comment] 2024-08-06 16:05
## Update

I could reproduce the error by killing the docker listener process, I tried solving the unexpected shutdown message but that is something we don't handle in the script

<details><summary>Configuration</summary>

```yml
<wodle name="docker-listener">
  <disabled>no</disabled>
  <attempts>200</attempts>
  <run_on_start>yes</run_on_start>
  <interval>1s</interval>
</wodle>
```

I also set `wazuh_modules.debug=2` in the internal options.

</details>

<details><summary>Killing the docker-listener process</summary>

```console
root@0d0a7f9e0760:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  1492 ?        Ss   14:19   0:00 bash /scripts/entrypoint.sh nginx-lb v4.9.0-beta1
root        1348  0.0  0.0   4628  3844 pts/0    Ss   14:20   0:00 bash
root        5395  0.0  0.0  23380  3080 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-execd
wazuh       5403  0.0  0.1 245156  8732 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-agentd
root        5417 14.0  0.1 200300 11916 ?        SNl  14:33   0:01 /var/ossec/bin/wazuh-syscheckd
root        5427  0.0  0.0 269272  7176 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-logcollector
root        5441  1.5  0.2 1397240 22880 ?       Sl   14:33   0:00 /var/ossec/bin/wazuh-modulesd
root        5448  0.9  0.3 106552 28428 ?        Ssl  14:33   0:00 python3 wodles/docker/DockerListener
root        6013  0.0  0.0   2792   988 ?        S    14:33   0:00 sleep 10
root        6023  0.0  0.0   7064  1564 pts/0    R+   14:33   0:00 ps aux
root@0d0a7f9e0760:/# kill 5448
```

</details>

<details><summary>Logs after the kill</summary>

```console
root@0d0a7f9e0760:/# cat /var/ossec/logs/ossec.log | grep wazuh-modulesd:docker-listener
...
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 0). Retrying to run in next scheduled time...
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

For the solution, I tried running the threads in daemon mode and exiting the module gracefully by instructing them to stop and closing the client connection

<details><summary>Changes</summary>

```py
self.exit_event = threading.Event()

def start(self):
  signal.signal(signal.SIGTERM, self.on_exit_handler)
  signal.signal(signal.SIGINT, self.on_exit_handler)
  self.send_msg(json.dumps({self.field_debug_name: "Started"}))
  self.thread1 = threading.Thread(target=self.listen, daemon=True)
  self.thread2 = threading.Thread(target=self.listen, daemon=True)
  self.connect(first_time=True)
  self.thread1.join()
  self.thread2.join()

...

def listen(self):
  """
  Listens Docker events

  """
  while not self.exit_event.is_set():
      try:
          for event in self.client.events():
              self.process(event)
      except Exception as e:
          raise e
      print("Docker service was stopped.")
      self.send_msg(json.dumps({self.field_debug_name: "Disconnected from the Docker service"}))
      self.connect()

...

def on_exit_handler(self, signum, frame):
  self.exit_event.set()
  self.client.close()
  sys.stderr.write('Docker service was stopped.\n')
  sys.exit(13)
```

</details>

but even with those changes in place, `wazuh-modulesd` logged the `WARNING` message 

<details><summary>Logs</summary>

```console
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:88 at wm_docker_main(): ERROR: Docker service was stopped.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 13). Retrying to run in next scheduled time...
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

As such, I believe the issue must be analyzed by the modulesd team to decide what to do with those messages.

**Comment by GGP1** [comment] 2024-08-06 16:05
## Update

I could reproduce the error by killing the docker listener process, I tried solving the unexpected shutdown message but that is something we don't handle in the script

<details><summary>Configuration</summary>

```yml
<wodle name="docker-listener">
  <disabled>no</disabled>
  <attempts>200</attempts>
  <run_on_start>yes</run_on_start>
  <interval>1s</interval>
</wodle>
```

I also set `wazuh_modules.debug=2` in the internal options.

</details>

<details><summary>Killing the docker-listener process</summary>

```console
root@0d0a7f9e0760:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  1492 ?        Ss   14:19   0:00 bash /scripts/entrypoint.sh nginx-lb v4.9.0-beta1
root        1348  0.0  0.0   4628  3844 pts/0    Ss   14:20   0:00 bash
root        5395  0.0  0.0  23380  3080 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-execd
wazuh       5403  0.0  0.1 245156  8732 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-agentd
root        5417 14.0  0.1 200300 11916 ?        SNl  14:33   0:01 /var/ossec/bin/wazuh-syscheckd
root        5427  0.0  0.0 269272  7176 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-logcollector
root        5441  1.5  0.2 1397240 22880 ?       Sl   14:33   0:00 /var/ossec/bin/wazuh-modulesd
root        5448  0.9  0.3 106552 28428 ?        Ssl  14:33   0:00 python3 wodles/docker/DockerListener
root        6013  0.0  0.0   2792   988 ?        S    14:33   0:00 sleep 10
root        6023  0.0  0.0   7064  1564 pts/0    R+   14:33   0:00 ps aux
root@0d0a7f9e0760:/# kill 5448
```

</details>

<details><summary>Logs after the kill</summary>

```console
root@0d0a7f9e0760:/# cat /var/ossec/logs/ossec.log | grep wazuh-modulesd:docker-listener
...
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 0). Retrying to run in next scheduled time...
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

For the solution, I tried running the threads in daemon mode and exiting the module gracefully by instructing them to stop and closing the client connection

<details><summary>Changes</summary>

```py
self.exit_event = threading.Event()

def start(self):
  signal.signal(signal.SIGTERM, self.on_exit_handler)
  signal.signal(signal.SIGINT, self.on_exit_handler)
  self.send_msg(json.dumps({self.field_debug_name: "Started"}))
  self.thread1 = threading.Thread(target=self.listen, daemon=True)
  self.thread2 = threading.Thread(target=self.listen, daemon=True)
  self.connect(first_time=True)
  self.thread1.join()
  self.thread2.join()

...

def listen(self):
  """
  Listens Docker events

  """
  while not self.exit_event.is_set():
      try:
          for event in self.client.events():
              self.process(event)
      except Exception as e:
          raise e
      print("Docker service was stopped.")
      self.send_msg(json.dumps({self.field_debug_name: "Disconnected from the Docker service"}))
      self.connect()

...

def on_exit_handler(self, signum, frame):
  self.exit_event.set()
  self.client.close()
  sys.stderr.write('Docker service was stopped.\n')
  sys.exit(13)
```

</details>

but even with those changes in place, `wazuh-modulesd` logged the `WARNING` messages

<details><summary>Logs</summary>

```console
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:88 at wm_docker_main(): ERROR: Docker service was stopped.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 13). Retrying to run in next scheduled time...
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

As such, I believe the issue must be analyzed by the agent team to decide what to do with those messages.

**Comment by GGP1** [comment] 2024-08-06 16:07
## Update

I could reproduce the error by killing the docker listener process, I tried solving the unexpected shutdown message but that is something we don't handle in the script

<details><summary>Configuration</summary>

```yml
<wodle name="docker-listener">
  <disabled>no</disabled>
  <attempts>200</attempts>
  <run_on_start>yes</run_on_start>
  <interval>1s</interval>
</wodle>
```

I also set `wazuh_modules.debug=2` in the internal options.

</details>

<details><summary>Killing the docker-listener process</summary>

```console
root@0d0a7f9e0760:/# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   4364  1492 ?        Ss   14:19   0:00 bash /scripts/entrypoint.sh nginx-lb v4.9.0-beta1
root        1348  0.0  0.0   4628  3844 pts/0    Ss   14:20   0:00 bash
root        5395  0.0  0.0  23380  3080 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-execd
wazuh       5403  0.0  0.1 245156  8732 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-agentd
root        5417 14.0  0.1 200300 11916 ?        SNl  14:33   0:01 /var/ossec/bin/wazuh-syscheckd
root        5427  0.0  0.0 269272  7176 ?        Sl   14:33   0:00 /var/ossec/bin/wazuh-logcollector
root        5441  1.5  0.2 1397240 22880 ?       Sl   14:33   0:00 /var/ossec/bin/wazuh-modulesd
root        5448  0.9  0.3 106552 28428 ?        Ssl  14:33   0:00 python3 wodles/docker/DockerListener
root        6013  0.0  0.0   2792   988 ?        S    14:33   0:00 sleep 10
root        6023  0.0  0.0   7064  1564 pts/0    R+   14:33   0:00 ps aux
root@0d0a7f9e0760:/# kill 5448
```

</details>

<details><summary>Logs after the kill</summary>

```console
root@0d0a7f9e0760:/# cat /var/ossec/logs/ossec.log | grep wazuh-modulesd:docker-listener
...
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:19 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 0). Retrying to run in next scheduled time...
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 14:33:43 wazuh-modulesd:docker-listener[5439] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

For the solution, I tried running the threads in daemon mode and exiting the module gracefully by instructing them to stop and closing the client connection

<details><summary>Changes</summary>

```py
self.exit_event = threading.Event()

def start(self):
  signal.signal(signal.SIGTERM, self.on_exit_handler)
  signal.signal(signal.SIGINT, self.on_exit_handler)
  self.send_msg(json.dumps({self.field_debug_name: "Started"}))
  self.thread1 = threading.Thread(target=self.listen, daemon=True)
  self.thread2 = threading.Thread(target=self.listen, daemon=True)
  self.connect(first_time=True)
  self.thread1.join()
  self.thread2.join()

...

def listen(self):
  """
  Listens Docker events

  """
  while not self.exit_event.is_set():
      try:
          for event in self.client.events():
              self.process(event)
      except Exception as e:
          raise e
      print("Docker service was stopped.")
      self.send_msg(json.dumps({self.field_debug_name: "Disconnected from the Docker service"}))
      self.connect()

...

def on_exit_handler(self, signum, frame):
  self.exit_event.set()
  self.client.close()
  sys.stderr.write('Docker service was stopped.\n')
  sys.exit(13)
```

</details>

but even with those changes in place, `wazuh-modulesd` logged the `WARNING` messages

<details><summary>Logs</summary>

```console
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:46 at wm_docker_main(): INFO: Module docker-listener started.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:20 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:88 at wm_docker_main(): ERROR: Docker service was stopped.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:112 at wm_docker_main(): WARNING: Docker-listener finished unexpectedly (code 13). Retrying to run in next scheduled time...
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] schedule_scan.c:153 at _get_next_time(): WARNING: Interval overtaken.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:59 at wm_docker_main(): INFO: Starting to listening Docker events.
2024/08/06 15:55:35 wazuh-modulesd:docker-listener[31446] wm_docker.c:63 at wm_docker_main(): DEBUG: Launching command 'wodles/docker/DockerListener'
```

</details>

As such, I believe the issue must be analyzed by the @wazuh/devel-agent-div2 team to decide what to do with those messages.

**Comment by fdalmaup** [comment] 2024-08-07 06:52
# Review

After discussing the issue with the release team, this should not be considered a stopper for the `4.9.0` version but a known bug since it relates to how `wazuh-modulesd` logs the `docker-listener` process exit, and in the `5.0` version this will suffer several changes that make it not worth the effort.

**Closed by fdalmaup** 2024-08-07 06:52 UTC
Labels: type/bug, level/task
