### ISSUE TITLE
Precedence/Multigroup it is not applied for macos localfile configuration

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#12904] opened 2022-03-29 13:06 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.0-40307 | Wazuh-logcollector & Wazuh-agentd | Agent | Packages/Sources | macOS 10.4 |

Wazuh agent reports more than one `macos` Localfile configuration as an error where it should be considered as valid and applies the precedence. 

- **Scenario 1** (high probable): users tend to use multiple groups and adding the configuration in various groups will trigger the error: 

![image](https://user-images.githubusercontent.com/16334770/160616776-3d1a6979-ab35-402c-8c8a-9355c1e42f61.png)
![image](https://user-images.githubusercontent.com/16334770/160616876-2b3429f8-f504-43b5-a210-21757f78b791.png)

-  **Scenario 2**: the user would add the configuration to the `ossec.conf` and push it as well through a group: 

![image](https://user-images.githubusercontent.com/16334770/160617232-6f903fdc-81a1-40df-be7d-02c9a5125d55.png)

Please note that the respective documentation does not mention that only one block should be used. however, keeping only a warning message about the duplicated (although one of them has a query) and applying the precedence would be the expected behavior. 

Regards,
Elwali

**Comment by juliancnn** [comment] 2022-04-01 14:43
I am removing the `bug` tag because **this is NOT a bug.** 
This is expected behavior, it was designed this way and it is also specified in the documentation:

![image](https://user-images.githubusercontent.com/1891958/161286435-9a92e15f-cca6-4e06-8654-2f9fc04caa2e.png)


Check `user-manual/reference/ossec-conf/localfile.html#log-format`

Regards.
Julian

**Comment by JcabreraC** [comment] 2022-04-05 16:21
This functionality is resolved in the PR: **Fix verify-agent-conf for MacOS ULS #13035**

**Closed** 2022-04-07 09:09 UTC
Labels: core/logcollector, operations
