### ISSUE TITLE
[3.10.1] Agents registration issue

### ISSUE THREAD

**Issue by Eowin78** [wazuh/wazuh#3994] opened 2019-09-20 11:41 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.1 | Agents | Manager/Agent | APT | Debian 9 |

Hi,

I encounter an Issue with the agent registration on the wazuh manager.

My wazuh server is an hosted server over internet, I'm acrually able to register all server with the public IP. I'm actually trying to install agent on my laptops (15) which are on the same local network so all laptops have the same public IP, I can register one computer only, if I try to add a second one, the first laptops register is replaced by the second laptops added.

I think that when you add a new laptop with the same ip, that replace the old one.

Can you help me ?

Regards,

**Comment by vikman90** [comment] 2019-09-20 22:01
@Eowin78 of course, you can register multiple hosts with the same public IP.

By default, the manager attaches an agent to its public IP. More concretely, it attaches an agent to the visible IP of the agent. If your manager or your agents are behind a NAT, you can register only one agent.

You need to add your agent with a "wildcard" IP address: "_any_". Simply add the option `-I any` to the registration command in your agent's host:

```sh
$ /var/ossec/bin/agent-auth -m <manager IP> -I any
```

Indeed, "_any_" works as "_0.0.0.0/0_".

On the other hand, you can set up this behavior by default in the manager so that it will register the agents with the "_any_" address.

Set this configuration in your manager's "_/var/ossec/etc/ossec.conf_":

```xml
<ossec_config>
  <auth>
    <use_source_ip>no</use_source_ip>
  </auth>
</ossec_config>
```

That option lets the manager assign the "_any_" address to the agents by default. You need to restart the manager to apply the configuration. The agent's option `-I` overwrites that setting.

For further information, please read:
- [`agent-auth` manual](https://documentation.wazuh.com/3.10/user-manual/reference/tools/agent-auth.html).
- [Manager's Auth daemon settings](https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/auth.html).

Hope that helps.
Best regards.

**Comment by Eowin78** [comment] 2019-09-23 10:37
Hi @vikman90,

Thank you for your response, I did many test today with your advices, but nothing seem work correctly, I still have only 1 laptop on the kibana interface.

I tried the manager config modification and the agent auth command with -I any :/

So you have an other idea ?

**Comment by Zenidd** [comment] 2019-09-23 15:15
Hi @Eowin78,

We have just discovered a bug causing successive registrations with the "-I any" option overwrite each other. 

As a workaround, to have your laptops correctly registered, you should follow the further steps:

- Be sure that ` <use_source_ip>no</use_source_ip>` is set to `no`
- Use agent-auth without `any` option:  `/var/ossec/bin/agent-auth -m <manager IP>`. If you are registering machines that have exactly the same hostname you have to manually specify an agent name using the -A option: `/var/ossec/bin/agent-auth -m <manager IP> -A <hostname>`
- This should be enough to register your agents.

About the bug, as soon as our workflow allows us to do so, we're going to fix it. You can track the progress in this issue.

I hope it helps. Please, let me know how it goes.

Best regards, Juan Pablo Sáez

**Comment by Eowin78** [comment] 2019-09-25 10:06
Hi @Zenidd,

I did steps that you told me to follow and that seem working fine now !

I have all laptops registered on wazuh now !

Thank you for your help :)

**Comment by Zenidd** [comment] 2019-09-25 13:25
Hi @Eowin78,

I'm reopening this issue as the bug is documented here so when our workflow allow us we can assign it to a project.

Greetings, JP Sáez

**Comment by jctello** [comment] 2019-10-11 16:53
Closing this as it is a duplicate of this prior issue: https://github.com/wazuh/wazuh/issues/2497

**Closed by jctello** 2019-10-11 16:53 UTC
Labels: bug, community
