### ISSUE TITLE
Analyze and compare agents upgrade related endpoints

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh#22371] opened 2024-03-05 18:23 UTC
## Description

The `GET /agents/upgrade_result` in charge of returning the upgrade results from agents, is one of the alternatives to be used as part of the [New endpoint plugin](https://github.com/wazuh/wazuh-dashboard-plugins/issues/6129) issue. To check the status of upgraded agents, the @wazuh/devel-dashboard team is currently using the `GET /tasks/status` which provides similar information. 

In an environment with a `4.9.0` manager and a `v4.7.3` agent, the behavior is as follows:

- Trying to upgrade a `v4.7.3` agent, the `GET tasks/status` returns:
  <details><summary>GET tasks/status</summary>
  
  ```json
  {
    "data": {
      "affected_items": [
        {
          "create_time": "2024-03-05T15:38:33Z",
          "error_message": "The version of the WPK does not exist in the repository",
          "last_update_time": "2024-03-05T15:38:33Z",
          "node": "wd_master_1",
          "agent_id": "004",
          "task_id": 1,
          "module": "upgrade_module",
          "status": "Failed",
          "command": "upgrade"
        }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
    },
    "message": "All specified task's status were returned",
    "error": 0
  }
  ```
  
  </details>

Using `GET /agents/upgrade_result` after attempting an upgrade on the agent returns:
<details><summary>GET /agents/upgrade_result</summary>

```json
{
    "data": {
      "affected_items": [
        {
          "message": "Success",
          "agent": "004",
          "task_id": 1,
          "node": "wd_master_1",
          "module": "upgrade_module",
          "command": "upgrade",
          "status": "Error",
          "error_msg": "The version of the WPK does not exist in the repository",
          "create_time": "2024-03-05T12:38:33Z",
          "update_time": "2024-03-05T12:38:33Z"
        }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
    },
    "message": "All upgrade tasks were returned",
    "error": 0
  }
```
</details>

> [!NOTE]
> - The failure in the upgrade task is expected. 
> - The response has already been mentioned in https://github.com/wazuh/wazuh/issues/17935. 

When a determined time-lapse passes, the response from `GET /agents/upgrade_result` is empty:
<details><summary></summary>

```json
$ curl -k -X GET "https://localhost:55555/agents/upgrade_result" -H "Authorization: Bearer $TOKEN" 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   159  100   159    0     0   6625      0 --:--:-- --:--:-- --:--:--  6625
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No upgrade task was returned",
  "error": 0
}
```

</details>

The goal of the present issue is to analyze the logic behind the mentioned endpoints and compare their performance against each other to make the necessary modifications to have well specified the objective of each endpoint.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment] 2024-03-07 18:32
## Update

### `GET /tasks/status`

Returns all available information about the specified tasks. It just queries the `tasks` table for information and returns that.

https://github.com/wazuh/wazuh/blob/098511a487d26a962f8d72dae0647a09d017f3e6/framework/wazuh/task.py#L42-L60

### `GET /agents/upgrade_result`

Returns the agents upgrade results by sending the command `upgrade_result` via the socket `queue/tasks/upgrade` to the task module. If there's a communication error with the manager, it attempts to create the upgrade tasks again with smaller messages chunks.

It also filters non-eligible agents that won't respond successfully to the command.

https://github.com/wazuh/wazuh/blob/098511a487d26a962f8d72dae0647a09d017f3e6/framework/wazuh/agent.py#L1218-L1308

## Conclusion

As we can clearly see, the design of `GET /tasks/status` is **much more efficient** than `GET /agents/upgrade_result`. 

It accesses a local database to get the status of a task instead of opening a connection to a socket and sending a command to get the upgrade results.

Given that `GET /agents/upgrade_result` and `GET /tasks/status` serve the same purpose, I would propose removing the former endpoint from the API.

**Comment by fdalmaup** [comment] 2024-03-11 12:05
# Review

The code analysis was correctly carried out. Due to the conclusion, I have a couple of questions:
- Is the `tasks` table only composed of upgrade tasks or what other tasks could be found? Should we consider edge cases before removing the command-sending endpoint or the database endpoint is always more reliable than the former?
- Did you find the logic behind the `GET /agents/upgrade_result` endpoint as to why the status of the tasks disappears after a while? Could it be due to the way the task module works?
- In the `framework/wazuh/core/task.py` file, the `send_to_tasks_socket` function was found. Is this used as part of the `GET /agents/upgrade_result` endpoint or does the `create_upgrade_tasks` replace it?

Leaving the issue On Hold until these questions are answered.

**Comment by GGP1** [comment] 2024-03-11 15:17
## Update

> Is the tasks table only composed of upgrade tasks or what other tasks could be found? Should we consider edge cases before removing the command-sending endpoint or the database endpoint is always more reliable than the former?

The `TASKS` table was design for multiple modules and commands but is currently used for upgrade tasks only. These are the existing commands:

- upgrade
- upgrade_custom
- upgrade_get_status
- upgrade_update_status
- upgrade_result
- upgrade_cancel_tasks
- set_timeout
- delete_old

> `set_timeout` and `delete_old` are related to upgrades as well.

There is no edge-cases to consider, the command-sending endpoint does what the database endpoint does directly.

After reviewing the task module source code I could determine that the response to the message we are sending to them is just the data from the database parsed differently.

> Did you find the logic behind the GET /agents/upgrade_result endpoint as to why the status of the tasks disappears after a while? Could it be due to the way the task module works?

I couldn't reproduce this after the upgrade was done, the `GET /agents/upgrade_result` endpoint returns the status of the last upgrade performed by querying the `TASKS` table.

This is the path followed by the Core task module:

https://github.com/wazuh/wazuh/blob/6f672d01053d274eab8f6d5622e995f6a588f6f8/src/wazuh_db/wdb_parser.c#L6528-L6547

https://github.com/wazuh/wazuh/blob/6f672d01053d274eab8f6d5622e995f6a588f6f8/src/wazuh_db/wdb_task.c#L199-L215

https://github.com/wazuh/wazuh/blob/6f672d01053d274eab8f6d5622e995f6a588f6f8/src/wazuh_db/wdb.c#L209

> In the framework/wazuh/core/task.py file, the send_to_tasks_socket function was found. Is this used as part of the GET /agents/upgrade_result endpoint or does the create_upgrade_tasks replace it?

The `create_upgrade_tasks` function uses `create_wazuh_socket_message` to send the command to the tasks socket.

https://github.com/wazuh/wazuh/blob/6f672d01053d274eab8f6d5622e995f6a588f6f8/framework/wazuh/core/agent.py#L1472

**Comment by fdalmaup** [comment] 2024-03-13 15:57
# Review

Analyzing the last update it can be seen that both endpoints request the DB, one using the Framework's code (`GET /tasks/status
`) and the other (`GET /agents/upgrade_result`) sending a command to the `queue/tasks/upgrade` socket for the manager to carry out the request to the DB. The behavior seen related to how the endpoint response changes after a while is related to the code shared in the last update.

I consider the analysis to be complete. LGTM!

**Comment by Selutario** [comment] 2024-03-14 17:33
LGTM. Moving this to blocked until discussing whether the `GET /agents/upgrade_result
` endpoint should be removed and the reasons why it was created, especially while there are no other tasks but upgrade-related.

**Comment by Selutario** [comment] 2024-03-27 11:14
We will not remove any endpoints in 4.9. Any breaking change will be assessed for 5.0, so I'm closing this issue.

**Closed by Selutario** 2024-03-27 11:14 UTC
Labels: type/enhancement, level/subtask
