### ISSUE TITLE
useradd error in Wazuh agent installation on Fedora 40

### ISSUE THREAD

**Issue by Desvelao** [wazuh/wazuh#25964] opened 2024-09-26 06:53 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

When installing the Wazuh agent in Fedora 40 (aarch64), there is an error:

<details>
  <summary>host details</summary>
  
  ```console
[fedora@ip-172-31-47-101 ~]$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="40 (Cloud Edition)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Cloud Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Cloud Edition"
VARIANT_ID=cloud
[fedora@ip-172-31-47-101 ~]$ uname -m
aarch64
  ```
</details>

```
useradd: failed to reset the lastlog entry of UID 992: No such file or directory
```

Wazuh agent installation logs:
```console
[root@ip-172-31-47-101 fedora]# WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='fedora40' WAZUH_MANAGER="54.81.49.136" yum install wazuh-agent
EL-40 - Wazuh                                                                                                                                                 141 kB/s |  86 kB     00:00    
Dependencies resolved.
==============================================================================================================================================================================================
Package                                          Architecture                                 Version                                       Repository                                  Size
==============================================================================================================================================================================================
Installing:
wazuh-agent                                      aarch64                                      4.9.1-1                                       wazuh                                       10 M

Transaction Summary
==============================================================================================================================================================================================
Install  1 Package

Total download size: 10 M
Installed size: 32 M
Is this ok [y/N]: y
Downloading Packages:
wazuh-agent-4.9.1-1.aarch64.rpm                                                                                                                                12 MB/s |  10 MB     00:00    
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                          12 MB/s |  10 MB     00:00     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
Preparing        :                                                                                                                                                                      1/1 
Running scriptlet: wazuh-agent-4.9.1-1.aarch64                                                                                                                                          1/1 
useradd: failed to reset the lastlog entry of UID 992: No such file or directory

Installing       : wazuh-agent-4.9.1-1.aarch64                                                                                                                                          1/1 
Running scriptlet: wazuh-agent-4.9.1-1.aarch64                                                                                                                                          1/1 

Installed:
wazuh-agent-4.9.1-1.aarch64                                                                                                                                                                 

Complete!
```

**Comment by Desvelao** [comment] 2024-09-26 11:11
Request data by @vikman90 

```console
bash-5.2$ yum info shadow-utils
Fedora 40 - aarch64                                                                                                                                            16 MB/s |  19 MB     00:01    
Fedora 40 openh264 (From Cisco) - aarch64                                                                                                                     3.1 kB/s | 1.4 kB     00:00    
Fedora 40 - aarch64 - Updates                                                                                                                                  24 MB/s | 9.9 MB     00:00    
EL-40 - Wazuh                                                                                                                                                 136 kB/s |  86 kB     00:00    
Last metadata expiration check: 0:00:01 ago on Thu Sep 26 11:09:28 2024.
Installed Packages
Name         : shadow-utils
Epoch        : 2
Version      : 4.15.1
Release      : 3.fc40
Architecture : aarch64
Size         : 7.3 M
Source       : shadow-utils-4.15.1-3.fc40.src.rpm
Repository   : @System
From repo    : 9eabcddc804842ea8c90f8ab5a9eed43
Summary      : Utilities for managing accounts and shadow password files
URL          : https://github.com/shadow-maint/shadow
License      : BSD-3-Clause AND GPL-2.0-or-later
Description  : The shadow-utils package includes the necessary programs for
             : converting UNIX password files to the shadow password format, plus
             : programs for managing user and group accounts. The pwconv command
             : converts passwords to the shadow password format. The pwunconv command
             : unconverts shadow passwords and generates a passwd file (a standard
             : UNIX password file). The pwck command checks the integrity of password
             : and shadow files. The lastlog command prints out the last login times
             : for all users. The useradd, userdel, and usermod commands are used for
             : managing user accounts. The groupadd, groupdel, and groupmod commands
             : are used for managing group accounts.

```

**Comment by vikman90** [comment] 2024-09-26 11:31
Thank you @Desvelao

I've managed to reproduce this issue on Fedora 40 @ x86_64.

||Platform|
|---|---|
|🟢|Docker|
|🔴|VirtualBox|

In fact, this happens when creating any user with ID < 1000:

```bash
useradd -ru 800 vikman
```
```
useradd: failed to reset the lastlog entry of UID 800: No such file or directory
```

### useradd version

```bash
rpm -qa | grep shadow-utils
```
```
shadow-utils-4.15.1-1.fc40.x86_64
```

## Related issue

This issue seems to be related to:
- [Error in Fedora with the lastlog file and useradd.](https://www.reddit.com/r/Fedora/comments/1eurfm0/error_in_fedora_with_the_lastlog_file_and_useradd)
- https://github.com/shadow-maint/shadow/issues/1072
   - The bug is new in 4.15.1: https://github.com/shadow-maint/shadow/commit/f45498a6c2867c26ecfd388e15cadf73d12b98eb
   - PR merged but not currently released: https://github.com/shadow-maint/shadow/pull/1073

## Conclusion

This issue is due to an external bug, and it's been addressed by the `useradd` tool maintainer.

**Closed by vikman90** 2024-09-26 11:31 UTC
Labels: type/bug, level/task
