### ISSUE TITLE
Analysisid returns "null" instead of null

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh#17331] opened 2023-05-30 13:30 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0 | Azure wodle| Manager/Agent | - | - |

## Description
During the investigation of `"null"` values in the Azure integration module described in Issue [16703](https://github.com/wazuh/wazuh/issues/16703) it was found that the error does not come from the integration itself. 

Throughout the ingestion process, from Azure to sending the data over the socket, the `null` value remains `null`, but has been found to appear as `"null"` in `alerts.json`. We think the problem is related to `analysisd`.

**Comment by vikman90** [comment] 2023-06-01 10:56
@RamosFe It's not a bug, it's a feature!

This is a duplicate of:
- https://github.com/wazuh/wazuh/issues/669
- https://github.com/wazuh/wazuh/pull/677

wazuh-analysisd can parse JSON but it handles fields as string-string key-value pairs. It must convert integers, booleans, null values, and even lists into strings.

You can select how to deal with null values in the `<decoder>`. Simply add:
```xml
<json_null_field>discard</json_null_field>
```

## Test log

```json
{"azure_tag": "azure-storage", "name":"sample event 1","null_content": null ,"contents":{"simple":"simple value","list":[1,2,3]}}
```

### Current behavior

<details><summary>Alert</summary>

```json
{
  "timestamp": "2023-06-01T11:55:49.684+0200",
  "rule": {
    "level": 3,
    "description": "Azure: Storage",
    "id": "87803",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "azure"
    ]
  },
  "agent": {
    "id": "000",
    "name": "Rocket"
  },
  "manager": {
    "name": "Rocket"
  },
  "id": "1685613349.1260181",
  "decoder": {
    "name": "json"
  },
  "data": {
    "azure_tag": "azure-storage",
    "name": "sample event 1",
    "null_content": "null",
    "contents": {
      "simple": "simple value",
      "list": [
        1,
        2,
        3
      ]
    }
  },
  "location": "/root/test/test.log"
}
```

</details>

### Alternate behavior

- Add this decoder to _/var/ossec/ruleset/decoders/0006-json_decoders.xml_, before the **_json_** decoder:

```xml
<decoder name="azure">
  <prematch>"azure_tag": "azure-</prematch>
  <plugin_decoder>JSON_Decoder</plugin_decoder>
  <json_null_field>discard</json_null_field>
</decoder>
```

- Change the source decoder to `azure` in _/var/ossec/ruleset/rules/0555-azure_rules.json_:

```xml
<rule id="87801" level="3">
  <decoded_as>json</decoded_as>
  <field name="azure_tag">azure-log-analytics</field>
  <description>Azure: Log analytics</description>
  <options>no_full_log</options>
</rule>

<rule id="87802" level="3">
  <decoded_as>json</decoded_as>
  <field name="azure_tag">azure-ad-graph</field>
  <description>Azure: AD $(activity)</description>
  <options>no_full_log</options>
</rule>

<rule id="87803" level="3">
  <decoded_as>json</decoded_as>
  <field name="azure_tag">azure-storage</field>
  <description>Azure: Storage</description>
  <options>no_full_log</options>
</rule>
```

You'll find that the resulting alert dropped the fields with null values:

<details><summary>Alert</summary>

```json
{
  "timestamp": "2023-06-01T12:41:40.766+0200",
  "rule": {
    "level": 3,
    "description": "Azure: Storage",
    "id": "87803",
    "firedtimes": 1,
    "mail": false,
    "groups": [
      "azure"
    ]
  },
  "agent": {
    "id": "000",
    "name": "Rocket"
  },
  "manager": {
    "name": "Rocket"
  },
  "id": "1685616100.1260922",
  "decoder": {
    "name": "azure"
  },
  "data": {
    "azure_tag": "azure-storage",
    "name": "sample event 1",
    "contents": {
      "simple": "simple value",
      "list": [
        1,
        2,
        3
      ]
    }
  },
  "location": "/root/test/test.log"
}
```

</details>

Let me close this issue as we don't need to fix anything in wazuh-analysisd. Feel free to reopen it if you don't agree.

Best!

**Closed by vikman90** 2023-06-01 10:56 UTC
Labels: type/bug, duplicated, invalid, module/analysis, level/task
