### ISSUE TITLE
Windows agent logcollector having recurring trouble processing SID

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh#1274] opened 2018-09-10 14:17 UTC
On a Windows Server 2012 R2 AWS EC2 instance running Wazuh agent 3.6.0 I keep seeing clusters of errors like this in the logs every few minutes when the windows.debug level is set to 1.

I have seen Wazuh complaints about SID resolution before on other Windows systems, like maybe a year or so ago, but I don't usually have windows debug logging turned on so I don't know how often this is really happening across my other systems.

```
2018/09/10 14:07:50 ossec-agent: DEBUG: Could not convert SID to string which returned (87)
2018/09/10 14:07:50 ossec-agent: DEBUG: Performing a LookupAccountSid() on (unknown)
2018/09/10 14:07:50 ossec-agent: DEBUG: Could not convert SID to string which returned (87)
2018/09/10 14:07:50 ossec-agent: DEBUG: Performing a LookupAccountSid() on (unknown)
2018/09/10 14:07:50 ossec-agent: DEBUG: Could not convert SID to string which returned (87)
2018/09/10 14:07:50 ossec-agent: DEBUG: Performing a LookupAccountSid() on (unknown)
2018/09/10 14:07:50 ossec-agent: DEBUG: Could not convert SID to string which returned (87)
2018/09/10 14:07:50 ossec-agent: DEBUG: Performing a LookupAccountSid() on (unknown)
```

In case it helps, here is the agent.conf file received by this agent from the manager:

```
<agent_config>
  <client_buffer>
    <!-- Agent buffer options -->
    <disable>no</disable>
    <queue_size>2500</queue_size>
    <events_per_second>100</events_per_second>
  </client_buffer>
</agent_config>

<!-- config section for specific operating system -->
<agent_config os="Windows">
<!-- Log analysis -->
  <localfile>
    <location>Application</location>
    <log_format>eventlog</log_format>
  </localfile>

  <localfile>
    <location>Security</location>
    <log_format>eventchannel</log_format>
    <query>Event/System[EventID != 5145 and EventID != 5156 and EventID != 5447]</query>
  </localfile>

  <localfile>
    <location>System</location>
    <log_format>eventlog</log_format>
  </localfile>

  <localfile>
    <location>C:\Program Files (x86)\ossec-agent\active-response\active-responses.log</location>
    <log_format>syslog</log_format>
  </localfile>

  <!-- Policy monitoring -->
  <rootcheck>
    <disabled>no</disabled>
    <windows_audit>./shared/win_audit_rcl.txt</windows_audit>
    <windows_apps>./shared/win_applications_rcl.txt</windows_apps>
    <windows_malware>./shared/win_malware_rcl.txt</windows_malware>
  </rootcheck>

<!-- System inventory -->
<wodle name="syscollector">
  <disabled>no</disabled>
  <interval>1h</interval>
  <scan_on_start>yes</scan_on_start>
  <hardware>yes</hardware>
  <os>yes</os>
  <network>yes</network>
  <packages>yes</packages>
  <ports all="no">yes</ports>
  <processes>yes</processes>
</wodle>

<syscheck>
   <disabled>no</disabled>
   <scan_on_start>yes</scan_on_start>
   <frequency>300</frequency>
   <directories check_all="yes" whodata="yes" realtime="yes" report_changes="yes">C:/apple</directories>
   <directories check_all="yes" whodata="yes">C:/orange</directories>
</syscheck>

  <!-- Active response -->
  <active-response>
    <disabled>no</disabled>
    <ca_store>wpk_root.pem</ca_store>
  </active-response>

  <!-- Choose between plain or json format (or both) for internal logs -->
  <logging>
    <log_format>plain</log_format>
  </logging>
</agent_config>
```

And the local ossec.conf on the Windows system:

```
<ossec_config>
  <client>
    <server>
      <address>10.0.0.132</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <config-profile>windows2012</config-profile>
    <notify_time>60</notify_time>
    <time-reconnect>300</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>
  <active-response>
    <disabled>no</disabled>
  </active-response>
</ossec_config>
```

**Comment by crolopez** [comment] 2018-12-19 14:43
Hi @branchnetconsulting,

First of all, I'm sorry for the late response.

The reason for this repetitive debug message is because logcollector searches for specific fields in Windows events, which may be or not there. More specifically, the message is because logcollector is looking for the UserID field in events that don't have it, and that means that logcollector can't process it.

Despite this, we are working on a new logcollector format that allows to extract all fields of Windows events dynamically. You can see this development in https://github.com/wazuh/wazuh/pull/2142.

Since it is expected behavior, let me close the issue. 

Thanks for your feedback!

Best regards.

**Closed by crolopez** 2018-12-19 14:43 UTC
