### ISSUE TITLE
fim_db_search: Agent '000' Couldn't decode fim sum

### ISSUE THREAD

**Issue by mehdimch-star** [wazuh/wazuh#22361] opened 2024-03-05 06:40 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.2-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

Hi,
When activating the integrity check in wazuh for rhel version3 by agentless module, it returns the following error message:

ossec-analysisd: WARNING: at fim_db_search: Agent '000' Couldn't decode fim sum ':85cd458ab2103a0d90753fd63ca3305b:85d14d8dfcf9decc229dffb7cae4e54bc7ed7f95'

**Comment by vikman90** [comment] 2024-03-05 11:15
@mehdimch-star This issue is a duplicate of #14406 and stems from a problem caused by the redesign in Wazuh v3.7.0:
- #1333
 
Prior to this update, the manager stored each agent's file inventory in text files, essentially acting as "databases." However, when we migrated this data to Wazuh DB, we ceased support for agentless devices. This is because the manager now maintains a database for each agent ID, and agentless devices lack such identifiers. In the best-case scenario, the inventory of all devices would be amalgamated under the default "000" agent (the manager itself). 

We need to reconsider how we handle file inventories for agentless devices. Please keep posted on #14406. Thank you.

Best regards.

**Closed by vikman90** 2024-03-05 11:15 UTC
Labels: type/bug, duplicated, reporter/community, module/agentless
