### ISSUE TITLE
Wazuh dashboard doesn't show GCP posture management alerts from custom rules.

### ISSUE THREAD

**Issue by Rolly-M** [wazuh/wazuh#21538] opened 2024-01-18 18:43 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0 | Wazuh component | Manager | Packages | Amazon AMI |

As part of the test requirements for [Release 4.8.0 - Alpha 2 - E2E UX tests - GCP integration](https://github.com/wazuh/wazuh/issues/21371) I had to test the GCP integration use cases for Posture management [Blogpost](https://wazuh.com/blog/cloud-security-posture-management/). I did the configuration as explained.

<details>
<summary>GCP integration config</summary>

```xml
<ossec_config>
  <gcp-pubsub>
    <pull_on_start>yes</pull_on_start>
    <interval>5m</interval>
    <project_id><PROJECT_ID></project_id>
    <subscription_name><SUBSCRIPTION_ID></subscription_name>
     <credentials_file>/var/ossec/wodles/gcloud/credentials.json</credentials_file>
  </gcp-pubsub>
</ossec_config>
```

</details>

<details>
<summary>/var/ossec/etc/rules/gcp_posture.xml</summary>

```xml
<group name="gcp,">

  <!-- Misconfiguration detection -->
    <rule id="100200" level="10">
        <if_sid>65000</if_sid>
        <field name="gcp.finding.findingClass">MISCONFIGURATION</field>
        <description>A $(gcp.finding.findingClass) with $(gcp.finding.severity) severity has been discovered on the GCP project $(gcp.resource.projectDisplayName). $(gcp.finding.description)</description>
        <mitre>
          <id>T1562</id>
        </mitre>
    </rule>
    

  <!-- Threat detection -->
    <rule id="100201" level="10">
        <if_sid>65000</if_sid>
        <field name="gcp.finding.findingClass">THREAT</field>
        <description>A $(gcp.finding.findingClass) with $(gcp.finding.severity) severity has been discovered on the GCP project $(gcp.resource.projectDisplayName). $(gcp.finding.category).</description>
        <mitre>
          <id>T1562</id>
        </mitre>
    </rule>
   
</group>
```

</details>

After I restarted the wazuh server I didn't get alerts on the wazuh dashboard as per the configured alerting rules. Instead I get a normal `NOTICE` alerts for the firewall rule creation:

![image](https://github.com/wazuh/wazuh/assets/99815109/1df8bf0b-0363-4935-9d20-2f0b1635f689)

I checked the `/var/ossec/logs/alerts/alerts.log` and actually got one of the firewall rule creation log below:

```console
{"timestamp":"2024-01-18T14:24:51.593+0000","rule":{"level":3,"description":"GCP notice event on project wazuh-dev-258815, monitored resource type: gce_firewall_rule.","id":"65042","firedtimes":3,"mail":false,"groups":["gcp"]},"agent":{"id":"000","name":"wazuh-server"},"manager":{"name":"wazuh-server"},"id":"1705587891.311040","decoder":{"name":"json"},"data":{"integration":"gcp","gcp":{"insertId":"t5af03e4fvkm","logName":"projects/wazuh-dev-258815/logs/cloudaudit.googleapis.com%2Factivity","operation":{"first":"true","id":"operation-1705587741437-60f3917762d96-e4fb2947-21a31dc5","producer":"compute.googleapis.com"},"protoPayload":{"@type":"type.googleapis.com/google.cloud.audit.AuditLog","authenticationInfo":{"principalEmail":"rolly.mougoue@wazuh.com"},"authorizationInfo":[{"granted":true,"permission":"compute.firewalls.create","resource":"projects/wazuh-dev-258815/global/firewalls/verybadrule","resourceAttributes":{"name":"projects/wazuh-dev-258815/global/firewalls/verybadrule","service":"compute","type":"compute.firewalls"}},{"granted":true,"permission":"compute.networks.updatePolicy","resource":"projects/wazuh-dev-258815/global/networks/default","resourceAttributes":{"name":"projects/wazuh-dev-258815/global/networks/default","service":"compute","type":"compute.networks"}}],"methodName":"beta.compute.firewalls.insert","request":{"@type":"type.googleapis.com/compute.firewalls.insert","alloweds":[{"IPProtocol":"all"}],"direction":"INGRESS","disabled":"false","logConfig":{"enable":"false"},"name":"verybadrule","network":"projects/wazuh-dev-258815/global/networks/default","priority":"1000","sourceRanges":["0.0.0.0/0"]},"requestMetadata":{"callerIp":"74.58.13.46","callerSuppliedUserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36,gzip(gfe),gzip(gfe)","requestAttributes":{"reason":"8uSywAYQGg5Db2xpc2V1bSBGbG93cw","time":"2024-01-18T14:22:22.158995Z"}},"resourceLocation":{"currentLocations":["global"]},"resourceName":"projects/wazuh-dev-258815/global/firewalls/verybadrule","response":{"@type":"type.googleapis.com/operation","id":"1617200115163106034","insertTime":"2024-01-18T06:22:21.887-08:00","name":"operation-1705587741437-60f3917762d96-e4fb2947-21a31dc5","operationType":"insert","progress":"0","selfLink":"https://www.googleapis.com/compute/beta/projects/wazuh-dev-258815/global/operations/operation-1705587741437-60f3917762d96-e4fb2947-21a31dc5","selfLinkWithId":"https://www.googleapis.com/compute/beta/projects/wazuh-dev-258815/global/operations/1617200115163106034","startTime":"2024-01-18T06:22:21.902-08:00","status":"RUNNING","targetId":"1961932358051728114","targetLink":"https://www.googleapis.com/compute/beta/projects/wazuh-dev-258815/global/firewalls/verybadrule","user":"rolly.mougoue@wazuh.com"},"serviceName":"compute.googleapis.com"},"receiveTimestamp":"2024-01-18T14:22:22.851151626Z","resource":{"labels":{"firewall_rule_id":"1961932358051728114","project_id":"wazuh-dev-258815"},"type":"gce_firewall_rule"},"severity":"NOTICE","timestamp":"2024-01-18T14:22:21.469704Z"}},"location":"Wazuh-GCloud"}
```

**Comment by AlexRuiz7** [comment] 2024-01-23 11:33
We couldn't reproduce the problem and the environment in which the tests were carried out has been deleted, so we can't check the logs either.

The information shown in the dashboard and the alert data in `alerts.json` match, so indexer and dashboard are working properly. The rules that trigger these alerts have been reviewed by @wazuh/threat-intel, and they are also correct.

Because of all these reasons, I'm closing the issue.

**Comment by lchico** [comment] 2024-07-24 17:49
I reopened this issue because this happened to me while I was testing this issue: https://github.com/wazuh/wazuh/issues/24858#issuecomment-2245471601.

**Closed** 2024-07-26 13:46 UTC
Labels: type/bug, level/task
