### ISSUE TITLE
syslog_output limit the message lenght

### ISSUE THREAD

**Issue by truyennt07** [wazuh/wazuh#8907] opened 2021-06-07 03:51 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|4.1.5-1|syslog_output|Manager|Sources|CentOS Linux VERSION=7 (Core)|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

I set syslog_output to send the json log to other system but I found the syslog message was limited since the ossec-csyslogd send message over UDP protocol. Could we add the protocol option to the syslog_output config to set it to TCP?

**Comment by antoniomanuelfr** [comment] 2021-06-07 07:29
Hi @truyennt07.

This issue seems like a duplicate of the issue https://github.com/wazuh/wazuh/issues/7637. 
As you mention, at this moment, `ossec-csyslogd` is unable to send messages over TCP, only via UDP. 
We are aware of this limitation and we hope to improve this behavior as soon as our workflow allows us. 

One possible workaround is to use `ossec-integratord`. With this module, you can send the alerts to a python script and using the python script to forward the message to the server where you want to store the logs. If you want to try it, you can check this [blog post](https://wazuh.com/blog/how-to-integrate-external-software-using-integrator/) where there is an example of how to use integratord.

**Comment by antoniomanuelfr** [comment] 2021-06-15 08:41
Hi @truyennt07 

Let me close this issue in favor of https://github.com/wazuh/wazuh/issues/7637.
If you have any other doubts, don't hesitate to ask or re-open this issue if it's necessary.

Kind regards.

**Closed by antoniomanuelfr** 2021-06-15 08:41 UTC
Labels: community, core/syslog output, duplicate
