### ISSUE TITLE
All agents offline after several hours

### ISSUE THREAD

**Issue by sempervictus** [wazuh/wazuh#336] opened 2017-12-29 18:46 UTC
We usually set up Wazuh for servers, in routed environments with static IPs. A recent workstation deployment with the server being an AWS instance and the agents residing on mostly OSX systems with variable IPs, behind NATs has brought to light a strange issue: after several hours or days of operation, agents slowly go offline, and dont show up as online until the wazuh-manager and wazuh-api are restarted (manager seems to be the critical service).

Since we're not routed with rational source IPs (this is over the WAN), its a bit hard to figure out from netstat/lsof which machine is connected and when (they often share src addrs since theyre in offices behind the same SNAT). All agent-server comms are TCP, so this isn't a "we use grams" issue.

This is Wazuh 2.1.1 and we can't push to 3 due to ES6 breaking all the things (though its easier here than in other places if that HAS to happen).

**Comment by vikman90** [comment] 2018-01-09 10:53
Hi @sempervictus,

If you find error logs in the manager or your agents, they may help us to figure out the cause of this issue.

I can advance you that Wazuh 3.0 fixes some bugs in TCP connections that occur when multiple components try to send data at the same time, this may corrupt the session until the agent reconnects and some errors like these may appear in the logs:

```
ERROR: Too big message size from manager.
ERROR: Incorrect message size from manager.
```

All these bugs have been fixed in Wazuh 3.0, no known communication issues using TCP exist in Wazuh 3.0 and 3.1.

Hope it help.
Best regards.

**Closed** 2018-03-12 18:53 UTC
