### ISSUE TITLE
Multiple timeout messages in the API

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#19221] opened 2023-09-25 17:13 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.3 RC 1 | API | Manager | Packages | CentOS 7 |

## Description

- In the analysis of the issue https://github.com/wazuh/wazuh/issues/19179, multiple error messages have been found in the API:

```
manager/var/ossec/logs/api.log:2023/09/24 00:00:52 ERROR: Timeout executing API request
```

This is related to the issue: https://github.com/wazuh/wazuh/issues/18456 and fixed in https://github.com/wazuh/wazuh/pull/18733, it is necessary to investigate if the cause is the same or not

**Comment by Selutario** [comment] 2023-09-26 09:55
## Update

The bug fixed in https://github.com/wazuh/wazuh/pull/18733 was related to the rotation of API logs. There was a race condition whereby, sometimes, only the error messages:
```
2023/08/28 17:13:08 ERROR: Timeout executing API request
2023/08/28 17:13:32 ERROR: Timeout executing API request
2023/08/28 17:13:55 ERROR: Timeout executing API request
2023/08/28 17:14:19 ERROR: Timeout executing API request
2023/08/28 17:14:43 ERROR: Timeout executing API request
2023/08/28 17:15:07 ERROR: Timeout executing API request
``` 

and not the requests that caused it were logged. E.g.: 
```
2023/09/23 00:00:51 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.039s: 500
2023/09/23 00:01:02 ERROR: Timeout executing API request
2023/09/23 00:01:02 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.088s: 500
2023/09/23 00:01:12 ERROR: Timeout executing API request
2023/09/23 00:01:12 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.061s: 500
2023/09/23 00:01:22 ERROR: Timeout executing API request
```

In other words, it was related to which logs were printed, not the reason behind the printed errors. This does seem to be solved after @fdalmaup's PR, since all the attached `api.log` contain an entry for each request used.

Regarding the timeout problem, there are two things to mention:

### 1. Lack of resources

The first API timeouts start on `2023/09/22 14:37:12`:
```
2023/09/22 14:34:40 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 1.417s: 200
2023/09/22 14:34:40 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.105s: 200
2023/09/22 14:34:47 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 1.505s: 200
2023/09/22 14:34:47 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.158s: 200
...
2023/09/22 14:36:39 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 6.489s: 200
2023/09/22 14:36:41 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 1.262s: 200
2023/09/22 14:36:56 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.485s: 200
2023/09/22 14:36:57 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.372s: 200
2023/09/22 14:37:12 ERROR: Timeout executing API request
2023/09/22 14:37:12 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.086s: 500
2023/09/22 14:37:22 ERROR: Timeout executing API request
```

And the last one occurs on `2023/09/24 07:52:24`, that is, 12 hours before the end of the test:
```
2023/09/24 07:52:08 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 10.756s: 200
2023/09/24 07:52:08 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.318s: 200
2023/09/24 07:52:24 ERROR: Timeout executing API request
```

If we look at the FD plot, we can see that right during the period where the API timeouts occur, the use of file descriptors by `wazuh-logcollector` or `wazuh-modulesd` seems to be reaching a limit:
![image](https://github.com/wazuh/wazuh/assets/23361101/6db7e18f-dcd9-450e-bb52-3ca62f12fefe)

The start and end of API timeouts happen on the same day and time as heavy FD usage by another service. Therefore, it does not seem like an API bug but rather a lack of system resources.

To generate a token (as part of `GET /security/user/authenticate`), the API must access its DB:
https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/framework/wazuh/rbac/preprocessor.py#L124-L136

and also read the API private and public key files:
https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/api/api/authentication.py#L104-L107

Therefore, if there are not enough FDs available, these actions will probably end up queued and their response time will be delayed enough to generate a timeout.

### 2. Incorrect management of API tokens

Another problem, although it is not the origin of the error, is that a token is being requested prior to each API request:
```
2023/09/24 20:32:59 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 2.814s: 200
2023/09/24 20:32:59 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.145s: 200
2023/09/24 20:33:06 INFO: wazuh 127.0.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 2.263s: 200
2023/09/24 20:33:06 INFO: wazuh 127.0.0.1 "GET /manager/daemons/stats" with parameters {"daemons_list": "wazuh-analysisd,wazuh-remoted"} and body {} done in 0.083s: 200
```

API tokens last 15 minutes by default and, ideally, should not be re-requested until the previous one has expired (return code `401`) or is close to expiring. Failure to do so leads to wasted resources.

**Comment by Selutario** [comment] 2023-09-26 12:59
Issue to fix this:
- https://github.com/wazuh/wazuh-jenkins/issues/5699

**Comment by rauldpm** [comment] 2023-09-26 13:32
Maybe related: https://github.com/wazuh/wazuh/issues/19222

**Comment by Selutario** [comment] 2023-10-06 09:25
We need to keep on investigating what resource or process is affecting the response time of `GET /security/user/authenticate` in the API:
- https://github.com/wazuh/wazuh-jenkins/pull/5735

**Comment by mhamra** [comment] 2023-10-06 20:33
## ENDPOINT GET /security/user/authenticate TIMEOUTS INVESTIGATION

The GET /security/user/authenticate endpoint is mapped to the controller async function login_user

https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/api/api/controllers/security_controller.py#L70-L103

This coroutine makes Distributed API calls to the get_permission function and the get_security_conf function (indirectly). It also calls the generate_keypair function in line 177.

The function get_permission makes a query to the RBAC SQLite DB to return the roles mapped to the user and the authorization context. 

https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/framework/wazuh/rbac/preprocessor.py#L118- L136

The function get_security_conf returns the security configuration from a yaml file.
https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/api/api/authentication.py#L134-L137

The function generate_keypair also accesses a file to read the private and public key generated on the first call to the function.
https://github.com/wazuh/wazuh/blob/9087982b0c4ae0180bcdcd214a2b243e75cd8416/api/api/authentication.py#L91-L111

To determine if the endpoint is affected by disk contention, I recommend caching the return value of these functions and running the test again. If the timeout is not observed after caching both functions, we can determine the root cause of the timeout problem.

If problems are still present without accessing the disk, probably the saturated resource is the CPU. The must CPU-intensive call is maybe jwt.encode.

**Comment by mhamra** [comment] 2023-10-10 04:23
### UPDATE
- Created a new branch feature/19221-cache-auth-endpoint-functions with the functions decorated with cache
- Tested that they are working in a local dev environment by running the AITs
- Created packages to prepare for running the Stress Test pipeline.

**Comment by wazuhci** [comment] 2023-10-10 21:51
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release candidate issue #** | #                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.5.3                                      |
| **Release candidate #** | RC1                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/4.5.3-rc1 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `warehouse-test`
- Package revision: `w19221`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/4463/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/monitor-manager-Test_stress_B4463_manager-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/plots/Test_stress_B4463_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4463_manager_2023-10-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/logs/ossec_Test_stress_B4463_manager_2023-10-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B4463_manager-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/data/monitor-manager-Test_stress_B4463_manager-warehouse-test.csv)
[Test_stress_B4463_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/data/Test_stress_B4463_manager_analysisd_events.csv)
[Test_stress_B4463_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/data/Test_stress_B4463_manager_analysisd_state.csv)
[Test_stress_B4463_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_manager_centos/data/Test_stress_B4463_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/monitor-agent-Test_stress_B4463_centos-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/Test_stress_B4463_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/Test_stress_B4463_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/Test_stress_B4463_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/plots/Test_stress_B4463_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4463_centos_2023-10-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/logs/ossec_Test_stress_B4463_centos_2023-10-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4463_centos-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/data/monitor-agent-Test_stress_B4463_centos-warehouse-test.csv)
[Test_stress_B4463_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_centos/data/Test_stress_B4463_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_FD.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/Test_stress_B4463_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/Test_stress_B4463_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/Test_stress_B4463_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/plots/Test_stress_B4463_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4463_ubuntu_2023-10-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/logs/ossec_Test_stress_B4463_ubuntu_2023-10-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B4463_ubuntu-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/data/monitor-agent-Test_stress_B4463_ubuntu-warehouse-test.csv)
[Test_stress_B4463_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_ubuntu/data/Test_stress_B4463_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_USS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/monitor-winagent-Test_stress_B4463_windows-warehouse-test_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/Test_stress_B4463_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/Test_stress_B4463_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/Test_stress_B4463_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/plots/Test_stress_B4463_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B4463_windows_2023-10-10.zip](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/logs/ossec_Test_stress_B4463_windows_2023-10-10.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B4463_windows-warehouse-test.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/data/monitor-winagent-Test_stress_B4463_windows-warehouse-test.csv)
[Test_stress_B4463_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/warehouse-test/4.5.3/B4463-60m/B4463_agent_windows/data/Test_stress_B4463_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by mhamra** [comment] 2023-10-11 15:28
### CONCLUSION OF ENDPOINT GET /security/user/authenticate TIMEOUTS INVESTIGATION
I've run the stress test with an API source code with cached functions to verify if disk contention could be the root cause of the observed API timeouts.

I've processed the API log of the 24-hour and 1-hour stress tests to compare API call durations and timeouts.

### GET /security/user/authenticate DURATION
|  | 24-hours| 1-hour|
|---|---|---|
| count  |8022.000000  |342.000000|
|mean      |3.768330    |5.159237|
|std       |3.427487    |3.509518|
|min       |0.972000    |0.779000|
|max      |16.387000   |10.937000|

The table shows that the duration is similar in both tests. While the mean is higher in the 1-hour test, the max is higher in the 24-hour test.

### GET /security/user/authenticate TIMEOUTS
|  | 24-hours| 1-hour|
|---|---|---|
|count|499| 59|
|% timeouts|6,2%| 17,2%|

The number of timeouts was higher in the 1-hour test.

**Comment by fdalmaup** [comment] 2023-10-12 20:17
# Review

The analysis and comparison between the execution of the carried out stress tests were accurate and well performed, but the original stress test was 2.5 days long, not 24 hours. Please modify those values to avoid confusion.

I agree with the last conclusion regarding the `monitor.py` script. Since it is not part of the load of the stress test, it should be enhanced to prevent it from influencing the results of said test. In case the timeout messages persist after the modifications on the said script, we should continue the analysis of the API endpoint and the rest of the resources when requests are made to stressed environments.

**Comment by Selutario** [comment] 2024-03-20 15:58
I'm closing this for now since the problem wasn't reported again. In the last footprint metrics, only two timeouts can be found:
- https://github.com/wazuh/wazuh/issues/22098

**Closed by Selutario** 2024-03-20 15:58 UTC
Labels: type/bug, level/task, qa_known
