### ISSUE TITLE
Error in manager: couldn't sync agent '001' group

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#2968] opened 2019-03-28 16:37 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0 | Manager | Packages/Sources | OS version |

Hello team

  We noticed that an error message is showed in the manager when this process is done in Centos:
1.- Install Manager and Agent.
2.- Modify the agent ossec.conf with the manager IP.
3.- Register the agent. 
4.- Restart the agent. 
5.- After some seconds, remove the agent from the manager with `manage_agents -r 001`. 

Then, the error `ERROR: Couldn't sync agent '001' group` appears. 

Best regards,
Alberto R.

**Comment by DaveVG1** [comment] 2019-03-29 16:02
Summary
---
- I've discovered the cause of this bug in the following line:
https://github.com/wazuh/wazuh/blob/cb15c02820a49bb47bca57f10c603445e2748f86/src/addagent/validate.c#L837
This access to the database lasts enough to make other callings get the `SQLite` error: `SQLITE_BUSY`. This makes that the agent isn't deleted from `agent` table (from `global.db`) because the database was busy.

**Comment by crolopez** [comment] 2019-04-12 15:42
Fixed in https://github.com/wazuh/wazuh/pull/2997.

**Closed** 2019-04-12 18:34 UTC
