### ISSUE TITLE
Segmentation fault (`libpython3.9.so`) when starting the Wazuh Manager

### ISSUE THREAD

**Issue by fedepacher** [wazuh/wazuh#14400] opened 2022-07-21 12:52 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.3.6 |Manager | Package | Repository | Ubuntu 18.04.6 LTS (Bionic Beaver) |

## Description

Following the [step-by-step](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html) guide to install the Wazuh Manager, a **segmentation fault** message appears after executing `systemctl start wazuh-manager.service`.

Operating system details:

```
Operating System: Ubuntu 18.04.6 LTS (Bionic Beaver)
Kernel: Linux 4.15.0-177-generic
Architecture: x86-64
```

>Note: This error seems to occur randomly, and I have not been able to reproduce it again.

## Evidences

When I try to start Wazuh Manager after a clean installation: 

```
root@ubuntu1:/home/vagrant# systemctl start wazuh-manager
Job for wazuh-manager.service failed because the control process exited with error code.
See "systemctl status wazuh-manager.service" and "journalctl -xe" for details.

root@ubuntu1:/home/vagrant# systemctl status wazuh-manager
wazuh-manager.service - Wazuh manager
   Loaded: loaded (/usr/lib/systemd/system/wazuh-manager.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2022-07-21 11:06:49 UTC; 23s ago
  Process: 8266 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=1/FAILURE)

Jul 21 11:06:39 ubuntu1 systemd[1]: Starting Wazuh manager...
Jul 21 11:06:40 ubuntu1 env[8266]: Starting Wazuh v4.3.6...
Jul 21 11:06:49 ubuntu1 env[8266]: Segmentation fault (core dumped)
Jul 21 11:06:49 ubuntu1 env[8266]: wazuh-apid did not start correctly.
Jul 21 11:06:49 ubuntu1 systemd[1]: wazuh-manager.service: Control process exited, code=exited status=1
Jul 21 11:06:49 ubuntu1 systemd[1]: wazuh-manager.service: Failed with result 'exit-code'.
Jul 21 11:06:49 ubuntu1 systemd[1]: Failed to start Wazuh manager.
```

```
root@ubuntu1:/home/vagrant# dmesg
[  504.859425] python3[8336]: segfault at 25cffffffe7 ip 00007f8d9beebab0 sp 00007ffd14ba85e8 error 4 in libpython3.9.so.1.0[7f8d9bc55000+424000]
```

## Steps to reproduce

It has been trying to reproduce the error but with no luck to do it. This fault seems to be random.

**Comment by AdriiiPRodri** [comment] 2022-07-26 13:33
## Status update

Considering the information we have, we have come to the conclusion that this was a punctual error and that if this error exists it would be present in all the versions of Wazuh that use Python 3.9.

In addition, we have also made a search through the official Python channels looking for this bug and we have found an issue that may be similar to the problem that occurred at the Wazuh startup: https://github.com/python/cpython/issues/90619.

The bug reported in the issue is similar to the one that occurred in the Wazuh startup, with the difference that in the case of Kodi, the error was consistent, however, in our case it is not.

Therefore, a possible solution to this bug is to upgrade Python to 3.9.13 or 3.10 as we are doing in this issue: https://github.com/wazuh/wazuh/issues/13366, however this is just an assumption as we can not guarantee that the bug on our side is exactly the same as the one fixed in https://github.com/python/cpython/issues/90619.

References:
- https://linux.debian.bugs.dist.narkive.com/2tgtNpUs/bug-975393-hexchat-segfault-on-startup-after-b2-build
- https://issuehint.com/issue/beetbox/beets/4011
- https://bugs.python.org/issue46461
- https://github.com/python/cpython/issues/90619
- https://github.com/python/cpython/issues/92036
- https://discourse.nixos.org/t/kodi-crashes-as-soon-as-any-addon-is-started/17941
- https://bugs.gentoo.org/744028
- https://forum.kodi.tv/showthread.php?tid=356701
- https://bugzilla.redhat.com/show_bug.cgi?id=1656388

**Comment by davidjiglesias** [comment] 2022-09-29 09:42
We have not been able to reproduce it, it has not appeared again anywhere.

**Closed by davidjiglesias** 2022-09-29 09:42 UTC
Labels: module/framework, module/api, reporter/qa, type/bug/crash
