### ISSUE TITLE
FIM crashes with segmentation fault

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh#9737] opened 2021-08-17 11:34 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.2.0-rc7 | Syscheck | Agent | Packages | Red Hat 7.5 |

We found that `wazuh-syscheckd` was not running in the agent, and this log was in the system log:

```
messages-20210815:Aug 13 00:45:34 ip-10-0-1-16 kernel: wazuh-syscheckd[6880]: segfault at 7f1fc8078000 ip 00007f1fcd6a38ba sp 00007f1fc7ffbbc0 error 6 in libc-2.17.so[7f1fcd614000+1c4000]
```

|Instruction pointer|Offset|File|Function address|Function|
|---|---|---|---|---|
|`00007f1fcd6a38ba`|`7f1fcd614000`|/lib64/libc-2.17.so|`8f8ba`|`__memmove_sse2`|

### Tracing the error

```shell
# objdump -DCgl /lib64/libc-2.17.so | grep -B100 8f8ba:
(...)
__memmove_sse2():
(...)
   8f89f:       74 21                   je     8f8c2 <__GI_memmove+0x102>
   8f8a1:       48 89 f2                mov    %rsi,%rdx
   8f8a4:       48 89 ee                mov    %rbp,%rsi
   8f8a7:       48 29 fb                sub    %rdi,%rbx
   8f8aa:       48 29 d6                sub    %rdx,%rsi
   8f8ad:       0f 1f 00                nopl   (%rax)
   8f8b0:       48 83 ea 01             sub    $0x1,%rdx
   8f8b4:       0f b6 0a                movzbl (%rdx),%ecx
   8f8b7:       48 39 da                cmp    %rbx,%rdx
   8f8ba:       88 0c 16                mov    %cl,(%rsi,%rdx,1)
```

### Code calling memmove in Syscheck

- [syscheck_audit.c:525](https://github.com/wazuh/wazuh/blob/39b4ff30a8a6f9b034240798ebbf43f4623ab625/src/syscheckd/whodata/syscheck_audit.c#L525)

**Comment by chemamartinez** [comment] 2021-08-24 07:45
Closing this issue since the cause of this crash is the one explained at https://github.com/wazuh/wazuh/issues/9032#issuecomment-903934240.

It was caused by the removal of directories in `/proc` while `readdir()` is consuming them. This situation occurs when Diamorphine is installed so the issue has been reported [to them](https://github.com/m0nad/Diamorphine/issues/31) as well.

Best regards.

**Closed by chemamartinez** 2021-08-24 07:45 UTC
Labels: bug, core/fim
