### ISSUE TITLE
A Timeout error is provided during Windows WPK upgrade

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#18329] opened 2023-08-10 12:27 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.5.1  | Manager/Agent | Packages | Windows 11/Windows Server 2012 R2|

## Description

After the testing performed in https://github.com/wazuh/wazuh-qa/issues/3260 the following error appears when we try to upgrade using a Windows agent:

```
Upgrading...

Failed upgrades:
    Agent 004 status: Timeout reached while waiting for the response from the agent

```

The environment used is a manager deployed in AWS and a Windows deployed with vagrant.

> The behavior for the success and rollback, it is the expected but the expected error is `Agent 001 status: Upgrade procedure exited with error code` 

## Evidences

The testing performed for different versions and the results can be found here https://github.com/wazuh/wazuh/issues/18248#issuecomment-1671897440

## Steps to reproduce

1. Prepare an environment with a 4.5.1 manager (AWS) and a 4.5.0 Windows agent (vagrant vm).

2. Upgrade the agent using `agent_upgrade` or the API:

  - `/var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.5.1-alpha1.wpk.fail_windows.wpk `.
  - `curl -k -X GET "https://localhost:55000/agents/outdated?pretty=true" -H  "Authorization: Bearer $TOKEN"`
  - `curl -k -X PUT "https://localhost:55000/agents/upgrade_custom?agents_list=001&file_path=/var/ossec/wazuh_agent_v4.5.1-alpha1.wpk.fail_windows.wpk&pretty=true" -H  "Authorization: Bearer $TOKEN"`

4. Check the results, `ossec.log`, and `C:\Program Files (x86)\ossec-agent\upgrade\upgrade.log`.

**Comment by vikman90** [comment] 2023-08-10 14:34
@roronoasins I guess this is the same problem as #14856.

Try to change this configuration in the manager:

```xml
<ossec_config>
  <agent-upgrade>
  <chunk_size>32768<chunk_size>
  </agent-upgrade>
</ossec_config>
```

If this gets the upgrade working, please close this issue as a duplicate.

Best.

**Comment by Deblintrake09** [comment] 2023-08-14 20:18
## Research results

After adding the proposed configuration on manager, the upgrade of windows agent was completed successfully.

```
root@ip-172-31-4-13:/home/qa# /var/ossec/bin/agent_upgrade -a 002 -f /home/qa/wazuh_agent_v4.5.1_windows.wpk

Upgrading...

Upgraded agents:
	Agent 002 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
```

Closing this issue as duplicate of https://github.com/wazuh/wazuh/issues/14856

**Closed by Deblintrake09** 2023-08-14 20:18 UTC
Labels: type/bug, duplicated, level/task
