### ISSUE TITLE
Wazuh API is not capable of fetching Wazuh Manager logs

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh#18939] opened 2023-09-11 11:23 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| v4.6.0-alpha1 | Wazuh API | Manager | Wazuh Stack - Step by step / OVA | AlmaLinux 8 / Amazon Linux 2 |

# Description

During https://github.com/wazuh/wazuh/issues/18851 exploratory step, it was found that Wazuh Dashboard was not capable of retrieving Wazuh Manager logs by "Wazuh>Managment>Logs", showing the following error

![image](https://github.com/wazuh/wazuh/assets/1791430/4082cdc6-5f06-41a1-8257-a3e0c93e350b)

Because this information is retrieved underneath by Wazuh API, a request was made using API Console, with the same results

![image](https://github.com/wazuh/wazuh/assets/1791430/1ebe38c9-775f-4ab4-bb2e-f28acaeda601)
![image](https://github.com/wazuh/wazuh/assets/1791430/8ea0471f-f5ce-4b5d-bec0-33f277b3e9ce)

@juliamagan was able to reproduce also using the Wazuh OVA VM

**Comment by Selutario** [comment] 2023-09-11 11:34
Could be related to:
- https://github.com/wazuh/wazuh/issues/17740

It was fixed in 4.8.0 since 4.6.0 was frozen and there was no patch, but we can migrate it.

**Comment by jnasselle** [comment] 2023-09-11 11:50
In fact @Selutario , after adding `json` logs are shown ok

![image](https://github.com/wazuh/wazuh/assets/1791430/61688604-c0b9-438b-8f0c-48caaacacc14)
![image](https://github.com/wazuh/wazuh/assets/1791430/ebf15208-f557-40d3-a2be-4459a1267a31)

**Comment by Selutario** [comment] 2023-09-11 11:55
This bug is a regression since `GET /manager/logs` was working fine in previous versions. Therefore, the fix [developed here](https://github.com/wazuh/wazuh/issues/18825#issuecomment-1712055073) should be migrated to 4.6.0 as part of this issue.

**Comment by GGP1** [comment] 2023-09-11 12:31
## Update

Cherry-picked changes from the 4.8.0 branch to 4.6.0 and made a rebase to clean up the commits.

**Closed** 2023-09-11 14:36 UTC
Labels: type/bug/regression, level/task
