### ISSUE TITLE
Cluster error while trying to terminate process in Demo Environment for 4.8.0 Beta 2

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#22149] opened 2024-02-26 19:02 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-beta2 | wazuh-cluster | Manager | Demo Environment | Amazon Linux 2 |

## Description
During the testing [Release 4.8.0 - Beta 2 - E2E UX tests - Demo environment](https://github.com/wazuh/wazuh/issues/22111) a warning was found in the cluster logs:
> No other log related to the process 11927 was found.
```shellsession
    2024/02/26 11:47:23 ERROR: [Cluster] [Main] Error while trying to terminate the process with ID 11927.
```

**Comment by davidjiglesias** [comment] 2024-03-06 10:34
Due to known failures in modulesd for v4.8.0 Beta 2, we close this issue as not reproducible.

**Closed** 2024-03-06 10:34 UTC
Labels: type/bug, level/task, qa_known
