### ISSUE TITLE
wazuh-agentd did not start

### ISSUE THREAD

**Issue by Robin-Sch** [wazuh/wazuh#17981] opened 2023-07-20 10:56 UTC
|Wazuh version|Component|Platform|
|---|---|---|
| 4.4.5 | Agent | debian 11 |

I'm using this docker compose file:
https://github.com/wazuh/wazuh-docker/blob/master/single-node/docker-compose.yml
(Changed every 4.8.0 to 4.4.5)

Installed agent using:
```
WAZUH_MANAGER='wazuh.manager' WAZUH_AGENT_GROUP='default' WAZUH_AGENT_NAME='xxx' apt install wazuh-agent
```
And made sure wazuh.manager resolves into 127.0.0.1

Then I ran:
```
sudo systemctl start wazuh-agent
```
Which gave
```
Starting Wazuh v4.4.5...
wazuh-execd already running...
debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
main.c:139 at main(): DEBUG: Wazuh home directory: /var/ossec
main.c:141 at main(): DEBUG: Started (pid: 2236951).
wazuh-agentd did not start
wazuh-agent.service: Control process exited, code=exited, status=1/FAILURE
wazuh-agent.service: Failed with result 'exit-code'.
wazuh-agent.service: Unit process 2224366 (wazuh-execd) remains running after unit stopped.
Failed to start Wazuh agent.
```

**Comment by MiguelazoDS** [comment] 2023-07-21 13:23
Hi @Robin-Sch, 

Regardless of the single-node deployment for the manager, did you follow this guide to install the agent? https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html 

I did a quick test with the same command using a Debian Bullseye VM and I could not reproduce this issue, of course in my case is not resolving correctly but that does not interfere with the installation of the agent. 

Where did you install the agent?

**Comment by Robin-Sch** [comment] 2023-07-22 09:12
First I ran the command shown in the wazuh dashboard to install an agent, which gave the same error/result
Then I uninstalled the agent, and installed it using the documentation you linked above
Both gave the same error/result (with no useful logs?)

**Comment by Robin-Sch** [comment] 2023-07-24 13:44
The agent is installed on the host, not inside a docker container
The server is installed via docker (the docker compose project)

**Comment by MiguelazoDS** [comment] 2023-07-24 13:53
Let's try this

- Stop the agent
- Set this `agent.debug=2` in `/var/ossec/etc/internal_options.conf`
- Start the agent
- Share the logs for wazuh-agentd 

To check the version you can use `manage-agents -V`

**Comment by Robin-Sch** [comment] 2023-07-24 14:04
Version is 4.4.5, which matches. I've never installed the agent before, so I doubt there is an old installation or anything which interferes.

Logs:
```
Starting Wazuh v4.4.5...
Started wazuh-execd...
wazuh-agentd[2407007] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
wazuh-agentd[2407007] main.c:139 at main(): DEBUG: Wazuh home directory: /var/ossec
wazuh-agentd[2407007] main.c:141 at main(): DEBUG: Started (pid: 2407007).
wazuh-agentd did not start
wazuh-agent.service: Control process exited, code=exited, status=1/FAILURE
wazuh-agent.service: Failed with result 'exit-code'.
wazuh-agent.service: Unit process 2406994 (wazuh-execd) remains running after unit stopped.
Failed to start Wazuh agent.
```

**Comment by MiguelazoDS** [comment] 2023-07-24 15:04
Mmm let's see if we can find more info. 

- Execute `systemctl stop wazuh-agent.service`
- What's the output of `ps -aux | grep wazuh`
- Execute `systemctl start wazuh-agent.service`
- What's the output of `journalctl -xe`

**Comment by Robin-Sch** [comment] 2023-07-24 15:07
```
root     2406994  0.0  0.0  24460  1024 ?        Sl   16:02   0:01 /var/ossec/bin/wazuh-execd
root     2456859  0.0  0.0   6240   644 pts/3    S+   17:05   0:00 grep wazuh
```
```
wazuh-agentd did not start
wazuh-agent.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ An ExecStart= process belonging to unit wazuh-agent.service has exited.
░░
░░ The process' exit code is 'exited' and its exit status is 1.
wazuh-agent.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ The unit wazuh-agent.service has entered the 'failed' state with result 'exit-code'.
wazuh-agent.service: Unit process 2406994 (wazuh-execd) remains running after unit stopped.
Failed to start Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has failed
░░ Defined-By: systemd
░░ Support: https://www.debian.org/support
░░
░░ A start job for unit wazuh-agent.service has finished with a failure.
░░
░░ The job identifier is 3792 and the job result is failed.
```

**Comment by MiguelazoDS** [comment] 2023-07-24 15:29
I would expect something like this

![image](https://github.com/wazuh/wazuh/assets/13010397/65a739e6-9b4c-458f-bc92-72ec8f658acb)

Please try killing the execd process before starting the service. `killall -9 wazuh-execd`

![image](https://github.com/wazuh/wazuh/assets/13010397/c98ba73e-4c8b-40ca-9803-f5e789252fb3)

**Comment by Robin-Sch** [comment] 2023-07-24 15:34
That still didn't fixed it.
```
Deleting PID file '/var/ossec/var/run/wazuh-execd-2406994.pid' not used...
Started wazuh-execd...
wazuh-agentd[2500905] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
wazuh-agentd[2500905] main.c:139 at main(): DEBUG: Wazuh home directory: /var/ossec
wazuh-agentd[2500905] main.c:141 at main(): DEBUG: Started (pid: 2500905).
wazuh-agentd did not start
wazuh-agent.service: Control process exited, code=exited, status=1/FAILURE
wazuh-agent.service: Failed with result 'exit-code'.
wazuh-agent.service: Unit process 2500887 (wazuh-execd) remains running after unit stopped.
Failed to start Wazuh agent.
```

**Comment by MiguelazoDS** [comment] 2023-07-24 16:20
Does this still fail using wazuh-control instead of systemctl?

**Comment by Robin-Sch** [comment] 2023-07-24 16:52
It's a fresh install, already tried cleaning and re-installing multiple times.
The agent does fail no matter whether it's connected to the manager (or well, the manager online is, I don't know if it connects) or not.

It also fails when I use `wazuh-control start`

**Comment by MiguelazoDS** [comment] 2023-07-25 12:52
Could you start every single process one by one using the flags `-fdd`? Let's if we can get more information.

**Comment by Robin-Sch** [comment] 2023-07-25 16:08
```
sudo ./wazuh-control start -fdd
wazuh-agentd[3612150] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
wazuh-agentd[3612150] main.c:139 at main(): DEBUG: Wazuh home directory: /var/ossec
wazuh-agentd[3612150] main.c:141 at main(): DEBUG: Started (pid: 3612150).
Starting Wazuh v4.4.5...
wazuh-execd already running...
wazuh-agentd[3612169] debug_op.c:70 at _log(): DEBUG: Logging module auto-initialized
wazuh-agentd[3612169] main.c:139 at main(): DEBUG: Wazuh home directory: /var/ossec
wazuh-agentd[3612169] main.c:141 at main(): DEBUG: Started (pid: 3612169).
wazuh-agentd did not start
```

**Comment by MiguelazoDS** [comment] 2023-07-28 18:09
I'm back with this, today I did a quick test deploying the manager the same way you did, although I don't see how can be related to the agent failure. I was not able to reproduce any error. This is what I did. 

- I deployed a Debian 11 VM (because I don't use Debian as host)
- Deployed the docker stack using the branch 4.4 
https://github.com/wazuh/wazuh-docker/tree/4.4/single-node
I execute each step detailed there. 
![2023-07-28_14-52](https://github.com/wazuh/wazuh/assets/13010397/da9a13c3-4aff-4b52-a662-480682921c62)
Everything started just fine
- Deployed an agent following this documentation. https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html
and using the same command you shared. 
![2023-07-28_14-57](https://github.com/wazuh/wazuh/assets/13010397/61ca728e-3c7b-4a01-9c35-bb0b685816ef)
I have to resolve the hostname wazuh.manager, but after that worked as expected.
- Finally in the UI I can the agent successfully registered.
![image](https://github.com/wazuh/wazuh/assets/13010397/3250fb52-1fc2-4511-a808-5ebbdd87c906)

I'll be asking if someone faced something similar to this, but from my side is not possible to reproduce any error.

**Comment by Dwordcito** [comment] 2023-08-07 02:08
Issue closed due to inactivity, thanks for being part of the community, if there is any pending question reopen the issue.

**Closed by Dwordcito** 2023-08-07 02:08 UTC
Labels: reporter/community

**Comment by aAbdman** [comment] 2023-12-14 21:55
Sorry to open this again, but was looking for a solution for the same problem which I did.
- Edit /var/ossec/etc/ossec.conf
- in 
<server>
      <address>**MANAGER_IP**</address> 
      <port>1514</port>
      <protocol>tcp</protocol>
  </server>
Add Server IP

- then 
#systemctl restart wazuh-agent

Hope this helps

**Comment by sshipway** [comment] 2024-02-28 01:51
Similar problem here; in the end the solution was to run
```
chown -R ossec.ossec /var/ossec
systemctl restart wazuh-agent
```
Looks like the filesystem had group access, which should have been enough, but not user access for the ossec user

**Comment by Tre-vor-W** [comment] 2024-03-30 04:05
> Sorry to open this again, but was looking for a solution for the same problem which I did found.
> 
> * Edit /var/ossec/etc/ossec.conf
> * in
>   `<server> <address>MANAGER_IP</address> <port>1514</port> <protocol>tcp</protocol> </server> `
> 
> Add Server IP address or domain name.
> 
> * Then
>   #systemctl restart wazuh-agent
> 
> Hope this helps

This helped me on 2 proxmox 8.1.8 hosts - the third didn't require it, it already had the IP address prefilled

**Comment by aghosh0605** [comment] 2024-10-30 04:46
> Similar problem here; in the end the solution was to run
> 
> ```
> chown -R ossec.ossec /var/ossec
> systemctl restart wazuh-agent
> ```
> 
> Looks like the filesystem had group access, which should have been enough, but not user access for the ossec user

I have 10 servers currently and from there only 2 servers are having the same issue. However, I installed **wazuh-agent** in the same way for all the servers. (By getting the wget or curl from the wazuh-dashboard **Add-Agent** section and then using systemctl to deploy)
Restarted the agent several times but still the issue persists. 

I don't have any **ossec** user or group for the command you provided. Below is the permission for the folder.
```bash
drwxr-x--- 15 root wazuh 4.0K Oct 21 14:44 ossec
```

Sorry for opening the issue again but was struggling with the issue for many days.
Please let me know how to fix it.

**Comment by sshipway** [comment] 2024-10-30 19:13
@aghosh0605 It appears your installation is the 'wazuh' user rather than 'ossec'.
I would suggest you use this, if your installation is mostly under that username:
```
chown -R wazuh.wazuh /var/ossec
systemctl restart wazuh-agent
```

**Comment by aghosh0605** [comment] 2024-11-06 04:43
> @aghosh0605 It appears your installation is the 'wazuh' user rather than 'ossec'. I would suggest you use this, if your installation is mostly under that username:
> 
> ```
> chown -R wazuh.wazuh /var/ossec
> systemctl restart wazuh-agent
> ```

It didn't work. I did the config yesterday and restarted the agent. However, within 24 hours again it is disconnected. I tried removing the agent and again installing it. Still, the issue persists. 
Please let me know if there is any permanent solution.

**Comment by sshipway** [comment] 2024-11-06 07:49
Sorry, I can only go with what worked for me!  Also I have a pretty old version of wazuh - I think yours is much newer.  You might want to try TrevorW's solution earlier (ensure using the manager IP rather than hostname in /var/ossec/etc/ossec.conf) to see if that helps?

**Comment by aghosh0605** [comment] 2024-11-13 04:40
In the end, nothing worked, so I tried a temporary solution. It's not the actual solution, but I am tired of restarting the service every day because no solution is working.
Just added automatic restart in systemd service config like below. To know where is the service config file, check `systemctl status wazuh-agent`

```bash
[Service]
...
Restart=always
RestartSec=3
```
Then just daemon-relaod with `systemctl daemon-relaod` and restart the service with `systemctl restart wazuh-agent`.
From now for any issue if the service crashes or stops, it will restart automatically with 3 sec buffer time.
However, for every update that occurs on wazuh-agent, the configs will be overwritten.
