### ISSUE TITLE
RBAC white agent endpoints integration tests failing

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#16750] opened 2023-04-18 14:39 UTC
|Wazuh version|Component|
|---|---|
| 4.6.0| Manager |

| Related |
| -- | 
| https://github.com/wazuh/wazuh-jenkins/issues/5066 |

## Description

During the development of https://github.com/wazuh/wazuh/issues/16714 and https://github.com/wazuh/wazuh/issues/16716 I found out that there were two endpoints tests failing in the `test_rbac_white_agent_endpoints` integration test.  The failure reason is not related to the changes introduced, and they fail in master as well. 

I started looking for the last pull request in which the API integrations test check executed these tests but I couldn't find any (at least in the last year). What I did find is a check that has been running for 7 months and 1 week -> https://github.com/wazuh/wazuh/pull/14835/checks?check_run_id=8326657900

These are the tests failing and their reasons:

`test_rbac_white_agent_endpoints.tavern.yaml::PUT /agents/group/{group_id}/restart`
```json
Test 'Restart all agents from group default (Partially allowed)' failed

{
  "data": {
    "failed_items": {
      "error": {
        "code": 4000,
        "message": "Permission denied: Resource type: agent:id",
        "remediation": "Please, make sure you have permissions to execute the current request. For more information on how to set up permissions, please visit https://documentation.wazuh.com/4.6/user-manual/api/rbac/configuration.html"
      }
    },
    "message": "Restart command was not sent to some agents"
  }
}
```

`test_rbac_white_agent_endpoints.tavern.yaml::PUT /agents/{agent_id}/group/{group_id}`

```json
Test 'Assign agent 008 to default (Allowed)' failed

{
  "data": {
    "failed_items": {
      "error": {
        "code": 1751,
        "message": "Could not assign agent to group",
        "remediation": "Agent already belongs to specified group, please select another agent"
      }
    },
    "message": "No agents were assigned to default"
  }
}
```

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment] 2023-04-18 19:05
## Update

Started reviewing and debugging the tests. I could solve one of the two (`PUT /agents/group/{group_id}/restart`) but I haven't find a solution for the other one yet.

**Comment by GGP1** [comment] 2023-04-19 17:18
## Update

The test fails when assigning an agent to a group because it already belongs to that group, I tried different agents and groups but none of those changes worked. I also reviewed the code in charge of the group assignment and it's working properly.

Furthermore, checking out other tests I found that there is one `test_agent_PUT_endpoints.tavern.yaml` that does the assignment successfully, and the `test_rbac_black_agent_endpoints.tavern.yaml` (which is the same as the one failing but with black mode)  doesn't even have this type of test.

I'm trying to set up an environment where I can run the tests and debug the agents and groups state at the same time. If there are no groups available for assignment, we may need to modify the environment.

**Comment by GGP1** [comment] 2023-04-21 15:29
## Update

Solved the remaining test failed and opened a pull request containing the changes. Moved the state to _pending review_.

**Comment by GGP1** [comment] 2023-05-04 12:18
## Update

Rebased branch to 4.5 as requested in the code review. Moving it to pending review again.

**Comment by GGP1** [comment] 2023-05-04 12:19
## Update

Rebased branch to 4.5 as requested in the code review. Moved it to pending review again.

**Comment by GGP1** [comment] 2023-05-05 18:44
## Update

We are investigating the reason why the test was working on `4.4` but started failing in `4.5`, here's what we know so far:

- The test is working in `4.3`, `4.4` but not in `4.5`.
- When removing an agent from all of the groups, it's added to the *default* one. Since `4.4` this is done by core, previously it was by framework.
- In `4.4`, when an agent is removed from all groups or all groups are deleted, the *default* group assignment is not taking place. However, we couldn't find changes in the code that indicate a bug was introduced in the transfer from framework to core in the `4.4` release.

**Comment by Selutario** [comment] 2023-05-08 12:51
## Update

@davidjiglesias and I have also been trying to reproduce this problem in `4.4`. Running the `test_rbac_white_agent_endpoints.tavern.yaml` with everything after line [1004](https://github.com/wazuh/wazuh/blob/94916de5ccefa2c8c97bc0044a6b217fb680e114/api/test/integration/test_rbac_white_agent_endpoints.tavern.yaml#L1004) removed and running the queries manually, we get the same behavior as described by Gaston.

### 1. Obtain 008 agent information
It has no groups as it can be seen in the API output
> `curl -k -X GET "https://localhost:55000/agents?pretty=true&agents_list=008&select=group,status" -H  "Authorization: Bearer $TOKEN"
`
```JSON
{
   "data": {
      "affected_items": [
         {
            "id": "008",
            "status": "disconnected"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected agents information was returned",
   "error": 0
}
```


### 2. Create `group1` and assign to agent 008


> `date && curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"group1\"}" && curl -k -X PUT "https://localhost:55000/agents/group?pretty=true&agents_list=008&group_id=group1" -H  "Authorization: Bearer $TOKEN"`

```JSON
lun 08 may 2023 14:04:04 CEST
{
   "message": "Group 'group1' created.",
   "error": 0
}{
   "data": {
      "affected_items": [
         "008"
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All selected agents were assigned to group1",
   "error": 0
}
```

<details>
<summary>ossec.log</summary>

```
2023/05/08 12:04:03 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: select-agent-group 7
2023/05/08 12:04:03 wazuh-remoted[33786] manager.c:1402 at lookfor_agent_group(): DEBUG: Agent '007' group is 'default'
2023/05/08 12:04:03 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: update-agent-data {"id":7,"version":"Wazuh v3.13.2","config_sum":"ab73af41699f13fdd81903b5f23d8d00","merged_sum":"4a8724b20dee0124ff9656783c490c4e","manager_host":"wazuh-master","node_name":"master-node","agent_ip":"192.168.80.12","labels":"#\"_manager_hostname\":wazuh-master\n#\"_agent_ip\":192.168.80.12\n#\"_node_name\":master-node\n#\"_wazuh_version\":Wazuh v3.13.2","connection_status":"active","sync_status":"synced","group_config_status":"synced","os_name":"Ubuntu","os_version":"18.04.5 LTS","os_major":"18","os_minor":"04","os_codename":"Bionic Beaver","os_platform":"ubuntu","os_uname":"Linux |wazuh-agent7 |5.15.0-70-generic |#77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 |x86_64","os_arch":"x86_64"}
2023/05/08 12:04:04 wazuh-modulesd:database[33893] wm_database.c:744 at wm_inotify_start(): DEBUG: inotify: i='0', name='group1', mask='1073742080', wd='2'
2023/05/08 12:04:04 wazuh-modulesd:database[33893] wm_database.c:812 at wm_inotify_push(): DEBUG: Adding 'etc/shared/group1' to path table.
2023/05/08 12:04:04 wazuh-modulesd:database[33893] wm_database.c:843 at wm_inotify_pop(): DEBUG: Taking 'etc/shared/group1' from path table.
2023/05/08 12:04:04 wazuh-modulesd:database[33893] wm_database.c:545 at wm_sync_file(): DEBUG: Synchronizing file 'etc/shared/group1'
2023/05/08 12:04:04 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: find-group group1
2023/05/08 12:04:04 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: insert-agent-group group1
2023/05/08 12:04:04 wazuh-modulesd:database[33893] wm_database.c:536 at wm_sync_shared_group(): DEBUG: wm_sync_shared_group(): 0.230 ms.
2023/05/08 12:04:04 wazuh-db[33628] main.c:324 at run_dealer(): DEBUG: New client connected (36).
2023/05/08 12:04:04 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: sync-agent-groups-get {"last_id":0, "condition":"all"}
2023/05/08 12:04:04 wazuh-db[33628] main.c:386 at run_worker(): DEBUG: Client 36 disconnected.
2023/05/08 12:04:04 wazuh-db[33628] main.c:324 at run_dealer(): DEBUG: New client connected (36).
2023/05/08 12:04:04 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: select-group-belong 008
2023/05/08 12:04:04 wazuh-db[33628] main.c:386 at run_worker(): DEBUG: Client 36 disconnected.
2023/05/08 12:04:04 wazuh-db[33628] main.c:324 at run_dealer(): DEBUG: New client connected (37).
2023/05/08 12:04:04 wazuh-db[33628] wdb_parser.c:821 at wdb_parse(): DEBUG: Global query: set-agent-groups {"mode":"append","sync_status":"syncreq","data":[{"id":008,"groups":["group1"]}]}
2023/05/08 12:04:04 wazuh-db[33628] main.c:386 at run_worker(): DEBUG: Client 37 disconnected.
2023/05/08 12:04:06 wazuh-remoted[33786] manager.c:764 at c_files(): DEBUG: Updating shared files sums.


```

</details>

Maybe being disconnected is the reason behind the `default` group not being assigned again. However, in some of our tests, I think that the agent was active while reproducing this same behavior with `default` group.

**Closed as completed** 2023-05-08 15:58 UTC
Labels: type/bug, module/api, level/task
