### ISSUE TITLE
Use API to upgrade agent with "agent_upgrade" tool.

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#4472] opened 2020-01-20 08:46 UTC
## Description

When running the "agent_upgrade" tool located in wazuh/bin, the following python script is used: https://github.com/wazuh/wazuh/blob/1cacad85497a8c52e08c5828773f71dabe76e65c/framework/scripts/agent_upgrade.py

This script does not use distributed calls. Therefore, when trying to upgrade an agent that is assigned to a worker node from the master node, an error such as the following appears:
```
MSG SENT: 078 com lock_restart -1
RESPONSE: err Cannot send request
Error 1715: Error sending WPK file: Cannot send request
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 167, in <module>
    main()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in main
    rl_timeout=-1 if args.timeout == None else args.timeout, use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.1-py3.7.egg/wazuh/agent.py", line 2159, in upgrade
    use_http=use_http)
  File "/var/ossec/framework/python/lib/python3.7/site-packages/wazuh-3.11.1-py3.7.egg/wazuh/agent.py", line 2010, in _send_wpk_file
    raise WazuhException(1715, data.replace("err ",""))
wazuh.exception.WazuhException: Error 1715 - Error sending WPK file: Cannot send request
```

## Fix

To make it easier to maintain and to avoid errors like this, it would be interesting to replace the script in the master node with an API call, which does implement call distribution. Thus, two separate structures that do the same function should not be maintained.

Currently, the way to avoid this error is to run the script from the worker node that corresponds to the agent you want to upgrade. 

More information can be found in this community thread:
https://groups.google.com/forum/#!searchin/wazuh/error$20upgraded$20some$20agents%7Csort:date/wazuh/sQ_FMKeFVjI/28thlDdiCAAJ

**Comment by crd1985** [comment] 2020-03-06 12:09
Duplicate of #2580

**Closed by crd1985** 2020-03-06 12:09 UTC
Labels: API, cluster, community, enhancement, framework
