### ISSUE TITLE
During the Wazuh upgrade from a quickstart deployment, the Kibana server password is not being set correctly.

### ISSUE THREAD

**Issue by sakib789** [wazuh/wazuh#25607] opened 2024-09-06 07:30 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.9.0 | Wazuh Dashboard |  | Quickstart | Ubuntu22.04 LTS |

Upgrade from 4.8.1 to 4.9.0

OS: Ubuntu 22.04

Initial installation: 4.8.1 using quickstart method. 

The indexer and the manager were running fine after the upgrade.

The Dashbaord service was up and running but on the Web interface, it was shown the Dashboard service is not ready yet.
Needed to change the password for the `kibanaserver` user.

`/usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -u kibanaserver -p '<New_Password>'`

![image](https://github.com/user-attachments/assets/b33d1291-c819-4e67-a4c0-ab0feb71e0ac)

Only updating the `<KIBANASERVER_PASSWORD>` password in the Wazuh dashboard keystore with the old password didn't work.

I also noticed some users faced the same issue during the upgrade.

Please look into this.

**Comment by iasdeoupxe** [comment] 2024-09-06 08:05
Duplicate of #25605

**Comment by gdiazlo** [comment] 2024-09-06 08:08
Closed in favor of https://github.com/wazuh/wazuh/issues/25605

**Closed by gdiazlo** 2024-09-06 08:08 UTC

**Comment by keerthanap0810** [comment] 2024-09-06 08:45
What's the solution for kubernetes deployment, as we run the 

`/usr/share/wazuh-indexer/plugins/opensearch-security/tools/wazuh-passwords-tool.sh -u kibanaserver -p '<New_Password>'`


above command 

outputs `The script should run as root`

**Comment by iasdeoupxe** [comment] 2024-09-06 09:55
@keerthanap0810 Support questions probably belongs to https://groups.google.com/g/wazuh/ and not to a closed Github issue...
