### ISSUE TITLE
Windows Agent is Unreachable

### ISSUE THREAD

**Issue by rafabailon** [wazuh/wazuh#22854] opened 2024-04-09 13:59 UTC
## Description

Related to https://github.com/wazuh/wazuh/issues/22823

During the tests of [Release 4.8.0 - Beta 5 - Integration tests](https://github.com/wazuh/wazuh/issues/22823) I have detected an error in Windows Agent. It seems that windows agents are unreachables. I have tried relaunching the builds but it persists.

<details>
  <summary>Pipeline Logs</summary>
  <br/>

```console
12:38:27  TASK [restart_wazuh : Restart wazuh on Windows] ********************************
12:38:27  task path: /home/ec2-user/workspace/Test_integration/ansible-roles/restart_wazuh/tasks/restart_wazuh.yaml:45
12:38:27  fatal: [ID2_B46809_Test_integration_windows_agent]: UNREACHABLE! => {
12:38:27      "changed": false,
12:38:27      "unreachable": true
12:38:27  }
12:38:27  
12:38:27  MSG:
12:38:27  
12:38:27  ssl: 
12:38:27  
12:38:27  PLAY RECAP *********************************************************************
12:38:27  ID2_B46809_Test_integration_windows_agent : ok=10   changed=8    unreachable=1    failed=0    skipped=40   rescued=0    ignored=0   
12:38:27  
12:38:27  Playbook run took 0 days, 0 hours, 4 minutes, 55 seconds
12:38:27  FATAL: command execution failed
12:38:27  hudson.AbortException: Ansible playbook execution failed
12:38:27  	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
12:38:27  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:430)
12:38:27  	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:351)
12:38:27  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
12:38:27  	at hudson.security.ACL.impersonate2(ACL.java:449)
12:38:27  	at hudson.security.ACL.impersonate(ACL.java:461)
12:38:27  	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
12:38:27  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
12:38:27  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
12:38:27  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
12:38:27  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
12:38:27  	at java.base/java.lang.Thread.run(Thread.java:829)
12:38:27  [Pipeline] }
12:38:27  ERROR: Ansible playbook execution failed
```

</details>

## Evidences

- Build (test_active_response): https://ci.wazuh.info/job/Test_integration/46782/
- Re-launch (test_active_response): https://ci.wazuh.info/job/Test_integration/46804/
- Build (test_agentd): https://ci.wazuh.info/job/Test_integration/46783/
- Re-launch (test_agentd): https://ci.wazuh.info/job/Test_integration/46809/
- Build (test_logcollector): https://ci.wazuh.info/job/Test_integration/46795/

**Comment by teddytpc1** [comment] 2024-04-09 17:40
Hi @rafabailon.
I have replayed the https://ci.wazuh.info/job/Test_integration/46782/ job and it succeeded. I was not able to reproduce the issue.
However, the AMI is a QA custom AMI, and the resource is being created in AWS. The owner of the pipeline should review why the instance is unreachable at some point in the job. Because the instance starts and a lot of Ansible tasks are performed in that instance previous to the unreachable error message.

**Comment by rafabailon** [comment] 2024-04-10 08:12
Hi @teddytpc1, 
Thanks for the clarification. Since the error is in the test environment, I change the project to QA Team to be reviewed.

**Comment by davidjiglesias** [comment] 2024-04-15 07:54
Since the error is not reproducible and we will not be running these tests much longer, I propose to close this issue.

**Closed by davidjiglesias** 2024-04-15 07:54 UTC
Labels: type/bug, level/task
