### ISSUE TITLE
Fix SSLError in API integration tests

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#9245] opened 2021-07-09 11:39 UTC
|Wazuh version|Component|
|---|---|
| 4.3.0 | Wazuh API Integration Tests |

Hello team,

We have a recurrent error in the API integration tests related to the SSL certificates when asking for a token:

```python
E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=55000): Max retries exceeded with url: /security/user/authenticate (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
```

It also shows **invalid credentials** errors sometimes. Checking the `api.log` we can see it:

```shellsession
2021/07/08 16:08:14 INFO: HTTPS is enabled but cannot find the private key and/or certificate. Attempting to generate them
2021/07/08 16:08:15 INFO: Generated private key file in WAZUH_PATH/api/configuration/ssl/server.key
2021/07/08 16:08:15 INFO: Generated certificate file in WAZUH_PATH/api/configuration/ssl/server.crt
2021/07/08 16:10:53 INFO: Listening on 0.0.0.0:55000..
2021/07/08 16:10:53 INFO: unknown_user 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.038s: 401
2021/07/08 16:10:53 INFO: unknown_user 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.023s: 401
2021/07/08 16:10:53 INFO: unknown_user 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.011s: 401
2021/07/08 16:10:54 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.430s: 200
2021/07/08 16:10:54 INFO: testing 172.20.0.1 "GET /syscollector/001/os" with parameters {"select": "os.name"} and body {} done in 0.182s: 200
2021/07/08 16:10:55 INFO: testing 172.20.0.1 "GET /security/user/authenticate" with parameters {} and body {} done in 0.490s: 200
```

We need to investigate if this error is environment related, implement a solution and also try to design a better mechanism to handle the token usage as we are asking for a new one for every test stage.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [x] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [x] Core (`framework/wazuh/core/tests/`)
  - [x] SDK (`framework/wazuh/tests/`)
  - [x] RBAC (`framework/wazuh/rbac/tests/`)
  - [x] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [x] Affected tests 
  - [x] Affected RBAC (black and white) tests
- [x] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [x] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [x] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [x] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [x] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [x] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

Regards,
Víctor

**Comment by noise-kngdm** [comment] 2021-07-16 15:12
## Issue update
Hello team,
after reviewing the logs of the testing environment it seems that the invalid credentials error is showing up because of a race condition, the manager is looking for the credentials of the testing user right after they've been added. Because of this, the logs will _sometimes_ show that unknown user message.

I've added a little fix in the login function of the test environment to avoid this.
https://github.com/wazuh/wazuh/blob/e350539f613619f638134705886bbbd751ec6a4d/api/test/integration/conftest.py#L31-L46

The debugging of the error of the TLS handshake, the stopper of this issue, is still ongoing.

Regards,
Gonzalo.

**Comment by noise-kngdm** [comment] 2021-07-19 13:50
Hello team,
after testing thoroughly the integration test environment, I've arrived to the conclusion that the error is due to another race condition in the testing environment. The series of test requests start before the API is ready to answer them, which translates in that `UNEXPECTED_EOF` error.
I'll investigate this and try to fix it in the following days.

Regards,
Gonzalo.

**Comment by noise-kngdm** [comment] 2021-07-20 12:34
Hello team,
to examine all the possible roots of the problem, I have deployed an environment which emulates the testing conditions of the API using `vagrant`. Now I'm the process to recreate the error in the emulated environment.

Regards,
Gonzalo.

**Comment by noise-kngdm** [comment] 2021-07-21 12:40
## Issue update
Hello team,
Before running the tests every testing container must be in a healthy status. This is checked in the managers using the following functions:
https://github.com/wazuh/wazuh/blob/3adf96c3e007844a55ee977500459291cda42ad7/api/test/integration/env/tools/healthcheck_utils.py#L46-L59

There are two checks interesting to this issue. 

- `check1`, which consists on executing `wazuh-control status` and ensuring that every daemon is in the desired state. This check is done comparing the output with a static file with the following content: 

https://github.com/wazuh/wazuh/blob/3adf96c3e007844a55ee977500459291cda42ad7/api/test/integration/env/configurations/base/manager/healthcheck/daemons_check.txt#L1-L16

The message `wazuh-apid is running...` will show up right after starting the api process, which doesn't mean that it is ready to get requests.

- `check2`, which verifies that  a line starting with `Listening on` exists in the api log.

The problem is that having `check1` doesn't mean that the API is ready to get requests, so `check2` should accomplish that. The library `aiohttp` is the one writing that message into the log, but it does it before it is actually running, as can be seen in the following code snippet.
```python
        if self.server == 'aiohttp':
            logger.info('Listening on %s:%s..', self.host, self.port)

            access_log = options.pop('access_log', None)

            if options.pop('use_default_access_log', None):
                access_log = logger

            web.run_app(self.app, port=self.port, host=self.host, access_log=access_log, **options)
``` 

To solve this issue, I'll change the health check so it makes a login request and get a `200` code as a response. I will then remove the previous fix, since this should solve both problems.

**Closed** 2021-08-02 08:01 UTC
Labels: API, bug, qa
