### ISSUE TITLE
Upgrading agents using agent_upgrade produce an internal error

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17934] opened 2023-07-17 09:34 UTC
| Wazuh version |
| ------------- |
| `v4.6.0-pre-alpha1`  |

### Description

During the upgrade process of both Linux and Windows agents, an internal error was encountered. The error message displayed was:
```
root@ip-172-31-14-246:/home/qa# /var/ossec/bin/agent_upgrade -a 001 -f /home/qa/wazuh_agent_v4.6.0_linux_x86_64.wpk

Upgrading...
Internal error: 'version'
```

However, despite the occurrence of these errors, the agent appears to have been successfully upgraded. This can be verified by checking the agent logs, where the following entry is found:

```
2023/07/17 08:16:45 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

Furthermore, confirming the upgrade can also be done through the agent_upgrade command, as shown below:
```
root@ip-172-31-14-246:/home/qa# /var/ossec/bin/agent_upgrade -l
ID    Name                                Version
002   EC2AMAZ-2BV3AJS                     Wazuh v4.4.5
```

No related error appears upgrading using the API:
```
curl -k -X GET "https://localhost:55000/agents/upgrade_result?agents_list=002&pretty=true" -H  "Authorization: Bearer $TOKEN"
{
   "data": {
      "affected_items": [
         {
            "message": "Success",
            "agent": "002",
            "task_id": 6,
            "node": "node01",
            "module": "upgrade_module",
            "command": "upgrade_custom",
            "status": "Updating",
            "create_time": "2023-07-17T08:48:47Z",
            "update_time": "2023-07-17T08:48:47Z"
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "All upgrade tasks were returned",
   "error": 0
}
```

### WPKs 

**Windows**: https://packages-dev.wazuh.com/warehouse/test/4.6/wpk/windows/wazuh_agent_v4.6.0_windows.wpk
**Linux**: https://packages-dev.wazuh.com/warehouse/test/4.6/wpk/linux/x86_64/wazuh_agent_v4.6.0_linux_x86_64.wpk

**Comment by TomasTurina** [comment] 2023-07-17 19:09
This error seems to be directly related to the `agent_upgrade` script, which belongs to @wazuh/framework.

It is failing at the time of retrieving the information of the upgrade procedure to be shown to the final user, that's why the upgrade executes successfully but the problem is with the response of the script.

We suppose the error is here:
```python
async def get_agents_versions(agents: list) -> dict:
    """Get the current versions of the specified agents.

    Parameters
    ----------
    agents : list
        List of agent's IDs.

    Returns
    -------
    dict
        Dictionary with the current version (prev_version).
    """
    f_kwargs = {
        "agent_list": agents,
        "select": ["version"],
        "limit": len(agents)
    }
    agent_versions = await cluster_utils.forward_function(get_agents, f_kwargs=f_kwargs)
    return {agent['id']: {"prev_version": agent['version'], "new_version": None}
            for agent in agent_versions.affected_items}
```

It is not finding the `version` inside the dict `agent`.

Moving this issue to the @wazuh/framework team so they can investigate it further.

**Comment by nico-stefani** [comment] 2023-07-24 19:41
# Issue Update

I was reproducing the error and getting more insights about it.

The problem is occurring after the update when the script tries to check the status of the agents.

```python
root@ubuntu-jammy:/var/ossec# bin/agent_upgrade -a 001 -f /home/vagrant/wazuh_agent_v4.6.0_linux_x86_64.wpk -d

Upgrading...
Internal error: 'version'
Traceback (most recent call last):
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 237, in <module>
    run(main())
  File "/var/ossec/framework/python/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/var/ossec/framework/python/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 221, in main
    await check_status(affected_agents=result.affected_items, result_dict=agents_versions,
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 183, in check_status
    else await get_agent_version(task_result['agent'])
  File "/var/ossec/framework/scripts/agent_upgrade.py", line 121, in get_agent_version
    return result['version']
  File "/var/ossec/framework/python/lib/python3.9/site-packages/wazuh-4.6.0-py3.9.egg/wazuh/core/results.py", line 49, in __getitem__
    return self.dikt[item]
KeyError: 'version'
```

**Closed** 2023-07-28 12:06 UTC
Labels: type/bug, level/task
