### ISSUE TITLE
Error while installing the Wazuh agent in AlpineLinux 3.12

### ISSUE THREAD

**Issue by davidcr01** [wazuh/wazuh#18411] opened 2023-08-14 11:49 UTC
# Description 
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-RC1 | Wazuh component | Agent | Sources | Alpine Linux 3.12.2 |

A new issue in the 4.5.1-RC1 testing has been found, specifically in https://github.com/wazuh/wazuh/issues/18387#issuecomment-1677162915.

When installing the Wazuh agent in the specified system, the following errors and warnings are generated:
```
alpine312:/home/vagrant# wget -O /etc/apk/keys/alpine-devel@wazuh.com
-633d7457.rsa.pub https://packages-dev.wazuh.com/key/alpine-devel%40w
azuh.com-633d7457.rsa.pub && echo "https://packages-dev.wazuh.com/pre
-release/alpine/v3.12/main" >> /etc/apk/repositories && apk update &&
 apk add wazuh-agent=4.5.1-r1
Connecting to packages-dev.wazuh.com (52.84.66.16:443)
saving to '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub'
alpine-devel@wazuh.c 100% |*********************|   800  0:00:00 ETA
'/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub' saved
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: UNTRUSTED signature
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/testing: UNTRUSTED signature
fetch https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.12.12-45-g8116a127ec [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v20200626-2940-gb0bea36da8 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v20200626-2939-g82163baa1b [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
2 errors; 17255 distinct packages available
```

The `apk add` command is not executed because the `apk update` command generates errors. If the `apk add` command is executed later, the Wazuh agent is installed.

Is necessary to investigate these errors. This behavior is not reproduced in Alpine Linux 3.18.2.

**Comment by vikman90** [comment] 2023-08-14 15:32
Moving this issue to the backlog, but we are **waiting for CICD** to report whether this issue is new in 4.5.1.

**Comment by davidcr01** [comment] 2023-08-14 15:56
@vikman90 this issue was not reported in the 4.5.0 testing. It is the first time we have seen this behavior.

**Comment by teddytpc1** [comment] 2023-08-14 17:49
I've been running some tests and could not reproduce the issue.

### 4.5.1

```BASH
# wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key
/alpine-devel%40wazuh.com-633d7457.rsa.pub && echo "https://packages-dev.wazuh.com/pre-release/alpin
e/v3.12/main" >> /etc/apk/repositories && apk update && apk add wazuh-agent=4.5.1-r1
Connecting to packages-dev.wazuh.com (3.160.90.102:443)
saving to '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub'
alpine-devel@wazuh.c 100% |****************************************************|   800  0:00:00 ETA
'/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub' saved
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
fetch https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.18.3-40-g630a645aead [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.3-40-g630a645aead [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
OK: 20071 distinct packages available
(1/8) Installing libintl (0.21.1-r7)
(2/8) Installing ncurses-terminfo-base (6.4_p20230506-r0)
(3/8) Installing libncursesw (6.4_p20230506-r0)
(4/8) Installing libproc2 (4.0.3-r1)
(5/8) Installing procps-ng (4.0.3-r1)
(6/8) Installing libgcc (12.2.1_git20220924-r10)
(7/8) Installing libstdc++ (12.2.1_git20220924-r10)
(8/8) Installing wazuh-agent (4.5.1-r1)
Executing wazuh-agent-4.5.1-r1.pre-install
Executing wazuh-agent-4.5.1-r1.post-install
Executing busybox-1.36.1-r2.trigger
OK: 28 MiB in 23 packages
```


### 4.5.0

```BASH
# wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key
/alpine-devel%40wazuh.com-633d7457.rsa.pub && echo "https://packages-dev.wazuh.com/pre-release/alpin
e/v3.12/main" >> /etc/apk/repositories && apk update && apk add wazuh-agent=4.5.0-r1
Connecting to packages-dev.wazuh.com (3.160.90.3:443)
saving to '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub'
alpine-devel@wazuh.c 100% |****************************************************|   800  0:00:00 ETA
'/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub' saved
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
fetch https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.18.3-40-g630a645aead [https://dl-cdn.alpinelinux.org/alpine/v3.18/main]
v3.18.3-40-g630a645aead [https://dl-cdn.alpinelinux.org/alpine/v3.18/community]
OK: 20071 distinct packages available
(1/8) Installing libintl (0.21.1-r7)
(2/8) Installing ncurses-terminfo-base (6.4_p20230506-r0)
(3/8) Installing libncursesw (6.4_p20230506-r0)
(4/8) Installing libproc2 (4.0.3-r1)
(5/8) Installing procps-ng (4.0.3-r1)
(6/8) Installing libgcc (12.2.1_git20220924-r10)
(7/8) Installing libstdc++ (12.2.1_git20220924-r10)
(8/8) Installing wazuh-agent (4.5.0-r1)
Executing wazuh-agent-4.5.0-r1.pre-install
Executing wazuh-agent-4.5.0-r1.post-install
Executing busybox-1.36.1-r2.trigger
OK: 28 MiB in 23 packages
```

**Comment by nmkoremblum** [comment] 2023-08-15 02:29
I couldn't reproduce it either.

- `4.5.1`
```
# wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub && echo "https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main" >> /etc/apk/repositories && apk update && apk add wazuh-agent=4.5.1-r1
--2023-08-15 02:23:02--  https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub
Resolving packages-dev.wazuh.com (packages-dev.wazuh.com)... 3.160.90.38, 3.160.90.102, 3.160.90.26, ...
Connecting to packages-dev.wazuh.com (packages-dev.wazuh.com)|3.160.90.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 800 [application/vnd.ms-publisher]
Saving to: '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub'

/etc/apk/keys/alpine-dev 100%[==================================>]     800  --.-KB/s    in 0s      

2023-08-15 02:23:04 (40.7 MB/s) - '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub' saved [800/800]

fetch https://mirrors.edge.kernel.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.edge.kernel.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.12.12-45-g8116a127ec [https://mirrors.edge.kernel.org/alpine/v3.12/main]
v3.12.12-46-g1df69604c4 [https://mirrors.edge.kernel.org/alpine/v3.12/community]
OK: 12771 distinct packages available
(1/5) Installing libproc (3.3.16-r0)
(2/5) Installing procps (3.3.16-r0)
(3/5) Installing libgcc (9.3.0-r2)
(4/5) Installing libstdc++ (9.3.0-r2)
(5/5) Installing wazuh-agent (4.5.1-r1)
Executing wazuh-agent-4.5.1-r1.pre-install
Executing wazuh-agent-4.5.1-r1.post-install
Executing busybox-1.31.1-r22.trigger
OK: 187 MiB in 92 packages
```
- `4.5.0`
```
# wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub && echo "https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main" >> /etc/apk/repositories && apk update && apk add wazuh-agent=4.5.0-r1
--2023-08-15 02:27:37--  https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub
Resolving packages-dev.wazuh.com (packages-dev.wazuh.com)... 3.160.90.38, 3.160.90.3, 3.160.90.102, ...
Connecting to packages-dev.wazuh.com (packages-dev.wazuh.com)|3.160.90.38|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 800 [application/vnd.ms-publisher]
Saving to: '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub'

/etc/apk/keys 100%     800  --.-KB/s    in 0s          

2023-08-15 02:27:39 (14.8 MB/s) - '/etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub' saved [800/800]

fetch https://mirrors.edge.kernel.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.edge.kernel.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
fetch https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
v3.12.12-45-g8116a127ec [https://mirrors.edge.kernel.org/alpine/v3.12/main]
v3.12.12-46-g1df69604c4 [https://mirrors.edge.kernel.org/alpine/v3.12/community]
OK: 12771 distinct packages available
(1/1) Downgrading wazuh-agent (4.5.1-r1 -> 4.5.0-r1)
Executing wazuh-agent-4.5.0-r1.pre-upgrade
Executing wazuh-agent-4.5.0-r1.post-upgrade
OK: 187 MiB in 92 packages
```
I only found an `Alpine 3.12.12` Vagrant box. I think @teddytpc1 you are using the same as well, as our outputs are similar., Maybe the problem is just related to `Alpine 3.12.2`?

**Comment by vikman90** [comment] 2023-08-16 11:41
@teddytpc1 I'm also unable to reproduce it.

## Dockerfiles

<details><summary>Dockerfile-3.12.2</summary>

```Dockerfile
FROM alpine:3.12.2

RUN wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub && \
    echo "https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main" >> /etc/apk/repositories && \
    apk update && \
    apk add wazuh-agent=4.5.1-r1
```

</details>

<details><summary>Dockerfile-3.18.3</summary>

```Dockerfile
FROM alpine:3.18.3

RUN wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub && \
    echo "https://packages-dev.wazuh.com/pre-release/alpine/v3.12/main" >> /etc/apk/repositories && \
    apk update && \
    apk add wazuh-agent=4.5.1-r1
```

</details>

## Build

<details><summary><code>docker build -t wazuh-test-3.12.2 - < Dockerfile-3.12.2</code></summary>

>[+] Building 4.6s (6/6) FINISHED                                                                         docker:default
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 362B                                                                               0.0s
 => [internal] load metadata for docker.io/library/alpine:3.12.2                                                   0.0s
 => [1/2] FROM docker.io/library/alpine:3.12.2                                                                     0.0s
 => [2/2] RUN wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/al  4.0s
 => exporting to image                                                                                             0.2s
 => => exporting layers                                                                                            0.2s
 => => writing image sha256:da598d0d0747fff1a5d7492b5840baaf8fda53213f1d1746d417ce243a712cbd                       0.0s
 => => naming to docker.io/library/wazuh-test-3.12.2                                                               0.0s

</details>

<details><summary><code>docker build -t wazuh-test-3.18.3 - < Dockerfile-3.18.3</code></summary>

>[+] Building 4.5s (6/6) FINISHED                                                                         docker:default
 => [internal] load build definition from Dockerfile                                                               0.1s
 => => transferring dockerfile: 362B                                                                               0.0s
 => [internal] load .dockerignore                                                                                  0.1s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/alpine:3.18.3                                                   0.0s
 => [1/2] FROM docker.io/library/alpine:3.18.3                                                                     0.0s
 => [2/2] RUN wget -O /etc/apk/keys/alpine-devel@wazuh.com-633d7457.rsa.pub https://packages-dev.wazuh.com/key/al  4.0s
 => exporting to image                                                                                             0.2s
 => => exporting layers                                                                                            0.2s
 => => writing image sha256:01bca3a1ed1a9e8916060e95ef0b5ddbfccdfd7532f565fe454dfbd078f86976                       0.0s
 => => naming to docker.io/library/wazuh-test-3.18.3                                                               0.0s
</details>

**Comment by davidcr01** [comment] 2023-08-16 12:43
I tested in Docker (3.12.0, 3.12.2, 3.12.3) and everything worked fine.
However, testing again with Vagrant, using the `alpine-linux/alpine-x86_64` box, the error is reproduced again. @vcerenu also could reproduce this behavior.

**Comment by nmkoremblum** [comment] 2023-08-16 15:28
The `alpine-linux/alpine-x86_64` vagrant box is broken. If you try to update `apk` with a fresh VM you get:
```
# apk update
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/community: UNTRUSTED signature
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge/testing: UNTRUSTED signature
v3.12.12-45-g8116a127ec [http://dl-cdn.alpinelinux.org/alpine/v3.12/main]
v20200626-2940-gb0bea36da8 [http://dl-cdn.alpinelinux.org/alpine/edge/community]
v20200626-2939-g82163baa1b [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
2 errors; 17247 distinct packages available
```
This might be related to the `musl` library and the 32-bit `time_t` variables which have been updated as stated in here:
- https://gitlab.alpinelinux.org/alpine/aports/-/issues/14043
- https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#musl_1.2
- https://gitlab.alpinelinux.org/alpine/aports/-/issues/11257

## Conclusion:

**The error is not related to Wazuh**, please, close this issue

**Closed** 2023-08-16 19:47 UTC
Labels: type/bug, level/task
