### ISSUE TITLE
Missing rules when retrieving the active configuration from the API

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#15725] opened 2022-12-20 10:53 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-40401 | Analysisd| Manager | Packages | CentOS 8 |

For the [development of statistics](https://github.com/wazuh/wazuh/issues/13099), new integration tests were requested for these statistics and for the configuration of the daemons. However, during the development of the integration test for the active configuration, an unexpected behavior was detected:

- If a rule has children rules, one child won't appear. For example:
  https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/ruleset/rules/0770-gitlab_rules.xml#L133-L148

  <details>
  <summary>API response</summary>

  ```json
                      {
                         "children":[
                            {
                               "sigid":65615,
                               "level":5,
                               "maxsize":0,
                               "frequency":0,
                               "timeframe":360,
                               "ignore_time":0,
                               "decoded_as":0,
                               "if_matched_sid":0,
                               "group":"gitlab_v.12",
                               "comment":"(Gitlab) ERROR:$(error).",
                               "if_sid":"65613",
                               "rule_file":"ruleset/rules/0770-gitlab_rules.xml",
                               "category":"syslog",
                               "field":[
                                  {
                                     "name":"error",
                                     "pattern":"\\.+",
                                     "type":"osregex",
                                     "negate":false
                                  }
                               ]
                            }
                         ],
                         "sigid":65613,
                         "level":3,
                         "maxsize":0,
                         "frequency":0,
                         "timeframe":360,
                         "ignore_time":0,
                         "decoded_as":258,
                         "if_matched_sid":0,
                         "group":"gitlab_v.12",
                         "comment":"Group of gitlab_sidekiq.",
                         "rule_file":"ruleset/rules/0770-gitlab_rules.xml",
                         "category":"syslog"
                      },
  ```

  </details>

 
- If a decoder has one child, the children list, will be empty. For example:

  https://github.com/wazuh/wazuh/blob/dacf07da9930c4445ea55b1e5cdf6c7baea9a8d6/ruleset/rules/0555-azure_rules.xml#L67-L72

  <details>
  <summary>API Response</summary>

   ```json
                      {
                         "children":[
                            
                         ],
                         "sigid":87803,
                         "level":3,
                         "maxsize":0,
                         "frequency":0,
                         "timeframe":360,
                         "ignore_time":0,
                         "decoded_as":305,
                         "if_matched_sid":0,
                         "group":"azure,",
                         "comment":"Azure: Storage",
                         "rule_file":"ruleset/rules/0555-azure_rules.xml",
                         "category":"syslog",
                         "field":[
                            {
                               "name":"azure_tag",
                               "pattern":"azure-storage",
                               "type":"osregex",
                               "negate":false
                            }
                         ]
                      },
  ```

</details>

- Some rules files are missing: 0215-policy_rules.xml, 0215-policy_rules.xml, 0215-policy_rules.xml, 0245-web_rules.xml, 0270-web_appsec_rules.xml, 0275-squid_rules.xml, 0330-sysmon_rules.xml, 0430-ms_wdefender_rules.xml, 0435-ms_logs_rules.xml, among others

This behavior is not new in 4.4.0, it has been reproduced in 4.3.10.

**Comment by vicferpoy** [comment] 2023-01-23 15:38
## Issue update

The affected endpoint is `GET /manager/configuration/{component}/{configuration}` (and its `cluster` version). This endpoint retrieves the component active configuration from its related socket:

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/framework/wazuh/manager.py#L204-L227

https://github.com/wazuh/wazuh/blob/9f896c311a2d1cf7922e88b98382aa55434bf45b/framework/wazuh/core/configuration.py#L839-L859

> **NOTE:** this code has been improved in `v4.5.0`, but the logic remains the same.

Debugging at this point, we can find that the `/var/ossec/queue/sockets/analysis` socket responds with the same information the Wazuh API does, missing the Gitlab rule from above.

Using the `wazuh-logtest` tool, we can confirm that at least the missing rules are loaded:

<details>

<summary>Gitlab sidekiq log example</summary>

```
2014-06-10T18:18:26Z 14299 TID-55uqo INFO: Booting Sidekiq 3.0.0 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq"}
```

</details>

```shellsession
root@wazuh-master:/# /var/ossec/bin/wazuh-logtest
Starting wazuh-logtest v4.4.0
Type one log per line

2014-06-10T18:18:26Z 14299 TID-55uqo INFO: Booting Sidekiq 3.0.0 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq"}

**Phase 1: Completed pre-decoding.
	full event: '2014-06-10T18:18:26Z 14299 TID-55uqo INFO: Booting Sidekiq 3.0.0 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq"}'

**Phase 2: Completed decoding.
	name: 'gitlab-sidekiq'
	parent: 'gitlab-sidekiq'
	info: 'Booting Sidekiq 3.0.0 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq"}'
	timestamp: '2014-06-10T18:18:26Z'

**Phase 3: Completed filtering (rules).
	id: '65614'
	level: '3'
	description: '(Gitlab) INFO:Booting Sidekiq 3.0.0 with redis options {:url=>"redis://localhost:6379/0", :namespace=>"sidekiq"}.'
	groups: '['gitlab_v.12']'
	firedtimes: '1'
	mail: 'False'
**Alert to be generated.

```

However, there must be a bug with `analysisd` on the active ruleset configuration reading.

**Comment by vikman90** [comment] 2023-01-24 10:49
@juliamagan @vicferpoy thanks for your comments!

I've found the cause of the problem:

- Decoders: [config_json.c:22](https://github.com/wazuh/wazuh/blob/3123b4d0f4fcb785bd073c298f381a0a7d164e4f/src/analysisd/config_json.c#L22)
- Rules: [config_json.c:237](https://github.com/wazuh/wazuh/blob/3123b4d0f4fcb785bd073c298f381a0a7d164e4f/src/analysisd/config_json.c#L237)

For each element, the algorithm is checking whether it has a sibling before reading it. That's why we're losing the last element of every list.

## Proposed fix

For each element, check whether it isn't null, then read it and get its sibling, in a loop.

**Comment by vicferpoy** [comment] 2023-01-24 12:44
Closed in favor of https://github.com/wazuh/wazuh/issues/15996.

**Closed by vicferpoy** 2023-01-24 12:44 UTC
Labels: reporter/qa
