### ISSUE TITLE
Wazuh agent log error in syscheck footprint tests - 4.3.11

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh#16841] opened 2023-04-21 10:32 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.3.11 | wazuh-agent | Agent | Packages | Windows |

We found the following error during the syscheck footprint tests for version 4.3.11:
https://github.com/wazuh/wazuh/issues/16835
```
2023/04/20 15:29:56 wazuh-agent: ERROR: (6704): Couldn't get path of '[x32] HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Services\\SharedAccess\\Parameters\\FirewallPolicy\\RestrictedServices\\Configurable\\System:51b607af-807a-4a45-b2cf-ca6596a6b3d7'
```

**Comment by davidjiglesias** [comment] 2023-04-21 10:41
Duplicate of https://github.com/wazuh/wazuh/issues/11090

**Closed** 2023-04-21 10:40 UTC
Labels: type/bug, module/agent, platform/windows, reporter/cicd, level/task
