### ISSUE TITLE
Can't modify installation path

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh#7213] opened 2021-01-19 09:08 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.4 | API | Manager | Sources | Linux |

Hello team!

We can modify the installation path using `PREFIX` in the compilation phase.

The issue is installation script always saves `framework/python` in `/var/ossec`:

![imagen](https://user-images.githubusercontent.com/17710550/105011590-693c5a80-5a3d-11eb-9a39-4284af8b109f.png)

It causes Wazuh manager doesn't start:

```
root@vmu20:/home/vagrant/wazuh/src# /opt/ossec/bin/wazuh-control status
wazuh-clusterd not running...
wazuh-modulesd not running...
wazuh-monitord not running...
wazuh-logcollector not running...
wazuh-remoted not running...
wazuh-syscheckd not running...
wazuh-analysisd not running...
wazuh-maild not running...
wazuh-execd not running...
wazuh-db not running...
wazuh-authd not running...
wazuh-agentlessd not running...
wazuh-integratord not running...
wazuh-dbd not running...
wazuh-csyslogd not running...
wazuh-apid not running...
root@vmu20:/home/vagrant/wazuh/src# /opt/ossec/bin/wazuh-control start
/opt/ossec/bin/wazuh-apid: 38: /opt/ossec/framework/python/bin/python3: not found
wazuh-apid: Configuration error. Exiting
```

Best regards,
Eva

**Comment by CarlosRS9** [comment] 2021-01-19 10:28
The following checkings have been performed:

### Installing Wazuh from sources - Master branch using PREFIX make parameter

**Steps followed:**
```
apt-get update && apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git vim -y
git clone https://github.com/wazuh/wazuh.git && cd wazuh/src && git checkout master
make clean && make deps && make TARGET=server DEBUG=yes PREFIX=/opt/ossec -j8 && ./../install.sh
```

**Output:**
```
make[1]: Leaving directory '/wazuh/src/external/cpython'
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
find: '/opt/ossec/framework/python': No such file or directory
make: *** [Makefile:1689: install_python] Error 1
Generating self-signed certificate for wazuh-authd...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
/opt/ossec/bin/wazuh-apid: 38: /opt/ossec/framework/python/bin/python3: not found
wazuh-apid: Configuration error. Exiting
```

After the installation the framework can be found in `/var/ossec/` instead of `/opt/ossec`:
```
root@9f4eeb2b0a35:/wazuh/src# ll /var/ossec/
total 16
drwxr-xr-x 3 root root 4096 Jan 19 09:28 ./
drwxr-xr-x 1 root root 4096 Jan 19 09:28 ../
drwxr-xr-x 3 root root 4096 Jan 19 09:28 framework/
root@9f4eeb2b0a35:/wazuh/src# ll /var/ossec/framework/
total 12
drwxr-xr-x 3 root root 4096 Jan 19 09:28 ./
drwxr-xr-x 3 root root 4096 Jan 19 09:28 ../
drwxr-xr-x 6 root root 4096 Jan 19 09:28 python/
```

### Installing Wazuh from sources - 4.0 branch (4.0.4) using PREFIX make parameter

**Steps followed:**
```
apt-get update && apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git vim -y 
git clone https://github.com/wazuh/wazuh.git && cd wazuh/src && git checkout 4.0
make clean && make deps && make TARGET=server DEBUG=yes PREFIX=/opt/ossec -j8 && ./../install.sh

```

**Output:**
```
make[1]: Leaving directory '/wazuh/src/external/cpython'
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
find: '/opt/ossec/framework/python': No such file or directory
make: *** [Makefile:1667: install_python] Error 1
Generating self-signed certificate for ossec-authd...
Building CDB lists...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
/opt/ossec/bin/wazuh-apid: 38: /opt/ossec/framework/python/bin/python3: not found
wazuh-apid: Configuration error. Exiting
```

After the installation the framework is present in `/var/ossec/` instead of `/opt/ossec`:
```
root@46d12f12775b:/wazuh/src# ll /var/ossec/
total 16
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 1 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 3 root root 4096 Jan 19 09:37 framework/
root@46d12f12775b:/wazuh/src# ll /var/ossec/framework/
total 12
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 6 root root 4096 Jan 19 09:37 python/
```

#### Installing Wazuh from sources - v4.0.0 tag using PREFIX make parameter

**Steps followed:**
```
apt-get update && apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git vim -y 
git clone https://github.com/wazuh/wazuh.git && cd wazuh/src && git checkout v4.0.0
make clean && make deps && make TARGET=server DEBUG=yes PREFIX=/opt/ossec -j8 && ./../install.sh

```

**Output:**
```
make[1]: Leaving directory '/wazuh/src/external/cpython'
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
find: '/opt/ossec/framework/python': No such file or directory
make: *** [Makefile:1667: install_python] Error 1
Generating self-signed certificate for ossec-authd...
Building CDB lists...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
/opt/ossec/bin/wazuh-apid: 38: /opt/ossec/framework/python/bin/python3: not found
wazuh-apid: Configuration error. Exiting
```

After the installation the framework is present in `/var/ossec/` instead of `/opt/ossec`:
```
root@46d12f12775b:/wazuh/src# ll /var/ossec/
total 16
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 1 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 3 root root 4096 Jan 19 09:37 framework/
root@46d12f12775b:/wazuh/src# ll /var/ossec/framework/
total 12
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 6 root root 4096 Jan 19 09:37 python/
```


#### Installing Wazuh from sources - v4.0.0 tag  WITHOUT using PREFIX make parameter

**Steps followed:**
```
apt-get update && apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git vim -y 
git clone https://github.com/wazuh/wazuh.git && cd wazuh && git checkout v4.0.0
make clean && make deps && ./install.sh
```
**Output:**
```
make[1]: Leaving directory '/wazuh/src/external/cpython'
find /opt/ossec/framework/python -name "*libpython3.8.so.1.0" -exec ln -f {} /opt/ossec/lib/libpython3.8.so.1.0 \;
find: '/opt/ossec/framework/python': No such file or directory
make: *** [Makefile:1667: install_python] Error 1
Generating self-signed certificate for ossec-authd...
Building CDB lists...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
/opt/ossec/bin/wazuh-apid: 38: /opt/ossec/framework/python/bin/python3: not found
wazuh-apid: Configuration error. Exiting
``
After the installation the framework is present in `/var/ossec/` instead of `/opt/ossec`:
```
root@46d12f12775b:/wazuh/src# ll /var/ossec/
total 16
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 1 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 3 root root 4096 Jan 19 09:37 framework/
root@46d12f12775b:/wazuh/src# ll /var/ossec/framework/
total 12
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ./
drwxr-xr-x 3 root root 4096 Jan 19 09:37 ../
drwxr-xr-x 6 root root 4096 Jan 19 09:37 python/
```

### Installing Wazuh from sources - 4.0 branch (4.0.4) WITHOUT make clean && make deps
**Steps followed:**
```
apt-get update && apt-get install python gcc make libc6-dev curl policycoreutils automake autoconf libtool git vim -y 
git clone https://github.com/wazuh/wazuh.git && cd wazuh && git checkout 4.0
./install.sh
```

**Output:**
```
Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/wazuh/src/external/cpython/Lib/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/wazuh/src/external/cpython/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 200, in _main
    return _bootstrap(
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 119, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/wazuh/src/external/cpython/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "<frozen zipimport>", line 241, in load_module
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 570, in _get_data
zipimport.ZipImportError: can't decompress data; zlib not available
make[1]: *** [Makefile:1187: install] Error 1
make[1]: Leaving directory '/wazuh/src/external/cpython'
make: *** [Makefile:1666: install_python] Error 2
Generating self-signed certificate for ossec-authd...
Building CDB lists...


 - System is Debian (Ubuntu or derivative).
 - Init script modified to start Wazuh during boot.
Starting Wazuh...
Traceback (most recent call last):
  File "/opt/ossec/api/scripts/wazuh-apid.py", line 10, in <module>
    from api import alogging, configuration
ModuleNotFoundError: No module named 'api'
wazuh-apid: Configuration error. Exiting
```

The error now is a different one. Additionally, framework now is present in the requested path (/opt/ossec). No `/var/ossec` folder was created this time.

### Conclusion

We can conclude the problem is not the PREFIX parameter but the `make deps` command. Regarding the zlib error raised when no `make deps` command was used, it can be fixed by installing `zlib1g-dev` and  `libsqlite3-dev` before attempting to install Wazuh. In that case, Wazuh installation finish without any error, the framework and the api are installed in the provided path and both works as expected.

We need to check why its necessary to manually install `zlib1g-dev` and  `libsqlite3-dev` when trying to install wazuh in a different path and why its not necessary when installing in the default path

**Closed** 2021-01-19 12:07 UTC
Labels: API, core/Makefile, framework
