### ISSUE TITLE
Rejecting mapping update to [wazuh-alerts-3.x-2020.02.03] as the final mapping would have more than 1 type: [wazuh, doc]

### ISSUE THREAD

**Issue by Sivasarathykb** [wazuh/wazuh#4554] opened 2020-02-03 11:56 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|3.11|wazuh|Manager|packages|rhel7|
| X.Y.Z-rev | Wazuh component | Manager/Agent | Packages/Sources | OS version |

**Comment by Sivasarathykb** [comment] 2020-02-03 11:57
Filebeat version 6.8.6
Elastic search version 6.8.6

**Comment by pablotr9** [comment] 2020-02-03 12:10
Hi @Sivasarathykb ,

Could you please share with us your Filebeat configuration file? You can find that file in `/etc/filebeat/filebeat.yml` 
Are you using only Filebeat or is Logstash also being used? In that case, could you also please share with us your Logstash configuration file? (`/etc/logstash/conf.d/01-wazuh.conf`)

Best Regards,
Pablo Torres

**Comment by Sivasarathykb** [comment] 2020-02-03 12:51
# Wazuh - Filebeat configuration file
filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: false

setup.template.json.enabled: true
setup.template.json.path: '/etc/filebeat/wazuh-template.json'
setup.template.json.name: 'wazuh'
setup.template.overwrite: true
setup.ilm.enabled: false

output.elasticsearch.hosts: ['http://x.x.x.x:9200']

Only filebeat is used.

**Comment by Sivasarathykb** [comment] 2020-02-03 12:57
I was using filebeat 7.5.1 now i have downgraded to 6.8.6 as i downgraded the elasticsearch from 7x to 6x. 
Wazuh filebeat.yml  for 6x only contains logstash configration parameters. So i have copied the 7x filebeat.yml template

**Comment by pablotr9** [comment] 2020-02-03 14:17
Hi @Sivasarathykb ,


Has Logstash been installed or has it been working before Filebeat was configured? It looks like the index (wazuh-alerts-3.x-2020.02.03) contains one document type (`wazuh`) and it's trying to index new documents with different document type (`_doc`) which is not allowed. On previous versions, Logstash was indexing documents with a different type than the one we use now with Filebeat.

Let's check how your stored documents look like, please do this request in Kibana Dev Tools:
`GET wazuh-alerts-3.x-2020.02.03/_search`

Let's now check Elasticsearch logs:
`tail -n 500 /var/log/elasticsearch/(clusterName--elasticsearch).log `
The output of above command will be huge, please paste that output in a file and attach it to your reply.

Best Regards,
Pablo Torres

**Comment by Sivasarathykb** [comment] 2020-02-03 14:48
No logstash was installed before, im was using only filebeat to send data to elasticsearch.

Result of - GET wazuh-alerts-3.x-2020.02.03/_search
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}

Attached the elasticsearch.log
[elasticsearch.log](https://github.com/wazuh/wazuh/files/4148453/elasticsearch.log)

**Comment by pablotr9** [comment] 2020-02-03 15:15
Hi @Sivasarathykb ,

Thanks for the output. The first command doesn't have any result, let's try again with a different existing index.
List all **wazuh-alerts*** indices:
`GET _cat/indices/wazuh-al*`
If there are indices, the output will look like this:
`green open wazuh-alerts-3.x-2020.02.02 sF2W5pe_QCOQHPH9IIpf9A 3 0 342 0 506.3kb 506.3kb`

Now, copy the name of one of those indices, in my example **wazuh-alerts-3.x-2020.02.02**, and then let's do the same request we did on my previous message:
`GET <INDEX_NAME>/_search`. 

Regarding the elasticsearch.log, it's full of error logs from non-wazuh indices, let's try filtering those logs:
`cat /var/log/elasticsearch/my-cluster.log | grep -i wazuh-alert`

Sorry for being repetitive with these 2 commands, but I need to see some extra logs.

Best Regards,
Pablo Torres

**Comment by Sivasarathykb** [comment] 2020-02-03 15:34
Below are the existing indices
green open wazuh-alerts-3.x-2020.02.01 SbkKf1pOQVK75sZI8-h73w 3 0 0 0 783b 783b
green open wazuh-alerts-3.x-2020.01.31 Y151alZKT26swoQPhDdDvg 3 0 0 0 783b 783b
green open wazuh-alerts-3.x-2020.02.02 uodgZx5uTT2I7FZF6D67EA 3 0 0 0 783b 783b
green open wazuh-alerts-3.x-2020.02.03 5BlVTj--SCWkoeenDz1JgQ 3 0 0 0 783b 783b
green open wazuh-alerts-3.x-2020.01.30 ci_rMQ_ZR1mTSO79Zb_EFw 3 0 0 0 783b 783b


I'm getting the below output for all the aove index
{
  "took" : 0,
  "timed_out" : false,
  "_shards" : {
    "total" : 3,
    "successful" : 3,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : 0,
    "max_score" : null,
    "hits" : [ ]
  }
}
Attached the elasticsearch log
[elasticsearch.log](https://github.com/wazuh/wazuh/files/4148664/elasticsearch.log)

**Comment by pablotr9** [comment] 2020-02-04 09:25
Hi @Sivasarathykb ,

Sorry for the late reply, I have just replicated your environment and I'm having the same issue. Indeed the problem is with document types of our indices (they differ from version 6.x to 7x).

I guess that you are using the `wazuh-template.json` for Elasticsearch v6.x (https://github.com/wazuh/wazuh/blob/master/extensions/elasticsearch/6.x/wazuh-template.json) 
that template was created to be used with Logstash, that's the reason why you are getting this error.

In your case, as you are using only Filebeat, please check the line 14 in that template (/etc/filebeat/wazuh-template.json)
```
    "wazuh": {
```
To make it work, just replace that line with

```
    "doc": {
```
Now restart Filebeat. This way, you don't create indices with `wazuh` type anymore so you can avoid that error.
Now that you replaced that line, please delete existing indices that have the previous wrong mapping:
(In Kibana Dev Tools)
`DELETE wazuh-alerts-3.x-2020*` 
This request will delete all wazuh-alerts indices, but I saw in your previous message they are all empty, so there won't be any problem.

Please let me know if it helps or if you have any other questions!

Best Regards,
Pablo Torres

**Comment by Sivasarathykb** [comment] 2020-02-04 10:09
It Worked!!. Able to create index without any error and able to get the data in Kibana..
Thanks for you support Pablo Torres...

**Comment by pablotr9** [comment] 2020-02-04 10:14
Hi @Sivasarathykb ,

Great! You are welcome. I'll close this issue, if you have any other suggestion or bug report please do not hesitate to open a new issue. For questions/support, you can also use our Slack community channel or join our Google group https://wazuh.com/community/.

Best Regards,
Pablo Torres

**Closed by pablotr9** 2020-02-04 10:14 UTC
Labels: community, help wanted

**Comment by Sivasarathykb** [comment] 2020-02-04 11:30
It Worked!!!. Able to create index without any erros and to data is populated in kibana.
Thanks a lot for your support Pablo Torres
