### ISSUE TITLE
Prevent Syscollector from repeating inventory data reports

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#2203] opened 2019-01-03 15:22 UTC
It has been proven that a high percentage of the events that come to the Manager are Syscollector events, especially packet scanning. 

We could considerably reduce the work of the manager if we used the same methodology as the FIM, with a hash table that stores the content of each scan we can know if there has been any change from one scan to another and simply send the necessary information to the manager.

This issue is based on some questions asked by Jürgen in #1245.
Thanks, @juergenc.

**Comment by vikman90** [comment] 2020-05-11 09:01
@bah07 thanks for opening this issue. This is a duplicate of #3940, that is in progress.

Cheers!

**Closed by vikman90** 2020-05-11 09:01 UTC
Labels: core/syscollector, enhancement
