### ISSUE TITLE
Starting Wazuh manager in containers leads to zombie processes

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#19829] opened 2023-10-24 15:23 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | Wazuh Manager | Manager | Sources | Ubuntu Jammy |

### Description

It has been verified that running a Wazuh manager version 4.7.0 within an Ubuntu Jammy container leads to the emergence of zombie processes.

This problem has only been observed when initiating the manager via an exec command within a new bash shell.

This issue emerged while resolving the Docker image used for system testing, as documented on GitHub at https://github.com/wazuh/wazuh-qa/issues/4592.

**Steps to reproduce**

 -   Launch a Docker Jammy instance with a bash shell
```
docker run -it --entrypoint /bin/bash ubuntu:jammy
```
-   [Install the necessary dependencies for source installation](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html):

```
apt-get update
apt-get install python3 gcc g++ make libc6-dev curl policycoreutils automake autoconf libtool libssl-dev git
curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz && cd cmake-3.18.3 && ./bootstrap --no-system-curl && make -j$(nproc) && make install
cd .. && rm -rf cmake-*
```
- Clone and install Wazuh 4.7.0 setting the following environemnt variables:
```
/bin/sh -c 'USER_LANGUAGE=en USER_NO_STOP=y USER_INSTALL_TYPE=server USER_DIR=/var/ossec USER_ENABLE_EMAIL=n USER_ENABLE_SYSCHECK=n USER_ENABLE_ROOTCHECK=n USER_ENABLE_OPENSCAP=n USER_WHITE_LIST=n USER_ENABLE_SYSLOG=y USER_ENABLE_AUTHD=y USER_AUTO_START=n USER_UPDATE=n
```

```
git clone https://github.com/wazuh/wazuh.git -b 4.7.0; cd wazuh; ./install.sh
```

- Attach a new bash shell to the docker instance. 
```
docker exec -it <manager-instance-name> /bin/bash
```
 -   Start the Wazuh manager.
```
/var/ossec/bin/wazuh-control start
```
 -   Observe zombie processes using the ps command.
```
   9610 ?        SN     0:00  \_ /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
   9613 ?        SN     0:00  \_ /var/ossec/framework/python/bin/python3 /var ossec/api/scripts/wazuh-apid.py
   9616 ?        SN     0:00  \_ /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
   8961 ?        ZNs    0:00 [wazuh-csyslogd] <defunct>
   8962 ?        ZN     0:00 [wazuh-csyslogd] <defunct>
   8967 ?        ZNs    0:00 [wazuh-dbd] <defunct>
   8968 ?        ZN     0:00 [wazuh-dbd] <defunct>
   8977 ?        ZNs    0:00 [wazuh-agentless] <defunct>
   8978 ?        ZN     0:00 [wazuh-agentless] <defunct>
   8991 ?        ZNs    0:00 [wazuh-authd] <defunct>
   8992 ?        SNl    0:00 /var/ossec/bin/wazuh-authd
   9004 ?        ZNs    0:00 [wazuh-db] <defunct>
   9005 ?        SNl    0:00 /var/ossec/bin/wazuh-db
   9028 ?        ZNs    0:00 [wazuh-execd] <defunct>
   9029 ?        SNl    0:00 /var/ossec/bin/wazuh-execd
   9039 ?        ZNs    0:00 [wazuh-analysisd] <defunct>
   9040 ?        SNl    0:01 /var/ossec/bin/wazuh-analysisd
   9048 ?        ZNs    0:00 [wazuh-syscheckd] <defunct>
   9049 ?        SNl    0:00 /var/ossec/bin/wazuh-syscheckd
   9060 ?        ZNs    0:00 [wazuh-remoted] <defunct>
   9061 ?        ZN     0:00 [wazuh-remoted] <defunct>
   9062 ?        SNl    0:00 /var/ossec/bin/wazuh-remoted
   9094 ?        ZNs    0:00 [wazuh-logcollec] <defunct>
   9095 ?        SNl    0:00 /var/ossec/bin/wazuh-logcollector
   9111 ?        ZNs    0:00 [wazuh-monitord] <defunct>
   9112 ?        SNl    0:00 /var/ossec/bin/wazuh-monitord
   9120 ?        ZNs    0:00 [wazuh-modulesd] <defunct>
   9121 ?        ZN     0:00 [wazuh-modulesd] <defunct>
```

**Expected Behavior**
Wazuh should run without causing zombie processes in a Ubuntu Jammy container.

**Actual Behavior**
Running Wazuh in a Ubuntu Jammy container leads to multiple processes in a zombie state.

**Additional Information**
No relevant information appears in the manager logs.

### Evidences

[func1.webm](https://github.com/wazuh/wazuh/assets/11089305/21907e9b-9d22-4713-940d-b3ff6f0bce38)

**Comment by Rebits** [comment] 2023-10-24 16:18
This behavior has been successfully replicated exclusively within the context of Ansible tasks utilizing the roles defined in the @wazuh/qa repository. Interestingly, when attempting to execute these tasks manually, the issue does not seem to arise.

We're temporarily closing this issue until we can provide clear and reproducible steps to address it.

**Comment by Rebits** [comment] 2023-10-25 13:42
The issue has indeed been successfully replicated. It appears to occur exclusively when the manager is launched within an exec shell.

**Comment by vikman90** [comment] 2023-10-26 08:52
May this be related to https://github.com/wazuh/wazuh/issues/13947?

**Comment by Rebits** [comment] 2023-10-27 16:50
The issue has been identified in the production version v4.5.4. It appears to be exclusive to the new AMI and doesn't affect the previous AMI (`dontpanicat/debian`). The problem doesn't manifest when the installation is performed using packages.

This observation has been verified with `ubuntu:jammy` and `ubuntu:buster` images using the dependencies specified in the [issue description](https://github.com/wazuh/wazuh/issues/19829#issue-1959517678). Notably, the ps command is available in these images.

**Comment by vikman90** [comment] 2023-10-30 11:30
Setting objective to _high impact bugs_.

**Comment by jotacarma90** [comment] 2023-11-13 09:25
Delaying ETA due to other higher priority issues related to 4.7.0
Issue in backlog yet, we´ll take it this week as soon as possible.

**Comment by lchico** [comment] 2023-11-14 21:40
After watching the video, I realized that the issue lies with the command maintaining the container running, **tail -f /dev/null**. This causes some processes to become zombies. I encountered a similar problem when working with Docker.

This can be observed in the attached image captured from the video, specifically in the command column where **tail -f /dev/null** is running instead of **/bin/bash**.
![Screenshot from 2023-11-14 10-26-57](https://github.com/wazuh/wazuh/assets/21695385/8a5bb1f1-f13d-42ea-8f06-44a0c137ee77)

What should look like:

![Screenshot from 2023-11-14 10-47-00](https://github.com/wazuh/wazuh/assets/21695385/91798896-d01b-4c77-beea-da2cc7d49468)

After syncing with Victor, we confirmed that this is the cause of the zombie processes. He will be working on finding a solution. One possibility is to use Docker Compose with **tty = true**, or explore alternative approaches to keep the container running.

![Screenshot from 2023-11-14 10-45-53](https://github.com/wazuh/wazuh/assets/21695385/579e42ff-c22f-4504-80f6-96c3d03391d8)

**Comment by lchico** [comment] 2023-11-15 18:27
I put on on hold until get new instructions about how to proceed.

**Comment by lchico** [comment] 2023-11-17 12:47
Block, waiting for more information from @Rebits about how the tests are executed in order to find the best solution.

**Comment by lchico** [comment] 2023-11-21 21:32
Hello @Rebits , I hope this message finds you well. Could you please provide an update on this matter? Your assistance is greatly appreciated. Thank you.

**Comment by Rebits** [comment] 2023-11-22 18:42
Hello @lchico, my apologies for the delayed response.


>  Currently awaiting additional details from @Rebits regarding the test execution process to devise the optimal solution.

As for the execution of system tests, they are orchestrated through an Ansible task. To address the present issue, we will consider to allocate a pseudo-TTY using the Ansible Docker module [Ansible Docker Module - tty parameter](https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#parameter-tty). Implementing this configuration is expected to resolve the encountered error within the environment.

Alternatively, exploring a modification to the entrypoint, akin to configurations employed in production Docker environments, could also serve as a potential solution.

***

Concerning the inquiries about the product, it is crucial to obtain a comprehensive understanding of the reasons behind this behavior. This clarification is essential for determining the impact of the reported issue and guiding any necessary corrective actions.

**Comment by lchico** [comment] 2023-11-23 18:32
With the help of @vcerenu,  he mentioned:

```
"By using TTY, you are directing the stdin and stdout of your container to a pseudo-terminal. This should help you keep the processes alive, which, in your case, are dying and turning into zombies. We use the
s6 overlay  to ensure the container's longevity and avoid relying on a single command. That's likely why we haven't encountered those problems."
```

Taking this into account, we @Rebits conclude that we could close this issue.

**Comment by lchico** [comment] 2023-11-25 00:19
Moved ETA to 29/11/23 to give time for reviewing.

**Comment by ncvicchi** [comment] 2023-11-28 00:45
According to  @Rebits conclusion, moving to pending final review for closure approval

**Closed** 2023-12-01 15:54 UTC
Labels: type/bug, level/task
