### ISSUE TITLE
Remove usages of group and group_hash columns

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh#16285] opened 2023-02-24 20:09 UTC
|Wazuh version|Component|Branch|
|---|---|---|
| 4.5.0 | API/Framework/DB | [enhancement/18675-remove-group-column](https://github.com/wazuh/wazuh/tree/enhancement/18675-remove-group-column) |

## Description

As part of https://github.com/wazuh/wazuh/issues/16204, the columns `group` and `group_hash` where removed from the `agent` table since they were violating the 1FN of the global database.

Since the framework code is using these columns to make some queries, it is requested to remove these usages and replace them with queries to the `belongs` and/or `group` table.

Besides, the structure of the `group` and `belongs` tables changed. Now, the name of the group is the PK. This is the new structure:

```
CREATE TABLE IF NOT EXISTS `group` (
    name TEXT PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS belongs (
    id_agent INTEGER REFERENCES agent (id) ON DELETE CASCADE,
    name_group TEXT REFERENCES `group` (name) ON DELETE CASCADE,
    priority INTEGER NOT NULL DEFAULT 0,
    UNIQUE (id_agent, priority),
    PRIMARY KEY (id_agent, name_group)
);
```

Framework should also be modified to use this DB structure.

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by GGP1** [comment] 2023-05-08 18:58
## Update

Started reviewing the code related to the `agent` and `belongs` tables.

**Comment by GGP1** [comment] 2023-05-08 19:02
## Update

Started reviewing the code and doing some changes to the table schemas used for testing.

**Comment by GGP1** [comment] 2023-05-10 03:50
## Update

Replaced the groups IDs with group names in several sections of the code.

**Comment by GGP1** [comment] 2023-05-12 15:25
## Update

- Fixed multiple failed unit tests (only 1 failing due to group name query logic changes still pending)
- Finished updating all controllers and models to use group names
- Pushed changes to remote to the branch [fix/16285-replace-group-column](https://github.com/wazuh/wazuh/tree/fix/16285-replace-group-column)

Putting the issue on hold temporarily while I continue with a higher priority one.

**Comment by GGP1** [comment] 2023-05-15 17:59
## Update

- Completed TODOs from previous days
- Implemented a class to query the relationship between agents and groups stored in the `belongs` table
- Updated and created unit tests to cover the new functionality

Moved the status to Blocked since there are failed checks to be fixed in https://github.com/wazuh/wazuh/issues/16918.

**Comment by GGP1** [comment] 2023-05-31 18:35
## Update

- Rebased branch to its parent to re-run checks (some of them failed)
- Reviewed the results to detect the cause of the failures.

    I found out that the QA AIT test was failing due to the statistics template having parameters as required that were removed in the development of this issue's parent one https://github.com/wazuh/wazuh/issues/16204. 

    I created the following issue to address this https://github.com/wazuh/wazuh-qa/issues/4217.

**Comment by GGP1** [comment] 2023-06-02 19:01
## Update

Started going through the AIT failed checks to find out what is the root of the failures.

**Comment by GGP1** [comment] 2023-06-06 19:39
## Update

- Fixed an issue in the command used to assign a group to an agent and updated its unit test
- Changed the logic to obtain an agent's groups and created a unit test to cover the new functionality
- Fixed some of the errors in the integration tests

**Comment by GGP1** [comment] 2023-06-08 13:29
## Benchmarks

The benchmarks below were performed in an environment containing 10 agents and 5 groups, and executed 10000 requests with 100 concurrent workers.

### Master branch

```console
gasti@pop-os:~/work$ hey -n 10000 -c 100 -T "application/json" \ 
    -H "Authorization: Basic ${BASIC_TOKEN}"  \ 
    -H "Authorization: Bearer ${BEARER_TOKEN}" \
    -m GET https://0.0.0.0:55050/agents

Summary:
  Total:	60.3122 secs
  Slowest:	1.0227 secs
  Fastest:	0.0085 secs
  Average:	0.6008 secs
  Requests/sec:	165.8040
  
  Total data:	38440000 bytes
  Size/request:	3844 bytes

Response time histogram:
  0.008 [1]	|
  0.110 [14]	|
  0.211 [10]	|
  0.313 [16]	|
  0.414 [18]	|
  0.516 [219]	|■
  0.617 [6887]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.718 [2592]	|■■■■■■■■■■■■■■■
  0.820 [215]	|■
  0.921 [24]	|
  1.023 [4]	|


Latency distribution:
  10% in 0.5755 secs
  25% in 0.5818 secs
  50% in 0.5942 secs
  75% in 0.6202 secs
  90% in 0.6422 secs
  95% in 0.6683 secs
  99% in 0.7678 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0008 secs, 0.0085 secs, 1.0227 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0015 secs
  resp wait:	0.6000 secs, 0.0084 secs, 1.0225 secs
  resp read:	0.0000 secs, 0.0000 secs, 0.0015 secs

Status code distribution:
  [200]	10000 responses
```

### Modified branch

```console
gasti@pop-os:~/work$ hey -n 10000 -c 100 -T "application/json" \ 
    -H "Authorization: Basic ${BASIC_TOKEN}"  \ 
    -H "Authorization: Bearer ${BEARER_TOKEN}" \
    -m GET https://0.0.0.0:55050/agents
    
Summary:
  Total:	88.0520 secs
  Slowest:	1.2430 secs
  Fastest:	0.4162 secs
  Average:	0.8766 secs
  Requests/sec:	113.5692
  
  Total data:	38440000 bytes
  Size/request:	3844 bytes

Response time histogram:
  0.416 [1]	|
  0.499 [16]	|
  0.582 [7]	|
  0.664 [11]	|
  0.747 [152]	|■
  0.830 [610]	|■■■
  0.912 [7403]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■
  0.995 [873]	|■■■■■
  1.078 [572]	|■■■
  1.160 [228]	|■
  1.243 [127]	|■


Latency distribution:
  10% in 0.8309 secs
  25% in 0.8386 secs
  50% in 0.8504 secs
  75% in 0.8828 secs
  90% in 0.9891 secs
  95% in 1.0377 secs
  99% in 1.1845 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0012 secs, 0.4162 secs, 1.2430 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0066 secs
  resp wait:	0.8753 secs, 0.4162 secs, 1.2426 secs
  resp read:	0.0001 secs, 0.0000 secs, 0.0013 secs

Status code distribution:
  [200]	10000 responses
```

**Comment by GGP1** [comment] 2023-06-09 15:14
## Benchmarks (2)

The benchmarks below were performed in an environment containing 50,000 agents, all of them belonging to the group 'default'. It executed 20 requests with 5 concurrent workers.

> The number of requests and concurrent workers was reduced significantly compared to the last benchmark due to the time taken to perform each request. Even with the parameter `wait_for_complete=true` the context deadline was exceeded in most of them.

#### Master branch

Query used to assign all agents to the group 'default':

```
global sql UPDATE agent SET `group`='default'
```

Results:

```console
gasti@pop-os:~/work$ hey -n 20 -c 5  -T "application/json" \ 
    -H "Authorization: Basic ${BASIC_TOKEN}"  \ 
    -H "Authorization: Bearer ${BEARER_TOKEN}" \
    -m GET https://0.0.0.0:55050/agents?wait_for_complete=true

Summary:
  Total:	10.7856 secs
  Slowest:	2.7682 secs
  Fastest:	0.5326 secs
  Average:	2.4144 secs
  Requests/sec:	1.8543
  
  Total data:	2269020 bytes
  Size/request:	113451 bytes

Response time histogram:
  0.533 [1]	|■■■
  0.756 [0]	|
  0.980 [0]	|
  1.203 [1]	|■■■
  1.427 [0]	|
  1.650 [1]	|■■■
  1.874 [0]	|
  2.098 [0]	|
  2.321 [1]	|■■■
  2.545 [0]	|
  2.768 [16]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■


Latency distribution:
  10% in 1.6176 secs
  25% in 2.6239 secs
  50% in 2.6610 secs
  75% in 2.7201 secs
  90% in 2.7485 secs
  95% in 2.7682 secs
  0% in 0.0000 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0011 secs, 0.5326 secs, 2.7682 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0000 secs
  resp wait:	2.4131 secs, 0.5279 secs, 2.7680 secs
  resp read:	0.0002 secs, 0.0001 secs, 0.0005 secs

Status code distribution:
  [200]	20 responses
```

#### Modified branch

Query used to assign all agents to the group 'default':

```
global sql INSERT INTO belongs (id_agent, group_name) SELECT id, 'default' FROM agent
```

Results:

```console
gasti@pop-os:~/work$ hey -n 20 -c 5  -T "application/json" \ 
    -H "Authorization: Basic ${BASIC_TOKEN}"  \ 
    -H "Authorization: Bearer ${BEARER_TOKEN}" \
    -m GET https://0.0.0.0:55050/agents?wait_for_complete=true

Summary:
  Total:	44.0608 secs
  Slowest:	11.0874 secs
  Fastest:	2.1901 secs
  Average:	9.9136 secs
  Requests/sec:	0.4539
  
  Total data:	2279580 bytes
  Size/request:	113979 bytes

Response time histogram:
  2.190 [1]	|■■■
  3.080 [0]	|
  3.970 [0]	|
  4.859 [1]	|■■■
  5.749 [0]	|
  6.639 [1]	|■■■
  7.528 [0]	|
  8.418 [0]	|
  9.308 [1]	|■■■
  10.198 [0]	|
  11.087 [16]	|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■


Latency distribution:
  10% in 6.6236 secs
  25% in 10.9302 secs
  50% in 10.9991 secs
  75% in 11.0600 secs
  90% in 11.0822 secs
  95% in 11.0874 secs
  0% in 0.0000 secs

Details (average, fastest, slowest):
  DNS+dialup:	0.0011 secs, 2.1901 secs, 11.0874 secs
  DNS-lookup:	0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	0.0000 secs, 0.0000 secs, 0.0000 secs
  resp wait:	9.9123 secs, 2.1854 secs, 11.0873 secs
  resp read:	0.0002 secs, 0.0001 secs, 0.0005 secs

Status code distribution:
  [200]	20 responses
```

**Comment by GGP1** [comment] 2023-06-22 20:34
## Update

I took the approach of joining the tables but many bugs arose from this. I was able to fix all but two:

1. If the query uses GROUP_CONCAT and does not have a WHERE condition, then it returns a single result, this occurs even when GROUP BY and ORDER BY are used. Very strange, I tried an online playground and the query should return all items.
2. The API is designed so that clients can select, filter, and sort objects by their fields (in turn based on the table schema).
 By removing the 'group' field we are no longer supporting these features for agent endpoints. I'm looking for a way to fix it without having to modify all the logic

**Comment by GGP1** [comment] 2023-06-23 20:31
## Update

 - Solved the issue with GROUP_CONCAT returning only one result
- Started analysing possibles solutions to support filtering, selecting and sorting by the `group` field. With the current design, it's permitted to perform this operations only if the field is part of the database schema corresponding to the object being returned.

    The simplest way to solve this would be to let users use the `group` field and then handle the functionality manually. However, we may encounter similar challenges in the future and doing this for every relationship field does not scale. I'm looking for a better solution that would allow us to handle custom fields as if they were part of the schema.

**Comment by GGP1** [comment] 2023-06-26 19:51
## Update

- Updated integration tests so they don't use the group field on agent endpoints
- Changes in the logic to return only agents with no group and creation of a new class for executing a special query
- I have to do the last tests to verify that everything works correctly before moving it to review

**Comment by Selutario** [comment] 2023-08-01 07:45
We won't be on time to include this development in `4.7.0`.
- **Reson:** It has required more and deeper changes than anticipated:
  - https://github.com/wazuh/wazuh/issues/17745
  - https://github.com/wazuh/wazuh/issues/17864
  - https://github.com/wazuh/wazuh-qa/issues/4217
- **Target release:** 4.8.0

**Comment by GGP1** [comment] 2023-08-28 19:51
## Update

Updated the query used by `WazuhDBQueryAgents` to include a left join to the table `belongs` and to group by `belongs.priority`. All that's left is to update the tests and check that everything works as expected.

**Comment by GGP1** [comment] 2023-08-29 18:40
## Update

- Restored deleted methods and logic that was mistakenly removed
- Updated unit tests and the data used for them
- Executed multiple queries to verified that they returned the results expected

Some tests of the AIT `test_agent_GET_endpoints.tavern.yaml` fail, I'm reviewing what is the issue.

**Comment by GGP1** [comment] 2023-09-01 18:11
## Update

- Made some modifications to the query building and group filter values processing to obtain the desired results.
- Tested the changes manually and rolled back some previous changes that were not necessary.

**Comment by GGP1** [comment] 2023-09-04 13:14
## Update

Updated test results for the endpoint `GET /agents/stats/distinct"` which is now returning one new item per group, this is because we are storing one row per group in the database and it's the query forces them to be separate.

Since this is a breaking change, I will discuss with the team before proceeding.

**Comment by GGP1** [comment] 2023-09-18 15:51
## Update

Restored the parameter for group names to `group_id` to avoid introducing a breaking change.

**Comment by GGP1** [comment] 2023-09-19 17:31
## Update

Tried replicating the old behavior by removing `belongs.name_group` from the `GROUP BY` clause, so the results are not separated by groups but other issues arose.

The expected behavior will be discussed by management and the issue will be on hold until then.

## Issues

Environment:

id | group | status
|---|---|---|
000 | | active
001 | default,group1,group2 | active
002 | default | active
003 | default | disconnected

### Fields: status,group

If the results are not grouped by their groups, the information is mixed, empty groups are not displayed and the count is inaccurate (it adds 1 per group as well)

```sql
sqlite> SELECT connection_status, COUNT(*), GROUP_CONCAT(belongs.name_group) FROM agent LEFT JOIN belongs ON agent.id = belongs.id_agent GROUP BY connection_status;
active|5|default,group1,group2,default
disconnected|1|default
```

Therefore, we cannot tell which results should be taken into account and the ones that not.

Whereas if we group by groups, we get one result per status-group distinct pair but duplicates can be easily detected and joined (`default,default`).

```sql
sqlite> SELECT connection_status, COUNT(*), GROUP_CONCAT(belongs.name_group) FROM agent LEFT JOIN belongs ON agent.id = belongs.id_agent GROUP BY connection_status, belongs.name_group;
active|1|
active|2|default,default
active|1|group1
active|1|group2
disconnected|1|default
```

### Fields: group

Similarly, if we retrieve all the groups, we are forced to use the GROUP BY or otherwise we get

```sql
sqlite> SELECT COUNT(*), GROUP_CONCAT(belongs.name_group) FROM agent LEFT JOIN belongs ON agent.id = belongs.id_agent;
6|default,group1,group2,default,default
```

If we group by ID, the results are separate but the count is now wrong (although there's a way to fix them, the implementation may not be that clean anymore)

```sql
sqlite> SELECT COUNT(*), GROUP_CONCAT(belongs.name_group) FROM agent LEFT JOIN belongs ON agent.id = belongs.id_agent GROUP BY id;
1|
3|default,group1,group2
1|default
1|default
```

Grouping by groups is, again, the one providing cleanest results
```sql
sqlite> SELECT COUNT(*), GROUP_CONCAT(belongs.name_group) FROM agent LEFT JOIN belongs ON agent.id = belongs.id_agent GROUP BY belongs.name_group;
1|
3|default,default,default
1|group1
1|group2
```

**Comment by GGP1** [comment] 2023-09-21 20:22
## Update

- Added a test case to the `test_agent_GET_endpoints.tavern.yaml`
- Made some corrections to the changes introduced
- Tested the changes to make sure everything works as expected

**Comment by GGP1** [comment] 2023-09-22 16:25
## Update

Change in `WazuhDBQueryAgentGroupBy` so that when searching it does not use the `group` field if the `belongs` table was not joined.

After pushing the changes, many of the checks failed. [Integration tests for API - Tier 0 and 1 / build (pull_request)](https://github.com/wazuh/wazuh/actions/runs/6275969961/job/17044682422?pr=17127) and [Test: API IT - Tier 0,1 -manager ](https://github.com/wazuh/wazuh/pull/17127/checks?check_run_id=17045204243) are expected to fail because they require the changes from https://github.com/wazuh/wazuh-qa/issues/4217 to pass. However, the other ones are most likely related to master being unstable since they fail in many other pull requests as well.

**Comment by GGP1** [comment] 2023-09-25 18:49
## Update

Ran wazuh and wazuh-qa API integration tests manually since they failed expectedly/didn't run in the checks. Moving the issue to pending review.

**Comment by GGP1** [comment] 2023-09-27 18:27
## Update

Applied changes requested, updated related unit tests and validated that the new logic works as expected.

**Closed** 2023-09-28 11:00 UTC
Labels: type/enhancement, module/db, type/enhancement/reliability, level/subtask
