### ISSUE TITLE
Port detection error in install script

### ISSUE THREAD

**Issue by 991547436** [wazuh/wazuh#16670] opened 2023-04-11 09:30 UTC
I opened port 9443, and the installation script will report that port 443 is occupied

https://packages.wazuh.com/4.4/wazuh-install.sh
[](url)

![QQ截图20230411172634](https://user-images.githubusercontent.com/15355274/231117399-1cb628e5-e4a2-4bff-a2c4-609c3ecf1583.png)

**Comment by jnasselle** [comment] 2023-04-13 11:51
@991547436,

Thanks for reporting this issue. It's a duplicate of https://github.com/wazuh/wazuh-packages/issues/1857 and will be backported to v4.4.2 by https://github.com/wazuh/wazuh-packages/pull/2023.

If you need it urgently, you can make those changes in your `wazuh-install.sh` script.

Regards,
Nicolas

**Closed** 2023-04-13 12:08 UTC
Labels: type/bug, reporter/community, module/install, level/task
