### ISSUE TITLE
Update `Agent-groups send` task to use the new cluster broadcast system

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh#13180] opened 2022-04-20 09:33 UTC
## Description

The `Agent-groups send` task should be updated to replace its broadcast mechanism with the new broadcast system developed at #12912. To do this, it will be necessary to remove this method:
https://github.com/wazuh/wazuh/blob/813c85f70612bfbbdba340d90c003408763fb65c/framework/wazuh/core/cluster/master.py#L1147-L1168

As well as refactor:
- [agent_groups_update()](https://github.com/wazuh/wazuh/blob/813c85f70612bfbbdba340d90c003408763fb65c/framework/wazuh/core/cluster/master.py#L1194-L1208 ) so it uses the new broadcast system instead of updating a dict.
- [send_agent_groups_information()](https://github.com/wazuh/wazuh/blob/813c85f70612bfbbdba340d90c003408763fb65c/framework/wazuh/core/cluster/master.py#L709-L731) so that it stops being a task with an infinite loop and becomes a normal method that receives as a parameter the information to send.

You need to update unit tests and review and remove any code that is no longer needed after these changes.

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by davidjiglesias** [comment] 2022-07-11 08:09
Duplicate of #13848

**Closed by davidjiglesias** 2022-07-11 08:09 UTC
Labels: type/enhancement, module/framework, module/cluster
