### ISSUE TITLE
`wazuh-db` increased its Disk Read by approximately 400%

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#19583] opened 2023-10-10 23:26 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.6.0-40602 | `wazuh-db` | Manager | Packages | CentOS 7 |

## Description

While analyzing the results in # we've noticed that `wazuh-db` increased its Disk Read by approximately **400%**

- 🔍 Further research is required
- 👀 If this is caused by a new feature or change it must be **justified**, otherwise a fix must be **proposed**.
- It could be related to: https://github.com/wazuh/wazuh/issues/19222#issuecomment-1743444224

<details><summary>Check the following results:</summary></br>

| Variable | `4.5.3` | `4.6.0-40602` |
|-- |-- |--
| `Disk_Read` | <img src="https://camo.githubusercontent.com/ba9990b6311542734165ea346e79552d9aff3595c52b23e265a44b7e6fc43de7/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e352e332f42343433342d333630306d2f42343433345f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343433345f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67" /> | <img src="https://camo.githubusercontent.com/6d21f9f7c4ee9eae219b2f8b3c00fe3e87ec9d1dc87f7dfd55a0e2bf58e49bed/68747470733a2f2f63692e77617a75682e636f6d2f646174612f546573745f7374726573732f7072652d72656c656173652f342e362e302f42343435362d333630306d2f42343435365f6d616e616765725f63656e746f732f706c6f74732f6d6f6e69746f722d6d616e616765722d546573745f7374726573735f42343435365f6d616e616765722d7072652d72656c656173655f4469736b5f526561642e706e67" />

</details>

**Comment by MarcelKemp** [comment] 2023-10-16 16:08
## Research

On the one hand, the disk read increase for the `wazuh-db` daemon is found since version `v4.6.0-alpha1`, so it is not due to a fix between the different stages:
- `Alpha 1`: https://github.com/wazuh/wazuh/issues/18921
- `Beta 1`: https://github.com/wazuh/wazuh/issues/19225
- `RC1`: https://github.com/wazuh/wazuh/issues/19556

On the other hand, this increase cannot be found in the individual footprints, as it needs an overload in several modules to be reflected in the disk read, which makes it difficult to get the exact module that is causing the increase:
- https://github.com/wazuh/wazuh/issues/19550
- https://github.com/wazuh/wazuh/issues/19547
- https://github.com/wazuh/wazuh/issues/19549
- https://github.com/wazuh/wazuh/issues/19543

It is also worth mentioning that this problem is reflected in this other open issue for the same reason, but referring to the disk read increment of several other daemons:
- https://github.com/wazuh/wazuh/issues/19596

According to this information, looking at developments that could directly affect the `wazuh-db` daemon, or large developments that could also affect this daemon, we find the following:
- https://github.com/wazuh/wazuh/pull/12745
- https://github.com/wazuh/wazuh/pull/14953

And according to the following stress tests, where one of the modules is not executed, we see that the main problem appears when there is a stress of `syscheck` + `logcollector` + `another component`, because in these issues the increment of `wazuh-db` does not appear:
- https://github.com/wazuh/wazuh/issues/19535
- https://github.com/wazuh/wazuh/issues/19548

**Comment by MarcelKemp** [comment] 2023-10-17 17:47
The disk problem seems to be related to the following issue, which has a PR that fixes the problem:
- #19074

As it is also a duplicate issue (of #19596), I am closing it.

When the results of the fix come out, it will be possible to verify if the problem is solved.

**Closed by MarcelKemp** 2023-10-17 17:47 UTC
Labels: type/bug, level/task
