### ISSUE TITLE
WPK Upgrade on macOS Intel failed due to timeout and the process is freeze

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh#18598] opened 2023-08-24 21:54 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.5.1-rc2 | Upgrade  | Agent | WPK | macOS 12.0.1|

## Description

After the testing performed in https://github.com/wazuh/wazuh/issues/18491 we have been able to see that, when we try to update a macOS agent with WPK, we receive:

```
Timeout reached while waiting for the response from the agent
```

Also, the upgrade seems to be frozen according to the information in the `upgrade.log`

## Steps to reproduce

1. Prepare an environment with a 4.5.1 manager and 4.5.0 macOS agent.
2. Configure in the manager ossec.conf: 
```
<agent-upgrade>
  <chunk_size>32768</chunk_size>
</agent-upgrade>

<task-manager>
  <task_timeout>1h</task_timeout>
</task-manager>
```

4. Upgrade the agent using `agent_upgrade`:

 ` /var/ossec/bin/agent_upgrade -a 001 `

5. Check the results and `/Library/Ossec/logs/upgrade.log`

## Evidence

- Upgrade.log:
![image](https://github.com/wazuh/wazuh/assets/26927338/d4bc67d8-8c02-4844-911a-5b78e22c81ce)

- Error in wazuh manager:
![image](https://github.com/wazuh/wazuh/assets/26927338/acb0b0a5-8533-4ad8-ab45-953a29557b06)

**Comment by roronoasins** [comment] 2023-08-25 14:21
LGTM

**Comment by Nicogp** [comment] 2023-08-29 18:05
The error shown in the Issue could be reproduced and we can see that the process gets stuck when installing the new package, more precisely while executing this line of code:
`installer -pkg ./var/upgrade/wazuh-agent* -target / >> ./logs/upgrade.log 2>&1`

Seeing that the command executed is the same as the one executed to perform an upgrade/installation by [console](https://documentation.wazuh.com/current/upgrade-guide/wazuh-agent/macos.html)
`installer -pkg wazuh-agent-4.5.1-1.intel64.pkg -target /`
we proceed to perform the upgrade by console and we get the same behavior, the process is stuck in the same point
![image](https://github.com/wazuh/wazuh/assets/13004400/be42c5b8-8921-440b-bf59-f1c8745faa8c)
In view of this, we rule out that this is a WPK problem.

When we continue with the tests and after a restart of the macOS machine we notice that the first upgrade/install is done correctly, but the following ones fail
![image](https://github.com/wazuh/wazuh/assets/13004400/22aabe7a-408b-4925-8731-78aca1beffcc)
References to Upgrade.log:

1. Start of the first upgrade
2. First upgrade completed successfully
3. Start of the second upgrade, hangs
4. After 10 minutes, restart virtual machine
5. First upgrade after reboot
6. First update completed successfully after reboot
7. Attempt second update (after reboot) and hangs

Same behavior for the installation/update by console, after restarting the first one is updated correctly and the following ones hang:
![image](https://github.com/wazuh/wazuh/assets/13004400/49e1af03-255d-4ef3-a990-addd4fcc0061)

We continued with the tests, in this case on `macOS bigsur` and we saw the same behavior, as we suspect that it is a policy of the `OS`, we tried to give `"Full Disk Access"` permission to `sh`
![image](https://github.com/wazuh/wazuh/assets/13004400/ec1f014b-75c9-4cfd-a813-d5246ff17723)

and after that it allowed us to do upgrades without any problem, both manually and by WPKs.
![image](https://github.com/wazuh/wazuh/assets/13004400/fd2f1362-4402-48fe-8b65-8f7a00082d07)
![image](https://github.com/wazuh/wazuh/assets/13004400/103ba3d7-ad05-482f-9278-ca724e788a2d)

But when testing on another OS version, now `macOS monterrey`, we did not have the same results, we gave `"Full Disk Access"` permission to `sh`, `zsh`, `installer`, `iOS App installer`, `bash`, `console`, `sshd `but in all cases we still have the same problem.

So we went on to test with other applications, for example python, and we observed the same behavior, after a restart of the macOS machine the first installation/update is done correctly and the next one gets stuck:
![image](https://github.com/wazuh/wazuh/assets/13004400/8b8507d0-5c04-4020-92ea-1c0d9b3a45e3)

Testing other software we have the same behavior:
![image](https://github.com/wazuh/wazuh/assets/13004400/be1b27ad-28e5-432f-ad21-f4a17450a8d9)

Having said the latter, I conclude that this is a limitation introduced by the OS, which is not related to the Wazuh package.

**Comment by BelenValdivia** [comment] 2023-08-30 16:56
I tested again on macOS Monterey and after restarting the VM, the first installation or update was done correctly, and the next one froze.


- Upgrade after restarting the VM:

```
h-3.2# tail -f /Library/Ossec/logs/upgrade.log
2023/08/28 18:20:30 - Generating Backup.
tar: Failed to set default locale
2023/08/28 18:20:41 - Upgrade started.
2023/08/28 20:02:28 - Generating Backup.
tar: Failed to set default locale
2023/08/28 20:02:33 - Upgrade started.
2023/08/30 14:58:50 - Generating Backup.
2023/08/30 14:59:02 - Upgrade started.
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
2023/08/30 14:59:31 - Installation result = 0
2023/08/30 14:59:32 - Waiting connection... Status = connected. Remaining attempts: 29.
2023/08/30 14:59:32 - Connected to manager.
2023/08/30 14:59:32 - Upgrade finished successfully.
```

- After the upgrade was done, I uninstalled the wazuh agent 4.5.1 to install 4.5.0 again  (without restarting the VM ), and the installation was frozen.

![image](https://github.com/wazuh/wazuh/assets/26927338/9f382fe2-5348-4a7f-bb3d-18eb71b25448)

**Comment by vikman90** [comment] 2023-09-19 06:42
## Recap

This is caused by an **external cause**, which is beyond our control: the macOS `installer` application.

This issue is blocked until we receive feedback from the application manufacturer (Apple).

Tested versions:
- **macOS Big Sur**: the problem can be solved (workaround) by granting "Full disk access" permissions to the `sh` application.
- **macOS Monterey**: we have not found any valid solution.

**Comment by mauromalara** [comment] 2023-09-26 19:32
@vikman90 I had an issue while testing `4.5.3-rc1`, I could not delete the `wazuh` user in macOS Sonoma:

<details><summary>Error</summary></br>

```
sh-3.2# /Library/Ossec/bin/wazuh-control stop
Killing wazuh-modulesd... 
Killing wazuh-logcollector... 
Killing wazuh-syscheckd... 
Killing wazuh-agentd... 
Killing wazuh-execd... 
Wazuh v4.5.3 Stopped

sh-3.2# /bin/rm -r /Library/Ossec

sh-3.2# /bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist

sh-3.2# /bin/rm -f /Library/LaunchDaemons/com.wazuh.agent.plist

sh-3.2# /bin/rm -rf /Library/StartupItems/WAZUH

sh-3.2# /usr/bin/dscl . -delete "/Users/wazuh"
<main> delete status: eDSPermissionError
<dscl_cmd> DS Error: -14120 (eDSPermissionError)

sh-3.2# /usr/bin/dscl . -delete "/Groups/wazuh"

sh-3.2# /usr/sbin/pkgutil --forget com.wazuh.pkg.wazuh-agent
Forgot package 'com.wazuh.pkg.wazuh-agent' on '/'.
```

</details>


So I:
1. Grant "Full Disk Access" to the "Terminal" application
2. Enable root by running `dsenableroot`

After that, I was able to delete the `wazuh` user without any problem.


Maybe something like this is related to this issue.

**Comment by vikman90** [comment] 2023-10-19 16:18
## Status update

Let's recap the behavior on the last 4 versions of macOS, including whether there is a possible workaround. Then, block this issue by management.

**Comment by sdvendramini** [comment] 2023-11-08 00:55
# Partial Results


|Version|Build|Status|
|---|---|:-:|
|11.0.0 BigSur|-| :yellow_circle:   |
|12.0.1 Monterey|-| :red_circle:  |
|12.7.1 Monterey|21G920| :green_circle:  |


### Legend
🟢 Works OK.
🟡 Fixed with workaround
🔴 Fails.

**Comment by havidarou** [comment] 2023-12-11 17:51
After this analysis, we understand that there was a bug in different macOS versions that has been later fixed.

As such, we can close this issue as not planned.

**Closed by havidarou** 2023-12-11 17:51 UTC
Labels: type/bug, level/task, qa_known
