### ISSUE TITLE
Problems with sending log (syslog)

### ISSUE THREAD

**Issue by dcantos1** [wazuh/wazuh#12041] opened 2022-01-31 15:07 UTC
4.2.0|Virtual Appliance

Configure a FW checkpoint to send the syslog to Wazuh but when I do a tcpdump I don't see any traffic.

The configuration that I have in wazuh is the following.

![Wazuh01](https://user-images.githubusercontent.com/80493416/151817348-713d5282-327f-4d35-9ded-54503c5c4c41.PNG)

The Firewall configuration is as follows

![FW01](https://user-images.githubusercontent.com/80493416/151817587-955e3894-d408-44d3-9466-b92aa447d7da.PNG)

when I do the TCPDUMP to port 514 I don't see any incoming traffic.

![tcpdump01](https://user-images.githubusercontent.com/80493416/151817774-8dc59d11-b39e-47a4-8647-9749729527e3.PNG)

but if I do a test if the port is listening if I have incoming traffic, the test is done with NC on another machine with linux.

![NC01](https://user-images.githubusercontent.com/80493416/151818169-0b32000a-0f78-46ce-81bd-88c3338d80c6.PNG)

In wazuh
![imagen](https://user-images.githubusercontent.com/80493416/151818252-a38d6209-94ba-44c5-b7e4-7097ff62d081.png)

please help me

**Comment by nmkoremblum** [comment] 2022-01-31 16:28
Hi @dcantos1!

Given your description, it seems to be a network configuration issue, as the port is opened and you can effectively connect to it from another terminal. Have you tried to do a reverse ping, from the manager to the FW? Can you share with us your FW's IP? (If it can be known, take into account this is a public thread)

I will be waiting for your reply!

**Comment by dcantos1** [comment] 2022-01-31 16:34
Hello, thank you very much for the answer, I am going to check if there is not a blockage in the FW, because if I have reverse ping as you commented.
![imagen](https://user-images.githubusercontent.com/80493416/151834053-91f04d33-72aa-47e3-92bf-360f4ffc2281.png)

**Comment by nmkoremblum** [comment] 2022-01-31 16:42
Great, apart from that, is there any other way to verify that the FW is actually sending any logs?

**Comment by dcantos1** [comment] 2022-01-31 16:46
I already reviewed and updated, additionally I also configured a graylog server to send the syslog to Wazuh but I don't see input data in the TCPdump either. 

this is in graylog (output to Wazuh)

![imagen](https://user-images.githubusercontent.com/80493416/151836097-b550e594-fd5f-4755-933a-6fdf47db1fdd.png)

**Comment by nmkoremblum** [comment] 2022-01-31 17:25
Could you please share with us your FW characteristics?

**Comment by dcantos1** [comment] 2022-01-31 17:52
By the way, in the graylog I have configured so that the same FW sends the syslog and if I have traffic in the graylog but not with Wazuh.

![imagen](https://user-images.githubusercontent.com/80493416/151846198-6ee7e30e-6ac9-4db3-ad0e-d896643cda8f.png)


the checkpoint model is 3800 and the version is R81.

**Comment by nmkoremblum** [comment] 2022-01-31 19:00
Has the server more than one Ethernet interface? Are the server and the firewalls in the same IP network?

**Comment by dcantos1** [comment] 2022-01-31 19:20
Hello, the server only has one interface and it is in the same subnet as the Firewall.

**Comment by nmkoremblum** [comment] 2022-01-31 19:39
Ok, then please try changing the `allowed-ips` option to: `<allowed-ips>192.168.10.0/24</allowed-ips>`

**Comment by dcantos1** [comment] 2022-01-31 19:46
Before I had it with the 192.168.10.0/24 subnet but I had the same problem, that's where I changed it to 0.0.0.0/0

**Comment by nmkoremblum** [comment] 2022-01-31 20:12
After all the information we have exchanged; the results of the tests you have shared with us and having consulted my colleagues about your issue, it seems that the problem is not related to Wazuh. It must be either a network restriction or a misconfiguration on the FW that is preventing the logs to arrive at the Wazuh manager's machine.

As for the last attempt, you could additionally try to change the remote port (514) to a custom one. If this doesn't work, then you should contact your network administrator and ask them if there is any rule that restricts logs from being sent. You could also try to perform a `traceroute` from your firewall to your manager's machine, to check where is the message being dropped.

I am sorry for not being able to solve your issue. Please, let us know if you have new updates.

Best Regards

**Comment by dcantos1** [comment] 2022-01-31 21:44
Hi, thank you very much, but let me tell you that we have been reviewing and there is no blocking in the network since it is the internal network, because as I mentioned in previous threads, I have configured a graylog and that if it receives the data without problems from the firewall, only with Wazuh passes me that problem.

Additionally, I perform the traceroute and there is only one jump to the firewall without problems.

![imagen](https://user-images.githubusercontent.com/80493416/151878123-ccf70a4b-4ea2-48a6-98dc-dfbfe8ecdc1f.png)

**Comment by dcantos1** [comment] 2022-01-31 21:47
Hello,

It's already solved, make the old reliable, restart the wazuh (the virtual server) and what I start I started receiving.

**Comment by nmkoremblum** [comment] 2022-02-01 12:05
Hi dcantos1! Sorry, I did not get the Graylog part, I thought it was on another machine.

Great to know you were able to make it work. For the future, take into account that you always need to reset the Wazuh manager after modifying its configuration files or its ruleset for them to take effect.

I proceed to close this thread, do not hesitate to reach out again whenever you need us.

Best Regards,

Mariano Koremblum

**Closed by nmkoremblum** 2022-02-01 12:05 UTC
Labels: community

**Comment by pappy-myron** [comment] 2023-05-19 16:46
Hello, 
Please I am trying to integrate SentinelOne logs into my Wazuh using Syslog. I have configured syslog settings on SentinelOne and have done the same on Wazuh. But I do not seem to be getting logs on the Wazuh. Kindly help.
