### ISSUE TITLE
SSL manager verification not working properly

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh#4164] opened 2019-10-29 20:51 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.10.2-rev | Manager/Agent | Manager/Agent | Packages/Sources | CentOS 7|

Hello Team,

I have followed instructions for **manager verification using ssl** as described here : https://documentation.wazuh.com/3.10/user-manual/registering/manager-verification/agents/linux-unix-manager-verification.html. Then i moved the rootCA.pem to the agents in order to allow registering them but i have mentioned that I'm able to register with or without the rootCA.pem as you can see below : 

- Registering agent with rootCA.pem : 

```
[root@Agent1 vagrant]# /var/ossec/bin/agent-auth -m 172.168.55.100 -v /var/ossec/etc/rootCA.pem -A agentwithrootCA -d
2019/10/29 20:40:22 agent-auth[5748] main-client.c:241 at main(): DEBUG: Starting ...
2019/10/29 20:40:22 agent-auth[5748] main-client.c:271 at main(): INFO: Started (pid: 5748).
2019/10/29 20:40:22 agent-auth[5748] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.
2019/10/29 20:40:22 agent-auth[5748] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2019/10/29 20:40:22 agent-auth[5748] main-client.c:330 at main(): INFO: No authentication password provided.
2019/10/29 20:40:22 agent-auth[5748] main-client.c:355 at main(): INFO: Connected to 172.168.55.100:1515
2019/10/29 20:40:22 agent-auth[5748] main-client.c:362 at main(): INFO: Verifying manager's certificate
2019/10/29 20:40:22 agent-auth[5748] check_cert.c:52 at check_x509_cert(): DEBUG: Checking certificate's subject alternative names.
2019/10/29 20:40:22 agent-auth[5748] check_cert.c:58 at check_x509_cert(): DEBUG: No matching subject alternative names found. Checking common name.
2019/10/29 20:40:22 agent-auth[5748] main-client.c:370 at main(): INFO: Using agent name as: agentwithrootCA
2019/10/29 20:40:22 agent-auth[5748] main-client.c:418 at main(): INFO: Send request to manager. Waiting for reply.
2019/10/29 20:40:22 agent-auth[5748] main-client.c:443 at main(): INFO: Received response with agent key
2019/10/29 20:40:22 agent-auth[5748] main-client.c:477 at main(): INFO: Valid key created. Finished.
2019/10/29 20:40:22 agent-auth[5748] main-client.c:485 at main(): INFO: Connection closed.
```
```
[root@wazuh vagrant]# /var/ossec/bin/agent_control -l
Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh (server), IP: 127.0.0.1, Active/Local
   ID: 022, Name: agentwithrootCA, IP: 172.168.55.121, Never connected

```

_**Debug logs :**_ 

```
2019/10/29 20:46:05 ossec-authd[16193] main-server.c:649 at run_dispatcher(): INFO: New connection from 172.168.55.121
2019/10/29 20:46:05 ossec-authd[16193] main-server.c:685 at run_dispatcher(): DEBUG: Request received: <OSSEC A:'agentwithrootCA'
>
2019/10/29 20:46:05 ossec-authd[16193] main-server.c:722 at run_dispatcher(): INFO: Received request for a new agent (agentwithrootCA) from: 172.168.55.121
2019/10/29 20:46:05 ossec-authd[16193] main-server.c:960 at run_dispatcher(): INFO: Duplicated IP '172.168.55.121' (023). Saving backup.
2019/10/29 20:46:05 ossec-authd[16193] validate.c:845 at OS_RemoveAgentGroup(): DEBUG: At OS_RemoveAgentGroup(): Could not open file '/queue/agent-groups/023'
2019/10/29 20:46:05 ossec-authd[16193] main-server.c:1082 at run_dispatcher(): INFO: Agent key generated for 'agentwithrootCA' (requested by 172.168.55.121)
2019/10/29 20:46:05 ossec-authd[16193] validate.c:685 at OS_BackupAgentInfo(): DEBUG: Couldn't create some backup files.
2019/10/29 20:46:13 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
2019/10/29 20:46:13 ossec-remoted: INFO: (1410): Reading authentication keys file.

```

- Registering agent without rootCA.pem :

```
[root@Agent1 vagrant]# /var/ossec/bin/agent-auth -m 172.168.55.100  -A agentwithoutrootCA -d 
2019/10/29 20:43:08 agent-auth[5749] main-client.c:241 at main(): DEBUG: Starting ...
2019/10/29 20:43:08 agent-auth[5749] main-client.c:271 at main(): INFO: Started (pid: 5749).
2019/10/29 20:43:08 agent-auth[5749] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2019/10/29 20:43:08 agent-auth[5749] main-client.c:330 at main(): INFO: No authentication password provided.
2019/10/29 20:43:08 agent-auth[5749] main-client.c:355 at main(): INFO: Connected to 172.168.55.100:1515
2019/10/29 20:43:08 agent-auth[5749] main-client.c:370 at main(): INFO: Using agent name as: agentwithoutrootCA
2019/10/29 20:43:08 agent-auth[5749] main-client.c:418 at main(): INFO: Send request to manager. Waiting for reply.
2019/10/29 20:43:08 agent-auth[5749] main-client.c:443 at main(): INFO: Received response with agent key
2019/10/29 20:43:08 agent-auth[5749] main-client.c:477 at main(): INFO: Valid key created. Finished.
2019/10/29 20:43:08 agent-auth[5749] main-client.c:485 at main(): INFO: Connection closed.
[root@Agent1 vagrant]# 

```
```
[root@wazuh vagrant]# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: wazuh (server), IP: 127.0.0.1, Active/Local
   ID: 023, Name: agentwithoutrootCA, IP: 172.168.55.121, Never connected

```
**_Debug logs :_** 

```
2019/10/29 20:47:29 ossec-authd[16193] main-server.c:649 at run_dispatcher(): INFO: New connection from 172.168.55.121
2019/10/29 20:47:29 ossec-authd[16193] main-server.c:685 at run_dispatcher(): DEBUG: Request received: <OSSEC A:'agentwithoutrootCA'
>
2019/10/29 20:47:29 ossec-authd[16193] main-server.c:722 at run_dispatcher(): INFO: Received request for a new agent (agentwithoutrootCA) from: 172.168.55.121
2019/10/29 20:47:29 ossec-authd[16193] main-server.c:960 at run_dispatcher(): INFO: Duplicated IP '172.168.55.121' (025). Saving backup.
2019/10/29 20:47:29 ossec-authd[16193] validate.c:845 at OS_RemoveAgentGroup(): DEBUG: At OS_RemoveAgentGroup(): Could not open file '/queue/agent-groups/025'
2019/10/29 20:47:29 ossec-authd[16193] main-server.c:1082 at run_dispatcher(): INFO: Agent key generated for 'agentwithoutrootCA' (requested by 172.168.55.121)
2019/10/29 20:47:29 ossec-authd[16193] validate.c:685 at OS_BackupAgentInfo(): DEBUG: Couldn't create some backup files.
2019/10/29 20:47:33 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
2019/10/29 20:47:33 ossec-remoted: INFO: (1410): Reading authentication keys file.

```

- Registering with wrong rootCA.pem (related issue https://github.com/wazuh/wazuh/issues/2994) : 

```
[root@Agent1 vagrant]# /var/ossec/bin/agent-auth -m 172.168.55.100 -v /var/ossec/etc/rootCA.pem -A agentwithrootCA -d
2019/10/29 20:44:17 agent-auth[5751] main-client.c:241 at main(): DEBUG: Starting ...
2019/10/29 20:44:17 agent-auth[5751] main-client.c:271 at main(): INFO: Started (pid: 5751).
2019/10/29 20:44:17 agent-auth[5751] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.
2019/10/29 20:44:17 agent-auth[5751] ssl.c:171 at load_ca_cert(): ERROR: Unable to read CA certificate file "/var/ossec/etc/rootCA.pem"
2019/10/29 20:44:17 agent-auth[5751] main-client.c:286 at main(): ERROR: SSL error. Exiting.

```

**Comment by elwali10** [comment] 2019-10-30 18:27
_**Additional information :**_ 

When using SAN (https://en.wikipedia.org/wiki/Subject_Alternative_Name) which allows various DNS/IPS to be associated to one security certificate (May be similar to wildcard certificate) using subjectAltName field the Wazuh manager fails to verify this type of certs.

**_Steps to reproduce  :_**  

- Create and issue the wazuh manager certs : 

```
[root@walitest vagrant]# openssl req -new -nodes -newkey rsa:4096 -keyout sslmanager.key -out sslmanager.csr -subj '/C=US/CN=192.177.56.100/subjectAltName=wazuh'


[root@walitest vagrant]# openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out sslmanager.cert -CAcreateserial
Signature ok
subject=/C=US/CN=192.177.56.100/subjectAltName=wazuh
Getting CA Private Key
``` 

Normally by using SAN we should be able to use the alternative name or common name when.

- Copy the rootCA.pem to the wazuh agent and register it : 

**_Registring with the CN works (but fails sometimes) :_** 

```
root@vagrant-ubuntu-trusty:/home/vagrant# /var/ossec/bin/agent-auth -m 192.177.56.100 -v /var/ossec/etc/rootCA.pem  -d
2019/10/30 18:16:11 agent-auth[7958] main-client.c:241 at main(): DEBUG: Starting ...
2019/10/30 18:16:11 agent-auth[7958] main-client.c:271 at main(): INFO: Started (pid: 7958).
2019/10/30 18:16:11 agent-auth[7958] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.
2019/10/30 18:16:11 agent-auth[7958] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2019/10/30 18:16:11 agent-auth[7958] main-client.c:330 at main(): INFO: No authentication password provided.
2019/10/30 18:16:11 agent-auth[7958] main-client.c:355 at main(): INFO: Connected to 192.177.56.100:1515
2019/10/30 18:16:11 agent-auth[7958] main-client.c:362 at main(): INFO: Verifying manager's certificate
2019/10/30 18:16:11 agent-auth[7958] check_cert.c:52 at check_x509_cert(): DEBUG: Checking certificate's subject alternative names.
2019/10/30 18:16:11 agent-auth[7958] check_cert.c:58 at check_x509_cert(): DEBUG: No matching subject alternative names found. Checking common name.
2019/10/30 18:16:11 agent-auth[7958] main-client.c:370 at main(): INFO: Using agent name as: vagrant-ubuntu-trusty
2019/10/30 18:16:11 agent-auth[7958] main-client.c:418 at main(): INFO: Send request to manager. Waiting for reply.
2019/10/30 18:16:11 agent-auth[7958] main-client.c:443 at main(): INFO: Received response with agent key
2019/10/30 18:16:11 agent-auth[7958] main-client.c:477 at main(): INFO: Valid key created. Finished.
2019/10/30 18:16:11 agent-auth[7958] main-client.c:485 at main(): INFO: Connection closed.
```

**_Registering with the alternative name always fails :_** 

```
root@vagrant-ubuntu-trusty:/home/vagrant# /var/ossec/bin/agent-auth -m wazuh -v /var/ossec/etc/rootCA.pem  -d
2019/10/30 18:15:59 agent-auth[7957] main-client.c:241 at main(): DEBUG: Starting ...
2019/10/30 18:15:59 agent-auth[7957] main-client.c:271 at main(): INFO: Started (pid: 7957).
2019/10/30 18:15:59 agent-auth[7957] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.
2019/10/30 18:15:59 agent-auth[7957] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.
2019/10/30 18:15:59 agent-auth[7957] main-client.c:330 at main(): INFO: No authentication password provided.
2019/10/30 18:15:59 agent-auth[7957] main-client.c:355 at main(): INFO: Connected to 192.177.56.100:1515
2019/10/30 18:15:59 agent-auth[7957] main-client.c:362 at main(): INFO: Verifying manager's certificate
2019/10/30 18:15:59 agent-auth[7957] check_cert.c:52 at check_x509_cert(): DEBUG: Checking certificate's subject alternative names.
2019/10/30 18:15:59 agent-auth[7957] check_cert.c:58 at check_x509_cert(): DEBUG: No matching subject alternative names found. Checking common name.
2019/10/30 18:15:59 agent-auth[7957] main-client.c:364 at main(): ERROR: Unable to verify server certificate.
```

**Comment by TomasTurina** [comment] 2019-11-05 15:36
Hi,

After an analysis, I reached the following conclusions:

- Regarding the problem with the manager verification, it is also registered when the CA certificate is not included with the -v option because it follows the simple registration service explained in this section of the documentation: https://documentation.wazuh.com/3.10/user-manual/registering/linux-unix-simple-registration.html.

- This is the expected behaviour by design, so to solve this problem, we've decided to include a new configuration option to allow the user decide whether to enforce the certificate verification or not. You can take a look at the issue related to this to stay updated: https://github.com/wazuh/wazuh/issues/4190.

- Regarding the SAN verification failure, there is a problem with the way you are creating manager certificates. The `subjectAltName` shouldn't be in the -subj option, it should be in the request extensions. Note that our embedded version of openssl is 1.1.0. You can follow these instructions to create a correct certificate with SAN:  https://www.endpoint.com/blog/2014/10/30/openssl-csr-with-alternative-names-one.

Please, let me know if you need help with any of these points.

Regards,

Tomás Turina.

**Comment by elwali10** [comment] 2019-11-06 16:54
Hello @TomasTurina,

Thanks for prompt response, and having https://github.com/wazuh/wazuh/issues/4190 is definitely needed to be part of the design to ensure registering only agents whose having a rootCA issued by the Wazuh manager.


On the other hand, Regarding SAN it still fails even when using the approach provided (which I have tested before) as you may see below : 

**_-  Create my SAN file to alternative dns :_**   

```
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
[ req_distinguished_name ]
countryName                 = Country Name (2 letter code)
stateOrProvinceName         = State or Province Name (full name)
localityName               = Locality Name (eg, city)
organizationName           = Organization Name (eg, company)
commonName                 = Common Name (e.g. server FQDN or YOUR name)
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = wazuh
DNS.2   = wazuh.test.com
```

-  _**Then use the san.cnf file to create the Wazuh master certificates (you will be prompt to add additional information) and sign them :**_ 

```
openssl req -out sslmanager.csr -newkey rsa:2048 -nodes -keyout sslmanager.key -config san.cnf
openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out sslmanager.cert -CAcreateserial
```


**_- Finally the registration phase (Tested with different agents against the same Wazuh manager) :_** 

_1. successful attempt :_ 

```
[root@Agent1 etc]# /var/ossec/bin/agent-auth -m wazuh -v /var/ossec/etc/rootCA.pem 
2019/10/28 21:18:03 agent-auth: INFO: Started (pid: 6620).
2019/10/28 21:18:03 agent-auth: INFO: No authentication password provided.
2019/10/28 21:18:03 agent-auth: INFO: Connected to 172.168.55.100:1515
2019/10/28 21:18:03 agent-auth: INFO: Verifying manager's certificate
2019/10/28 21:18:03 agent-auth: INFO: Using agent name as: Agent1
2019/10/28 21:18:03 agent-auth: INFO: Send request to manager. Waiting for reply.
2019/10/28 21:18:03 agent-auth: INFO: Received response with agent key
2019/10/28 21:18:03 agent-auth: INFO: Valid key created. Finished.
2019/10/28 21:18:03 agent-auth: INFO: Connection closed.
```
 
_2. failure attempt :_ 

```
sh-3.2# /Library/Ossec/bin/agent-auth -m wazuh -v /Library/Ossec/etc/rootCA.pem -d

2019/10/29 10:54:50 agent-auth[75354] debug_op.c:252 at os_logging_config(): DEBUG: (1228): Element 'log_format' without any option.

2019/10/29 10:54:50 agent-auth[75354] main-client.c:241 at main(): DEBUG: Starting ...

2019/10/29 10:54:50 agent-auth[75354] main-client.c:271 at main(): INFO: Started (pid: 75354).

2019/10/29 10:54:50 agent-auth[75354] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.

2019/10/29 10:54:50 agent-auth[75354] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.

2019/10/29 10:54:51 agent-auth[75354] main-client.c:330 at main(): INFO: No authentication password provided.

2019/10/29 10:54:51 agent-auth[75354] ssl.c:191 at verify_callback(): ERROR: Problem with certificate at depth 0

2019/10/29 10:54:51 agent-auth[75354] ssl.c:194 at verify_callback(): ERROR: issuer = /C=US/ST=California/CN=Wazuh

2019/10/29 10:54:51 agent-auth[75354] ssl.c:197 at verify_callback(): ERROR: subject = /C=US/ST=California/CN=Wazuh

2019/10/29 10:54:51 agent-auth[75354] ssl.c:199 at verify_callback(): ERROR: 18:self signed certificate

2019/10/29 10:54:51 agent-auth[75354] main-client.c:349 at main(): ERROR: SSL error (1). Connection refused by the manager. Maybe the port specified is incorrect. Exiting.

4592137664:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
```

_3. Alternative name not recognized :_ 

```
sh-3.2# /Library/Ossec/bin/agent-auth -m wazuh.test.com -v /Library/Ossec/etc/rootCA.pem -d

2019/10/29 10:54:50 agent-auth[75354] debug_op.c:252 at os_logging_config(): DEBUG: (1228): Element 'log_format' without any option.

2019/10/29 10:54:50 agent-auth[75354] main-client.c:241 at main(): DEBUG: Starting ...

2019/10/29 10:54:50 agent-auth[75354] main-client.c:271 at main(): INFO: Started (pid: 75354).

2019/10/29 10:54:50 agent-auth[75354] ssl.c:47 at os_ssl_keys(): DEBUG: Peer verification requested.

2019/10/29 10:54:50 agent-auth[75354] ssl.c:83 at os_ssl_keys(): DEBUG: Returning CTX for client.

2019/10/29 10:54:51 agent-auth[75354] main-client.c:330 at main(): INFO: No authentication password provided.

2019/10/29 10:54:51 agent-auth[75354] ssl.c:191 at verify_callback(): ERROR: Problem with certificate at depth 0

2019/10/29 10:54:51 agent-auth[75354] ssl.c:194 at verify_callback(): ERROR: issuer = /C=US/ST=California/CN=Wazuh

2019/10/29 10:54:51 agent-auth[75354] ssl.c:197 at verify_callback(): ERROR: subject = /C=US/ST=California/CN=Wazuh

2019/10/29 10:54:51 agent-auth[75354] ssl.c:199 at verify_callback(): ERROR: 18:self signed certificate

2019/10/29 10:54:51 agent-auth[75354] main-client.c:349 at main(): ERROR: SSL error (1). Connection refused by the manager. Maybe the port specified is incorrect. Exiting.

4592137664:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1230:
```

Regards,
Wali

**Comment by TomasTurina** [comment] 2019-11-06 20:48
Hi @elwali10,

After some research, I realized that the `altnames` weren't being copied from `sslmanager.csr` to `sslmanager.cert`. 

To copy them in the manager certificate file, you have to run the following commands:

> openssl req -out sslmanager.csr -newkey rsa:2048 -nodes -keyout sslmanager.key -config req.conf

> openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out sslmanager.cert -CAcreateserial -extfile req.conf -extensions req_ext

You need to add `-extfile` and `-extensions` options when you create the manager certificate. They work as follows:
1) The `-extfile req.conf` option will copy the subject from `sslmanager.csr` to `sslmanager.cert`.
2) The ` -extensions req_ext` option after `-extfile req.conf` will also copy the request extensions section from `sslmanager.csr` to `sslmanager.cert`.
3) The `-extensions req_ext` option won't work alone, you need to specify the configuration file too.

Please, let me know if this problem is solved.

Regards,

Tomás.

**Comment by elwali10** [comment] 2019-11-07 15:20
Hello @TomasTurina 

Thanks for investigate this matter. I confirm that using the aforementioned options i was able to register my agents with different dns. 

For anyone that may find it useful following are the steps to register your Wazuh agents with a **_SAN cert_** (can be deemed as a wildcard cert) : 

1 - _If you do not have  a certificate of Authority (CA), it may be created as following :_ 
```
openssl req -x509 -new -nodes -newkey rsa:4096 -keyout rootCA.key -out rootCA.pem -batch -subj "/C=US/ST=CA/O=Manager"
```

2 - _Create your SAN file, I'm naming it **req.conf** :_ 

```
[ req ]
default_bits       = 2048
distinguished_name = req_distinguished_name
req_extensions     = req_ext
[ req_distinguished_name ]
countryName                 = Country Name (2 letter code)
stateOrProvinceName         = State or Province Name (full name)
localityName               = Locality Name (eg, city)
organizationName           = Organization Name (eg, company)
commonName                 = Common Name (e.g. server FQDN or YOUR name)
[ req_ext ]
subjectAltName = @alt_names
[alt_names]
DNS.1   = wazuh
DNS.2   = wazuh.test.com
```

3 - _Issue and sign  your wazuh manager certificates :_ 

```
openssl req -out sslmanager.csr -newkey rsa:2048 -nodes -keyout sslmanager.key -config req.conf

openssl x509 -req -days 365 -in sslmanager.csr -CA rootCA.pem -CAkey rootCA.key -out sslmanager.cert -CAcreateserial -extfile req.conf -extensions req_ext
```

4 - _Overwrite the wazuh manager existing certs and restart your Wazuh manager :_ 

```
# mv sslmanager.cert sslmanager.key /var/ossec/etc/
mv: overwrite ‘/var/ossec/etc/sslmanager.cert’? y
mv: overwrite ‘/var/ossec/etc/sslmanager.key’? y

# systemctl restart wazuh-manager
```

5 - _Then register your agents using the different DNS after placing the rootCA.pem as following :_ 

```
[root@Agent1 vagrant]# /var/ossec/bin/agent-auth -m wazuh.test.com -v /var/ossec/etc/rootCA.pem  
2019/11/07 15:11:53 agent-auth: INFO: Started (pid: 8752).
2019/11/07 15:11:53 agent-auth: INFO: No authentication password provided.
2019/11/07 15:11:53 agent-auth: INFO: Connected to 172.168.56.144:1515
2019/11/07 15:11:53 agent-auth: INFO: Verifying manager's certificate
2019/11/07 15:11:53 agent-auth: INFO: Using agent name as: Agent1
2019/11/07 15:11:53 agent-auth: INFO: Send request to manager. Waiting for reply.
2019/11/07 15:11:53 agent-auth: INFO: Received response with agent key
2019/11/07 15:11:53 agent-auth: INFO: Valid key created. Finished.
2019/11/07 15:11:53 agent-auth: INFO: Connection closed.

[root@Agent2 vagrant]# /var/ossec/bin/agent-auth -m wazuh -v /var/ossec/etc/rootCA.pem 
2019/11/07 15:11:55 agent-auth: INFO: Started (pid: 8753).
2019/11/07 15:11:55 agent-auth: INFO: No authentication password provided.
2019/11/07 15:11:55 agent-auth: INFO: Connected to 172.168.56.144:1515
2019/11/07 15:11:55 agent-auth: INFO: Verifying manager's certificate
2019/11/07 15:11:55 agent-auth: INFO: Using agent name as: Agent2
2019/11/07 15:11:55 agent-auth: INFO: Send request to manager. Waiting for reply.
2019/11/07 15:11:55 agent-auth: INFO: Received response with agent key
2019/11/07 15:11:55 agent-auth: INFO: Valid key created. Finished.
2019/11/07 15:11:55 agent-auth: INFO: Connection closed.
```


Big shout-out for @TomasTurina :D.

Regards,
Wali

**Comment by chemamartinez** [comment] 2019-11-18 18:23
Hi @elwali10 and @TomasTurina,

Both solutions for this issue have been just merged:

- Warning message when the agent is registered without verifying the manager identity: https://github.com/wazuh/wazuh/pull/4207
- Improved the manager verification section of the documentation to add an explanation for using SAN: https://github.com/wazuh/wazuh-documentation/pull/2005

Let me close this issue, GJ both of you!

Regards,
Chema.

**Closed** 2019-11-21 09:58 UTC
Labels: bug, operations
