### ISSUE TITLE
Warnings in SCA policy analysis 4.3.0

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#11092] opened 2021-11-29 12:31 UTC
As reported in https://github.com/wazuh/wazuh/issues/11019#issuecomment-980453570 we have found some problems inside Windows Wazuh agent logs related with SCA module.

```
WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\stress_files_policy.yml'. Skipping it.
WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\stress_registers_policy.yml'. Skipping it.
WARNING: Error found while parsing file: 'C:\Program Files (x86)\ossec-agent\ruleset\sca\cis_win2019.yml'. Skipping it.
```

The errors were found in:
- [All-except-syscollector](https://github.com/wazuh/wazuh/issues/11046)
- [All-except-Docker(...)](https://github.com/wazuh/wazuh/issues/11033)
- [All-except-AR](https://github.com/wazuh/wazuh/issues/11035)
- [All-except-rootcheck](https://github.com/wazuh/wazuh/issues/11040)
- [All](https://github.com/wazuh/wazuh/issues/11039)

**Comment by chemamartinez** [comment] 2021-12-09 17:10
This issue is probably caused by the memory leak reported at https://github.com/wazuh/wazuh/issues/11084 and fixed in https://github.com/wazuh/wazuh/pull/11118.

The lack of memory can lead to an error when parsing the SCA policy.

This is coherent with the following analysis:
- The policies are YML valid files
- The errors appear at the end of the test

We will wait for the following RC to repeat the tests and check if the error disappears along with the memory leak.

**Comment by vikman90** [comment] 2022-01-11 11:42
https://github.com/wazuh/wazuh/issues/11688 does not show any noticeable memory increase. Closing this issue.

**Closed by vikman90** 2022-01-11 11:42 UTC
Labels: cicd, cicd-tracked
