### ISSUE TITLE
Release 4.5.2 - RC 1 - System tests

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh#18691] opened 2023-08-28 17:24 UTC
The following issue aims to run all `system tests` for the current release candidate, report the results, and open new issues for any encountered errors.

## System tests information
|                                      |                                            |
|--------------------------------------|--------------------------------------------|
| **Main release candidate issue**     | https://github.com/wazuh/wazuh/issues/18617 |
| **Version**                          |4.5.2|
| **Release candidate #**              |RC 1|
| **Tag**                              | https://github.com/wazuh/wazuh/tree/v4.5.2-rc1 |
| **Previous system tests issue**      |https://github.com/wazuh/wazuh/issues/18497|

## Test report procedure
All individual test checks must be marked as:
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| Pass | The test ran successfully. |
| Xfail | The test was expected to fail and it failed. It must be properly justified and reported in an issue.  |
| Skip | The test was not run. It must be properly justified and reported in an issue.  |
| Fail | The test failed. A new issue must be opened to evaluate and address the problem. |

All test results must have one the following statuses: 
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| :green_circle:  | All checks passed. |
| :red_circle:  | There is at least one failed check. |
| :yellow_circle:  | There is at least one expected fail or skipped test and no failures. |

Any failing test must be properly addressed with a new issue, detailing the error and the possible cause. It must be included in the `Fixes` section of the current release candidate main issue.

Any expected fail or skipped test must have an issue justifying the reason. All auditors must validate the justification for an expected fail or skipped test.

An extended report of the test results must be attached as a zip or txt. This report can be used by the auditors to dig deeper into any possible failures and details.

## Auditors validation

- [ ]

**Comment by QU3B1M** [comment] 2023-08-28 20:23
The System tests were executed in a EC2 machine, later for some reason this machine was stopped, after starting it again when I try to connect using `ssh`, it fails because of timeout.

**Comment by davidjiglesias** [comment] 2023-08-29 11:38
Duplicate of https://github.com/wazuh/wazuh/issues/18696

**Closed** 2023-08-29 11:38 UTC
Labels: type/test, level/task
