### ISSUE TITLE
Fix webhook endpoints integration test - 4.9.0

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh#19724] opened 2023-10-18 18:49 UTC
|Wazuh version|Component|
|---|---|
| 4.9.0 | API |

## Description

When trying to execute the `test_webhook_endpoints.tavern.yaml` integration test, pytest fails saying that that one of the marks is not an attrs-decorated class.

The test uses the `usefixtures` mark that is not present in any other test and that seems to be conflicting with the pytest version we use.

Artifacts of a failed [PR](https://github.com/wazuh/wazuh/pull/18619) check: [Test_integration_endpoints_B3940_test_event_endpoints.zip](https://github.com/wazuh/wazuh/files/13032690/Test_integration_endpoints_B3940_test_event_endpoints.zip)

<details><summary>test_webhook_endpoints.tavern.yaml</summary>

```console
(venv) gasti@pop-os:~/work/wazuh/api/test/integration$ pytest -vv test_webhook_endpoints.tavern.yaml
========================================================================== test session starts ==========================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/gasti/work/wazuh/venv/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-76060200-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.0.0'}, 'Plugins': {'asyncio': '0.18.1', 'tavern': '1.23.5', 'trio': '0.7.0', 'html': '2.1.1', 'aiohttp': '1.0.4', 'metadata': '3.0.0'}}
rootdir: /home/gasti/work/wazuh/api/test/integration
configfile: pytest.ini
plugins: asyncio-0.18.1, tavern-1.23.5, trio-0.7.0, html-2.1.1, aiohttp-1.0.4, metadata-3.0.0
asyncio: mode=auto
collected 0 items / 1 error                                                                                                                                             

================================================================================ ERRORS =================================================================================
__________________________________________________________ ERROR collecting test_webhook_endpoints.tavern.yaml __________________________________________________________
../../../venv/lib/python3.9/site-packages/tavern/testutils/pytesthook/file.py:325: in collect
    for i in self._generate_items(test_spec):
../../../venv/lib/python3.9/site-packages/tavern/testutils/pytesthook/file.py:300: in _generate_items
    item.add_markers(pytest_marks)
../../../venv/lib/python3.9/site-packages/tavern/testutils/pytesthook/item.py:103: in add_markers
    new_mark = attr.evolve(pm.mark, args=pm.mark.args[0])
../../../venv/lib/python3.9/site-packages/attr/_funcs.py:404: in evolve
    attrs = fields(cls)
../../../venv/lib/python3.9/site-packages/attr/_make.py:1944: in fields
    raise NotAnAttrsClassError(f"{cls!r} is not an attrs-decorated class.")
E   attr.exceptions.NotAnAttrsClassError: <class '_pytest.mark.structures.Mark'> is not an attrs-decorated class.
=========================================================================== warnings summary ============================================================================
../../../venv/lib/python3.9/site-packages/_pytest/nodes.py:642
  /home/gasti/work/wazuh/venv/lib/python3.9/site-packages/_pytest/nodes.py:642: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to YamlFile is deprecated. Please use the (path: pathlib.Path) argument instead.
  See https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path
    return super().from_parent(parent=parent, fspath=fspath, path=path, **kw)

../../../venv/lib/python3.9/site-packages/pytest_trio/plugin.py:62
  /home/gasti/work/wazuh/venv/lib/python3.9/site-packages/pytest_trio/plugin.py:62: TrioDeprecationWarning: trio.MultiError is deprecated since Trio 0.22.0; use BaseExceptionGroup (on Python 3.11 and later) or exceptiongroup.BaseExceptionGroup (earlier versions) instead (https://github.com/python-trio/trio/issues/2211)
    if issubclass(call.excinfo.type, trio.MultiError):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================== short test summary info ========================================================================
ERROR test_webhook_endpoints.tavern.yaml - attr.exceptions.NotAnAttrsClassError: <class '_pytest.mark.structures.Mark'> is not an attrs-decorated class.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
===================================================================== 2 warnings, 1 error in 0.10s ======================================================================
```

</details>

## Checks

The following elements have been updated or reviewed (should also be checked if no modification is required):
- [x] Tests (unit tests, API integration tests).
- [x] Changelog.
- [x] Documentation.
- [x] Integration test mapping (using `api/test/integration/mapping/_test_mapping.py`).

**Comment by fdalmaup** [comment] 2023-10-20 11:44
The described error was also found in #19612. Since it is due to test dependencies added in `4.7.0`, we are reviewing the test in said issue to add the changes in upward versions (`4.8.0` and `4.9.0`).

**Comment by javiersanchz** [comment] 2023-11-10 17:23
## Update 

   - I was troubleshooting with env-wazuh-master-1 when launching integration tests.
   - I reproduced the problem and was seeing where it came from.

**Comment by javiersanchz** [comment] 2023-11-13 12:16
## Update

 - The tests from `test_webhook_endpoints.tavern.yaml` have been renamed to `test_event_endpoints.tavern.yaml` in the following PR:
https://github.com/wazuh/wazuh/pull/18619

 - The error displayed in the issue seems to have been resolved in this PR as well. The `test_event_endpoints.tavern.yaml` has been tested locally and on Jenkins, and all tests pass successfully as shown below: 

```
/Git/wazuh/api/test/integration$ pytest -vv test_event_endpoints.tavern.yaml
=========================================================================================== test session starts ============================================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.2.0 -- /home/wazuh/venv/api-it/bin/python
cachedir: .pytest_cache
metadata: {'Python': '3.9.16', 'Platform': 'Linux-6.2.0-32-generic-x86_64-with-glibc2.35', 'Packages': {'pytest': '7.3.1', 'pluggy': '1.2.0'}, 'Plugins': {'metadata': '3.0.0', 'aiohttp': '1.0.4', 'html': '2.1.1', 'trio': '0.7.0', 'asyncio': '0.18.1', 'tavern': '1.23.5'}}
rootdir: /home/wazuh/Git/wazuh/api/test/integration
configfile: pytest.ini
plugins: metadata-3.0.0, aiohttp-1.0.4, html-2.1.1, trio-0.7.0, asyncio-0.18.1, tavern-1.23.5
asyncio: mode=auto
collected 5 items                                                                                                                                                                                          

test_event_endpoints.tavern.yaml::POST /events PASSED                                                                                                                                                [ 20%]
test_event_endpoints.tavern.yaml::POST /events with invalid formats PASSED                                                                                                                           [ 40%]
test_event_endpoints.tavern.yaml::POST /events with more than 100 events PASSED                                                                                                                      [ 60%]
test_event_endpoints.tavern.yaml::POST /events with big events PASSED                                                                                                                                [ 80%]
test_event_endpoints.tavern.yaml::Try to send more than 30 requests per minute PASSED                                                                                                                [100%]
```

## Test report
[Artifacts.zip](https://github.com/wazuh/wazuh/files/13334654/Artifacts.zip)

![image](https://github.com/wazuh/wazuh/assets/96108386/80f5564c-710a-494e-a0fc-ad66977f964c)


## Test results
---
| **Test name** | **Pass** | **XPass** | **Skip** | **XFail** | **Fail** | **Issues Ref.** | **Status** |
|--|--|--|--|--|--|--|--|
| test_event_endpoints.tavern.yaml | 5 | 0 | 0 | 0 | 0 |  | :green_circle: |

```

**Comment by EduLeon12** [comment] 2023-11-13 15:00
## Review update

After looking at the different issues and solutions in the updates regarding the main problem (testing dependencies versions), I can conclude it is fixed in the mentioned branch, The mentioned test is passing without errors or warnings. Therefore, the issue scope has been fulfilled and can be closed.

LGTM!

**Closed** 2023-11-15 12:31 UTC
Labels: type/bug, level/task
