### ISSUE TITLE
Integrator not running 

### ISSUE THREAD

**Issue by bearrito** [wazuh/wazuh#43] opened 2016-09-02 02:36 UTC
I followed the docs at - https://github.com/wazuh/wazuh-documentation/blob/master/source/manual_integrator.rst

The integrator does not appear to be running.

I don't see anything relevant in the ossec.log or the integrations.log.

 I have generated events that match the filter.

Terminal output

```
root@host:/var/ossec# /var/ossec/bin/ossec-control enable integrator
root@host:/var/ossec# /var/ossec/bin/ossec-control restart
Killing ossec-monitord .. 
Killing ossec-logcollector .. 
Killing ossec-syscheckd .. 
Killing ossec-analysisd .. 
ossec-maild not running ..
ossec-execd not running ..
ossec-integratord not running ..
OSSEC HIDS v2.8 Stopped
Starting OSSEC HIDS v2.8 (by Trend Micro Inc.)...
2016/09/02 02:29:09 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.
root@host:/var/ossec# /var/ossec/bin/ossec-control status
ossec-monitord is running...
ossec-logcollector is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd not running...
ossec-integratord not running...
root@host-0:/var/ossec# 
```

Settings

```
  <integration>
   <name>slack</name>
   <hook_url>https://hooks.slack.com/services/REDACTED</hook_url>
   <level>7</level>
  </integration>
```

Edit:

If I run the integratord in the foreground it seems to work

```
root@host:/var/ossec# /var/ossec/bin/ossec-integratord -t 
root@host:/var/ossec# /var/ossec/bin/ossec-integratord -f
2016/09/02 02:52:25 ossec-integratord: INFO: Started (pid: 57697).
2016/09/02 02:52:25 ossec-integratord: INFO: Enabling integration for: 'slack'.
```

If I then stop it running in the foreground and then check the status it shows as running, but I need to be able to do this non-interactively since I'll start the whole process off using configuration management tools.

**Comment by vikman90** [comment] 2016-09-02 10:17
Hi @bearrito,

Thanks for your feedback. I followed your steps but I couldn't reproduce the issue. A line printing `Started ossec-integratord...` should appear in your log since `integrator` is enabled.

I think that the issue is at the `ossec-control` script, not the `integrator` daemon. The process settings are stored on `/var/ossec/bin/.process_list`. Its content should be:

`INTEGRATOR_DAEMON=ossec-integratord`

Please, try to remove it and re-enable `integrator`.

On the other hand, what about starting `/var/ossec/integratord` as a daemon (without the `-f` option)? If you do this, then `ossec-control status` should print that `ossec-integratord` is running.

Please tell us that version are you using and write back to us if you can try these things.

Thank you for your comment.
Kind regards.

**Comment by bearrito** [comment] 2016-09-02 16:51
@vikman90 I tried the latter approach of starting the daemon in the background and that is working as you suggessted.

I'll give your other suggestion a try later today and report back with the result.

Thanks for the fast response.

**Comment by bearrito** [comment] 2016-10-20 13:24
Hello all. This was working for a while and now I've noticed that the integrator doesn't seem to be working. I see no errors in the integration.log. The status shows that integratord is running.

What's the best way for me to debug this.

**Comment by vikman90** [comment] 2016-10-20 14:07
Hi @bearrito,

Do you see any message such these on the `ossec.log`?

> 2016/10/20 15:42:04 ossec-integratord: INFO: Started (pid: 3480).
> 2016/10/20 15:42:04 ossec-integratord: INFO: Enabling integration for: 'slack'.

If you do, please review your Slack configuration. I've tested it with the following one:

>`<integration>`
>&nbsp;&nbsp;`<name>slack</name>`
>&nbsp;&nbsp;`<hook_url>https://hooks.slack.com/services/ABCdefGHI12345</hook_url>`
>&nbsp;&nbsp;`<level>3</level>`
>`</integration>`

If you can't find any log, maybe there's a remaining PID file. You should follow these steps:

1. Stop OSSEC: `/var/ossec/bin/ossec-control stop`
2. List PID files at runtime directory: `ls -l /var/ossec/var/run/*.pid`. There should be no such files. If there's a file like `ossec-integratord-????.pid`, remove it.
3. Start OSSEC again: `/var/ossec/bin/ossec-control start`

Please write back to us if the issue persists. Thanks for your feedback.
Best regards.

**Comment by bearrito** [comment] 2016-10-20 14:54
Checking Status Initially
```
root@bnr-eastus-bastion-0:/home/barrett# /var/ossec/bin/ossec-control status
ossec-monitord is running...
ossec-logcollector is running...

ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
ossec-integratord is running...
```

Slack config

```
   <integration>
    <name>slack</name>
    <hook_url>https://hooks.slack.com/services/REDACTED</hook_url>
    <level>2</level>
  </integration>

```
Stop it and check PID
```
root@bnr-eastus-bastion-0:/var/ossec# /var/ossec/bin/ossec-control stop
ossec-monitord not running ..
ossec-logcollector not running ..
ossec-syscheckd not running ..
ossec-analysisd not running ..
ossec-maild not running ..
ossec-execd not running ..
ossec-integratord not running ..
OSSEC HIDS v2.8 Stopped
root@bnr-eastus-bastion-0:/var/ossec# ls -l /var/ossec/var/run/
total 0
```

Start it back up and run in foreground
```
root@bnr-eastus-bastion-0:/var/ossec# /var/ossec/bin/ossec-control start
Starting OSSEC HIDS v2.8 (by Trend Micro Inc.)...
2016/10/20 14:47:42 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.
root@bnr-eastus-bastion-0:/var/ossec# /var/ossec/bin/ossec-integratord -f
2016/10/20 14:48:05 ossec-integratord: INFO: Started (pid: 4827).
2016/10/20 14:48:05 ossec-integratord: INFO: Enabling integration for: 'slack'.
```

Check PID (Are permissions correct?)
```
root@bnr-eastus-bastion-0:/home/barrett# ls -l /var/ossec/var/run/*.pid
-rw-r----- 1 ossec  ossec 5 Oct 20 14:47 /var/ossec/var/run/ossec-analysisd-4804.pid
-rw-r----- 1 root   ossec 5 Oct 20 14:47 /var/ossec/var/run/ossec-execd-4799.pid
-rw-r----- 1 ossecm ossec 5 Oct 20 14:48 /var/ossec/var/run/ossec-integratord-4827.pid
-rw-r----- 1 root   root  5 Oct 20 14:47 /var/ossec/var/run/ossec-logcollector-4808.pid
-rw-r----- 1 ossec  ossec 5 Oct 20 14:47 /var/ossec/var/run/ossec-monitord-4815.pid
-rw-r----- 1 root   root  5 Oct 20 14:47 /var/ossec/var/run/ossec-syscheckd-4812.pid
```

Don't see any incoming messages and nothing in /var/ossec/logs/integrations.log. 
I have logged in and out of the host a couple times which generated RL 3 messages in alerts.log.

**Comment by vikman90** [comment] 2016-10-20 15:35
Yes, permissions appear to be correct. But I see that no `Started ossec-integratord...` appears at `ossec-control start`.

When you enable Integratord, a hidden file is created at `/var/ossec/bin/.process_list` with this content:

> `INTEGRATOR_DAEMON=ossec-integratord`

It must be enabled correctly because it appears at `ossec-control stop` but it's strange that it appears here and not at the former call.

Please tell me what OS you have and the Wazuh version that you're using, so maybe I could reproduce this problem.

**Comment by bearrito** [comment] 2016-10-20 15:54
Kernel 3.19.0-65-generic #73~14.04  Ubuntu 14.04.04

I have been using https://github.com/wazuh/ossec-wazuh/archive/v1.1.1.tar.gz

INTEGRATOR_DAEMON does appear in that file on my host.

**Comment by vikman90** [comment] 2016-10-20 16:44
When you launch `ossec-control` it prints:

> `Starting OSSEC HIDS v2.8 (by Trend Micro Inc.)...`

It should print:

> `Starting OSSEC HIDS v2.9.0 (by Trend Micro Inc.)...`

It occurs when the file `/etc/ossec-init.conf` (a copy from `/var/ossec/ossec-init.conf`) doesn't exist. And this also produces to show the version v2.8 and not to start `ossec-integratord` properly. Please create a copy from that file at OSSEC directory on `/etc`:

> `cp /var/ossec/etc/ossec-init.conf /etc`

It should contain something like this:

>DIRECTORY="/var/ossec"
>VERSION="v2.9.0"
>WAZUH_VERSION="v1.1.1"
>DATE="Thu oct 20 18:39:40 CEST 2016"
>TYPE="server"

And try again to restart OSSEC.

**Comment by bearrito** [comment] 2016-10-20 17:20
I completely re-installed to ensure I was using the version found at - https://github.com/wazuh/ossec-wazuh/archive/v1.1.1.tar.gz

After doing that and the stops you showed, it still shows as v2.8

```
root@bnr-eastus-bastion-0:/var/ossec# /var/ossec/bin/ossec-control status
ossec-monitord is running...
ossec-logcollector is running...
ossec-syscheckd is running...
ossec-analysisd is running...
ossec-maild not running...
ossec-execd is running...
ossec-integratord is running...
root@bnr-eastus-bastion-0:/var/ossec# cat /etc/ossec-init.conf 
DIRECTORY="/var/ossec"
VERSION="v2.9.0"
WAZUH_VERSION="v1.1.1"
DATE="Thu Oct 20 17:08:04 UTC 2016"
TYPE="local"
root@bnr-eastus-bastion-0:/var/ossec# cat /var/ossec/bin/.process_list
INTEGRATOR_DAEMON=ossec-integratord
root@bnr-eastus-bastion-0:/var/ossec# /var/ossec/bin/ossec-control restart
Killing ossec-monitord .. 
Killing ossec-logcollector .. 
Killing ossec-syscheckd .. 
Killing ossec-analysisd .. 
ossec-maild not running ..
Killing ossec-execd .. 
Killing ossec-integratord .. 
OSSEC HIDS v2.8 Stopped
Starting OSSEC HIDS v2.8 (by Trend Micro Inc.)...
2016/10/20 17:14:55 ossec-maild: INFO: E-Mail notification disabled. Clean Exit.
Started ossec-maild...
Started ossec-execd...
Started ossec-analysisd...
Started ossec-logcollector...
Started ossec-syscheckd...
Started ossec-monitord...
Completed.
```

**Comment by bearrito** [comment] 2016-10-20 17:25
After a grep, I saw the `v2.8` was hardcoded into the /bin/ossec-control

**Comment by vikman90** [comment] 2016-10-21 08:42
I found the problem!

Local-mode installation doesn't enable Integrator properly, and doesn't load `/etc/ossec-init.conf`. In order to solve it you should edit `/var/ossec/bin/ossec-control` or `src/init/ossec-local.sh` (that's the actual source for `ossec-control`) and make the following changes:

1. After line 24, just after DAEMONS="ossec-monitord ... :
>`[ -f /etc/ossec-init.conf ] && . /etc/ossec-init.conf;`

2. At line 187, as first line of `start()` function, add `${INTEGRATOR_DAEMON}` to the list:
>`SDAEMONS="${DB_DAEMON} ${CSYSLOG_DAEMON} ${AGENTLESS_DAEMON} ${INTEGRATOR_DAEMON} ossec-maild ossec-execd ossec-analysisd ossec-logcollector ossec-syscheckd ossec-monitord"`

I fixed this at our development branch and it will be available officially soon in the new release: https://github.com/wazuh/ossec-wazuh/commit/27c0e09bbeed0d23881003ab8e29192eb947fbdd

This is the patched file for the v1.1.1 version: [patch.zip](https://github.com/wazuh/ossec-wazuh/files/543881/patch.zip)

With this fix, reinstalling the program and setting the Integrator configuration, it appears to work properly.

I hope it works for you. 
Thank you again for your feedback, you helped us to find a bug.

Best regards.

**Comment by bearrito** [comment] 2016-10-25 13:17
This did not seem to work for me.

Steps I took:
1. Remove my existing installation - `rm -r /var/ossec`
2. Copied the patched file to `$SRC_DIR/ossec-1.1.1/src/init/ossec-local.sh`
3. Build the application
4. Follow normal steps above to restart and re-enable integrator.

I don't see anything in logs/integration.log but I do see it enable slack in the ossec.log.
The integratord is also running.

I tried to run the master branch but that was very broken for me. Giving me the below errors.

```
2016/10/25 13:08:27 ossec-testrule: INFO: Reading decoder file etc/bossanova_decoders/openvpn_decoder.xml.
2016/10/25 13:08:27 ossec-analysisd(2106): ERROR: Error adding decoder plugin.
2016/10/25 13:08:27 ossec-analysisd: Invalid decoder name: 'pam'.
2016/10/25 13:08:27 ossec-testrule(1220): ERROR: Error loading the rules: 'pam_rules.xml'.
2016/10/25 13:08:46 ossec-testrule: INFO: Reading decoder file etc/bossanova_decoders/openvpn_decoder.xml.
2016/10/25 13:08:46 ossec-analysisd(2106): ERROR: Error adding decoder plugin.
2016/10/25 13:08:46 ossec-analysisd: Invalid decoder name: 'pam'.
2016/10/25 13:08:46 ossec-testrule(1220): ERROR: Error loading the rules: 'pam_rules.xml'.

```

**Comment by vikman90** [comment] 2016-10-25 14:50
Did you a clean installation of the new version? Please note that the `ossec_decoders` and `wazuh_decoders` folders were merged into one directory: `decoders`, and that the decoder loading order matters at `ossec.conf.`

Regarding the integrator, if nothing appears at the `integrations.log`, I suspect that either alerts aren't being read at file `integrator.c` or the `slack` script isn't working.

I'll take a deeper look into this and write back to you.
Thank you.

**Comment by bearrito** [comment] 2016-10-25 15:33
I did do a clean install of master. I might try adopt those directory change if I have the time and retest.

**Comment by bearrito** [comment] 2016-11-06 21:16
Any more thoughts on this? I'm fine running a dev branch if you guys need someone to test.

**Comment by vikman90** [comment] 2016-11-07 10:59
Hello @bearrito,

since the Slack script prints a log onto `/var/ossec/logs/integrations.log` and you have no messages at it, I think that the issue is in the daemon, so I created a new branch on the project called **debug-integrator**: https://github.com/wazuh/ossec-wazuh/tree/debug-integrator.

Please checkout that branch, install it and run the Integrator with level 2 debugging. The integrator has no option at `internal_options.conf` to enable level 2 debugging, so it's better to start it manually:

1. Prevent _integratord_ from being started by _ossec-control_: `ossec-control disable integrator`
2. Start the integrator with two "d": `/var/ossec/bin/ossec-integratord -dd`

The daemon debugging logs will appear at `/var/ossec/logs/ossec.log` and the Slack script messages will be at `/var/ossec/logs/integrations.log`.

There is another way to start the integrator: with option -f, so the program won't became a background process and you'll get the messages directly on your terminal: `/var/ossec/bin/ossec-integratord -dd -f`. If you do it this way, you must close the program with `Ctrl+C`.

Please run the integrator in debug mode and write back to us with the result so we can know with point the program fails at.

Thank you very much.
Kind regards.

**Comment by bearrito** [comment] 2017-03-11 02:22
Is this still in progress?

It looks like #58 is related?

**Comment by vikman90** [comment] 2017-03-13 00:33
Hi,

as I tell you, we were not able to reproduce this issue, that's why I created a new branch (https://github.com/wazuh/ossec-wazuh/tree/debug-integrator) with more debugging messages.

We greatly appreciate if you could clone that branch and test it. Those logs might be very useful to find the cause of this problem.

Best regards.

**Closed** 2017-12-27 06:52 UTC
Labels: bug
