### ISSUE TITLE
Review and fix sca endpoints API integration tests

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh#11474] opened 2021-12-23 13:25 UTC
|Component|
|---|
| API integration tests |

This issue is part of https://github.com/wazuh/wazuh/issues/10918.

The SCA API integration test is failing in the `4.3` branch.

The following test stage is the one failing:

```
- name: Parameters -> limit=1
    request:
      verify: False
      url: "{protocol:s}://{host:s}:{port:d}/sca/001"
      method: GET
      headers:
        Authorization: "Bearer {test_login_token}"
      params:
        limit: 1
    response:
      status_code: 200
      json:
        error: 0
        data:
          affected_items:
            - &sca_agent_result_001
              name: !anystr
              pass: !anyint
              score: !anyint
              references: !anystr
              fail: !anyint
              description: !anystr
              policy_id: !anystr
              start_scan: !anystr
              end_scan: !anystr
              hash_file: !anystr
              total_checks: !anyint
              invalid: !anyint
          total_affected_items: 1
          failed_items: []
          total_failed_items: 0
      save:
        json:
          expected_name: data.affected_items[0].name
          expected_description: data.affected_items[0].description
```

As we can see in the test output, no SCA information was returned for the agent with ID 001, when we were expecting information. This could be due to a lack of this information in the relative database. We should investigate the possible cause of this error and include a solution.

[test_sca_endpoints.txt](https://github.com/wazuh/wazuh/files/7769508/Test_integration_endpoints_B1754_test_sca_endpoints.txt)
[test_sca_endpoints.zip](https://github.com/wazuh/wazuh/files/7769510/Test_integration_endpoints_B1754_test_sca_endpoints.zip)
[test_sca_endpoints_logs.zip](https://github.com/wazuh/wazuh/files/7769511/Test_integration_endpoints_B1754_test_sca_endpoints_logs.zip)

### wazuh/wazuh
- Unit tests without failures. Updated and/or expanded if there are new functions/methods/outputs:
  - [ ] Cluster (`framework/wazuh/core/cluster/tests/` & `framework/wazuh/core/cluster/dapi/tests/`)
  - [ ] Core (`framework/wazuh/core/tests/`)
  - [ ] SDK (`framework/wazuh/tests/`)
  - [ ] RBAC (`framework/wazuh/rbac/tests/`)
  - [ ] API (`api/api/tests/`)
- API tavern integration tests without failures. Updated and/or expanded if needed (`api/test/integration/`):
  - [ ] Affected tests 
  - [ ] Affected RBAC (black and white) tests
- [ ] Review integration test mapping using the script (`api/test/integration/mapping/integration_test_api_endpoints.json`)
- [ ] Review of spec.yaml examples and schemas (`api/api/spec/spec.yaml`)
- [ ] Review exceptions remediation when any endpoint path changes or is removed (`framework/wazuh/core/exception.py`)
- [ ] Changelog (`CHANGELOG.md`)

### wazuh/wazuh-documentation
- [ ] Migration from 3.X for changed endpoints (`source/user-manual/api/equivalence.rst`)
- [ ] Update RBAC reference with new/modified actions/resources/relationships (`source/user-manual/api/rbac/reference.rst`)

**Comment by Kondent** [comment] 2022-01-18 19:48
## Update

Reviewing all the logs I found the following:
```
2021/12/23 09:35:05 ERROR: [Cluster] [Main] Unhandled exception: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO policies (id, name, policy, created_at) VALUES (?, ?, ?, ?)]
[parameters: (36, 'security_all_security', '{"actions": ["security:read", "security:update", "security:delete"], "resources": ["role:id:*", "policy:id:*", "user:id:*", "rule:id:*"], "effect": "allow"}', '2021-12-23 09:35:00.643556')]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

Seems like a race condition while accessing this `.db` file.
It could be a problem between the `entrypoint.sh` and the cluster itself.
I'm currently trying to replicate it.

**Comment by Kondent** [comment] 2022-01-19 21:15
## Update
* The mentioned SQLite error appeared at the logs of the worker1 and the script from the entrypoint which uses `rbac.db` is only available in the master node, so it's not the problem.
* The issue related with SQLite is already fixed in https://github.com/wazuh/wazuh/pull/11598.
---

While doing a few tests, I was able to replicate this error (`GET /sca/001` is not returning data for the specific agent) just once. I'm currently reviewing all logs.

**Comment by Kondent** [comment] 2022-01-20 16:56
# Update

## Conditions:
- Cluster is not running at Worker1. As we saw in `test_sca-worker1-cluster.log`:
```log
2021/12/23 09:35:05 ERROR: [Cluster] [Main] Unhandled exception: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO policies (id, name, policy, created_at) VALUES (?, ?, ?, ?)]
[parameters: (36, 'security_all_security', '{"actions": ["security:read", "security:update", "security:delete"], "resources": ["role:id:*", "policy:id:*", "user:id:*", "rule:id:*"], "effect": "allow"}', '2021-12-23 09:35:00.643556')]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

* Later on, NGINX, which is working as a load balancer in the API integration test environment, will asign this worker to the agent `001`.


## How to replicate:

I made a few tests in a local environment, in which:
* The cluster is **disabled** at worker1 node.
* The agent `004` is assigned to this worker.


### Agent4 - logs:
* Connected to the server once.
* SCA **completed** at `2022/01/20 14:33:37`.

*`oosec.log` @ wazuh-agent4:*
```log
root@wazuh-agent4:/var/ossec/logs# grep -E 'Connected to the server|sca:' ossec.log 
2022/01/20 14:33:26 sca: INFO: Module started.
2022/01/20 14:33:26 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2022/01/20 14:33:26 sca: INFO: Starting Security Configuration Assessment scan.
2022/01/20 14:33:26 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2022/01/20 14:33:34 wazuh-agentd: INFO: (4102): Connected to the server (nginx-lb/172.26.0.5:1514/tcp).
2022/01/20 14:33:37 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu20-04.yml'
2022/01/20 14:33:37 sca: INFO: Security Configuration Assessment scan finished. Duration: 11 seconds.
```

### `global.db` worker:
As expected, the information of the agent in the `global.db` file from the worker1 is correct.
```
sqlite> select * from agent where id='004';
4|wazuh-agent4|172.26.0.9|any|c21059fd406aae01b99c9e179602223e15051036eaf4f9403897bb86703ed293|Ubuntu|20.04.1 LTS|20|04|Focal Fossa||ubuntu|Linux |wazuh-agent4 |5.13.0-27-generic |#29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 |x86_64|x86_64|Wazuh v4.3.0||x|wazuh-worker1|worker1|0|1642689534|default|syncreq|active|0
```

### `global.db` master:
Since the cluster is not running at worker1 node, is not possible to synchronize the agent information.
```
sqlite> select * from agent where id='004';
4|wazuh-agent4||any|c21059fd406aae01b99c9e179602223e15051036eaf4f9403897bb86703ed293||||||||||||||unknown|0||default|synced|never_connected|0
```

### `GET /agents`:
*`api.log` @ master:*
```log
2022/01/20 14:36:51 INFO: wazuh 172.26.0.1 "GET /agents" with parameters {"select": "id,node_name"} and body {} done in 0.029s: 200
```

Response:
```json
{
  "node_name": "unknown",
  "id": "004"
},
```

### Agent4 - SCA results:
This query was made at `2022/01/20 14:37:01`, which is after the finalization of the SCA scan at agent4.

*`api.log` @ master:*
```log
2022/01/20 14:37:01 INFO: wazuh 172.26.0.1 "GET /sca/004" with parameters {} and body {} done in 0.014s: 200
```

Response:
```json
{
  "data": {
    "affected_items": [],
    "total_affected_items": 0,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "No sca information was returned",
  "error": 0
}
```

_At this point the `test_sca_endpoints` would fail if the agent were `001` instead of `004` since it's waiting for specific data from this scan but no information was returned._


## Conclusion
As mentioned in the comment above, the issue related with `sqlite` was fixed in https://github.com/wazuh/wazuh/pull/11598.
However, we need to review how to manage and handle this type of situation where an API query is made but the communication between nodes is currently unavailable. I'm opening an issue to investigate it in more depth.

**Comment by Kondent** [comment] 2022-01-21 12:13
# Update
After doing a research about the API and how it handles a request when the communication between nodes is unavailable, I found out that is properly managed. 

First of all, the previously mentioned problem was replicated while running the test itself. And as we know, our API integration test environment is pre-configured to assign agents by manual modifications to the related databases. All of these modifications are performed before the environment is completely started.

In a real Wazuh environment, this situation is not possible.

1. If we kill the cluster process in a worker node assigned to the agent `001`, the response of `GET /sca/001` will be the following:
```
{
  "title": "Wazuh Cluster Error",
  "detail": "Unknown node ID",
  "remediation": "Check the name of the node",
  "error": 3022
}
```
Which is an expected behavior.

2. If we kill the cluster process in a worker node before it's assigned to an agent, the cluster will manage this situation and it will assign another node to this specific agent.


Finally and as I said before, the reported problem in this issue is already fixed in https://github.com/wazuh/wazuh/pull/11598.
Plus, this situation is not possible to be replicated in a real Wazuh environment.

**Closed** 2022-01-24 09:06 UTC
Labels: bug, qa, API
