### ISSUE TITLE
Build Wazuh-manager from source code

### ISSUE THREAD

**Issue by thanvantrong** [wazuh/wazuh#18218] opened 2023-08-03 03:09 UTC
Hi,

I tried to build wazuh-manager version - 4.3.10 from source.
i installed all dependences from documents.
i use 2 command: 
`make deps EXTERNAL_SRC_ONLY=1 TARGET=manager` in **wazuh/src** directory
`sudo ./install` from **wazuh** directory
but i got error like that:
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/2fe61fe5-c65d-4172-b263-a36edc4c61d7)
that told me that could't build python.
`libwazuhext.so: cannot open shared object file: No such file or directory`
`libwazuhext.so` file was found in source code
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/be6d6d2d-5b6a-4c70-98ae-6cd60b836c2e)
i tried with other version - 4.4.5 and the same error.

How can i solve this situation ?

Best Regards,

**Comment by thanvantrong** [comment] 2023-08-08 02:10
Hi, @pereyra-m

I built wazuh-manager in Ubuntu Server 22.04 x64.
Wazuh source code version 4.3.10 and i tried with version 4.4.5, both got the same ERROR.
`make deps EXTERNAL_SRC_ONLY=1 TARGET=manager` is wrong, i fixed it `make deps EXTERNAL_SRC_ONLY=1 TARGET=server` but i can't build this complete with this ERROR.
I read 2 links above.
I want to build Wazuh-manager from source but got this ERROR.
Build with `pre-compiled` is no ERROR.

Best Regards,

**Comment by pereyra-m** [comment] 2023-08-09 01:51
Hello again @thanvantrong !

Please try without enabling the `EXTERNAL_SRC_ONLY` flag and share the output message

```
make -C src clean
make -C src clean-deps
make -C deps EXTERNAL_SRC_ONLY=0 TARGET=server
sudo ./install
```

Also, what do you mean with "no ERROR"?

**Comment by thanvantrong** [comment] 2023-08-09 02:11
Hi, @pereyra-m

Following above commands, here is end of output when i build wazuh-manager
![ảnh](https://github.com/wazuh/wazuh/assets/82009148/0bd514a4-4bcc-4207-b015-cb43fcfe78ee)
Successfully when using `pre-compiled` packages
'no  ERROR' mean that wazuh-manager is built successfully with `pre-compiled` packages.
Anyway, how can i build wazuh-manager with option `EXTERNAL_SRC_ONLY=1` successfully ?

Best Regards,

**Comment by pereyra-m** [comment] 2023-08-09 15:13
Thank you @thanvantrong ! Now I understand.

The pre-compiled external dependencies work but you need to build them from sources. Is it required for changing the version of a library?

When you call the script `install.sh`, all the external dependencies are compiled and merged in the library `libwazuhext.so` and then Wazuh is installed.
The error message you've shown suggests that this compilation fails, so the library isn't generated and the installation can't continue. 

We'll try first to build the manager without installing it, to find out where the compilation is failing:

```bash
make -C src clean
make -C src clean-deps
make -C src deps EXTERNAL_SRC_ONLY=1 TARGET=server
make -C src build TARGET=server INSTALLDIR=/var/ossec
```

Please share the output of the last command.
Regards.

**Comment by thanvantrong** [comment] 2023-08-09 17:21
Hi, @pereyra-m

Here is file that contains all output of last above command.
[output.txt](https://drive.google.com/file/d/1uDN7jkeDYy5wE4MRPvNnFraKgFlOM8cw/view?usp=sharing)

Best Regards,

**Comment by pereyra-m** [comment] 2023-08-10 00:44
Hi @thanvantrong !

Thank you for sharing the results of the test.
The compilation ends successfully and I see no error messages in `output.txt`.
This means that in your system
- The manager can be compiled and installed successfully with the pre-compiled external libraries
- The manager can be compiled successfully but fails to be installed if the external libraries are built from sources

This behavior isn't reasonable, because if the installation script works , the way `libwazuhext.so` is built shouldn't be a problem.
I also was unable to reproduce this behavior in Ubuntu 22.04 x64bits.
I'll try with Ubuntu server, but first make a last test: we'll run all the commands within the same folder to discard a path issue

**Test 1**

```bash
cd wazuh/src
make clean
make clean-deps
make deps EXTERNAL_SRC_ONLY=1 TARGET=server
make build TARGET=server INSTALLDIR=/var/ossec
../install.sh
```

**Test 2**

```bash
cd wazuh/
make -C src/ clean
make -C src/ clean-deps
make -C src/ deps EXTERNAL_SRC_ONLY=1 TARGET=server
make -C src/ build TARGET=server INSTALLDIR=/var/ossec
./install.sh
```

Please tell me if one of this options worked.

Regards.

**Comment by thanvantrong** [comment] 2023-08-10 03:51
Hi, @pereyra-m

I tried 2 test and not work.
The same ERROR with 2 test.

Best Regards,

**Comment by Dwordcito** [comment] 2023-08-21 04:41
Thank you for being part of the community, we closed the issue due to inactivity, in case you return please reopen the issue!

**Closed by Dwordcito** 2023-08-21 04:41 UTC
Labels: reporter/community
