### ISSUE TITLE
Amazon Cloudtrail integration error showing data in graphs (Dashboard)

### ISSUE THREAD

**Issue by Leoquicenoz** [wazuh/wazuh#19784] opened 2023-10-20 16:53 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
|4.7.0-Alpha1	|Manager|[Amazon Machine Images (AMI)](https://documentation-dev.wazuh.com/v4.7.0-alpha1/deployment-options/amazon-machine-images/amazon-machine-images.html)|[Amazon Machine Images (AMI)](https://documentation-dev.wazuh.com/v4.7.0-alpha1/deployment-options/amazon-machine-images/amazon-machine-images.html)||

### Description

During E2E testing on #19661, integration with Amazon Cloudtrail It was evidenced that in the dashboard, in the Amazon AWS section there are two graphs that do not show data and apparently this is an error (Accounts and Regions), in the following graph you can see this irregular behavior:

![image](https://github.com/wazuh/wazuh/assets/106568370/5e7761dc-ffae-4dde-ab69-c3b6232d2e58)

This issue is created with the objective of informing about this, although this error has been occurring since previous versions (as can be seen in this issue: [Release 4.6.0 - Alpha 1 - E2E UX tests - Amazon Cloudtrail integration](https://github.com/wazuh/wazuh/issues/18830)

**Comment by Selutario** [comment] 2023-11-08 10:03
The problem was fixed in this PR for 4.4:
- https://github.com/wazuh/wazuh/pull/4459

However, the content that is downloaded while installing Wazuh (either step by step or using the installation assistant) [here](https://documentation.wazuh.com/current/installation-guide/wazuh-server/step-by-step.html#configuring-filebeat):
![image](https://github.com/wazuh/wazuh/assets/23361101/9a790425-73b9-43ea-aea5-9ed15a8c70e9)


does not contain the `data.aws.region`, `data.aws.accountId` and `data.aws.service.action.networkConnectionAction.remoteIpDetails.ipAddressV4` fields  included in the PR:

![image](https://github.com/wazuh/wazuh/assets/23361101/4560c128-7f23-4f85-b0c9-dd6daa4461cc)

We need to know what content is being used to create the `wazuh-filebeat.tar.gz` since it must be updated with those fixes.

**Comment by davidjiglesias** [comment] 2023-11-09 08:50
The QA team is in charge of uploading the latest Filebeat version in the publication. I have updated the necessary issues and templates so this does not happen again.

**Comment by damarisg** [comment] 2023-11-09 19:09
First, I tried to reproduce the error on Debian 12 and CentOS 8. The task is locked until I have access. ([Issue](https://github.com/wazuh/internal-devel-requests/issues/465))

Remember that Wazuh does not recommend Debian 12 for install by the Quickstar method.

**Closed** 2023-11-13 07:35 UTC
Labels: type/bug, level/task
