### ISSUE TITLE
Phase1 decoder problem with year

### ISSUE THREAD

**Issue by MattiasWass** [wazuh/wazuh#185] opened 2017-09-05 12:41 UTC
when using syslog and HP v1920-24G it decodes year as hostname, if manually remove year it will be decoded right 

Jan 28 06:43:28 2017 HOSTNAME-SW01 %%10WEB/4/WEBOPT_LOGIN_FAIL(l): admin failed to log in from 172.16.200.234

**Phase 1: Completed pre-decoding.
       full event: 'Jan 28 06:43:28 2017 HOSTNAME-SW01 %%10WEB/4/WEBOPT_LOGIN_FAIL(l): admin failed to log in from xxx.xxx.xxx.xxx'
       hostname: '2017'
       program_name: '(null)'
       log: 'HOSTNAME-SW01 %%10WEB/4/WEBOPT_LOGIN_FAIL(l): admin failed to log in from xxx.xxx.xxx.xxx'

**Phase 2: Completed decoding.
       No decoder matched.

**Phase 3: Completed filtering (rules).
       Rule id: '1002'
       Level: '2'
       Description: 'Unknown problem somewhere in the system.'

**Comment by vikman90** [comment] 2017-09-05 13:35
Hi @MattiasWass,

following the Syslog protocol specified at [RFC 3164](https://www.ietf.org/rfc/rfc3164.txt) (page 9):

>  The TIMESTAMP field is the local time and is in the format of "Mmm dd
   hh:mm:ss" (without the quote marks)

I wonder why your syslog is inserting the year. Following this protocol, the Wazuh predecoder interprets the field after the timestamp as the hostname. Maybe there is a configuration that allows to change the timestamp pattern.

Please tell us if you can change that configuration. Currently there is no option to disable the predecoding since that may make decoders not to work properly.

Best regards.

**Comment by MattiasWass** [comment] 2017-09-05 13:48
Hi @vikman90.
i have gone thru the switch config and tried to find any way to change or atleast remove the year from it. 
but no luck there. it is also present in the switch GUI under logging. the same problem does also exist for the v1910,

//Mattias

**Comment by cleberb** [comment] 2019-01-09 19:57
Solution:

<pre>
[sysname] info-center timestamp loghost no-year-date
</pre>

But I wish the wazuh had a more robust pre-decoder to identify multiple timestamps. Even by setting the **"iso"** option of the comware (example: 2019-01-09T15: 39: 31), it is not possible to identify the timestamp.

**Comment by vikman90** [comment] 2019-01-12 16:18
Hi @cleberb,

I agree. The pre-decoding stage is currently a static decoder written in C, we can't change or disable it.

It would be better improving the regex engine and allowing the user to define custom pre-decoders.

That's not an easy task but let me mark this issue as enhancement so we will discuss it with the team.

Thanks for your feedback.
Regards.

**Comment by jonnycastaway** [comment] 2023-02-20 15:27
So, hi everyone,
i have the same problem with HPE 1950 Switches. But the Solution "no-year-date" is not possible anymore.
There is no such point in the WebUi nor in the CLI.
I think i have to rewrite an decoder. Is this right?

**Comment by jonnycastaway** [comment] 2023-02-23 06:29
Puh, no one can help?
I readed the whole decoder section in documentation but realize that it's not a hel.
The problem is one step before and i have no idea where to start.

**Comment by jonnycastaway** [comment] 2023-02-23 13:49
Ok, after many searching i finally found the way to switch HPE 1950 also to no-year-date.
And heres the way for future searches:

Activate Telnet or SSH via WebUI
Logging in with Telnet/SSH
Switch to Extended CLI Mode
	xtd-cli-mode <Enter>
	y <Enter>
        Find the password here ;-) : [https://networkguy.de/enabling-advanced-cli-on-hp-v1950-switches/](url)
Switch to System-View
	system-view <Enter>
Switch syslog timestamp
	info-center timestamp loghost no-year-date <Enter>
Save config
	save <Enter>
	y <Enter>
	<Enter>
	y <Enter>

Exit CLI with exit (maybe multiple times)
Deactivate Telnet or SSH in WebUI

**Comment by fabitom** [comment] 2024-12-05 20:30
Hi, any progress on pre-decoding timestamp ? I've other device with "Dec 04 11:23:12 2024 hostname "

**Comment by vikman90** [comment] 2024-12-13 10:04
@fabitom this will be fixed in the new Engine (5.0):

- https://github.com/wazuh/wazuh/issues/23577

Best regards.

**Closed by vikman90** 2024-12-13 10:04 UTC
Labels: type/enhancement
