### ISSUE TITLE
Bug reading FIM configuration using follow symbolic links.

### ISSUE THREAD

**Issue by bah07** [wazuh/wazuh#6320] opened 2020-10-19 08:10 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.13 | FIM | Agent | Any | Any |

We have found an error that caused that after the first check of the status of the monitored symbolic links the entries corresponding to the directories `/usr/bin` and `/usr/sbin` were eliminated, content that should remain in DB since it was explicitly monitored with the directories `/usr/bin` and `/usr/sbin`, because of a bad reading of the configuration of the links `/bin` and `/sbin` in the default configuration:

```xml
    <!-- Directories to check  (perform all possible verifications) -->
    <directories>/etc,/usr/bin,/usr/sbin</directories>
    <directories>/bin,/sbin,/boot</directories>
```

With:
- `/bin -> /usr/bin`
- `/sbin -> /usr/sbin`

**Comment by Molter73** [comment] 2020-11-10 14:39
It looks like this issue comes from an inconsistency on how we read the configuration and how the symbolic link checker thread updates them.

When a symbolic link is found in the configuration, `dump_syscheck_entry` correctly puts the path to the link in `syscheck.dir[i]` and adds the hardlink it points to into `syscheck.symbolic_links[i]`. After a given period of time, `symlink_checker_thread` sweeps through the configured directories and incorrectly sets `syscheck.dir[i]` to the value of the hardlink. This causes a couple of problems if a directory and a symbolic link to it are configured:
- The information retrieved from the initial scan and the one we get after `symlink_checker_thread` runs is different, even if nothing in the system has changed.
- If the configured symbolic link comes after the hardlink directory, modifying the link to a different directory will cause the configured directory to not be present anymore.

In order to fix this problem, we should review how we handle symbolic links and make sure entries in `syscheck.dir` always reflect those configured by the user. After that, we should run tests on all three operation modes with symbolic links to make sure we are not missing logic to check some events against `syscheck.symbolic_links` for specific configurations.

As a side note for future implementations, we should consider grouping together fields that refer to directories configurations in a manner similar to how we handle registers, it would look similar to this:
```c
typedef struct directory {
    char *path;
    int opts;
    int diff_size_limit;
    char *symbolic_links;
    OSMatch *filerestrict;
    int recursion_level;
    char *tag;
} directory;
```

We can then have a single array of directories, instead of multiple arrays spread across `syscheck_config`. Once we have that working, we should look into creating a separate array with a similar struct for symbolic links, this would allow us to have specific logic for handling them separate from directories.

**Comment by jesusjimsa** [comment] 2020-11-13 16:11
I have been working on a refactor of all the code related to symbolic links to make sure `syscheck.dir` is never overwritten, it will modify `syscheck.symbolic_links` instead. `syscheck.dir` should only contain what the user has configured in the `directories` tag.
I have it almost ready, I only need to test it to check that it is still working correctly.

**Comment by jesusjimsa** [comment] 2020-11-16 16:04
While fixing [this memory leak](https://github.com/wazuh/wazuh/pull/6613#issuecomment-728132868) I have found that some log messages where not being printed correctly. I have now fixed the memory leak but I am going to fix the log messages before pushing a new commit.
After fixing these messages, I will check which integration tests I have to modify to adapt them for the new changes and will open an issue describing the changes that need to be done in the integration tests.

**Comment by jesusjimsa** [comment] 2020-11-17 15:16
I launched yesterday the integration tests and they run in Windows with no fails. There were some failed tests on UNIX systems:
* `test_delete_symlink`
* `test_delete_target`

These failures were caused by a `syscheck.dir` I missed when replacing them with `syscheck.symbolic_links`. I have fixed this now and the failing tests are now passing. I will generate new packages and run integration tests again to confirm everything is working.
While the integration tests run, I will start fixing the unit tests.

**Closed** 2020-11-19 15:54 UTC
Labels: bug, core/fim, platform/unix
