### ISSUE TITLE
Alerts not showing up consistently

### ISSUE THREAD

**Issue by njmulsqb** [wazuh/wazuh#17758] opened 2023-07-05 12:10 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.3 | Wazuh manager | Manager | Packages/Sources | Ubuntu |

The issue that I am facing with wazuh is that for past few days, alerts are not consistent, randomly for some hours all the agents stop giving events or maybe manager stops processing event. The image below shows no events at all between 9 to 16. This is concerning. What could be the issue?

<img width="860" alt="image" src="https://github.com/wazuh/wazuh/assets/47940898/035dece1-c381-4ace-b5ae-1c325b0218da">

**Comment by njmulsqb** [comment] 2023-07-06 09:36
Hi @pereyra-m,

Now the manager is not showing any alerts for last 24 hours:
<img width="1440" alt="image" src="https://github.com/wazuh/wazuh/assets/47940898/05e8cfe1-3daa-4de9-af75-2025872e6eb8">


Thank you for your prompt response, I have gathered some information which is as follows:
`ossec.log` file from one of the agents: 

- `ossec-01.log` : https://paste.debian.net/1285083/
- `ossec-02.log`: https://paste.debian.net/1285084/
- `ossec-03.log`: https://paste.debian.net/1285085/
- `ossec-04.log`: https://paste.debian.net/1285086/
- `ossec-05.log`: https://paste.debian.net/1285087/

`ossec.log` from manager: https://pastebin.com/FhzUGeWW
`alerts.json` : https://drive.google.com/file/d/1EZ1TDGfG3zVK5nhUAYKtI1iTEm1QG2Zr/view?usp=sharing

This is a single node installation, installed on a Ubuntu server by following the instruction in official docs.

For future reference, is there anyway to configure email notifications if the alerts stops being collected from the agents?

**Comment by pereyra-m** [comment] 2023-07-06 14:06
Hello again @njmulsqb !

Thank you for all the information provided.
I don't see any communication or reporting issues between the agents and the manager.
Filebeat seems to be working properly and the `alerts.json` file contains alerts (I can only see the last event at `2023-07-06T00:27:48.874+0000` but you say that we should be seeing alerts).

So this must be an index problem. 
Run the following query in your Dev Tools console to get more information 

```
GET _cluster/health
```

The most probable cause is running out of available shards. If this is the case, no more alerts will be indexed. 
You can remove old indices to free shards or increase the number of shards per node, but the best solution is to implement an index policy as you can see in

https://wazuh.com/blog/wazuh-index-management/

After this problem is fixed, you'll be able to reinject the alerts with a script
https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/

Regards.

**Comment by pereyra-m** [comment] 2023-07-06 15:06
Maybe you are using the API console from Wazuh, that's why you got an error.
Use this one instead

![2023-07-06_12-03](https://github.com/wazuh/wazuh/assets/65046601/b635da72-8c2b-4e92-ba0a-01650a89de96)

![2023-07-06_12-03_1](https://github.com/wazuh/wazuh/assets/65046601/6453e19a-e539-4a86-9eee-af20fab5f373)

**Comment by njmulsqb** [comment] 2023-07-06 15:08
```

{
  "cluster_name": "wazuh-cluster",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "discovered_master": true,
  "discovered_cluster_manager": true,
  "active_primary_shards": 125,
  "active_shards": 125,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

**Comment by njmulsqb** [comment] 2023-07-06 15:17
Everything seems to be alright, but I cant see any alerts at all :(
<img width="1432" alt="image" src="https://github.com/wazuh/wazuh/assets/47940898/80016a58-e6b7-4310-bdf3-34427112e0ef">

**Comment by pereyra-m** [comment] 2023-07-06 18:10
Hi again @njmulsqb.

It's true that we don't see a high number of shards.
Maybe we can find an error message in other log files, please share the output of the following commands
- `cat /var/log/wazuh-indexer/wazuh-cluster.log | grep -i -E "error|warn"`
- `cat /var/log/filebeat/filebeat | grep -i -E "error|warn"`
- `journalctl -u wazuh-dashboard`
- `cat /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log | grep -i -E "error|warn"`

**Comment by njmulsqb** [comment] 2023-07-06 18:47
Finally, we have got some errors, phew xD:

- `cat /var/log/wazuh-indexer/wazuh-cluster.log | grep -i -E "error|warn"` : https://paste.debian.net/1285136/
- `cat /var/log/filebeat/filebeat | grep -i -E "error|warn"` :  This file contains 7000+ entries of  line **2023-07-06T18:11:56.267Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:180	failed to publish events: temporary bulk send failure**
- `journalctl -u wazuh-dashboard` : https://paste.debian.net/1285143/
- `cat /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log | grep -i -E "error|warn"` : https://paste.debian.net/1285144/

Seems like disk space issues,
```
root@wazuhsecurityengine:/home/muzzammil# df -h -T
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       29G   28G  1.1G  97% /
devtmpfs       devtmpfs   16G     0   16G   0% /dev
tmpfs          tmpfs      16G  928K   16G   1% /dev/shm
tmpfs          tmpfs     3.2G  1.1M  3.2G   1% /run
tmpfs          tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs          tmpfs      16G     0   16G   0% /sys/fs/cgroup
/dev/sdb15     vfat      105M  6.1M   99M   6% /boot/efi
/dev/loop2     squashfs   54M   54M     0 100% /snap/snapd/19361
/dev/loop4     squashfs   92M   92M     0 100% /snap/lxd/24061
/dev/loop5     squashfs   54M   54M     0 100% /snap/snapd/19457
/dev/loop3     squashfs   64M   64M     0 100% /snap/core20/1950
/dev/loop0     squashfs   64M   64M     0 100% /snap/core20/1974
tmpfs          tmpfs     3.2G     0  3.2G   0% /run/user/1000
```

Could this be the reason? Doesnt Wazuh alert about disk space issues? How can I calculate the required disk space? I only have 7 agents running and it has eaten up the memory.

**Comment by pereyra-m** [comment] 2023-07-06 19:47
I think that this could be the reason.

> Could this be the reason? Doesnt Wazuh alert about disk space issues? How can I calculate the required disk space? I only have 7 agents running and it has eaten up the memory.

You have a disk space calculator on the website, check the [Calculate the hot storage you need](https://wazuh.com/cloud/#pricing) to have an estimation.
Sometimes few agents generate a lot of EPS (events per second), and it changes a lot according to the OS, the configuration, etc.

You can configure a disk space alert, see
https://documentation.wazuh.com/current/user-manual/capabilities/command-monitoring/command-configuration.html#disk-space-utilization

> /var/ossec/var/run/wazuh-analysisd.state shows events dropped as 0 which is something contradictory to above hypothesis.

This is just a reference and it's related to CPU and memory.  
A host without available space can fail at any time in many unpredictable ways.

Consider increasing your storage capacity according to your alerts retention policy and index management policy (https://wazuh.com/blog/wazuh-index-management). Also, remember that the manager rotates the logs but doesn't remove them, see this section for more details
https://documentation.wazuh.com/4.4/getting-started/architecture.html#archival-data-storage

**Comment by Dwordcito** [comment] 2023-07-17 02:43
It looks like we were able to find the root cause analysis and it's foreign to the product, more of a space issue in the environment.

Thank you very much for your report!

**Closed by Dwordcito** 2023-07-17 02:43 UTC
Labels: reporter/community

**Comment by njmulsqb** [comment] 2023-08-16 04:57
Hi @pereyra-m 

I increased the storage and also moved Wazuh logs to a separate 1TB disk, it worked for some while but again Wazuh has stopped working, here are some of the logs:
`cat /var/log/wazuh-indexer/wazuh-cluster.log | grep -i -E "error|warn"`: https://paste.debian.net/1289109/
`cat /var/log/filebeat/filebeat | grep -i -E "error|warn"`:https://paste.debian.net/1289110/
`journalctl -u wazuh-dashboard `:https://paste.debian.net/1289111/
`cat /usr/share/wazuh-dashboard/data/wazuh/logs/wazuhapp.log | grep -i -E "error|warn"`: {"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:15:00.751Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:15:00.751Z","level":"info","location":"Cron-scheduler"}
{"date":"2023-08-15T14:15:00.773Z","level":"error","location":"monitoring:createIndex","message":"Could not create wazuh-monitoring-2023.33w index on elasticsearch due to index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];"}
{"date":"2023-08-15T14:15:00.774Z","level":"error","location":"monitoring:insertMonitoringDataElasticsearch","message":"index_not_found_exception: [index_not_found_exception] Reason: no such index [wazuh-monitoring-2023.33w]"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:20:01.265Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:20:01.266Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:25:00.228Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:25:00.229Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:30:00.449Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:30:00.450Z","level":"info","location":"Cron-scheduler"}
{"date":"2023-08-15T14:30:00.475Z","level":"error","location":"monitoring:createIndex","message":"Could not create wazuh-monitoring-2023.33w index on elasticsearch due to index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];"}
{"date":"2023-08-15T14:30:00.476Z","level":"error","location":"monitoring:insertMonitoringDataElasticsearch","message":"index_not_found_exception: [index_not_found_exception] Reason: no such index [wazuh-monitoring-2023.33w]"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:35:00.659Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:35:00.660Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:40:01.574Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:40:01.575Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:45:00.075Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:45:00.075Z","level":"info","location":"Cron-scheduler"}
{"date":"2023-08-15T14:45:00.096Z","level":"error","location":"monitoring:createIndex","message":"Could not create wazuh-monitoring-2023.33w index on elasticsearch due to index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];"}
{"date":"2023-08-15T14:45:00.097Z","level":"error","location":"monitoring:insertMonitoringDataElasticsearch","message":"index_not_found_exception: [index_not_found_exception] Reason: no such index [wazuh-monitoring-2023.33w]"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:50:00.302Z","level":"info","location":"Cron-scheduler"}
{"data":{"message":"index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];","stack":"ResponseError: index_create_block_exception: [index_create_block_exception] Reason: blocked by: [FORBIDDEN/10/cluster create-index blocked (api)];\n    at onBody (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:374:23)\n    at IncomingMessage.onEnd (/usr/share/wazuh-dashboard/node_modules/@opensearch-project/opensearch/lib/Transport.js:293:11)\n    at IncomingMessage.emit (events.js:412:35)\n    at IncomingMessage.emit (domain.js:475:12)\n    at endReadableNT (internal/streams/readable.js:1333:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21)"},"date":"2023-08-15T14:50:00.302Z","level":"info","location":"Cron-scheduler"}
{"data":{"detail":"Cluster is not running, it might be disabled in `WAZUH_HOME/etc/ossec.conf`","error":3013,"remediation":"Please, visit the official documentation (https://documentation.wazuh.com/4.5/user-manual/configuring-cluster/index.html) to get more information about how to configure a cluster","title":"Bad Request"},"date":"2023-08-15T15:09:26.319Z","level":"error","location":"wazuh-api:makeRequest"}

Logs seem to refer to cluster at many places, but this is a single node installation

**Comment by aeroboss13** [comment] 2024-11-01 08:17
> Hi @njmulsqb !
> 
> I see that @jesuslinares is working on this at https://wazuh.slack.com/archives/C0A933R8E/p1692190128372309.
> 
> Regards.

Hi guys! I faced the same problem... 17 agents are connected that supplied events perfectly, but since Oct 30, 2024 @ 02:02:16.644 I don't receive any information in the wazuh
![Снимок экрана 2024-11-01 в 11 15 12](https://github.com/user-attachments/assets/d9bc46e7-4f6e-4966-b7d1-4740f7cb9743)
![Снимок экрана 2024-11-01 в 11 17 04](https://github.com/user-attachments/assets/4689fa09-3ccd-4d29-93d6-f436b477a713)
 dashboard, while in alert.json I receive security events, and my integration with alerts in telegram also works
