### ISSUE TITLE
SCA command gets an extra EMPTY_LINE when running commands using c:

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh#12347] opened 2022-02-17 10:40 UTC
|Wazuh version| Component | Action type |
|---| --- | --- |
| 4.2.5+ | SCA | Error |

# Affected Platforms

By now, we have reproduced the issue on these platforms: 

- HP-UX system - HP-UX sovmh317 B.11.31 U ia64 1870146614 unlimited-user license
- CentOS 7 with NGINX - Nginx version: nginx/1.20.1
- macOS Big Sur
- Red Hat Enterprise Linux 9
- Microsoft Windows Server
- Microsoft Windows Desktop
- Debian Linux 
- Ubuntu Linux

# Problem description

```EMPTY_LINE``` is part of the return values in the SCA results to check when running a command line with the ```c``` option.

Sample rule - ``` 'c:ls /Users/jizquierdo/scatest/  -> r:^$' ```

SCA seems to get an extra **EMPTY_LINE** item in the output when running commands despite whether the command output is empty or not. This **EMPTY_LINE** is returned and tested against the rule match criteria, which may cause a wrong succeeded or failed match.

A user may build a rule without taking this **EMPTY_LINE** into account, causing the rule to behave unexpectedly.

```DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 1```

Note: ```1 - success, 0 - failure```

# Test for demonstrated success and failure scenarios for the same rule.

## Test description and configuration
- Test success criteria - The defined ```<folder>``` must be empty. 
- Console command - ```ls <folder>```
- Rule  - ``` 'c:ls /Users/jizquierdo/scatest/  -> r:^$' ```
- Sample A - The command output is empty as the folder is empty. expected to succeed.
- Sample B - Two new folders are created in ```<folder>``` so the command output is not empty and shows two results. Expected to fail.

### Command and  output from console:

```
# ls /Users/jizquierdo/scatest/
#
```
### SCA rule and modulesd DEBUG output

rule 
```
'c:ls /Users/jizquierdo/scatest/  -> r:^$'

```

output

note: when debug lines show ```-> 0``` means failure, and ```-> 1```means success

```
2022/06/11 10:43:15 sca[10332] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:ls /Users/jizquierdo/scatest/  -> r:^$'
2022/06/11 10:43:15 sca[10332] wm_sca.c:1128 at wm_sca_do_scan(): DEBUG: Running command: 'ls /Users/jizquierdo/scatest/ '
2022/06/11 10:43:15 sca[10332] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'ls /Users/jizquierdo/scatest/ ', and testing output with pattern 'r:^$'
2022/06/11 10:43:15 sca[10332] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'ls /Users/jizquierdo/scatest/ ' returned code 0
2022/06/11 10:43:15 sca[10332] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 1
2022/06/11 10:43:15 sca[10332] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(EMPTY_LINE) -> 1
2022/06/11 10:43:15 sca[10332] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:^$)(ls /Users/jizquierdo/scatest/ ) -> 1
2022/06/11 10:43:15 sca[10332] wm_sca.c:1131 at wm_sca_do_scan(): DEBUG: Command output matched.
2022/06/11 10:43:15 sca[10332] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:ls /Users/jizquierdo/scatest/  -> r:^$': 1
2022/06/11 10:43:15 sca[10332] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 18000 'Verify all Apple provided software is current.' -> 1 
```

- Sample Result: ```Pass```. Expected: ```Pass```

### Explanation

This test works fine, the console command provides no item, and SCA uses the EMPTY_LINE as the single and only command output. Again, the rule is looking for an output item without no value, so this time, the rule works.

### Command and  output from console:

```
# ls /Users/jizquierdo/scatest/
folder-a        folder-b
#
```
### SCA rule and modulesd DEBUG output

rule 
```
'c:ls /Users/jizquierdo/scatest/  -> r:^$'

```

output

note: when debug lines show ```-> 0``` means failure, and ```-> 1```means success

```
2022/06/11 11:35:28 sca[12403] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:ls /Users/jizquierdo/scatest/  -> r:^$'
2022/06/11 11:35:28 sca[12403] wm_sca.c:1128 at wm_sca_do_scan(): DEBUG: Running command: 'ls /Users/jizquierdo/scatest/ '
2022/06/11 11:35:28 sca[12403] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'ls /Users/jizquierdo/scatest/ ', and testing output with pattern 'r:^$'
2022/06/11 11:35:28 sca[12403] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'ls /Users/jizquierdo/scatest/ ' returned code 0
2022/06/11 11:35:28 sca[12403] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(folder-a) -> 0
2022/06/11 11:35:28 sca[12403] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(folder-a) -> 0
2022/06/11 11:35:28 sca[12403] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(folder-b) -> 0
2022/06/11 11:35:28 sca[12403] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(folder-b) -> 0
2022/06/11 11:35:28 sca[12403] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 1
2022/06/11 11:35:28 sca[12403] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(EMPTY_LINE) -> 1
2022/06/11 11:35:28 sca[12403] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:^$)(ls /Users/jizquierdo/scatest/ ) -> 1
2022/06/11 11:35:28 sca[12403] wm_sca.c:1131 at wm_sca_do_scan(): DEBUG: Command output matched.
2022/06/11 11:35:28 sca[12403] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:ls /Users/jizquierdo/scatest/  -> r:^$': 1
```
- Sample B Result: ```Pass```. Expected: ```Failed```

## Explanation

This test doesn't work, the result from running the console command shows two items, but SCA has three results, both folder names, and the EMPTY_LINE. The rule matches again, making the test succeed because of this last EMPTY_LINE item. The output of DEBUG lines shows the *folder-a* and *folder-b* items failing the check, but the EMPTY_LINE matches again.

**Comment by 72nomada** [comment] 2022-06-11 08:57
```
'c:find / \( -nouser -o -nogroup \) -> r:^$'
```

Sample command #1

```
# find / \( -nouser -o -nogroup \)
/opt/java6/demo/jfc/SwingSet2/src/resources/images/toolbar/JList.gif
/usr/share/man/man1m.Z/tuneserver.1m
#
```

SCA output in Debug mode:

```
2022/02/17 03:19:19 sca[8198] wm_sca.c:983 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 21133 'Resolve "unowned" files and directories.'
2022/02/17 03:19:19 sca[8198] wm_sca.c:984 at wm_sca_do_scan(): DEBUG: Rule aggregation strategy for this check is 'all'
2022/02/17 03:19:19 sca[8198] wm_sca.c:985 at wm_sca_do_scan(): DEBUG: Initial rule-aggregator value por this type of rule is '1'
2022/02/17 03:19:19 sca[8198] wm_sca.c:986 at wm_sca_do_scan(): DEBUG: Beginning rules evaluation.
2022/02/17 03:19:19 sca[8198] wm_sca.c:1011 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:find / \( -nouser -o -nogroup \) -> r:^$'
2022/02/17 03:19:19 sca[8198] wm_sca.c:1092 at wm_sca_do_scan(): DEBUG: Running command: 'find / \( -nouser -o -nogroup \)'
2022/02/17 03:19:19 sca[8198] wm_sca.c:1568 at wm_sca_read_command(): DEBUG: Executing command 'find / \( -nouser -o -nogroup \)', and testing output with pattern 'r:^$'
2022/02/17 03:19:22 sca[8198] wm_sca.c:1574 at wm_sca_read_command(): DEBUG: Command 'find / \( -nouser -o -nogroup \)' returned code 0
2022/02/17 03:19:22 sca[8198] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(/opt/java6/demo/jfc/SwingSet2/src/resources/images/toolbar/JList.gif) ->
 0
2022/02/17 03:19:22 sca[8198] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(/opt/java6/demo/jfc/SwingSet2/src/resources/images/toolbar/JList.gi
f) -> 0
2022/02/17 03:19:22 sca[8198] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(/usr/share/man/man1m.Z/tuneserver.1m) -> 0
2022/02/17 03:19:22 sca[8198] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(/usr/share/man/man1m.Z/tuneserver.1m) -> 0
2022/02/17 03:19:22 sca[8198] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 1
2022/02/17 03:19:22 sca[8198] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(EMPTY_LINE) -> 1
2022/02/17 03:19:22 sca[8198] wm_sca.c:1630 at wm_sca_read_command(): DEBUG: Result for (r:^$)(find / \( -nouser -o -nogroup \)) -> 1
2022/02/17 03:19:22 sca[8198] wm_sca.c:1095 at wm_sca_do_scan(): DEBUG: Command output matched.
2022/02/17 03:19:22 sca[8198] wm_sca.c:1164 at wm_sca_do_scan(): DEBUG: Result for rule 'c:find / \( -nouser -o -nogroup \) -> r:^$': 1
2022/02/17 03:19:22 sca[8198] wm_sca.c:1187 at wm_sca_do_scan(): DEBUG: Result for check id: 21133 'Resolve "unowned" files and directories.' -> 1
```

Sample command #2

```
# ipfstat -io
empty list for ipfilter(out)
pass in on lan0 from any to any
block in proto icmp from any to any
#
```

SCA log 

With HP-UX
```
2022/02/17 03:50:25 sca[9305] wm_sca.c:1574 at wm_sca_read_command(): DEBUG: Command 'ipfstat -io' returned code 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:block in all)(empty list for ipfilter(out)) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:block in all)(empty list for ipfilter(out)) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:block in all)(pass in on lan0 from any to any) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:block in all)(pass in on lan0 from any to any) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:block in all)(block in proto icmp from any to any) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:block in all)(block in proto icmp from any to any) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1840 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:block in all)(EMPTY_LINE) -> 0
2022/02/17 03:50:25 sca[9305] wm_sca.c:1843 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:block in all)(EMPTY_LINE) -> 0
```

With NginX

sample command 
```
nginx -V 2>&1| grep with-http_dav_module
configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'
```

```
2022/03/31 09:10:35 sca[4234] wm_sca.c:986 at wm_sca_do_scan(): DEBUG: Beginning evaluation of check id: 23000 'Ensure HTTP WebDAV module is not installed'
2022/03/31 09:10:35 sca[4234] wm_sca.c:987 at wm_sca_do_scan(): DEBUG: Rule aggregation strategy for this check is 'all'
2022/03/31 09:10:35 sca[4234] wm_sca.c:988 at wm_sca_do_scan(): DEBUG: Initial rule-aggregator value por this type of rule is '1'
2022/03/31 09:10:35 sca[4234] wm_sca.c:989 at wm_sca_do_scan(): DEBUG: Beginning rules evaluation.
2022/03/31 09:10:35 sca[4234] wm_sca.c:1014 at wm_sca_do_scan(): DEBUG: Considering rule: 'c:sh -c "nginx -V 2>&1 | grep \"http_dav_module\""  -> r:^$'
2022/03/31 09:10:35 sca[4234] wm_sca.c:1128 at wm_sca_do_scan(): DEBUG: Running command: 'sh -c "nginx -V 2>&1 | grep \"http_dav_module\"" '
2022/03/31 09:10:35 sca[4234] wm_sca.c:1623 at wm_sca_read_command(): DEBUG: Executing command 'sh -c "nginx -V 2>&1 | grep \"http_dav_module\"" ', and testing output with pattern 'r:^$'
2022/03/31 09:10:35 sca[4234] wm_sca.c:1629 at wm_sca_read_command(): DEBUG: Command 'sh -c "nginx -V 2>&1 | grep \"http_dav_module\"" ' returned code 0
2022/03/31 09:10:35 sca[4234] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E') -> 0
2022/03/31 09:10:35 sca[4234] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(configure arguments: --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-compat --with-debug --with-file-aio --with-google_perftools_module --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_degradation_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_image_filter_module=dynamic --with-http_mp4_module --with-http_perl_module=dynamic --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-http_xslt_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-stream_ssl_preread_module --with-threads --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E') -> 0
>>>>>>> 2022/03/31 09:10:35 sca[4234] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:^$)(EMPTY_LINE) -> 1
>>>>>>> 2022/03/31 09:10:35 sca[4234] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:^$)(EMPTY_LINE) -> 1
>>>>>>> 2022/03/31 09:10:35 sca[4234] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:^$)(sh -c "nginx -V 2>&1 | grep \"http_dav_module\"" ) -> 1
>>>>>>> 2022/03/31 09:10:35 sca[4234] wm_sca.c:1131 at wm_sca_do_scan(): DEBUG: Command output matched.
2022/03/31 09:10:35 sca[4234] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:sh -c "nginx -V 2>&1 | grep \"http_dav_module\""  -> r:^$': 1
2022/03/31 09:10:35 sca[4234] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 23000 'Ensure HTTP WebDAV module is not installed' -> 1
```

**Comment by 72nomada** [comment] 2022-06-13 15:39
same behavior in windows environments 

```
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(Get-ADDefaultDomainPasswordPolicy : The term 'Get-ADDefaultDomainPasswordPolicy' is not recognized as the name of a ) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(Get-ADDefaultDomainPasswordPolicy : The term 'Get-ADDefaultDomainPasswordPolicy' is not recognized as the name of a ) -> 0
2022/06/13 06:52:31 wazuh-agent[1120] syscheck_op.c:853 at process_ace_info(): DEBUG: No information could be extracted from the account linked to the SID. Error: 1789.
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify ) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify ) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(that the path is correct and try again.) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(that the path is correct and try again.) -> 0
2022/06/13 06:52:31 wazuh-agent[1120] syscheck_op.c:853 at process_ace_info(): DEBUG: No information could be extracted from the account linked to the SID. Error: 1789.
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(At line:1 char:1) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(At line:1 char:1) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(+ Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(+ Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(    + CategoryInfo          : ObjectNotFound: (Get-ADDefaultDomainPasswordPolicy:String) [], CommandNotFoundException) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(    + CategoryInfo          : ObjectNotFound: (Get-ADDefaultDomainPasswordPolicy:String) [], CommandNotFoundException) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(    + FullyQualifiedErrorId : CommandNotFoundException) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(    + FullyQualifiedErrorId : CommandNotFoundException) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)( ) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)( ) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1895 at wm_sca_pattern_matches(): DEBUG: Testing minterm (r:ComplexityEnabled\s+: True)(EMPTY_LINE) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1898 at wm_sca_pattern_matches(): DEBUG: Pattern test result: (r:ComplexityEnabled\s+: True)(EMPTY_LINE) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1685 at wm_sca_read_command(): DEBUG: Result for (r:ComplexityEnabled\s+: True)(powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser) -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1218 at wm_sca_do_scan(): DEBUG: Result for rule 'c:powershell Get-ADDefaultDomainPasswordPolicy -Current LoggedOnUser -> r:ComplexityEnabled\s+: True': 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1225 at wm_sca_do_scan(): DEBUG: Breaking from rule aggregator 'all' with found = 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:1241 at wm_sca_do_scan(): DEBUG: Result for check id: 26004 'Ensure 'Password must meet complexity requirements' is set to 'Enabled'' -> 0
2022/06/13 06:52:31 sca[1120] wm_sca.c:479 at wm_sca_read_files(): DEBUG: Calculating hash for scanned results.
2022/06/13 06:52:31 sca[1120] wm_sca.c:2802 at wm_sca_hash_integrity(): DEBUG: Concatenating check results:
2022/06/13 06:52:31 sca[1120] wm_sca.c:2805 at wm_sca_hash_integrity(): DEBUG: ID: 26004; Result: 'failed'
```

**Comment by vikman90** [comment] 2023-11-20 11:12
Hi, I've reproduced this issue.

## Reproduced

### Environment

```
- [dir] /root
 \
  - [dir] test
   \
    - [dir] empty
    - [dir] nonempty
     \
      - [file] one
      - [file] two 
```
### Rules

```yml
  - id: 10001
    title: "ls is empty"
    condition: all
    rules:
      - 'c:ls /root/test/empty -> r:^$'

  - id: 10002
    title: "ls is not empty"
    condition: none
    rules:
      - 'c:ls /root/test/nonempty -> r:^$'
```

### Result

According to the environment and the check titles, **both checks are expected to pass**.

|Check|Expected rule result|Rule result|Check result|
|---|:-:|:-:|:-:|
|`ls` is empty | ✅ |✅ | ✅ |
|`ls` is not empty | ❌ | ✅ | ❌ |

<details><summary>Log</summary>

```
Result for rule 'c:ls /root/test/empty -> r:^$': 1
Result for check id: 10001 'ls is empty' -> 1

Result for rule 'c:ls /root/test/nonempty -> r:^$': 1
Breaking from rule aggregator 'none' with found = 1
Result for check id: 10002 'ls is not empty' -> 0
```
</details>

## Rationale

When we run `ls` on an empty directory, we expect no output. Therefore, if we do `ls` on a non-empty directory, we expect that there will be some output. This works that way, except that **`ls` adds a last newline `\n` at the end of the output.

According to the documentation ([Creating custom SCA policies](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/creating-custom-policies.html)), **SCA runs the regex on each line**. As `ls` and other commands insert the final `\n`, the regex `^$` always matches.

**This is not a bug, and it's normal behavior for many shell tools.**

## Proposed rule

Create a complex shell command to check whether the number of files is exactly zero:

```yml
  - id: 10001
    title: "ls is empty"
    condition: all
    rules:
      - 'c:bash -c "ls /root/test/empty | wc -l" -> r:^0$'

  - id: 10002
    title: "ls is not empty"
    condition: none
    rules:
      - 'c:bash -c "ls /root/test/nonempty | wc -l" -> r:^0$'
```

### Result

According to the environment and the check titles, **both checks are expected to pass**.

|Check|Expected rule result|Rule result|Check result|
|---|:-:|:-:|:-:|
|`ls` is empty | ✅ |✅ | ✅ |
|`ls` is not empty | ❌ | ❌ | ✅ |

## Conclusion

We can close this issue as there is no bug and we don't plan to fix this use case.

**Closed by vikman90** 2023-11-20 11:12 UTC
Labels: type/bug, module/sca, reporter/threatintel, level/task, qa_known
