### ISSUE TITLE
Syscheckd cannot process paths with non-UTF-8 characters

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh#23545] opened 2024-05-21 15:39 UTC
# Description

Hello team, we have detected some problems in syscheck where it is not possible to process some non-UTF-8 characters.
More info related to this problem in this issue:
https://github.com/wazuh/wazuh/issues/23354

We have been able to fix the crashes by conveniently handling the errors, but currently syscheck is not able to generate alerts if the aforementioned invalid characters are found in the paths.

This issue is to make an in-depth analysis of the possible solutions to be able to process these files.

### Reproduce behaviour

```xml
<syscheck>
  <directories realtime="yes" report_changes="yes">/root/test/fim</directories>
</syscheck>
```

**Create a file with non-UTF8 name:**
    ```shell
    touch $(echo -n "Víctor" | iconv -f UTF-8 -t ISO-8859-1)
    ```

This will produce the error log:
```
    > 2024/05/21 10:10:08 wazuh-syscheckd: ERROR: [json.exception.type_error.316] invalid UTF-8 byte at index 17: 0x63
```

The problem is specifically in the nlohmann json dump function. We need to find out if it is possible to store those characters or look for an alternative solution such as converting them to UTF-8.

**Comment by juljar** [comment] 2024-07-17 10:45
Hello, is there any update on the issue?

We are using FIM to monitor certain directories and, after the update to 4.8.0, we're getting hundreds of warnings every day. Any filepath containing the letters "ä", "ö", or "ü" (German language) won't be monitored, which defeats the purpose of FIM in our case.

**Comment by akraegelius** [comment] 2024-08-20 10:31
The same here... Wazuh Agent 4.8.1. and thousand entries like

2024/08/20 12:29:48 wazuh-agent: WARNING: (6955): Ignoring file 'd:\daten\12 finanzen und controlling\fibu\bank\zahlungen\2023\Überweisung lohn.xml' due to unsupported name (non-UTF8).

**Comment by akraegelius** [comment] 2024-09-10 14:25
I can confirm that the same behaviour happens with 4.9
The agent starts scanning, crashes and starts to scan again, and agan and again

**Comment by dankra001** [comment] 2024-09-16 19:43
Hello.
I’ve updated to the latest version, but the agent logs show:
WARNING: (6955): Ignoring file due to unsupported name (non-UTF8).
Could you provide guidance on this issue or verify if the fix fully addresses the problem for Windows systems?

**Comment by MROSSFTEK** [comment] 2024-09-24 17:00
i agree with dankra001.. im running 4.9, latest revision and still having that same issue on windows agents.

**Comment by vikman90** [comment] 2024-10-15 13:56
Duplicate issue:
- https://github.com/wazuh/wazuh-agent/issues/216

**Comment by MarcelKemp** [comment] 2024-12-12 11:52
Fixed in next issue:
- https://github.com/wazuh/wazuh/issues/25967
  - PR: https://github.com/wazuh/wazuh/pull/26289

**Closed by MarcelKemp** 2024-12-12 11:52 UTC
Labels: type/bug, module/fim, level/task
