### ISSUE TITLE
Wrong agent version on Windows Server machines

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh#12083] opened 2022-02-03 10:19 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| >v3.9.1 | Agent | NA | Windows Server |

## Description

It has been reported that Windows Server agents store their agent version as a merge of the OS version and the actual Wazuh version. For instance (using the `GET /overview/agents` API endpoint):

![image](https://user-images.githubusercontent.com/37274979/152318400-5ec77a87-ed2e-4190-a208-e61a080c4419.png)

As it can be seen, those agent version should be `Wazuh v4.2.5` and thus counted in the same group as the rest.

This issue has also been detected on `Wazuh v3.9.1` agents (using `GET /agents` API endpoint):

```json
{
    "os": {
      "build": "17763",
      "major": "10",
      "minor": "0",
      "name": "Microsoft Windows Server 2019 Standard",
      "platform": "windows",
      "uname": "Microsoft Windows Server 2019 Standard",
      "version": "10.0.17763"
    },
    "mergedSum": "27a02e2789aaffbee5604a5c3f74c946",
    "configSum": "095817d8a77c917e216aa74ebc1bb93a",
    "status": "active",
    "id": "83882",
    "ip": "192.168.3.4",
    "registerIP": "any",
    "name": "SW730VTAQS007",
    "group": [
      "WINDOWS",
      "18431"
    ],
    "manager": "sl73wazuapq",
    "node_name": "sl73wazuapq",
    "lastKeepAlive": "2021-12-06T15:44:18",
    "dateAdd": "2021-10-08T08:42:05",
    "version": "Wazuh v3.9.1Microsoft Windows Server 2019 Standard [Ver: 10.0.17763] - Wazuh v3.9.1"
  },
```

These endpoints retrieve the agent version from the `global.db`.

**Comment by vikman90** [comment] 2022-02-03 11:46
@vicferpoy thanks for reporting this issue.

As we have chatted, this problem seems to be due to any particularity in the agent platform.

### Agent 4.2.5 on Windows 11 Desktop

```json
{
  "data": {
    "affected_items": [
      {
        "os": {
          "build": "22000",
          "major": "10",
          "minor": "0",
          "name": "Microsoft Windows 10 Pro",
          "platform": "windows",
          "uname": "Microsoft Windows 10 Pro",
          "version": "10.0.22000"
        },
        "name": "Rocky",
        "version": "Wazuh v4.2.5",
        "ip": "192.168.1.49",
        "manager": "Rocket",
        "status": "active",
        "dateAdd": "2022-02-03T09:25:00Z",
        "registerIP": "any",
        "id": "001",
        "group": [
          "default"
        ],
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "lastKeepAlive": "2022-02-03T09:25:42Z",
        "mergedSum": "2c45c95db2954d2c7d0ea533f09e81a5",
        "node_name": "node01"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

### Windows Server 2019 Desktop

```json
{
  "data": {
    "affected_items": [
      {
        "os": {
          "build": "17763",
          "major": "10",
          "minor": "0",
          "name": "Microsoft Windows Server 2019 Standard Evaluation",
          "platform": "windows",
          "uname": "Microsoft Windows Server 2019 Standard Evaluation",
          "version": "10.0.17763"
        },
        "name": "WIN-1PS2F97D2I6",
        "version": "Wazuh v4.2.5",
        "ip": "192.168.182.130",
        "manager": "Rocket",
        "status": "active",
        "dateAdd": "2022-02-03T10:02:37Z",
        "registerIP": "any",
        "id": "002",
        "group": [
          "default"
        ],
        "lastKeepAlive": "2022-02-03T10:02:57Z",
        "mergedSum": "x",
        "node_name": "node01"
      }
    ],
    "total_affected_items": 1,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

## Next step

I think that the issue is in the agent's notify message. Either the agent is not building the string properly, or the manager is not parsing it correctly. I wonder if it may be due to any special character in the version, related to the OS language.

Please enable debug-2 mode in the agent (_internal_options.conf_):
```sh
windows.debug=2
```

Then restart the agent and find a log like this in _ossec.log_:
```
2022/02/03 10:41:20 wazuh-agent[1356] notify.c:188 at run_notify(): DEBUG: Sending keep alive: #!-Microsoft Windows Server 2019 Standard Evaluation [Ver: 10.0.17763] - Wazuh v4.2.5 / ab73af41699f13fdd81903b5f23d8d00
2c45c95db2954d2c7d0ea533f09e81a5 merged.mg
#"_agent_ip":192.168.182.130
```

Finally, set `windows.debug` back to `0` and restart the agent, to prevent it from flooding the log.

That log will definitely help us catch the bug.

Cheers!

**Comment by mhamra** [comment] 2023-06-07 20:19
### UPDATE
- Installed a Vbox Windows 11 Virtual machine to prepare an agent connected to a local docker environment.

**Comment by mhamra** [comment] 2023-06-08 15:48
### UPDATE
I couldn't reproduce the issue. Here are the details.

- Windows 11 pro installed in a virtual box VM.
![VirtualBox_windows 11_08_06_2023_12_01_09](https://github.com/wazuh/wazuh/assets/2949519/260d5238-4c5d-40cd-ac3d-94fe63c8d0ec)

- Wazuh v4.4.3 agent installed in windows and enrolled in a Single-node docker environment. Manager version 4.4.0 revision 40405
![image](https://github.com/wazuh/wazuh/assets/2949519/d7557dc3-83aa-4e35-ae0a-c4faa41884b1)

![image](https://github.com/wazuh/wazuh/assets/2949519/f69e7213-8fb0-4335-86c6-cc55a50bb5a9)

- API Call to overview/agents
```
curl -k -X GET "https://localhost:55000/overview/agents?pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "nodes": [
         {
            "node_name": "node01",
            "count": 1
         }
      ],
      "groups": [
         {
            "name": "default",
            "count": 1,
            "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         }
      ],
      "agent_os": [
         {
            "os": {
               "name": "Microsoft Windows 11 Pro",
               "platform": "windows",
               "version": "10.0.22000.2003"
            },
            "count": 1
         }
      ],
      "agent_status": {
         "connection": {
            "active": 0,
            "disconnected": 1,
            "never_connected": 0,
            "pending": 0,
            "total": 1
         },
         "configuration": {
            "synced": 1,
            "total": 1,
            "not_synced": 0
         }
      },
      "agent_version": [
         {
            "version": "Wazuh v4.4.3",
            "count": 1
         }
      ],
      "last_registered_agent": [
         {
            "os": {
               "build": "22000",
               "major": "10",
               "minor": "0",
               "name": "Microsoft Windows 11 Pro",
               "platform": "windows",
               "uname": "Microsoft Windows 11 Pro",
               "version": "10.0.22000.2003"
            },
            "name": "wazuh-w11",
            "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
            "dateAdd": "2023-06-07T20:39:15+00:00",
            "node_name": "node01",
            "id": "001",
            "ip": "192.168.88.54",
            "group": [
               "default"
            ],
            "registerIP": "any",
            "version": "Wazuh v4.4.3",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "manager": "wazuh.manager",
            "status": "disconnected",
            "lastKeepAlive": "2023-06-08T12:14:32+00:00",
            "disconnection_time": "2023-06-08T12:32:25+00:00",
            "group_config_status": "synced"
         }
      ]
   },
   "error": 0
}
```

**Comment by vikman90** [comment] 2023-06-12 09:34
@mhamra Thanks for the update. In this case, let me close this issue. Feel free to open it back if the problem appears again.

Best!

**Closed by vikman90** 2023-06-12 09:34 UTC
Labels: type/bug, module/agent, platform/windows, level/task

**Comment by mhamra** [comment] 2023-06-12 12:15
### UPDATE
- Windows Server 2019 std installed in a virtual machine with wazuh agent. Wazuh agent service started on the virtual machine
![image](https://github.com/wazuh/wazuh/assets/2949519/5198e361-2516-4bf9-b36f-2d3e3c7d0e02)

- Manage_agents output in manager node
```
****************************************
* Wazuh v4.4.0 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q: L

Available agents: 
   ID: 002, Name: wazuh-w11, IP: any
   ID: 003, Name: WIN-TA1KRF91QAR, IP: any

** Press ENTER to return to the main menu.
```

- Api call to overview/agents  endpoint and output
```
curl -k -X GET "https://localhost:55000/overview/agents?pretty=true" -H "Authorization: Bearer $TOKEN"
{
   "data": {
      "nodes": [
         {
            "node_name": "node01",
            "count": 2
         }
      ],
      "groups": [
         {
            "name": "default",
            "count": 2,
            "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00"
         }
      ],
      "agent_os": [
         {
            "os": {
               "name": "Microsoft Windows 11 Pro",
               "platform": "windows",
               "version": "10.0.22000.258"
            },
            "count": 1
         },
         {
            "os": {
               "name": "Microsoft Windows Server 2019 Standard Evaluation",
               "platform": "windows",
               "version": "10.0.17763.3650"
            },
            "count": 1
         }
      ],
      "agent_status": {
         "connection": {
            "active": 2,
            "disconnected": 0,
            "never_connected": 0,
            "pending": 0,
            "total": 2
         },
         "configuration": {
            "synced": 2,
            "total": 2,
            "not_synced": 0
         }
      },
      "agent_version": [
         {
            "version": "Wazuh v4.4.3",
            "count": 2
         }
      ],
      "last_registered_agent": [
         {
            "os": {
               "build": "17763",
               "major": "10",
               "minor": "0",
               "name": "Microsoft Windows Server 2019 Standard Evaluation",
               "platform": "windows",
               "uname": "Microsoft Windows Server 2019 Standard Evaluation",
               "version": "10.0.17763.3650"
            },
            "name": "WIN-TA1KRF91QAR",
            "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
            "dateAdd": "2023-06-12T11:58:23+00:00",
            "node_name": "node01",
            "id": "003",
            "ip": "192.168.88.50",
            "group": [
               "default"
            ],
            "registerIP": "any",
            "version": "Wazuh v4.4.3",
            "configSum": "ab73af41699f13fdd81903b5f23d8d00",
            "manager": "wazuh.manager",
            "status": "active",
            "lastKeepAlive": "2023-06-12T12:07:27+00:00",
            "group_config_status": "synced"
         }
      ]
   },
   "error": 0
```
