### ISSUE TITLE
Abort in wazuh-syscheckd (RHEL 9)

### ISSUE THREAD

**Issue by santipadilla** [wazuh/wazuh#21820] opened 2024-02-08 08:47 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-40803 | Syscheckd | Agent | Demo-environment | RHEL 9 |

## Description
During testing of [4.8.0 beta 1 - demo environment](https://github.com/wazuh/wazuh/issues/21763) an abort message from wazuh-syscheckd appears on RHEL 9 Agent.

## Service status
```console
[root@ip-10-0-1-23 wazuh-user]# journalctl -xe -u wazuh-agent.service --no-pager
Feb 07 11:38:17 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
░░ Subject: A start job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 5593.
Feb 07 11:38:17 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Starting Wazuh v4.8.0...
Feb 07 11:38:17 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Started wazuh-execd...
Feb 07 11:38:18 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Started wazuh-agentd...
Feb 07 11:38:19 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Started wazuh-syscheckd...
Feb 07 11:38:19 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Started wazuh-logcollector...
Feb 07 11:38:20 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Started wazuh-modulesd...
Feb 07 11:38:22 ip-10-0-1-23.us-west-1.compute.internal env[6226]: Completed.
Feb 07 11:38:22 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has finished successfully.
░░ 
░░ The job identifier is 5593.
Feb 07 11:38:26 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopping Wazuh agent...
░░ Subject: A stop job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 5862.
Feb 07 11:38:26 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Killing wazuh-modulesd...
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Killing wazuh-logcollector...
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Killing wazuh-syscheckd...
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Killing wazuh-agentd...
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Killing wazuh-execd...
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6737]: Wazuh v4.8.0 Stopped
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service has successfully entered the 'dead' state.
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopped Wazuh agent.
░░ Subject: A stop job for unit wazuh-agent.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has finished.
░░ 
░░ The job identifier is 5862 and the job result is done.
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Consumed 3.782s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service completed and consumed the indicated resources.
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
░░ Subject: A start job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 5862.
Feb 07 11:38:30 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Starting Wazuh v4.8.0...
Feb 07 11:38:31 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Started wazuh-execd...
Feb 07 11:38:32 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Started wazuh-agentd...
Feb 07 11:38:33 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Started wazuh-syscheckd...
Feb 07 11:38:34 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Started wazuh-logcollector...
Feb 07 11:38:35 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Started wazuh-modulesd...
Feb 07 11:38:37 ip-10-0-1-23.us-west-1.compute.internal env[6873]: Completed.
Feb 07 11:38:37 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has finished successfully.
░░ 
░░ The job identifier is 5862.
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopping Wazuh agent...
░░ Subject: A stop job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 18539.
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Killing wazuh-modulesd...
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Killing wazuh-logcollector...
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Killing wazuh-syscheckd...
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Killing wazuh-agentd...
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Killing wazuh-execd...
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal env[49782]: Wazuh v4.8.0 Stopped
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service has successfully entered the 'dead' state.
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopped Wazuh agent.
░░ Subject: A stop job for unit wazuh-agent.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has finished.
░░ 
░░ The job identifier is 18539 and the job result is done.
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Consumed 45.082s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service completed and consumed the indicated resources.
Feb 07 11:51:51 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
░░ Subject: A start job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 18539.
Feb 07 11:51:52 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Starting Wazuh v4.8.0...
Feb 07 11:51:53 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Started wazuh-execd...
Feb 07 11:51:54 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Started wazuh-agentd...
Feb 07 11:51:55 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Started wazuh-syscheckd...
Feb 07 11:51:56 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Started wazuh-logcollector...
Feb 07 11:51:57 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Started wazuh-modulesd...
Feb 07 11:51:59 ip-10-0-1-23.us-west-1.compute.internal env[49846]: Completed.
Feb 07 11:51:59 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has finished successfully.
░░ 
░░ The job identifier is 18539.
Feb 07 11:52:50 ip-10-0-1-23.us-west-1.compute.internal systemd-coredump[52170]: [🡕] Process 51572 (wazuh-syscheckd) of user 0 dumped core.
░░ Subject: Process 51572 (wazuh-syscheckd) dumped core
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ Documentation: man:core(5)
░░ 
░░ Process 51572 (wazuh-syscheckd) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
Feb 07 11:52:56 ip-10-0-1-23.us-west-1.compute.internal osqueryd[52287]: osqueryd started [version=4.4.0]
Feb 07 11:56:04 ip-10-0-1-23.us-west-1.compute.internal osqueryd[54435]: osqueryd started [version=4.4.0]
Feb 07 12:11:57 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopping Wazuh agent...
░░ Subject: A stop job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 22288.
Feb 07 12:11:57 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Killing wazuh-modulesd...
Feb 07 12:11:57 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Killing wazuh-logcollector...
Feb 07 12:11:57 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Killing wazuh-syscheckd...
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Killing wazuh-agentd...
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Killing wazuh-execd...
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal env[57628]: Wazuh v4.8.0 Stopped
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service has successfully entered the 'dead' state.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 54443 (osqueryd) remains running after unit stopped.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 57657 (wazuh-modulesd) remains running after unit stopped.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 57658 (wazuh-modulesd) remains running after unit stopped.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopped Wazuh agent.
░░ Subject: A stop job for unit wazuh-agent.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has finished.
░░ 
░░ The job identifier is 22288 and the job result is done.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Consumed 1min 56.752s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service completed and consumed the indicated resources.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
░░ Subject: A start job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 22288.
Feb 07 12:11:58 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Starting Wazuh v4.8.0...
Feb 07 12:11:59 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Started wazuh-execd...
Feb 07 12:12:00 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Started wazuh-agentd...
Feb 07 12:12:01 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Started wazuh-syscheckd...
Feb 07 12:12:02 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Started wazuh-logcollector...
Feb 07 12:12:02 ip-10-0-1-23.us-west-1.compute.internal osqueryd[57803]: osqueryd started [version=4.4.0]
Feb 07 12:12:03 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Started wazuh-modulesd...
Feb 07 12:12:05 ip-10-0-1-23.us-west-1.compute.internal env[57696]: Completed.
Feb 07 12:12:05 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has finished successfully.
░░ 
░░ The job identifier is 22288.
Feb 07 12:17:44 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopping Wazuh agent...
░░ Subject: A stop job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 25772.
Feb 07 12:17:44 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Killing wazuh-modulesd...
Feb 07 12:17:44 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Killing wazuh-logcollector...
Feb 07 12:17:44 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Killing wazuh-syscheckd...
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Killing wazuh-agentd...
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Killing wazuh-execd...
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal env[60481]: Wazuh v4.8.0 Stopped
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service has successfully entered the 'dead' state.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 57811 (osqueryd) remains running after unit stopped.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 60516 (wazuh-modulesd) remains running after unit stopped.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Unit process 60517 (wazuh-modulesd) remains running after unit stopped.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Stopped Wazuh agent.
░░ Subject: A stop job for unit wazuh-agent.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-agent.service has finished.
░░ 
░░ The job identifier is 25772 and the job result is done.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: wazuh-agent.service: Consumed 42.363s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-agent.service completed and consumed the indicated resources.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Starting Wazuh agent...
░░ Subject: A start job for unit wazuh-agent.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has begun execution.
░░ 
░░ The job identifier is 25772.
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Starting Wazuh v4.8.0...
Feb 07 12:17:45 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Started wazuh-execd...
Feb 07 12:17:46 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Started wazuh-agentd...
Feb 07 12:17:47 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Started wazuh-syscheckd...
Feb 07 12:17:47 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Started wazuh-logcollector...
Feb 07 12:17:47 ip-10-0-1-23.us-west-1.compute.internal osqueryd[60645]: osqueryd started [version=4.4.0]
Feb 07 12:17:48 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Started wazuh-modulesd...
Feb 07 12:17:50 ip-10-0-1-23.us-west-1.compute.internal env[60555]: Completed.
Feb 07 12:17:50 ip-10-0-1-23.us-west-1.compute.internal systemd[1]: Started Wazuh agent.
░░ Subject: A start job for unit wazuh-agent.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-agent.service has finished successfully.
░░ 
░░ The job identifier is 25772.
```

## Part where it appears
```console
Feb 07 11:52:50 ip-10-0-1-23.us-west-1.compute.internal systemd-coredump[52170]: [🡕] Process 51572 (wazuh-syscheckd) of user 0 dumped core.
░░ Subject: Process 51572 (wazuh-syscheckd) dumped core
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ Documentation: man:core(5)
░░ 
░░ Process 51572 (wazuh-syscheckd) crashed and dumped core.
░░ 
░░ This usually indicates a programming error in the crashing program and
░░ should be reported to its vendor as a bug.
```

## More details about the core dump
```console
[root@ip-10-0-1-23 wazuh-user]# coredumpctl info 51572
           PID: 51572 (wazuh-syscheckd)
           UID: 0 (root)
           GID: 990 (wazuh)
        Signal: 6 (ABRT)
     Timestamp: Wed 2024-02-07 11:52:50 UTC (12h ago)
  Command Line: /var/ossec/bin/wazuh-syscheckd
    Executable: /var/ossec/bin/wazuh-syscheckd
 Control Group: /system.slice/wazuh-agent.service
          Unit: wazuh-agent.service
         Slice: system.slice
       Boot ID: 3b231978b13e4d8c9ce6cfa2099ac807
    Machine ID: ec2f78a0fef40904170a42f046ff675e
      Hostname: ip-10-0-1-23.us-west-1.compute.internal
       Storage: none
       Message: Process 51572 (wazuh-syscheckd) of user 0 dumped core.
```

**Comment by lchico** [comment] 2024-02-08 22:20
# Update:

I tried to reproduce the coredump but without success. 

One of the things I noticed is that close to the coredump event, a reboot had occurred. Therefore, I conducted the following tests:

1. I ran a command that forced a reboot every 65 seconds.

```bash
let count=0 ; while [[ $(coredumpctl list|wc -l) < 5 ]] ; do service wazuh-agent restart; sleep 65 ;echo Try $count|tee number_of_try_to_coredump.txt ; ((count++)) ; done
```
![Screenshot from 2024-02-08 18-22-49](https://github.com/wazuh/wazuh/assets/21695385/9ab4b537-44ad-43a6-bff0-9015370e7190)

**Note:** I leave this command running to check if it reproduces the coredump

2. I also noticed that a test had been run previously (*/home/wazuh-user/yara/installation/yara-4.0.1/test-exception*) which generated signals (**SIGBUS**, **SIGSEGV**). Therefore, I conducted a similar test to the previous one, but instead of restarting the agent, I ran the test.
![Screenshot from 2024-02-08 16-16-28](https://github.com/wazuh/wazuh/assets/21695385/3b43ea9e-0b5f-4edf-b79a-dbd50f7491a9)


```bash
let count=9 ; while [[ $(coredumpctl list|wc -l) < $count ]] ; do ./test-exception; sleep 5 ;echo Try $count|tee number_of_try_to_coredump.txt ; ((count+=2)) ; done
```
![Screenshot from 2024-02-08 18-52-55](https://github.com/wazuh/wazuh/assets/21695385/52fc6f7e-21d5-46df-bb78-a85e90aba8dc)

3. I downloaded the ossec-07.log file but couldn't find anything unusual.

**Comment by lchico** [comment] 2024-02-09 13:25
# Update 9-02-2024:
Moving to Blocked as we cannot reproduce it after 256 restarts and all functionalities appear to be working correctly. Unfortunately, reproducing the issue requires further details.

![Screenshot from 2024-02-09 10-02-35](https://github.com/wazuh/wazuh/assets/21695385/b2839e42-d73d-441b-8dbd-1b6de3c1689e)

**Comment by vikman90** [comment] 2024-02-12 11:35
Closing this issue as non-reproducible.

**Closed by vikman90** 2024-02-12 11:35 UTC
Labels: type/bug
