### ISSUE TITLE
Debian 12 agent installation

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh#17757] opened 2023-07-05 10:31 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 4.4.4-1|  Agent | Packages | Debian 12 |

## Description

During the installation of an agent on Debian 12, the following error was detected:

```
Preparing to unpack .../wazuh-agent_4.4.4-1_amd64.deb ...
Unpacking wazuh-agent (4.4.4-1) ...
Setting up wazuh-agent (4.4.4-1) ...
chmod: cannot access '/var/ossec/ruleset/sca/*': No such file or directory
dpkg: error processing package wazuh-agent (--configure):
 installed wazuh-agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
## Steps to reproduce

<details>
<summary>Step by step installation</summary>
<br>

Necessary previous steps that were not in the documentation:

```
apt update
apt upgrade
apt install gpg curl
```

We follow the [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html) and at the moment of installation we obtain:

```
root@bookworm:/home/vagrant# WAZUH_MANAGER="172.17.1.12" apt-get install wazuh-agent
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  wazuh-agent
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 8921 kB of archives.
After this operation, 30.2 MB of additional disk space will be used.
Get:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-agent amd64 4.4.4-1 [8921 kB]
Fetched 8921 kB in 2s (4610 kB/s)      
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "es_ES.UTF-8",
	LC_MONETARY = "es_ES.UTF-8",
	LC_ADDRESS = "es_ES.UTF-8",
	LC_TELEPHONE = "es_ES.UTF-8",
	LC_NAME = "es_ES.UTF-8",
	LC_MEASUREMENT = "es_ES.UTF-8",
	LC_IDENTIFICATION = "es_ES.UTF-8",
	LC_NUMERIC = "es_ES.UTF-8",
	LC_PAPER = "es_ES.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Preconfiguring packages ...
Selecting previously unselected package wazuh-agent.
(Reading database ... 25796 files and directories currently installed.)
Preparing to unpack .../wazuh-agent_4.4.4-1_amd64.deb ...
Unpacking wazuh-agent (4.4.4-1) ...
Setting up wazuh-agent (4.4.4-1) ...
chmod: cannot access '/var/ossec/ruleset/sca/*': No such file or directory
dpkg: error processing package wazuh-agent (--configure):
 installed wazuh-agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Afterwards, the installation is half-finished and the environment is left dirty:

```
root@bookworm:/home/vagrant# ls /var/ossec/
active-response  backup  etc  logs	      queue    tmp  wodles
agentless	 bin	 lib  packages_files  ruleset  var

root@bookworm:/home/vagrant# ls /var/ossec/ruleset/
sca
```

</details>

<details>
<summary>Install from packages list</summary>
<br>

We can find the same result when installing the [Pacakges list](https://documentation.wazuh.com/current/installation-guide/packages-list.html) package:

```
root@bookworm:/home/vagrant# wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.4-1_amd64.deb
--2023-07-05 09:17:11--  https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.4.4-1_amd64.deb
Resolving packages.wazuh.com (packages.wazuh.com)... 18.154.48.50, 18.154.48.93, 18.154.48.117, ...
Connecting to packages.wazuh.com (packages.wazuh.com)|18.154.48.50|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8920964 (8.5M) [binary/octet-stream]
Saving to: 'wazuh-agent_4.4.4-1_amd64.deb'

wazuh-agent_4.4.4-1_amd64 100%[=====================================>]   8.51M  4.91MB/s    in 1.7s    

2023-07-05 09:17:13 (4.91 MB/s) - 'wazuh-agent_4.4.4-1_amd64.deb' saved [8920964/8920964]

root@bookworm:/home/vagrant# dpkg -i wazuh-agent_4.4.4-1_amd64.deb 
Selecting previously unselected package wazuh-agent.
(Reading database ... 25530 files and directories currently installed.)
Preparing to unpack wazuh-agent_4.4.4-1_amd64.deb ...
Unpacking wazuh-agent (4.4.4-1) ...
Setting up wazuh-agent (4.4.4-1) ...
chmod: cannot access '/var/ossec/ruleset/sca/*': No such file or directory
dpkg: error processing package wazuh-agent (--install):
 installed wazuh-agent package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
```

</details>

<details>
<summary>Install from sources</summary>
<br>

Finally, if we install by [sources](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html) we can see:

```
Done building agent

Wait for success...
success
Removing old SCA policies...
Installing SCA policies...


Created symlink /etc/systemd/system/multi-user.target.wants/wazuh-agent.service → /etc/systemd/system/wazuh-agent.service.

 - Configuration finished properly.

 - To start Wazuh:
      /var/ossec/bin/wazuh-control start

 - To stop Wazuh:
      /var/ossec/bin/wazuh-control stop

 - The configuration can be viewed or modified at /var/ossec/etc/ossec.conf


   Thanks for using Wazuh.
   Please don't hesitate to contact us if you need help or find
   any bugs.

   Use our public Mailing List at:
          https://groups.google.com/forum/#!forum/wazuh

   More information can be found at:
          - http://www.wazuh.com

    ---  Press ENTER to finish (maybe more information below). ---


 - More information at: 
   https://documentation.wazuh.com/
```

It does not seem to give any error, but we see that the installation is also incomplete:

```
root@bookworm:/home/vagrant/wazuh-4.4.4# ls /var/ossec/ruleset/sca/
root@bookworm:/home/vagrant/wazuh-4.4.4# 
```

We can also connect to the manager and the agent is running as expected:

```
root@bookworm:/home/vagrant# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: bookworm (server), IP: 127.0.0.1, Active/Local
   ID: 002, Name: testing, IP: any, Active
```

```
root@bookworm:/home/vagrant/wazuh-4.4.4# systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
     Loaded: loaded (/etc/systemd/system/wazuh-agent.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-07-05 10:24:04 UTC; 4min 11s ago
    Process: 20254 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUC>
      Tasks: 28 (limit: 2307)
     Memory: 218.0M
        CPU: 10.271s
     CGroup: /system.slice/wazuh-agent.service
             ├─20532 /var/ossec/bin/wazuh-execd
             ├─20543 /var/ossec/bin/wazuh-agentd
             ├─20557 /var/ossec/bin/wazuh-syscheckd
             ├─20576 /var/ossec/bin/wazuh-logcollector
             └─20628 /var/ossec/bin/wazuh-modulesd

Jul 05 10:23:57 bookworm systemd[1]: Starting wazuh-agent.service - Wazuh agent...
Jul 05 10:23:57 bookworm env[20254]: Starting Wazuh v4.4.4...
Jul 05 10:23:58 bookworm env[20254]: Started wazuh-execd...
Jul 05 10:23:59 bookworm env[20254]: Started wazuh-agentd...
Jul 05 10:24:00 bookworm env[20254]: Started wazuh-syscheckd...
Jul 05 10:24:01 bookworm env[20254]: Started wazuh-logcollector...
Jul 05 10:24:02 bookworm env[20254]: Started wazuh-modulesd...
Jul 05 10:24:04 bookworm env[20254]: Completed.
Jul 05 10:24:04 bookworm systemd[1]: Started wazuh-agent.service - Wazuh agent.
```

</details>

<details>
<summary>Manager installation</summary>
<br>

However, the manager has been installed without any problems:

```
root@bookworm:/home/vagrant# apt-get -y install wazuh-manager
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Suggested packages:
  expect
The following NEW packages will be installed:
  wazuh-manager
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 171 MB of archives.
After this operation, 631 MB of additional disk space will be used.
Get:1 https://packages.wazuh.com/4.x/apt stable/main amd64 wazuh-manager amd64 4.4.4-1 [171 MB]
Fetched 171 MB in 33s (5226 kB/s)                                                                      
apt-listchanges: Can't set locale; make sure $LC_* and $LANG are correct!
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "es_ES.UTF-8",
	LC_MONETARY = "es_ES.UTF-8",
	LC_ADDRESS = "es_ES.UTF-8",
	LC_TELEPHONE = "es_ES.UTF-8",
	LC_NAME = "es_ES.UTF-8",
	LC_MEASUREMENT = "es_ES.UTF-8",
	LC_IDENTIFICATION = "es_ES.UTF-8",
	LC_NUMERIC = "es_ES.UTF-8",
	LC_PAPER = "es_ES.UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package wazuh-manager.
(Reading database ... 25800 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.4.4-1_amd64.deb ...
Unpacking wazuh-manager (4.4.4-1) ...
Setting up wazuh-manager (4.4.4-1) ...
```

And it is running as expected:

```
root@bookworm:/home/vagrant# systemctl status wazuh-manager
● wazuh-manager.service - Wazuh manager
     Loaded: loaded (/lib/systemd/system/wazuh-manager.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-07-05 08:52:43 UTC; 17s ago
    Process: 45915 ExecStart=/usr/bin/env /var/ossec/bin/wazuh-control start (code=exited, status=0/SUC>
      Tasks: 111 (limit: 495)
     Memory: 263.1M
        CPU: 14.297s
     CGroup: /system.slice/wazuh-manager.service
             ├─45971 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─46011 /var/ossec/bin/wazuh-authd
             ├─46027 /var/ossec/bin/wazuh-db
             ├─46041 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─46044 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py
             ├─46057 /var/ossec/bin/wazuh-execd
             ├─46071 /var/ossec/bin/wazuh-analysisd
             ├─46114 /var/ossec/bin/wazuh-syscheckd
             ├─46133 /var/ossec/bin/wazuh-remoted
             ├─46191 /var/ossec/bin/wazuh-logcollector
             ├─46241 /var/ossec/bin/wazuh-monitord
             └─46293 /var/ossec/bin/wazuh-modulesd

Jul 05 08:52:33 bookworm env[45915]: Started wazuh-db...
Jul 05 08:52:34 bookworm env[45915]: Started wazuh-execd...
Jul 05 08:52:35 bookworm env[45915]: Started wazuh-analysisd...
Jul 05 08:52:36 bookworm env[45915]: Started wazuh-syscheckd...
Jul 05 08:52:37 bookworm env[45915]: Started wazuh-remoted...
Jul 05 08:52:39 bookworm env[45915]: Started wazuh-logcollector...
Jul 05 08:52:40 bookworm env[45915]: Started wazuh-monitord...
Jul 05 08:52:41 bookworm env[45915]: Started wazuh-modulesd...
Jul 05 08:52:43 bookworm env[45915]: Completed.
Jul 05 08:52:43 bookworm systemd[1]: Started wazuh-manager.service - Wazuh manager.
```

</details>

**Comment by misje** [comment] 2023-07-05 17:01
I haven't inspected all of postinst, but I am guessing that this fails perhaps because there are no SCA rules for Bookworm. After all, there seems to be logic depending on the distribution output of `lsb_release`, and there is no file */var/ossec/packages_files/agent_installation_scripts/etc/templates/config/debian/12/sca.files*.

When a package's postinst breaks, to some extent you break the package manager. You may have to explicitly remove wazuh-agent to continue using dpkg / your package manager. I would consider this an important issue.

I have modified postinst as a workaround, leaving the target without a SCA. Should the Debian 11/Bullseye SCA file be used instead of having no SCA file, perhaps?

**Comment by vikman90** [comment] 2023-07-06 07:03
@juliamagan @misje This issue is a duplicate of https://github.com/wazuh/wazuh-packages/issues/2196.

We're already working on that (related PR: https://github.com/wazuh/wazuh-packages/pull/2197). 

Let me close this issue.
Cheers!

**Closed by vikman90** 2023-07-06 07:03 UTC
Labels: duplicated
