### ISSUE TITLE
Timeout when upgrading a Rocky Linux agent

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh#18759] opened 2023-09-01 18:30 UTC
|Wazuh versions |Component | Install type | Install method | Platform |
|---|---|---|---|---|
| `4.4.1` - `4.5.1` | Upgrade Module | - | Packages | Ubuntu Jammy Jellyfish |

## Description

When trying to upgrade an agent in a Rocky Linux endpoint from the manager using the `agent_upgrade` tool the process fails with a timeout error.

🗒️ This has been happening in a community user's environment since `4.4.1` and it can be reproduced in `4.5.1`.

## Steps to reproduce

1. Upgrade a Rocky Linux agent using the `agent_upgrade` tool
2. Wait until the timeout error is displayed

## Test - Deployment 1: Manager and agent running in the same host

- `Host`: macOS M2 (arm64)
- `Virtualization system`: Docker (using Rosetta to allow `amd64` containers to run over the M2 chip):
  - Containers:
    - `Wazuh Manager 4.5.1`: Ubuntu 22.04 Jammy Jellyfish (5.15.49-linuxkit-pr aarch64) [**privileged mode**]
    - `Wazuh Agent 4.5.0`: Rocky Linux Green Obsidian 8.8 (5.15.49-linuxkit-pr x86_64) [**privileged mode**]

**Necessary files**: [manager-agent_rocky_linux.zip](https://github.com/wazuh/wazuh/files/12500411/manager-agent_rocky_linux.zip)

**To deploy**: `docker-compose -f man-agent_rocky.yaml up --build -d`

### Evidence of failure

[evidence-manager-rocky-upgrade.md](https://github.com/wazuh/wazuh/files/12500145/evidence-manager-rocky-upgrade.md)

> ⚠️ **Note:** The errors from `wazuh-logcollector` will be addressed in another issue as they could be caused by the environment. For now, it has been found that they do not have direct influence over the upgrade process.

## Test - Deployment 2: Manager and agent in different hosts (community user)

The same issue is happening in the environment of a **community user** 👤, which is the following:

- `Host 1`: Ubuntu 20.04.6 LTS (GNU/Linux 5.4.0-148-generic x86_64)
  - `Wazuh Manager 4.5.1`
- `Host 2`: Debian 10
  - `Virtualization system`: KVM (using Proxmox 6)
    - KVM machine:
      - `Wazuh Agent 4.5.0`: Rocky Linux 8.8

### Evidence of failure

<details></br>

```
# /var/ossec/bin/agent_upgrade -a 001 003 004 005 006 007 008 009 010 011

Upgrading...

Upgraded agents:
	Agent 003 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 004 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 005 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 006 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 007 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 008 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 009 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 010 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1
	Agent 011 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1

Failed upgrades:
	Agent 001 status: Timeout reached while waiting for the response from the agent



root@wazu:/home/ubuntu# /var/ossec/bin/agent_control -i 001

Wazuh agent_control. Agent information:
   Agent ID:   001
   Agent Name: cp.uhlhosting.ch
   IP address: any
   Status:     Active

   Operating system:    Linux |cp.uhlhosting.ch |4.18.0-425.19.2.el8_7.x86_64 |#1 SMP Tue Apr 4 22:38:11 UTC 2023 |x86_64
   Client version:      Wazuh v4.5.0
   Configuration hash:  c185d15fce5171983a7bfb3f09447244
   Shared file hash:    993c61d7952b815a526590d53072f0d9
   Last keep alive:     1693361718

   Syscheck last started at:  Wed Aug 30 01:05:15 2023
   Syscheck last ended at:    Wed Aug 30 01:10:23 2023
```

</details>

## Current result

- The manager reports a timeout error
- The agent is successfully upgraded, and the logs do not show anything wrong

## Expected result

- The manager should report that the agent was upgraded successfully as the agent does

**Comment by mauromalara** [comment] 2023-09-01 18:48
The impact of this is **low** because the agent is upgraded successfully and the connection with the manager is established ok after the timeout error.

**Comment by vikman90** [comment] 2023-09-04 06:13
@mauromalara Can you confirm that the problem is different than https://github.com/wazuh/wazuh/issues/14856?

Please assure that the manager's configuration has this setting:

```xml
<agent-upgrade>
  <chunk_size>32768</chunk_size>
</agent-upgrade>
```

If the upgrade works with that configuration, we can close this issue.

Best.

**Comment by mauromalara** [comment] 2023-09-04 11:46
@vikman90 the upgrade works, but the message thrown by the manager is not correct. The agent is correctly upgraded in this case. Which is different than the case you mentioned, where the agent is not upgraded due to connection issues so it's necessary to increase the chunk size. But, I'll increase that number and let you know the results.

Regards.

**Comment by mauromalara** [comment] 2023-09-04 20:10
@vikman90 

I made different tests (**with `chunk_size` set in the value you mentioned**) and some of them passed only when several modules were disabled:

> ALL == SYSCHECK, SCA, SYSCOLLECTOR, ROOTCHECK (_and sometimes + ACTIVE-RESPONSE_)

- [Test with ALL modules disabled on both sides 🟢](https://github.com/wazuh/wazuh/files/12516355/evidence-manager-rocky-upgrade-OK.md)
- [Test with ALL disabled on both sides (DEBUG DISABLED on Agent) 🟢](https://github.com/wazuh/wazuh/files/12516359/evidence-manager-rocky-upgrade-OK-NO-DEBUG.md)
- [Test with LOGCOLLECTOR disabled on Agent and ALL modules disabled on Manager 🔴](https://github.com/wazuh/wazuh/files/12516356/evidence-manager-rocky-upgrade-LOGCOLLECTOR-DISABLED-AGENT.md)
- [Test with SYSCOLLECTOR disabled on Agent and ALL disabled on Manager 🔴](https://github.com/wazuh/wazuh/files/12516357/evidence-manager-rocky-upgrade-SYSCOLLECTOR-DISABLED-AGENT.md)
- [Test with ALL disabled on Manager and ALL enabled on Agent 🔴](https://github.com/wazuh/wazuh/files/12516358/evidence-manager-rocky-upgrade-NOTHING-ENABLED-MANAGER.md)

When the test passes it is observed that the agent sends the following message:

```syslog
2023/09/04 14:04:21 wazuh-modulesd:agent-upgrade[1202] wm_agent_upgrade_agent.c:280 at wm_upgrade_agent_send_ack_message(): DEBUG: (8163): Sending upgrade ACK event: '{"command":"upgrade_update_status","parameters":{"error":0,"message":"Upgrade was successful","status":"Done"}}'
```

And the manager receives this message correctly:
```syslog
2023/09/04 14:04:21 wazuh-modulesd:agent-upgrade[2836] wm_agent_upgrade_manager.c:150 at wm_agent_upgrade_listen_messages(): DEBUG: (8155): Incomming message: '{"command":"upgrade_update_status","parameters":{"error":0,"message":"Upgrade was successful","status":"Done","agents":[1]}}'
2023/09/04 14:04:21 wazuh-modulesd:agent-upgrade[2836] wm_agent_upgrade_commands.c:187 at wm_agent_upgrade_process_agent_result_command(): INFO: (8164): Received upgrade notification from agent '1'. Error code: '0', message: 'Upgrade was successful'
```

⚠️ **In the other cases the agent never sends this message to the manager causing the manager to keep waiting in the "Updating" status.**


That expected message comes from the `wazuh-modulesd`:

https://github.com/wazuh/wazuh/blob/731cdf39a430d2fb6fa02f3721624e07f887b02f/src/wazuh_modules/agent_upgrade/agent/wm_agent_upgrade_agent.c#L257C4-L283

**Comment by vikman90** [comment] 2023-09-05 09:21
I've not managed to reproduce this problem with a Docker environment.

<details><summary><h3>Files</h3></summary>

#### Dockerfile

```Dockerfile
FROM rockylinux:9-minimal

ARG WAZUH_MANAGER="172.28.54.78"

ADD wazuh.repo /etc/yum.repos.d/wazuh.repo
ADD run.sh /usr/local/bin/run

RUN microdnf install -y procps wazuh-agent-4.5.0-1 && \
    microdnf clean all

CMD run
```

#### run.sh [chmod +x]

```shell
#! /bin/bash

/var/ossec/bin/wazuh-control start
tail -f /var/ossec/logs/ossec.log
```

#### wazuh.repo

```
[wazuh]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-\$releasever - Wazuh
baseurl=https://packages.wazuh.com/4.x/yum/
protect=1

```

</details>

### Manager command

```shell
agent_upgrade -a 008
```

```
Upgrading...

Upgraded agents:
        Agent 008 upgraded: Wazuh v4.5.0 -> Wazuh v4.5.1

**Closed** 2024-04-16 19:47 UTC
Labels: type/bug, level/task
