### ISSUE TITLE
`ciscat-report.txt` and `ciscat-report.xml` files not found

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#15453] opened 2022-11-21 17:36 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Found in: 4.4.0 | wazuh-modulesd:ciscat | Agent | Packages | CentOS 7<br>Windows 2016 |

In the analysis of the 3 days stress test: https://github.com/wazuh/wazuh-jenkins/issues/4423#issuecomment-1320984282, the following error was found in the CentOS and Windows Wazuh agent.

- CentOS

```
ossec-17.log:2022/11/17 00:00:57 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
ossec-17.log:2022/11/17 00:00:57 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
```

- Windows

```
ossec-17.log:2022/11/17 00:00:54 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
ossec-17.log:2022/11/17 00:00:54 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp\ciscat-report.xml': No such file or directory
```

References to these files have been found in: 

- https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_modules/wm_ciscat.c#L735-L739

```
#ifdef WIN32
    snprintf(file, OS_MAXSTR - 1, "%s%s", TMP_DIR, "\\ciscat-report.txt");
#else
    snprintf(file, OS_MAXSTR - 1, "%s%s", WM_CISCAT_REPORTS, "/ciscat-report.txt");
#endif
```

- https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_modules/wm_ciscat.c#L940-946

```
#ifdef WIN32
    snprintf(in_file, OS_MAXSTR - 1, "%s%s", TMP_DIR, "\\ciscat-report.xml");
    snprintf(out_file, OS_MAXSTR - 1, "%s%s", TMP_DIR, "\\ciscat-tmp.xml");
#else
    snprintf(in_file, OS_MAXSTR - 1, "%s%s", WM_CISCAT_REPORTS, "/ciscat-report.xml");
    snprintf(out_file, OS_MAXSTR - 1, "%s%s", WM_CISCAT_REPORTS, "/ciscat-tmp.xml");
#endif
```

- https://github.com/wazuh/wazuh/blob/4.4/src/wazuh_modules/wm_ciscat.c#L683-L687

```
#ifdef WIN32
    snprintf(file, OS_MAXSTR - 1, "%s%s", TMP_DIR, "\\ciscat-report.xml");
#else
    snprintf(file, OS_MAXSTR - 1, "%s%s", WM_CISCAT_REPORTS, "/ciscat-report.xml");
#endif
```

---

- It is necessary to determine the origin of this error and perform the necessary actions to fix it.
- It is also necessary to determine whether this file should be collected for stress test analysis or not, if necessary, an issue should be opened in the `wazuh-jenkins` repository.

**Comment by chemamartinez** [comment] 2022-12-30 11:03
Hi team,

The reason for the following errors:
```
2022/11/17 00:00:57 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
2022/11/17 00:00:57 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
```
Is because the CIS-CAT integration is not able to run the scan against the configured benchmarks for any reason. So the report files are not generated and the module throws these errors when trying to parse the scan results.

This can be explained by the following:

**CentOS agent**
The CentOS agent used for the footprint tests is CentOS 8:
```
2022/11/16 22:28:24 wazuh-agentd: INFO: Version detected -> Linux |ip-172-31-15-118.ec2.internal |4.18.0-305.3.1.el8.x86_64 |#1 SMP Tue Jun 1 16:14:33 UTC 2021 |x86_64 [CentOS Linux|centos: 8.4] - Wazuh v4.4.0
```

However, the CIS-CAT benchmark configured is for CentOS 7, and Google Chrome, which will work only if the agent has Google Chrome installed. This is the reason why the scanner is not able to run the policies showing the following trace:
```
2022/11/16 22:30:54 wazuh-modulesd:ciscat: INFO: Starting evaluation.
2022/11/16 22:30:56 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
2022/11/16 22:30:56 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
2022/11/16 22:30:56 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_Google_Chrome_Benchmark_v1.2.0-xccdf.xml'
2022/11/16 22:31:01 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp/ciscat-report.txt' missing: No such file or directory
2022/11/16 22:31:01 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp/ciscat-report.xml': No such file or directory
2022/11/16 22:31:01 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy '/var/ossec/wodles/cis-cat/benchmarks/CIS_CentOS_Linux_7_Benchmark_v2.1.1-xccdf.xml'
2022/11/16 22:31:01 wazuh-modulesd:ciscat: INFO: Evaluation finished.
```

**Windows**
Here it is happening the same. The agent is Windows Server 2019:
```
2022/11/16 22:29:18 wazuh-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2019 Datacenter [Ver: 10.0.17763.1999] - Wazuh v4.4.0).
```
And the configured policy is for Windows Server 2016:
```
2022/11/16 22:30:04 wazuh-modulesd:ciscat: ERROR: Report result file 'tmp\ciscat-report.txt' missing: No such file or directory
2022/11/16 22:30:04 wazuh-modulesd:ciscat: ERROR: Unable to open 'tmp\ciscat-report.xml': No such file or directory
2022/11/16 22:30:04 wazuh-modulesd:ciscat: ERROR: Failed reading scan results for policy 'C:\cis-cat\benchmarks\CIS_Microsoft_Windows_Server_2016_Benchmark_v1.0.0-xccdf.xml'
```

CIS-CAT is too restrictive when the benchmark doesn't match the target OS.

This is not a regression bug (it also happens in older versions) and not a release stopper either, so I suggest the following:
- Close this issue and also https://github.com/wazuh/wazuh/issues/12088 which has the same reason.
- Open an issue to deprecate the CIS-CAT integration, since it is no longer maintained in favor of SCA.
- If decided to keep supporting CIS-CAT, fix the footprint test by configuring the correct CIS-CAT benchmarks (already reported at https://github.com/wazuh/wazuh-jenkins/issues/3293).

**Closed** 2023-01-11 10:50 UTC
Labels: reporter/cicd

**Comment by niek1992** [comment] 2023-04-07 10:39
Would like to add to this that the CIS-CAT integration of Wazuh only supports CIS-CAT Pro V3 (deprecated, not available to download anymore) instead of V4. Meaning that i needed to create a wrapper script called (CIS-CAT.sh) that calls Assessor-CLI.sh (which the script is called when you download CIS-CAT Pro V4) without some parameters that aren't available in V4 (mainly -rn and -r, which changed to -rp and -rd respectively).

Didn't know CIS-CAT was not being maintained anymore. SCA isn't fully covered either (some checks are not implemented) so i would like to have something that can check the full CIS benchmark that doesn't leave out any info that could potentially give a false idea of security. Not checked doesn't automatically mean that you're safe.
