### ISSUE TITLE
API fails to display agent present in `manage_agents` tool

### ISSUE THREAD

**Issue by GabrielEValenzuela** [wazuh/wazuh#23975] opened 2024-06-06 20:21 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.4 | Wazuh manager | Manager | Packages | Unknow/Cluster environment  |

### Description
The current API (version 4.7.4) does not display a specific agent, even though this agent is verifiably present when checked using the `manage_agents` tool. This discrepancy between the API's output and the tool's data could lead to inconsistencies in managing and monitoring agents.

This behavior has been reported by the community

### Steps to Reproduce
1. **Verify Agent Presence:**
   - Use the `manage_agents` tool to list all agents. Note that the agent in question appears in the list.
   
2. **API Query:**
   - Make a request to the API endpoint that lists agents or checks a specific agent's details.
   - Observe that the agent in question does not appear in the API response.

### Expected Behavior
The API should consistently reflect all agents that are present and accounted for in the `manage_agents` tool, ensuring accurate data representation across all management interfaces.

### Actual Behavior
The agent, though present when checked via the `manage_agents` tool, does not appear in the API output, leading to potential oversight and mismanagement.

### Additional Information
Upon request 

### Action Required
- **Investigation:** Further investigation is needed to determine why the API fails to display the agent.

## Acknowledgements
We greatly appreciate the efforts of @git-cgallagher for identifying and reporting this discrepancy. Thank you for your valuable contribution to our community!

---

**Comment by RamosFe** [comment] 2024-06-26 18:17
## Update

When testing the API endpoint `{protocol}://{host}:{port}/agents` and the `mamage_agents` tool in different environments, no difference was found. After investigating a bit more, the user said that the agent that didn't appear in the results of the API endpoint had local errors related to the enrollment, due to having the same name as another registered agent.

I built a new environment with the following configuration for both of the agents (The environment has 1 master, 2 workers, and 2 agents):

```bash
# Use sed to insert the <enrollment> block after the <server> block
sed -i '/<server>/,/<\/server>/{
/<\/server>/a \
    <enrollment>\n\
      <agent_name>hardcoded</agent_name>\n\
    </enrollment>
}' /var/ossec/etc/ossec.conf
```

Finally, the results from the API are the expected ones. There should be only 1 agent enrolled and another with an error due to the duplicated name:

```json
{
    "data": {
        "affected_items": [
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |wazuh-master |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "dateAdd": "2024-06-26T15:24:31+00:00",
                "ip": "127.0.0.1",
                "registerIP": "127.0.0.1",
                "lastKeepAlive": "9999-12-31T23:59:59+00:00",
                "node_name": "master-node",
                "status_code": 0,
                "status": "active",
                "name": "wazuh-master",
                "manager": "wazuh-master",
                "group_config_status": "synced",
                "version": "Wazuh v4.8.0",
                "id": "000"
            },
            {
                "os": {
                    "arch": "x86_64",
                    "codename": "Focal Fossa",
                    "major": "20",
                    "minor": "04",
                    "name": "Ubuntu",
                    "platform": "ubuntu",
                    "uname": "Linux |2e0489ceb4ec |6.2.6-76060206-generic |#202303130630~1683753207~22.04~77c1465 SMP PREEMPT_DYNAMIC Wed M |x86_64",
                    "version": "20.04.6 LTS"
                },
                "configSum": "ab73af41699f13fdd81903b5f23d8d00",
                "dateAdd": "2024-06-26T15:24:58+00:00",
                "ip": "172.23.0.4",
                "registerIP": "any",
                "lastKeepAlive": "2024-06-26T15:26:03+00:00",
                "node_name": "worker",
                "status_code": 0,
                "status": "active",
                "name": "hardcoded",
                "manager": "wazuh-worker1",
                "group_config_status": "synced",
                "group": [
                    "default"
                ],
                "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
                "version": "Wazuh v4.8.0",
                "id": "001"
            }
        ],
        "total_affected_items": 2,
        "total_failed_items": 0,
        "failed_items": []
    },
    "message": "All selected agents' information was returned",
    "error": 0
}
```

The same for the `manage_agents` tool:
```sh
root@wazuh-master:/var/ossec/bin# ./manage_agents -l

Available agents: 
   ID: 001, Name: hardcoded, IP: any
```

## Conclusion

No differences were found between the tool and the API. The API works as expected and only shows the connected Agents (in this test case only 1 due to the name duplication). Passing this Issue to @wazuh/devel-cppserver  due to having the ownership of the `manage_agents` tool.

**Comment by JavierBejMen** [comment] 2024-06-27 15:23
## Update
Made a test with an all-in-one deployment with 4 agents (ubuntu), trying to register one with a duplicated name, and registering it after deleting the old one. API and manage_agents results were both as expected.

I'm going to do a test in a cluster environment and more agents with different OSs. I will post the results once finish.

**Comment by JavierBejMen** [comment] 2024-06-28 09:19
## Update
### Server setup
```
# /var/ossec/bin/cluster_control -l
NAME     TYPE    VERSION  ADDRESS
wazuh-1  master  4.7.5    192.168.2.20
wazuh-2  worker  4.7.5    192.168.2.22
wazuh-3  worker  4.7.5    192.168.2.21
```

### Agents initial setup
manage_agents:
```
# /var/ossec/bin/manage_agents -l

Available agents:
   ID: 001, Name: ubuntu, IP: any
   ID: 002, Name: centos, IP: any
   ID: 003, Name: suse, IP: any
   ID: 004, Name: ama, IP: any
```

API:

<details>
<summary>response.json</summary>

```json
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "x86_64",
          "codename": "Focal Fossa",
          "major": "20",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |wazuh-manager-master |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64",
          "version": "20.04.6 LTS"
        },
        "status": "active",
        "lastKeepAlive": "9999-12-31T23:59:59+00:00",
        "group_config_status": "synced",
        "node_name": "wazuh-1",
        "registerIP": "127.0.0.1",
        "status_code": 0,
        "ip": "127.0.0.1",
        "version": "Wazuh v4.7.5",
        "manager": "wazuh-manager-master",
        "dateAdd": "2024-06-28T08:21:57+00:00",
        "name": "wazuh-manager-master",
        "id": "000"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "Focal Fossa",
          "major": "20",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |wazuh-agent-0 |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64",
          "version": "20.04.6 LTS"
        },
        "status": "active",
        "lastKeepAlive": "2024-06-28T08:51:47+00:00",
        "group": [
          "default"
        ],
        "group_config_status": "synced",
        "node_name": "wazuh-1",
        "registerIP": "any",
        "status_code": 0,
        "ip": "192.168.2.30",
        "version": "Wazuh v4.7.5",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "manager": "wazuh-manager-master",
        "dateAdd": "2024-06-28T08:38:12+00:00",
        "name": "ubuntu",
        "id": "001",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "7",
          "minor": "8",
          "name": "CentOS Linux",
          "platform": "centos",
          "uname": "Linux |wazuh-agent-1 |3.10.0-1127.el7.x86_64 |#1 SMP Tue Mar 31 23:36:51 UTC 2020 |x86_64",
          "version": "7.8"
        },
        "status": "active",
        "lastKeepAlive": "2024-06-28T08:51:48+00:00",
        "group": [
          "default"
        ],
        "group_config_status": "synced",
        "node_name": "wazuh-1",
        "registerIP": "any",
        "status_code": 0,
        "ip": "192.168.2.31",
        "version": "Wazuh v4.7.5",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "manager": "wazuh-manager-master",
        "dateAdd": "2024-06-28T08:38:51+00:00",
        "name": "centos",
        "id": "002",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "15",
          "minor": "5",
          "name": "openSUSE Leap",
          "platform": "opensuse-leap",
          "uname": "Linux |wazuh-agent-2 |5.14.21-150500.55.65-default |#1 SMP PREEMPT_DYNAMIC Thu May 23 04:57:11 UTC 2024 (a46829d) |x86_64",
          "version": "15.5"
        },
        "status": "active",
        "lastKeepAlive": "2024-06-28T08:51:46+00:00",
        "group": [
          "default"
        ],
        "group_config_status": "synced",
        "node_name": "wazuh-1",
        "registerIP": "any",
        "status_code": 0,
        "ip": "192.168.2.32",
        "version": "Wazuh v4.7.5",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "manager": "wazuh-manager-master",
        "dateAdd": "2024-06-28T08:41:50+00:00",
        "name": "suse",
        "id": "003",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "2",
          "name": "Amazon Linux",
          "platform": "amzn",
          "uname": "Linux |wazuh-agent-3 |4.14.336-257.568.amzn2.x86_64 |#1 SMP Sat Mar 23 09:49:55 UTC 2024 |x86_64",
          "version": "2"
        },
        "status": "active",
        "lastKeepAlive": "2024-06-28T08:51:43+00:00",
        "group": [
          "default"
        ],
        "group_config_status": "synced",
        "node_name": "wazuh-1",
        "registerIP": "any",
        "status_code": 0,
        "ip": "192.168.2.33",
        "version": "Wazuh v4.7.5",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "manager": "wazuh-manager-master",
        "dateAdd": "2024-06-28T08:47:06+00:00",
        "name": "ama",
        "id": "004",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e"
      }
    ],
    "total_affected_items": 5,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

🟢 **Both methods correctly lists the agents**

### Agents modified setup
Renamed the centos agent to ama, waited until duplicate name is thrown:
```
# tail -f /var/ossec/logs/ossec.log
2024/06/28 09:02:18 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2024/06/28 09:02:19 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:19 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:29 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:39 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:49 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:59 wazuh-remoted: WARNING: (1408): Invalid ID 002 for the source ip: '192.168.2.31' (name 'unknown').
2024/06/28 09:02:59 wazuh-authd: INFO: New connection from 192.168.2.31
2024/06/28 09:02:59 wazuh-authd: INFO: Received request for a new agent (ama) from: 192.168.2.31
2024/06/28 09:02:59 wazuh-authd: WARNING: Duplicate name 'ama', rejecting enrollment. Agent '004' can't be replaced since it is not disconnected.
```

Added automatic replacement in 1 min:
```xml
<force>
     <enabled>yes</enabled>
     <disconnected_time enabled="yes">1m</disconnected_time>
     <after_registration_time>1m</after_registration_time>
     <key_mismatch>yes</key_mismatch>
</force>
```
Disconected the ama agent and let the manager replace it:
```
2024/06/28 09:16:20 wazuh-authd: INFO: New connection from 192.168.2.31
2024/06/28 09:16:20 wazuh-authd: INFO: Received request for a new agent (ama) from: 192.168.2.31
2024/06/28 09:16:20 wazuh-authd: INFO: Duplicate name. Removing old agent 'ama' (id '004').
2024/06/28 09:16:20 wazuh-authd: INFO: Agent key generated for 'ama' (requested by any)
```

manage_agents:
```
# /var/ossec/bin/manage_agents -l

Available agents:
   ID: 001, Name: ubuntu, IP: any
   ID: 003, Name: suse, IP: any
   ID: 005, Name: ama, IP: any
```

API:

<details>
<summary>response.json</summary>

```json
{
  "data": {
    "affected_items": [
      {
        "os": {
          "arch": "x86_64",
          "codename": "Focal Fossa",
          "major": "20",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |wazuh-manager-master |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64",
          "version": "20.04.6 LTS"
        },
        "registerIP": "127.0.0.1",
        "name": "wazuh-manager-master",
        "group_config_status": "synced",
        "status_code": 0,
        "lastKeepAlive": "9999-12-31T23:59:59+00:00",
        "status": "active",
        "dateAdd": "2024-06-28T08:21:57+00:00",
        "node_name": "wazuh-1",
        "ip": "127.0.0.1",
        "manager": "wazuh-manager-master",
        "version": "Wazuh v4.7.5",
        "id": "000"
      },
      {
        "os": {
          "arch": "x86_64",
          "codename": "Focal Fossa",
          "major": "20",
          "minor": "04",
          "name": "Ubuntu",
          "platform": "ubuntu",
          "uname": "Linux |wazuh-agent-0 |5.4.0-169-generic |#187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 |x86_64",
          "version": "20.04.6 LTS"
        },
        "registerIP": "any",
        "name": "ubuntu",
        "group_config_status": "synced",
        "status_code": 0,
        "lastKeepAlive": "2024-06-28T09:17:43+00:00",
        "status": "active",
        "dateAdd": "2024-06-28T08:38:12+00:00",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "node_name": "wazuh-1",
        "group": [
          "default"
        ],
        "ip": "192.168.2.30",
        "manager": "wazuh-manager-master",
        "version": "Wazuh v4.7.5",
        "id": "001"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "15",
          "minor": "5",
          "name": "openSUSE Leap",
          "platform": "opensuse-leap",
          "uname": "Linux |wazuh-agent-2 |5.14.21-150500.55.65-default |#1 SMP PREEMPT_DYNAMIC Thu May 23 04:57:11 UTC 2024 (a46829d) |x86_64",
          "version": "15.5"
        },
        "registerIP": "any",
        "name": "suse",
        "group_config_status": "synced",
        "status_code": 0,
        "lastKeepAlive": "2024-06-28T09:17:44+00:00",
        "status": "active",
        "dateAdd": "2024-06-28T08:41:50+00:00",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "node_name": "wazuh-1",
        "group": [
          "default"
        ],
        "ip": "192.168.2.32",
        "manager": "wazuh-manager-master",
        "version": "Wazuh v4.7.5",
        "id": "003"
      },
      {
        "os": {
          "arch": "x86_64",
          "major": "7",
          "minor": "8",
          "name": "CentOS Linux",
          "platform": "centos",
          "uname": "Linux |wazuh-agent-1 |3.10.0-1127.el7.x86_64 |#1 SMP Tue Mar 31 23:36:51 UTC 2020 |x86_64",
          "version": "7.8"
        },
        "registerIP": "any",
        "name": "ama",
        "group_config_status": "synced",
        "status_code": 0,
        "lastKeepAlive": "2024-06-28T09:17:40+00:00",
        "status": "active",
        "dateAdd": "2024-06-28T09:16:20+00:00",
        "mergedSum": "4a8724b20dee0124ff9656783c490c4e",
        "configSum": "ab73af41699f13fdd81903b5f23d8d00",
        "node_name": "wazuh-1",
        "group": [
          "default"
        ],
        "ip": "192.168.2.31",
        "manager": "wazuh-manager-master",
        "version": "Wazuh v4.7.5",
        "id": "005"
      }
    ],
    "total_affected_items": 4,
    "total_failed_items": 0,
    "failed_items": []
  },
  "message": "All selected agents information was returned",
  "error": 0
}
```

</details>

🟢 **Both methods correctly lists the agents**

## Conclusion
Everything worked as expected

**Comment by JcabreraC** [comment] 2024-06-28 12:04
This issue was reported by a community user, but we have no additional evidence to support it. Since we have been unable to replicate the bug, I am closing this issue for now.

If we receive more detailed information or are able to reproduce the bug, we will reopen the issue.

**Closed by JcabreraC** 2024-06-28 12:04 UTC
Labels: type/bug, module/api, reporter/community, type/research, level/task
