### ISSUE TITLE
Failing to install Windows agent using CLI mechanism

### ISSUE THREAD

**Issue by srikwit** [wazuh/wazuh#1017] opened 2018-07-30 08:19 UTC
Dear Team,

I am trying to install my Wazuh agent using the CLI options mentioned at : 
https://documentation.wazuh.com/3.x/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html

wazuh-agent-3.4.0-1.msi /q works for me as it writes new files into the default directory with the latest timestamp.

However, when I try to use the ADDRESS or the AUTHD options I am unable to see the changes in my ossec.conf or even observe a network traffic towards my auth server.

I am running the agent with administrator privileges and am unable to see any significant error messages in the client installer log.

Kindly suggest where I am going wrong.

**Comment by BraulioV** [comment] 2018-07-30 17:14
Hi @srikwit,

which Windows version are you using? Maybe there's a problem with `agent-auth` and the SSL version that is running in Windows. By default, the manager uses TLSv1.2, so if the agent uses an older version of TLS, it the registration process may fail.

This error happens in Windows 7 and older. If this is your case, you can run in the manager `ossec-authd` with this parameter:

```shellsession
# /var/ossec/bin/ossec-authd -a
```

This will auto-negotiate the best TLS version and register the agent with older versions of TLS. More details here: https://documentation.wazuh.com/current/user-manual/reference/daemons/ossec-authd.html.

After that, you can try again to install the agent using the `ADDRESS` and `AUTHD` parameters. 

Hope it helps.

Regards,
Braulio.

**Comment by srikwit** [comment] 2018-07-30 23:09
Hi @BraulioV ,

My Operating system version is Windows 10.0.17134.

I have found a bug in agent-auth now while testing your recommendation.

When agent-auth runs from a non-administrator console it will still confirm that a valid key has been created although no client.keys file is actually written to disk. An agent does gets registered at the server end but the client will lack the keys file.

The original issue however still remains with the wazuh agent installer. As now I can confirm that the agent-auth executable can successfully negotiate the key exchange with my server when run from an administrator console so it is not a bug in the TLS implementation.

Regards,
Srikanth

**Comment by srikwit** [comment] 2018-07-31 12:54
Hi @BraulioV , kindly disregard that bug, it was caused because of my mistake of running the agent-auth with two different current working directories.

**Comment by vikman90** [comment] 2018-08-23 12:11
Hi @srikwit,

Happy to know you found the cause of this problem.
Let me close this issue.

Feel free to reopen it or open a new issue if you have any further question.
Best regards.

**Closed by vikman90** 2018-08-23 12:11 UTC
Labels: packages
