### ISSUE TITLE
Negation of srcip and dstip with `!` is not working

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh#17595] opened 2023-06-15 14:31 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.4-1 | Wazuh server | Manager | Packages | Ubuntu 22.04.2 LTS |

# Description
When a user creates a custom rule, and uses the `dstip` or `srcip` fields, it should be possible to negate the expression with either `negate='yes'` or  `!`. However, the last one isn't working. 

# How to test it

Using the following example log 

```log
date=2018-12-29 time=14:50:47 logid="0000000013" type="traffic" subtype="forward" level="notice" vd="vdom1" eventtime=1540849847 srcip=10.1.100.22 srcport=46552 srcintf="dmz" srcintfrole="lan" dstip=172.16.200.55 dstport=80 dstintf="wan1" dstintfrole="wan" poluuid="c939f294-d6ff-51e8-3988-c628cfa2a346" sessionid=2979 proto=6 action="server-rst" policyid=1 policytype="policy" service="HTTP" dstcountry="Reserved" srccountry="Reserved" trandisp="snat" transip=172.16.200.6 transport=46552 duration=0 sentbyte=296 rcvdbyte=152 sentpkt=4 rcvdpkt=3 appcat="unscanned" utmaction="reset" countips=1 devtype="Linux PC" devcategory="None" osname="Linux" osversion="Debian" mastersrcmac="00:0c:29:6c:43:21" srcmac="00:0c:29:6c:43:21" srcserver=0 utmref=65522-42
```

That by default triggers the rule `81618` (level 1) with the decoded fields
-  dstip: '172.16.200.55'
-  srcip: '10.1.100.22'

Create custom rules and test against the log. 

## Case 1 

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <dstip>172.16.200.55</dstip>
</rule>
```

As expected, the custom rule is triggered

## Case 2 

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <dstip negate='yes'>172.16.200.55</dstip>
</rule>
```

As expected, the custom rule is not triggered

## Case 3 

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <dstip>!172.16.200.55</dstip>
</rule>
```

### Expected result
The custom rule should not be triggered

### Actual result
The custom rule is triggered

## Case 4 

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <srcip>10.1.100.22</srcip>
</rule>
```

As expected, the custom rule is triggered

## Case 5

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <srcip negate='yes'>10.1.100.22</srcip>
</rule>
```

As expected, the custom rule is not triggered

## Case 6

```
<rule id="100002" level="5">
    <if_sid>81618</if_sid>
    <description>Testing the rule</description>
    <srcip>!10.1.100.22</srcip>
</rule>
```

### Expected result
The custom rule should not be triggered

### Actual result
The custom rule is triggered

**Comment by JcabreraC** [comment] 2024-07-12 09:47
Thank you for your report. This issue is a duplicate of #16675, as previously noted.

This issue will not be addressed in Analysisd. However, we are currently developing a new analysis engine that significantly changes the way rules are created.

For more information about the new engine, please refer to issue #23577.

**Closed by JcabreraC** 2024-07-12 09:47 UTC
