### ISSUE TITLE
Feature request: add a configurable and persistent storage for agent unset messages

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh#23446] opened 2024-05-15 14:43 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| All | Logcollector | Agent | Packages/Sources | OS version |

## Description

An user has made a feature request at #23377.

It happens that currently the agent has only two different mechanisms to avoid missing logs with **logcollector**
- The `only_future_events` option to keep reading files since the last timestamp when the agent was running
- The leaky bucket, that holds in memory the events until the connection is re-established

The second in particular has some drawbacks, for example:
- A restart of the agent during the disconnection period causes the loss of all events in memory
- The disconnection period could be long, and the buffer insufficient

That's why @protocolpaladin proposed a configurable log retention threshold with high capacity (GBs) to store the logs until they can be sent to the manager.

## DoD

- [ ] The corresponding team analyzes the feature request
- [ ] The feature is included in the backlog or rejected

**Comment by vikman90** [comment] 2024-05-17 10:08
@pereyra-m this issue seems to be a duplicate of https://github.com/wazuh/wazuh/issues/15294.

**Closed by vikman90** 2024-05-17 10:08 UTC
Labels: type/enhancement
