### ISSUE TITLE
Analyze and investigate cluster structure and configuration to develop cluster by default

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh#7143] opened 2021-01-12 09:33 UTC
Hello team,

We should study our current cluster structure in depth to properly design towards making Wazuh manager a cluster by default.

Any shenanigans and possible problems should be properly evaluated and a solution proposed. As a product of this issue we should have a clear design roadmap for https://github.com/wazuh/wazuh/issues/7108.

Best regards,

David J. Iglesias

**Comment by Selutario** [comment] 2022-05-05 13:04
## Issue update
### Loopback

I've done some tests using `localhost` hostname in the cluster config:
```XML
  <cluster>
    <name>wazuh</name>
        <node_name>master-node</node_name>
        <node_type>master</node_type>
        <key>9d273b53510fef702b54a92e9cffc82e</key>
        <port>1516</port>
        <bind_addr>localhost</bind_addr>
        <nodes>
            <node>127.0.0.1</node>
        </nodes>
        <hidden>no</hidden>
        <disabled>no</disabled>
     </cluster>
```

However, it seems to be resolving IPv6 instead of IPv4, so the following error is raised when starting the cluster. The problem is probably related to using docker since IPv6 is not enabled by default in it, but 127.0.0.1 should be used instead of localhost to make sure it always binds to IPv4 loopback:
```
/var/ossec/bin/wazuh-clusterd -f
Starting cluster in foreground (pid: 3814)
2022/05/05 06:40:38 INFO: [Local Server] [Main] Serving on /var/ossec/queue/cluster/c-internal.sock
2022/05/05 06:40:38 ERROR: [Master] [Main] Could not start master: [Errno 99] error while attempting to bind on address ('::1', 1516, 0, 0): cannot assign requested address
2022/05/05 06:40:38 INFO: [Cluster] [Main] SIGINT received. Bye!
```

### Update framework
In the framework there are some references to the check_cluster status() function (which checks the status of the `disabled` tag, which will be removed):
https://github.com/wazuh/wazuh/blob/22b0fcb7190057d3116b1bdb8ef75fe19d9b0ffb/framework/wazuh/core/cluster/dapi/dapi.py#L142

Similarly, it is necessary to remove any code where it is checked whether the cluster is disabled in the configuration:
https://github.com/wazuh/wazuh/blob/22b0fcb7190057d3116b1bdb8ef75fe19d9b0ffb/framework/wazuh/agent.py#L23-L24

It is also necessary to know what happens with the manager endpoints from now on and if the Manager actions should be removed and only the cluster ones should be left.
https://github.com/wazuh/wazuh/blob/22b0fcb7190057d3116b1bdb8ef75fe19d9b0ffb/framework/wazuh/manager.py#L43-L44

**Comment by Selutario** [comment] 2022-05-10 11:05
## Status update

The following issues were opened:
- #13320
- #13336
- #13351
- #13353
- #13382
- #13408
- #13410
- https://github.com/wazuh/wazuh-packages/issues/1526
- https://github.com/wazuh/wazuh-puppet/issues/491
- https://github.com/wazuh/wazuh-ansible/issues/766

An epic issue for documentation was also opened:
- https://github.com/wazuh/wazuh-documentation/issues/5212
- https://github.com/wazuh/wazuh-documentation/issues/5214
- https://github.com/wazuh/wazuh-documentation/issues/5215
- https://github.com/wazuh/wazuh-documentation/issues/5216

**Closed** 2022-05-17 08:13 UTC
Labels: enhancement, cluster
