### ISSUE TITLE
Investigate if it's possible to relaunch the API integration tests after an environment failure

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh#9924] opened 2021-08-27 09:08 UTC
|Wazuh Component|
|---|
|API integration tests|

Right now, when the environment of an API integration test fails at the start or is not deployed correctly, the test fails automatically. Even though this kind of failure doesn't happen frequently, they make the testing process troublesome, because they force us to relaunch all of the API integration tests just for an environment failure on one of them.

The object of this issue is to investigate how we could relaunch the failed test if there's an error of this kind. As a first approximation, I would advise starting researching if this behavior could be developed in `api/test/integration/conftest.py`.

**Comment by mcarmona99** [comment] 2021-09-01 16:40
## Issue update

Right now, these are the steps followed in the conftest to set up the Docker environment needed for each API integration tests:


```
- Change RBAC mode.
- Create a temporary folder.
- Copy base configurations to the tmp folder
- Copy specific configurations to the tmp folder
- Build all the Docker containers:
	- Get Wazuh branch
	- While retries < max retries    and    build or start returned an error
		- Build the Docker environment with the branch as argument
		- Start the Docker environment
		- Delay
- While retries < max retries     and     managers or agents not healthy:
	- Check health of containers with managers installed
	- Check health of containers with agents installed
	- Delay
- Pass the test
- Clean temporary folder
- Save logs if there are failed tests
- Stop the Docker environmnet
```

These steps are implemented in the `api_test` function that is a pytest fixture. Each test executes this function before been passed.

A possible solution may be checking if the tests returned `ERROR` instead of `PASSED` or `FAILED`. We have seen that an `ERROR` means an environment failure. 

> Error is reserved for a failure in a fixture.

More information here: https://stackoverflow.com/questions/21513718/pytest-error-vs-fail


The `api_test` function must relaunch the Docker environment if one of the test returned ERROR.

We can check the status code of the test session by using the variable `request.session.exitstatus` in `test_api`. I have implemented a solution following this and the exitstatus is always 0 so it seems to be a variable that is set after the test finishes.

This solution won't work to solve this issue, I keep investigating `pytest_report_teststatus` as hooks seem to be a possible solution.

```
<TestReport 'test_agent_GET_endpoints.tavern.yaml::GET /agents' when='setup' outcome='passed'>
<TestReport 'test_agent_GET_endpoints.tavern.yaml::GET /agents' when='call' outcome='failed'>
<TestReport 'test_agent_GET_endpoints.tavern.yaml::GET /agents' when='teardown' outcome='passed'>
```

These are the reports obtained using `pytest_report_teststatus` (one for each test case).

We can implement a solution by checking if the `outcome` is `failed` in the `setup` step.

**Comment by mcarmona99** [comment] 2021-09-06 11:23
## Issue update


After investigating posible fixes, I have seen that the only problem that would result in an error could be an exception in the docker environment creation.

This possible exception was avoided with the fixes included in this issue: https://github.com/wazuh/wazuh/issues/8722. That issue solved the error:

```
E subprocess.CalledProcessError: Command 'docker inspect env_wazuh-master_1 -f '{{json .State.Health.Status}}'' returned non-zero exit status 1.
```

Another problem that used to appear in our API integration test environment was this one:

´´´
E   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=55000): Max retries exceeded with url: /security/user/authenticate (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))
´´´

This was also fixed in the PR https://github.com/wazuh/wazuh/pull/9399 with changes to healthchecks.


After this problems, I have not seen new errors regarding the API integration test environment. Therefore, I propose to close this issue and reopen it in case there are new errors discovered in local or in our external tool.

If this issue is reopened, please feel free to add new comments showing error outputs and all the possible extra information.

**Closed** 2021-09-08 08:09 UTC
Labels: enhancement, qa, API
