### ISSUE TITLE
Connection Errors present in agent logs after upgrade

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh#21453] opened 2024-01-16 14:09 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.8.0-alpha2 | Wazuh component | Manager | Packages | Linux |

## Description

During testing for `4.8.0 Alpha 2` https://github.com/wazuh/wazuh/issues/21390 it was detected some Agents presented connection errors in in the logs and failed the `upgrade_agent_test.py::test_check_log_errors` test. 

- The errors were present in Red Hat 6, Debian Bookworm and Debian Bullseye.
   - On Debian Bookworm and Debian Bullseye, manager tests also failed, and might be related to the agent connection error.

## Agent Evidence

- Example from `Red Hat 6` Agent

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.11.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /upgrade_agent
collecting ... collected 11 items

upgrade_agent_test.py::test_check_version PASSED                         [  9%]
upgrade_agent_test.py::test_check_process_modulesd PASSED                [ 18%]
upgrade_agent_test.py::test_check_process_logcollector PASSED            [ 27%]
upgrade_agent_test.py::test_check_process_syscheckd PASSED               [ 36%]
upgrade_agent_test.py::test_check_process_agentd PASSED                  [ 45%]
upgrade_agent_test.py::test_check_process_execd PASSED                   [ 54%]
upgrade_agent_test.py::test_check_log_errors FAILED                      [ 63%]
upgrade_agent_test.py::test_check_system_ossec_conf PASSED               [ 72%]
upgrade_agent_test.py::test_check_ossec_conf PASSED                      [ 81%]
upgrade_agent_test.py::test_check_client_keys_conf PASSED                [ 90%]
upgrade_agent_test.py::test_check_local_internal_options_conf PASSED     [100%]

=================================== FAILURES ===================================
____________________________ test_check_log_errors _____________________________
upgrade_agent_test.py:149: in test_check_log_errors
    assert init_time_date <= line_log_time_date <= end_time_date, assert_description['error']['exception_not_interval']
E   AssertionError: An error was found outside of upgrade interval
E   assert datetime.datetime(2024, 1, 12, 17, 46, 36) <= datetime.datetime(2024, 1, 12, 12, 47)
----------------------------- Captured stdout call -----------------------------
2024/01/12 12:47:00 wazuh-agentd: ERROR: (1137): Lost connection with manager. Setting lock.
2024/01/12 12:47:00 wazuh-agentd: INFO: Closing connection to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:00 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:00 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:47:01 wazuh-syscheckd: WARNING: Process locked due to agent is offline. Waiting for connection...
2024/01/12 12:47:10 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:10 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:47:20 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:20 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:47:30 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:30 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:47:40 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:40 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:47:40 wazuh-agentd: INFO: Requesting a key from server: 172.31.8.28
2024/01/12 12:47:40 wazuh-agentd: ERROR: (1208): Unable to connect to enrollment service at '[172.31.8.28]:1515'
2024/01/12 12:47:50 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '172.31.8.28'. Ensure that the manager version is 'v4.7.2' or higher.
2024/01/12 12:47:50 wazuh-agentd: WARNING: Unable to connect to any server.
2024/01/12 12:47:50 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:47:50 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:00 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:00 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:10 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:10 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:20 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:20 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:30 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:30 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:30 wazuh-agentd: INFO: Requesting a key from server: 172.31.8.28
2024/01/12 12:48:30 wazuh-agentd: ERROR: (1208): Unable to connect to enrollment service at '[172.31.8.28]:1515'
2024/01/12 12:48:40 wazuh-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '172.31.8.28'. Ensure that the manager version is 'v4.7.2' or higher.
2024/01/12 12:48:40 wazuh-agentd: WARNING: Unable to connect to any server.
2024/01/12 12:48:40 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:40 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:48:50 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:48:50 wazuh-agentd: ERROR: (1216): Unable to connect to '[172.31.8.28]:1514/tcp': 'Connection refused'.
2024/01/12 12:49:00 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:49:00 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.8.28]:1514/tcp).
2024/01/12 12:49:00 wazuh-agentd: INFO: Server responded. Releasing lock.
2024/01/12 12:49:01 wazuh-syscheckd: INFO: Agent is now online. Process unlocked, continuing...
2024/01/12 12:49:43 wazuh-modulesd:syscollector: INFO: Stop received for Syscollector.
2024/01/12 12:49:43 wazuh-modulesd:syscollector: INFO: Module finished.
2024/01/12 12:49:43 wazuh-logcollector: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/01/12 12:49:43 wazuh-syscheckd: INFO: (1756): Shutdown received. Releasing resources.
2024/01/12 12:49:43 wazuh-syscheckd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/01/12 12:49:43 wazuh-agentd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/01/12 12:49:43 wazuh-execd: INFO: (1314): Shutdown received. Deleting responses.
2024/01/12 12:49:43 wazuh-execd: INFO: (1225): SIGNAL [(15)-(Terminated)] Received. Exit Cleaning...
2024/01/12 12:49:45 wazuh-execd: INFO: Started (pid: 1833).
2024/01/12 12:49:46 wazuh-agentd: INFO: (1410): Reading authentication keys file.
2024/01/12 12:49:46 wazuh-agentd: INFO: Using notify time: 10 and max time to reconnect: 60
2024/01/12 12:49:46 wazuh-agentd: INFO: Version detected -> Linux |ip-172-31-46-155.ec2.internal |5.10.201-191.748.amzn2.x86_64 |#1 SMP Mon Nov 27 18:28:14 UTC 2023 |x86_64 [Red Hat Enterprise Linux Server|rhel: 6.10] - Wazuh v4.8.0
2024/01/12 12:49:46 wazuh-agentd: INFO: Started (pid: 1845).
2024/01/12 12:49:46 wazuh-agentd: INFO: Using AES as encryption method.
2024/01/12 12:49:46 wazuh-agentd: INFO: Trying to connect to server ([172.31.8.28]:1514/tcp).
2024/01/12 12:49:46 wazuh-agentd: INFO: (4102): Connected to the server ([172.31.8.28]:1514/tcp).
2024/01/12 12:49:47 wazuh-syscheckd: INFO: Started (pid: 1860).
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/bin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/boot', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/etc', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/sbin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/usr/bin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6003): Monitoring path: '/usr/sbin', with options 'size | permissions | owner | group | mtime | inode | hash_md5 | hash_sha1 | hash_sha256 | scheduled'.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/mtab'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/hosts.deny'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/mail/statistics'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/random-seed'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/random.seed'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/adjtime'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/httpd/logs'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/utmpx'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/wtmpx'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/cups/certs'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/dumpdates'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6206): Ignore 'file' entry '/etc/svc/volatile'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6207): Ignore 'file' sregex '.log$|.swp$'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6004): No diff for file: '/etc/ssl/private.key'
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6000): Starting daemon...
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6010): File integrity monitoring scan frequency: 43200 seconds
2024/01/12 12:49:47 rootcheck: INFO: Starting rootcheck scan.
2024/01/12 12:49:47 wazuh-syscheckd: INFO: (6008): File integrity monitoring scan started.
2024/01/12 12:49:48 wazuh-logcollector: INFO: Monitoring output of command(360): df -P
2024/01/12 12:49:48 wazuh-logcollector: INFO: Monitoring full output of command(360): netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d

2024/01/12 12:49:48 wazuh-logcollector: INFO: Monitoring full output of command(360): last -n 20
2024/01/12 12:49:48 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2024/01/12 12:49:48 wazuh-logcollector: INFO: Started (pid: 1875).
2024/01/12 12:49:49 wazuh-modulesd: INFO: Started (pid: 1893).
2024/01/12 12:49:49 wazuh-modulesd:control: INFO: Starting control thread.
2024/01/12 12:49:49 wazuh-modulesd:agent-upgrade: INFO: (8153): Module Agent Upgrade started.
2024/01/12 12:49:49 sca: INFO: Module started.
2024/01/12 12:49:49 sca: INFO: Loaded policy '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2024/01/12 12:49:49 sca: INFO: Starting Security Configuration Assessment scan.
2024/01/12 12:49:49 wazuh-modulesd:osquery: INFO: Module disabled. Exiting...
2024/01/12 12:49:49 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2024/01/12 12:49:49 wazuh-modulesd:syscollector: INFO: Module started.
2024/01/12 12:49:49 wazuh-modulesd:syscollector: INFO: Starting evaluation.
2024/01/12 12:49:50 sca: INFO: Starting evaluation of policy: '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2024/01/12 12:49:50 wazuh-modulesd:syscollector: INFO: Evaluation finished.
2024/01/12 12:49:50 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2024/01/12 12:49:50 wazuh-syscheckd: INFO: FIM sync module started.
2024/01/12 12:49:55 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_rhel6_linux.yml'
2024/01/12 12:49:55 sca: INFO: Security Configuration Assessment scan finished. Duration: 6 seconds.
2024/01/12 12:50:01 rootcheck: INFO: Ending rootcheck scan.
['UPGRADE_INIT=20240112174636', 'UPGRADE_END=20240112174908']
=========================== short test summary info ============================
FAILED upgrade_agent_test.py::test_check_log_errors - AssertionError: An erro...
========================= 1 failed, 10 passed in 0.09s =========================
```

- On Debian Bookworm and  Bullseye tests also failed on the manager

   - Debian Bookworm
```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.11.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /upgrade_manager
collecting ... collected 19 items

upgrade_manager_test.py::test_check_version PASSED                       [  5%]
upgrade_manager_test.py::test_check_process_clusterd PASSED              [ 10%]
upgrade_manager_test.py::test_check_process_modulesd PASSED              [ 15%]
upgrade_manager_test.py::test_check_process_monitord PASSED              [ 21%]
upgrade_manager_test.py::test_check_process_logcollector PASSED          [ 26%]
upgrade_manager_test.py::test_check_process_remoted PASSED               [ 31%]
upgrade_manager_test.py::test_check_process_syscheckd PASSED             [ 36%]
upgrade_manager_test.py::test_check_process_analysisd PASSED             [ 42%]
upgrade_manager_test.py::test_check_process_maild PASSED                 [ 47%]
upgrade_manager_test.py::test_check_process_execd PASSED                 [ 52%]
upgrade_manager_test.py::test_check_process_wazuhdb PASSED               [ 57%]
upgrade_manager_test.py::test_check_log_errors PASSED                    [ 63%]
upgrade_manager_test.py::test_check_system_ossec_conf FAILED             [ 68%]
upgrade_manager_test.py::test_check_ossec_conf FAILED                    [ 73%]
upgrade_manager_test.py::test_check_client_keys_conf FAILED              [ 78%]
upgrade_manager_test.py::test_check_local_internal_options_conf FAILED   [ 84%]
upgrade_manager_test.py::test_check_local_decoder_conf FAILED            [ 89%]
upgrade_manager_test.py::test_check_local_rules_conf FAILED              [ 94%]
upgrade_manager_test.py::test_check_agent_conf FAILED                    [100%]

=================================== FAILURES ===================================
_________________________ test_check_system_ossec_conf _________________________
upgrade_manager_test.py:184: in test_check_system_ossec_conf
    assert system in f.read(), assert_description['files']['ossec_conf_OS_not_detected'] + ". It was expected to read {} in ossec.conf".format(system)
E   AssertionError: Could not read your OS in /var/ossec/etc/ossec.conf. It was expected to read debian 12 in ossec.conf
E   assert 'debian 12' in '<!--\n  Wazuh - Manager - Default configuration for debian 8\n  More info at: https://documentation.wazuh.com\n  Mail...NODE_IP</node>\n    </nodes>\n    <hidden>no</hidden>\n    <disabled>yes</disabled>\n  </cluster>\n\n</ossec_config>\n'
E    +  where '<!--\n  Wazuh - Manager - Default configuration for debian 8\n  More info at: https://documentation.wazuh.com\n  Mail...NODE_IP</node>\n    </nodes>\n    <hidden>no</hidden>\n    <disabled>yes</disabled>\n  </cluster>\n\n</ossec_config>\n' = <built-in method read of _io.TextIOWrapper object at 0x7fcb2dec22b0>()
E    +    where <built-in method read of _io.TextIOWrapper object at 0x7fcb2dec22b0> = <_io.TextIOWrapper name='/var/ossec/etc/ossec.conf' mode='r' encoding='UTF-8'>.read
____________________________ test_check_ossec_conf _____________________________
upgrade_manager_test.py:194: in test_check_ossec_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['ossec_conf'], assert_description['files']['check_ossec_conf_checksum']
E   AssertionError: The checksum file don't match with the checksum generated before upgrading
E   assert 'f7ccbc3ee422...1469338d657e2' == '51da5287892a...6159514157593'
E     - 51da5287892a8f065609a16bfd4e0674019f5c214719564f2d86159514157593
E     + f7ccbc3ee422bea8d87d1d47b6daafaf40c62d3e0046fa999321469338d657e2
_________________________ test_check_client_keys_conf __________________________
upgrade_manager_test.py:203: in test_check_client_keys_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['client_keys'], assert_description['files']['check_client_keys_checksum']
E   AssertionError: The client keys file don't match with the checksum generated before upgrading
E   assert 'e3b0c44298fc...5991b7852b855' == '22869fe9ab6c...e44690591c62e'
E     - 22869fe9ab6c7e041ea752b143ae604b7eb8381e20f5bd06167e44690591c62e
E     + e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
____________________ test_check_local_internal_options_conf ____________________
upgrade_manager_test.py:212: in test_check_local_internal_options_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['local_internal_options'], assert_description['files']['check_local_internal_options_checksum']
E   AssertionError: The local_internal_options checksum file is not the correct one
E   assert '73252a6f47ff...cf0b0ac77133f' == '5f21fe0053b6...2868d8850bcad'
E     - 5f21fe0053b6a96aacf06b5e54ea41b854f8c7877c3dbc404ad2868d8850bcad
E     + 73252a6f47fff93d8ce62ca70a8f9196a216d5e09dc2228758fcf0b0ac77133f
________________________ test_check_local_decoder_conf _________________________
upgrade_manager_test.py:221: in test_check_local_decoder_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['local_decoder'], assert_description['files']['check_local_decoder_checksum']
E   AssertionError: The local_decoder checksum file is not the correct one
E   assert '21f5e1ff2ea0...52d9c2a1c5c13' == '0563b4dad0fe...1f938c5efb584'
E     - 0563b4dad0fea835e7e2204fe51be3ea17b30f214a44442e3a81f938c5efb584
E     + 21f5e1ff2ea096f2b1b6acdc1fc25bcac46734614b253f6ad1352d9c2a1c5c13
_________________________ test_check_local_rules_conf __________________________
upgrade_manager_test.py:230: in test_check_local_rules_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['local_rules'], assert_description['files']['check_local_rules_checksum']
E   AssertionError: The local_rules checksum file is not the correct one
E   assert '991dc926bd2e...2ac33620425f4' == 'c06afd0f52a4...9c764ad8a0ae6'
E     - c06afd0f52a4834ff0e966e0ea659eb27c034b50016314b7b229c764ad8a0ae6
E     + 991dc926bd2e3aec88bd79be1c8b458777f64f489b3e6524e682ac33620425f4
____________________________ test_check_agent_conf _____________________________
upgrade_manager_test.py:239: in test_check_agent_conf
    assert hashlib.sha256(conf_file_data).hexdigest() == checksums['agent_conf'], assert_description['files']['check_agent_conf_checksum']
E   AssertionError: The agent_conf checksum file is not the correct one
E   assert 'd76908d51018...ed66f1af47ed0' == '93ca61d22ff3...a8e42f382c7b6'
E     - 93ca61d22ff3a356a1eee94485060d5d4b485636bca4cb0c91aa8e42f382c7b6
E     + d76908d51018ec72afc1a7e17fbc3971c6a812446fd930fdba5ed66f1af47ed0
=============================== warnings summary ===============================
upgrade_manager_test.py:127
  /upgrade_manager/upgrade_manager_test.py:127: DeprecationWarning: invalid escape sequence \w
    daemonRegex = '\w+-\w+:'

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED upgrade_manager_test.py::test_check_system_ossec_conf - AssertionError...
FAILED upgrade_manager_test.py::test_check_ossec_conf - AssertionError: The c...
FAILED upgrade_manager_test.py::test_check_client_keys_conf - AssertionError:...
FAILED upgrade_manager_test.py::test_check_local_internal_options_conf - Asse...
FAILED upgrade_manager_test.py::test_check_local_decoder_conf - AssertionErro...
FAILED upgrade_manager_test.py::test_check_local_rules_conf - AssertionError:...
FAILED upgrade_manager_test.py::test_check_agent_conf - AssertionError: The a...
=================== 7 failed, 12 passed, 1 warning in 0.11s ====================
```

Further research is needed

**Comment by LucioDonda** [comment] 2024-01-25 16:54
Comment for each OS
* Red Hat 6 Agent:
The test that failed was _test_check_log_errors_ here the agent logs are checked for the presence of lines with the keyword **ERROR**, but not all the matches will trigger the failure because, while the upgrade is in process, the are some disconnections among other messages that are bypassed. This during a window of time matching the start and the end of the upgrade. In the red hat 6 case this is happening but the agent holds a different UTC.

* Debian Bookworm:

* Debian Bullseye:

**Comment by LucioDonda** [comment] 2024-01-29 20:17
After some help from the QA team, I was only able to replicate the issue regarding red hat 6 ([new job.](https://ci.wazuh.info/blue/organizations/jenkins/Test_upgrade/detail/Test_upgrade/132927/pipeline/232/))

As stated in the above comment, the agent is comparing timestamps in different time zones.
This can be fixed in two different ways.
* Using UTC in both cases ([playbook's command line date](https://github.com/wazuh/wazuh-jenkins/blob/750e25b5b81ad66cbebd6ccfb3dae96e7c6f094d/quality/deployments/ansible/conf/wazuh_packages_install.yaml#L517) and Python [strptime](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes) from the log file).

* using UNIX epoch time in both cases. This could simplify the comparison [here](https://github.com/wazuh/wazuh-jenkins/blob/750e25b5b81ad66cbebd6ccfb3dae96e7c6f094d/quality/tests/generic/03-upgrade/linux/test/upgrade_agent_test.py#L143:L144):

```
init_time_date = datetime.datetime.strptime(init_time_string, "%Y%m%d%H%M%S")
end_time_date = datetime.datetime.strptime(end_time_string, "%Y%m%d%H%M%S") + datetime.timedelta(minutes=4)

line_log_time_string = " ".join(line.split(" ")[0:2])
line_log_time_date = datetime.datetime.strptime(line_log_time_string, "%Y/%m/%d %H:%M:%S")

assert init_time_date <= line_log_time_date <= end_time_date, assert_description['error']['exception_not_interval']
```

Besides that I wasn't able to find the root causes of these issues because this test has been running for some time, and AFAIK this is the first time it triggers this kind of error. Another possible solution could be to add an additional step to the playbook in order to unify timezones for all the instances involved.

rerun jobs:
[Debian bookworm](https://ci.wazuh.info/blue/organizations/jenkins/Test_upgrade/detail/Test_upgrade/132928/pipeline/211/) marks and additional failure due to another reason but the tests finish successfully.
[Debian bullseye.](https://ci.wazuh.info/blue/organizations/jenkins/Test_upgrade/detail/Test_upgrade/132929/).

c.c. @cborla @Deblintrake09

**Comment by jnasselle** [comment] 2024-01-31 11:57
# Update

A new upgrade tier was launched since the original one expired https://ci.wazuh.info/job/Test_upgrade_tier/2170/

**Comment by davidjiglesias** [comment] 2024-02-02 08:36
LGTM

**Closed by davidjiglesias** 2024-02-02 08:36 UTC
Labels: type/bug, level/task, qa_known
