### ISSUE TITLE
Event values "serviceName" and "targetUserName" appear reversed in Wazuh Rule ID 60131

### ISSUE THREAD

**Issue by commradd** [wazuh/wazuh#4438] opened 2020-01-10 22:08 UTC
Wazuh version | Component | Install type
-- | -- | --
3.9.5-1 | logcollector | Agent

I've only tested this running the agent on Windows Server 2012 R2.

When the log event "description" is "Windows DC Logon Failure", the following appear reversed in Kibana:
data.win.event.serviceName
data.win.event.targetUserName

In other words, the "serviceName" shows the Username from the event log, and the "targetUserName" shows the service name from the event log.  They are backwards.

All other event "description" values produce the correct "serviceName" and "targetUserName".  While using Kibana in the Discovery window, and sorting by "description", "data.win.event.targetUserName" and "data.win.event.serviceName" the "targetUserName" and "serviceName" report correctly... **except** when the event includes a "description" value of "Windows DC Logon Failure".  Other "description" values produce the correct results.

Other specifics that are part of this event:
**data.win.system.channel: Security
data.win.system.severityValue: AUDIT_FAILURE
decoder.name: windows_eventchannel
event_type: ossec
event_id: 4,769
wazuh-rule.groups: windows,  windows_security, win_authentication_failed
wazuh-rule.id: 60131**

**Comment by Zenidd** [comment] 2020-01-14 10:26
Hello @commradd,

I need a bit more information to figure out what is happening. That's why I would like you to generate a 4769 event in your environment and then paste here the related archives.log entry and the related Wazuh UI screenshot.

*To archive all the incoming logs into `archives.log` file, you should enable the `<logall>yes</logall>` option in the manager `ossec.conf`. After enabling `<logall>` and restarting the manager, please, generate some windows 4769 ID events in the agent side, and try to find these events in the `achives.log` file. Paste here these events along with the Wazuh UI screenshots so we can adjust the error scope.

Greetings, JP Sáez

**Comment by commradd** [comment] 2020-01-15 19:00
2020 Jan 15 18:26:04 (Server-dc-2) 192.168.1.145->EventChannel {"win":{"system":{"providerName":"Microsoft-Windows-Security-Auditing","providerGuid":"{54849625-5478-4994-A5BA-3E3B0328C30D}","eventID":"4769","version":"0","level":"0","task":"14337","opcode":"0","keywords":"0x8010000000000000","systemTime":"2020-01-15T18:26:03.224071900Z","eventRecordID":"1045067319","processID":"472","threadID":"1108","channel":"Security","computer":"Server-DC-2.domain.com","severityValue":"AUDIT_FAILURE","message":"A Kerberos service ticket was requested."},"eventdata":{"targetUserName":"MACHINE-NAME$@DOMAIN.COM","targetDomainName":"DOMAIN.COM","serviceName":"jsmith_a","serviceSid":"S-1-0-0","ticketOptions":"0x40810000","ticketEncryptionType":"0xffffffff","ipAddress":"::ffff:192.168.1.165","ipPort":"51230","status":"0x1b","logonGuid":"{00000000-0000-0000-0000-000000000000}"}}}

**Comment by Zenidd** [comment] 2020-01-16 11:25
Hello again @commradd,

Thanks for the sample event. Anyway, the best scenario for troubleshooting this issue is tracking the same event in the Windows Event viewer, in the archives.log file, and in the Wazuh UI. This way we can compare and see where the fields get switched.

For the sake of solving this issue, could you paste the event here in its 3 different forms?

Sorry for the inconveniences and Greetings, JP Sáez

**Comment by commradd** [comment] 2020-01-16 18:53
So after looking at this event in the event viewer, I see that it's not Wazuh after all.  Windows either has a bug, or this is by design.  So my apologies for your time, I should have noticed this earlier. You can close this ticket.  Here's an event from Event Viewer that demonstrates this:

Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          1/16/2020 10:17:06 AM
Event ID:      4769
Task Category: Kerberos Service Ticket Operations
Level:         Information
Keywords:      Audit Failure
User:          N/A
Computer:      SERVER-DC-1.DOMAIN.COM
Description:
A Kerberos service ticket was requested.

Account Information:
	Account Name:		SQLDEV1$@DOMAIN.COM
	Account Domain:		DOMAIN.COM
	Logon GUID:		{00000000-0000-0000-0000-000000000000}

Service Information:
	Service Name:		jsmith_a
	Service ID:		NULL SID

Network Information:
	Client Address:		::ffff:192.168.1.102
	Client Port:		58041

Additional Information:
	Ticket Options:		0x40810000
	Ticket Encryption Type:	0xFFFFFFFF
	Failure Code:		0x1B
	Transited Services:	-

This event is generated every time access is requested to a resource such as a computer or a Windows service.  The service name indicates the resource to which access was requested.

This event can be correlated with Windows logon events by comparing the Logon GUID fields in each event.  The logon event occurs on the machine that was accessed, which is often a different machine than the domain controller which issued the service ticket.

Ticket options, encryption types, and failure codes are defined in RFC 4120.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" />
    <EventID>4769</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>14337</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8010000000000000</Keywords>
    <TimeCreated SystemTime="2020-01-16T18:17:06.867758400Z" />
    <EventRecordID>955613499</EventRecordID>
    <Correlation />
    <Execution ProcessID="480" ThreadID="6352" />
    <Channel>Security</Channel>
    <Computer>SERVER-DC-1.DOMAIN.COM</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="TargetUserName">SQLDEV1$@DOMAIN.COM</Data>
    <Data Name="TargetDomainName">DOMAIN.COM</Data>
    <Data Name="ServiceName">jsmith_a</Data>
    <Data Name="ServiceSid">S-1-0-0</Data>
    <Data Name="TicketOptions">0x40810000</Data>
    <Data Name="TicketEncryptionType">0xffffffff</Data>
    <Data Name="IpAddress">::ffff:192.168.1.102</Data>
    <Data Name="IpPort">58041</Data>
    <Data Name="Status">0x1b</Data>
    <Data Name="LogonGuid">{00000000-0000-0000-0000-000000000000}</Data>
    <Data Name="TransmittedServices">-</Data>
  </EventData>
</Event>

**Comment by commradd** [comment] 2020-01-16 18:56
So after looking at this event in the event viewer, I see that it's not Wazuh after all. Windows either has a bug, or this is by design. So my apologies for your time, I should have noticed this earlier. You can close this ticket. Here's an event from Event Viewer that demonstrates this... see attached.
[Event XML.txt](https://github.com/wazuh/wazuh/files/4073197/Event.XML.txt)

**Comment by Zenidd** [comment] 2020-01-17 09:59
Hello again @commradd,

> So after looking at this event in the event viewer, I see that it's not Wazuh after all. Windows either has a bug, or this is by design

Thanks for gathering all the needed data! I'm glad this time the ball is not in our court. 

> Windows either has a bug, or this is by design. So my apologies for your time, I should have noticed this earlier. You can close this ticket

Don't worry commradd, the community comes first for us. I've done some research and I found the information about the `serviceName` field on the [_Windows Security Monitoring: Scenarios and Patterns_](https://books.google.ru/books?id=nEJRDwAAQBAJ) book. Seems like this is by design:

![image](https://user-images.githubusercontent.com/14923294/72602319-5cab9080-3917-11ea-9315-905dbf340aff.png)

Such a non-descriptive name for a field. They could have called it `serviceRequester` or something similar.

I hope it helps. Let me know if I can close the issue.

Best regards, JP Sáez

**Comment by Zenidd** [comment] 2020-01-23 10:29
Hello again @commradd,

I'm closing the ticket. Let us know if you need anything else. 

On the other hand, for further questions, we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh). 

Best regards, JP Sáez

**Closed by Zenidd** 2020-01-23 10:29 UTC
Labels: Eventchannel, community, platform/windows
