### ISSUE TITLE
Wrong behavior detected during configuration module testing

### ISSUE THREAD

**Issue by roronoasins** [wazuh/wazuh#16110] opened 2023-02-07 17:52 UTC
## Description

After the team added configuration module changes to be able to configure the engine https://github.com/wazuh/wazuh/issues/15939, the following testing was performed:

- https://github.com/wazuh/wazuh-qa/issues/3888

## Bugs

The following issues were created after the above testing 

- https://github.com/wazuh/wazuh/issues/16106
- https://github.com/wazuh/wazuh/issues/16107
- https://github.com/wazuh/wazuh/issues/16108

**Comment by JcabreraC** [comment] 2024-05-31 08:15
Closed as all tasks have been completed.

## Using an API endpoint that is already used breaks that instance
Using an API endpoint that is already used breaks that instance #16106
The problem you're encountering is expected behavior due to a configuration conflict. When multiple instances attempt to use the same API socket, it leads to communication errors because the socket can only be accessed by one instance at a time.

Regarding the event socket not being deleted as expected, this might be a separate issue that requires further investigation. The socket should be removed when the engine terminates to prevent such conflicts. Please check the engine's shutdown process and ensure that it properly cleans up the socket.

## Infinite loop when defining negative thread number or a big amount of them
Fixed in https://github.com/wazuh/wazuh/issues/15717 (commit https://github.com/wazuh/wazuh/commit/97f51a50f21361451484fc00422a483a7e3f3a4f)

## The engine starts when providing a negative number as queue size
Fixed in https://github.com/wazuh/wazuh/issues/15717 (commit https://github.com/wazuh/wazuh/commit/97f51a50f21361451484fc00422a483a7e3f3a4f)

**Closed by JcabreraC** 2024-05-31 08:15 UTC
Labels: type/enhancement, reporter/qa, module/engine, level/task
