### ISSUE TITLE
Configuration is not the expected after upgrade from 4.3.7 to 4.6.0 for Fedora34

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh#17920] opened 2023-07-13 17:21 UTC
|Wazuh version|
|---|
| `4.6.0-pre-alpha1` | 

### Description

During https://github.com/wazuh/wazuh/issues/17720 it has been detected an error in the `upgrade_manager_test` and `upgrade_agent_test` regarding the discrepancied in the resulting configuration after the upgrade.

**Build**:  https://ci.wazuh.info/job/Test_upgrade/122073/

<details>

<summary> upgrade_agent_test </summary>

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.11.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /upgrade_agent
collecting ... collected 11 items

upgrade_agent_test.py::test_check_version PASSED                         [  9%]
upgrade_agent_test.py::test_check_process_modulesd PASSED                [ 18%]
upgrade_agent_test.py::test_check_process_logcollector PASSED            [ 27%]
upgrade_agent_test.py::test_check_process_syscheckd PASSED               [ 36%]
upgrade_agent_test.py::test_check_process_agentd PASSED                  [ 45%]
upgrade_agent_test.py::test_check_process_execd PASSED                   [ 54%]
upgrade_agent_test.py::test_check_log_errors PASSED                      [ 63%]
upgrade_agent_test.py::test_check_system_ossec_conf FAILED               [ 72%]
upgrade_agent_test.py::test_check_ossec_conf PASSED                      [ 81%]
upgrade_agent_test.py::test_check_client_keys_conf PASSED                [ 90%]
upgrade_agent_test.py::test_check_local_internal_options_conf PASSED     [100%]

=================================== FAILURES ===================================
_________________________ test_check_system_ossec_conf _________________________
upgrade_agent_test.py:181: in test_check_system_ossec_conf
    assert system in f.read(), assert_description['files']['ossec_conf_OS_not_detected'] + ". It was expected to read {} in ossec.conf".format(system)
E   AssertionError: Could not read your OS in /var/ossec/etc/ossec.conf. It was expected to read fedora 34 in ossec.conf
E   assert 'fedora 34' in '<!--\n  Wazuh - Agent - Default configuration for linux \n  More info at: https://documentation.wazuh.com\n  Mailing ...responses.log</location>\n  </localfile>\n\n</ossec_config>\n<!-- This commentary altered checksum of ossec.conf -->\n'
E    +  where '<!--\n  Wazuh - Agent - Default configuration for linux \n  More info at: https://documentation.wazuh.com\n  Mailing ...respo
```

</details>

<details>

<summary> upgrade_manager_test </summary>

```
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-5.4.1, py-1.11.0, pluggy-0.13.1 -- /usr/testing/bin/python3.8
cachedir: .pytest_cache
rootdir: /upgrade_manager
collecting ... collected 19 items

upgrade_manager_test.py::test_check_version PASSED                       [  5%]
upgrade_manager_test.py::test_check_process_clusterd PASSED              [ 10%]
upgrade_manager_test.py::test_check_process_modulesd PASSED              [ 15%]
upgrade_manager_test.py::test_check_process_monitord PASSED              [ 21%]
upgrade_manager_test.py::test_check_process_logcollector PASSED          [ 26%]
upgrade_manager_test.py::test_check_process_remoted PASSED               [ 31%]
upgrade_manager_test.py::test_check_process_syscheckd PASSED             [ 36%]
upgrade_manager_test.py::test_check_process_analysisd PASSED             [ 42%]
upgrade_manager_test.py::test_check_process_maild PASSED                 [ 47%]
upgrade_manager_test.py::test_check_process_execd PASSED                 [ 52%]
upgrade_manager_test.py::test_check_process_wazuhdb PASSED               [ 57%]
upgrade_manager_test.py::test_check_log_errors PASSED                    [ 63%]
upgrade_manager_test.py::test_check_system_ossec_conf FAILED             [ 68%]
upgrade_manager_test.py::test_check_ossec_conf PASSED                    [ 73%]
upgrade_manager_test.py::test_check_client_keys_conf PASSED              [ 78%]
upgrade_manager_test.py::test_check_local_internal_options_conf PASSED   [ 84%]
upgrade_manager_test.py::test_check_local_decoder_conf PASSED            [ 89%]
upgrade_manager_test.py::test_check_local_rules_conf PASSED              [ 94%]
upgrade_manager_test.py::test_check_agent_conf PASSED                    [100%]

=================================== FAILURES ===================================
_________________________ test_check_system_ossec_conf _________________________
upgrade_manager_test.py:184: in test_check_system_ossec_conf
    assert system in f.read(), assert_description['files']['ossec_conf_OS_not_detected'] + ". It was expected to read {} in ossec.conf".format(system)
E   AssertionError: Could not read your OS in /var/ossec/etc/ossec.conf. It was expected to read fedora 34 in ossec.conf
E   assert 'fedora 34' in '<!--\n  Wazuh - Manager - Default configuration for linux \n  More info at: https://documentation.wazuh.com\n  Mailin...responses.log</location>\n  </localfile>\n\n</ossec_config>\n<!-- This commentary altered checksum of ossec.conf -->\n'
E    +  where '<!--\n  Wazuh - Manager - Default configuration for linux \n  More info at: https://documentation.wazuh.com\n  Mailin...responses.log</location>\n  </localfile>\n\n</ossec_config>\n<!-- This commentary altered checksum of ossec.conf -->\n' = <built-in method read of _io.TextIOWrapper object at 0x7f7fe1598ad0>()
E    +    where <built-in method read of _io.TextIOWrapper object at 0x7f7fe1598ad0> = <_io.TextIOWrapper name='/var/ossec/etc/ossec.conf' mode='r' encoding='UTF-8'>.read
=============================== warnings summary ===============================
upgrade_manager_test.py:127
  /upgrade_manager/upgrade_manager_test.py:127: DeprecationWarning: invalid escape sequence \w
    daemonRegex = '\w+-\w+:'

-- Docs: https://docs.pytest.org/en/latest/warnings.html
=========================== short test summary info ============================
FAILED upgrade_manager_test.py::test_check_system_ossec_conf - AssertionError...
=================== 1 failed, 18 passed, 1 warning in 0.11s ====================
```

</details>

**Comment by jnasselle** [comment] 2023-07-24 14:37
Duplicate of https://github.com/wazuh/wazuh-packages/issues/1933. Closing this issue

**Closed by jnasselle** 2023-07-24 14:37 UTC
Labels: type/bug, level/task
