### ISSUE TITLE
Wazuh-modulesd single CPU 100% utilisation

### ISSUE THREAD

**Issue by lemrouch** [wazuh/wazuh#7192] opened 2021-01-14 09:56 UTC
Hi,
I have upgraded my WAZUH installation to wazuh-agent 4.0.3-1 amd64 debian package managed by puppet.
Configuration is mostly default, just SCA and active responses are disabled.

I can see wazuh-modulesd process eating 100% of one CPU core on two of my servers.
Strace and lsof told me the wazuh-modulesd is busy reading /proc/PID/net/route files.
The problem is that those servers are actually BGP routers and each of the route files has over 800k lines.

Would it be possible just to skip them?

**Comment by Molter73** [comment] 2021-01-14 11:18
Hi @lemrouch, 

This issue seems related to #4890 and #5479.

Looks like this problem was fixed on version 3.13 by #5548 and was somehow reintroduced on version 4.0 by #5548, I will run some tests to verify this.

Could you provide a little more information on what OS is your server running? Specifically Linux distribution and kernel versions would be great so we can more accurately reproduce the bug.

**Comment by lemrouch** [comment] 2021-01-14 11:20
It's Debian Buster with kernel 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux.

**Comment by lemrouch** [comment] 2021-01-14 11:26
I did not read the sources yet.
Maybe the read stops after it find default gateway but those routes have none at all.

**Comment by Molter73** [comment] 2021-01-14 12:26
I have not been able to reproduce this issue yet but not having a default gateway in the file `/proc/net/route` would certainly cause this high cpu usage. Can you check if there are any entries on the server with a gateway value of `00000000` in `/proc/net/route` by using this command?

```bash
vagrant@buster:~$ cat /proc/net/route | grep 00000000
eth0    0002000A        00000000        0001    0       0       0       00FFFFFF  0

eth1    0032A8C0        00000000        0001    0       0       0       00FFFFFF  0
```

You don't need to share the actual output since the destination field could be a public IP, just confirm if the command returns something. In the meantime, I'm trying to find a way to remove thos entries from the file to test it.

**Comment by lemrouch** [comment] 2021-01-14 12:38
Yes, I can see some lines with 00000000 in 3rd row.

**Comment by Molter73** [comment] 2021-01-14 15:09
Alright, I managed to reproduce this bug (in a smaller scale at least).

As the issues from my previous messages stated, whenever an agent tries to send a keep-alive message to the manager (every 10 seconds by default), the agent issues a message to the control module to retrieve either the default gateway or the first IP from the route table for each of the system's interfaces. In my test, I had a machine with 2 ethernet interfaces (`eth0` and `eth1`), removed all default entries by using `ip route del default`, causing the routing table to look as follows:

```bash
vagrant@buster:~$ sudo head -n 10 /proc/net/route
Iface   Destination     Gateway         Flags   RefCnt  Use     Metric  Mask     MTU      Window  IRTT
eth0    0002000A        00000000        0001    0       0       0       00FFFFFF 0
eth1    0032A8C0        00000000        0001    0       0       0       00FFFFFF 0
```

After that, I added around 65K entries to the routing table associated with eth0 with the following command:
```bash
root@buster:/home/vagrant# for i in {0..255}; do for j in {0..255}; do ip route add 10.$i.$j.0/24 via 10.0.2.15; done; done
```

This caused the entry associated with `eth1` to be pushed to the bottom of the routing table:
```bash
vagrant@buster:~$ sudo cat /proc/net/route | wc -l
65538
vagrant@buster:~$ sudo tail /proc/net/route
eth0    00F7FF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00F8FF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00F9FF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FAFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FBFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FCFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FDFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FEFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth0    00FFFF0A        0F02000A        0003    0       0       0       00FFFFFF 0
eth1    0032A8C0        00000000        0001    0       0       0       00FFFFFF 0
```

And `wazuh-modulesd` never has a CPU usage lower than 15% (this is nowhere near to 100% use on a core, but I'm also nowhere near 800K entries on the routing table).
![imagen](https://user-images.githubusercontent.com/20206636/104608916-c1144380-5682-11eb-885d-1bf19d728ed2.png)

We will need to look into this and try to find a better way to get this information for systems with large routing tables or implement a way to turn off this lookup on every keep-alive notification.

As for a workaround while we look into this, you probably won't be able to modify the routing table of a BGP router, but adding a default gateway to any of the interfaces should immediately stop `wazuh-modulesd` from hogging your CPU.

**Comment by lemrouch** [comment] 2021-01-18 10:14
Workaround with default gateway is working fine so far.
Thanks a lot.

**Comment by antoniomanuelfr** [comment] 2021-01-27 16:13
Hi !! 

@Molter73 and I have been investigating this issue for the last couple of days. 

It looks like the algorithm that searches into the routing table wasn't the cause of this particular problem. We have been trying to improve the efficiency of the algorithm but we saw the same result regardless of the solution: high CPU usage when there is a large number of entries in the routing table and there is not a default gateway. 

After doing some research, we have seen that the problem here looks like `ossec-logcollector` is requesting to the control module every second to get the IP address of the host. 
In the end, the function that gets the IP ends up calling to `get_default_gateway`, and the `modulesd` reach a high CPU usage because it is looking at the default gateway in a huge routing table almost every second. 

We need to keep investigating this issue and look if  `logcollector`  really needs to get the IP every second. 

Kind regards

**Comment by Molter73** [comment] 2021-02-08 11:56
Hi @lemrouch,

We are studying if it's worth it to make a change on agentd in order to further decrease the CPU consumption of the agent. In order to do this, we would need to test on an affected server if stopping the `ossec-logcollector` process brings the CPU usage of `wazuh-modulesd` down to an acceptable level.

The test would be to remove the default gateway on the affected server in order to get the CPU usage of wazuh-modulesd back up to 100% and issuing the following command to stop logcollector: `kill $(ps aux | grep '[l]ogcollector' | awk '{print $2}')`. You can use `ps aux | grep logcollector` to check if the process has actually stopped running. After issuing the command, the CPU usage of wazuh-modulesd should go back down and show small spikes every 10 seconds. The last step to get logcollector back up and running would be to run `/var/ossec/bin/ossec-logcollector` and re-adding the default gateway in order to prevent the continuous high CPU usage.

Is this a test you would be able to run on your environment?

**Comment by lemrouch** [comment] 2021-02-08 12:49
Hi @Molter73,
I just tried to to remove default gateway and kill the `logcollector` process and I do see CPU load spikes as expected.

**Comment by Molter73** [comment] 2021-02-08 15:56
So killing logcollector stops the 100% usage but keeps load spikes that can be appreciated. These should be possible to be spread further away from eachother by increasing the agent's [notify_time](https://documentation.wazuh.com/4.0/user-manual/reference/ossec-conf/client.html#notify-time). However, since the agent's footprint must be as small as possible, we will look into the possibility of keeping the information that is queried by agentd cached and configuring how often it gets updated.

**Closed** 2021-02-18 18:13 UTC
Labels: bug, core/agent, core/logcollector, core/modulesd

**Comment by masterdanzh** [comment] 2023-01-08 10:58
I have the same issue of modulesd hijacking the CPU even with the latest version and no huge routing list...

**Comment by jhaprins** [comment] 2023-01-13 11:10
A quick question regarding this issue, and several related issues. Reading through some if this it looks like you are doing all kind of magic to find either "the" IP address of the server, which could be difficult with a server with multiple interfaces like routers etc, or you are searching through big routing tables to find some default route. 
Why are you not just looking at the hostname of the server, resolve that to an IP address and check if that IP address is on any of the interfaces. That way you quickly have a trusted way of finding the correct IP address and you don't have to worry about routes etc, because when you send the message to the Wazuh manager the routing stack on the system should be able to take care of the message as long as you are telling it where the message has to go.

**Comment by Nenq** [comment] 2023-04-27 07:51
Exactly the same issue on the software router with 900k routes. Agent version: 4.4.1

**Comment by madalinignisca** [comment] 2024-11-27 17:26
I just did a fresh installation of Wazuh (4.9.2), added 3 agents and Wazuh-modulesd went nuts. It's eating the server's cpu and makes all sluggish and slow.

Related to large routing tables, I doubt I'm in that situation, as it's a small small network.
