### ISSUE TITLE
Support for a distributed API call to add an agent along with key with group assignation

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh#4904] opened 2020-04-14 22:09 UTC
Allow groups parameters handling on a registration thru distributed API call.
- Provide parsing logic for a payload containing Groups arguments .
- Provide validation for valid Groups.
- Provide Groups addition after a new agent registration

**Comment by vikman90** [comment] 2020-04-20 16:03
This issue is a duplicate of #4918

**Closed by vikman90** 2020-04-20 16:03 UTC
Labels: core/auth, duplicate
