### ISSUE TITLE
Integration tests Authd - Failed

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh#25430] opened 2024-08-27 20:08 UTC
## Description

Analyzing the [integration tests](https://github.com/wazuh/wazuh/issues/25347) executed with the new GHA, the following error was detected:

Test: https://github.com/wazuh/wazuh/actions/runs/10582010017

Error:

```
_ ERROR at setup of test_agentd_server_configuration[Basic name and IPV6 exploded] _

    @pytest.fixture(scope='module')
    def wait_for_api_startup_module():
        """Monitor the API log file to detect whether it has been started or not.
    
        Raises:
            RuntimeError: When the log was not found.
        """
        # Set the default values
        logs_format = 'plain'
        host = '0.0.0.0'
        port = WAZUH_API_PORT
    
        # Check if specific values were set or set the defaults
        file_to_monitor = WAZUH_API_JSON_LOG_FILE_PATH if logs_format == 'json' else WAZUH_API_LOG_FILE_PATH
        monitor_start_message = file_monitor.FileMonitor(file_to_monitor)
        monitor_start_message.start(
            callback=generate_callback(API_STARTED_MSG, {
                'host': str(host),
                'port': str(port)
            })
        )
    
        if monitor_start_message.callback_result is None:
>           raise RuntimeError('The API was not started as expected.')
E           RuntimeError: The API was not started as expected.
```

Summary:

```
=========================== short test summary info ============================
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV4]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 exploded]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 1]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 2]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 3]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 4]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 5]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 6]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 7]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 8]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 9]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 10]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 11]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 12]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 13]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 14]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 15]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 16]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 17]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 short 18]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV6 repeated IP]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV4 repeated IP]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name IPV4 formatted as IPV6]
ERROR test_authd/test_api_registration/test_api_agent_registration.py::test_agentd_server_configuration[Basic name and IPV4 repeated IP using IPv4 as IPV6]
= 140 passed, 2 skipped, 1 xfailed, 206 warnings, 24 errors in 3911.17s (1:05:11) =
Error: Process completed with exit code 1.
```

More research is required

**Comment by vikman90** [comment] 2024-08-28 07:39
Testing ITs locally:

```
test_authd/test_api_registration/test_api_agent_registration.py ........................ 
```

Relaunching:
- [Job #293](https://github.com/wazuh/wazuh/actions/runs/10592316403)

**Comment by vikman90** [comment] 2024-08-28 11:25
I have investigated the issue regarding the failing integration tests for Authd, specifically for the `test_api_agent_registration`. After running the tests locally, I can confirm they pass without any issues.

However, when running the tests using `act` (which emulates GitHub Actions locally), I encountered the same error that was reported: the API appears to be unavailable. Upon further investigation and multiple attempts to reproduce the issue, I identified that the tests are stalling due to a long wait when trying to restart the manager service. This is caused by processes becoming zombie (defunct) and blocking the restart process, as `wazuh-control` expects these processes to disappear.

The root cause appears to be that the parent process in the container is `tail`, which does not handle child processes properly, leading to the accumulation of zombie processes. To address this issue and prevent the container from having zombie processes, I propose the following solutions:

1. **Use an "init system" like `tini`**: Incorporating `tini` as the init system in the Docker container will properly reap zombie processes and prevent them from accumulating.

2. **Modify the restart process**: Update the restart logic to handle child processes more effectively, ensuring that all child processes are properly terminated and do not become defunct.

3. **Avoid unnecessary service restarts**: If possible, adjust the test setup or the service management to minimize or avoid service restarts during the tests, reducing the likelihood of zombie processes forming.

Implementing any of these solutions should help prevent the issue with zombie processes and allow the integration tests to complete successfully.

## Conclusion

- Issue confirmed.
- The bug is related to the test itself instead o the product.

**Comment by NahuFigueroa97** [comment] 2024-08-30 01:27
## Update

<details><summary>Test output</summary>

```
============================================================================================= short test summary info =============================================================================================
FAILED test_authd/test_common/test_authd_agents_ctx.py::test_ossec_authd_agents_ctx[get_configuration0-main] - AssertionError: Did not recieve the expected group: {test_group} for the agent
FAILED test_authd/test_use_password/test_authd_use_password_invalid.py::test_authd_use_password_invalid[Use empty password file.] - Failed: DID NOT RAISE <class 'ValueError'>
ERROR test_authd/test_cluster/test_authd_local.py::test_authd_local_messages[Add duplicate agent without force options in request] - Exception: The wdb socket is not up. wazuh-db was restarted but the socket ...
ERROR test_authd/test_cluster/test_authd_local.py::test_authd_local_messages[Failed duplicate registration] - Exception: The wdb socket is not up. wazuh-db was restarted but the socket was not found
ERROR test_authd/test_cluster/test_authd_local.py::test_authd_local_messages[Force registration] - Exception: The wdb socket is not up. wazuh-db was restarted but the socket was not found
ERROR test_authd/test_cluster/test_authd_local.py::test_authd_local_messages[Remove agent] - Exception: The wdb socket is not up. wazuh-db was restarted but the socket was not found
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Single Group - Name too long] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Single Group - Invalid Characters] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Single Group - Empty Group] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Valid groups] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - One group is invalid] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Name too long] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Invalid Characters] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Empty List] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Exceed max multigrup length] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Exceed max Multigrup number] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd.py::test_ossec_auth_messages[Multiple Group - Send a message of exactly 16k] - TimeoutError: None does not meet condition: running = False
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Agent name same as Manager] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Register with Default config] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Too short agent name] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Min len agent name] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Max len agent name] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Too long agent name] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Check non-alphanumeric '*'] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Check non-alphanumeric '-'] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Check non-alphanumeric '_'] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Check non-alphanumeric '.'] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Valid IP] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IP: incomplete] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IP: alphabetic character] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IP: greater than 255: 1] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IP: greater than 255: 2] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IP: 4 digits] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Ip with mask/0] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Ip with mask /24] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Ip with mask /32] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid mask] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid mask, wrong character0] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid mask, wrong character1] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Valid IPv6] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Valid compressed IPv6] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid IPv6: 2 double colons] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid long agent IPv6 address] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_common/test_authd_valid_name_ip.py::test_authd_valid_name_ip[Invalid Agent IPv6 address with words] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_force_options/test_authd_force_options.py::test_authd_force_options[disconnected_time_disabled] - Exception: The wdb socket is not up. wazuh-db was restarted but the socket was not found
ERROR test_authd/test_ssl/test_authd_ssl_options.py::test_ossec_auth_configurations[SSL - Default] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_ssl/test_authd_ssl_options.py::test_ossec_auth_configurations[SSL - Incompatible ciphers from Agent] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_use_password/test_authd_use_password.py::test_authd_use_password[Use password yes - Register with wrong password] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_use_password/test_authd_use_password.py::test_authd_use_password[Use password yes - Random password, request with wrong password] - TimeoutError: wazuh-db does not meet condition: runnin...
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip yes, Let manager decide, use_source_ip enabled] - TimeoutError: wazuh-db does not meet condition: runnin...
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip yes, Let manager decide - IPv6] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip yes, Not specific IPv6] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip no, Override use_source_ip] - TimeoutError: wazuh-db does not meet condition: running = True
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip no, Let manager decide - IPv6] - socket.gaierror: [Errno -5] No address associated with hostname
ERROR test_authd/test_use_source_ip/test_authd_use_source_ip.py::test_authd_use_source_ip[Use source ip no, Not specific IPv6] - socket.gaierror: [Errno -5] No address associated with hostname
============================================================ 2 failed, 112 passed, 2 skipped, 1 xfailed, 124 warnings, 53 errors in 9116.46s (2:31:56) ============================================================

```

</details>

**Comment by NahuFigueroa97** [comment] 2024-08-30 21:03
## Update

To investigate the issue with the test execution, I decided to debug the code, focusing on the file_monitor module of the qa-integration-framework. This module is designed to detect if a specific text appears in a given file. In the case of the test_authd/test_api_registration/ test, the goal was to check for the presence of the pattern r'.*Listening on \{host}:{port}.+', which indicates if the API is available and listening on the expected port.

When the test failed by not finding this pattern, the message: "The API was not started as expected." was reported. This led to an initial hypothesis about possible zombie processes, as suggested by @vikman90 . However, upon further review, I found no zombie processes on my machine during the test execution.

Moving forward, I investigated how the services module of the framework handles service restarts. I found that for Solaris and macOS systems, the module uses wazuh-control, while for other systems it uses the service command. To confirm this, I tracked the changes in the API log file with the command tail -f /var/ossec/logs/api.log. I noticed that the pattern r'.*Listening on \{host}:{port}.+' was present in the logs, both when running pytest and when performing manual restarts with wazuh-control and service.

When reviewing the pattern definition, I noticed that an escape character \ had been added in this https://github.com/wazuh/qa-integration-framework/pull/222 to adapt the pattern to the new API format. This escape character was interfering with the pattern detection in the logs. After removing the escape character, the pattern was detected correctly and the test worked as expected again.

![Captura desde 2024-08-30 18-03-07](https://github.com/user-attachments/assets/63035409-6948-432f-be00-5912f9242d7e)

**Comment by NahuFigueroa97** [comment] 2024-09-02 15:24
## Update

The change in QA was made because since this PR https://github.com/wazuh/wazuh/pull/25216 the API also listens on IPv6 by default, so that log changed. The problem is that 4.9.1 was merged into main of qa-integration-framework so the API is being launched without IPv6 but the regex takes it into account and that's why it fails.
The same test was launched with 4.9.1 and it was confirmed that it did indeed happen.
https://github.com/wazuh/wazuh/actions/runs/10668608480/job/29568723324

**Comment by JcabreraC** [comment] 2024-09-03 15:08
As noted, this issue is caused by the change introduced in PR #25216 to enable IPv6 support.

In version 4.9.1, the transition to IPv6 works correctly: [Reference link](https://github.com/wazuh/wazuh/actions/runs/10668608480/job/29568723324).

**Closed by JcabreraC** 2024-09-03 15:08 UTC
Labels: type/bug, level/task
