### ISSUE TITLE
SCA lost some alerts of 10k when custom policy is defined

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh#3075] opened 2019-04-10 16:30 UTC
Hi team,

We have done some performance testing over SCA module and we have detected some problem on first and consecutive policy scans of SCA, when SCA is scaning 10K registers seems to lost exactly 8 registers `from 2500 to 2508`, and later it sends 8 alerts with same register `r2505`, we will describe our testing process to help developers to reproduce it:
1. Agent configuration:
```
<ossec_config>
  <client>
    <server>
      <address>192.168.121.100</address>
      <port>1514</port>
      <protocol>tcp</protocol>
    </server>
    <crypto_method>aes</crypto_method>
    <notify_time>10</notify_time>
    <time-reconnect>60</time-reconnect>
    <auto_restart>yes</auto_restart>
  </client>

  <sca>
    <enabled>yes</enabled>
    <scan_on_start>yes</scan_on_start>
    <interval>300s</interval>
    <skip_nfs>yes</skip_nfs>

    <policies>
      <policy>win_audit_rcl.yml</policy>
      <policy>win_custom_rcl.yaml</policy>
    </policies>
  </sca>

  <logging>
    <log_format>plain</log_format>
  </logging>
</ossec_config>
```

2. Execute this script and stop when all registers was set to 0:
```
$originalLimit=10000
$customRegistryPath="HKCU:\Software\test"

New-Item $customRegistryPath -Force | out-null
while($true)
{
  "Starting registers to 1"
  For ($i=0; $i -le $originalLimit; $i++) {
    New-ItemProperty -Path $customRegistryPath -Name "r$i" -Value 1 -Force | out-null
  }
  "All registers to 1"
  Start-Sleep -Seconds 5
  "Starting registers to 0"
  For ($i=0; $i -le $originalLimit; $i++) {
    New-ItemProperty -Path $customRegistryPath -Name "r$i" -Value 0 -Force | out-null
  }
  "All registers to 0"
  Start-Sleep -Seconds 5
}
```

3. `cat /var/ossec/logs/alerts/alerts.json | grep 'HKCU\\\\Software\\\\test' | wc -l` on the manager side to extract how many alerts arrive on manager.

4. When 9991 alerts arrive use `tail -f /var/ossec/logs/alerts/alerts.json` and wait to see the repeated alerts come.

This is an example of alerts received after a time on the manager side
```
{"timestamp":"2019-04-10T14:14:00.411+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":3,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554905640.6924619","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:30:49.488+0000","rule":{"level":9,"description":"Benchmark for Windows audit: Null sessions allowed: Status changed from passed to failed","id":"19010","firedtimes":4,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554906649.6925383","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1387538289","policy":"Benchmark for Windows audit","check":{"id":"2505","title":"Null sessions allowed","compliance":{"pci_dss":"11.4"},"registry":"HKLM\\System\\CurrentControlSet\\Control\\Lsa","result":"failed","previous_result":"passed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:35:05.848+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":4,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554906905.6926159","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:37:26.943+0000","rule":{"level":9,"description":"Benchmark for Windows audit: Null sessions allowed: Status changed from passed to failed","id":"19010","firedtimes":5,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554907046.6926923","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1387538289","policy":"Benchmark for Windows audit","check":{"id":"2505","title":"Null sessions allowed","compliance":{"pci_dss":"11.4"},"registry":"HKLM\\System\\CurrentControlSet\\Control\\Lsa","result":"failed","previous_result":"passed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:41:32.308+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":5,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554907292.6927699","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:52:29.580+0000","rule":{"level":9,"description":"Benchmark for Windows audit: Null sessions allowed: Status changed from passed to failed","id":"19010","firedtimes":6,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554907949.6928463","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1387538289","policy":"Benchmark for Windows audit","check":{"id":"2505","title":"Null sessions allowed","compliance":{"pci_dss":"11.4"},"registry":"HKLM\\System\\CurrentControlSet\\Control\\Lsa","result":"failed","previous_result":"passed"}}},"location":"sca"}
{"timestamp":"2019-04-10T14:57:17.928+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":6,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554908237.6929239","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
{"timestamp":"2019-04-10T15:22:29.716+0000","rule":{"level":9,"description":"Benchmark for Windows audit: Null sessions allowed: Status changed from passed to failed","id":"19010","firedtimes":1,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554909749.6930003","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1387538289","policy":"Benchmark for Windows audit","check":{"id":"2505","title":"Null sessions allowed","compliance":{"pci_dss":"11.4"},"registry":"HKLM\\System\\CurrentControlSet\\Control\\Lsa","result":"failed","previous_result":"passed"}}},"location":"sca"}
{"timestamp":"2019-04-10T15:26:01.733+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":1,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554909961.6930779","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
{"timestamp":"2019-04-10T15:30:13.671+0000","rule":{"level":9,"description":"Benchmark for Windows audit: Null sessions allowed: Status changed from passed to failed","id":"19010","firedtimes":2,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554910213.6931543","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1387538289","policy":"Benchmark for Windows audit","check":{"id":"2505","title":"Null sessions allowed","compliance":{"pci_dss":"11.4"},"registry":"HKLM\\System\\CurrentControlSet\\Control\\Lsa","result":"failed","previous_result":"passed"}}},"location":"sca"}
{"timestamp":"2019-04-10T15:33:52.655+0000","rule":{"level":3,"description":"Custom Benchmark for Windows registry: Register r2505 enabled: Status changed from failed to passed","id":"19009","firedtimes":2,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"]},"agent":{"id":"006","name":"win-2008R2-std","ip":"192.168.121.22"},"manager":{"name":"localhost.localdomain"},"id":"1554910432.6932319","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"172333971","policy":"Custom Benchmark for Windows registry","check":{"id":"2505","title":"Register r2505 enabled","compliance":{"pci_dss":"10.6.1"},"registry":"HKCU\\Software\\test","result":"passed","previous_result":"failed"}}},"location":"sca"}
```
We will give more details when we do more tests, don't hesitate to ask us some information or configuration.

|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
| 3.9.0-3912 | Agent | Packages | Windows Server 2008 |

Regards.

**Comment by okynos** [comment] 2019-04-11 09:42
Hi team,

We will give some more information:
[win_custom_rc.yaml.txt](https://github.com/wazuh/wazuh/files/3067970/win_custom_rc.yaml.txt) **Rename to yaml** (Github doesn't support yaml at time of writing).


Log on the **agent** side:
```
2019/04/11 09:25:51 ossec-agent: INFO: Using notify time: 10 and max time to reconnect: 60
2019/04/11 09:25:51 ossec-agent: INFO: (1905): No file configured to monitor.
2019/04/11 09:25:51 ossec-agent: INFO: No option <ca_store> defined. Using Wazuh default CA (wpk_root.pem).
2019/04/11 09:25:51 ossec-agent: INFO: Started (pid: 4444).
2019/04/11 09:25:51 ossec-agent: INFO: (1410): Reading authentication keys file.
2019/04/11 09:25:51 ossec-agent: INFO: Trying to connect to server (192.168.121.100:1514/tcp).
2019/04/11 09:25:51 ossec-agent: INFO: Starting syscheckd thread.
2019/04/11 09:25:51 ossec-agent: INFO: (1702): No directory provided for syscheck to monitor.
2019/04/11 09:25:51 ossec-agent: INFO: Syscheck disabled.
2019/04/11 09:25:51 rootcheck: INFO: Rootcheck disabled.
2019/04/11 09:25:51 ossec-agent: INFO: (4102): Connected to the server (192.168.121.100:1514/tcp).
2019/04/11 09:25:51 sca: INFO: Module started.
2019/04/11 09:25:51 sca: INFO: The request_db_interval option cannot be higher than the scan interval. It will be redefined to that value.
2019/04/11 09:25:51 ossec-agent: INFO: Active response command not present: 'active-response/bin/restart-ossec.sh'. Not using it on this system.
2019/04/11 09:25:51 sca: INFO: Starting Security Configuration Assessment scan.
2019/04/11 09:25:51 ossec-agent: INFO: Active response command not present: 'active-response/bin/script.cmd'. Not using it on this system.
2019/04/11 09:25:51 ossec-agent: INFO: Windows version is 6.0 or newer. (Microsoft Windows Server 2016 Standard [Ver: 10.0.14393] - Wazuh v3.9.0).
2019/04/11 09:25:51 sca: INFO: Starting evaluation of policy: 'win_audit_rcl.yml
2019/04/11 09:25:51 ossec-agent: INFO: Started (pid: 4444).
2019/04/11 09:25:54 sca: INFO: Evaluation finished for policy 'win_audit_rcl.yml'.
2019/04/11 09:25:56 sca: INFO: Starting evaluation of policy: 'win_custom_rcl.yaml
2019/04/11 09:35:53 sca: INFO: Evaluation finished for policy 'win_custom_rcl.yaml'.
2019/04/11 09:35:53 sca: INFO: Integration checksum failed for policy: 'win_custom_rcl.yaml'. Resending scan results in 35 seconds.
2019/04/11 09:35:54 sca: INFO: Security Configuration Assessment scan finished. Duration: 603 seconds.
2019/04/11 09:35:54 sca: ERROR: Interval overtaken.
2019/04/11 09:35:54 sca: INFO: Starting Security Configuration Assessment scan.
2019/04/11 09:35:54 sca: INFO: Starting evaluation of policy: 'win_audit_rcl.yml
2019/04/11 09:35:57 sca: INFO: Evaluation finished for policy 'win_audit_rcl.yml'.
2019/04/11 09:35:59 sca: INFO: Starting evaluation of policy: 'win_custom_rcl.yaml
```

Log on the **Manager** side:
[sca_manager_log.txt](https://github.com/wazuh/wazuh/files/3067974/sca_manager_log.txt)


Regards.

**Comment by JuantAldea** [comment] 2019-04-11 14:30
After further discussion with @okynos, the problem manifests itself during the first run, without swapping the registry values.

**Comment by chemamartinez** [comment] 2019-04-12 16:12
@okynos and @JuantAldea please, let me close this issue since it was unable to be reproduced. Feel free to reopen it whether the behavior reappears again.

Regards.

**Closed by chemamartinez** 2019-04-12 16:12 UTC
Labels: bug
