### ISSUE TITLE
Windows Wazuh tmp folder gets blocked after uninstalling

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh#10103] opened 2021-09-13 15:13 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| any | --- | Agent | any | Windows |

We have detected that, from time to time, after uninstalling a Wazuh-Agent, the "tmp" folder gets blocked, so no new Wazuh-Agent installation can be performed until a reboot is done.

We were able to check that this happens, at least, on Windows Server 2008 R2 and Windows 7, and also with multiple versions of Wazuh as, for example, 4.1.5 and 4.2.0.

---

Here are some screenshots related to this:

![image](https://user-images.githubusercontent.com/75255206/133109254-e860a22c-5609-4577-884a-f02f6260fe62.png)

![image](https://user-images.githubusercontent.com/75255206/133109197-490cf062-3a63-4677-bd60-1e83aed97ba1.png)

These images were taken from a Windows Server 2008 R2, after uninstalling Wazuh-Agent 4.1.5.

---

Best Regards,

Mariano Koremblum

**Comment by FrancoRivero** [comment] 2022-04-27 15:21
Hello team, I am working on this issue so I have done some tests to reproduce this issue, however I haven't been able to produce it.
From my point of view we should close this issue because this problem is not reproduced in the release tests after it created this issue and I haven't been able to reproduce it either.

I have tested on Windows 7 SP1 build 7601 using the two latest versions of Wazuh, I mean `4.1.5-1` and `4.2.6-1`.
With this in mind, the tests I did were as follows:

1. Install `4.1.5`, uninstall `4.1.5`, reboot system and install `4.2.6`
2. Install `4.2.6`, uninstall `4.2.6`, reboot system and install `4.1.5`
3. Install `4.1.5`, reboot and install `4.2.6`
4. Install `4.1.5`, reboot and install `4.2.6`, reboot and uninstall
5. Install `4.1.5`, uninstall `4.1.5`, and install `4.2.6`
6. Install `4.2.6`, uninstall `4.2.6`, and install `4.1.5`
7. Install `4.1.5` and install `4.2.6`
8. Install `4.1.5` , install `4.2.6` and uninstall
9. Install `4.1.5`, configure FIM and install `4.2.6`
10. Install `4.1.5`, configure FIM, reboot, install `4.2.6` and uninstall

**Closed by FrancoRivero** 2022-04-27 15:21 UTC
Labels: bug, core/fim, core/agent, platform/windows, installer
