### ISSUE TITLE
Add basic logging by default for integrations (without the need of `DEBUG` level)

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh#15205] opened 2022-10-21 09:11 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.4.0-40400 | `wazuh-integratord` | Manager | Packages | Ubuntu focal |

Doing [testing for the Wazuh integration with shuffle](https://github.com/wazuh/wazuh-qa/issues/3398), we have realized that the logging shown by default is very poor, since they depend on the `DEBUG` mode `integrator.debug=x` being enabled in `local_internal_options.conf`.

For example, as a user, I would like that Wazuh notify me if alerts are not being sent correctly to shuffle, either because the webhook is down....

Generalizing all this a bit, if the receiver's response to the alert being sent is other than 200, then it means there is some problem that needs to be pointed out to the user to make it look like everything is working correctly when in fact it is not.

According to the development team, this is common to all integrations, so this would have to be reviewed for the rest of the integrations, and a general solution would have to be proposed.

Also, I want to suggest the idea of unifying the `integrations.log` log in `ossec.log`, so that everything that is written in that file, is written directly in `ossec.log` as part of the `integratord` logging. For example, sometimes to find out what is going on, you have to consult both logs, because one part appears in `ossec.log` and the other in `integrations.log`.

### Child issue
- [x] https://github.com/wazuh/wazuh/issues/16662

**Comment by GGP1** [comment] 2023-03-31 19:43
## Update

There is almost no information logged if the debug mode is off. Perhaps we could offer more logging levels (`info`, `warn`, `error`) to cover a wider scope, `info` being the default and providing enough relevant information.

I have reviewed the code and the scripts for each platform perform a very similar job. I think we should be consistent on how we log information across integrations. 

Once I finish setting up the integrations I will start implementing changes.

**Comment by GGP1** [comment] 2023-04-04 19:26
## Update

Created [pull request](https://github.com/wazuh/wazuh/pull/16624) with the refactor of the logging performed in the Slack, Virustotal and Shuffle integration scripts. The one for Pagerduty is in progress.

Tested the changes with the Slack service and it works as expected.

**Comment by GGP1** [comment] 2023-04-05 16:38
## Update

- Finished pagerduty script refactor, updated shuffle test and improved the logger setup on the rest of the integrations.
- Changed the status to `pending review`
- Created the issue https://github.com/wazuh/wazuh/issues/16641 to change the scripts implementations and abstract the main operations so duplicated code can be removed and new integrations can be added with less effort. Didn't do those changes here since it's outside the scope of this issue.

**Comment by GGP1** [comment] 2023-04-10 14:15
## Update

Added `conftest.py` and a hook to remove the log file created by the tested functions at the end of the test.

Created the issue https://github.com/wazuh/wazuh/issues/16662 for the core team to adapt the `wazuh-integratord` script execution to the new logging levels.

**Comment by GGP1** [comment] 2023-05-30 12:32
## Update

Created two issues for the end-to-end tests of the changes introduced in the linked pull request

- https://github.com/wazuh/wazuh/issues/17316
- https://github.com/wazuh/wazuh/issues/17317

**Comment by GGP1** [comment] 2023-06-02 13:55
## Update

We met with the Core team to synchronize this issue's PR and https://github.com/wazuh/wazuh/pull/16090, since they both make changes to the structure of the same code. 

Given that https://github.com/wazuh/wazuh/pull/16090 contains changes in the integrator daemon and a more extensive list of changes to the scripts (including the migration of pagerduty to Python), we concluded that we are going to merge those changes first and then apply the ones to the logging after.

Furthermore, the Core team has already created unit tests and manually tested their changes, now that we are going to change just the logging the E2E UX tests are no longer necessary and were closed as not planned.

This issue remains blocked until the mentioned PR is merged.

**Comment by GGP1** [comment] 2023-06-02 13:56
## Update

We met with the Core team to synchronize this issue's PR and https://github.com/wazuh/wazuh/pull/16090, since they both make changes to the structure of the same code. 

Given that https://github.com/wazuh/wazuh/pull/16090 contains changes in the integrator daemon and a more extensive list of changes to the scripts (including the migration of pagerduty to Python), we concluded that we are going to merge those changes first and then apply the ones to the logging after.

Furthermore, the Core team has already created unit tests and manually tested their changes, now that we are going to change just the logging the E2E UX tests are no longer necessary and were closed as not planned.

This issue remains blocked until https://github.com/wazuh/wazuh/pull/16090 is merged.

**Comment by GGP1** [comment] 2023-07-17 18:03
## Update

Refactored the logging of the integrations after the PR https://github.com/wazuh/wazuh/pull/16090 from Core has been merged.

Since the new changes are completely unrelated to the ones I did before the changes from core, I'm moving it to pending review again.

**Comment by GGP1** [comment] 2023-07-17 18:04
## Update

Refactored the logging of the integrations after the PR https://github.com/wazuh/wazuh/pull/16090 from Core has been merged.

Since the new changes are completely unrelated to the ones I did before, I'm moving it to pending review again.

**Comment by EduLeon12** [comment] 2023-07-31 13:46
## Review Conclusion

After a meeting with the team, it was decided that the standardization of logs will be made later on with the new upcoming changes on the external integration module.

Also, current changes address the issue and provided good visibility of logs until future changes are developed. 
Therefore the issue is approved.

**Comment by GGP1** [comment] 2023-08-22 15:43
## Update

- Applied the style changes requested
- Implemented log rotation
- Change the level of webhook logs to `debug`
- Updated unit tests

I'm leaving the issue on hold until we decide with the team what to do with secrets and which are the appropiate parameters to the `RotatingFileHandler` logger.

**Comment by GGP1** [comment] 2023-08-22 15:44
## Update

- Applied the style changes requested
- Implemented log rotation
- Change the level of webhook logs to `debug`
- Updated unit tests

I'm leaving the issue _on hold_ until we decide with the team what to do with secrets and which are the appropriate parameters to the `RotatingFileHandler` logger.

**Comment by GGP1** [comment] 2023-08-23 12:54
## Update 

Changed the log rotation to be executed on each midnight and updated the number of files to be kept to 31.

**Comment by Selutario** [comment] 2023-08-24 12:04
Moving to blocked until the issue below is completed so I can review and test it correctly:
- https://github.com/wazuh/wazuh/issues/16662

**Comment by GGP1** [comment] 2023-10-05 18:18
## Update

Rebased to master to pull the changed from Core and validated that everything works as it should.

<details><summary>ossec.conf</summary>

```xml
<integration>
  <name>slack</name>
  <hook_url>https://hooks.slack.com/services/XXX</hook_url>
  <alert_format>json</alert_format>
</integration>

```

</details>

<details><summary>internal_options.conf</summary>

```console
...
# Integrator daemon debug (server, local or Unix agent)
integrator.debug=2
...
```

</details> 

<details><summary>wazuh-integratord logs</summary>

```console
root@wazuh-master:/# cat /var/ossec/logs/ossec.log | grep wazuh-integratord
...
2023/10/05 18:12:56 wazuh-integratord[3209] main.c:181 at main(): INFO: Started (pid: 3209).
2023/10/05 18:12:56 wazuh-integratord[3209] integrator.c:53 at OS_IntegratorD(): DEBUG: JSON file queue connected.
2023/10/05 18:12:56 wazuh-integratord[3209] integrator.c:143 at OS_IntegratorD(): INFO: Enabling integration for: 'slack'.
2023/10/05 18:12:56 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:12:56 wazuh-integratord[3209] intgcom.c:76 at intgcom_main(): DEBUG: Local requests thread ready
2023/10/05 18:12:57 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:12:58 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:12:59 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:13:00 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:161 at OS_IntegratorD(): DEBUG: Sending new alert.
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:293 at OS_IntegratorD(): DEBUG: File /tmp/slack-1696529581-940328887.alert was written.
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:444 at OS_IntegratorD(): DEBUG: Running script with args: integrations /tmp/slack-1696529581-940328887.alert  https://hooks.slack.com/services/XXX INFO  10 3
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Running Slack script
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Alerts file location: /tmp/slack-1696529581-940328887.alert
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 ERROR JSON file for options  doesn't exist
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Processing alert with ID 1696529580.4902
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Generating message
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Sending message
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:453 at OS_IntegratorD(): DEBUG: Thu Oct 05 18:13:01 UTC 2023 INFO Message sent successfully
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:466 at OS_IntegratorD(): DEBUG: Command ran successfully.
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:154 at OS_IntegratorD(): DEBUG: jqueue_next()
2023/10/05 18:13:01 wazuh-integratord[3209] integrator.c:161 at OS_IntegratorD(): DEBUG: Sending new alert.
...
```

</details>

<details><summary>integrations.log</summary>

```console
root@wazuh-master:/# cat /var/ossec/logs/integrations.log 
Thu Oct 05 18:13:01 UTC 2023 INFO Running Slack script
Thu Oct 05 18:13:01 UTC 2023 INFO Alerts file location: /tmp/slack-1696529581-940328887.alert
Thu Oct 05 18:13:01 UTC 2023 ERROR JSON file for options  doesn't exist
Thu Oct 05 18:13:01 UTC 2023 INFO Processing alert with ID 1696529580.4902
Thu Oct 05 18:13:01 UTC 2023 INFO Generating message
Thu Oct 05 18:13:01 UTC 2023 INFO Sending message
Thu Oct 05 18:13:01 UTC 2023 INFO Message sent successfully
Thu Oct 05 18:13:01 UTC 2023 INFO Running Slack script
Thu Oct 05 18:13:01 UTC 2023 INFO Alerts file location: /tmp/slack-1696529581-1210046344.alert
Thu Oct 05 18:13:01 UTC 2023 ERROR JSON file for options  doesn't exist
Thu Oct 05 18:13:01 UTC 2023 INFO Processing alert with ID 1696529580.5281
Thu Oct 05 18:13:01 UTC 2023 INFO Generating message
Thu Oct 05 18:13:01 UTC 2023 INFO Sending message
Thu Oct 05 18:13:02 UTC 2023 INFO Message sent successfully
Thu Oct 05 18:13:13 UTC 2023 INFO Running Slack script
Thu Oct 05 18:13:13 UTC 2023 INFO Alerts file location: /tmp/slack-1696529593--1268591238.alert
Thu Oct 05 18:13:13 UTC 2023 ERROR JSON file for options  doesn't exist
Thu Oct 05 18:13:13 UTC 2023 INFO Processing alert with ID 1696529592.5668
Thu Oct 05 18:13:13 UTC 2023 INFO Generating message
Thu Oct 05 18:13:13 UTC 2023 INFO Sending message
Thu Oct 05 18:13:13 UTC 2023 INFO Message sent successfully
```

</details>

### Slack messages

**Comment by davidjiglesias** [comment] 2024-04-17 08:37
We have finally decided not to do this.

**Closed** 2024-04-17 08:37 UTC
Labels: type/enhancement, module/integration, reporter/qa, level/task
