### ISSUE TITLE
Wazuh API not installing on RHEL Server 7.6 after nodejs installation

### ISSUE THREAD

**Issue by aamore** [wazuh/wazuh#3416] opened 2019-05-29 13:14 UTC
I currently have kibana, wazuh-manager and elasticsearch downloaded onto a RHEL  Server 7.6  VM.
I need to have the wazuh app installed. 

I have already downloaded nodejs as required by the documentation found online. Unfortunately, I had to download nodejs manually since the repository was not being added.

When I try to install the wazuh app, i get this output: 

**error: Failed dependencies:
	nodejs >= 4.6 is needed by wazuh-api-3.9.1-1.x86_64**

Since I already have nodejs installed, this error should not be popping up (one would think at least). Anyone have any advice?

If more information is needed, please let me know.

**Comment by alberpilot** [comment] 2019-05-29 14:10
Hello @aamore 

  I tried to reproduce your issue unsuccessfully. Please, correct me if I'm wrong, you followed the steps described here: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm.html#installing-the-wazuh-api

![image](https://user-images.githubusercontent.com/3830293/58563341-366f9e00-822b-11e9-8d4c-01fa3d419c19.png)

Was the step one executed without errors? And step two? The first `curl` command adds the NodeJS 8 repository to your RHEL 7 host. The second command `yum install nodejs` will install the correct _nodejs_ package required by _wazuh-api_

I've attached an output file of my tested command line in a CentOS 7.6 host. Please verify that your followed steps match with the ones used in the attached file. If you have the same problem, please send me the output so we can analyze it. 

[centos7_output.txt](https://github.com/wazuh/wazuh/files/3232853/centos7_output.txt)

Sorry for the inconveniences, hope it helps. 
Best regards, 
Alberto R.

**Comment by aamore** [comment] 2019-05-29 14:55
Step one was executed until nodejs needed to be installed.  I successfully added the repositories.
Step 3 cannot be done because nodejs is supposedly not installed. 

Here is the output after trying to complete Step 1: 
![nodejs](https://user-images.githubusercontent.com/51163236/58565861-7ddf3580-81fd-11e9-91cb-edc607250257.PNG)


Since I previously installed nodejs externally, this is the output I get when I check the version:
![version](https://user-images.githubusercontent.com/51163236/58565882-89326100-81fd-11e9-962b-ee797daab84e.PNG)


After trying to install the wazuh-api, i get this output:
![dependencies](https://user-images.githubusercontent.com/51163236/58565916-9e0ef480-81fd-11e9-9061-adbb24f219d3.PNG)

 
I have tried replacing the repositories and checking to see if anything is missing. After pressing 'y' it fails and gives me this output: 
![workaround](https://user-images.githubusercontent.com/51163236/58566051-df070900-81fd-11e9-9d50-cd3b0932e6fd.PNG)

After enabling the repositories, it refers me to the redhat website and has me run this command and install wazuh-api again:
rm -fr /var/cache/yum/*
yum clean all 
sudo yum install wazuh-api

After that has been executed, it asks me to enable all repositories again. After that happens, this is the output given:
![nodejsneed](https://user-images.githubusercontent.com/51163236/58567275-124a9780-8200-11e9-907e-d7c25e9718ac.PNG)

I really appreciate your help by the way!

**Comment by alberpilot** [comment] 2019-05-29 15:52
Hello @aamore 

  I think that the problem is nodejs version. So we need to install the correct version. After the curl command, if we execute `cat /etc/yum.repos.d/nodesource-el7.repo` we would have the following output:
```
[root@manager vagrant]# cat /etc/yum.repos.d/nodesource-el7.repo 
[nodesource]
name=Node.js Packages for Enterprise Linux 7 - $basearch
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL

[nodesource-source]
name=Node.js for Enterprise Linux 7 - $basearch - Source
baseurl=https://rpm.nodesource.com/pub_8.x/el/7/SRPMS
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/NODESOURCE-GPG-SIGNING-KEY-EL
gpgcheck=1
```

Do you have the same output? If yes, let's go to the next verification step ` yum --showduplicates list nodejs`:
```
[root@manager vagrant]# yum --showduplicates list nodejs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.uv.es
 * epel: mirror.uv.es
 * extras: mirror.uv.es
 * updates: mirror.uv.es
Installed Packages
nodejs.x86_64                                1:6.16.0-1.el7                                                @epel     
Available Packages
nodejs.x86_64                                1:6.16.0-1.el7                                                epel      
nodejs.x86_64                                2:8.0.0-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.1.0-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.1.1-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.1.2-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.1.3-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.1.4-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.2.0-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.2.1-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.3.0-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.4.0-1nodesource.el7.centos                                nodesource
nodejs.x86_64                                2:8.5.0-1nodesource                                           nodesource
nodejs.x86_64                                2:8.6.0-1nodesource                                           nodesource
nodejs.x86_64                                2:8.7.0-1nodesource                                           nodesource
nodejs.x86_64                                2:8.8.0-1nodesource                                           nodesource
nodejs.x86_64                                2:8.8.1-1nodesource                                           nodesource
nodejs.x86_64                                2:8.9.0-1nodesource                                           nodesource
nodejs.x86_64                                2:8.9.1-1nodesource                                           nodesource
nodejs.x86_64                                2:8.9.2-1nodesource                                           nodesource
nodejs.x86_64                                2:8.9.3-1nodesource                                           nodesource
nodejs.x86_64                                2:8.9.4-1nodesource                                           nodesource
nodejs.x86_64                                2:8.10.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.11.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.11.1-1nodesource                                          nodesource
nodejs.x86_64                                2:8.11.2-1nodesource                                          nodesource
nodejs.x86_64                                2:8.11.3-1nodesource                                          nodesource
nodejs.x86_64                                2:8.11.4-1nodesource                                          nodesource
nodejs.x86_64                                2:8.12.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.13.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.14.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.14.1-1nodesource                                          nodesource
nodejs.x86_64                                2:8.15.0-1nodesource                                          nodesource
nodejs.x86_64                                2:8.15.1-1nodesource                                          nodesource
nodejs.x86_64                                2:8.16.0-1nodesource                                          nodesource
```

If you have the same output, it means that the repository it's working and offering us all 8.x nodejs versions. 

The next point is to replace your old nodejs version. For this, you could remove it **carefully**. Please, make sure that, if you remove nodejs, other application can be damaged. If you only installed nodejs for Wazuh purpose, just type: `yum remove nodejs`. 
Once old nodejs is removed, install it again: `yum install nodejs`. After install it, review the version: 
```
[root@manager vagrant]# node -v
v8.16.0
```
Now, with this version you'll be able to install wazuh-api. 
Please, let me know if it works. 
Best regards, 

Alberto R.

**Comment by aamore** [comment] 2019-05-29 16:43
After the curl command, I received those two exact outputs.

When I tried to install nodejs, I received this output:
![newnode](https://user-images.githubusercontent.com/51163236/58574992-411c3a00-820f-11e9-9e76-302796a21f37.PNG)


I'm definitely getting somewhere though!

**Comment by alberpilot** [comment] 2019-05-29 17:43
Hello @aamore 

  Looks like if something it's happening with NodeJS and their key. Let's try to add manually the key:

First verify the installed keys: 
```
[root@manager vagrant]# rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
gpg-pubkey-f4a80eb5-53a7ff4b	gpg(CentOS-7 Key (CentOS 7 Official Signing Key) <security@centos.org>)
gpg-pubkey-29111145-579ec98c	gpg(Wazuh.com (Wazuh Signing Key) <support@wazuh.com>)
gpg-pubkey-352c64e5-52ae6884	gpg(Fedora EPEL (7) <epel@fedoraproject.org>)
gpg-pubkey-34fa74dd-540237d4	gpg(NodeSource <gpg-rpm@nodesource.com>)
```
Then, let's remove NodeSource:
```
[root@manager vagrant]# rpm -e gpg-pubkey-34fa74dd-540237d4
```
The next step is to import the key:
```
[root@manager vagrant]# rpm --import https://rpm.nodesource.com/pub/el/NODESOURCE-GPG-SIGNING-KEY-EL
```
And now, if you try to install nodejs must work:
```
[root@manager vagrant]# yum install nodejs
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirror.tedra.es
 * extras: mirror.tedra.es
 * updates: ftp.csuc.cat
Resolving Dependencies
--> Running transaction check
---> Package nodejs.x86_64 2:8.16.0-1nodesource will be installed
--> Finished Dependency Resolution

Dependencies Resolved

==============================================================================================================================================================================================================================================
 Package                                              Arch                                                 Version                                                             Repository                                                Size
==============================================================================================================================================================================================================================================
Installing:
 nodejs                                               x86_64                                               2:8.16.0-1nodesource                                                nodesource                                                16 M

Transaction Summary
==============================================================================================================================================================================================================================================
Install  1 Package

Total size: 16 M
Installed size: 49 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Warning: RPMDB altered outside of yum.
  Installing : 2:nodejs-8.16.0-1nodesource.x86_64                                                                                                                                                                                         1/1 
  Verifying  : 2:nodejs-8.16.0-1nodesource.x86_64                                                                                                                                                                                         1/1 

Installed:
  nodejs.x86_64 2:8.16.0-1nodesource                                                                                                                                                                                                          

Complete!
```



**Alternative option**: You could install using `--nogpgcheck` option: `yum install --nogpgcheck -y nodejs` if you are comfortable with this (take into account that you're not verifying the identity of packages provider). References: 
https://github.com/nodesource/distributions/issues/386
https://github.com/GovTechSG/centos-ruby-node/commit/d6d3ec6378bc15eddb0f937eb706d8705c4f458c


Please, let me know if it works.
Best regards, 
Alberto R

**Comment by aamore** [comment] 2019-05-29 18:12
I was able to add the key and install nodejs and install wazuh-api. Thanks for the help!

**Comment by alberpilot** [comment] 2019-05-29 20:16
Glad to help! I close this issue, don't hesitate to re-open if you consider it. 
Best regards, 

Alberto R.

**Closed by alberpilot** 2019-05-29 20:16 UTC
