### ISSUE TITLE
Release 4.7.3 - RC 1 - Upgrade metrics

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh#22035] opened 2024-02-22 14:05 UTC
### Packages tests metrics information

| | |
|:--|:--:|
|**Main release stage issue**|#22018|
|**Main packages metrics issue**|#22033|
|**Version**|4.7.3|
|**Release stage**|RC 1|
|**Tag**|https://github.com/wazuh/wazuh/tree/v4.7.3-rc1|

### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

### Automated tests

Build: https://ci.wazuh.info/job/Test_upgrade_tier/2179/

---

|System|3.13.6|4.6.0|4.7.2|
|:--|:--|:--|:--|
|CentOS 8|:green_circle:|:green_circle:|:green_circle:|
|CentOS 7|:green_circle:|:green_circle:|:green_circle:|
|CentOS 6|:red_circle:|:green_circle:|:green_circle:|
|CentOS 5|:green_circle:|:green_circle:|:green_circle:|
|Debian 12 (bookworm)|:white_circle:|:green_circle:|:green_circle:|
|Debian 11 (bullseye)|:green_circle:|:green_circle:|:green_circle:|
|Debian 10 (buster)|:green_circle:|:green_circle:|:green_circle:|
|Debian 9 (strech)|:green_circle:|:green_circle:|:green_circle:|
|Fedora 36|:green_circle:|:green_circle:|:green_circle:|
|Fedora 35|:green_circle:|:green_circle:|:green_circle:|
|Fedora 34|:green_circle:|:green_circle:|:green_circle:|
|Fedora 32|:green_circle:|:green_circle:|:green_circle:|
|Fedora 31|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Focal|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Bionic|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Xenial|:green_circle:|:green_circle:|:green_circle:|
|Ubuntu Trusty|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 2|:green_circle:|:green_circle:|:green_circle:|
|Amazon Linux 1|:green_circle:|:green_circle:|:green_circle:|
|Oracle Linux 8|:green_circle:|:green_circle:|:green_circle:|
|openSUSE Tumbleweed|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 6|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 7|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 8|:green_circle:|:green_circle:|:green_circle:|
|Red Hat 9|:green_circle:|:green_circle:|:green_circle:|

---

### Manual tests - Upgrade 4.7.2 -> 4.7.3

|System|MSI Upgrade|Logs|Alerts|
|:--|:--:|:--:|:--:|
|Windows Server 2022|:white_circle:|:white_circle:|:white_circle:|
|Windows 11|:white_circle:|:white_circle:|:white_circle:|

---

|System|Upgrade*|Upgrade**|TCP|UDP|Alerts|Logs|User|Group|PID changed|Remove|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|macOS 11.00 Big Sur|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 14 Sonoma(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 14 Sonoma(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
- \* Without environment variables
- \** With environment variables

---

#### WPK Upgrade

|System|WPK 4.7.2 -> 4.7.3|WPK Force 4.7.3 -> 4.7.3|
|:--|:--:|:--:|
|Ubuntu 22.04|:white_circle:|:white_circle:|
|Red Hat 9|:white_circle:|:white_circle:|
|Windows 11|:white_circle:|:white_circle:|

---

|System|Upgrade (WPK)|Alerts|Logs|User|Group|PID changed|Force*|
|:--|:--:|:--:|:--:|:--:|:--:|:--:|:--:|
|macOS 11.00 Big Sur|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 14 Sonoma(intel64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 12.01 Monterey(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 13.4 Ventura(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
|macOS 14 Sonoma(arm64)|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|:white_circle:|
- \* Must include all other checks again

---

Status legend:
:black_circle: - Not started
:white_circle: - Skipped
:large_blue_circle: - In progress
:orange_circle: - Ready to review
:green_circle: - Approved
:yellow_circle: - Approved with warnings or expected errors
:red_circle: - Rejected

---

### New Issues:

- https://github.com/wazuh/wazuh-jenkins/issues/5132

---

In order to close and proceed with the release or the next candidate version, the following auditors must give the green light to this RC.
- [ ] @davidjiglesias

---

**Comment by rafabailon** [comment] 2024-02-23 12:02
## CentOS 6 - Test Failed (3.13.6)

CentOS 6 test failed with this error: 

```bash
11:25:35  Namespace(directory='/var/ossec', from_version='3.13.6', ignore='/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python', no_show_ignore_list=True, os='linux', target='manager', test='upgrade', version='4.7.3')
11:25:35  Checking files...
11:25:35  
11:25:35  Extra (Not present in the check-files but they are installed):
11:25:35  /var/ossec/queue/db/000.db-journal  [wazuh wazuh 0640 -rw-r-----]
```

This is the complete log of the error: 

<details>
  <summary>Error Logs</summary>
  <br/>

```console
11:25:35  TASK [test-manager : Run check files tests] ************************************
11:25:35  task path: /home/ec2-user/workspace/Test_upgrade/quality/tests/generic/03-upgrade/linux/test/conf/test-manager/tasks/configure_test.yaml:77
11:25:35  fatal: [amd64-centos-6-manager-3_13_6_0]: FAILED! => {
11:25:35      "changed": true,
11:25:35      "cmd": [
11:25:35          "/usr/testing/bin/python3",
11:25:35          "./check_files.py",
11:25:35          "-a",
11:25:35          "upgrade",
11:25:35          "-o",
11:25:35          "linux",
11:25:35          "-t",
11:25:35          "manager",
11:25:35          "-v",
11:25:35          "4.7.3",
11:25:35          "-f",
11:25:35          "3.13.6",
11:25:35          "-i",
11:25:35          "/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python",
11:25:35          "--no_show_ignore_list"
11:25:35      ],
11:25:35      "delta": "0:00:11.961158",
11:25:35      "end": "2024-02-23 10:25:35.657453",
11:25:35      "rc": 1,
11:25:35      "start": "2024-02-23 10:25:23.696295"
11:25:35  }
11:25:35  
11:25:35  STDOUT:
11:25:35  
11:25:35  Namespace(directory='/var/ossec', from_version='3.13.6', ignore='/var/ossec/wodles/oscap/content/cve-debian-8-oval.xml,/var/ossec/wodles/oscap/content/cve-ubuntu-xenial-oval.xml,/var/ossec/wodles/oscap/content/cve-debian-9-oval.xml,/var/ossec/wodles/oscap/content/ssg-debian-8-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1404-ds.xml,/var/ossec/wodles/oscap/content/ssg-ubuntu-1604-ds.xml,/var/ossec/queue/syscheck,/var/ossec/backup/shared,/var/ossec/queue/agents-timestamp,/var/ossec/logs/api.log,/var/ossec/api/configuration/auth,/var/ossec/api/configuration/auth/htpasswd,/var/ossec/var/wodles/syscollector,/var/ossec/etc/decoders/local_decoder.xml,/var/ossec/etc/rules/local_rules.xml,/var/ossec/etc/shared/default/agent.conf,/var/ossec/.ssh,/var/ossec/logs/cluster.log,/var/ossec/var/run/wazuh-api.pid,/var/ossec/tmp,/var/ossec/framework/python', no_show_ignore_list=True, os='linux', target='manager', test='upgrade', version='4.7.3')
11:25:35  Checking files...
11:25:35  
11:25:35  Extra (Not present in the check-files but they are installed):
11:25:35  /var/ossec/queue/db/000.db-journal  [wazuh wazuh 0640 -rw-r-----]
11:25:35  
11:25:35  
11:25:35  Please, review your files.
```

</details>

**Comment by Rebits** [comment] 2024-02-23 13:52
We need to open an issue reporting centOS 6 failure https://github.com/wazuh/wazuh/issues/22035#issuecomment-1961205608

**Comment by rafabailon** [comment] 2024-02-23 15:50
I found this open issue https://github.com/wazuh/wazuh-jenkins/issues/6253 that reports the same error. I have updated the conclusions.

**Comment by Rebits** [comment] 2024-02-26 09:54
@rafabailon, it appears that the issue at hand may not be directly connected to this current situation. It seems that certain dynamic fields are being erroneously marked as extra, potentially linked to the matter discussed in https://github.com/wazuh/wazuh-jenkins/issues/5132.

**Comment by rafabailon** [comment] 2024-02-27 12:59
> @rafabailon, it appears that the issue at hand may not be directly connected to this current situation. It seems that certain dynamic fields are being erroneously marked as extra, potentially linked to the matter discussed in [wazuh/wazuh-jenkins#5132](https://github.com/wazuh/wazuh-jenkins/issues/5132).

I have updated the information with the issue you mention

**Comment by Rebits** [comment] 2024-02-27 15:33
LGTM

**Comment by juliamagan** [comment] 2024-02-27 15:53
I think the first issue was closed because the error does not seem to have been reproduced, but since it has reappeared, the issue should be reopened for triage.

**Comment by juliamagan** [comment] 2024-02-27 16:31
LGTM

**Closed by juliamagan** 2024-02-27 16:31 UTC
Labels: type/test, level/subtask
