### ISSUE TITLE
WAZUH CUSTOM RULES DO NOT FILTER OUT DEFAULT RULES 

### ISSUE THREAD

**Issue by jaoglesbee** [wazuh/wazuh#25557] opened 2024-09-03 12:45 UTC
|4.8| RULES CUSTOMRULES.XML | BROKEN |
|---| --- | --- |
| X.Y.Z-rev | Rules/Decoders | New/Error/Improve |

## Description

I have reached out everywhere i can find to get an anwser to this and im at my last resort, in wazuh when i want to filter out a rule based on a specific program it is broken. For example rule 60107 Failed attempt to perform a privelage operation chrome is triggering this event and it is a false positive. 
data.win.eventdata.processName | C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe

so, i have added this to my local rules file to filter that event 

<rule id="10002" level="0">
    <if_sid>60107</if_sid>
    <field name="win.system.eventID">^577$|^4673$</field>
    <field name="win.eventdata.processName">\\Program Files\\Google\\Chrome\\Application\\chrome.exe</field>
    <options>no_full_log</options>
    <description>Exclude Chrome from "Failed attempt to perform a privileged operation." event.</description>
    <mitre>
    <id>T1078</id>
    </mitre>
    <group>suppression-rules</group>
</rule>

THIS DOES NOT WORK I HAVE TRIED MULTIPLE VARIATIONS OF THIS AND NOTHING WORKS. EVENTS STILL GET TRIGGERED UNDER 60107 WITH A LEVEL OF 4 PLEASE HELP!!

</body>
</html>

**Comment by juliancnn** [comment] 2024-09-09 14:07
Hi jaoglesbee ,

Could you share with us the alert in json format, extracted from `/var/ossec/logs/alerts/alerts.json` that you want to silence? It is to be able to verify the rule locally.

**Comment by jaoglesbee** [comment] 2024-09-09 16:00
yes i will share it now, a quick update i used this as a custom rule for chrome.exe as reccomended by others and it did filter it but it only changed the rule ID to rule id 11 and when i click the hyperlink on the alert it says error rule id not found so im very confused..

<rule id="100110" level="0">
    <if_sid>60107</if_sid>
    <field name="win.eventdata.processName">chrome.exe</field>
    <description>Rule to mute chrome.exe</description>
</rule>

![image](https://github.com/user-attachments/assets/59de855a-acb5-4b6b-9d22-a83c8bf2b8ed)
![image](https://github.com/user-attachments/assets/7ffe7dcb-7078-4a9c-bab8-4bbb5d42620e)

**Comment by jaoglesbee** [comment] 2024-09-09 16:15
{
  "_index": "wazuh-alerts-4.x-2024.09.09",
  "_id": "voiK15EBePZyNmzS9W8X",
  "_version": 1,
  "_score": null,
  "_source": {
    "cluster": {
      "node": "worker01",
      "name": "wazuh"
    },
    "input": {
      "type": "log"
    },
    "agent": {
      "name": "wsjaoglesbee",
      "id": "002"
    },
    "manager": {
      "name": "wazuh.worker"
    },
    "data": {
      "win": {
        "eventdata": {
          "subjectLogonId": "0x21efda",
          "subjectUserSid": "S-1-5-21-4036470205-3564954405-1495889348-12868",
          "processId": "0x4890",
          "processName": "C:\\\\Program Files\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe",
          "subjectDomainName": "INET",
          "objectServer": "Security",
          "privilegeList": "SeProfileSingleProcessPrivilege",
          "subjectUserName": "JAOglesbee"
        },
        "system": {
          "eventID": "4673",
          "keywords": "0x8010000000000000",
          "providerGuid": "{54849625-5478-4994-a5ba-3e3b0328c30d}",
          "level": "0",
          "channel": "Security",
          "opcode": "0",
          "message": "\"A privileged service was called.\r\n\r\nSubject:\r\n\tSecurity ID:\t\tS-1-5-21-4036470205-3564954405-1495889348-12868\r\n\tAccount Name:\t\tJAOglesbee\r\n\tAccount Domain:\t\tINET\r\n\tLogon ID:\t\t0x21EFDA\r\n\r\nService:\r\n\tServer:\tSecurity\r\n\tService Name:\t-\r\n\r\nProcess:\r\n\tProcess ID:\t0x4890\r\n\tProcess Name:\tC:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\r\n\r\nService Request Information:\r\n\tPrivileges:\t\tSeProfileSingleProcessPrivilege\"",
          "version": "0",
          "systemTime": "2024-09-09T16:08:01.9764485Z",
          "eventRecordID": "40892905",
          "threadID": "13208",
          "computer": "WSJAOglesbee.inet.coaaa.org",
          "task": "13056",
          "processID": "4",
          "severityValue": "AUDIT_FAILURE",
          "providerName": "Microsoft-Windows-Security-Auditing"
        }
      }
    },
    "rule": {
      "mail": false,
      "level": 4,
      "groups": [
        "stats"
      ],
      "id": "11"
    },
    "location": "EventChannel",
    "decoder": {
      "name": "windows_eventchannel"
    },
    "id": "1725898091.122081179",
    "full_log": "The average number of logs between 16:00 and 17:00 is 107. We reached 1358.",
    "timestamp": "2024-09-09T16:08:11.388+0000"
  },
  "fields": {
    "timestamp": [
      "2024-09-09T16:08:11.388Z"
    ]
  },
  "sort": [
    1725898091388,
    1
  ],
  "isAnchor": true
}


here is json thank you

**Comment by juliancnn** [comment] 2024-09-09 17:34
Hi @jaoglesbee ,

The problem is in the regex, if you pay attention to the event, there can be 4 characters ``, these are grouped by 2, since it is a character that in json must be escaped, so in fact the path is separated by 2 `` and not by one. I recommend that you use a regex like the following to avoid these problems:

```xml
  <rule id="10003" level="0">
    <if_sid>60107</if_sid>
    <field name="win.system.eventID">^577$|^4673$</field>
    <!--
    <field name="win.eventdata.processName">\\\\Program Files\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe</field>
    -->
    <field name="win.eventdata.processName" type="pcre2">[\\]{1,2}Program Files[\\]{1,2}Google[\\]{1,2}Chrome[\\]{1,2}Application[\\]{1,2}chrome\.exe</field>
    <options>no_full_log</options>
    <description>Exclude Chrome from "Failed attempt to perform a privileged operation." event.</description>
    <mitre>
    <id>T1078</id>
    </mitre>
    <group>suppression-rules</group>
</rule>
```
Let me know if this solved the rule problem.

Regards.

**Comment by jaoglesbee** [comment] 2024-09-09 18:29
ok i have added this rule to my list thank you i will test it now.. but i would like to understand further what exactly you mean by this  these are grouped by 2, since it is a character that in json must be escaped, so in fact the path is separated by 2  can you please explain so i  understand better?

**Comment by juliancnn** [comment] 2024-09-09 19:39
Of course, no problem.
In json, slashes are a special character, so if you want to represent a slash `\` you have to escape it with another slash `\`.
For example, suppose you have the string `I am a slash \ and I must be escaped.` If you want to store this content in a json string then the json string would be `"I am a slash \\ and I must be escaped."`. These definitions are part of the json standard: https://www.json.org/json-en.html

In the json that you have shared, i.e. the json of the event, you can see the following field:
```json
   "processName": "C:\\\\Program Files\\\\Google\\\\Chrome\\\\Application\\\\chrome.exe",
```
As you can see in the value of the `processName` field, 4 slashes `\` are used to separate the directories. This means, that in fact the content (string) of processName is:
```plaintext
C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe
```

This is why you need to make a regex that matches 2 slashes and not one like the regex you have shared:
```xml
    <field name="win.eventdata.processName">\\Program Files\\Google\\Chrome\\Application\\chrome.exe</field>
```

On the other hand, remember that in regex `\\` is a single slash and not 2, since the slash is a character that must be escaped,  both in [os_regex](https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions) and in [pcre2](https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions).

**Comment by JcabreraC** [comment] 2024-09-19 11:12
As @juliancnn mentioned, the issue was related to the construction of the rule's regex.

I'm closing this issue now, but please feel free to reach out if you have any further questions.

**Closed by JcabreraC** 2024-09-19 11:12 UTC
Labels: reporter/community
