### ISSUE TITLE
PagerDuty integration doesn't create alerts

### ISSUE THREAD

**Issue by oz17il** [wazuh/wazuh#3639] opened 2019-07-09 10:52 UTC
I have some issue with PagerDuty integration.
All settings set and logs seem ok. Still, no incidents create on the PagerDuty side.
Environment:
OS: Ubuntu 18.04
Wazuh version: 3.9.2
Pagerduty API version: v2

P.S - slack integration works ok.
![pagererror](https://user-images.githubusercontent.com/52443245/60882348-5776d600-a250-11e9-9a73-389f8f747237.png)

Logs:
Tue Jul  9 09:54:31 UTC 2019 /var/ossec/integrations/pagerduty /tmp/pagerduty-1562666071-1063734621.alert xxxxxxxxx
Tue Jul  9 09:54:31 UTC 2019 /var/ossec/integrations/pagerduty /tmp/pagerduty-1562666071-1885643350.alert  xxxxxxxxx
Tue Jul  9 09:54:43 UTC 2019 /var/ossec/integrations/pagerduty /tmp/pagerduty-1562666083-1679382591.alert  xxxxxxxxx
Tue Jul 09 09:54:43 UTC 2019 /tmp/slack-156266xxx.alert https://hooks.slack.com/services/xxxxxxxxxxxxx/xxxxxxxxmjNpPJlfGVwu > /dev/null

**Comment by Zenidd** [comment] 2019-07-15 11:36
Hi @oz17il,

First of all, sorry for the late reply.

I've tried to recreate your environment successfully and I think I've found the cause of your problem:

- To enable PagerDuty integration, i added the integration configuration block to ossec.conf and then i followed the [PagerDuty Generating API Key document](https://support.pagerduty.com/docs/generating-api-keys) to generate my API Token. I filled the `<api_key>` tag on `ossec.conf` and then I faced the same behavior as you: all the settings seem correct but the notifications do not appear in PagerDuty.

- After a while of research I have found that it is necessary to create a new integration and generate it's own API Token.  It is not enough just to generate a generic Token API.


### The solution:

Please, to generate the right API Token on PagerDuty go to:

```
Configuration --> Services --> "YourService" --> Integrations --> New Integration --> Use our API directly
```

The API token generated in this way should allow alerts to appear in PagerDuty.
<br></br>
Please, let me know if it helps ! If this doesn't solve your problem we can look for other ways.

Kind regards,

Juan Pablo Sáez

**Comment by oz17il** [comment] 2019-07-16 07:20
> n

Hi, 

I already tried this workflow but still no new incidents. 
I also tried to run the script manually and got this error: 

root@ip-10-0-0-1:/var/ossec/logs# /var/ossec/integrations/pagerduty /tmp/pager.json 7c5f370830ac4ec1111111111

/var/ossec/integrations/pagerduty: 82: /var/ossec/integrations/pagerduty: Bad substitution

**Comment by oz17il** [comment] 2019-07-16 07:21
> Hi @oz17il,
> 
> First of all, sorry for the late reply.
> 
> I've tried to recreate your environment successfully and I think I've found the cause of your problem:
> 
> * To enable PagerDuty integration, i added the integration configuration block to ossec.conf and then i followed the [PagerDuty Generating API Key document](https://support.pagerduty.com/docs/generating-api-keys) to generate my API Token. I filled the `<api_key>` tag on `ossec.conf` and then I faced the same behavior as you: all the settings seem correct but the notifications do not appear in PagerDuty.
> * After a while of research I have found that it is necessary to create a PagerDuty new integration and generate it's own API Token.  It is not enough just to generate a generic Token API.
> 
> ### The solution:
> Please, to generate the right API Token on PagerDuty go to:
> 
> ```
> Configuration --> Services --> "YourService" --> Integrations --> New Integration --> Use our API directly
> ```
> 
> The API token generated in this way should allow alerts to appear in PagerDuty.
> 
> 
> 
> Please, let me know if it helps ! If this doesn't solve your problem we can look for other ways.
> 
> Kind regards,
> 
> Juan Pablo Sáez



> Hi @oz17il,
> 
> First of all, sorry for the late reply.
> 
> I've tried to recreate your environment successfully and I think I've found the cause of your problem:
> 
> * To enable PagerDuty integration, i added the integration configuration block to ossec.conf and then i followed the [PagerDuty Generating API Key document](https://support.pagerduty.com/docs/generating-api-keys) to generate my API Token. I filled the `<api_key>` tag on `ossec.conf` and then I faced the same behavior as you: all the settings seem correct but the notifications do not appear in PagerDuty.
> * After a while of research I have found that it is necessary to create a PagerDuty new integration and generate it's own API Token.  It is not enough just to generate a generic Token API.
> 
> ### The solution:
> Please, to generate the right API Token on PagerDuty go to:
> 
> ```
> Configuration --> Services --> "YourService" --> Integrations --> New Integration --> Use our API directly
> ```
> 
> The API token generated in this way should allow alerts to appear in PagerDuty.
> 
> 
> 
> Please, let me know if it helps ! If this doesn't solve your problem we can look for other ways.
> 
> Kind regards,
> 
> Juan Pablo Sáez

Hi,

I already tried this workflow but still no new incidents.
I also tried to run the script manually and got this error:

root@ip-10-0-0-1:/var/ossec/logs# /var/ossec/integrations/pagerduty /tmp/pager.json 7c5f370830ac4ec1111111111

/var/ossec/integrations/pagerduty: 82: /var/ossec/integrations/pagerduty: Bad substitution

**Comment by Zenidd** [comment] 2019-07-16 07:29
Hi @oz17il,

I had the same problem. Make sure you change 
```
#!/bin/sh 
```
at the top of your script. Instead, you should add
```
#!/bin/bash
```
Please, let me know if it helps.

Greetings,

Juan Pablo Sáez

**Comment by oz17il** [comment] 2019-07-16 08:53
> Hi @oz17il,
> 
> I had the same problem. Make sure you change
> 
> ```
> #!/bin/sh 
> ```
> 
> at the top of your script. Instead, you should add
> 
> ```
> #!/bin/bash
> ```
> 
> Please, let me know if it helps.
> 
> Greetings,
> 
> Juan Pablo Sáez

Thanks, it works!!
One more thing - it seems that Slack and PagerDuty integrations cant work together. 
as you can see, the alert send at the same time there is a problem: Slack generate the alert without problems while PagerDuty trying to send the Slack alert:

Tue Jul 16 08:47:02 UTC 2019 /tmp/slack-1563266822-387163777.alert https://hooks.slack.com/services/T063XRE2H/BL29DQ9SR/4YSRfDFzAdVR1111111 > /dev/null
Tue Jul 16 08:47:02 UTC 2019 /var/ossec/integrations/pagerduty /tmp/slack-1563111822-387163777.alert e43b13f84ea2462ba3bddb1111111

**Comment by Zenidd** [comment] 2019-07-16 10:12
Hi again @oz17il,

I've been able to recreate your environment successfully:

As you said, when `Slack` and `PagerDuty` integrations are running simultaneously, the alerts are only displayed in `PagerDuty`. Using debug mode for integratord ( `integrator.debug=2` on `/var/ossec/etc/internal_options.conf`) throws no errors on `/var/ossec/logs/ossec.log`

To check if this happens whenever two integrations are made simultaneously, I have tried to configure the Slack and Jira integrations. The generated alerts can be viewed in both apps and no errors on `/var/ossec/logs/ossec.log`

Then I tried to use the pagerduty and jira integrations simultaneously and found the following error (the alerts appear only in PagerDuty):

```
2019/07/16 12:01:25 ossec-integratord[17061] integrator.c:410 at OS_IntegratorD(): ERROR: Unable to run integration for custom-jira -> /var/ossec/integrations/custom-jira
2019/07/16 12:01:25 ossec-integratord[17061] integrator.c:411 at OS_IntegratorD(): ERROR: While running custom-jira -> /var/ossec/integrations/custom-jira. Output: ValueError: No JSON object could be decoded
```

There seems to be a problem with PagerDuty integration that does not allow another integration to work simultaneously. 

Let me investigate the causes of this problem.

Greetings,

Juan Pablo Sáez

**Comment by oz17il** [comment] 2019-07-16 12:28
> Hi again @oz17il,
> 
> I've been able to recreate your environment successfully:
> 
> As you said, when `Slack` and `PagerDuty` integrations are running simultaneously, the alerts are only displayed in `PagerDuty`. Using debug mode for integratord ( `integrator.debug=2` on `/var/ossec/etc/internal_options.conf`) throws no errors on `/var/ossec/logs/ossec.log`
> 
> To check if this happens whenever two integrations are made simultaneously, I have tried to configure the Slack and Jira integrations. The generated alerts can be viewed in both apps and no errors on `/var/ossec/logs/ossec.log`
> 
> Then I tried to use the pagerduty and jira integrations simultaneously and found the following error (the alerts appear only in PagerDuty):
> 
> ```
> 2019/07/16 12:01:25 ossec-integratord[17061] integrator.c:410 at OS_IntegratorD(): ERROR: Unable to run integration for custom-jira -> /var/ossec/integrations/custom-jira
> 2019/07/16 12:01:25 ossec-integratord[17061] integrator.c:411 at OS_IntegratorD(): ERROR: While running custom-jira -> /var/ossec/integrations/custom-jira. Output: ValueError: No JSON object could be decoded
> ```
> 
> There seems to be a problem with PagerDuty integration that does not allow another integration to work simultaneously.
> 
> Let me investigate the causes of this problem.
> 
> Greetings,
> 
> Juan Pablo Sáez

PagerDuty and Slack can't work together, as you can see in the attached screenshot logs, Slack trying to send the same alert name as PagerDuty, instead of generating a slack alert format. 

![image](https://user-images.githubusercontent.com/52443245/61294353-4c86ed00-a7de-11e9-9d71-91a57ebde5aa.png)

**Comment by Zenidd** [comment] 2019-07-16 16:00
Hi again @oz17il,

After some research, the behavior you have observed in your simultaneous integrations is a bug in the integrator.c code. 

I've opened an issue with all the information, you can track the progress there: https://github.com/wazuh/wazuh/issues/3670 

Greetings, Juan Pablo Sáez

**Comment by oz17il** [comment] 2019-07-17 07:39
> Hi again @oz17il,
> 
> After some research, the behavior you have observed in your simultaneous integrations is a bug in the integrator.c code.
> 
> Wazuh version	Component	Install type	Install method	Platform
> 3.9.2	Integratord	Manager	All	Supported OS
> Use of simultaneous integrations results in error and integration deactivation on blocks subsequent to the first.
> 
> In the following example 3 integrations are used simultaneously:
> 
> ```
> <integration>
>   <name>slack</name>
>   <hook_url>MY_HOOK_URL</hook_url>
>   <alert_format>json</alert_format>
> </integration>
> 
> <integration>
>   <name>pagerduty</name>
>   <api_key>MY_API_KEY</api_key>
> </integration>
> 
> <integration>
>   <name>custom-jira</name>
> <group>syscheck</group>
> <hook_url>MY_HOOK_URL</hook_url>
>   <api_key>MY_APY_KEY</api_key>
>   <alert_format>json</alert_format>
> </integration>
> ```
> 
> The further debug output on ossec.log shows that the alert file generated for the first integration is attempted to be used to the others:
> 
> ```
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/slack /tmp/slack-1563289721-1465517659.alert  https://hooks.slack.com/services/TKVXXXX9E/BKXXXLT/9ol6WiS4XXXXXXXXPDwbtsX debug
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:414 at OS_IntegratorD(): DEBUG: Command ran successfully
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/pagerduty /tmp/slack-1563289721-1465517659.alert dcd07XXXXXXXXX0d6e3b9e29  debug
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:414 at OS_IntegratorD(): DEBUG: Command ran successfully
> 2019/07/16 17:08:41 ossec-integratord[22326] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/custom-jira /tmp/slack-1563289721-1465517659.alert id@mail.com:J1RcUlmzS6aXXXXXXX788A https://wazuhtest.atlassian.net/rest/api/2/issue/ debug
> 2019/07/16 17:08:42 ossec-integratord[22326] integrator.c:414 at OS_IntegratorD(): DEBUG: Command ran successfully
> ```
> 
> In detail:
> 
> ```
> /var/ossec/integrations/slack /tmp/slack-1563289721-1465517659.alert
> /var/ossec/integrations/pagerduty /tmp/slack-1563289721-1465517659.alert
> /var/ossec/integrations/custom-jira /tmp/slack-1563289721-1465517659.alert
> ```
> 
> Another example with other integration order:
> 
> ```
> <integration>
>   <name>custom-jira</name>
> <group>syscheck</group>
> <hook_url>MY_HOOK_URL</hook_url>
>   <api_key>MY_APY_KEY</api_key>
>   <alert_format>json</alert_format>
> </integration>
> 
> <integration>
>   <name>slack</name>
>   <hook_url>MY_HOOK_URL</hook_url>
>   <alert_format>json</alert_format>
> </integration>
> 
> <integration>
>   <name>pagerduty</name>
>   <api_key>MY_API_KEY</api_key>
> </integration>
> ```
> 
> ossec.log output:
> 
> ```
> 2019/07/16 17:13:10 ossec-integratord[3982] integrator.c:131 at OS_IntegratorD(): DEBUG: sending new alert.
> 2019/07/16 17:13:10 ossec-integratord[3982] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/custom-jira /tmp/custom-jira-1563289990--2099405109.alert id@mail.com:J1RcUlmzS6aXXXXXXX788A https://wazuhtest.atlassian.net/rest/api/2/issue/ debug
> 2019/07/16 17:13:11 ossec-integratord[3982] integrator.c:414 at OS_IntegratorD(): DEBUG: Command ran successfully
> 2019/07/16 17:13:11 ossec-integratord[3982] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/slack /tmp/custom-jira-1563289990--2099405109.alert  https://hooks.slack.com/services/TKVXXXX9E/BKXXXLT/9ol6WiS4XXXXXXXXPDwbtsX debug
> 2019/07/16 17:13:12 ossec-integratord[3982] integrator.c:414 at OS_IntegratorD(): DEBUG: Command ran successfully
> 2019/07/16 17:13:12 ossec-integratord[3982] integrator.c:389 at OS_IntegratorD(): DEBUG: Running: /var/ossec/integrations/pagerduty /tmp/custom-jira-1563289990--2099405109.alert dcd07XXXXXXXXX0d6e3b9e29  debug
> ```
> 
> The integrations as Slack written in Python throw an error by the absence of the file of alert that they expect to read. This does not happen in Pagerduty integration as it is a bash script.
> 
> ```
> 2019/07/16 17:36:39 ossec-integratord[29841] integrator.c:410 at OS_IntegratorD(): ERROR: Unable to run integration for slack -> /var/ossec/integrations/slack
> 2019/07/16 17:36:39 ossec-integratord[29841] integrator.c:411 at OS_IntegratorD(): ERROR: While running slack -> /var/ossec/integrations/slack. Output: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> The error seems to be located on the loop inside [integrator.c file](https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_integrator/integrator.c#L122-L436). On this loop the structure `integrator_config[s]` is used to create custom alerts for each integration.
> 
> The s counter variable that allows to go through the structure is not increased so only the alert file corresponding to the integration whose block is the first in `ossec.conf` is generated in each while loop.
> 
> Greetings, Juan Pablo Sáez

Thanks a lot, 
One more thing - Is there a way to set alert level like that:  <level>6-9</level>
 (get only alerts between 6 and 9)  ?

**Comment by Zenidd** [comment] 2019-07-17 14:37
Hi,

Unfortunately, that's not possible. In the code below you can see how the alerts are checked against the [<level>](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/integration.html#level) set on integrator configuration block. Only the lower limit can be set.
https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_integrator/integrator.c#L168-L180

This functionality has already been requested by other users for the ossec-maild module that also has a [<level>](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/email_alerts.html#level) tag.

We will take this into account when we start working on this issue.

Greetings, Juan Pablo Sáez

**Comment by oz17il** [comment] 2019-07-25 08:45
> Hi,
> 
> Unfortunately, that's not possible. In the code below you can see how the alerts are checked against the [level](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/integration.html#level) set on integrator configuration block. Only the lower limit can be set.
> https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_integrator/integrator.c#L168-L180
> 
> This functionality has already been requested by other users for the ossec-maild module that also has a [level](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/email_alerts.html#level) tag.
> 
> We will take this into account when we start working on this issue.
> 
> Greetings, Juan Pablo Sáez

And there is a way to exclude in the integration a specific Rule ID ?

**Comment by Zenidd** [comment] 2019-07-26 09:49
Hi again @oz17il,

We don't have a way to explicitly exclude rules. Being more specific, integrations config blocks support the use of a [`<rule_id>`](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/integration.html#rule-id) tag. This tag only works with comma-separated rule IDs and does not allow [sregex](https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/regex.html#sregex-os-match-syntax) statements.

As a workaround, if the rules you want to notify in `Slack` are not too many, you could specify these rules ID's on your `integration` block as in the following example:

```
<integration>
   <name>slack</name>
   <hook_url>slack_hook_url</hook_url>
   <rule_id>ruleID1, ruleID2, ... , ruleIDn</rule_id>
   <alert_format>json</alert_format>
</integration>
```

I understand that it is easier to exclude one than to include all the others. I apologize for any inconvenience.

Greetings, Juan Pablo Sáez

**Comment by paroma96** [comment] 2019-08-14 18:41
Hi, @Zenidd .  

I've been trying to replicate it with the same configuration as mentioned but with the new version (3.9.5) instead, I've found that there might be a step missing while using the integration because I still had the following error:

```
2019/08/14 20:00:31 ossec-integratord[30337] integrator.c:399 at OS_IntegratorD(): DEBUG: integratord: {"status":"invalid event","message":"Event object is invalid","errors":["Service key is the wrong length (should be 32 characters)"]}
```

I could solve it by modifying the `/var/ossec/integrations/pagerduty` script by substituting the "service_key" value ($APIKEY) for the 32 chars integration_key that can be found at 

> Configuration > Services > Integrations. 

Then, all alerts can be checked at pagerduty website.

**Comment by PSjoe** [comment] 2019-11-26 14:09
Any news on when the bug with multiple integrations might be solved?  We're running 3.10.2 release and it appears to still be present:

`Running: /var/ossec/integrations/slack /tmp/slack-1574776696-1015598604.alert
Running: /var/ossec/integrations/pagerduty /tmp/slack-1574776696-1015598604.alert`

Whichever integration I place second never fires.  Only the first integration.

**Comment by xr09** [comment] 2020-08-05 13:08
Hey team, 

refloating this since I got to experience the bug today, as @Zenidd mentions the alert file of the first integration is being reused by the others, here in [integrator.c](https://github.com/wazuh/wazuh/blob/013bf64218540e965729547bcdb8426735d64cbb/src/os_integrator/integrator.c#L246-L247) is the relevant logic, since not all integrations use the same format this is a problem.

I'm guessing Slack and Virustotal work fine together since both use JSON, but PagerDuty doesn't. One possible solution could be switching PagerDuty script to use JSON as well.

**Comment by TomasTurina** [comment] 2022-10-18 12:40
Fixed in https://github.com/wazuh/wazuh/pull/14848

**Closed by TomasTurina** 2022-10-18 12:40 UTC
Labels: type/bug, module/integration, reporter/community
