### ISSUE TITLE
default group merged.mg error

### ISSUE THREAD

**Issue by IOTech17** [wazuh/wazuh#20851] opened 2023-12-14 12:58 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.0 | Group management | Manager | officiel docker image | n/a |

I have upgrade from Wazuh docker 4.5.2 to 4.60 then from 4.6.0 to 4.7.0

When checking the merged.mg file of the default group I get an error that the file contains an error

error on line 1 at column 847: xmlParseEntityRef: no name

![image](https://github.com/wazuh/wazuh/assets/68947790/4fde4d85-dd26-4d7e-8d71-b26d65712820)

Is this a bug or normal?

Another question is there a way to make sure any news group created get all the files the default has?

![image](https://github.com/wazuh/wazuh/assets/68947790/b48c9d66-8820-41c7-af48-119d0bb38eb3)

Thank you in advance,

**Comment by rauldpm** [comment] 2024-01-08 17:48
Investigated in https://github.com/wazuh/wazuh-docker/issues/1154

Reproduced through a 4.7.1 Wazuh installation assistant deployment, not related to Wazuh docker, added to @wazuh/core initially to triage it

**Comment by Selutario** [comment] 2024-01-09 11:01
## Update

After taking a look at the code and with the help of @Desvelao, these are the conclusions:

The dashboard is sending a `GET /groups/default/files/merged.mg/xml` API request to fetch the XML content of the `merged.mg` file. However, only `agent.conf` files are returned as XML. All others are parsed to JSON:
https://github.com/wazuh/wazuh/blob/037ede2424c1c4402068bc0a1651836f732ccc70/framework/wazuh/core/configuration.py#L819-L829

There is an XML validator in the dashboard, which is the one that shows the error message since the content obtained is JSON format.

## Proposal

As I mentioned, except for the `agent.conf` files, all others are transformed into JSON even if the `GET /groups/{group_id}/files/{file_name}/xml` endpoint is used. Also, `merged.mg` is a compressed file and is being treated as an `rcl`, so what it returns is wrong. 

We need to rethink and refactor these endpoints:
- [GET /groups/{group_id}/files/{file_name}/xml](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_group_file_xml)
- [GET /groups/{group_id}/files/{file_name}/json](https://documentation.wazuh.com/current/user-manual/api/reference.html#operation/api.controllers.agent_controller.get_group_file_json)

Since we are not transforming files to XML in the current `GET /groups/{group_id}/files/{file_name}/xml`, the endpoints should be merged into one. In this new endpoint, it should be possible to set whether the result is `json` format or `plain`.  The `merged.mg` should only be readable in plain format.

**Comment by IOTech17** [comment] 2024-01-09 11:16
Great news, so the file is fine it is just the validator trying to validate a file that is being parsed as Json not XML.

Quick question, is there a guide to get all these file to be loaded for the non default groups?

**Comment by Selutario** [comment] 2024-01-10 15:30
@IOTech17 agents can belong to multiple groups and will get files from all of them. Additionally, all of them belong to the default group unless explicitly indicated otherwise. Therefore, the easiest way to ensure that all agents have these files regardless of what other groups they belong to is to do nothing. You can take a look at this related documentation:
- [Agent groups - Wazuh doc](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html#agent-groups)

The only alternative I can think of is to manually add the files to the other groups.

**Comment by GGP1** [comment] 2024-01-26 18:09
## Update

I began analysing the affected endpoints, the potential solutions and their implications.

**Comment by GGP1** [comment] 2024-01-29 16:35
## Update

I merged both endpoints into one that contains the `return_format` parameter which can be either `plain` (default) or `json`.

I decided to make `plain` the default format since most of the files inside the `/var/ossec/etc/shared/<group>` folder are `.txt`. I also opted to let users get the `merged.mg` file in `json` format if they prefer so (I couldn't think of a reason why it would be appropiate to return an error in such case).

**Comment by GGP1** [comment] 2024-01-30 18:08
## Update

- Replaced the `return_format` parameter with `raw`.
- Created a function that parses the `merged.mg` file converting it in a list of dictionaries with the fields `file_name`, `file_size` and `file_content`.
- Tested the changes manually and updated unit and integration tests.

**Comment by GGP1** [comment] 2024-01-31 12:31
## Update

Updated the `raw` default value to `False` instead of `None` and updated the base branch.

**Comment by Selutario** [comment] 2024-02-01 16:40
Reopening this since it was closed automatically when merging the PR. The documentation will need to be updated (https://github.com/wazuh/wazuh/pull/21653#pullrequestreview-1856968111)

**Comment by GGP1** [comment] 2024-02-01 17:30
## Update

Updated the documentation RBAC reference.

**Closed** 2024-02-08 13:33 UTC
Labels: type/bug, level/task
