### ISSUE TITLE
TBD: Changed netstat command causing alerts for e.g. restarted services

### ISSUE THREAD

**Issue by ghost** [wazuh/wazuh#179] opened 2017-09-03 20:07 UTC
In https://github.com/wazuh/wazuh/pull/145 the netstat command was changed from:

``netstat -tln | grep -v 127.0.0.1 | sort``

to:

``netstat -tulpen | sort``

I'm currently seeing an issue with this change as it hasn't just added an alias and UDP support (as written in the issue description of https://github.com/wazuh/wazuh/pull/145) but also included now the program name/PID (-p parameter) as well as extended info like the inode of the program (-e parameter).

This change is now triggering an "Listened ports status (netstat) changed (new port opened or closed)." alert even after a restart of a service (the inode and PID just changed here).

**Comment by chemamartinez** [comment] 2017-09-12 16:44
You are certainly right. According to the issue https://github.com/wazuh/wazuh/issues/188, we are trying to find the best way for checking listening ports.

As you have mencioned before, this command should be consistent with its rule and show only the necessary information to trigger an alert when any port is opened or closed. For this reason, we are removing the PID and inode from the output of the default command.

Your suggestion and feedback is very welcome! Thanks.

**Comment by vikman90** [comment] 2017-09-21 09:28
Hi @kdslkdsaldsal and @chemamartinez,

We have just made three improvements to the `netstat` command by Logcollector:

1. Remove the PID info, so restarting services won't produce alert but if a different process listens to the same port that another process listened to before will do produce an alert.
2. Regarding issue https://github.com/wazuh/wazuh/issues/188 by @rwagner-inf, the port list will appear ordered by port number (mixing TCP, UDP and IPV6). This is just for convenience, the alert matching will work as long as the port list is in the same order.
3. We have improved compatibility with macOS and OpenBSD.

If you think that this is OK please close this issue.

Thanks to @crolopez for developing this task!

Best regards.

**Comment by kdslkdsaldsal** [comment] 2017-09-21 17:22
@vikman90 @crolopez Hey, thank you very much. Great work!

One remark about the comment of @rwagner-inf in 188#issuecomment-329883305:

> I also do not like the display of the Recv-Q Send-Q columns, which generate unnecessary alerts. Since the focus of this monitoring is on new ports in LISTENING mode, and the connection queue issue does not make much sense here.

It seems this is still the case when running the new netstat command from https://github.com/wazuh/wazuh/commit/e1d8bcbf053427a54cfa1aa4a1312b8cfe5b5dd6 . On a recent Debian testing i get e.g. the following output:

```
Active
Proto
tcp        0      0 127.0.0.1:25            0.0.0.0:*              
tcp6       0      0 ::1:25                  :::*                   
udp        0      0 0.0.0.0:68              0.0.0.0:*                          dhclient       
udp        0      0 0.0.0.0:123             0.0.0.0:*                          ntpd    
*snip*
```

Seems the last ``| sed 's/ [0-9]*\///'`` is trying to remove the Recv-Q / Send-Q but is failing as i get the same output without it.

**Comment by crolopez** [comment] 2017-09-21 19:05
Hi @kdslkdsaldsal,

It is true that the Recv-Q and Send-Q columns can generate unnecessary alerts. That's why they've been removed at https://github.com/wazuh/wazuh/commit/2f046c87651176f74428c7a6c8360c88ee6eaa28.

The objective of `sed' s/[0-9]*\///'` is not to remove the Recv-Q and Send-Q columns, but the PID of the process. If the same program is opened several times, it will change its PID and generate a false alert.

Thank for your feedback.

Best regards.

**Comment by kdslkdsaldsal** [comment] 2017-09-22 07:18
Hey, great work. Thanks again for the update and the additional insight about the last sed.

Looks fine for me (only tested on linux as i don't have OpenBSD nor Mac OS X) so closing here for now.

**Comment by rwagner-inf** [comment] 2017-09-28 15:08
Hi Guys.

I saw that the command was committed:
netstat -tulpn | sed -r 's/ ([A-Z]|\-|_)+//' | sed 's/:\([[:digit:]]\+\) / : \1 /' | sort -k 6 -g | sed 's/ : /:/' | sed 's/ [0-9]*\///' | sed 's/ [0-9]\+\ *[0-9]\+ //'

An adjustment was still missing.
These lines are being shown unnecessarily:
![image](https://user-images.githubusercontent.com/24550871/30974256-9fe38fec-a445-11e7-92df-40e1dc324a1e.png)


In addition, the columns still show Recv-Q and Send-Q. Would not it be nice to remove them, too?

If they decide to remove, it would be the command:
netstat -tulpn | sed 1,2d | sed -r 's/ ([A-Z]|\-|_)+//' | sed 's/:\([[:digit:]]\+\) / : \1 /' | sort -k 6 -g | sed 's/ : /:/' | sed 's/ [0-9]*\///' | sed 's/ [0-9]\+\ *[0-9]\+ //'

**Comment by crolopez** [comment] 2017-09-28 15:33
Hi @rwagner-inf,

The existence of the first 2 lines does not affect the correct operation of the command because they are not modified at any time, so they do not generate false alerts. Even so, your proposal adds aesthetic value to the output of the command, so it will be included.

Thank you for contributing to WAZUH!

Best regards.

**Comment by kdslkdsaldsal** [comment] 2017-11-27 09:27
Unfortunately i need to re-open this. It seems there are still some issues with the current rule:

```
Rule: 533 fired (level 7) -> "Listened ports status (netstat) changed (new port opened or closed)."
Portion of the log(s):
ossec: output: 'netstat listening ports':
tcp       127.0.0.1:25            0.0.0.0:*                   master        
tcp6      ::1:25                  :::*                        master        
tcp6      :::443                  :::*                        apache2        
Previous output:
ossec: output: 'netstat listening ports':
tcp       127.0.0.1:25            0.0.0.0:*                   master        
tcp6      ::1:25                  :::*                        master        
tcp6      :::443                  :::*                        apache2       
```

The ports havn't changed but if we're marking the whole output we can see two additional ending white spaces after the first ``apache2`` vs. two less in the second ``apache2`` line.

**Comment by crolopez** [comment] 2017-11-27 09:36
Hi @kdslkdsaldsal,

Thank you for reporting the bug. The netstat commands will be restructured to avoid similar bugs. In what distribution has it happened?

Best regards.

**Comment by kdslkdsaldsal** [comment] 2017-11-27 10:04
Hi,

i have observed this behavior on a current Debian Stable/Stretch.

**Comment by crolopez** [comment] 2017-12-29 11:24
Hi @ghost,
The command was corrected. You shouldn't have any problems with Debian and the latest version of Wazuh.

Best regards.

**Comment by rwagner-inf** [comment] 2018-01-02 19:04
Hi Guys!

I have the same problem, running on Centos 7 and wazuh 3.1.

The problem is some spaces, which appear at some times, at the end of the line, after the process name. I did make  a gif of the problem, it did not look so good, but I think you can see it.

![ezgif-4-243209634b](https://user-images.githubusercontent.com/24550871/34495895-04a4066a-efd6-11e7-8150-558e25bcd882.gif)

I modified the command on my agents.

**Comment by vikman90** [comment] 2018-01-02 21:13
Hi @rwagner-inf,

I'm sorry that is not the expected result of command _netstat_  in Wazuh v3.1. No pads should appear in the result.

Could you kindly confirm that the `<localfile>` setting for _netstat_  in your system is this one?

```xml
<localfile>
  <log_format>full_command</log_format>
  <command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ \([[:digit:]]*\/[[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>
  <alias>netstat listening ports</alias>
  <frequency>360</frequency>
</localfile>
```

This is an example alert for that command on CentOS 7:
```
** Alert 1514927288.1150: - ossec,pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,
2018 Jan 02 22:08:08 fedora->netstat listening ports
Rule: 533 (level 7) -> 'Listened ports status (netstat) changed (new port opened or closed).'
ossec: output: 'netstat listening ports':
tcp 0.0.0.0:22 0.0.0.0:* 693/sshd
tcp6 :::22 :::* 693/sshd
udp 127.0.0.1:323 0.0.0.0:* 619/chronyd
udp6 ::1:323 :::* 619/chronyd
udp 0.0.0.0:1514 0.0.0.0:* 25217/ossec-remoted
tcp6 :::9090 :::* 1/systemd
Previous output:
ossec: output: 'netstat listening ports':
tcp 0.0.0.0:22 0.0.0.0:* 693/sshd
tcp6 :::22 :::* 693/sshd
udp 0.0.0.0:68 0.0.0.0:* 12770/dhclient
udp 127.0.0.1:323 0.0.0.0:* 619/chronyd
udp6 ::1:323 :::* 619/chronyd
udp 0.0.0.0:1514 0.0.0.0:* 25217/ossec-remoted
tcp6 :::9090 :::* 1/systemd
```

Please double check your configuration and write back to us if the problem persists.

Best regards.

**Comment by crolopez** [comment] 2018-02-19 10:57
Hi @cfi-gb,

PID changes can be understood as abnormal or reportable behavior. If you tell me your distribution, I can give you an adapted command.

On the other hand, Wazuh will soon release a module that will replace the netstat command, and will allow monitoring other elements of the system.

Best regards.

**Comment by ebolansk** [comment] 2018-04-17 13:49
For Debian Stretch you can use the followeing command to supress the Process-IDs:

<command>netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ [[:digit:]]*\/\([[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d</command>

Best regards.

**Comment by mdklapwijk** [comment] 2018-09-27 11:50
@crolopez, yes changing PIDs might be a reportable event, but not within this particular event/rule, as it should only be about the listening ports.  I suspect we were getting a lot of 'false positives' due logrotates etc.

The solution @ebolansk suggested, is exactly the same as we came up with and seems to do the job.

**Comment by hemedga** [comment] 2019-07-16 07:41
What is the status on this?
We experience the same issues with PID change.

**Comment by crolopez** [comment] 2019-07-16 09:39
Hi @hemedga,

The process of detecting changes in the ports of an agent/manager through calls to `netstat` is going to be deprecated in a future release due to the complexity of the commands and how unmaintainable they are.

Syscollector will be able to handle the integrity of the ports inventory, reporting only those that have changed efficiently. In addition, information relating to each port will be available for on-demand consultation from the APP. Related issue: https://github.com/wazuh/wazuh/issues/742

A solution to distinguish in 2 rules the PID change from the port state change would be to configure 2 `netstat` commands with 2 different aliases. By this way, the first command will only monitor port changes and ignore PIDs (should be sufficient with the default netstat command, associated with rule 533) and the second will ignore ports changes to focus on PID changes.

Note that the second rule would be identical to 533 except for the alias (`netstat listening ports`), which should refer to the second localfile block.

If you wish, you can explain your use case and what systems you use to help you with the commands and rules.

Best regards.

**Comment by hemedga** [comment] 2019-07-17 02:26
I'm not entirely sure about the future Syscollector because I'm not familiar with the feature, but I can tell you that there is a more straightforward way to handle the complexity of `netstat` and the method of controlling the output.

First move away from `netstat `because other commands are replacing it, for this situation I will use `ss`.

Please review the output of the following commands:
```
# ss -46 state listening | awk '{print $4}'
Local
*%ens33:ipv6-icmp
[::]:ssh
*:55000
[::1]:6010
[::1]:6011
[::1]:6012
[::1]:6013
[::ffff:127.0.0.1]:9200
[::1]:9200
[::ffff:127.0.0.1]:9300
[::1]:9300
```
or
```
# ss -tu state listening | awk '{print $4}'
Local
0.0.0.0:ssh
127.0.0.1:6010
127.0.0.1:6011
127.0.0.1:6013
127.0.0.1:5601
0.0.0.0:1515
127.0.0.53%lo:domain
[::]:ssh
*:55000
[::1]:6010
[::1]:6011
[::1]:6013
[::ffff:127.0.0.1]:9200
[::1]:9200
[::ffff:127.0.0.1]:9300
[::1]:9300
```

Note: `awk` can remove the first line but I think this will complicate the solution

**Comment by crolopez** [comment] 2019-07-17 11:03
Your solution can replace the default one included in Wazuh's configuration templates to detect port changes, and possibly the use of `ss` is more universal than `netstat`.

We know that `awk` is a cleaner and more straightforward solution to filter the command's output, but we can't include it in the default configuration because we have found systems compatible with Wazuh that didn't have it installed. For this reason, we use `grep` instead.

The best solution for managing port state integrity is to abstract to the configuration of call commands using `netstat` or `ss` and extract them automatically and natively. That will be the improvement of Syscollector (#742). 

Because of this, the default command to report port changes will not change unless it includes some bug that generates false positives or it does not work as expected. Is this your case?

Best regards.

**Comment by hemedga** [comment] 2019-07-18 04:01
It doesn't work as expected for me because of PID changes and it's a non-issue because I know how to handle it.

As for your comments, I'll give some feedback from my perspective:
`ss` is replacing `netstat` for the use case we are looking at, in the long run, it is recommended to move away from `netstat`. I Understand it's a waste of time at the moment but should be definitely considered if the project won't migrate to Syscollector.

`awk` is globally installed on all new *NIXs.  It is true that very old systems didn't come with it preinstalled and some Solaris versions also lack the program preinstalled. For the community, I think that `awk` is much better than `sed` for the functionality. 

Finally, if you want me to prepare a tested pull request, I'll happily do so because I'm doing the change for my customers anyway.

**Comment by crolopez** [comment] 2019-07-18 08:35
Of course, your help will be greatly appreciated.

The default `ossec.conf` file is generated following the template structure configured in [wazuh/etc/templates/config](https://github.com/wazuh/wazuh/tree/v3.9.3/etc/templates/config). This applies to all Wazuh-compatible systems except for Windows, which loads its configuration from [this file](https://github.com/wazuh/wazuh/blob/v3.9.3/src/win32/ossec.conf) for Windows Vista or higher or from [this file](https://github.com/wazuh/wazuh/blob/v3.9.3/src/win32/ossec-pre6.conf) for Windows XP or lower.

The configuration templates must have the following structure: `<component>.<target>.template`. 
- **Component**: configuration block on which the template configuration will be applied. In this case, it will be `localfile-commands`.
- **Target**: Type of installation on which it will be applied (manager/agent). If not specified, it will affect both.

If a template is not found in the OS tree for the agent/manager distribution, the default configuration applied will be the one found in the `generic` folder.

For example, the file [wazuh/etc/templates/config/bsd/localfile-commands.template](https://github.com/wazuh/wazuh/blob/v3.9.3/etc/templates/config/bsd/localfile-commands.template) has te default `netstat` command from managers (currently not supported) and agents BSD. However, this file does not exist in [wazuh/etc/templates/config/ubuntu/16/04/](https://github.com/wazuh/wazuh/blob/v3.9.3/etc/templates/config/ubuntu/16/04), which means that this command will be taken from [wazuh/etc/templates/config/generic/localfile-commands.template](https://github.com/wazuh/wazuh/blob/v3.9.3/etc/templates/config/generic/localfile-commands.template) for Ubuntu 16.04.

For your use case, if you have tested `ss` command for Ubuntu 18.04, you can create the folder `wazuh/etc/templates/config/ubuntu/18/04/` and adding it following the netstat block structure.

Note that the alias section is fundamental to the generation of rule `533`. If you want to change `netstat listening ports` by `ss listening ports`, you will have to modify the following rule:

https://github.com/wazuh/wazuh/blob/852146faece1c041c8b90045d8a53bd6a4f037a1/etc/rules/0015-ossec_rules.xml#L172-L178

To maintain compatibility with netstat events, you can make the following modification. In addition, we can make the description more generic by removing the netstat word:

``` XML
<rule id="533" level="7">
    <if_sid>530</if_sid>
    <match>ossec: output: 'netstat listening ports|ossec: output: 'ss listening ports</match>
    <check_diff />
    <description>Listened ports status changed (new port opened or closed).</description>
    <group>pci_dss_10.2.7,pci_dss_10.6.1,gpg13_10.1,gdpr_IV_35.7.d,</group>
</rule>
```

When you do PR, don't forget to indicate the systems in which you have tested it.

Thank you for your collaboration!

Best regards.

**Comment by maltfield** [comment] 2020-05-12 17:07
I had to address this issue because the built-in `netstat` command was picking-up processes that weren't actually just LISTENing. Namely, it picked-up postfix's intermittent `local` package, which had an non-listening UDP socket open.

> `awk` is a cleaner and more straightforward solution to filter the command's output, but we can't include it in the default configuration because we have found systems compatible with Wazuh that didn't have it installed. For this reason, we use `sed` instea

Here's an `awk`-free solution with `sed`

```
root@host:/var/ossec# ss -Htunp state listening | sed 's/\([[:alnum:]]\+\)[[:space:]]\+[[:digit:]]\+[[:space:]]\+[[:digit:]]\+[[:space:]]\+\(.\+\)\?:\([[:digit:]]*\)[[:space:]]\+\(.\+\)\?\*[[:space:]]\+\(users.*\)/\1 \2:\3 \4 \5/'                                           
tcp 127.0.0.1:25 0.0.0.0: users:(("master",pid=2012,fd=13))
tcp 0.0.0.0:443 0.0.0.0: users:(("nginx",pid=28110,fd=18),("nginx",pid=28108,fd=18))
...
root@host:/var/ossec# 
```

**Comment by CODE-REaD** [comment] 2020-06-05 19:44
**Environment: CentOS 7, Wazuh agent 3.12.0**.
Dear Wazuh Team,
This problem of false positives due to process id's being interpreted as a change in listened ports has degraded my experience of Wazuh and delayed its progress as a project at my company.  Following extensive research I have located its source as reported here.  I am grateful to have found this information, but disappointed that a solution is not pending due to issues such as a) netstat will "soon" be replaced by a module (Feb 19, 2018) or b) ss is replacing netstat (Jul 16, 2019).

The false positive report I receive as frequently as every 5 minutes, `Listened ports status (netstat) changed (new port opened or closed).`, is not inaccurate, just irrelevant, because as described by others already, my server spawns new httpd listeners routinely based on demand.  This behavior is entirely normal for Apache.

The resulting flood of alerts renders other alerts much less visible.  Because no other remedy for this is available, I will revise my ossec.conf files, changing `netstat -tulpen` to `netstat -tulen` as a workaround, and now I will need to manage this customization on future deployments.

I understand the need for vision, but out of concern for the success of Wazuh **I wish leadership emphasized break-fixes in this type of case.**  I agree with @ghost,

> Sure, i could revert the mentioned command at my installation. But that wouldn't resolve the issue that the newer command is now causing a wrong alert on every Wazuh instance out there about a new port opened or closed port if only the PID (happens at a restart) or the Inode (happens here without a restart) is changed.

**Comment by TomasTurina** [comment] 2020-07-29 21:00
This functionality was designed to process the output of a configurable command.

There are several use cases that can fit within this request, but the one we provide by default is to monitor all ports in listening state (TCP and UDP) retrieved with the `netstat` command (including process info) and filtering them with `sed`.

We use both `netstat` and `sed` commands by default because they are compatible with all the systems we support. For example, replacing `netstat` with `ss` will cause us to lose support with macOS systems, while replacing `sed` with` awk` will be a problem for older systems.

I've tested the configuration we give and it works as expected on all Wazuh supported systems. It is true that it includes the PID of the process and any restart of the process will trigger an alert, but as I said before, this would be a different use case that can be implemented by changing the command executed by a new one. For example, the command that can be used to avoid the PID of the process is the following (https://github.com/wazuh/wazuh/issues/179#issuecomment-381999277):

```bash
netstat -tulpn | sed 's/\([[:alnum:]]\+\)\ \+[[:digit:]]\+\ \+[[:digit:]]\+\ \+\(.*\):\([[:digit:]]*\)\ \+\([0-9\.\:\*]\+\).\+\ [[:digit:]]*\/\([[:alnum:]\-]*\).*/\1 \2 == \3 == \4 \5/' | sort -k 4 -g | sed 's/ == \(.*\) ==/:\1/' | sed 1,2d
```

If you want to change this command to one that uses `ss` and/or `awk`, you can also do it. Both proposed commands are valid (https://github.com/wazuh/wazuh/issues/179#issuecomment-627473264 and https://github.com/wazuh/wazuh/issues/179#issuecomment-639753715), just make sure they are compatible with the systems you monitor. To make these types of changes, I will recommend that you use the centralized configuration that Wazuh has to easily distribute the configuration changes you need with all agents connected to a manager. You can find information about this feature at [this link](https://documentation.wazuh.com/3.13/user-manual/reference/centralized-configuration.html?highlight=centralized%20configuration), and there is also a blogpost that explains how to do this [here](https://wazuh.com/blog/agent-groups-and-centralized-configuration/).

I'll also mention that the [syscollector module](https://documentation.wazuh.com/3.13/user-manual/capabilities/syscollector.html#ports) is capable of monitoring port states and can perform scans at configurable time intervals. Also, we are currently working on a new feature that will allow syscollector to report, for example, only those ports that change between different scans. You can track the status of this feature [here](https://github.com/wazuh/wazuh/issues/4316).

I hope this information can answer all your questions.

Best regards.

**Closed** 2020-09-07 08:15 UTC
Labels: community, question

**Comment by mdklapwijk** [comment] 2020-11-18 08:23
@TomasTurina, with which program ports are checked are not the issue at hand in this ticket. What @ghost and others of us were reporting is the incorrect inclusion of inode and pid in the result of the "listening port check". Including those triggers a lot of false alerts.

Packages I noticed where this to be cumbersome:
- logrotate; tends to reload/restart services every night
- postfix ; tends to change its name/pid every once in a while
- apache; tends to get restarted on config changes or cycled on busy servers.

If one would like the check to include the pid and inode to be checked, it should be named something like "pid, inode and listening port check" and its messages in the alerts should clearly state what has changed (pid, inode or port), not "Listened ports status (netstat) changed (new port opened or closed)."

But out of the box a "listening port check" should only just do that; check for changes in the ports open for incoming connections.
