### ISSUE TITLE
The Wazuh manager does not start correctly in the registration test due to wazuh-modulesd

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh#23111] opened 2024-04-24 13:26 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.7.4-rc1 | wazuh-modulesd | Manager | Packages | Debian 9 |

## Description

In the analysis of the issue https://github.com/wazuh/wazuh/issues/23103, the following error has been found starting the Wazuh manager:

```
11:30:48  wazuh-modulesd: Process 7787 not used by Wazuh, removing...
11:30:48  wazuh-modulesd did not start correctly.
```

The previous task was `Stop Wazuh manager` and it did not report any error, and it is possible to see a message about killing wazuh-modulesd

```
11:30:24  wazuh-clusterd not running...
11:30:24  Killing wazuh-modulesd...
11:30:24  Killing wazuh-monitord...
11:30:24  Killing wazuh-logcollector...
11:30:24  Killing wazuh-remoted...
11:30:24  Killing wazuh-syscheckd...
11:30:24  Killing wazuh-analysisd...
11:30:24  wazuh-maild not running...
11:30:24  Killing wazuh-execd...
11:30:24  Killing wazuh-db...
11:30:24  Killing wazuh-authd...
11:30:24  wazuh-agentlessd not running...
11:30:24  wazuh-integratord not running...
11:30:24  wazuh-dbd not running...
11:30:24  wazuh-csyslogd not running...
11:30:24  Killing wazuh-apid...
11:30:24  Wazuh v4.7.4 Stopped
```

The CI build where this has been found is https://ci.wazuh.info/job/Test_registration/10280/
- [output.log](https://github.com/wazuh/wazuh/files/15111892/output.log)

**Comment by Dwordcito** [comment] 2024-04-24 14:37
Do you have reliable reproduction steps?
Do you have an environment with the issue playing consistently?
Do you have a segmentation fault dump?

Blocked, until you have enough information to do the root cause analysis.

**Comment by rauldpm** [comment] 2024-04-24 15:15
> Do you have reliable reproduction steps?

The issue has the full build output in the link provided, with all steps executed in order, as I say in the following point, I have not been able to reproduce it

> Do you have an environment with the issue playing consistently?

You can try to reproduce it by executing new builds or executing the steps locally in a VM, I executed five tests with success status

- https://ci.wazuh.info/job/Test_registration/10299/console
- https://ci.wazuh.info/job/Test_registration/10301/console
- https://ci.wazuh.info/job/Test_registration/10302/console
- https://ci.wazuh.info/job/Test_registration/10300/console
- https://ci.wazuh.info/job/Test_registration/10303/console

However, I think we have a clear point of failure: `the "wazuh-control stop" didn't kill the wazuh-modulesd process and ended as if it did`

> Do you have a segmentation fault dump?

No, I have a wazuh-modulesd error message and a wazuh-control start in a failed state

**Comment by Dwordcito** [comment] 2024-04-24 15:59
1- Low prevalence, Intermittent issue.
2- We don't manage the runners of https://ci.wazuh.info/job/Test_registration, therefore we need them to activate some capture mechanism with package executions compiled in debug. Core team dont have this capacity.
3- Pre-existent issue, we dont change modulesd in 4.7.4, no blocker issue: https://github.com/wazuh/wazuh/blob/4.7.4/CHANGELOG.md -> Removed from 4.7.4

Without this information we cannot do the RCA in efficient way.

@sebasfalcone try to reproduce this issue in a timebox of 1 day, if not block this issue to request more information from the source side.

**Comment by pereyra-m** [comment] 2024-04-25 14:47
Hi @rauldpm !

I don't have access to the VPN, could you please upload the logs of the tests to the issue?

**Comment by rauldpm** [comment] 2024-04-25 14:51
I edited the issue, the file is called output.log

**Comment by pereyra-m** [comment] 2024-04-26 03:45
Hello again @rauldpm.
Would it be possible to add the `ossec.log` file of the test that failed? Only the log of the test is available in the issue.

Analyzing this, I could say:
- The failure appears in the `register_verify_manager_agent_password.yaml` test. Here the registration with different options is tested and this exercises `authd` mostly. Even when `modulesd` reads the `client.keys` file, this failure might not be related directly to the feature under testing.
- I have run manually the steps of the test on a Wazuh manager v4.7.4 compiled by sources and the issue didn't appear.
- As @Dwordcito says, there aren't changes in `modulesd` in this patch, so it could be a pre-existent issue, making it even more difficult to find the root cause.

I suggest that these tests are run with the debug logs enabled on hosts with core dumps configured, to improve the quality and accuracy of the information collected when these issues appear.
I'm not saying there isn't a real bug here, I just don't have enough information to work on this problem.

**Comment by rauldpm** [comment] 2024-04-26 15:55
No, it is not possible, the test only gives the output provided

This error is not related to the register test I think, note that the error is that a `stop` command didn't kill the modulesd process, for me, this is not related to the test but to the process stop management

Probably it is an old issue, but I couldn't find an issue about it

Tests are executed in a Docker container in ECS, the image used is stored in ECR, so the DevOps team can give you access to download it and try to reproduce it locally enabling the debug mode

> I just don't have enough information to work on this problem.

I know, but I can only give the output of the test and the steps of the test, if you cannot reproduce it we can close the issue as not reproduced or leave it open in case we find another case in the future, but I think we should review the stop procedure as the error is pretty clear for me:


- Stop -> Kill processes -> Start -> Fails because modulesd process is still alive

**Comment by sebasfalcone** [comment] 2024-04-29 02:19
We where unable to reproduce this issue in a local environment, so we are closing it for now

**Closed by sebasfalcone** 2024-04-29 02:19 UTC
Labels: type/bug, level/task
