### ISSUE TITLE
Footprint - Absence of activity in Windows Agent plots due to massive drop in activity

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh#25182] opened 2024-08-12 13:31 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---| 
| 4.9.0-Beta2 | Wazuh Component | Manager | Packages | Windows |

Testing [Release 4.9.0 - Beta 2 - Footprint Metrics - ALL (2.5d)](https://github.com/wazuh/wazuh/issues/25150) all the plots, unless agentd_number_of_messages, generated_events, have a dramatic crash of its activity between 2024/08/11 16:38hs and 17:14hs while in https://github.com/wazuh/wazuh/issues/24474 the plots have been continuously printed.

<details><summary>v4.9.0-Beta2</summary>

### Windows
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/Test_stress_B5504_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/Test_stress_B5504_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/Test_stress_B5504_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/Test_stress_B5504_windows_agentd_state_AgentD_Status.png)

</details>

<details><summary> v4.8.1-RC2 </summary>

### Windows
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/monitor-winagent-Test_stress_B5398_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/Test_stress_B5398_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/Test_stress_B5398_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/Test_stress_B5398_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.8.1/B5398-3600m/B5398_agent_windows/plots/Test_stress_B5398_windows_agentd_state_AgentD_Status.png)
</details>

There is also an absence of activity in logs from the moment the Windows agent activity log disappears, only some logs are repeated

Further investigation into the reason for the crash will be required.

**Comment by vikman90** [comment] 2024-08-13 07:56
I see the abrupt cessation of activity that you report, but it doesn't tell us anything about the cause. It would be worth analyzing the Event Viewer to see if Windows reported any process crash.

It doesn't look like a memory leak and I would be surprised if it was due to a recent bug, but with this data, we can't confirm anything.

There are no significant changes in the log, meaning we can't determine why it crashed at that time, and not before or after.

Therefore, we have requested the execution of a new test, which will leave the machine active so that we can access debugging:
- Job [#5512](https://ci.wazuh.info/job/Test_stress/5512)

Due to the time lag, we will be able to return to this issue on **August 15th** at around 21:55 CEST / 16:55 ARG.

**Comment by vikman90** [comment] 2024-08-13 08:01
Closing this issue as decided not to relaunch the test.

**Comment by vikman90** [comment] 2024-08-13 09:43
Test relaunched:

- Job [#5513](https://ci.wazuh.info/job/Test_stress/5513)

Due to the time lag, we will be able to return to this issue on August 15th at around 22:35 CEST / 17:35 ARG.

**Comment by wazuhci** [comment] 2024-08-15 20:49
## Footprint metrics information
|                                  |                                            |
|---------------------------------|--------------------------------------------|
| **Main release stage issue #** | #25126                                         |
| **Main footprint metrics issue #** | #                                         |
| **Version** | 4.9.0                                      |
| **Release stage #** | Beta 2                                         |
| **Tag** | https://github.com/wazuh/wazuh/tree/v4.9.0-beta2 |

## Stress test documentation
### Packages used
- Repository: `packages-dev.wazuh.com`
- Package path: `pre-release`
- Package revision: `1`

- **Jenkins build**: https://ci.wazuh.info/job/Test_stress/5513/

---

<details><summary>Manager</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/monitor-manager-Test_stress_B5513_manager-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_events_Decoded_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_events_Dropped_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_events_EDPS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_events_Written_stats.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_state_Number_Events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/plots/Test_stress_B5513_manager_analysisd_state_Queues_state.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B5513_manager_2024-08-15.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/logs/ossec_Test_stress_B5513_manager_2024-08-15.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-manager-Test_stress_B5513_manager-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/data/monitor-manager-Test_stress_B5513_manager-pre-release.csv)
[Test_stress_B5513_manager_analysisd_events.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/data/Test_stress_B5513_manager_analysisd_events.csv)
[Test_stress_B5513_manager_analysisd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/data/Test_stress_B5513_manager_analysisd_state.csv)
[Test_stress_B5513_manager_remoted_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_manager_centos/data/Test_stress_B5513_manager_remoted_state.csv)



    </details>

</details>

<details><summary>Centos agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/monitor-agent-Test_stress_B5513_centos-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/Test_stress_B5513_centos_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/Test_stress_B5513_centos_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/Test_stress_B5513_centos_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/plots/Test_stress_B5513_centos_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B5513_centos_2024-08-15.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/logs/ossec_Test_stress_B5513_centos_2024-08-15.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B5513_centos-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/data/monitor-agent-Test_stress_B5513_centos-pre-release.csv)
[Test_stress_B5513_centos_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_centos/data/Test_stress_B5513_centos_agentd_state.csv)



    </details>

</details>

<details><summary>Ubuntu agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_FD.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_PSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_SWAP.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/monitor-agent-Test_stress_B5513_ubuntu-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/Test_stress_B5513_ubuntu_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/Test_stress_B5513_ubuntu_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/Test_stress_B5513_ubuntu_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/plots/Test_stress_B5513_ubuntu_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B5513_ubuntu_2024-08-15.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/logs/ossec_Test_stress_B5513_ubuntu_2024-08-15.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-agent-Test_stress_B5513_ubuntu-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/data/monitor-agent-Test_stress_B5513_ubuntu-pre-release.csv)
[Test_stress_B5513_ubuntu_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_ubuntu/data/Test_stress_B5513_ubuntu_agentd_state.csv)



    </details>

</details>

<details><summary>Windows agent</summary>

+ <details><summary>Plots</summary>

    ![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_CPU.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Disk.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Disk_Read.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Disk_Written.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Handles.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Read_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_RSS_MAXMIN.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_RSS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_USS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_VMS.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_Write_Ops.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/Test_stress_B5513_windows_agentd_state_AgentD_Number_of_events_buffered.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/Test_stress_B5513_windows_agentd_state_AgentD_Number_of_generated_events.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/Test_stress_B5513_windows_agentd_state_AgentD_Number_of_messages.png)
![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/Test_stress_B5513_windows_agentd_state_AgentD_Status.png)



    </details>
+ <details><summary>Logs and configuration</summary>

    [ossec_Test_stress_B5513_windows_2024-08-15.zip](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/logs/ossec_Test_stress_B5513_windows_2024-08-15.zip)



    </details>
+ <details><summary>CSV</summary>

    [monitor-winagent-Test_stress_B5513_windows-pre-release.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/data/monitor-winagent-Test_stress_B5513_windows-pre-release.csv)
[Test_stress_B5513_windows_agentd_state.csv](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/data/Test_stress_B5513_windows_agentd_state.csv)



    </details>

</details>

<details><summary>macOS agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

<details><summary>Solaris agent</summary>

+ <details><summary>Plots</summary>

    


    </details>
+ <details><summary>Logs and configuration</summary>

    


    </details>
+ <details><summary>CSV</summary>

    


    </details>

</details>

**Comment by vikman90** [comment] 2024-08-16 11:59
## Summary

This time, the agent held out until the end:

|First|Second|
|--|--|
|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5504-3600m/B5504_agent_windows/plots/monitor-winagent-Test_stress_B5504_windows-pre-release_CPU.png)|![](https://ci.wazuh.com/data/Test_stress/pre-release/4.9.0/B5513-3600m/B5513_agent_windows/plots/monitor-winagent-Test_stress_B5513_windows-pre-release_CPU.png)|

In addition, we're sure that the problem was originated by the issue addressed at:
- https://github.com/wazuh/wazuh/issues/25202

We can close this issue.

**Closed by vikman90** 2024-08-16 11:59 UTC
Labels: type/bug, level/task
