### ISSUE TITLE
Windows Compatibility

### ISSUE THREAD

**Issue by ixalle** [wazuh/wazuh#153] opened 2017-07-12 09:30 UTC
Hello,

I wanted to know which versions of Windows Server are supported (Agent side) ?

I have installed on :

- Windows Server 2012 R2 OK,
- Windows Server 2008 R2 NOK
- Windows Server 2016 NOK

Thanks for your help :+1:

**Comment by vikman90** [comment] 2017-07-12 10:00
Hi @ixalle,

The Wazuh agent should work on all those operating systems. In fact we are doing some tests on Windows Server 2008 and 2016 and it's working properly.

Which problem are you experiencing?

**Comment by ixalle** [comment] 2017-07-12 11:38
Hi @vikman90 ,

Thanks for your quick answer, in fact, from Wazuh manager (via Kibana App) all of this servers have status : Never connceted

I installed this binary : https://documentation.wazuh.com/2.0/installation-guide/packages-list/index.html
I think the binary works on each server but there is some issue with Wazuh API (same Subnet, no filtering)

Logs from Wazuh manager :

`2017/07/12 13:10:40 wazuh-modulesd:database(1117): ERROR: Could not retrieve informations of file '/var/ossec/queue/rootcheck/ XXXXX due to [(2)-(No such file or directory)].`

I don't know why, enough space on disk, others servers works fine.

Thanks,

**Comment by ixalle** [comment] 2017-07-12 12:20
I created this file manually and syscheck too and now all works fine but I don't understand why this error happened...

**Comment by vikman90** [comment] 2017-07-12 13:29
Hi,

this error is not critical: it may happen when a new agent is added and the manager is restarted before the agent connects to the manager. This is an acceptable condition, and we should silence that error message.

Those files are created by the manager when the agent gets connected and starts to send Rootcheck events. Don't worry about that.

On the other hand, there may be an issue with the new agents. Please check that there is communication between agents and manager (i.e. no firewall is blocking messages) and the agent has the correct manager's IP and a valid key.

If there is a communication problem, the agent log would should a message like:

> 2017/07/11 17:19:50 ossec-agentd: INFO: Trying to connect to server (192.168.66.2:1514).

And **no message like this one** follows it:

> 2017/07/11 17:20:05 ossec-agentd(4102): INFO: Connected to the server (192.168.66.2:1514).

If the problem is in the manager, its log should indicate the problem.

Hope it help.
Best regards.

**Comment by DaveVG1** [comment] 2019-04-16 13:05
Hi @ixalle,

The rootcheck file error message was silenced here https://github.com/wazuh/wazuh/pull/2997/commits/096fb6a80619b079e54c79a9d07d71b621727845. I'm going to proceed to close this issue. If you have any further questions/problems regarding this issue, please feel free to re-open it.

Kind regards.

**Closed by DaveVG1** 2019-04-16 13:05 UTC
