### ISSUE TITLE
Update_ruleset error on fresh 4.0.3 install

### ISSUE THREAD

**Issue by VictorMorenoJimenez** [wazuh/wazuh#6818] opened 2020-12-03 08:09 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 4.0.3-40010 | Ruleset | Unattended All-in-one OSS | Unattended script  | CentOS7 |

Hi team,
There is a problem with executing `/var/ossec/bin/update_ruleset` after fresh install. When executing it gives the following error:
```
[root@centos7 scripts]# /var/ossec/bin/update_ruleset
### Wazuh ruleset ###
ERROR: Upgrade aborted: Unexpected version in the new ruleset. Expected version v4.0.x. Found version v4.0.2
```
I've found that that script has different permissions:
```
[root@centos7 scripts]# ls -larth
total 60K
-rw-r-----. 1 root ossec 7.6K Nov 30 08:42 wazuh-clusterd.py
-rw-r-----. 1 root ossec 7.7K Nov 30 08:42 cluster_control.py
-rw-r-----. 1 root ossec 7.0K Nov 30 08:42 agent_upgrade.py
-rw-r-----. 1 root ossec  12K Nov 30 08:42 agent_groups.py
drwxr-x---. 5 root ossec   48 Dec  1 08:47 ..
-rwxr-x---. 1 root root   24K Dec  3 07:43 update_ruleset.py
drwxr-x---. 2 root ossec  129 Dec  3 07:45 .
```

**Comment by vikman90** [comment] 2020-12-03 16:36
Hi @VictorMorenoJimenez,

The problem was caused by the branch `4.0` in the ruleset repository, which was pointing to v4.0.2 yet.

That is fixed now. Sorry for the inconvenience.

Best regards.

**Closed by vikman90** 2020-12-03 16:36 UTC
Labels: cicd
