### ISSUE TITLE
aws-s3 wodle exits on long messages

### ISSUE THREAD

**Issue by spartantri** [wazuh/wazuh#2535] opened 2019-02-07 02:45 UTC
|Wazuh version|Install type|Install method|Platform|
|---|---|---|---|
|3.8.2|Managar|Packages|RH7|

The aws-s3 wodle script exits with Error 90 when it receives events containing the inventory for the region.

Those entries may be over 250Kb and the debug in level 3 shows a 106 lines of that event, it exists and stop processing any further event: 
```
{"aws": {"eventVersion": "1.05", "eventID": "xxxxxxxxxxxxxxxxxx", "responseElements": {"unprocessedResourceKeys": [], "baseConfigurationItems": [{"configurationItemCaptureTime":
...106 lines....
"sourceIPAddress": "securityhub.amazonaws.com"}, "integration": "aws"}
ERROR: Error sending message to wazuh: [Errno 90] Message too long
```

**Comment by UranusBytes** [comment] 2019-02-07 18:47
I'd originally fixed this problem as part of #733, but it looks like the code got ripped out...

In #1189, lines 573-593 were removed to change the way lists were cast from strings to dictionaries, but the code to handle large messages (lines 595-608) was also removed.  Then the underlying max_queue_buffer was removed as part of #1880.

Try increasing the size of rmem_max and see if that lets the event be received by wazuh.

**Comment by spartantri** [comment] 2019-02-07 19:31
for now, I just commented the exit(13) line, it goes get all logs from the bucket but still having weird behavior, I'm not seen any event at all related to aws in the wazuh-app

**Comment by UranusBytes** [comment] 2019-02-07 20:19
If I had to guess, the problem is that the socket is being kept open by line 233, assuming the exception is occuring on line 232

https://github.com/wazuh/wazuh/blob/b02be14b3a846e5b17ceaa38d695b9f12228120a/wodles/aws/aws-s3.py#L229-L233

Try adding an `s.close()` after the commented out `exit(13)`

**Comment by UranusBytes** [comment] 2019-02-11 12:41
@spartantri Can you confirm if the addition of the s.close() was required?

**Comment by spartantri** [comment] 2019-02-11 18:18
Hi @UranusBytes it worked without the `s.close()`, I have only a few records that exceeded the maximum length so didn't have issues. I added it anyway to avoid having too many unnecessary sockets open in the future.
Thanks for the help!

**Comment by slavag** [comment] 2019-03-02 11:58
I have the same issue, tried to change rmem_max to 1mb, while message is about 270kb, but still have the same issue.

**Comment by slavag** [comment] 2019-03-18 11:00
Is there any progress on this issue (for large AWS logs) ?
Thanks

**Comment by mgmacias95** [comment] 2019-03-22 14:42
Hello everyone,

@UranusBytes, we had to remove the code to handle large messages because it didn't work on Docker containers (https://github.com/wazuh/wazuh-docker/issues/68).

The proper fix should be increasing buffer size or allowing an event to be sent in multiple messages over a socket. However, this is a long term fix that requires a big change in the code. In the meanwhile:
* A good error handler should be added to prevent the wodle to fail.
* Logs should be reviewed in order to determine if there are any fields that can be removed in order to make logs smaller. @slavag could you share some of the logs that make the integration fail?

Sorry for the inconvenience.

Best regards,
Marta

**Comment by slavag** [comment] 2019-03-25 10:26
I can share logs, but in private only, and they need to be removed after investigation.
But in general it's terminate instances cloudtrail log, about 230kb.

**Comment by mgmacias95** [comment] 2019-03-28 16:07
Hello @slavag,

We have sucessfully parsed _terminate instances_ logs so I am not able to use our environment to replicate the error. Could you please reach me at _marta at wazuh dot com_ and share some logs that make the wodle crash? I'll remove everything once this issue is fixed.

Thank you so much,
Marta

**Comment by slavag** [comment] 2019-04-02 10:52
Hi,
Looks like I  don't have anymore messages like that, and don't see those exceptions anymore.
Anyway on terminate instance cloudtrail log is the problematic one, as it can contain hundreds of instances in the log.

**Comment by druizz90** [comment] 2019-04-03 16:02
Hi @slavag,

Fix introduced by @UranusBytes will be available in our next release (`3.9`), but unfortunately `analisysd` socket has a limit of `64 KB`, and events longer than this limit will be discarded.

It is possible that this limit will be increased in the future, but not in next release.

It could be very useful for us if you send to us a log file with a huge event for thinking in other way to resolve this problem, we have not got events with this size.

Best regards,

Demetrio.

**Comment by crd1985** [comment] 2020-03-06 12:16
Closing this issue since the original problem has been solved.

We can discuss about the need of increasing the maximum size of messages to be sent to `analysisd` in a new issue

**Closed by crd1985** 2020-03-06 12:16 UTC
Labels: aws_integration, framework

**Comment by slavag** [comment] 2020-03-10 21:36
Hi Demetrio,
Thanks.
I'll follow the logs and see what can be provided as good example.

Thanks
