### ISSUE TITLE
AWS Module not working with Service Cloud Watch and Trusted Advisor

### ISSUE THREAD

**Issue by guilhermerezendemarques** [wazuh/wazuh#7407] opened 2021-02-08 16:38 UTC
I don't saw the logs of services Cloud Watch(API) and S3 bucket Trusted Advisor in Kibana, kibana shows only Clould Trail logs.

No have errors in ossec.log and in /var/ossec/bin/wazuh-modulesd -fdddd don't find any errors.

DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35966641722385717813434823240691325417299162838449586691", start_time "1612789194019" and end_time "None"
DEBUG: Saving data for log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" and log stream "dev-Monitoring".
DEBUG: The saved values are "{'token': 'f/35966641722385717813434823240691325417299162838449586691', 'start_time': 1612742400000, 'end_time': 1612789194019}"
DEBUG: Some data already exists on DB for that key. Updating their values...
DEBUG: Purging the BD
DEBUG: Getting log streams for "dev-Monitoring-/var/log/ecs/ecs-agent.log" log group
DEBUG: Found "dev-Monitoring" log stream in dev-Monitoring-/var/log/ecs/ecs-agent.log
DEBUG: committing changes and closing the DB

2021/02/08 16:36:11 wazuh-modulesd:aws-s3[11160] wm_aws.c:159 at wm_aws_main(): INFO: Fetching logs finished.
2021/02/08 16:36:11 wazuh-modulesd:aws-s3[11160] wm_aws.c:68 at wm_aws_main(): DEBUG: Sleeping until: 2021/02/08 16:45:37

But this logs not appear in Kibana AWS visualization, only Cloud Trail bucket.

**Comment by CarlosRS9** [comment] 2021-02-09 08:28
Hello,

Examining the logs provided it looks like the CloudWatch integration is working just fine. Logs from "dev-Monitoring-/var/log/ecs/ecs-agent.log" log group inside the "dev-Monitoring" log stream are being detected and downloaded. Please make sure you are looking for those alerts in the right place. CloudWatchLogs should appear within the `Wazuh > Security Information Management > Security events section`:

![image](https://user-images.githubusercontent.com/54286452/107335901-c82f4580-6ab8-11eb-9c27-01200374c8de.png)

Also take into account that even if you have logs available in CloudWatchLogs and Wazuh collects them as expected they won't show up in the Wazuh UI (kibana) if no rules match for those particular logs. To make it clear, when Wazuh collects CloudWatchLogs logs it tries to match those logs with any of the available rules in a similar way as if the log itself had been generated on your own system instead of coming from AWS. This means there is no specific CloudWatch rules. As an example, if your CloudWatchLogs are being generated by an Apache server their logs will be matched with the Apache rules. A log coming from the AWS module will have set `Wazuh-AWS` as its `location` field value.



With this in mind, if you think that an alert should be raised but you still cannot see them in the Wazuh UI then I suggest you to enable `modulesd` debug mode and look for the message that the AWS module is sending to `Analysisd` (the module in charge of checking if an event should trigger an alert). You can enable debug mode by adding the following line to the `{wazuh-path}/etc/local_internal_options.conf` file:
```
wazuh_modules.debug=2
```

Don't forget to replace `{wazuh-path}` with the path you have Wazuh installed on. By default, it is `/var/ossec/`.

After that, restart the wazuh service and you should be able to see something like this in the `{wazuh-path}/logs/ossec.log`:
```
DEBUG: Getting CloudWatch logs from log stream "<REDACTED>" in log group "<REDACTED>" using token "<REDACTED>", start_time "<REDACTED>" and end_time "<REDACTED>"
DEBUG: +++ Sending events to Analysd...
DEBUG: The message is "{"timestamp":"2021-01-22T08:47:26.840+0000","agent":{"id":"000","name":"wazuh-manager"},"manager":{"name":"wazuh-manager"},"id":"<REDACTED>","full_log":"[Wed Jun 10 07:39:15.069241 2020] [mpm_event:notice] [pid 1:tid <REDACTED>] AH00489: Apache/2.4.43 (Unix) configured -- resuming normal operations","decoder":{"name":"apache-errorlog"},"location":"Wazuh-AWS"}"
```

You can use the following command to look for your CloudWatchLogs logs:
```
tail -f {wazuh-path}/logs/ossec.log | grep "The message is"
```

That message is the same that is being sent to `analysisd`, so if you want to make sure it should trigger any alert you can use our `logtest` tool. You can find it in `{wazuh-path}/bin/ossec-logtest` or in `{wazuh-path}/bin/wazuh-logtest` depending on your Wazuh version. Execute it, paste the message obtained previously from the `ossec.log` on it and press Enter. You should be able to see something like this:

```
{"timestamp":"2021-01-22T08:47:26.840+0000","agent":{"id":"000","name":"wazuh-manager"},"manager":{"name":"wazuh-manager"},"id":"<redacted>","full_log":"[Wed Jun 10 07:39:15.069241 2020] [mpm_event:notice] [pid 1:tid <redacted>] AH00489: Apache/2.4.43 (Unix) configured -- resuming normal operations","decoder":{"name":"apache-errorlog"},"location":"Wazuh-AWS"}


*Phase 1: Completed pre-decoding.
		<PRE DECODING INFO>

**Phase 2: Completed decoding.
		<DECODING INFORMATION>

**Phase 3: Completed filtering (rules).
       Rule id: '#####'
       Level: '#'
```

If `Phase 3: Completed filtering (rules)` does not appear in the output that would mean that particular log is not matching with any of your existing rules and because of that no alert are being raised.


Regarding TrustedAdvisor, I cannot see anything related to it within the log provided but you can debug it in the same way. Could you confirm us that you followed our official documentation when setting it up?

Finally, feel free to share with us here your AWS module configuration (removing any sensitive information) and I will review it for you to see if there is something wrong with it.

Regards.

**Comment by guilhermerezendemarques** [comment] 2021-02-09 11:55
Hi Carlos, my level of debug is 3 in this file {wazuh-path}/etc/local_internal_options.conf. 
This logs of Cloud Watch and Trusted Advisor would appear in Discovery Wazuh ALerts( index) but not appear in this indixes and in kibana dashboards.
My version of Wazuh is 4.0(docker container installation of compose of Wazuh site).
Logging of debug:

DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "None", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35967785772915147632932672444353049496311584653934264450", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35968167115658042506588410112120965333600452837325210120", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "None", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35967785772915147632932672444353049496311584653934264450", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35968167115658042506588410112120965333600452837325210120", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "None", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35967785772915147632932672444353049496311584653934264450", start_time "1612828800000" and end_time "None"
DEBUG: Getting CloudWatch logs from log stream "dev-Monitoring" in log group "dev-Monitoring-/var/log/ecs/ecs-agent.log" using token "f/35968167115658042506588410112120965333600452837325210120", start_time "1612828800000" and end_time "None"


2021/02/09 11:39:51 wazuh-modulesd:aws-s3[12080] wm_aws.c:382 at wm_aws_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket wazuhtrusteradvistor --aws_profile default --type custom --debug 2 --skip_on_error
DEBUG: +++ Marker: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-13-30-94f7c112-4f4a-44c6-8ed2-ccd5ce393c71
DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-18-34-d2545e6b-1e52-49d4-b328-b5accf26dcbe
DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-23-38-a83732e3-fdbd-43a4-9c53-255a3fd82df8
2021/02/09 11:49:20 wazuh-modulesd:syscollector[12080] syscollector_linux.c:542 at sys_rpm_packages(): DEBUG: sys_rpm_packages() sending '{"type":"program","ID":255710041,"timestamp":"2021/02/09 11:49:19","program":{"format":"rpm","name":"p11-kit-trust","description":"System trust module from p11-kit","size":427,"vendor":"CentOS","group":"Unspecified","architecture":"x86_64","source":"p11-kit-0.23.5-3.el7.src.rpm","install_time":"2020/11/13 01:54:07","version":"0.23.5-3.el7"}}'
2021/02/09 11:49:49 wazuh-modulesd:aws-s3[12080] wm_aws.c:119 at wm_aws_main(): INFO: Executing Bucket Analysis: (Bucket: wazuhtrusteradvistor, Type: custom, Profile: default)
2021/02/09 11:49:49 wazuh-modulesd:aws-s3[12080] wm_aws.c:382 at wm_aws_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket wazuhtrusteradvistor --aws_profile default --type custom --debug 2 --skip_on_error
DEBUG: +++ Marker: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-13-30-94f7c112-4f4a-44c6-8ed2-ccd5ce393c71
DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-18-34-d2545e6b-1e52-49d4-b328-b5accf26dcbe
DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-23-38-a83732e3-fdbd-43a4-9c53-255a3fd82df8

I saw one problem in GIT to informe Wazuh 4.0 bug for more 1 bucket AWS(S3). You Know?
https://github.com/wazuh/wazuh/issues/7351a

**Comment by CarlosRS9** [comment] 2021-02-09 13:10
Hi,

Those logs you shared shows that the AWS module seems to be working just fine. However, I think those logs are coming from `/var/ossec/bin/wazuh-modulesd -fddd`. Unfortunately, the `wazuh-modulesd` binary does not provide us with the information I need to help you further when executing that way. That's why I need you to enable modulesd debug mode and look into the `ossec.log` instead. 

Regarding `{wazuh-path}/etc/local_internal_options.conf.` at debug mode `3`, I'm afraid that `3` is not a valid debug mode for this file. If you try to restart wazuh after enabling debug mode at level `3`  the following error may appear:
```
CRITICAL: (2302): Invalid definition for wazuh_modules.debug: '3'.
```

Please, if possible, paste the following line into `local_internal_options.conf` and restart the wazuh service:
```
wazuh_modules.debug=2
```

After restarting, take a look to the ossec.log and look for any warning or error message. Finally, look for the `The message is` string inside the ossec.log to see what events are being sent to analysisd. You can use the following command to do so:
```
tail -f {wazuh-path}/logs/ossec.log | grep "The message is"
```

Additionally, you can enable the `logall` and `logall_json` options inside the global configuration of `ossec.conf` and restart Wazuh. Doing this you will log into `{wazuh-path/logs/archives/alerts.log` and `{wazuh-path/logs/archives/alerts.json` every single event that is sent to `Analysisd` regardless of it that event triggered a rule or not. Check the events related to CloudWatchLogs and Trusted Advisor present in the `alerts.json´ file and try to paste one of them into the `logtest` tool as I explained in the previous message.

If you share here the requested information and I would be able to help you further.

**Comment by guilhermerezendemarques** [comment] 2021-02-09 13:19
[root@wazuh-manager /]# service wazuh-manager restart
Stopping Wazuh:                                            [  OK  ]
Starting Wazuh: 2021/02/09 13:17:02 wazuh-modulesd[21433] debug_op.c:69 at _log(): DEBUG: Logging module auto-initialized
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:138 at wm_aws_read(): DEBUG: Found a bucket tag
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:148 at wm_aws_read(): DEBUG: Creating first bucket structure
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:177 at wm_aws_read(): DEBUG: Loop thru child nodes
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:180 at wm_aws_read(): DEBUG: Parse child node: name
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:180 at wm_aws_read(): DEBUG: Parse child node: aws_profile
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:138 at wm_aws_read(): DEBUG: Found a bucket tag
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:143 at wm_aws_read(): DEBUG: Creating another bucket structure
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:177 at wm_aws_read(): DEBUG: Loop thru child nodes
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:180 at wm_aws_read(): DEBUG: Parse child node: name
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:180 at wm_aws_read(): DEBUG: Parse child node: aws_profile
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:274 at wm_aws_read(): DEBUG: Found a service tag
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:289 at wm_aws_read(): DEBUG: Creating first service structure
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:314 at wm_aws_read(): DEBUG: Loop thru child nodes
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:317 at wm_aws_read(): DEBUG: Parse child node: aws_profile
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:317 at wm_aws_read(): DEBUG: Parse child node: aws_log_groups
2021/02/09 13:17:02 wazuh-modulesd:aws-s3[21433] wmodules-aws.c:317 at wm_aws_read(): DEBUG: Parse child node: regions

[root@wazuh-manager /]# tail -f /var/ossec/logs/ossec.log | "The message is"
bash: The message is: command not found

**Comment by guilhermerezendemarques** [comment] 2021-02-09 13:21
[root@wazuh-manager archives]# cat archives.log | grep trust
2021 Feb 09 13:20:53 wazuh-manager->syscollector {"type":"program","ID":1026022537,"timestamp":"2021/02/09 13:20:52","program":{"format":"rpm","name":"p11-kit-trust","description":"System trust module from p11-kit","size":427,"vendor":"CentOS","group":"Unspecified","architecture":"x86_64","source":"p11-kit-0.23.5-3.el7.src.rpm","install_time":"2020/11/13 01:54:07","version":"0.23.5-3.el7"}}
2021 Feb 09 13:21:23 wazuh-manager->aws-s3 DEBUG: +++ Marker: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-13-30-94f7c112-4f4a-44c6-8ed2-ccd5ce393c71
2021 Feb 09 13:21:23 wazuh-manager->aws-s3 DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-18-34-d2545e6b-1e52-49d4-b328-b5accf26dcbe
2021 Feb 09 13:21:23 wazuh-manager->aws-s3 DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-23-38-a83732e3-fdbd-43a4-9c53-255a3fd82df8

**Comment by guilhermerezendemarques** [comment] 2021-02-09 13:24
Only Cloudtrail json appear in this logs.

{"timestamp":"2021-02-09T13:21:23.660+0000","agent":{"id":"000","name":"wazuh-manager"},"manager":{"name":"wazuh-manager"},"id":"1612876883.903281","full_log":"DEBUG: +++ Marker: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-13-30-94f7c112-4f4a-44c6-8ed2-ccd5ce393c71","decoder":{},"location":"aws-s3"}
{"timestamp":"2021-02-09T13:21:23.671+0000","agent":{"id":"000","name":"wazuh-manager"},"manager":{"name":"wazuh-manager"},"id":"1612876883.903281","full_log":"DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-18-34-d2545e6b-1e52-49d4-b328-b5accf26dcbe","decoder":{},"location":"aws-s3"}
{"timestamp":"2021-02-09T13:21:23.681+0000","agent":{"id":"000","name":"wazuh-manager"},"manager":{"name":"wazuh-manager"},"id":"1612876883.903281","full_log":"DEBUG: ++ Skipping previously processed file: firehose/2021/02/05/17/wazuhtrusteradvistor-1-2021-02-05-17-23-38-a83732e3-fdbd-43a4-9c53-255a3fd82df8","decoder":{},"location":"aws-s3"}

**Comment by guilhermerezendemarques** [comment] 2021-02-09 13:26
![image](https://user-images.githubusercontent.com/33107798/107370062-442d8b80-6ac1-11eb-9ef0-5f3b0ee91efd.png)

**Comment by guilhermerezendemarques** [comment] 2021-02-09 13:27
Only appear Cloud Trail, trusted advisor source S3 not appear.

**Comment by CarlosRS9** [comment] 2021-02-09 14:43
> [root@wazuh-manager /]# tail -f /var/ossec/logs/ossec.log | "The message is"
> bash: The message is: command not found

There is a typo there. The `grep` command is missing. Please, try again:

**Comment by CarlosRS9** [comment] 2021-02-09 15:32
Hi again,

It looks there has been some confusion here. Let me try to help you with this.

CloudWatchLogs alerts should appear in the `Wazuh > Modules > Security Events` section but it seems you are looking for them in `Wazuh > Modules > Amazon AWS` instead. In the `Amazon AWS` section you should be able to see CloudTrail and Trusted Advisor alerts but not the ones from CloudWatchLogs. Please, take a look to `Wazuh > Modules > Security Events` and verify if those alerts from CloudWatchLogs are present there.
![image](https://user-images.githubusercontent.com/54286452/107386067-c9ca2f00-6af3-11eb-8f63-8d8a82c1a017.png)

The logs you shared in your previous messages indicate that the AWS integration is working fine. If you are looking for them in the right place but the alerts are not present then it is possible that none of those logs in your bucket are triggering any rule. That's why I asked you to run the previous command: 

> [root@wazuh-manager /]# tail -f /var/ossec/logs/ossec.log | "The message is"
> bash: The message is: command not found


There is a typo there. The `grep` command is missing. Please, try again:
```
tail -f {wazuh-path}/logs/ossec.log | grep "The message is"
```

Please, try to run the command again while the AWS module is running and share with us one example of those logs sent to `Analysisd`. With that I will be able to check if that log matches any of the available rules.

Also, when checking the `alerts.json` file please make sure you are not filtering by anything. Run the `cat archives.json` command without any `grep` and check if any of the CloudWatchLogs or Trusted Advisor logs are present.

Additionally, please confirm us if you configured Trusted Advisor following the steps detailed [in our documentation](https://documentation.wazuh.com/4.0/amazon/services/supported-services/trusted-advisor.html).

**Comment by guilhermerezendemarques** [comment] 2021-02-10 18:44
DEBUG: The message is "level=info time=2021-02-10T17:59:55Z msg="Managed task [arn:aws:ecs:us-east-1:112542087706:task/db3d9a34-bef4-4d6b-9e46-2029aa9617b2]: waiting for event for task" module=task_manager.go"

**Comment by guilhermerezendemarques** [comment] 2021-02-10 18:49
In this logs archives.json not appear anythink of Cloud Watch and trusted advisor.

**Comment by CarlosRS9** [comment] 2021-02-11 07:43
The problem is that particular log in your AWS Bucket does not match with any rule, so no alerts are being generated for it, as you can see using our `logtest` tool, and because of that nothing will be available in Kibana:

```
level=info time=2021-02-10T17:59:55Z msg="Managed task [arn:aws:ecs:us-east-1:112542087706:task/db3d9a34-bef4-4d6b-9e46-2029aa9617b2]: waiting for event for task" module=task_manager.go

**Phase 1: Completed pre-decoding.
	full event: 'level=info time=2021-02-10T17:59:55Z msg="Managed task [arn:aws:ecs:us-east-1:112542087706:task/db3d9a34-bef4-4d6b-9e46-2029aa9617b2]: waiting for event for task" module=task_manager.go'

**Phase 2: Completed decoding.
	No decoder matched.
```

That particular message seems to be coming from your AWS CloudwatchLogs, not from Trusted Advisor, but I may be wrong.

I recommend you to take a look to some of the logs in your Trusted Advisor bucket and in your CloudWatchLogs and see if they should be triggering any rule.



> DEBUG: The message is "level=info time=2021-02-10T17:59:55Z msg="Managed task [arn:aws:ecs:us-east-1:112542087706:task/db3d9a34-bef4-4d6b-9e46-2029aa9617b2]: waiting for event for task" module=task_manager.go"

Take into account that if a particular log was already processed (but no alert was generated as it didn't match with any rule) no event will be present in the alerts.json, and that log is telling us those logs are being skipped because they were already processed before.

The module seems to be working fine. You may need custom rules for those AWS logs.

**Comment by guilhermerezendemarques** [comment] 2021-02-16 12:33
HI Carlos, I understand the Trusted Advisor is default role and could appear in AWS Module, but in this log, is ok, but not appear.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 14:45
I can't see logs os trustedadvisor in Kibana AWS Module and in index not appear too.

2021/02/18 14:33:44 wazuh-modulesd:aws-s3[89077] wm_aws.c:382 at wm_aws_run_s3(): DEBUG: Launching S3 Command: /var/ossec/wodles/aws/aws-s3 --bucket wazuhtrusteradvistor --aws_profile default --trail_prefix firehose/ --type custom --debug 2 --skip_on_error
2021/02/18 14:33:45 wazuh-modulesd:syscollector[89077] syscollector_linux.c:864 at sys_os_unix(): DEBUG: sys_os_unix() sending '{"type":"OS","ID":134489821,"timestamp":"2021/02/18 14:33:45","inventory":{"os_name":"CentOS Linux","os_major":"7","os_minor":"9","os_version":"7.9","os_platform":"centos","sysname":"Linux","hostname":"wazuh-manager","release":"5.4.0-1029-aws","version":"#30-Ubuntu SMP Tue Oct 20 10:06:38 UTC 2020","architecture":"x86_64"}}'
2021/02/18 14:33:47 wazuh-modulesd:syscollector[89077] syscollector_linux.c:1519 at sys_proc_linux(): DEBUG: sys_proc_linux() sending '{"type":"process","ID":2136436898,"timestamp":"2021/02/18 14:33:47","process":{"pid":12803,"name":"vi","state":"S","ppid":12759,"utime":0,"stime":1,"cmd":"vi","argvs":["aws-s3.py"],"euser":"root","ruser":"root","suser":"root","egroup":"root","rgroup":"root","sgroup":"root","fgroup":"root","priority":20,"nice":0,"size":6604,"vm_size":26416,"resident":936,"share":777,"start_time":1726722,"pgrp":12803,"session":12759,"nlwp":1,"tgid":12803,"tty":34821,"processor":1}}'
2021/02/18 14:33:47 wazuh-modulesd:syscollector[89077] syscollector_linux.c:1519 at sys_proc_linux(): DEBUG: sys_proc_linux() sending '{"type":"process","ID":2136436898,"timestamp":"2021/02/18 14:33:47","process":{"pid":89094,"name":"aws-s3","state":"S","ppid":89080,"utime":0,"stime":0,"cmd":"/bin/sh","argvs":["/var/ossec/wodles/aws/aws-s3","--bucket","wazuhtrusteradvistor","--aws_profile","default","--trail_prefix","firehose/","--type","custom","--debug","2","--skip_on_error"],"euser":"root","ruser":"root","suser":"root","egroup":"ossec","rgroup":"ossec","sgroup":"ossec","fgroup":"ossec","priority":30,"nice":10,"size":2924,"vm_size":11696,"resident":673,"share":621,"start_time":87186758,"pgrp":89094,"session":89094,"nlwp":1,"tgid":89094,"tty":0,"processor":1}}'
2021/02/18 14:33:47 wazuh-modulesd:syscollector[89077] syscollector_linux.c:1519 at sys_proc_linux(): DEBUG: sys_proc_linux() sending '{"type":"process","ID":2136436898,"timestamp":"2021/02/18 14:33:47","process":{"pid":89105,"name":"python3","state":"R","ppid":89094,"utime":59,"stime":5,"cmd":"/var/ossec/framework/python/bin/python3","argvs":["/var/ossec/wodles/aws/aws-s3.py","--bucket","wazuhtrusteradvistor","--aws_profile","default","--trail_prefix","firehose/","--type","custom","--debug","2","--skip_on_error"],"euser":"root","ruser":"root","suser":"root","egroup":"ossec","rgroup":"ossec","sgroup":"ossec","fgroup":"ossec","priority":30,"nice":10,"size":30563,"vm_size":122252,"resident":9761,"share":2825,"start_time":87186767,"pgrp":89094,"session":89094,"nlwp":1,"tgid":89105,"tty":0,"processor":1}}'
2021/02/18 14:33:47 wazuh-modulesd:aws-s3[89077] wm_aws.c:422 at wm_aws_run_s3(): DEBUG: Bucket:  -  OUTPUT: DEBUG: +++ Debug mode on - Level: 2
2021/02/18 14:33:47 wazuh-modulesd:aws-s3[89077] wm_aws.c:159 at wm_aws_main(): INFO: Fetching logs finished.
2021/02/18 14:33:47 wazuh-modulesd:aws-s3[89077] wm_aws.c:68 at wm_aws_main(): DEBUG: Sleeping until: 2021/02/18 14:43:44

**Comment by CarlosRS9** [comment] 2021-02-18 15:50
Hi again,

I'm afraid there is no useful information there. I think you are running the `wazuh-modulesd -fdd` command, but only logs related to `syscollector` are present there, nothing related to the aws-s3 module except for the `Launching S3 Command` message.


It seems your TrustedAdvisor logs are not matching with any rule, so no alerts are being raised and nothing is shown in Kibana. I suggest you to take a look to your TrustedAdvisor logs in your AWS console to see if there is something wrong with them. After that, enable the `logall` and `logall_json` options in the `global` section of your ossec.conf, restart Wazuh and take a look to the  `/var/ossec/logs/archives/archives.log` and `/var/ossec/logs/archives/archives.json`. Look for something related to your TrustedAdvisor logs and share with some of those logs related to TrustedAdvisor. Remember to remove any sensitive information present in those log before sharing them here, if necessary.



> HI Carlos, I understand the Trusted Advisor is default role and could appear in AWS Module, but in this log, is ok, but not appear.

Sorry but I don't understand what do you mean with this. Sorry for the inconvenience.

Regards.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 17:31
I understand that Wazuh already has rules enabled for any AWS service. As I said, the only service that worked was Cloud Trail, if I insert Trusted Advisor, GuardyDuty, VPC Logs, these logs are in Bucket and do not appear in Kibana. I am not the one who creates rules, the rules are the default of the tool. Is it necessary to have Bussiness support on AWS to generate more information from the Trusted Advisor to fall under the rules? My account is basic and the logs are being generated in Bucket. In logs archives, have no error information. Neither of Wazuh pulling the logs for Elastic. The logs all and json all are already enabled.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 17:32
How to test this Module in Wazuh Cloud Trial? I don't access this server for configurate this account AWS.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 17:34
Follow my settings.
 <wodle name="aws-s3">
    <disabled>no</disabled>
    <interval>10m</interval>
    <run_on_start>yes</run_on_start>
    <skip_on_error>yes</skip_on_error>
    <bucket type="custom">
      <name>wazuhtrusteradvistor</name>
      <path>firehose/</path>
      <aws_profile>default</aws_profile>
    </bucket>
    <bucket type="guardduty">
      <name>wazuh-cloudtrail-algar</name>
      <path>guardduty/</path>
      <aws_profile>default</aws_profile>
    </bucket>
  </wodle>

**Comment by guilhermerezendemarques** [comment] 2021-02-18 17:35
If I cat the archives archives.json and archives.log com | grep wazuhtrusted or guardydutty nothing appears and are the bucket names in the wazuh configuration.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 17:37
If I cat the archives archives.json and archives.log com | grep wazuhtrusted or guardydutty nothing appears and are the bucket names in the wazuh configuration.

**Comment by guilhermerezendemarques** [comment] 2021-02-18 18:10
I'm used this version docker-compose image 4.11, it's bug?

**Comment by guilhermerezendemarques** [comment] 2021-02-18 19:06
I reinstalled wazuh and received error.

2021/02/18 19:05:26 wazuh-modulesd:aws-s3[5226] wm_aws.c:396 at wm_aws_run_s3(): WARNING: Bucket:  -  Returned exit code 6
ERROR: Unable to create SQLite DB: database is locked

**Comment by CarlosRS9** [comment] 2021-02-19 11:49
Wazuh provides rules for the supported AWS services, such as Trusted Advisor, GuardDuty or VPC Logs. You can find and check those rules in `{WAZUH_PATH}/ruleset/rules/0350-amazon_rules.xml`. If you take a look to that file you would find these rules for Trusted Advisor:

```
    <rule id="80480" level="0">
        <if_sid>80200</if_sid>
        <field name="aws.source">trustedadvisor</field>
        <description>AWS Trusted Advisor alert.</description>
        <group>aws_trusted_advisor,</group>
        <options>no_full_log</options>
    </rule>

    <rule id="80481" level="5">
        <if_sid>80480</if_sid>
        <field name="aws.status">ERROR</field>
        <description>AWS Trusted Advisor - [$(aws.uuid)] [$(aws.check-name)]: $(aws.status)</description>
        <group>aws_trusted_advisor,</group>
        <options>no_full_log</options>
    </rule>

    <rule id="80482" level="4">
        <if_sid>80480</if_sid>
        <field name="aws.status">WARN</field>
        <description>AWS Trusted Advisor - [$(aws.uuid)] [$(aws.check-name)]: $(aws.status)</description>
        <group>aws_trusted_advisor,</group>
        <options>no_full_log</options>
    </rule>

    <rule id="80483" level="3">
        <if_sid>80480</if_sid>
        <field name="aws.status">OK</field>
        <description>AWS Trusted Advisor - [$(aws.uuid)] [$(aws.check-name)]: $(aws.status)</description>
        <group>aws_trusted_advisor,</group>
        <options>no_full_log</options>
    </rule>
```

This means for any given Trusted Advisor event (those with `trustedadvisor` as its `aws.source` value) from your Bucket that has status `OK`, `WARN` or `ERROR` an alert will appear in Kibana. If the event doesn't has the status field then it will match with rule `80480` and no alert will be raised as it has al alert level of `0`. GuardDuty, VPC and the rest of the supported AWS services have their rules available in that same file too.


> If I cat the archives archives.json and archives.log com | grep wazuhtrusted or guardydutty nothing appears and are the bucket names in the wazuh configuration.

The name of the buckets are not present in the events, so if you use that `grep wazuhtrusted` or `grep guardydutty` nothing will be shown. You should check those files using a `grep trustedadvisor`, which is the source of the log, but if possible I recommend you to not use any grep at all, so you can see everything inside the archives.json and check if there is something wrong with those events.


> I reinstalled wazuh and received error.
> 
> 2021/02/18 19:05:26 wazuh-modulesd:aws-s3[5226] wm_aws.c:396 at wm_aws_run_s3(): WARNING: Bucket: - Returned exit code 6
> ERROR: Unable to create SQLite DB: database is locked

There is no reason to reinstall Wazuh as it was working fine. If this `database error` still persists then I will need to know what steps you followed to reinstall Wazuh, as it looks like you messed something up with the configuration.

**Comment by CarlosRS9** [comment] 2021-03-30 09:22
@guilhermerezendemarques let me close this issue. Do not hesitate to reopen it in case of any questions or suggestions related to this topic.

Regards.

**Closed** 2021-03-30 09:22 UTC
Labels: aws_integration, community
