### ISSUE TITLE
`Failed to parse file macie` error using AWS s3 integration

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh#15305] opened 2022-11-04 17:39 UTC
|Wazuh version|Component|
|---|---|
| 4.4.0-1 | Wazuh component |

## Description
After the deployment of a development Demo environment we noticed that the classic used AWS integration show the following errors:
```
2022/11/04 05:33:23 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Failed to parse file macie/2021/06/03/01/firehose_macie-1-2022-11-02-02-42-42-e465368f-0b7e-4j62-a2e2-925224farst1: Expecting value: line 1 column 1 (char 0)
2022/11/04 17:07:35 wazuh-modulesd:aws-s3: WARNING: Bucket:  -  Returned exit code 9
```

**Comment by CarlosRS9** [comment] 2022-11-09 15:04
## Status update

After investigating the error by accessing both the DEV environment (`4.4.0`) and the demo environment (`4.3.9`), we have been able to confirm and conclude that this issue is not exclusive to `4.4`, but also happens in `4.3`. Therefore, **it is not a problem related to any of the changes introduced in `4.4`.**


### Tests performed

We have proceeded to locate the problematic logs, exported them and tried to process them in our local test environments. In both cases, `4.3.9` and `4.4.0`, the results are the same. It is not possible to process these files correctly, even though they have been stored in S3 using Firehose, which is one of the requirements imposed by our integration with Macie.

We have been able to confirm that the module is able to correctly process other Macie logs without any problem, so the problem lies in these particular logs.

### Conclusions

We have been able to confirm that the error occurs in both `4.3` and `4.4`, however, the error message is only present in the `4.4` environment. This is due to the bug that was fixed in https://github.com/wazuh/wazuh/pull/12147. In `4.3` by default `skip_on_error` is always set to True. This, together with the fact that debug mode was not enabled in the environment means that the message is ignored and not shown in the ossec.log at all. In `4.4` `skip_on_error` defaults to false and that is why it is indeed failing and the error is being displayed, even with debug mode disabled.



### Pending

Having demonstrated that the root cause are the logs themselves, we must determine the following:

1. Why these files cannot be processed while others with similar structures can.

2. The integrity of the log files as well as their origin in order to conclude whether they really should be able to be processed or whether it is reasonable that the integration fails.

We are working on this.

**Comment by CarlosRS9** [comment] 2022-11-10 10:52
## Status update

The issue has been fixed.

### Cause of the issue

As explained in the previous message, the cause is a bug in the process of replacing `lat` and `lon` values present in `ipGeolocation` fields, introduced in https://github.com/wazuh/wazuh/pull/8672. Specifically, the problem is:

https://github.com/wazuh/wazuh/blob/4f0f1934dc9c32dda06a8c05a2540a626f54e9fc/wodles/aws/aws_s3.py#L2180-L2181

If a pattern with `lat` and `lon` is found, it's replaced by converting it to float to avoid values not compatible with the json format. The problem is that this conversion affects the length of the event, reducing it. The `json_event_generator` function uses this length to determine when one json line ends and the next one begins. This bug caused the length of the modified json to be used on the original json, resulting in an incomplete json when splitting it.

The fix applied make sure that the `json_index` is applied on the already modified data, not on the original data.

### Why the error was not detected during manual testing

Unfortunately the logs we had available for testing did not have the necessary fields to cause this error, as it requires specific `lat` and `lon` values, so this error did not occur during our tests.

We have generated new events to be able to test this correctly in the future.


### Tests performed

To test the fix we have uploaded 3 files to our DEV environment. Two of these files have been extracted from the Demo environment, they contain problematic geolocation fields, and were the reason why the integration was failing. The third log also has a valid format, but does not contain a geolocation field. The integration was able to ingest it correctly despite the bug, so this will be our control log.

The logs are stored in `wazuh-aws-wodle-macie/2022/11/10/`.

#### Manual testing before the fix

```
rm -rf /var/ossec/wodles/aws/s3_cloudtrail.db
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-macie -t custom -s 2022-NOV-10 -p dev -d2 | grep -v 'Skipping file'
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2022/11/10
DEBUG: ++ Found new log: 2022/11/10/firehose_macie-1-2021-12-01-00-40-40-with-geolocation-1
ERROR: Failed to parse file 2022/11/10/firehose_macie-1-2021-12-01-00-40-40-with-geolocation-1: Expecting value: line 1 column 1 (char 0)
```

#### Manual testing after the fix
```
/var/ossec/wodles/aws/aws-s3 -b wazuh-aws-wodle-macie -t custom -s 2022-NOV-10 -p dev -d2 | grep -v 'Skipping file'
DEBUG: +++ Debug mode on - Level: 2
DEBUG: Generating default configuration for retries: mode standard - max_attempts 10
DEBUG: +++ Table does not exist; create
DEBUG: +++ Marker: 2022/11/10
DEBUG: ++ Found new log: 2022/11/10/firehose_macie-1-2021-12-01-00-40-40-with-geolocation-1
DEBUG: ++ Found new log: 2022/11/10/firehose_macie-1-2021-12-01-00-40-40-with-geolocation-2
DEBUG: ++ Found new log: 2022/11/10/firehose_macie-1-2022-02-14-01-20-42-no-geolocation
DEBUG: +++ DB Maintenance
```
We have been able to confirm that the events were correctly sent to analysisd by looking at the archives.log.

**Closed** 2022-11-15 07:29 UTC
Labels: reporter/cicd, team/framework
