### ISSUE TITLE
False positive during FIM scan

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh#4163] opened 2019-10-29 16:21 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| Manager: 3.10.2/Agent: 3.9.1| FIM (syscheck) | Manager/Agent | Packages/Sources | RHEL 6-7 |

There is a FIM alert: `checksum changed` that wrongly appears in some scans, stating that the file's sha256sum and inode has changed, the sha256 gets the previous value of the inode and the inode takes a completely different value. Then on the next scan it shows again, correcting it back to the previous hash and inode. Md5 does not change at all in either. 

It seems relevant that on the scan that causes the alert. It does **not log mtime** for some reason, but then on the second scan that fixes the registered values to the correct ones, it does log mtime correctly. It appears as if by not logging mtime, it is comparing the other variables with the wrong values, comparing sha256's value with the inode's value and triggering the alert.  

As of now, this keeps happening, when it happens, there is always a first wrong alert, and a second one that fixes it with the right values.

**First alert that causes the issue:**  

`{
  "_index": "wazuh-alerts-3.x-2019.10.21",
  "_type": "_doc",
  "_id": "XXXXXXXXX",
  "_score": 1,
  "_source": {
    "cluster": {
      "node": "XXXXXX",
      "name": "XXXXX"
    },
    "syscheck": {
      "uname_after": "XXXXX",
      "inode_before": 3814644,
      "size_after": "2416",
      "gid_after": "4440",
      "sha256_before": "1423cfda2475c4dae006cce6b863b0e16f9733d9cf112d22c4df046ea3b52293",
      "tags": [
        "XXX"
      ],
      "path": "PATH_TO_FILE",
      "sha1_after": "566782300bff8026f4e7ceef9d00234d3c7d5d29",
      "attrs_after": [
        "HIDDEN",
        "NORMAL",
        "READONLY",
        "REPARSE_POINT",
        "SYSTEM",
        "TEMPORARY"
      ],
      "uid_after": "23247",
      "perm_after": "100644",
      "event": "modified",
      "md5_after": "587131bd4a3f312d1a675d58d452af6a",
      "sha256_after": "3814644",
      "inode_after": 1526794945
    },
    "agent": {
      "ip": "XXXXX",
      "name": "XXXXXX,
      "id": "XXX",
      "labels": {
        "app": {
          "group": "XX"
        }
      }
    },
    "XXXX": "XXXX",
    "rule": {
      "firedtimes": 1,
      "mail": false,
      "level": 13,
      "pci_dss": [
        "10.2.5"
      ],
      "description": "XXXX",
      "groups": [
        "deg",
        "syscheck"
      ],
      "id": "130013"
    },
    "full_log": "File 'PATH_TO_FILE' checksum changed.\nOld sha256sum was: '1423cfda2475c4dae006cce6b863b0e16f9733d9cf112d22c4df046ea3b52293'\nNew sha256sum is : '3814644'\nOld inode was: '3814644', now it is '1526794945'\n",
    "id": "1571686215.1332457028",
    "timestamp": "2019-10-21T14:30:15.638-0500",
    "manager": {
      "name": "node1"
    },
    "decoder": {
      "name": "syscheck_integrity_changed"
    },
    "input": {
      "type": "log"
    },
    "@timestamp": "2019-10-21T19:30:15.638Z",
    "location": "syscheck"
  },
  "fields": {
    "@timestamp": [
      "2019-10-21T19:30:15.638Z"
    ],
    "timestamp": [
      "2019-10-21T19:30:15.638Z"
    ]
  }
}`

**Second alert that "fixes" the previous mistake:** 

`{
  "_index": "wazuh-alerts-3.x-2019.10.22",
  "_type": "_doc",
  "_id": "XXXXXX",
  "_score": 1,
  "_source": {
    "cluster": {
      "node": "XXXX",
      "name": "XXXX"
    },
    "syscheck": {
      "uname_after": "XXXX",
      "mtime_after": "2018-05-20T00:42:25",
      "inode_before": 1526794945,
      "size_after": "2416",
      "gid_after": "4440",
      "sha256_before": "3814644",
      "tags": [
        "deg"
      ],
      "path": "PATH_TO_FILE",
      "sha1_after": "566782300bff8026f4e7ceef9d00234d3c7d5d29",
      "gname_after": "XXXX",
      "uid_after": "23247",
      "perm_after": "100644",
      "event": "modified",
      "md5_after": "587131bd4a3f312d1a675d58d452af6a",
      "sha256_after": "1423cfda2475c4dae006cce6b863b0e16f9733d9cf112d22c4df046ea3b52293",
      "inode_after": 3814644
    },
    "agent": {
      "ip": "XXXX",
      "name": "XXXX",
      "id": "XXX",
      "labels": {
        "app": {
          "group": "XXX"
        }
      }
    },
    "XXXX": "XXXX",
    "rule": {
      "firedtimes": 1,
      "mail": false,
      "level": 13,
      "pci_dss": [
        "10.2.5"
      ],
      "description": "XXXXX",
      "groups": [
        "deg",
        "syscheck"
      ],
      "id": "130013"
    },
    "full_log": "File 'PATH_TO_FILE' checksum changed.\nOld sha256sum was: '3814644'\nNew sha256sum is : '1423cfda2475c4dae006cce6b863b0e16f9733d9cf112d22c4df046ea3b52293'\nOld inode was: '1526794945', now it is '3814644'\n",
    "id": "1571729744.1351370727",
    "timestamp": "2019-10-22T02:35:44.327-0500",
    "manager": {
      "name": "XXXX"
    },
    "decoder": {
      "name": "syscheck_integrity_changed"
    },
    "input": {
      "type": "log"
    },
    "@timestamp": "2019-10-22T07:35:44.327Z",
    "location": "syscheck"
  },
  "fields": {
    "@timestamp": [
      "2019-10-22T07:35:44.327Z"
    ],
    "syscheck.mtime_after": [
      "2018-05-20T00:42:25.000Z"
    ],
    "timestamp": [
      "2019-10-22T07:35:44.327Z"
    ]
  }
}`

**Comment by vikman90** [comment] 2019-11-28 07:49
Hi @MiguelCasaresRobles.

We have not managed to reproduce this issue. I guess this problem is due to an invalid character in the Syscheck payload, whose fields are colon-separated.

The new version of FIM (#3319) replaces this payload with a JSON message. That will likely solve this problem.

However, I cannot be sure about that until we can reproduce that.

Cheers.

**Comment by jesusjimsa** [comment] 2020-04-27 15:26
We haven't been able to reproduce this issue. We also added a rework of the FIM module in Wazuh 3.12 and it isn't happening in that version, therefore I'm closing this issue.
Feel free to re-open it if it causes any problem again.

**Closed by jesusjimsa** 2020-04-27 15:26 UTC
Labels: bug, core/fim, operations, platform/unix, priority/beta
