### ISSUE TITLE
Add new field in data by input user 

### ISSUE THREAD

**Issue by DyyDOS** [wazuh/wazuh#5686] opened 2020-08-09 14:29 UTC
|Wazuh version|Component|Install type|Install method|Platform|
|3.11.3|Wazuh component| Agent |From Source|Windows|
I want to add a field in db elastic, in item "agent", ex as MAC address, "agent": {
      "ip": "172.10.10.14",
      "name": "nameagent",
      "id": "020",
       "anyfield","testfield"
    },
I think edit code for agent because each info is different, I found section code in file json_extended.c, it has function W_ParseJSON() parse event info to json, i added test code: cJSON_AddStringToObject(agent, "test", "abc");
i was edited file wazuh-template json define field declare, but it not working, can you help me?
Regards!

**Comment by pereyra-m** [comment] 2020-08-10 19:14
Hello @DyyDOS !

This Github issue is related to [this](https://wazuh.slack.com/archives/C0A933R8E/p1596963947121000) conversation in Slack. I'll reproduce the answer here:

You may be needing to add **labels** to every agent. This allows you to assign new, specific and static information without touching the source code.

As we can see in the documentation about [Agent labels](https://documentation.wazuh.com/3.13/user-manual/capabilities/labels.html), you can add this fields in two ways:

- Locally in every agent, modifying the **ossec.conf**  file

```
<labels>
  <label key="network.mac">02:42:ac:11:00:02</label>
</labels>
```

- Remotely at manager level, using [Centralized configuration](https://documentation.wazuh.com/3.13/user-manual/reference/centralized-configuration.html), modifying the **agent.conf**  file. This will push the information to the agents

```
<agent_config name="agent_name">
  <labels>
    <label key="network.mac">02:42:ac:11:00:02</label>
  </labels>
</agent_config>
```

Now, the alerts will have these extra fields you added.
Tell me if you were able to use this feature!

Regards.

**Comment by chemamartinez** [comment] 2020-08-13 12:17
Closing this issue since it is a question solved in the slack community channel.

Please, @DyyDOS, don't hesitate to reopen it if you want to report us any bug or feature request.

Best regards.

**Closed by chemamartinez** 2020-08-13 12:17 UTC
Labels: community
