### ISSUE TITLE
Wazuh 2.0 - kibana plugin error; Expected [5.3.0]; found [5.2.2]

### ISSUE THREAD

**Issue by magenx** [wazuh/wazuh#93] opened 2017-03-28 16:07 UTC
i know you will fix it , but anyway i was trying to test and here is the error:
```
[root@centos]# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 16620060 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.3.0]; found [5.2.2]"
```

how this plugin versioning/upgrade will work later, if all ELK stack will be upgraded will it hang if your plugin is outdated?

**Comment by snaow** [comment] 2017-03-28 16:24
Hi @magenx,

Thanks for your feedback!
As you could imagine, there is a new version of the entire Elastic Stack, we are in progress of review Wazuh App compatibility with new Kibana version 5.3.0, once we test it, we will release the new version and upload it to our public repositories.

One funny note is Elastic guys did not release the new version yet ([Kibana download page](https://www.elastic.co/downloads/kibana)).

In the meantime, you could downgrade your cluster to 5.2.2 version:

`yum install kibana-5.2.2`
`apt-get install kibana=5.2.2`

Install the App using the desired version:
`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0-5.2.2.zip`

We are studying to lock Wazuh installation to a certain Elastic Stack version, what do you think?

Thanks again for the feedback, best regards,
Pedro 'snaow' Sanchez.

**Comment by magenx** [comment] 2017-03-28 17:48
probably they have packages released first, but then updated their page.
the problem is that i have interactive Wazuh 2.0 stack installation into Magento webstack,
with yum-cron upgrades enabled.

if you say it will work with specific version only - then ok, i will lock these packages.
just want to make sure how it will work

**Comment by snaow** [comment] 2017-03-29 08:32
Hi @magenx,

We will try to keep updated Wazuh App to work with latest Kibana version, but there are cases that the process of adapting the new version could take some days (in days case it was a few hours).

In your case if you have some stack/cluster integration you could consider to lock versions.

Wazuh App 2.0 working with Kibana 5.3.0, check latest [commit ](https://github.com/wazuh/wazuh-kibana-app/commit/0d70f727e6bcda4f772d33254db22854b7d53d95) for details.

Package link
https://packages.wazuh.com/wazuhapp/wazuhapp-2.0-5.3.0.zip

Plugin installation
`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0-5.3.0.zip`

Best regards,
Pedro Sanchez.

**Comment by magenx** [comment] 2017-03-29 10:05
correct app file name
wazuhapp-2.0_5.3.0.zip
with underscore


testing

**Comment by snaow** [comment] 2017-03-29 10:31
Corrected @magenx !! Thanks! My mistake.

**Comment by magenx** [comment] 2017-03-29 17:24
one more little issue: 
api confugration script must change ip address too.

**Comment by goodccs** [comment] 2017-05-08 18:06
i upgrade my system debian 8.7 to 8.8 and kibana upgrade 5.3 to 5.4 and Menu Wazuh no show, how can restore again?

**Comment by alberpilot** [comment] 2017-05-08 19:09
Hello @goodccs

  If the update has occurs, please retry the step:

`/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip`

As soon as Kibana launch a release, we try to update our Wazuh App. In this case, the app is able to use with the new version of kibana. 

Thanks for trying and let us know if it works. 

Best regards, 
Alberto R.

**Comment by goodccs** [comment] 2017-05-09 15:15
Hello @alberpilot 

I followed the steps indicated, too systemctl daemon-reload and systemctl restart kibana.service, i not sure what fail after update but it works now thanks

**Comment by alberpilot** [comment] 2017-05-09 15:27
Hello @goodccs 

  Great news. The cause: when you perform an "upgrade" of system the version of Kibana (Elasticsearch and Logstash too), if Kibana has any new version, it will be updated. But the WazuhApp is not updated automaticly in a "upgrade". We are working at this issue, we want to design an automatic process in order to have WazuhApp updated when a Kibana upgrade occurs. 

Best regards,

**Comment by warunac** [comment] 2017-06-27 23:27
Wazuh - Kibana App Installation for Kibana version 5.4.2	
/usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-2.0_5.4.2.zip
refer 
https://github.com/wazuh/wazuh-kibana-app

**Comment by magenx** [comment] 2017-09-12 09:02
again this error:
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.0]; found [5.5.2]"

and there is no package:
https://packages.wazuh.com/wazuhapp/wazuhapp-2.1.0_5.6.0.zip
etc...

**Comment by malbarral** [comment] 2017-09-12 09:56
Hello @magenx,

We are working on it. It will be available soon.

Best regards,
Manuel

**Comment by lumhi** [comment] 2017-09-14 10:36
Manuel,

Is there any update on the update?

Regards
Eoin

**Comment by malbarral** [comment] 2017-09-14 13:23
Hello all,

Wazuh Kibana App supports Kibana 5.6.0. The package is available here: https://packages.wazuh.com/wazuhapp/wazuhapp.zip

Thank you for your patience,
Manuel

**Comment by mrevros** [comment] 2017-11-09 12:18
Hi All,

I have this error
"Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.4]; found [5.6.3]"  Any fix near future?

Thanks

**Comment by havidarou** [comment] 2017-11-09 14:17
Hi @mrevros we are working on it.

Regards.

**Comment by suyashjain** [comment] 2017-11-10 07:16
Hi @havidarou ,

I am also facing the same issue

# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Transferring 4458996 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Extracting plugin archive
Extraction complete
Plugin installation was unsuccessful due to error "Incorrect Kibana version in plugin [wazuh]. Expected [5.6.4]; found [5.6.3]"

wazuh-manager => wazuh-manager-2.1.1-1.el6.x86_64
wazuh-api => wazuh-api-2.1.1-1.el6.x86_64
rpm -q kibana => kibana-5.6.4-1.x86_64

Hoping the issue could be solved on earliest.

**Comment by havidarou** [comment] 2017-11-13 11:15
Hi, 

you can now download the app for Kibana 5.6.4

Please refer to links in the repo's README.

Regards.

**Closed by havidarou** 2017-11-13 11:15 UTC

**Comment by tekletade** [comment] 2019-12-03 07:13
![hurry](https://user-images.githubusercontent.com/16237160/70028327-6bcbbe80-15b5-11ea-92aa-99bb196368d1.jpg)
